Napi::TypeError
TypeError Napi::TypeError::New(napi_env env, const char *message)
References Napi::Error::New.
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Database::Configure, node_sqlite3::Database::Database, Napi::ObjectWrap< T >::OnCalledAsFunction, node_sqlite3::Statement::Statement, Napi::ObjectWrap< Backup >::StaticMethod.
TypeError Napi::TypeError::New(napi_env env, const std::string &message)
References Napi::Error::New.
Napi::TypeError::TypeError()
Napi::TypeError::TypeError(napi_env env, napi_value value)