Napi::Number
Number Napi::Number::New(napi_env env, double value)
Node-API environment
References NAPI_THROW_IF_FAILED, Number.
Referenced by node_sqlite3::Statement::AsyncEach, node_sqlite3::Database::Database, Napi::details::vf_number< T >::From, node_sqlite3::Backup::PageCountGetter, node_sqlite3::Database::ProfileCallback, node_sqlite3::Backup::RemainingGetter, node_sqlite3::Statement::RowToJS, node_sqlite3::Database::UpdateCallback.
void Napi::Number::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::Number::Number()
Creates a new empty Number instance.
Referenced by New.
Napi::Number::Number(napi_env env, napi_value value)
Wraps a Node-API value primitive.
Napi::Number::operator int32_t() const
Converts a Number value to a 32-bit signed integer value.
Napi::Number::operator uint32_t() const
Converts a Number value to a 32-bit unsigned integer value.
Napi::Number::operator int64_t() const
Converts a Number value to a 64-bit signed integer value.
Napi::Number::operator float() const
Converts a Number value to a 32-bit floating-point value.
Napi::Number::operator double() const
Converts a Number value to a 64-bit floating-point value.
int32_t Napi::Number::Int32Value() const
Converts a Number value to a 32-bit signed integer value.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::Bind, node_sqlite3::Statement::BindParameter, node_sqlite3::Backup::GetRetryErrors, OtherIsInt.
uint32_t Napi::Number::Uint32Value() const
Converts a Number value to a 32-bit unsigned integer value.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
int64_t Napi::Number::Int64Value() const
Converts a Number value to a 64-bit signed integer value.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
float Napi::Number::FloatValue() const
Converts a Number value to a 32-bit floating-point value.
References DoubleValue.
double Napi::Number::DoubleValue() const
Converts a Number value to a 64-bit floating-point value.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::Bind, node_sqlite3::Statement::BindParameter, FloatValue, OtherIsInt.