Napi::Buffer
Buffer< T > Napi::Buffer< T >::New(napi_env env, size_t length)
References NAPI_THROW_IF_FAILED.
Buffer< T > Napi::Buffer< T >::New(napi_env env, T *data, size_t length)
References NAPI_THROW_IF_FAILED.
Buffer< T > Napi::Buffer< T >::New(napi_env env, T *data, size_t length, Finalizer finalizeCallback)
References NAPI_THROW_IF_FAILED.
Buffer< T > Napi::Buffer< T >::New(napi_env env, T *data, size_t length, Finalizer finalizeCallback, Hint *finalizeHint)
References NAPI_THROW_IF_FAILED.
Buffer< T > Napi::Buffer< T >::NewOrCopy(napi_env env, T *data, size_t length)
References Napi::Buffer< T >::Copy, Napi::details::napi_no_external_buffers_allowed, NAPI_THROW_IF_FAILED.
Buffer< T > Napi::Buffer< T >::NewOrCopy(napi_env env, T *data, size_t length, Finalizer finalizeCallback)
References Napi::Buffer< T >::Copy, Napi::details::napi_no_external_buffers_allowed, NAPI_THROW_IF_FAILED, Napi::details::FinalizeData< T, Finalizer, Hint >::Wrapper.
Buffer< T > Napi::Buffer< T >::NewOrCopy(napi_env env, T *data, size_t length, Finalizer finalizeCallback, Hint *finalizeHint)
References Napi::Buffer< T >::Copy, Napi::details::napi_no_external_buffers_allowed, NAPI_THROW_IF_FAILED, Napi::details::FinalizeData< T, Finalizer, Hint >::WrapperWithHint.
Buffer< T > Napi::Buffer< T >::Copy(napi_env env, const T *data, size_t length)
References NAPI_THROW_IF_FAILED.
Referenced by Napi::Buffer< T >::NewOrCopy, Napi::Buffer< T >::NewOrCopy, Napi::Buffer< T >::NewOrCopy, node_sqlite3::Statement::RowToJS.
void Napi::Buffer< T >::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::Buffer< T >::Buffer()
Napi::Buffer< T >::Buffer(napi_env env, napi_value value)
size_t Napi::Buffer< T >::Length() const
Referenced by node_sqlite3::Statement::BindParameter.
T * Napi::Buffer< T >::Data() const
References Napi::TypedArrayOf< T >::Data.
Referenced by node_sqlite3::Statement::BindParameter.