Napi::Symbol
Symbol Napi::Symbol::New(napi_env env, const char *description=nullptr)
Node-API environment
References Napi::String::New, New.
Referenced by New, New, New.
Symbol Napi::Symbol::New(napi_env env, const std::string &description)
Node-API environment
References Napi::String::New, New.
Symbol Napi::Symbol::New(napi_env env, String description)
Node-API environment
References New.
Symbol Napi::Symbol::New(napi_env env, napi_value description)
Node-API environment
References NAPI_THROW_IF_FAILED, Symbol.
MaybeOrValue< Symbol > Napi::Symbol::WellKnown(napi_env, const std::string &name)
Get a public Symbol (e.g. Symbol.iterator).
References Napi::Value::As, Napi::Object::Get, Napi::Env::Global, Napi::Just, Napi::Nothing.
MaybeOrValue< Symbol > Napi::Symbol::For(napi_env env, const std::string &description)
References For, Napi::String::New.
Referenced by For, For, For.
MaybeOrValue< Symbol > Napi::Symbol::For(napi_env env, const char *description)
References For, Napi::String::New.
MaybeOrValue< Symbol > Napi::Symbol::For(napi_env env, String description)
References For.
MaybeOrValue< Symbol > Napi::Symbol::For(napi_env env, napi_value description)
References Napi::Value::As, Napi::Function::Call, Napi::Object::Get, Napi::Env::Global, Napi::Just, Napi::Nothing.
void Napi::Symbol::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::Symbol::Symbol()
Creates a new empty Symbol instance.
Referenced by New.
Napi::Symbol::Symbol(napi_env env, napi_value value)
Wraps a Node-API value primitive.