Napi::PropertyDescriptor
using Napi::PropertyDescriptor::GetterCallback = Napi::Value (*)(const Napi::CallbackInfo& info)
using Napi::PropertyDescriptor::SetterCallback = void (*)(const Napi::CallbackInfo& info)
napi_property_descriptor Napi::PropertyDescriptor::_desc
static PropertyDescriptor Napi::PropertyDescriptor::Accessor(const char *utf8name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)
Referenced by Accessor, Accessor, Accessor.
static PropertyDescriptor Napi::PropertyDescriptor::Accessor(const std::string &utf8name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Accessor(napi_value name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Accessor(Name name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Accessor(const char *utf8name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Accessor(const std::string &utf8name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Accessor(napi_value name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Accessor(Name name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Function(const char *utf8name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)
Referenced by Function.
static PropertyDescriptor Napi::PropertyDescriptor::Function(const std::string &utf8name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Function(napi_value name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)
static PropertyDescriptor Napi::PropertyDescriptor::Function(Name name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)
PropertyDescriptor Napi::PropertyDescriptor::Accessor(const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Napi::details::TemplatedCallback.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(const std::string &utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Accessor.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Name name, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Napi::details::TemplatedCallback.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Napi::details::TemplatedCallback, Napi::details::TemplatedVoidCallback.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(const std::string &utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Accessor.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Name name, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Napi::details::TemplatedCallback, Napi::details::TemplatedVoidCallback.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Napi::Env env, Napi::Object object, const char *utf8name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)
References NAPI_THROW_IF_FAILED, PropertyDescriptor.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Napi::Env env, Napi::Object object, const std::string &utf8name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Accessor.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Napi::Env env, Napi::Object object, Name name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)
References NAPI_THROW_IF_FAILED, PropertyDescriptor.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Napi::Env env, Napi::Object object, const char *utf8name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)
References NAPI_THROW_IF_FAILED, PropertyDescriptor.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Napi::Env env, Napi::Object object, const std::string &utf8name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Accessor.
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Napi::Env env, Napi::Object object, Name name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)
References NAPI_THROW_IF_FAILED, PropertyDescriptor.
PropertyDescriptor Napi::PropertyDescriptor::Function(Napi::Env env, Napi::Object object, const char *utf8name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Napi::Function::New, PropertyDescriptor.
PropertyDescriptor Napi::PropertyDescriptor::Function(Napi::Env env, Napi::Object object, const std::string &utf8name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Function.
PropertyDescriptor Napi::PropertyDescriptor::Function(Napi::Env env, Napi::Object object, Name name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)
References Napi::Function::New, PropertyDescriptor.
PropertyDescriptor Napi::PropertyDescriptor::Value(const char *utf8name, napi_value value, napi_property_attributes attributes=napi_default)
References PropertyDescriptor.
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Database::Database, node_sqlite3::Statement::Statement, Value, Value.
PropertyDescriptor Napi::PropertyDescriptor::Value(const std::string &utf8name, napi_value value, napi_property_attributes attributes=napi_default)
References Value.
PropertyDescriptor Napi::PropertyDescriptor::Value(napi_value name, napi_value value, napi_property_attributes attributes=napi_default)
References PropertyDescriptor.
PropertyDescriptor Napi::PropertyDescriptor::Value(Name name, Napi::Value value, napi_property_attributes attributes=napi_default)
References Value.
Napi::PropertyDescriptor::PropertyDescriptor(napi_property_descriptor desc)
Referenced by Accessor, Accessor, Accessor, Accessor, Function, Function, Value, Value.
Napi::PropertyDescriptor::operator napi_property_descriptor &()
Napi::PropertyDescriptor::operator const napi_property_descriptor &() const
PropertyDescriptor Napi::PropertyDescriptor::Accessor(const char *utf8name, Getter getter, napi_property_attributes attributes, void *)
PropertyDescriptor Napi::PropertyDescriptor::Accessor(const std::string &utf8name, Getter getter, napi_property_attributes attributes, void *data)
PropertyDescriptor Napi::PropertyDescriptor::Accessor(napi_value name, Getter getter, napi_property_attributes attributes, void *)
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Name name, Getter getter, napi_property_attributes attributes, void *data)
PropertyDescriptor Napi::PropertyDescriptor::Accessor(const char *utf8name, Getter getter, Setter setter, napi_property_attributes attributes, void *)
PropertyDescriptor Napi::PropertyDescriptor::Accessor(const std::string &utf8name, Getter getter, Setter setter, napi_property_attributes attributes, void *data)
PropertyDescriptor Napi::PropertyDescriptor::Accessor(napi_value name, Getter getter, Setter setter, napi_property_attributes attributes, void *)
PropertyDescriptor Napi::PropertyDescriptor::Accessor(Name name, Getter getter, Setter setter, napi_property_attributes attributes, void *data)
PropertyDescriptor Napi::PropertyDescriptor::Function(const char *utf8name, Callable cb, napi_property_attributes attributes, void *)
PropertyDescriptor Napi::PropertyDescriptor::Function(const std::string &utf8name, Callable cb, napi_property_attributes attributes, void *data)
PropertyDescriptor Napi::PropertyDescriptor::Function(napi_value name, Callable cb, napi_property_attributes attributes, void *)
PropertyDescriptor Napi::PropertyDescriptor::Function(Name name, Callable cb, napi_property_attributes attributes, void *data)