Napi::String
String Napi::String::New(napi_env env, const std::string &value)
Node-API environment
References New.
Referenced by node_sqlite3::Statement::BindParameter, node_sqlite3::Backup::CleanQueue, node_sqlite3::Statement::CleanQueue, node_sqlite3::Database::Configure, node_sqlite3::Backup::Error, node_sqlite3::Statement::Error, Napi::Symbol::For, Napi::Symbol::For, Napi::details::vf_utf16_charp::From, Napi::details::vf_utf16_string::From, Napi::details::vf_utf8_charp::From, Napi::details::vf_utf8_string::From, New, New, Napi::Symbol::New, Napi::Symbol::New, node_sqlite3::Database::Process, node_sqlite3::Database::ProfileCallback, node_sqlite3::Statement::RowToJS, Napi::Env::RunScript, node_sqlite3::Database::Schedule, StringConcat, node_sqlite3::Database::TraceCallback, node_sqlite3::Database::UpdateCallback.
String Napi::String::New(napi_env env, const std::u16string &value)
Node-API environment
References New.
String Napi::String::New(napi_env env, const char *value)
Node-API environment
References NAPI_THROW_IF_FAILED, String.
String Napi::String::New(napi_env env, const char16_t *value)
Node-API environment
References NAPI_THROW_IF_FAILED, String.
String Napi::String::New(napi_env env, const char *value, size_t length)
Node-API environment
Creates a new String value from a UTF-8 encoded C string with specified length.
References NAPI_THROW_IF_FAILED, String.
String Napi::String::New(napi_env env, const char16_t *value, size_t length)
Node-API environment
Creates a new String value from a UTF-16 encoded C string with specified length.
References NAPI_THROW_IF_FAILED, String.
String Napi::String::From(napi_env env, const T &value)
Creates a new String based on the original object's type. value may be any of: const char* (encoded using UTF-8, null-terminated) const char16_t* (encoded using UTF-16-LE, null-terminated) std::string (encoded using UTF-8) std::u16string
Referenced by Napi::Error::Value.
void Napi::String::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::String::String()
Creates a new empty String instance.
Referenced by New, New, New, New.
Napi::String::String(napi_env env, napi_value value)
Wraps a Node-API value primitive.
Napi::String::operator std::string() const
Converts a String value to a UTF-8 encoded C++ string.
Napi::String::operator std::u16string() const
Converts a String value to a UTF-16 encoded C++ string.
std::string Napi::String::Utf8Value() const
Converts a String value to a UTF-8 encoded C++ string.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Statement::Statement, StringConcat.
std::u16string Napi::String::Utf16Value() const
Converts a String value to a UTF-16 encoded C++ string.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED, NAPI_WIDE_TEXT.