Napi::Error
using Napi::Error::create_error_fn = napi_status (*)(napi_env envb, napi_value code, napi_value msg, napi_value* result)
!cond INTERNAL
std::string Napi::Error::_message
Error Napi::Error::New(napi_env env)
References Error, NAPI_FATAL_IF_FAILED.
Referenced by node_sqlite3::Database::Interrupt, New, New, Napi::RangeError::New, Napi::RangeError::New, Napi::TypeError::New, Napi::TypeError::New, node_sqlite3::Backup::RetryErrorSetter, ThrowAsJavaScriptException.
Error Napi::Error::New(napi_env env, const char *message)
References New.
Error Napi::Error::New(napi_env env, const std::string &message)
References New.
NAPI_NO_RETURN void Napi::Error::Fatal(const char *location, const char *message)
Napi::Error::Error()
Referenced by New.
Napi::Error::Error(napi_env env, napi_value value)
References Napi::Reference< Object >::_ref, Napi::Value::From, NAPI_FATAL_IF_FAILED.
Napi::Error::Error(Error &&other)
Error & Napi::Error::operator=(Error &&other)
Napi::Error::Error(const Error &)
Error & Napi::Error::operator=(const Error &)
References Napi::Reference< Object >::_env, Napi::Reference< Object >::_ref, Napi::Reference< T >::Env, NAPI_THROW_IF_FAILED, Napi::Reference< Object >::Reset, Value.
const std::string & Napi::Error::Message() const NAPI_NOEXCEPT
References Napi::Reference< Object >::_env, Napi::Value::As, Napi::ObjectReference::Get.
void Napi::Error::ThrowAsJavaScriptException() const
References Napi::Reference< Object >::_env, Napi::Reference< Object >::IsEmpty, NAPI_FATAL_IF_FAILED, New, Value.
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Database::Configure, node_sqlite3::Database::Database, node_sqlite3::Database::Interrupt, node_sqlite3::Backup::RetryErrorSetter, node_sqlite3::Statement::Statement, Napi::details::WrapCallback, Napi::details::WrapVoidCallback.
Object Napi::Error::Value() const
References Napi::Reference< Object >::_env, Napi::Reference< Object >::_ref, Napi::String::From, NAPI_THROW_IF_FAILED.
Referenced by operator=, ThrowAsJavaScriptException.
TError Napi::Error::New(napi_env env, const char *message, size_t length, create_error_fn create_error)
References NAPI_THROW_IF_FAILED.
const char * Napi::Error::ERROR_WRAP_VALUE() NAPI_NOEXCEPT
!endcond