node_sqlite3::Database
typedef void(* node_sqlite3::Database::Work_Callback) (Baton *baton))(Baton *baton)
typedef Async<std::string, Database> node_sqlite3::Database::AsyncTrace
typedef Async<ProfileInfo, Database> node_sqlite3::Database::AsyncProfile
typedef Async<UpdateInfo, Database> node_sqlite3::Database::AsyncUpdate
Napi::FunctionReference Database::constructor
Referenced by HasInstance, Init.
friend class Statement
friend class Backup
sqlite3* node_sqlite3::Database::_handle
Referenced by node_sqlite3::Statement::Bind, ~Database.
bool node_sqlite3::Database::open
Referenced by IsOpen, Process, Schedule, node_sqlite3::Backup::Work_BeginInitialize, node_sqlite3::Statement::Work_BeginPrepare, ~Database.
bool node_sqlite3::Database::closing
bool node_sqlite3::Database::locked
Referenced by IsLocked, Process, Schedule.
unsigned int node_sqlite3::Database::pending
Referenced by gyp.input.ParallelState.LoadTargetBuildFileCallback, Process, Schedule, node_sqlite3::Backup::Work_BeginInitialize, node_sqlite3::Statement::Work_BeginPrepare.
bool node_sqlite3::Database::serialize
Referenced by Schedule.
std::queue<Call*> node_sqlite3::Database::queue
Referenced by Process, Schedule.
AsyncTrace* node_sqlite3::Database::debug_trace
Referenced by RemoveCallbacks, TraceCallback.
AsyncProfile* node_sqlite3::Database::debug_profile
Referenced by ProfileCallback, RemoveCallbacks.
AsyncUpdate* node_sqlite3::Database::update_event
Referenced by RemoveCallbacks, UpdateCallback.
Napi::Object Database::Init(Napi::Env env, Napi::Object exports)
References Configure, constructor, Napi::ObjectWrap< Database >::DefineClass, Napi::InstanceWrap< Database >::InstanceAccessor, Napi::InstanceWrap< Database >::InstanceMethod, Interrupt, Parallelize, Napi::Persistent, Serialize, Napi::Object::Set, Napi::Reference< T >::SuppressDestruct, Wait.
static bool node_sqlite3::Database::HasInstance(Napi::Value val)
References Napi::Value::As, constructor, Napi::Value::Env, Napi::Object::InstanceOf, Napi::Value::IsObject, Napi::Reference< T >::Value.
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Statement::Statement.
bool node_sqlite3::Database::IsOpen()
References open.
Referenced by node_sqlite3::Backup::InitializeBaton::~InitializeBaton, node_sqlite3::Statement::PrepareBaton::~PrepareBaton.
bool node_sqlite3::Database::IsLocked()
References locked.
Referenced by node_sqlite3::Backup::InitializeBaton::~InitializeBaton, node_sqlite3::Statement::PrepareBaton::~PrepareBaton.
Database::Database(const Napi::CallbackInfo &info)
References Napi::Value::As, Napi::CallbackInfo::Env, Napi::CallbackInfo::Length, Napi::Number::New, Napi::TypeError::New, OtherIsInt, Napi::CallbackInfo::This, Napi::Error::ThrowAsJavaScriptException, Napi::PropertyDescriptor::Value.
node_sqlite3::Database::~Database()
References _handle, open, RemoveCallbacks.
node_sqlite3::Database::WORK_DEFINITION(Open)
node_sqlite3::Database::WORK_DEFINITION(Exec)
node_sqlite3::Database::WORK_DEFINITION(Close)
node_sqlite3::Database::WORK_DEFINITION(LoadExtension)
void Database::Schedule(Work_Callback callback, Baton *baton, bool exclusive=false)
References node_sqlite3::Database::Baton::callback, EMIT_EVENT, Napi::Reference< Object >::Env, EXCEPTION, IS_FUNCTION, locked, Napi::String::New, open, pending, queue, serialize, TRY_CATCH_CALL, Napi::Reference< T >::Value, Napi::Reference< Object >::Value.
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Statement::Statement.
void Database::Process()
References EMIT_EVENT, Napi::Reference< Object >::Env, EXCEPTION, node_sqlite3::Database::Call::exclusive, IS_FUNCTION, locked, Napi::String::New, open, pending, queue, TRY_CATCH_CALL, Napi::Reference< Object >::Value, Napi::Value::Value.
Napi::Value Database::Wait(const Napi::CallbackInfo &info)
References Napi::CallbackInfo::Env, OPTIONAL_ARGUMENT_FUNCTION, Napi::CallbackInfo::This, Work_Wait.
Referenced by Init.
Napi::Value Database::Serialize(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, OPTIONAL_ARGUMENT_FUNCTION, Napi::CallbackInfo::This, TRY_CATCH_CALL.
Referenced by Init.
Napi::Value Database::Parallelize(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, OPTIONAL_ARGUMENT_FUNCTION, Napi::CallbackInfo::This, TRY_CATCH_CALL.
Referenced by Init.
Napi::Value Database::Configure(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, Napi::String::New, Napi::TypeError::New, RegisterProfileCallback, RegisterTraceCallback, RegisterUpdateCallback, REQUIRE_ARGUMENTS, SetBusyTimeout, SetLimit, StringConcat, Napi::CallbackInfo::This, Napi::Error::ThrowAsJavaScriptException.
Referenced by Init.
Napi::Value Database::Interrupt(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, Napi::Error::New, Napi::CallbackInfo::This, Napi::Error::ThrowAsJavaScriptException.
Referenced by Init.
void Database::RemoveCallbacks()
References debug_profile, debug_trace, Async< Item, Parent >::finish, update_event.
Referenced by ~Database.
void Database::Work_Wait(Baton *baton)
References IS_FUNCTION, TRY_CATCH_CALL, Napi::Value::Value.
Referenced by Wait.
void Database::SetBusyTimeout(Baton *baton)
Referenced by Configure.
void Database::SetLimit(Baton *baton)
Referenced by Configure.
void Database::RegisterTraceCallback(Baton *baton)
References TraceCallback.
Referenced by Configure.
void Database::TraceCallback(void *db, const char *sql)
References debug_trace, Async< Item, Parent >::send.
Referenced by RegisterTraceCallback.
void Database::TraceCallback(Database *db, std::string *sql)
References EMIT_EVENT, Napi::Reference< T >::Env, Napi::String::New, Napi::Reference< T >::Value.
void Database::RegisterProfileCallback(Baton *baton)
References ProfileCallback.
Referenced by Configure.
void Database::ProfileCallback(void *db, const char *sql, sqlite3_uint64 nsecs)
References debug_profile, Async< Item, Parent >::send.
Referenced by RegisterProfileCallback.
void Database::ProfileCallback(Database *db, ProfileInfo *info)
References EMIT_EVENT, Napi::Reference< T >::Env, Napi::Number::New, Napi::String::New, Napi::Reference< T >::Value.
void Database::RegisterUpdateCallback(Baton *baton)
References UpdateCallback.
Referenced by Configure.
void Database::UpdateCallback(void *db, int type, const char *database, const char *table, sqlite3_int64 rowid)
References Async< Item, Parent >::send, update_event.
Referenced by RegisterUpdateCallback.
void Database::UpdateCallback(Database *db, UpdateInfo *info)
References EMIT_EVENT, Napi::Reference< T >::Env, Napi::Number::New, Napi::String::New, sqlite_authorizer_string, Napi::Reference< T >::Value.