Napi::Reference
napi_env Napi::Reference< T >::_env
!cond INTERNAL
Referenced by Napi::Reference< T >::Reference.
napi_ref Napi::Reference< T >::_ref
Referenced by Napi::Reference< T >::Reference.
bool Napi::Reference< T >::_suppressDestruct
!endcond
Reference< T > Napi::Reference< T >::New(const T &value, uint32_t initialRefcount=0)
References Napi::Reference< T >::Env, NAPI_THROW_IF_FAILED.
Referenced by Napi::Persistent, Napi::Persistent, Napi::Persistent, Napi::Weak, Napi::Weak, Napi::Weak.
Napi::Reference< T >::Reference()
Napi::Reference< T >::Reference(napi_env env, napi_ref ref)
Napi::Reference< T >::~Reference()
Napi::Reference< T >::Reference(Reference< T > &&other)
Reference< T > & Napi::Reference< T >::operator=(Reference< T > &&other)
Napi::Reference< T >::operator napi_ref() const
bool Napi::Reference< T >::operator==(const Reference< T > &other) const
References Napi::Value::StrictEquals, Napi::Reference< T >::Value.
bool Napi::Reference< T >::operator!=(const Reference< T > &other) const
Napi::Env Napi::Reference< T >::Env() const
Referenced by node_sqlite3::Statement::Async::Async, node_sqlite3::Statement::AsyncEach, node_sqlite3::Statement::Error, Napi::Reference< T >::New, Napi::Error::operator=, node_sqlite3::Database::ProfileCallback, node_sqlite3::Database::TraceCallback, node_sqlite3::Database::UpdateCallback, node_sqlite3::Backup::Work_BeginInitialize, node_sqlite3::Statement::Work_BeginPrepare, node_sqlite3::Backup::Baton::~Baton, node_sqlite3::Database::Baton::~Baton, node_sqlite3::Statement::Baton::~Baton.
bool Napi::Reference< T >::IsEmpty() const
T Napi::Reference< T >::Value() const
References NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Backup::Error, node_sqlite3::Statement::Error, node_sqlite3::Statement::Finalize_, node_sqlite3::Backup::GetRetryErrors, node_sqlite3::Database::HasInstance, Napi::Reference< T >::operator==, node_sqlite3::Database::ProfileCallback, Napi::Reference< T >::Reference, node_sqlite3::Database::Schedule, node_sqlite3::Database::TraceCallback, node_sqlite3::Database::UpdateCallback.
uint32_t Napi::Reference< T >::Ref() const
References NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::Async::Async, node_sqlite3::Backup::Backup, node_sqlite3::Backup::Baton::Baton, node_sqlite3::Database::Baton::Baton, node_sqlite3::Statement::Baton::Baton, node_sqlite3::Backup::InitializeBaton::InitializeBaton, node_sqlite3::Statement::PrepareBaton::PrepareBaton, node_sqlite3::Statement::Statement.
uint32_t Napi::Reference< T >::Unref() const
References NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::Finalize_, node_sqlite3::Backup::FinishAll, node_sqlite3::Statement::Async::~Async, node_sqlite3::Backup::Baton::~Baton, node_sqlite3::Database::Baton::~Baton, node_sqlite3::Statement::Baton::~Baton, node_sqlite3::Backup::InitializeBaton::~InitializeBaton, node_sqlite3::Statement::PrepareBaton::~PrepareBaton.
void Napi::Reference< T >::Reset()
References NAPI_THROW_IF_FAILED_VOID.
Referenced by node_sqlite3::Backup::Baton::Baton, node_sqlite3::Database::Baton::Baton, node_sqlite3::Statement::Baton::Baton, node_sqlite3::Statement::Async::~Async, node_sqlite3::Backup::~Backup, node_sqlite3::Backup::Baton::~Baton, node_sqlite3::Database::Baton::~Baton, node_sqlite3::Statement::Baton::~Baton, node_sqlite3::Statement::EachBaton::~EachBaton.
void Napi::Reference< T >::Reset(const T &value, uint32_t refcount=0)
References NAPI_THROW_IF_FAILED_VOID.
void Napi::Reference< T >::SuppressDestruct()
Referenced by node_sqlite3::Database::Init.
Napi::Reference< T >::Reference(const Reference< T > &)
References Napi::Reference< T >::_env, Napi::Reference< T >::_ref, NAPI_FATAL_IF_FAILED, Napi::Reference< T >::Value.