Napi::Name
void Napi::Name::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::Name::Name()
Creates a new empty Name instance.
Referenced by gyp.xcodeproj_file.XCObject.__repr__, gyp.xcodeproj_file.XCObject.Comment, gyp.xcodeproj_file.XCHierarchicalElement.Compare, gyp.xcodeproj_file.XCHierarchicalElement.CompareRootGroup, gyp.xcodeproj_file.XCObject.Hashables, gyp.xcodeproj_file.PBXGroup.TakeOverOnlyChild.
Napi::Name::Name(napi_env env, napi_value value)
Wraps a Node-API value primitive.
Referenced by gyp.xcodeproj_file.XCObject.__repr__, gyp.xcodeproj_file.XCObject.Comment, gyp.xcodeproj_file.XCHierarchicalElement.Compare, gyp.xcodeproj_file.XCHierarchicalElement.CompareRootGroup, gyp.xcodeproj_file.XCObject.Hashables, gyp.xcodeproj_file.PBXGroup.TakeOverOnlyChild.