Napi::Function
using Napi::Function::VoidCallback = void (*)(const CallbackInfo& info)
using Napi::Function::Callback = Value (*)(const CallbackInfo& info)
Function Napi::Function::New(napi_env env, const char *utf8name=nullptr, void *data=nullptr)
Referenced by Napi::PropertyDescriptor::Function, Napi::PropertyDescriptor::Function, New, New, New, New, Napi::FunctionReference::New, Napi::FunctionReference::New.
static Function Napi::Function::New(napi_env env, const char *utf8name=nullptr, void *data=nullptr)
Function Napi::Function::New(napi_env env, const std::string &utf8name, void *data=nullptr)
References New.
static Function Napi::Function::New(napi_env env, const std::string &utf8name, void *data=nullptr)
Function Napi::Function::New(napi_env env, Callable cb, const char *utf8name=nullptr, void *data=nullptr)
Callable must implement operator() accepting a const CallbackInfo& and return either void or Value.
References Napi::CreateFunction, Function, NAPI_THROW_IF_FAILED.
Function Napi::Function::New(napi_env env, Callable cb, const std::string &utf8name, void *data=nullptr)
Callable must implement operator() accepting a const CallbackInfo& and return either void or Value.
References New.
void Napi::Function::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::Function::Function()
Referenced by Napi::ObjectWrap< Backup >::Finalize, New.
Napi::Function::Function(napi_env env, napi_value value)
MaybeOrValue< Value > Napi::Function::operator()(const std::initializer_list< napi_value > &args) const
References Call, Napi::Value::Env.
MaybeOrValue< Value > Napi::Function::Call(const std::initializer_list< napi_value > &args) const
References Call, Napi::Value::Env.
Referenced by Call, Call, Call, Call, Call, Call, Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::Symbol::For, operator().
MaybeOrValue< Value > Napi::Function::Call(const std::vector< napi_value > &args) const
References Call, Napi::Value::Env.
MaybeOrValue< Value > Napi::Function::Call(const std::vector< Value > &args) const
References Call, Napi::Value::Env.
MaybeOrValue< Value > Napi::Function::Call(size_t argc, const napi_value *args) const
References Call, Napi::Value::Env.
MaybeOrValue< Value > Napi::Function::Call(napi_value recv, const std::initializer_list< napi_value > &args) const
References Call.
MaybeOrValue< Value > Napi::Function::Call(napi_value recv, const std::vector< napi_value > &args) const
References Call.
MaybeOrValue< Value > Napi::Function::Call(napi_value recv, const std::vector< Value > &args) const
References Call.
MaybeOrValue< Value > Napi::Function::Call(napi_value recv, size_t argc, const napi_value *args) const
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< Value > Napi::Function::MakeCallback(napi_value recv, const std::initializer_list< napi_value > &args, napi_async_context context=nullptr) const
References MakeCallback.
Referenced by MakeCallback, MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback.
MaybeOrValue< Value > Napi::Function::MakeCallback(napi_value recv, const std::vector< napi_value > &args, napi_async_context context=nullptr) const
References MakeCallback.
MaybeOrValue< Value > Napi::Function::MakeCallback(napi_value recv, size_t argc, const napi_value *args, napi_async_context context=nullptr) const
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< Object > Napi::Function::New(const std::initializer_list< napi_value > &args) const
References New.
MaybeOrValue< Object > Napi::Function::New(const std::vector< napi_value > &args) const
References New.
MaybeOrValue< Object > Napi::Function::New(size_t argc, const napi_value *args) const
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.