Async
typedef void(* Async< Item, Parent >::Callback) (Parent *parent, Item *item))(Parent *parent, Item *item)
uv_async_t Async< Item, Parent >::watcher
Referenced by Async< Item, Parent >::Async, Async< Item, Parent >::finish, Async< Item, Parent >::send.
NODE_SQLITE3_MUTEX_t std::vector<Item*> Async< Item, Parent >::data
Referenced by Async< Item, Parent >::add, gyp.input.ParallelState.LoadTargetBuildFileCallback.
Callback Async< Item, Parent >::callback
Referenced by Async< Item, Parent >::listener.
Parent* Async< Item, Parent >::parent
Referenced by gyp.msvs_emulation.MsvsSettings._GetWrapper.__call__, gyp.xcodeproj_file.XCObject.Copy, gyp.xcodeproj_file.PBXBuildFile.Name, gyp.xcodeproj_file.XCConfigurationList.Name, gyp.xcodeproj_file.XCObject.PBXProjectAncestor.
Async< Item, Parent >::Async(Parent *parent_, Callback cb_)
References Async< Item, Parent >::listener, NODE_SQLITE3_MUTEX_INIT, Async< Item, Parent >::watcher.
void Async< Item, Parent >::finish()
References Async< Item, Parent >::close, Async< Item, Parent >::listener, Async< Item, Parent >::watcher.
Referenced by node_sqlite3::Database::RemoveCallbacks.
void Async< Item, Parent >::add(Item *item)
References Async< Item, Parent >::data, NODE_SQLITE3_MUTEX_LOCK, NODE_SQLITE3_MUTEX_UNLOCK.
Referenced by Async< Item, Parent >::send, gyp.common.OrderedSet.update.
void Async< Item, Parent >::send()
References Async< Item, Parent >::watcher.
Referenced by node_sqlite3::Database::ProfileCallback, Async< Item, Parent >::send, node_sqlite3::Database::TraceCallback, node_sqlite3::Database::UpdateCallback.
void Async< Item, Parent >::send(Item *item)
References Async< Item, Parent >::add, Async< Item, Parent >::send.
Async< Item, Parent >::~Async()
References NODE_SQLITE3_MUTEX_DESTROY.
static void Async< Item, Parent >::listener(uv_async_t *handle)
References Async< Item, Parent >::callback, NODE_SQLITE3_MUTEX_LOCK, NODE_SQLITE3_MUTEX_UNLOCK.
Referenced by Async< Item, Parent >::Async, Async< Item, Parent >::finish.
static void Async< Item, Parent >::close(uv_handle_t *handle)
Referenced by Async< Item, Parent >::finish.