node_sqlite3::Backup
typedef void(* node_sqlite3::Backup::Work_Callback) (Baton *baton))(Baton *baton)
Database* node_sqlite3::Backup::db
Referenced by Backup, FinishAll.
sqlite3_backup* node_sqlite3::Backup::_handle
Referenced by FinishSqlite.
sqlite3* node_sqlite3::Backup::_otherDb
Referenced by FinishSqlite.
sqlite3* node_sqlite3::Backup::_destDb
Referenced by FinishSqlite.
bool node_sqlite3::Backup::inited
Referenced by CleanQueue, Process, Schedule.
bool node_sqlite3::Backup::locked
Referenced by Process, Schedule.
bool node_sqlite3::Backup::completed
Referenced by FinishAll.
bool node_sqlite3::Backup::failed
Referenced by FinishAll.
int node_sqlite3::Backup::remaining
int node_sqlite3::Backup::pageCount
bool node_sqlite3::Backup::finished
Referenced by FinishAll, Process, Schedule, ~Backup.
int node_sqlite3::Backup::status
Referenced by Error.
std::string node_sqlite3::Backup::message
Referenced by Error.
std::queue<std::unique_ptr<Call> > node_sqlite3::Backup::queue
Referenced by CleanQueue, Process, Schedule.
Napi::Reference<Array> node_sqlite3::Backup::retryErrors
Referenced by GetRetryErrors, ~Backup.
Napi::Object Backup::Init(Napi::Env env, Napi::Object exports)
References CompletedGetter, Napi::ObjectWrap< Backup >::DefineClass, FailedGetter, IdleGetter, Napi::InstanceWrap< Backup >::InstanceAccessor, Napi::InstanceWrap< Backup >::InstanceMethod, PageCountGetter, RemainingGetter, RetryErrorGetter, RetryErrorSetter, Napi::Object::Set.
Backup::Backup(const Napi::CallbackInfo &info)
References Napi::Value::As, db, Napi::CallbackInfo::Env, node_sqlite3::Database::HasInstance, Napi::CallbackInfo::IsConstructCall, Napi::CallbackInfo::Length, Napi::TypeError::New, Napi::Reference< T >::Ref, node_sqlite3::Database::Schedule, Napi::CallbackInfo::This, Napi::Error::ThrowAsJavaScriptException, Napi::ObjectWrap< T >::Unwrap, Napi::String::Utf8Value, Napi::PropertyDescriptor::Value, Napi::Value::Value, Work_BeginInitialize.
node_sqlite3::Backup::~Backup()
References FinishAll, finished, Napi::Reference< T >::Reset, retryErrors.
Napi::Value Backup::IdleGetter(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, Napi::Boolean::New.
Referenced by Init.
Napi::Value Backup::CompletedGetter(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, Napi::Boolean::New.
Referenced by Init.
Napi::Value Backup::FailedGetter(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, Napi::Boolean::New.
Referenced by Init.
Napi::Value Backup::PageCountGetter(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, Napi::Number::New.
Referenced by Init.
Napi::Value Backup::RemainingGetter(const Napi::CallbackInfo &info)
References Napi::Reference< Object >::Env, Napi::Number::New.
Referenced by Init.
Napi::Value node_sqlite3::Backup::FatalErrorGetter(const Napi::CallbackInfo &info)
Napi::Value Backup::RetryErrorGetter(const Napi::CallbackInfo &info)
References Napi::Value::Value.
Referenced by Init.
void node_sqlite3::Backup::FatalErrorSetter(const Napi::CallbackInfo &info, const Napi::Value &value)
void Backup::RetryErrorSetter(const Napi::CallbackInfo &info, const Napi::Value &value)
References Napi::Value::As, Napi::Value::IsArray, Napi::Error::New, Napi::Error::ThrowAsJavaScriptException.
Referenced by Init.
void Backup::Work_BeginInitialize(Database::Baton *baton)
References CREATE_WORK, node_sqlite3::Database::Baton::db, Napi::Reference< T >::Env, node_sqlite3::Database::open, node_sqlite3::Database::pending, Work_AfterInitialize, Work_Initialize.
Referenced by Backup.
void Backup::Work_Initialize(napi_env env, void *data)
References BACKUP_INIT.
Referenced by Work_BeginInitialize.
void Backup::Work_AfterInitialize(napi_env env, napi_status status, void *data)
References BACKUP_END, Error, Napi::Value::IsEmpty, Napi::Value::IsFunction, TRY_CATCH_CALL, Napi::Value::Value.
Referenced by Work_BeginInitialize.
void Backup::Error(T *baton)
References EMIT_EVENT, EXCEPTION, Napi::Value::IsEmpty, Napi::Value::IsFunction, message, Napi::String::New, status, TRY_CATCH_CALL, Napi::Reference< T >::Value, Napi::Value::Value.
Referenced by Work_AfterInitialize.
void Backup::Schedule(Work_Callback callback, Baton *baton)
References CleanQueue, finished, inited, locked, queue.
void Backup::Process()
References CleanQueue, finished, inited, locked, queue.
void Backup::CleanQueue()
References EMIT_EVENT, Napi::Reference< Object >::Env, EXCEPTION, inited, Napi::Value::IsEmpty, Napi::Value::IsFunction, Napi::String::New, queue, TRY_CATCH_CALL, Napi::Reference< Object >::Value, Napi::Value::Value.
Referenced by FinishAll, Process, Schedule.
void Backup::FinishAll()
References CleanQueue, completed, db, failed, finished, FinishSqlite, Napi::Reference< T >::Unref.
Referenced by ~Backup, node_sqlite3::Backup::InitializeBaton::~InitializeBaton.
void Backup::FinishSqlite()
References _destDb, _handle, _otherDb.
Referenced by FinishAll.
void Backup::GetRetryErrors(std::set< int > &retryErrorsSet)
References Napi::Number::Int32Value, Napi::Array::Length, retryErrors, Napi::Reference< T >::Value.