Napi::DataView
void* Napi::DataView::_data
size_t Napi::DataView::_length
DataView Napi::DataView::New(napi_env env, Napi::ArrayBuffer arrayBuffer)
References Napi::ArrayBuffer::ByteLength, New.
Referenced by New, New.
DataView Napi::DataView::New(napi_env env, Napi::ArrayBuffer arrayBuffer, size_t byteOffset)
References Napi::ArrayBuffer::ByteLength, DataView, NAPI_THROW, New, Napi::RangeError::New.
DataView Napi::DataView::New(napi_env env, Napi::ArrayBuffer arrayBuffer, size_t byteOffset, size_t byteLength)
References Napi::ArrayBuffer::ByteLength, DataView, NAPI_THROW, NAPI_THROW_IF_FAILED, Napi::RangeError::New.
void Napi::DataView::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::DataView::DataView()
Creates a new empty DataView instance.
Referenced by New, New.
Napi::DataView::DataView(napi_env env, napi_value value)
Wraps a Node-API value primitive.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED_VOID.
Napi::ArrayBuffer Napi::DataView::ArrayBuffer() const
Gets the backing array buffer.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
size_t Napi::DataView::ByteOffset() const
Gets the offset into the buffer where the array starts.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
size_t Napi::DataView::ByteLength() const
Gets the length of the array in bytes.
void * Napi::DataView::Data() const
float Napi::DataView::GetFloat32(size_t byteOffset) const
double Napi::DataView::GetFloat64(size_t byteOffset) const
int8_t Napi::DataView::GetInt8(size_t byteOffset) const
int16_t Napi::DataView::GetInt16(size_t byteOffset) const
int32_t Napi::DataView::GetInt32(size_t byteOffset) const
uint8_t Napi::DataView::GetUint8(size_t byteOffset) const
uint16_t Napi::DataView::GetUint16(size_t byteOffset) const
uint32_t Napi::DataView::GetUint32(size_t byteOffset) const
void Napi::DataView::SetFloat32(size_t byteOffset, float value) const
void Napi::DataView::SetFloat64(size_t byteOffset, double value) const
void Napi::DataView::SetInt8(size_t byteOffset, int8_t value) const
void Napi::DataView::SetInt16(size_t byteOffset, int16_t value) const
void Napi::DataView::SetInt32(size_t byteOffset, int32_t value) const
void Napi::DataView::SetUint8(size_t byteOffset, uint8_t value) const
void Napi::DataView::SetUint16(size_t byteOffset, uint16_t value) const
void Napi::DataView::SetUint32(size_t byteOffset, uint32_t value) const
T Napi::DataView::ReadData(size_t byteOffset) const
void Napi::DataView::WriteData(size_t byteOffset, T value) const