Napi::TypedArray
napi_typedarray_type Napi::TypedArray::_type
!cond INTERNAL
Referenced by Napi::ObjectWrap< Backup >::DefineClass, ElementSize, TypedArray, TypedArrayType.
size_t Napi::TypedArray::_length
Referenced by Napi::ObjectWrap< Backup >::DefineClass, ElementLength, TypedArray.
void Napi::TypedArray::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Referenced by Napi::TypedArrayOf< T >::CheckCast.
Napi::TypedArray::TypedArray()
Creates a new empty TypedArray instance.
Napi::TypedArray::TypedArray(napi_env env, napi_value value)
Wraps a Node-API value primitive.
References Napi::Value::_env, _length, _type, Napi::Value::_value, NAPI_THROW_IF_FAILED_VOID.
napi_typedarray_type Napi::TypedArray::TypedArrayType() const
Gets the type of this typed-array.
References _type.
Napi::ArrayBuffer Napi::TypedArray::ArrayBuffer() const
Gets the backing array buffer.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
uint8_t Napi::TypedArray::ElementSize() const
Gets the size in bytes of one element in the array.
References _type.
Referenced by ByteLength.
size_t Napi::TypedArray::ElementLength() const
Gets the number of elements in the array.
References _length.
Referenced by ByteLength.
size_t Napi::TypedArray::ByteOffset() const
Gets the offset into the buffer where the array starts.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
size_t Napi::TypedArray::ByteLength() const
Gets the length of the array in bytes.
References ElementLength, ElementSize.
Napi::TypedArray::TypedArray(napi_env env, napi_value value, napi_typedarray_type type, size_t length)
static constexpr napi_typedarray_type Napi::TypedArray::TypedArrayTypeForPrimitiveType()