Napi::Value
napi_env Napi::Value::_env
!cond INTERNAL
Referenced by Napi::Object::AddFinalizer, Napi::Object::AddFinalizer, Napi::DataView::ArrayBuffer, Napi::TypedArray::ArrayBuffer, As, Napi::ArrayBuffer::ByteLength, Napi::DataView::ByteOffset, Napi::TypedArray::ByteOffset, Napi::Function::Call, Napi::ArrayBuffer::Data, Napi::DataView::DataView, Napi::ObjectWrap< Backup >::DefineClass, Napi::Object::DefineProperties, Napi::Object::DefineProperties, Napi::Object::DefineProperty, Napi::Object::Delete, Napi::Number::DoubleValue, Napi::Promise::Deferred::Env, Env, Napi::Object::Get, Napi::Object::Get, Napi::Object::Get, Napi::Object::GetPropertyNames, Napi::Object::Has, Napi::Object::Has, Napi::Object::Has, Napi::Object::HasOwnProperty, Napi::Object::HasOwnProperty, Napi::Object::HasOwnProperty, Napi::InstanceWrap< Backup >::InstanceMethod, Napi::Object::InstanceOf, Napi::Number::Int32Value, Napi::Number::Int64Value, IsArray, IsArrayBuffer, IsBuffer, IsDataView, IsPromise, IsTypedArray, Napi::Array::Length, Napi::Function::MakeCallback, Napi::Function::New, Napi::Promise::Deferred::Promise, Napi::Promise::Deferred::Reject, Napi::Promise::Deferred::Resolve, Napi::Object::Set, Napi::Object::Set, Napi::Object::Set, Napi::Object::Set, StrictEquals, ToBoolean, ToNumber, ToObject, ToString, Type, Napi::TypedArray::TypedArray, Napi::Number::Uint32Value, Napi::String::Utf16Value, Napi::String::Utf8Value, Napi::Boolean::Value.
napi_value Napi::Value::_value
Referenced by Napi::DataView::ArrayBuffer, Napi::TypedArray::ArrayBuffer, As, Napi::ArrayBuffer::ByteLength, Napi::DataView::ByteOffset, Napi::TypedArray::ByteOffset, Napi::Function::Call, Napi::ArrayBuffer::Data, Napi::DataView::DataView, Napi::ObjectWrap< Backup >::DefineClass, Napi::Object::DefineProperties, Napi::Object::DefineProperties, Napi::Object::DefineProperty, Napi::Object::Delete, Napi::Number::DoubleValue, Napi::Object::Get, Napi::Object::Get, Napi::Object::Get, Napi::Object::GetPropertyNames, Napi::Object::Has, Napi::Object::Has, Napi::Object::Has, Napi::Object::HasOwnProperty, Napi::Object::HasOwnProperty, Napi::Object::InstanceOf, Napi::Number::Int32Value, Napi::Number::Int64Value, IsArray, IsArrayBuffer, IsBuffer, IsDataView, IsEmpty, IsPromise, IsTypedArray, Napi::Array::Length, Napi::Function::MakeCallback, Napi::Function::New, Napi::Object::Set, Napi::Object::Set, Napi::Object::Set, Napi::Object::Set, ToBoolean, ToNumber, ToObject, ToString, Type, Napi::TypedArray::TypedArray, Napi::Number::Uint32Value, Napi::String::Utf16Value, Napi::String::Utf8Value, Napi::Boolean::Value.
Napi::Value::Value()
Creates a new empty Value instance.
Referenced by node_sqlite3::Statement::AsyncEach, node_sqlite3::Backup::Backup, node_sqlite3::Backup::CleanQueue, node_sqlite3::Statement::CleanQueue, node_sqlite3::Backup::Error, node_sqlite3::Statement::Error, node_sqlite3::Statement::Finalize_, Napi::Object::Get, Napi::Object::Get, Napi::Object::Get, node_sqlite3::Database::Process, node_sqlite3::Backup::RetryErrorGetter, node_sqlite3::Backup::Work_AfterInitialize, node_sqlite3::Statement::Work_AfterPrepare, node_sqlite3::Database::Work_Wait.
Napi::Value::Value(napi_env env, napi_value value)
Wraps a Node-API value primitive.
Napi::Value::operator napi_value() const
Converts to a Node-API value primitive. If the instance is empty, this returns nullptr.
bool Napi::Value::operator==(const Value &other) const
Tests if this value strictly equals another value.
References StrictEquals.
Referenced by operator!=.
bool Napi::Value::operator!=(const Value &other) const
Tests if this value does not strictly equal another value.
References operator==.
bool Napi::Value::StrictEquals(const Value &other) const
Tests if this value strictly equals another value.
References _env, NAPI_THROW_IF_FAILED.
Referenced by Napi::Reference< T >::operator==, operator==.
Napi::Env Napi::Value::Env() const
Gets the environment the value is associated with.
References _env.
Referenced by node_sqlite3::Statement::BindParameter, Napi::Function::Call, Napi::Function::Call, Napi::Function::Call, Napi::Function::Call, node_sqlite3::Database::HasInstance, Napi::Function::operator(), OtherInstanceOf, StringConcat, Napi::ObjectWrap< T >::Unwrap.
bool Napi::Value::IsEmpty() const
Checks if the value is empty (uninitialized). An empty value is invalid, and most attempts to perform an operation on an empty value will result in an exception. Note an empty value is distinct from JavaScript null or undefined, which are valid values. When C++ exceptions are disabled at compile time, a method with a Value return type may return an empty value to indicate a pending exception. So when not using C++ exceptions, callers should check whether the value is empty before attempting to use it.
References _value.
Referenced by node_sqlite3::Statement::AsyncEach, node_sqlite3::Backup::CleanQueue, node_sqlite3::Statement::CleanQueue, node_sqlite3::Backup::Error, IsArray, IsArrayBuffer, IsBuffer, Napi::CallbackInfo::IsConstructCall, IsDataView, IsPromise, IsTypedArray, Type, node_sqlite3::Backup::Work_AfterInitialize.
napi_valuetype Napi::Value::Type() const
Gets the type of the value.
References _env, _value, IsEmpty, NAPI_THROW_IF_FAILED.
Referenced by IsBoolean, IsExternal, IsFunction, IsNull, IsNumber, IsObject, IsString, IsSymbol, IsUndefined.
bool Napi::Value::IsUndefined() const
Tests if a value is an undefined JavaScript value.
References Type.
Referenced by node_sqlite3::Database::Baton::Baton.
bool Napi::Value::IsNull() const
Tests if a value is a null JavaScript value.
References Type.
Referenced by node_sqlite3::Statement::BindParameter.
bool Napi::Value::IsBoolean() const
Tests if a value is a JavaScript boolean.
References Type.
Referenced by node_sqlite3::Statement::BindParameter.
bool Napi::Value::IsNumber() const
Tests if a value is a JavaScript number.
References Type.
Referenced by node_sqlite3::Statement::BindParameter.
bool Napi::Value::IsString() const
Tests if a value is a JavaScript string.
References Type.
Referenced by node_sqlite3::Statement::BindParameter.
bool Napi::Value::IsSymbol() const
Tests if a value is a JavaScript symbol.
References Type.
bool Napi::Value::IsArray() const
Tests if a value is a JavaScript array.
References _env, _value, IsEmpty, NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Backup::RetryErrorSetter.
bool Napi::Value::IsArrayBuffer() const
Tests if a value is a JavaScript array buffer.
References _env, _value, IsEmpty, NAPI_THROW_IF_FAILED.
bool Napi::Value::IsTypedArray() const
Tests if a value is a JavaScript typed array.
References _env, _value, IsEmpty, NAPI_THROW_IF_FAILED.
bool Napi::Value::IsObject() const
Tests if a value is a JavaScript object.
References IsFunction, Type.
Referenced by node_sqlite3::Statement::BindParameter, node_sqlite3::Database::HasInstance.
bool Napi::Value::IsFunction() const
Tests if a value is a JavaScript function.
References Type.
Referenced by node_sqlite3::Statement::AsyncEach, node_sqlite3::Database::Baton::Baton, node_sqlite3::Backup::CleanQueue, node_sqlite3::Statement::CleanQueue, node_sqlite3::Backup::Error, IsObject, node_sqlite3::Backup::Work_AfterInitialize.
bool Napi::Value::IsPromise() const
Tests if a value is a JavaScript promise.
References _env, _value, IsEmpty, NAPI_THROW_IF_FAILED.
bool Napi::Value::IsDataView() const
Tests if a value is a JavaScript data view.
References _env, _value, IsEmpty, NAPI_THROW_IF_FAILED.
bool Napi::Value::IsBuffer() const
Tests if a value is a Node buffer.
References _env, _value, IsEmpty, NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::BindParameter.
bool Napi::Value::IsExternal() const
Tests if a value is a pointer to external data.
References Type.
T Napi::Value::As() const
Casts to another type of Napi::Value, when the actual type is known or assumed. This conversion does NOT coerce the type. Calling any methods inappropriate for the actual value type will throw Napi::Error. If NODE_ADDON_API_ENABLE_TYPE_CHECK_ON_AS is defined, this method asserts that the actual type is the expected type.
References _env, _value.
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Statement::BindParameter, node_sqlite3::Database::Database, Napi::Symbol::For, node_sqlite3::Database::HasInstance, Napi::Error::Message, Napi::FunctionReference::New, Napi::FunctionReference::New, node_sqlite3::Backup::RetryErrorSetter, node_sqlite3::Statement::Statement, StringConcat, Napi::details::TemplatedInstanceCallback, Napi::details::TemplatedInstanceVoidCallback, Napi::Symbol::WellKnown.
MaybeOrValue< Boolean > Napi::Value::ToBoolean() const
Coerces a value to a JavaScript boolean.
References _env, _value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< Number > Napi::Value::ToNumber() const
Coerces a value to a JavaScript number.
References _env, _value, NAPI_RETURN_OR_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::BindParameter.
MaybeOrValue< String > Napi::Value::ToString() const
Coerces a value to a JavaScript string.
References _env, _value, NAPI_RETURN_OR_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::BindParameter.
MaybeOrValue< Object > Napi::Value::ToObject() const
Coerces a value to a JavaScript object.
References _env, _value, NAPI_RETURN_OR_THROW_IF_FAILED.
Value Napi::Value::From(napi_env env, const T &value)
Creates a JS value from a C++ primitive. value may be any of: bool Any integer type Any floating point type const char* (encoded using UTF-8, null-terminated) const char16_t* (encoded using UTF-16-LE, null-terminated) std::string (encoded using UTF-8) std::u16string napi::Value napi_value
Referenced by Napi::Error::Error, Napi::Object::Set, Napi::Object::Set, Napi::Object::Set, Napi::Object::Set.