Napi::RangeError
RangeError Napi::RangeError::New(napi_env env, const char *message)
References Napi::Error::New.
Referenced by Napi::InstanceWrap< Backup >::InstanceMethod, Napi::DataView::New, Napi::DataView::New.
RangeError Napi::RangeError::New(napi_env env, const std::string &message)
References Napi::Error::New.
Napi::RangeError::RangeError()
Napi::RangeError::RangeError(napi_env env, napi_value value)