Napi::CallbackInfo
const size_t Napi::CallbackInfo::_staticArgCount
napi_env Napi::CallbackInfo::_env
napi_callback_info Napi::CallbackInfo::_info
napi_value Napi::CallbackInfo::_this
size_t Napi::CallbackInfo::_argc
napi_value* Napi::CallbackInfo::_argv
napi_value Napi::CallbackInfo::_staticArgs[6][6]
napi_value* Napi::CallbackInfo::_dynamicArgs
void* Napi::CallbackInfo::_data
Napi::CallbackInfo::CallbackInfo(napi_env env, napi_callback_info info)
References NAPI_THROW_IF_FAILED_VOID.
Napi::CallbackInfo::~CallbackInfo()
Napi::Env Napi::CallbackInfo::Env() const
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Statement::Bind, node_sqlite3::Database::Database, node_sqlite3::Statement::Finalize_, Napi::ObjectWrap< T >::ObjectWrap, Napi::ObjectWrap< T >::OnCalledAsFunction, operator[], node_sqlite3::Statement::Statement, This, node_sqlite3::Database::Wait.
Value Napi::CallbackInfo::NewTarget() const
References NAPI_THROW_IF_FAILED.
Referenced by IsConstructCall.
bool Napi::CallbackInfo::IsConstructCall() const
References Napi::Value::IsEmpty, NewTarget.
Referenced by node_sqlite3::Backup::Backup.
size_t Napi::CallbackInfo::Length() const
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Statement::Bind, node_sqlite3::Database::Database, node_sqlite3::Statement::Statement.
const Value Napi::CallbackInfo::operator[](size_t index) const
References Env, Napi::Env::Undefined.
Value Napi::CallbackInfo::This() const
References Env, Napi::Env::Undefined.
Referenced by node_sqlite3::Backup::Backup, node_sqlite3::Database::Configure, node_sqlite3::Database::Database, node_sqlite3::Database::Interrupt, Napi::ObjectWrap< T >::ObjectWrap, node_sqlite3::Database::Parallelize, node_sqlite3::Database::Serialize, node_sqlite3::Statement::Statement, Napi::details::TemplatedInstanceCallback, Napi::details::TemplatedInstanceVoidCallback, node_sqlite3::Database::Wait.
void * Napi::CallbackInfo::Data() const
Referenced by Napi::details::AccessorCallbackData< Getter, Setter >::GetterWrapper, Napi::details::AccessorCallbackData< Getter, Setter >::SetterWrapper, Napi::details::CallbackData< Callable, Return >::Wrapper, Napi::details::CallbackData< Callable, void >::Wrapper.
void Napi::CallbackInfo::SetData(void *data)
Referenced by Napi::details::AccessorCallbackData< Getter, Setter >::GetterWrapper, Napi::details::AccessorCallbackData< Getter, Setter >::SetterWrapper, Napi::details::CallbackData< Callable, Return >::Wrapper, Napi::details::CallbackData< Callable, void >::Wrapper.
Napi::CallbackInfo::operator napi_callback_info() const