node_sqlite3::Statement
typedef void(* node_sqlite3::Statement::Work_Callback) (Baton *baton))(Baton *baton)
Database* node_sqlite3::Statement::db
Referenced by Bind, Finalize_, Finalize_, Statement.
sqlite3_stmt* node_sqlite3::Statement::_handle
Referenced by Bind, Finalize_.
int node_sqlite3::Statement::status
Referenced by Bind, Error.
bool node_sqlite3::Statement::prepared
Referenced by CleanQueue, Process, Schedule.
bool node_sqlite3::Statement::locked
Referenced by Process, Schedule.
bool node_sqlite3::Statement::finalized
Referenced by Finalize_, Process, Schedule, ~Statement.
std::queue<Call*> node_sqlite3::Statement::queue
Referenced by CleanQueue, Process, Schedule.
std::string node_sqlite3::Statement::message
Referenced by Bind, Error.
Napi::Object Statement::Init(Napi::Env env, Napi::Object exports)
References Bind, Napi::ObjectWrap< Statement >::DefineClass, Finalize_, Napi::InstanceWrap< Statement >::InstanceMethod, Napi::Reference< Object >::Reset, Napi::Object::Set.
static Napi::Value node_sqlite3::Statement::New(const Napi::CallbackInfo &info)
Statement::Statement(const Napi::CallbackInfo &info)
References Napi::Value::As, db, Napi::CallbackInfo::Env, node_sqlite3::Database::HasInstance, Napi::CallbackInfo::Length, Napi::TypeError::New, Napi::Reference< T >::Ref, node_sqlite3::Database::Schedule, Napi::CallbackInfo::This, Napi::Error::ThrowAsJavaScriptException, Napi::ObjectWrap< T >::Unwrap, Napi::String::Utf8Value, Napi::PropertyDescriptor::Value, Work_BeginPrepare.
node_sqlite3::Statement::~Statement()
References Finalize_, finalized.
Napi::Value Statement::Finalize_(const Napi::CallbackInfo &info)
References db, Napi::CallbackInfo::Env, Finalize_, OPTIONAL_ARGUMENT_FUNCTION, Schedule, Napi::Reference< T >::Value.
Referenced by node_sqlite3::Statement::PrepareBaton::~PrepareBaton.
void Statement::Work_BeginPrepare(Database::Baton *baton)
References CREATE_WORK, node_sqlite3::Database::Baton::db, Napi::Reference< T >::Env, node_sqlite3::Database::open, node_sqlite3::Database::pending, Work_AfterPrepare, Work_Prepare.
Referenced by Statement.
void Statement::Work_Prepare(napi_env env, void *data)
References STATEMENT_INIT, STATEMENT_MUTEX.
Referenced by Work_BeginPrepare.
void Statement::Work_AfterPrepare(napi_env env, napi_status status, void *data)
References Error, STATEMENT_END, TRY_CATCH_CALL, Napi::Value::Value.
Referenced by Work_BeginPrepare.
void Statement::AsyncEach(uv_async_t *handle)
References CloseCallback, Napi::Reference< T >::Env, IS_FUNCTION, Napi::Value::IsEmpty, Napi::Value::IsFunction, Napi::Number::New, NODE_SQLITE3_MUTEX_LOCK, NODE_SQLITE3_MUTEX_UNLOCK, RowToJS, node_sqlite3::Statement::Async::stmt, TRY_CATCH_CALL, Napi::Value::Value.
void Statement::CloseCallback(uv_handle_t *handle)
Referenced by AsyncEach.
void Statement::Finalize_(Baton *baton)
References IS_FUNCTION, TRY_CATCH_CALL, Napi::Value::Value.
void Statement::GetRow(Row *row, sqlite3_stmt *stmt)
Napi::Value Statement::RowToJS(Napi::Env env, Row *row)
References Napi::Buffer< T >::Copy, Napi::EscapableHandleScope::Escape, Napi::Number::New, Napi::Object::New, Napi::String::New, Napi::Env::Null.
Referenced by AsyncEach.
void Statement::Error(T *baton)
References EMIT_EVENT, Napi::Reference< T >::Env, EXCEPTION, IS_FUNCTION, message, Napi::String::New, status, TRY_CATCH_CALL, Napi::Reference< T >::Value, Napi::Value::Value.
Referenced by Work_AfterPrepare.
void Statement::Finalize_()
References _handle, CleanQueue, db, finalized, Napi::Reference< T >::Unref.
Referenced by Finalize_, Init, ~Statement.
std::unique_ptr< Values::Field > Statement::BindParameter(const Napi::Value source, T pos)
References Napi::Value::As, Napi::Buffer< T >::Data, Napi::Number::DoubleValue, Napi::Value::Env, Napi::Number::Int32Value, Napi::Value::IsBoolean, Napi::Value::IsBuffer, Napi::Value::IsNull, Napi::Value::IsNumber, Napi::Value::IsObject, Napi::Value::IsString, Napi::Buffer< T >::Length, Napi::String::New, OtherInstanceOf, OtherIsInt, Napi::Value::ToNumber, Napi::Value::ToString, Napi::Boolean::Value.
Referenced by Bind.
T * Statement::Bind(const Napi::CallbackInfo &info, int start=0, int end=-1)
References BindParameter, Napi::Number::DoubleValue, Napi::CallbackInfo::Env, Napi::Object::GetPropertyNames, Napi::Number::Int32Value, Napi::Array::Length, Napi::CallbackInfo::Length, OtherInstanceOf.
Referenced by Init.
bool Statement::Bind(const Parameters &parameters)
References node_sqlite3::Database::_handle, _handle, db, message, status.
void Statement::Schedule(Work_Callback callback, Baton *baton)
References CleanQueue, finalized, locked, prepared, queue.
Referenced by Finalize_.
void Statement::Process()
References CleanQueue, finalized, locked, prepared, queue.
void Statement::CleanQueue()
References EMIT_EVENT, Napi::Reference< Object >::Env, EXCEPTION, Napi::Value::IsEmpty, Napi::Value::IsFunction, Napi::String::New, prepared, queue, TRY_CATCH_CALL, Napi::Reference< Object >::Value, Napi::Value::Value.
Referenced by Finalize_, Process, Schedule.