gyp::MSVSSettings::_Boolean
gyp.MSVSSettings._Boolean._Validate(self, value)
Referenced by gyp.MSVSSettings._Boolean.ConvertToMSBuild, gyp.MSVSSettings._Boolean.ValidateMSBuild, gyp.MSVSSettings._Boolean.ValidateMSVS.
gyp.MSVSSettings._Boolean.ValidateMSVS(self, value)
Verifies that the value is legal for MSVS. Args: value: the value to check for this type. Raises: ValueError if value is not valid for MSVS.
References gyp.MSVSSettings._Boolean._Validate.
gyp.MSVSSettings._Boolean.ValidateMSBuild(self, value)
Verifies that the value is legal for MSBuild. Args: value: the value to check for this type. Raises: ValueError if value is not valid for MSBuild.
References gyp.MSVSSettings._Boolean._Validate.
gyp.MSVSSettings._Boolean.ConvertToMSBuild(self, value)
Returns the MSBuild equivalent of the MSVS value given. Args: value: the MSVS value to convert. Returns: the MSBuild equivalent. Raises: ValueError if value is not valid.
References gyp.MSVSSettings._Boolean._Validate.
Referenced by gyp.MSVSSettings._Enumeration.ValidateMSVS, gyp.MSVSSettings._Integer.ValidateMSVS.