Napi::EscapableHandleScope
napi_env Napi::EscapableHandleScope::_env
napi_escapable_handle_scope Napi::EscapableHandleScope::_scope
Napi::EscapableHandleScope::EscapableHandleScope(napi_env env, napi_escapable_handle_scope scope)
Napi::EscapableHandleScope::EscapableHandleScope(Napi::Env env)
References NAPI_THROW_IF_FAILED_VOID.
Napi::EscapableHandleScope::~EscapableHandleScope()
References NAPI_FATAL_IF_FAILED.
Napi::EscapableHandleScope::operator napi_escapable_handle_scope() const
Napi::Env Napi::EscapableHandleScope::Env() const
Referenced by Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::New, Napi::FunctionReference::New, Napi::FunctionReference::operator().
Value Napi::EscapableHandleScope::Escape(napi_value escapee)
References NAPI_THROW_IF_FAILED.
Referenced by Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::New, Napi::FunctionReference::New, Napi::FunctionReference::operator(), node_sqlite3::Statement::RowToJS.