Napi::Boolean
Boolean Napi::Boolean::New(napi_env env, bool value)
Node-API environment
References Boolean, NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Backup::CompletedGetter, node_sqlite3::Backup::FailedGetter, Napi::details::vf_number< bool >::From, node_sqlite3::Backup::IdleGetter.
void Napi::Boolean::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::Boolean::Boolean()
Creates a new empty Boolean instance.
Referenced by New.
Napi::Boolean::Boolean(napi_env env, napi_value value)
Wraps a Node-API value primitive.
Napi::Boolean::operator bool() const
Converts a Boolean value to a boolean primitive.
bool Napi::Boolean::Value() const
Converts a Boolean value to a boolean primitive.
References Napi::Value::_env, Napi::Value::_value, NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::BindParameter.