Napi::Env
napi_env Napi::Env::_env
Napi::Env::Env(napi_env env)
Napi::Env::operator napi_env() const
Object Napi::Env::Global() const
References NAPI_THROW_IF_FAILED.
Referenced by Napi::Symbol::For, OtherInstanceOf, Napi::Symbol::WellKnown.
Value Napi::Env::Undefined() const
References NAPI_THROW_IF_FAILED.
Referenced by Napi::CallbackInfo::operator[], Napi::CallbackInfo::This.
Value Napi::Env::Null() const
References NAPI_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::RowToJS.
bool Napi::Env::IsExceptionPending() const
Referenced by Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::New, Napi::FunctionReference::New, Napi::FunctionReference::operator().
Error Napi::Env::GetAndClearPendingException() const
MaybeOrValue< Value > Napi::Env::RunScript(const char *utf8script) const
References Napi::String::New, RunScript.
Referenced by RunScript, RunScript.
MaybeOrValue< Value > Napi::Env::RunScript(const std::string &utf8script) const
References RunScript.
MaybeOrValue< Value > Napi::Env::RunScript(String script) const
References NAPI_RETURN_OR_THROW_IF_FAILED.