Napi::Object
Object Napi::Object::New(napi_env env)
Node-API environment
References NAPI_THROW_IF_FAILED, Object.
Referenced by node_sqlite3::Statement::RowToJS.
void Napi::Object::CheckCast(napi_env env, napi_value value)
References NAPI_CHECK.
Napi::Object::Object()
Creates a new empty Object instance.
Referenced by New.
Napi::Object::Object(napi_env env, napi_value value)
Wraps a Node-API value primitive.
Object::PropertyLValue< std::string > Napi::Object::operator[](const char *utf8name)
UTF-8 encoded null-terminated property name
Object::PropertyLValue< std::string > Napi::Object::operator[](const std::string &utf8name)
UTF-8 encoded property name
Object::PropertyLValue< uint32_t > Napi::Object::operator[](uint32_t index)
Property / element index
Object::PropertyLValue< Value > Napi::Object::operator[](Value index) const
Property / element index
MaybeOrValue< Value > Napi::Object::operator[](const char *utf8name) const
UTF-8 encoded null-terminated property name
References Get.
MaybeOrValue< Value > Napi::Object::operator[](const std::string &utf8name) const
UTF-8 encoded property name
References Get.
MaybeOrValue< Value > Napi::Object::operator[](uint32_t index) const
Property / element index
References Get.
MaybeOrValue< bool > Napi::Object::Has(napi_value key) const
Property key primitive
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
Referenced by Has.
MaybeOrValue< bool > Napi::Object::Has(Value key) const
Property key
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::Has(const char *utf8name) const
UTF-8 encoded null-terminated property name
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::Has(const std::string &utf8name) const
UTF-8 encoded property name
References Has.
MaybeOrValue< bool > Napi::Object::HasOwnProperty(napi_value key) const
Property key primitive
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
Referenced by HasOwnProperty, HasOwnProperty.
MaybeOrValue< bool > Napi::Object::HasOwnProperty(Value key) const
Property key
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::HasOwnProperty(const char *utf8name) const
UTF-8 encoded null-terminated property name
References Napi::Value::_env, HasOwnProperty, NAPI_MAYBE_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::HasOwnProperty(const std::string &utf8name) const
UTF-8 encoded property name
References HasOwnProperty.
MaybeOrValue< Value > Napi::Object::Get(napi_value key) const
Property key primitive
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED, Napi::Value::Value.
Referenced by Napi::Symbol::For, Get, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::Object::PropertyLValue< Key >::operator Value, operator[], operator[], operator[], OtherInstanceOf, Napi::Symbol::WellKnown.
MaybeOrValue< Value > Napi::Object::Get(Value key) const
Property key
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED, Napi::Value::Value.
MaybeOrValue< Value > Napi::Object::Get(const char *utf8name) const
UTF-8 encoded null-terminated property name
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED, Napi::Value::Value.
MaybeOrValue< Value > Napi::Object::Get(const std::string &utf8name) const
UTF-8 encoded property name
References Get.
MaybeOrValue< bool > Napi::Object::Set(napi_value key, const ValueType &value) const
Property key primitive
References Napi::Value::_env, Napi::Value::_value, Napi::Value::From, NAPI_RETURN_OR_THROW_IF_FAILED.
Referenced by node_sqlite3::Backup::Init, node_sqlite3::Database::Init, node_sqlite3::Statement::Init, Napi::Object::PropertyLValue< Key >::operator=, Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set, Napi::ObjectReference::Set.
MaybeOrValue< bool > Napi::Object::Set(Value key, const ValueType &value) const
Property key
References Napi::Value::_env, Napi::Value::_value, Napi::Value::From, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::Set(const char *utf8name, const ValueType &value) const
UTF-8 encoded null-terminated property name
References Napi::Value::_env, Napi::Value::_value, Napi::Value::From, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::Set(const std::string &utf8name, const ValueType &value) const
UTF-8 encoded property name
References Set.
MaybeOrValue< bool > Napi::Object::Delete(napi_value key) const
Property key primitive
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::Delete(Value key) const
Property key
MaybeOrValue< bool > Napi::Object::Delete(const char *utf8name) const
UTF-8 encoded null-terminated property name
MaybeOrValue< bool > Napi::Object::Delete(const std::string &utf8name) const
UTF-8 encoded property name
MaybeOrValue< bool > Napi::Object::Has(uint32_t index) const
Property / element index
MaybeOrValue< Value > Napi::Object::Get(uint32_t index) const
Property / element index
MaybeOrValue< bool > Napi::Object::Set(uint32_t index, const ValueType &value) const
Property / element index
References Napi::Value::_env, Napi::Value::_value, Napi::Value::From, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::Delete(uint32_t index) const
Property / element index
MaybeOrValue< Array > Napi::Object::GetPropertyNames() const
Get all property names.
This operation can fail in case of Proxy.[[OwnPropertyKeys]] and Proxy.[[GetOwnProperty]] calling into JavaScript. See: https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-ownpropertykeys https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-getownproperty-p
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
Referenced by node_sqlite3::Statement::Bind.
MaybeOrValue< bool > Napi::Object::DefineProperty(const PropertyDescriptor &property) const
Descriptor for the property to be defined
Defines a property on the object. This operation can fail in case of Proxy.[[DefineOwnProperty]] calling into JavaScript. See https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-defineownproperty-p-desc
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::DefineProperties(const std::initializer_list< PropertyDescriptor > &properties) const
List of descriptors for the properties to be defined
Defines properties on the object. This operation can fail in case of Proxy.[[DefineOwnProperty]] calling into JavaScript. See https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-defineownproperty-p-desc
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::DefineProperties(const std::vector< PropertyDescriptor > &properties) const
Vector of descriptors for the properties to be defined
Defines properties on the object. This operation can fail in case of Proxy.[[DefineOwnProperty]] calling into JavaScript. See https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-defineownproperty-p-desc
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
MaybeOrValue< bool > Napi::Object::InstanceOf(const Function &constructor) const
Constructor function
Checks if an object is an instance created by a constructor function. This is equivalent to the JavaScript instanceof operator. This operation can fail in case of Proxy.[[GetPrototypeOf]] calling into JavaScript. See https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-getprototypeof
References Napi::Value::_env, Napi::Value::_value, NAPI_RETURN_OR_THROW_IF_FAILED.
Referenced by node_sqlite3::Database::HasInstance, OtherInstanceOf.
void Napi::Object::AddFinalizer(Finalizer finalizeCallback, T *data) const
References Napi::Value::_env, NAPI_THROW_IF_FAILED_VOID.
void Napi::Object::AddFinalizer(Finalizer finalizeCallback, T *data, Hint *finalizeHint) const
References Napi::Value::_env, NAPI_THROW_IF_FAILED_VOID.