gyp::xcode_ninja
gyp.xcode_ninja._WriteWorkspace(main_gyp, sources_gyp, params)
Create a workspace to wrap main and sources gyp paths.
Referenced by gyp.xcode_ninja.CreateWrapper.
gyp.xcode_ninja._TargetFromSpec(old_spec, params)
Create fake target for xcode-ninja wrapper.
References gyp.generator.ninja.ComputeOutputDir.
Referenced by gyp.xcode_ninja.CreateWrapper.
gyp.xcode_ninja.IsValidTargetForWrapper(target_extras, executable_target_pattern, spec)
Limit targets for Xcode wrapper. Xcode sometimes performs poorly with too many targets, so only include proper executable targets, with filters to customize. Arguments: target_extras: Regular expression to always add, matching any target. executable_target_pattern: Regular expression limiting executable targets. spec: Specifications for target.
Referenced by gyp.xcode_ninja.CreateWrapper.
gyp.xcode_ninja.CreateWrapper(target_list, target_dicts, data, params)
Initialize targets for the ninja wrapper. This sets up the necessary variables in the targets to generate Xcode projects that use ninja as an external builder. Arguments: target_list: List of target pairs: 'base/base.gyp:base'. target_dicts: Dict of target properties keyed on target pair. data: Dict of flattened build files keyed on gyp path. params: Dict of global options for gyp.
References gyp.xcode_ninja._TargetFromSpec, gyp.xcode_ninja._WriteWorkspace, gyp.xcode_ninja.IsValidTargetForWrapper.
Referenced by gyp.generator.xcode.GenerateOutput.