gyp::generator::make
dict gyp::generator::make.generator_default_variables
bool gyp::generator::make.generator_supports_multiple_toolsets
bool gyp::generator::make.generator_wants_sorted_dependencies
list gyp::generator::make.generator_additional_non_configuration_keys
list gyp::generator::make.generator_additional_path_sections
list gyp::generator::make.generator_extra_sources_for_rules
gyp::generator::make.generator_filelist_paths
str gyp::generator::make.SPACE_REPLACEMENT
str gyp::generator::make.LINK_COMMANDS_LINUX
str gyp::generator::make.LINK_COMMANDS_MAC
str gyp::generator::make.LINK_COMMANDS_ANDROID
str gyp::generator::make.LINK_COMMANDS_AIX
str gyp::generator::make.LINK_COMMANDS_OS390
tuple gyp::generator::make.SHARED_HEADER
str gyp::generator::make.SHARED_HEADER_MAC_COMMANDS
str gyp::generator::make.SHARED_HEADER_SUFFIX_RULES_COMMENT1
str gyp::generator::make.SHARED_HEADER_SUFFIX_RULES_COMMENT2
str gyp::generator::make.SHARED_FOOTER
str gyp::generator::make.header
dict gyp::generator::make.COMPILABLE_EXTENSIONS
str gyp::generator::make.srcdir_prefix
dict gyp::generator::make.target_outputs
dict gyp::generator::make.target_link_deps
gyp.generator.make.CalculateVariables(default_variables, params)
Calculate additional variables for use in the build (called by gyp).
References gyp.common.GetFlavor.
gyp.generator.make.CalculateGeneratorInputInfo(params)
Calculate the generator specific info that gets fed to input (called by gyp).
gyp.generator.make.WriteRootHeaderSuffixRules(writer)
Referenced by gyp.generator.make.GenerateOutput.
gyp.generator.make.Compilable(filename)
Return true if the file is compilable (should be in OBJS).
gyp.generator.make.Linkable(filename)
Return true if the file is linkable (should be on the link line).
Referenced by gyp.generator.make.MakefileWriter.WriteSources.
gyp.generator.make.Target(filename)
Translate a compilable filename to its .o target.
Referenced by gyp.generator.make.MakefileWriter.WriteSources.
gyp.generator.make.EscapeShellArgument(s)
Quotes an argument so that it will be interpreted literally by a POSIX shell. Taken from http://stackoverflow.com/questions/35817/whats-the-best-way-to-escape-ossystem-calls-in-python
Referenced by gyp.generator.make.EscapeCppDefine, gyp.generator.make.MakefileWriter.WriteTarget.
gyp.generator.make.EscapeMakeVariableExpansion(s)
Make has its own variable expansion syntax using $. We must escape it for string to be interpreted literally.
Referenced by gyp.generator.make.EscapeCppDefine.
gyp.generator.make.EscapeCppDefine(s)
Escapes a CPP define so that it will reach the compiler unaltered.
References gyp.generator.make.EscapeMakeVariableExpansion, gyp.generator.make.EscapeShellArgument.
gyp.generator.make.QuoteIfNecessary(string)
TODO: Should this ideally be replaced with one or more of the above functions?
gyp.generator.make.StringToMakefileVariable(string)
Convert a string to a value that is acceptable as a make variable name.
Referenced by gyp.generator.make.MakefileWriter.WriteActions, gyp.generator.make.MakefileWriter.WriteCopies, gyp.generator.make.MakefileWriter.WriteRules.
gyp.generator.make.Sourceify(path)
Convert a path to its source directory form.
Referenced by gyp.generator.make.SourceifyAndQuoteSpaces, gyp.generator.make.MakefileWriter.WriteActions, gyp.generator.make.MakefileWriter.WriteCopies, gyp.generator.make.MakefileWriter.WriteMacBundleResources, gyp.generator.make.MakefileWriter.WriteMacInfoPlist, gyp.generator.make.MakefileWriter.WriteRules, gyp.generator.make.MakefileWriter.WriteSources, gyp.generator.make.MakefileWriter.WriteTarget.
gyp.generator.make.QuoteSpaces(s, quote=r"\ ")
Referenced by gyp.generator.make.SourceifyAndQuoteSpaces, gyp.generator.make.MakefileWriter.WriteActions, gyp.generator.make.MakefileWriter.WriteCopies, gyp.generator.make.MakefileWriter.WriteDoCmd, gyp.generator.make.MakefileWriter.WriteMakeRule, gyp.generator.make.MakefileWriter.WriteTarget.
gyp.generator.make.SourceifyAndQuoteSpaces(path)
Convert a path to its source directory form and quote spaces.
References gyp.generator.make.QuoteSpaces, gyp.generator.make.Sourceify.
Referenced by gyp.generator.make.WriteAutoRegenerationRule.
gyp.generator.make.WriteAutoRegenerationRule(params, root_makefile, makefile_name, build_files)
Write the target to regenerate the Makefile.
References gyp.common.EncodePOSIXShellList, gyp.common.FixIfRelativePath, gyp.RegenerateFlags, gyp.common.RelativePath, gyp.generator.make.SourceifyAndQuoteSpaces.
Referenced by gyp.generator.make.GenerateOutput.
gyp.generator.make.PerformBuild(data, configurations, params)
gyp.generator.make.GenerateOutput(target_list, target_dicts, data, params)
References gyp.common.AllTargets, gyp.common.CopyTool, gyp.common.EnsureDirExists, gyp.common.GetFlavor, gyp.xcode_emulation.MergeGlobalXcodeSettingsToSpec, gyp.common.ParseQualifiedTarget, gyp.common.RelativePath, gyp.common.UnrelativePath, gyp.generator.make.WriteAutoRegenerationRule, gyp.generator.make.WriteRootHeaderSuffixRules.