Napi::details
int Napi::details::napi_no_external_buffers_allowed
Referenced by Napi::Buffer< T >::NewOrCopy, Napi::Buffer< T >::NewOrCopy, Napi::Buffer< T >::NewOrCopy.
void Napi::details::default_finalizer(napi_env, void *data, void *)
References default_finalizer.
Referenced by default_finalizer.
napi_status Napi::details::AttachData(napi_env env, napi_value obj, FreeType *data, void *hint=nullptr)
References AttachData.
Referenced by AttachData, Napi::InstanceWrap< T >::AttachPropData, Napi::ObjectWrap< Backup >::StaticAccessor.
napi_value Napi::details::WrapCallback(Callable callback)
References Napi::Error::ThrowAsJavaScriptException, WrapCallback.
Referenced by Napi::RegisterModule, TemplatedInstanceCallback, WrapCallback.
void Napi::details::WrapVoidCallback(Callable callback)
References Napi::Error::ThrowAsJavaScriptException, WrapVoidCallback.
Referenced by Napi::details::FinalizeData< T, Finalizer, Hint >::Wrapper, Napi::details::FinalizeData< T, Finalizer, Hint >::WrapperWithHint, WrapVoidCallback.
napi_value Napi::details::TemplatedVoidCallback(napi_env env, napi_callback_info info) NAPI_NOEXCEPT
References TemplatedVoidCallback.
Referenced by Napi::PropertyDescriptor::Accessor, Napi::PropertyDescriptor::Accessor, Napi::ObjectWrap< T >::StaticMethod, Napi::ObjectWrap< T >::StaticMethod, TemplatedVoidCallback.
napi_value Napi::details::TemplatedCallback(napi_env env, napi_callback_info info) NAPI_NOEXCEPT
References TemplatedCallback.
Referenced by Napi::PropertyDescriptor::Accessor, Napi::PropertyDescriptor::Accessor, Napi::ObjectWrap< Backup >::Finalize, Napi::ObjectWrap< T >::StaticAccessor, Napi::ObjectWrap< T >::StaticAccessor, TemplatedCallback.
napi_value Napi::details::TemplatedInstanceCallback(napi_env env, napi_callback_info info) NAPI_NOEXCEPT
References Napi::Value::As, TemplatedInstanceCallback, Napi::CallbackInfo::This, WrapCallback.
Referenced by Napi::InstanceWrap< T >::InstanceAccessor, Napi::InstanceWrap< T >::InstanceAccessor, TemplatedInstanceCallback.
napi_value Napi::details::TemplatedInstanceVoidCallback(napi_env env, napi_callback_info info) NAPI_NOEXCEPT
References Napi::Value::As, TemplatedInstanceVoidCallback, Napi::CallbackInfo::This.
Referenced by Napi::InstanceWrap< T >::InstanceMethod, Napi::InstanceWrap< T >::InstanceMethod, TemplatedInstanceVoidCallback.