gyp::MSVSVersion
gyp.MSVSVersion.JoinPath(*args)
Referenced by gyp.MSVSVersion.VisualStudioVersion._SetupScriptInternal.
gyp.MSVSVersion._RegistryQueryBase(sysdir, key, value)
Use reg.exe to read a particular key. While ideally we might use the win32 module, we would like gyp to be python neutral, so for instance cygwin python lacks this module. Arguments: sysdir: The system subdirectory to attempt to launch reg.exe from. key: The registry key to read from. value: The particular value to read. Return: stdout from reg.exe, or None for failure.
Referenced by gyp.MSVSVersion._RegistryQuery.
gyp.MSVSVersion._RegistryQuery(key, value=None)
Use reg.exe to read a particular key through _RegistryQueryBase. First tries to launch from %WinDir%\Sysnative to avoid WoW64 redirection. If that fails, it falls back to System32. Sysnative is available on Vista and up and available on Windows Server 2003 and XP through KB patch 942589. Note that Sysnative will always fail if using 64-bit python due to it being a virtual directory and System32 will work correctly in the first place. KB 942589 - http://support.microsoft.com/kb/942589/en-us. Arguments: key: The registry key. value: The particular registry value to read (optional). Return: stdout from reg.exe, or None for failure.
References gyp.MSVSVersion._RegistryQueryBase.
Referenced by gyp.MSVSVersion._RegistryGetValue.
gyp.MSVSVersion._RegistryGetValueUsingWinReg(key, value)
Use the _winreg module to obtain the value of a registry key. Args: key: The registry key. value: The particular registry value to read. Return: contents of the registry key's value, or None on failure. Throws ImportError if winreg is unavailable.
Referenced by gyp.MSVSVersion._RegistryGetValue.
gyp.MSVSVersion._RegistryGetValue(key, value)
Use _winreg or reg.exe to obtain the value of a registry key. Using _winreg is preferable because it solves an issue on some corporate environments where access to reg.exe is locked down. However, we still need to fallback to reg.exe for the case where the _winreg module is not available (for example in cygwin python). Args: key: The registry key. value: The particular registry value to read. Return: contents of the registry key's value, or None on failure.
References gyp.MSVSVersion._RegistryGetValueUsingWinReg, gyp.MSVSVersion._RegistryQuery.
Referenced by gyp.MSVSVersion._DetectVisualStudioVersions.
gyp.MSVSVersion._CreateVersion(name, path, sdk_based=False)
Sets up MSVS project generation. Setup is based off the GYP_MSVS_VERSION environment variable or whatever is autodetected if GYP_MSVS_VERSION is not explicitly specified. If a version is passed in that doesn't match a value in versions python will throw a error.
Referenced by gyp.MSVSVersion._DetectVisualStudioVersions, gyp.MSVSVersion.SelectVisualStudioVersion.
gyp.MSVSVersion._ConvertToCygpath(path)
Convert to cygwin path if we are using cygwin.
Referenced by gyp.MSVSVersion._DetectVisualStudioVersions.
gyp.MSVSVersion._DetectVisualStudioVersions(versions_to_check, force_express)
Collect the list of installed visual studio versions. Returns: A list of visual studio versions installed in descending order of usage preference. Base this on the registry and a quick check if devenv.exe exists. Possibilities are: 2005(e) - Visual Studio 2005 (8) 2008(e) - Visual Studio 2008 (9) 2010(e) - Visual Studio 2010 (10) 2012(e) - Visual Studio 2012 (11) 2013(e) - Visual Studio 2013 (12) 2015 - Visual Studio 2015 (14) 2017 - Visual Studio 2017 (15) 2019 - Visual Studio 2019 (16) 2022 - Visual Studio 2022 (17) Where (e) is e for express editions of MSVS and blank otherwise.
References gyp.MSVSVersion._ConvertToCygpath, gyp.MSVSVersion._CreateVersion, gyp.MSVSVersion._RegistryGetValue.
Referenced by gyp.MSVSVersion.SelectVisualStudioVersion.
gyp.MSVSVersion.SelectVisualStudioVersion(version="auto", allow_fallback=True)
Select which version of Visual Studio projects to generate. Arguments: version: Hook to allow caller to force a particular version (vs auto). Returns: An object representing a visual studio project format version.
References gyp.MSVSVersion._CreateVersion, gyp.MSVSVersion._DetectVisualStudioVersions.
Referenced by gyp.msvs_emulation.GetVSVersion, test_gyp.print_configuration_info.