gyp::simple_copy
list gyp::simple_copy.__all__
dict gyp::simple_copy._deepcopy_dispatch
gyp::simple_copy.types
gyp.simple_copy.deepcopy(x)
Deep copy operation on gyp objects such as strings, ints, dicts and lists. More than twice as fast as copy.deepcopy but much less generic.
Referenced by gyp.simple_copy._deepcopy_dict, gyp.simple_copy._deepcopy_list, gyp.input.ExpandVariables, gyp.input.LoadTargetBuildFile, gyp.input.ProcessToolsetsInDict, gyp.input.SetUpConfigurations.
gyp.simple_copy._deepcopy_atomic(x)
gyp.simple_copy._deepcopy_list(x)
References gyp.simple_copy.deepcopy.
gyp.simple_copy._deepcopy_dict(x)
References gyp.simple_copy.deepcopy.