gyp::generator::eclipse
bool gyp::generator::eclipse.generator_wants_static_library_dependencies_adjusted
dict gyp::generator::eclipse.generator_default_variables
gyp.generator.eclipse.CalculateVariables(default_variables, params)
References gyp.msvs_emulation.CalculateCommonVariables, gyp.common.GetFlavor.
gyp.generator.eclipse.CalculateGeneratorInputInfo(params)
Calculate the generator specific info that gets fed to input (called by gyp).
gyp.generator.eclipse.GetAllIncludeDirectories(target_list, target_dicts, shared_intermediate_dirs, config_name, params, compiler_path)
Calculate the set of include directories to be used. Returns: A list including all the include_dir's specified for every target followed by any include directories that were added as cflag compiler options.
References gyp.common.GetFlavor.
Referenced by gyp.generator.eclipse.GenerateCdtSettingsFile.
gyp.generator.eclipse.GetCompilerPath(target_list, data, options)
Determine a command that can be used to invoke the compiler. Returns: If this is a gyp project that has explicit make settings, try to determine the compiler from that. Otherwise, see if a compiler was specified via the CC_target environment variable.
References gyp.common.ParseQualifiedTarget.
Referenced by gyp.generator.eclipse.GenerateCdtSettingsFile.
gyp.generator.eclipse.GetAllDefines(target_list, target_dicts, data, config_name, params, compiler_path)
Calculate the defines for a project. Returns: A dict that includes explicit defines declared in gyp files along with all of the default defines that the compiler uses.
References gyp.common.GetFlavor.
Referenced by gyp.generator.eclipse.GenerateCdtSettingsFile.
gyp.generator.eclipse.WriteIncludePaths(out, eclipse_langs, include_dirs)
Write the includes section of a CDT settings export file.
Referenced by gyp.generator.eclipse.GenerateCdtSettingsFile.
gyp.generator.eclipse.WriteMacros(out, eclipse_langs, defines)
Write the macros section of a CDT settings export file.
Referenced by gyp.generator.eclipse.GenerateCdtSettingsFile.
gyp.generator.eclipse.GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
References gyp.generator.eclipse.GenerateCdtSettingsFile, gyp.generator.eclipse.GenerateClasspathFile.
Referenced by gyp.generator.eclipse.GenerateOutput.
gyp.generator.eclipse.GenerateCdtSettingsFile(target_list, target_dicts, data, params, config_name, out_name, options, shared_intermediate_dirs)
References gyp.common.EnsureDirExists, gyp.generator.eclipse.GetAllDefines, gyp.generator.eclipse.GetAllIncludeDirectories, gyp.generator.eclipse.GetCompilerPath, gyp.generator.eclipse.WriteIncludePaths, gyp.generator.eclipse.WriteMacros.
Referenced by gyp.generator.eclipse.GenerateOutputForConfig.
gyp.generator.eclipse.GenerateClasspathFile(target_list, target_dicts, toplevel_dir, toplevel_build, out_name)
Generates a classpath file suitable for symbol navigation and code completion of Java code (such as in Android projects) by finding all .java and .jar files used as action inputs.
References gyp.common.EnsureDirExists, gyp.generator.eclipse.GetJavaJars, gyp.generator.eclipse.GetJavaSourceDirs.
Referenced by gyp.generator.eclipse.GenerateOutputForConfig.
gyp.generator.eclipse.GetJavaJars(target_list, target_dicts, toplevel_dir)
Generates a sequence of all .jars used as inputs.
Referenced by gyp.generator.eclipse.GenerateClasspathFile.
gyp.generator.eclipse.GetJavaSourceDirs(target_list, target_dicts, toplevel_dir)
Generates a sequence of all likely java package root directories.
Referenced by gyp.generator.eclipse.GenerateClasspathFile.
gyp.generator.eclipse.GenerateOutput(target_list, target_dicts, data, params)
Generate an XML settings file that can be imported into a CDT project.
References gyp.generator.eclipse.GenerateOutputForConfig.