gyp::generator::compile_commands_json
list gyp::generator::compile_commands_json.generator_additional_non_configuration_keys
list gyp::generator::compile_commands_json.generator_additional_path_sections
list gyp::generator::compile_commands_json.generator_extra_sources_for_rules
gyp::generator::compile_commands_json.generator_filelist_paths
bool gyp::generator::compile_commands_json.generator_supports_multiple_toolsets
bool gyp::generator::compile_commands_json.generator_wants_sorted_dependencies
dict gyp::generator::compile_commands_json.generator_default_variables
gyp.generator.compile_commands_json.IsMac(params)
References gyp.common.GetFlavor.
Referenced by gyp.generator.compile_commands_json.AddCommandsForTarget, gyp.generator.compile_commands_json.GenerateOutput.
gyp.generator.compile_commands_json.CalculateVariables(default_variables, params)
References gyp.common.GetFlavor.
gyp.generator.compile_commands_json.AddCommandsForTarget(cwd, target, params, per_config_commands)
References gyp.common.EncodePOSIXShellArgument, gyp.common.EncodePOSIXShellList, gyp.generator.compile_commands_json.IsMac.
Referenced by gyp.generator.compile_commands_json.GenerateOutput.
gyp.generator.compile_commands_json.GenerateOutput(target_list, target_dicts, data, params)
References gyp.generator.compile_commands_json.AddCommandsForTarget, gyp.common.EnsureDirExists, gyp.generator.compile_commands_json.IsMac, gyp.xcode_emulation.MergeGlobalXcodeSettingsToSpec, gyp.common.ParseQualifiedTarget.
gyp.generator.compile_commands_json.PerformBuild(data, configurations, params)