gyp::MSVSSettings
dict gyp::MSVSSettings._msvs_validators
dict gyp::MSVSSettings._msbuild_validators
dict gyp::MSVSSettings._msvs_to_msbuild_converters
dict gyp::MSVSSettings._msbuild_name_of_tool
gyp::MSVSSettings._boolean
gyp::MSVSSettings._integer
gyp::MSVSSettings._string
gyp::MSVSSettings._file_name
gyp::MSVSSettings._folder_name
gyp::MSVSSettings._file_list
gyp::MSVSSettings._folder_list
gyp::MSVSSettings._string_list
gyp::MSVSSettings._newly_boolean
tuple gyp::MSVSSettings.fix_vc_macro_slashes_regex_list
gyp::MSVSSettings.fix_vc_macro_slashes_regex
gyp::MSVSSettings._EXCLUDED_SUFFIX_RE
gyp::MSVSSettings._compile
gyp::MSVSSettings._link
gyp::MSVSSettings._midl
gyp::MSVSSettings._rc
gyp::MSVSSettings._lib
gyp::MSVSSettings._manifest
gyp::MSVSSettings._masm
gyp::MSVSSettings._armasm
gyp::MSVSSettings._subsystem_enumeration
gyp::MSVSSettings._target_machine_enumeration
gyp.MSVSSettings._AddTool(tool)
Adds a tool to the four dictionaries used to process settings. This only defines the tool. Each setting also needs to be added. Args: tool: The _Tool object to be added.
gyp.MSVSSettings._GetMSBuildToolSettings(msbuild_settings, tool)
Returns an MSBuild tool dictionary. Creates it if needed.
Referenced by gyp.MSVSSettings._ConvertedToAdditionalOption, gyp.MSVSSettings._CustomGeneratePreprocessedFile, gyp.MSVSSettings._Renamed.
gyp.MSVSSettings._Same(tool, name, setting_type)
Defines a setting that has the same name in MSVS and MSBuild. Args: tool: a dictionary that gives the names of the tool for MSVS and MSBuild. name: the name of the setting. setting_type: the type of this setting.
References gyp.MSVSSettings._Renamed.
gyp.MSVSSettings._Renamed(tool, msvs_name, msbuild_name, setting_type)
Defines a setting for which the name has changed. Args: tool: a dictionary that gives the names of the tool for MSVS and MSBuild. msvs_name: the name of the MSVS setting. msbuild_name: the name of the MSBuild setting. setting_type: the type of this setting.
References gyp.MSVSSettings._GetMSBuildToolSettings.
Referenced by gyp.MSVSSettings._Same.
gyp.MSVSSettings._Moved(tool, settings_name, msbuild_tool_name, setting_type)
References gyp.MSVSSettings._MovedAndRenamed.
gyp.MSVSSettings._MovedAndRenamed(tool, msvs_settings_name, msbuild_tool_name, msbuild_settings_name, setting_type)
Defines a setting that may have moved to a new section. Args: tool: a dictionary that gives the names of the tool for MSVS and MSBuild. msvs_settings_name: the MSVS name of the setting. msbuild_tool_name: the name of the MSBuild tool to place the setting under. msbuild_settings_name: the MSBuild name of the setting. setting_type: the type of this setting.
Referenced by gyp.MSVSSettings._Moved.
gyp.MSVSSettings._MSVSOnly(tool, name, setting_type)
Defines a setting that is only found in MSVS. Args: tool: a dictionary that gives the names of the tool for MSVS and MSBuild. name: the name of the setting. setting_type: the type of this setting.
gyp.MSVSSettings._MSBuildOnly(tool, name, setting_type)
Defines a setting that is only found in MSBuild. Args: tool: a dictionary that gives the names of the tool for MSVS and MSBuild. name: the name of the setting. setting_type: the type of this setting.
gyp.MSVSSettings._ConvertedToAdditionalOption(tool, msvs_name, flag)
Defines a setting that's handled via a command line option in MSBuild. Args: tool: a dictionary that gives the names of the tool for MSVS and MSBuild. msvs_name: the name of the MSVS setting that if 'true' becomes a flag flag: the flag to insert at the end of the AdditionalOptions
References gyp.MSVSSettings._GetMSBuildToolSettings.
gyp.MSVSSettings._CustomGeneratePreprocessedFile(tool, msvs_name)
References gyp.MSVSSettings._GetMSBuildToolSettings.
gyp.MSVSSettings._ValidateExclusionSetting(setting, settings, error_msg, stderr=sys.stderr)
Verify that 'setting' is valid if it is generated from an exclusion list. If the setting appears to be generated from an exclusion list, the root name is checked. Args: setting: A string that is the setting name to validate settings: A dictionary where the keys are valid settings error_msg: The message to emit in the event of error stderr: The stream receiving the error messages.
Referenced by gyp.MSVSSettings._ValidateSettings, gyp.MSVSSettings.ConvertToMSBuildSettings.
gyp.MSVSSettings.FixVCMacroSlashes(s)
Replace macros which have excessive following slashes. These macros are known to have a built-in trailing slash. Furthermore, many scripts hiccup on processing paths with extra slashes in the middle. This list is probably not exhaustive. Add as needed.
Referenced by gyp.MSVSSettings.ConvertVCMacrosToMSBuild.
gyp.MSVSSettings.ConvertVCMacrosToMSBuild(s)
Convert the MSVS macros found in the string to the MSBuild equivalent. This list is probably not exhaustive. Add as needed.
References gyp.MSVSSettings.FixVCMacroSlashes.
Referenced by gyp.MSVSSettings._String.ConvertToMSBuild, gyp.MSVSSettings._StringList.ConvertToMSBuild.
gyp.MSVSSettings.ConvertToMSBuildSettings(msvs_settings, stderr=sys.stderr)
Converts MSVS settings (VS2008 and earlier) to MSBuild settings (VS2010+). Args: msvs_settings: A dictionary. The key is the tool name. The values are themselves dictionaries of settings and their values. stderr: The stream receiving the error messages. Returns: A dictionary of MSBuild settings. The key is either the MSBuild tool name or the empty string (for the global settings). The values are themselves dictionaries of settings and their values.
References gyp.MSVSSettings._ValidateExclusionSetting.
gyp.MSVSSettings.ValidateMSVSSettings(settings, stderr=sys.stderr)
Validates that the names of the settings are valid for MSVS. Args: settings: A dictionary. The key is the tool name. The values are themselves dictionaries of settings and their values. stderr: The stream receiving the error messages.
References gyp.MSVSSettings._ValidateSettings.
gyp.MSVSSettings.ValidateMSBuildSettings(settings, stderr=sys.stderr)
Validates that the names of the settings are valid for MSBuild. Args: settings: A dictionary. The key is the tool name. The values are themselves dictionaries of settings and their values. stderr: The stream receiving the error messages.
References gyp.MSVSSettings._ValidateSettings.
gyp.MSVSSettings._ValidateSettings(validators, settings, stderr)
Validates that the settings are valid for MSBuild or MSVS. We currently only validate the names of the settings, not their values. Args: validators: A dictionary of tools and their validators. settings: A dictionary. The key is the tool name. The values are themselves dictionaries of settings and their values. stderr: The stream receiving the error messages.
References gyp.MSVSSettings._ValidateExclusionSetting.
Referenced by gyp.MSVSSettings.ValidateMSBuildSettings, gyp.MSVSSettings.ValidateMSVSSettings.