gyp::MSVSUtil
dict gyp::MSVSUtil.TARGET_TYPE_EXT
gyp.MSVSUtil._GetLargePdbShimCcPath()
Returns the path of the large_pdb_shim.cc file.
Referenced by gyp.MSVSUtil.InsertLargePdbShims.
gyp.MSVSUtil._DeepCopySomeKeys(in_dict, keys)
Performs a partial deep-copy on |in_dict|, only copying the keys in |keys|. Arguments: in_dict: The dictionary to copy. keys: The keys to be copied. If a key is in this list and doesn't exist in |in_dict| this is not an error. Returns: The partially deep-copied dictionary.
Referenced by gyp.MSVSUtil.InsertLargePdbShims.
gyp.MSVSUtil._SuffixName(name, suffix)
Add a suffix to the end of a target. Arguments: name: name of the target (foo#target) suffix: the suffix to be added Returns: Target name with suffix added (foo_suffix#target)
Referenced by gyp.MSVSUtil._ShardName, gyp.MSVSUtil.InsertLargePdbShims.
gyp.MSVSUtil._ShardName(name, number)
Add a shard number to the end of a target. Arguments: name: name of the target (foo#target) number: shard number Returns: Target name with shard added (foo_1#target)
References gyp.MSVSUtil._SuffixName.
Referenced by gyp.MSVSUtil.ShardTargets.
gyp.MSVSUtil.ShardTargets(target_list, target_dicts)
Shard some targets apart to work around the linkers limits. Arguments: target_list: List of target pairs: 'base/base.gyp:base'. target_dicts: Dict of target properties keyed on target pair. Returns: Tuple of the new sharded versions of the inputs.
References gyp.MSVSUtil._ShardName.
gyp.MSVSUtil._GetPdbPath(target_dict, config_name, vars)
Returns the path to the PDB file that will be generated by a given configuration. The lookup proceeds as follows: - Look for an explicit path in the VCLinkerTool configuration block. - Look for an 'msvs_large_pdb_path' variable. - Use '<(PRODUCT_DIR)/<(product_name).(exe|dll).pdb' if 'product_name' is specified. - Use '<(PRODUCT_DIR)/<(target_name).(exe|dll).pdb'. Arguments: target_dict: The target dictionary to be searched. config_name: The name of the configuration of interest. vars: A dictionary of common GYP variables with generator-specific values. Returns: The path of the corresponding PDB file.
Referenced by gyp.MSVSUtil.InsertLargePdbShims.
gyp.MSVSUtil.InsertLargePdbShims(target_list, target_dicts, vars)
Insert a shim target that forces the linker to use 4KB pagesize PDBs. This is a workaround for targets with PDBs greater than 1GB in size, the limit for the 1KB pagesize PDBs created by the linker by default. Arguments: target_list: List of target pairs: 'base/base.gyp:base'. target_dicts: Dict of target properties keyed on target pair. vars: A dictionary of common GYP variables with generator-specific values. Returns: Tuple of the shimmed version of the inputs.
References gyp.MSVSUtil._DeepCopySomeKeys, gyp.MSVSUtil._GetLargePdbShimCcPath, gyp.MSVSUtil._GetPdbPath, gyp.MSVSUtil._SuffixName.