gyp::msvs_emulation
gyp::msvs_emulation.windows_quoter_regex
gyp::msvs_emulation.vs_version
gyp.msvs_emulation.QuoteForRspFile(arg, quote_cmd=True)
Quote a command line argument so that it appears as one argument when processed via cmd.exe and parsed by CommandLineToArgvW (as is typical for Windows programs).
Referenced by gyp.msvs_emulation.EncodeRspFileList, gyp.generator.ninja.QuoteShellArgument.
gyp.msvs_emulation.EncodeRspFileList(args, quote_cmd)
Process a list of arguments using QuoteCmdExeArgument.
References gyp.msvs_emulation.QuoteForRspFile.
Referenced by gyp.generator.ninja.NinjaWriter.WriteNewNinjaRule.
gyp.msvs_emulation._GenericRetrieve(root, default, path)
Given a list of dictionary keys |path| and a tree of dicts |root|, find value at path, or return |default| if any of the path doesn't exist.
References gyp.msvs_emulation._GenericRetrieve.
Referenced by gyp.msvs_emulation._GenericRetrieve, gyp.msvs_emulation.MsvsSettings._GetAndMunge.
gyp.msvs_emulation._AddPrefix(element, prefix)
Add |prefix| to |element| or each subelement if element is iterable.
Referenced by gyp.msvs_emulation.MsvsSettings._GetAndMunge.
gyp.msvs_emulation._DoRemapping(element, map)
If |element| then remap it through |map|. If |element| is iterable then each item will be remapped. Any elements not found will be removed.
Referenced by gyp.msvs_emulation.MsvsSettings._GetAndMunge.
gyp.msvs_emulation._AppendOrReturn(append, element)
If |append| is None, simply return |element|. If |append| is not None, then add |element| to it, adding each item in |element| if it's a list or tuple.
Referenced by gyp.msvs_emulation.MsvsSettings._GetAndMunge.
gyp.msvs_emulation._FindDirectXInstallation()
Try to find an installation location for the DirectX SDK. Check for the standard environment variable, and if that doesn't exist, try to find via the registry. May return None if not found in either location.
Referenced by gyp.msvs_emulation.GetGlobalVSMacroEnv.
gyp.msvs_emulation.GetGlobalVSMacroEnv(vs_version)
Get a dict of variables mapping internal VS macro names to their gyp equivalents. Returns all variables that are independent of the target.
References gyp.msvs_emulation._FindDirectXInstallation.
Referenced by gyp.msvs_emulation.ExtractSharedMSVSSystemIncludes, gyp.msvs_emulation.MsvsSettings.GetVSMacroEnv.
gyp.msvs_emulation.ExtractSharedMSVSSystemIncludes(configs, generator_flags)
Finds msvs_system_include_dirs that are common to all targets, removes them from all targets, and returns an OrderedSet containing them.
References gyp.msvs_emulation.ExpandMacros, gyp.msvs_emulation.GetGlobalVSMacroEnv, gyp.msvs_emulation.GetVSVersion.
Referenced by gyp.generator.ninja.GenerateOutputForConfig.
gyp.msvs_emulation._LanguageMatchesForPch(source_ext, pch_source_ext)
Referenced by gyp.msvs_emulation.MsvsSettings._GetPchFlags, gyp.msvs_emulation.PrecompiledHeader.GetObjDependencies.
gyp.msvs_emulation.GetVSVersion(generator_flags)
References gyp.MSVSVersion.SelectVisualStudioVersion.
Referenced by gyp.msvs_emulation._GetVsvarsSetupArgs, gyp.msvs_emulation.CalculateCommonVariables, gyp.msvs_emulation.ExtractSharedMSVSSystemIncludes, gyp.msvs_emulation.GenerateEnvironmentFiles.
gyp.msvs_emulation._GetVsvarsSetupArgs(generator_flags, arch)
References gyp.msvs_emulation.GetVSVersion.
gyp.msvs_emulation.ExpandMacros(string, expansions)
Expand $(Variable) per expansions dict. See MsvsSettings.GetVSMacroEnv for the canonical way to retrieve a suitable dict.
Referenced by gyp.msvs_emulation.MsvsSettings.ConvertVSMacros, gyp.msvs_emulation.ExtractSharedMSVSSystemIncludes, gyp.generator.ninja.NinjaWriter.GypPathToNinja.
gyp.msvs_emulation._ExtractImportantEnvironment(output_of_set)
Extracts environment variables required for the toolchain to run from a textual dump output by the cmd.exe 'set' command.
Referenced by gyp.msvs_emulation.GenerateEnvironmentFiles.
gyp.msvs_emulation._FormatAsEnvironmentBlock(envvar_dict)
Format as an 'environment block' directly suitable for CreateProcess. Briefly this is a list of key=value\0, terminated by an additional \0. See CreateProcess documentation for more details.
Referenced by gyp.msvs_emulation.GenerateEnvironmentFiles.
gyp.msvs_emulation._ExtractCLPath(output_of_where)
Gets the path to cl.exe based on the output of calling the environment setup batch file, followed by the equivalent of `where`.
Referenced by gyp.msvs_emulation.GenerateEnvironmentFiles.
gyp.msvs_emulation.GenerateEnvironmentFiles(toplevel_build_dir, generator_flags, system_includes, open_out)
It's not sufficient to have the absolute path to the compiler, linker, etc. on Windows, as those tools rely on .dlls being in the PATH. We also need to support both x86 and x64 compilers within the same build (to support msvs_target_platform hackery). Different architectures require a different compiler binary, and different supporting environment variables (INCLUDE, LIB, LIBPATH). So, we extract the environment here, wrap all invocations of compiler tools (cl, link, lib, rc, midl, etc.) via win_tool.py which sets up the environment, and then we do not prefix the compiler with an absolute path, instead preferring something like "cl.exe" in the rule which will then run whichever the environment setup has put in the path. When the following procedure to generate environment files does not meet your requirement (e.g. for custom toolchains), you can pass "-G ninja_use_custom_environment_files" to the gyp to suppress file generation and use custom environment files prepared by yourself.
References gyp.msvs_emulation._ExtractCLPath, gyp.msvs_emulation._ExtractImportantEnvironment, gyp.msvs_emulation._FormatAsEnvironmentBlock, gyp.msvs_emulation.GetVSVersion.
Referenced by gyp.generator.ninja.GenerateOutputForConfig.
gyp.msvs_emulation.VerifyMissingSources(sources, build_dir, generator_flags, gyp_to_ninja)
Emulate behavior of msvs_error_on_missing_sources present in the msvs generator: Check that all regular source files, i.e. not created at run time, exist on disk. Missing files cause needless recompilation when building via VS, and we want this check to match for people/bots that build using ninja, so they're not surprised when the VS build fails.
gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
References gyp.msvs_emulation.GetVSVersion.
Referenced by gyp.generator.analyzer.CalculateVariables, gyp.generator.dump_dependency_json.CalculateVariables, gyp.generator.eclipse.CalculateVariables, gyp.generator.ninja.CalculateVariables.