gyp::generator::msvs
gyp::generator::msvs.VALID_MSVS_GUID_CHARS
gyp::generator::msvs.generator_supports_multiple_toolsets
dict gyp::generator::msvs.generator_default_variables
list gyp::generator::msvs.generator_additional_path_sections
list gyp::generator::msvs.generator_additional_non_configuration_keys
gyp::generator::msvs.generator_filelist_paths
list gyp::generator::msvs.precomp_keys
gyp::generator::msvs.cached_username
gyp::generator::msvs.cached_domain
gyp::generator::msvs.fixpath_prefix
gyp::generator::msvs.quote_replacer_regex
gyp::generator::msvs.delimiters_replacer_regex
gyp::generator::msvs.quote_replacer_regex2
gyp::generator::msvs.MSVS_VARIABLE_REFERENCE
gyp.generator.msvs._GetDomainAndUserName()
Referenced by gyp.generator.msvs._CreateMSVSUserFile.
gyp.generator.msvs._NormalizedSource(source)
Normalize the path. But not if that gets rid of a variable, as this may expand to something larger than one directory. Arguments: source: The path to be normalize.d Returns: The normalized path.
Referenced by gyp.generator.msvs._AddNormalizedSources, gyp.generator.msvs._ConvertSourcesToFilterHierarchy, gyp.generator.msvs._FixPath, gyp.generator.msvs._GenerateMSVSProject, gyp.generator.msvs._PrepareListOfSources.
gyp.generator.msvs._FixPath(path, separator="\\")
Convert paths to a form that will make sense in a vcproj file. Arguments: path: The path to convert, may contain / etc. Returns: The path with all slashes made into backslashes.
References gyp.generator.msvs._IsWindowsAbsPath, gyp.generator.msvs._NormalizedSource.
Referenced by gyp.generator.msvs._AddCustomBuildToolForMSVS, gyp.generator.msvs._AddMSBuildAction, gyp.generator.msvs._AddSources2, gyp.generator.msvs._AdjustSourcesForRules, gyp.generator.msvs._BuildCommandLineForRuleRaw, gyp.generator.msvs._FixPaths, gyp.generator.msvs._GetCopies, gyp.generator.msvs._GetExcludedFilesFromBuild, gyp.generator.msvs._GetModuleDefinition, gyp.generator.msvs._GetMSBuildAttributes, gyp.generator.msvs._GetMSBuildConfigurationGlobalProperties, gyp.generator.msvs._GetMSVSAttributes, gyp.generator.msvs._GetPrecompileRelatedFiles, gyp.generator.msvs._HandlePreCompiledHeaders.
gyp.generator.msvs._IsWindowsAbsPath(path)
On Cygwin systems Python needs a little help determining if a path is an absolute Windows path or not, so that it does not treat those as relative, which results in bad paths like: '..\\C:\\<some path>\\some_source_code_file.cc'
Referenced by gyp.generator.msvs._FixPath.
gyp.generator.msvs._FixPaths(paths, separator="\\")
Fix each of the paths of the list.
References gyp.generator.msvs._FixPath.
Referenced by gyp.generator.msvs._AddCustomBuildToolForMSVS, gyp.generator.msvs._AddMSBuildAction, gyp.generator.msvs._AdjustSourcesAndConvertToFilterHierarchy, gyp.generator.msvs._AdjustSourcesForRules, gyp.generator.msvs._FilterActionsFromExcluded, gyp.generator.msvs._GenerateExternalRules, gyp.generator.msvs._GenerateNativeRulesForMSVS, gyp.generator.msvs._GetIncludeDirs, gyp.generator.msvs._GetLibraryDirs, gyp.generator.msvs._GetMSBuildPropertySheets, gyp.generator.msvs._GetMSVSAttributes, gyp.generator.msvs._RuleInputsAndOutputs.
gyp.generator.msvs._ConvertSourcesToFilterHierarchy(sources, prefix=None, excluded=None, list_excluded=True, msvs_version=None)
Converts a list split source file paths into a vcproj folder hierarchy. Arguments: sources: A list of source file paths split. prefix: A list of source file path layers meant to apply to each of sources. excluded: A set of excluded files. msvs_version: A MSVSVersion object. Returns: A hierarchy of filenames and MSVSProject.Filter objects that matches the layout of the source tree. For example: _ConvertSourcesToFilterHierarchy([['a', 'bob1.c'], ['b', 'bob2.c']], prefix=['joe']) --> [MSVSProject.Filter('a', contents=['joe\\a\\bob1.c']), MSVSProject.Filter('b', contents=['joe\\b\\bob2.c'])]
References gyp.generator.msvs._ConvertSourcesToFilterHierarchy, gyp.generator.msvs._NormalizedSource.
Referenced by gyp.generator.msvs._AdjustSourcesAndConvertToFilterHierarchy, gyp.generator.msvs._ConvertSourcesToFilterHierarchy.
gyp.generator.msvs._ToolAppend(tools, tool_name, setting, value, only_if_unset=False)
References gyp.generator.msvs._ToolSetOrAppend.
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._ToolSetOrAppend(tools, tool_name, setting, value, only_if_unset=False)
Referenced by gyp.generator.msvs._FinalizeMSBuildSettings, gyp.generator.msvs._ToolAppend.
gyp.generator.msvs._ConfigTargetVersion(config_data)
Referenced by gyp.generator.msvs._GetMSBuildConfigurationDetails.
gyp.generator.msvs._ConfigPlatform(config_data)
Referenced by gyp.generator.msvs._ConfigFullName, gyp.generator.msvs._GetMSBuildGlobalProperties, gyp.generator.msvs._GetPlatformOverridesOfProject, gyp.generator.msvs._GetUniquePlatforms.
gyp.generator.msvs._ConfigBaseName(config_name, platform_name)
Referenced by gyp.generator.msvs._GetPlatformOverridesOfProject.
gyp.generator.msvs._ConfigFullName(config_name, config_data)
References gyp.generator.msvs._ConfigPlatform.
Referenced by gyp.generator.msvs._AddConfigurationToMSVS, gyp.generator.msvs._AddCustomBuildToolForMSVS, gyp.generator.msvs._ExcludeFilesFromBeingBuilt, gyp.generator.msvs._GetPlatformOverridesOfProject, gyp.generator.msvs._HandlePreCompiledHeaders, gyp.generator.msvs._WriteMSVSUserFile, gyp.generator.msvs.GenerateOutput.
gyp.generator.msvs._ConfigWindowsTargetPlatformVersion(config_data, version)
Referenced by gyp.generator.msvs._GetMSBuildGlobalProperties.
gyp.generator.msvs._BuildCommandLineForRuleRaw(spec, cmd, cygwin_shell, has_input_path, quote_cmd, do_setup_env)
References gyp.generator.msvs._FixPath.
Referenced by gyp.generator.msvs._BuildCommandLineForRule, gyp.generator.msvs._GenerateExternalRules, gyp.generator.msvs._GetMSBuildExternalBuilderTargets.
gyp.generator.msvs._BuildCommandLineForRule(spec, rule, has_input_path, do_setup_env)
References gyp.generator.msvs._BuildCommandLineForRuleRaw.
Referenced by gyp.generator.msvs._AddActions, gyp.generator.msvs._GenerateNativeRulesForMSVS.
gyp.generator.msvs._AddActionStep(actions_dict, inputs, outputs, description, command)
Merge action into an existing list of actions. Care must be taken so that actions which have overlapping inputs either don't get assigned to the same input, or get collapsed into one. Arguments: actions_dict: dictionary keyed on input name, which maps to a list of dicts describing the actions attached to that input file. inputs: list of inputs outputs: list of outputs description: description of the action command: command line to execute
Referenced by gyp.generator.msvs._AddActions, gyp.generator.msvs._AddCopies, gyp.generator.msvs._GenerateExternalRules.
gyp.generator.msvs._AddCustomBuildToolForMSVS(p, spec, primary_input, inputs, outputs, description, cmd)
Add a custom build tool to execute something. Arguments: p: the target project spec: the target project dict primary_input: input file to attach the build tool to inputs: list of inputs outputs: list of outputs description: description of the action cmd: command line to execute
References gyp.generator.msvs._ConfigFullName, gyp.generator.msvs._FixPath, gyp.generator.msvs._FixPaths.
Referenced by gyp.generator.msvs._AddAccumulatedActionsToMSVS.
gyp.generator.msvs._AddAccumulatedActionsToMSVS(p, spec, actions_dict)
Add actions accumulated into an actions_dict, merging as needed. Arguments: p: the target project spec: the target project dict actions_dict: dictionary keyed on input name, which maps to a list of dicts describing the actions attached to that input file.
References gyp.generator.msvs._AddCustomBuildToolForMSVS.
Referenced by gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._RuleExpandPath(path, input_file)
Given the input file to which a rule applied, string substitute a path. Arguments: path: a path to string expand input_file: the file to which the rule applied. Returns: The string substituted path.
Referenced by gyp.generator.msvs._GenerateExternalRules, gyp.generator.msvs._RuleInputsAndOutputs.
gyp.generator.msvs._FindRuleTriggerFiles(rule, sources)
Find the list of files which a particular rule applies to. Arguments: rule: the rule in question sources: the set of all known source files for this project Returns: The list of sources that trigger a particular rule.
Referenced by gyp.generator.msvs._AdjustSourcesForRules, gyp.generator.msvs._GenerateExternalRules.
gyp.generator.msvs._RuleInputsAndOutputs(rule, trigger_file)
Find the inputs and outputs generated by a rule. Arguments: rule: the rule in question. trigger_file: the main trigger for this rule. Returns: The pair of (inputs, outputs) involved in this rule.
References gyp.generator.msvs._FixPaths, gyp.generator.msvs._RuleExpandPath.
Referenced by gyp.generator.msvs._AdjustSourcesForRules, gyp.generator.msvs._GenerateExternalRules.
gyp.generator.msvs._GenerateNativeRulesForMSVS(p, rules, output_dir, spec, options)
Generate a native rules file. Arguments: p: the target project rules: the set of rules to include output_dir: the directory in which the project/gyp resides spec: the project dict options: global generator options
References gyp.generator.msvs._BuildCommandLineForRule, gyp.generator.msvs._FixPaths.
Referenced by gyp.generator.msvs._GenerateRulesForMSVS.
gyp.generator.msvs._Cygwinify(path)
Referenced by gyp.generator.msvs._GenerateExternalRules.
gyp.generator.msvs._GenerateExternalRules(rules, output_dir, spec, sources, options, actions_to_add)
Generate an external makefile to do a set of rules. Arguments: rules: the list of rules to include output_dir: path containing project and gyp files spec: project specification data sources: set of sources known options: global generator options actions_to_add: The list of actions we will add to.
References gyp.generator.msvs._AddActionStep, gyp.generator.msvs._BuildCommandLineForRuleRaw, gyp.generator.msvs._Cygwinify, gyp.generator.msvs._FindRuleTriggerFiles, gyp.generator.msvs._FixPaths, gyp.generator.msvs._RuleExpandPath, gyp.generator.msvs._RuleInputsAndOutputs, gyp.common.WriteOnDiff.
Referenced by gyp.generator.msvs._GenerateRulesForMSBuild, gyp.generator.msvs._GenerateRulesForMSVS.
gyp.generator.msvs._EscapeEnvironmentVariableExpansion(s)
Escapes % characters. Escapes any % characters so that Windows-style environment variable expansions will leave them alone. See http://connect.microsoft.com/VisualStudio/feedback/details/106127/cl-d-name-text-containing-percentage-characters-doesnt-compile to understand why we have to do this. Args: s: The string to be escaped. Returns: The escaped string.
Referenced by gyp.generator.msvs._EscapeCppDefineForMSBuild, gyp.generator.msvs._EscapeCppDefineForMSVS.
gyp.generator.msvs._EscapeCommandLineArgumentForMSVS(s)
Escapes a Windows command-line argument. So that the Win32 CommandLineToArgv function will turn the escaped result back into the original string. See http://msdn.microsoft.com/en-us/library/17w5ykft.aspx ("Parsing C++ Command-Line Arguments") to understand why we have to do this. Args: s: the string to be escaped. Returns: the escaped string.
Referenced by gyp.generator.msvs._EscapeCppDefineForMSVS.
gyp.generator.msvs._EscapeVCProjCommandLineArgListItem(s)
Escapes command line arguments for MSVS. The VCProj format stores string lists in a single string using commas and semi-colons as separators, which must be quoted if they are to be interpreted literally. However, command-line arguments may already have quotes, and the VCProj parser is ignorant of the backslash escaping convention used by CommandLineToArgv, so the command-line quotes and the VCProj quotes may not be the same quotes. So to store a general command-line argument in a VCProj list, we need to parse the existing quoting according to VCProj's convention and quote any delimiters that are not already quoted by that convention. The quotes that we add will also be seen by CommandLineToArgv, so if backslashes precede them then we also have to escape those backslashes according to the CommandLineToArgv convention. Args: s: the string to be escaped. Returns: the escaped string.
Referenced by gyp.generator.msvs._EscapeCppDefineForMSVS.
gyp.generator.msvs._EscapeCppDefineForMSVS(s)
Escapes a CPP define so that it will reach the compiler unaltered.
References gyp.generator.msvs._EscapeCommandLineArgumentForMSVS, gyp.generator.msvs._EscapeEnvironmentVariableExpansion, gyp.generator.msvs._EscapeVCProjCommandLineArgListItem.
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject.
gyp.generator.msvs._EscapeCommandLineArgumentForMSBuild(s)
Escapes a Windows command-line argument for use by MSBuild.
Referenced by gyp.generator.msvs._EscapeCppDefineForMSBuild.
gyp.generator.msvs._EscapeMSBuildSpecialCharacters(s)
Referenced by gyp.generator.msvs._EscapeCppDefineForMSBuild.
gyp.generator.msvs._EscapeCppDefineForMSBuild(s)
Escapes a CPP define so that it will reach the compiler unaltered.
References gyp.generator.msvs._EscapeCommandLineArgumentForMSBuild, gyp.generator.msvs._EscapeEnvironmentVariableExpansion, gyp.generator.msvs._EscapeMSBuildSpecialCharacters.
Referenced by gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._GenerateRulesForMSVS(p, output_dir, options, spec, sources, excluded_sources, actions_to_add)
Generate all the rules for a particular project. Arguments: p: the project output_dir: directory to emit rules to options: global options passed to the generator spec: the specification for this project sources: the set of all known source files in this project excluded_sources: the set of sources excluded from normal processing actions_to_add: deferred list of actions to add in
References gyp.generator.msvs._AdjustSourcesForRules, gyp.generator.msvs._GenerateExternalRules, gyp.generator.msvs._GenerateNativeRulesForMSVS.
Referenced by gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._AdjustSourcesForRules(rules, sources, excluded_sources, is_msbuild)
References gyp.generator.msvs._FindRuleTriggerFiles, gyp.generator.msvs._FixPath, gyp.generator.msvs._FixPaths, gyp.generator.msvs._RuleInputsAndOutputs.
Referenced by gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateRulesForMSBuild, gyp.generator.msvs._GenerateRulesForMSVS.
gyp.generator.msvs._FilterActionsFromExcluded(excluded_sources, actions_to_add)
Take inputs with actions attached out of the list of exclusions. Arguments: excluded_sources: list of source files not to be built. actions_to_add: dict of actions keyed on source file they're attached to. Returns: excluded_sources with files that have actions attached removed.
References gyp.generator.msvs._FixPaths.
Referenced by gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._GetDefaultConfiguration(spec)
Referenced by gyp.generator.msvs._GenerateProject, gyp.generator.msvs._GetGuidOfProject, gyp.generator.msvs._GetMsbuildToolsetOfProject, gyp.generator.msvs._GetPathOfProject.
gyp.generator.msvs._GetGuidOfProject(proj_path, spec)
Get the guid for the project. Arguments: proj_path: Path of the vcproj or vcxproj file to generate. spec: The target dictionary containing the properties of the target. Returns: the guid. Raises: ValueError: if the specified GUID is invalid.
References gyp.generator.msvs._GetDefaultConfiguration.
Referenced by gyp.generator.msvs._CreateProjectObjects.
gyp.generator.msvs._GetMsbuildToolsetOfProject(proj_path, spec, version)
Get the platform toolset for the project. Arguments: proj_path: Path of the vcproj or vcxproj file to generate. spec: The target dictionary containing the properties of the target. version: The MSVSVersion object. Returns: the platform toolset string or None.
References gyp.generator.msvs._GetDefaultConfiguration.
Referenced by gyp.generator.msvs._CreateProjectObjects.
gyp.generator.msvs._GenerateProject(project, options, version, generator_flags, spec)
Generates a vcproj file. Arguments: project: the MSVSProject object. options: global generator options. version: the MSVSVersion object. generator_flags: dict of generator-specific flags. Returns: A list of source files that cannot be found on disk.
References gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject, gyp.generator.msvs._GetDefaultConfiguration.
Referenced by gyp.generator.msvs.GenerateOutput.
gyp.generator.msvs._GenerateMSVSProject(project, options, version, generator_flags)
Generates a .vcproj file. It may create .rules and .user files too. Arguments: project: The project object we will generate the file for. options: Global options passed to the generator. version: The VisualStudioVersion object. generator_flags: dict of generator-specific flags.
References gyp.generator.msvs._AddAccumulatedActionsToMSVS, gyp.generator.msvs._AddActions, gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._AddCopies, gyp.generator.msvs._AddToolFilesToMSVS, gyp.generator.msvs._AdjustSourcesAndConvertToFilterHierarchy, gyp.generator.msvs._ExcludeFilesFromBeingBuilt, gyp.generator.msvs._FilterActionsFromExcluded, gyp.generator.msvs._GenerateRulesForMSVS, gyp.generator.msvs._GetMSVSConfigurationType, gyp.generator.msvs._GetUniquePlatforms, gyp.generator.msvs._HandlePreCompiledHeaders, gyp.generator.msvs._NormalizedSource, gyp.generator.msvs._PrepareListOfSources, gyp.generator.msvs._VerifySourcesExist, gyp.generator.msvs._WriteMSVSUserFile, gyp.common.EnsureDirExists, gyp.common.RelativePath.
Referenced by gyp.generator.msvs._GenerateProject.
gyp.generator.msvs._GetUniquePlatforms(spec)
Returns the list of unique platforms for this spec, e.g ['win32', ...]. Arguments: spec: The target dictionary containing the properties of the target. Returns: The MSVSUserFile object created.
References gyp.generator.msvs._ConfigPlatform.
Referenced by gyp.generator.msvs._AddSources2, gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._CreateMSVSUserFile(proj_path, version, spec)
Generates a .user file for the user running this Gyp program. Arguments: proj_path: The path of the project file being created. The .user file shares the same path (with an appropriate suffix). version: The VisualStudioVersion object. spec: The target dictionary containing the properties of the target. Returns: The MSVSUserFile object created.
References gyp.generator.msvs._GetDomainAndUserName.
Referenced by gyp.generator.msvs._WriteMSVSUserFile.
gyp.generator.msvs._GetMSVSConfigurationType(spec, build_file)
Returns the configuration type for this project. It's a number defined by Microsoft. May raise an exception. Args: spec: The target dictionary containing the properties of the target. build_file: The path of the gyp file. Returns: An integer, the configuration type.
Referenced by gyp.generator.msvs._ConvertMSVSBuildAttributes, gyp.generator.msvs._GenerateMSVSProject, gyp.generator.msvs._GetMSBuildAttributes.
gyp.generator.msvs._AddConfigurationToMSVSProject(p, spec, config_type, config_name, config)
Adds a configuration to the MSVS project. Many settings in a vcproj file are specific to a configuration. This function the main part of the vcproj file that's configuration specific. Arguments: p: The target project being generated. spec: The target dictionary containing the properties of the target. config_type: The configuration type, a number as defined by Microsoft. config_name: The name of the configuration. config: The dictionary that defines the special processing to be done for this configuration.
References gyp.generator.msvs._AddConfigurationToMSVS, gyp.generator.msvs._EscapeCppDefineForMSVS, gyp.generator.msvs._GetDefines, gyp.generator.msvs._GetDisabledWarnings, gyp.generator.msvs._GetIncludeDirs, gyp.generator.msvs._GetLibraries, gyp.generator.msvs._GetLibraryDirs, gyp.generator.msvs._GetModuleDefinition, gyp.generator.msvs._GetOutputFilePathAndTool, gyp.generator.msvs._ToolAppend.
Referenced by gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._GetIncludeDirs(config)
Returns the list of directories to be used for #include directives. Arguments: config: The dictionary that defines the special processing to be done for this configuration. Returns: The list of directory paths.
References gyp.generator.msvs._FixPaths.
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._GetLibraryDirs(config)
Returns the list of directories to be used for library search paths. Arguments: config: The dictionary that defines the special processing to be done for this configuration. Returns: The list of directory paths.
References gyp.generator.msvs._FixPaths.
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._GetLibraries(spec)
Returns the list of libraries for this configuration. Arguments: spec: The target dictionary containing the properties of the target. Returns: The list of directory paths.
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._GetOutputFilePathAndTool(spec, msbuild)
Returns the path and tool to use for this target. Figures out the path of the file this spec will create and the name of the VC tool that will create it. Arguments: spec: The target dictionary containing the properties of the target. Returns: A triple of (file path, name of the vc tool, name of the msbuild tool)
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._GetOutputTargetExt(spec)
Returns the extension for this target, including the dot If product_extension is specified, set target_extension to this to avoid MSB8012, returns None otherwise. Ignores any target_extension settings in the input files. Arguments: spec: The target dictionary containing the properties of the target. Returns: A string with the extension, or None
Referenced by gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._GetDefines(config)
Returns the list of preprocessor definitions for this configuration. Arguments: config: The dictionary that defines the special processing to be done for this configuration. Returns: The list of preprocessor definitions.
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._GetDisabledWarnings(config)
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._GetModuleDefinition(spec)
References gyp.generator.msvs._FixPath.
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject, gyp.generator.msvs._FinalizeMSBuildSettings.
gyp.generator.msvs._ConvertToolsToExpectedForm(tools)
Convert tools to a form expected by Visual Studio. Arguments: tools: A dictionary of settings; the tool name is the key. Returns: A list of Tool objects.
Referenced by gyp.generator.msvs._AddConfigurationToMSVS.
gyp.generator.msvs._AddConfigurationToMSVS(p, spec, tools, config, config_type, config_name)
Add to the project file the configuration specified by config. Arguments: p: The target project being generated. spec: the target project dict. tools: A dictionary of settings; the tool name is the key. config: The dictionary that defines the special processing to be done for this configuration. config_type: The configuration type, a number as defined by Microsoft. config_name: The name of the configuration.
References gyp.generator.msvs._ConfigFullName, gyp.generator.msvs._ConvertToolsToExpectedForm, gyp.generator.msvs._GetMSVSAttributes.
Referenced by gyp.generator.msvs._AddConfigurationToMSVSProject.
gyp.generator.msvs._GetMSVSAttributes(spec, config, config_type)
References gyp.generator.msvs._FixPath, gyp.generator.msvs._FixPaths.
Referenced by gyp.generator.msvs._AddConfigurationToMSVS, gyp.generator.msvs._ConvertMSVSBuildAttributes.
gyp.generator.msvs._AddNormalizedSources(sources_set, sources_array)
References gyp.generator.msvs._NormalizedSource.
Referenced by gyp.generator.msvs._PrepareListOfSources.
gyp.generator.msvs._PrepareListOfSources(spec, generator_flags, gyp_file)
Prepare list of sources and excluded sources. Besides the sources specified directly in the spec, adds the gyp file so that a change to it will cause a re-compile. Also adds appropriate sources for actions and copies. Assumes later stage will un-exclude files which have custom build steps attached. Arguments: spec: The target dictionary containing the properties of the target. gyp_file: The name of the gyp file. Returns: A pair of (list of sources, list of excluded sources). The sources will be relative to the gyp file.
References gyp.generator.msvs._AddNormalizedSources, gyp.generator.msvs._NormalizedSource.
Referenced by gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._AdjustSourcesAndConvertToFilterHierarchy(spec, options, gyp_dir, sources, excluded_sources, list_excluded, version)
Adjusts the list of sources and excluded sources. Also converts the sets to lists. Arguments: spec: The target dictionary containing the properties of the target. options: Global generator options. gyp_dir: The path to the gyp file being processed. sources: A set of sources to be included for this project. excluded_sources: A set of sources to be excluded for this project. version: A MSVSVersion object. Returns: A trio of (list of sources, list of excluded sources, path of excluded IDL file)
References gyp.generator.msvs._ConvertSourcesToFilterHierarchy, gyp.generator.msvs._FixPaths, gyp.generator.msvs._GetPrecompileRelatedFiles, gyp.generator.msvs._IdlFilesHandledNonNatively.
Referenced by gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._IdlFilesHandledNonNatively(spec, sources)
Referenced by gyp.generator.msvs._AdjustSourcesAndConvertToFilterHierarchy.
gyp.generator.msvs._GetPrecompileRelatedFiles(spec)
References gyp.generator.msvs._FixPath.
Referenced by gyp.generator.msvs._AdjustSourcesAndConvertToFilterHierarchy.
gyp.generator.msvs._ExcludeFilesFromBeingBuilt(p, spec, excluded_sources, excluded_idl, list_excluded)
References gyp.generator.msvs._ConfigFullName, gyp.generator.msvs._GetExcludedFilesFromBuild.
Referenced by gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._GetExcludedFilesFromBuild(spec, excluded_sources, excluded_idl)
References gyp.generator.msvs._FixPath.
Referenced by gyp.generator.msvs._ExcludeFilesFromBeingBuilt, gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._AddToolFilesToMSVS(p, spec)
Referenced by gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._HandlePreCompiledHeaders(p, sources, spec)
References gyp.generator.msvs._ConfigFullName, gyp.generator.msvs._FixPath.
Referenced by gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._AddActions(actions_to_add, spec, relative_path_of_gyp_file)
References gyp.generator.msvs._AddActionStep, gyp.generator.msvs._BuildCommandLineForRule.
Referenced by gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._WriteMSVSUserFile(project_path, version, spec)
References gyp.generator.msvs._ConfigFullName, gyp.generator.msvs._CreateMSVSUserFile.
Referenced by gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._AddCopies(actions_to_add, spec)
References gyp.generator.msvs._AddActionStep, gyp.generator.msvs._GetCopies.
Referenced by gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject.
gyp.generator.msvs._GetCopies(spec)
References gyp.generator.msvs._FixPath.
Referenced by gyp.generator.msvs._AddCopies.
gyp.generator.msvs._GetPathDict(root, path)
References gyp.generator.msvs._GetPathDict.
Referenced by gyp.generator.msvs._GatherSolutionFolders, gyp.generator.msvs._GetPathDict.
gyp.generator.msvs._DictsToFolders(base_path, bucket, flat)
References gyp.generator.msvs._DictsToFolders.
Referenced by gyp.generator.msvs._DictsToFolders, gyp.generator.msvs._GatherSolutionFolders.
gyp.generator.msvs._CollapseSingles(parent, node)
References gyp.generator.msvs._CollapseSingles.
Referenced by gyp.generator.msvs._CollapseSingles, gyp.generator.msvs._GatherSolutionFolders.
gyp.generator.msvs._GatherSolutionFolders(sln_projects, project_objects, flat)
References gyp.generator.msvs._CollapseSingles, gyp.generator.msvs._DictsToFolders, gyp.generator.msvs._GetPathDict, gyp.common.ParseQualifiedTarget.
Referenced by gyp.generator.msvs.GenerateOutput.
gyp.generator.msvs._GetPathOfProject(qualified_target, spec, options, msvs_version)
References gyp.generator.msvs._GetDefaultConfiguration, gyp.common.BuildFile, gyp.common.RelativePath.
Referenced by gyp.generator.msvs._CreateProjectObjects.
gyp.generator.msvs._GetPlatformOverridesOfProject(spec)
References gyp.generator.msvs._ConfigBaseName, gyp.generator.msvs._ConfigFullName, gyp.generator.msvs._ConfigPlatform.
Referenced by gyp.generator.msvs._CreateProjectObjects.
gyp.generator.msvs._CreateProjectObjects(target_list, target_dicts, options, msvs_version)
Create a MSVSProject object for the targets found in target list. Arguments: target_list: the list of targets to generate project objects for. target_dicts: the dictionary of specifications. options: global generator options. msvs_version: the MSVSVersion object. Returns: A set of created projects, keyed by target.
References gyp.generator.msvs._GetGuidOfProject, gyp.generator.msvs._GetMsbuildToolsetOfProject, gyp.generator.msvs._GetPathOfProject, gyp.generator.msvs._GetPlatformOverridesOfProject, gyp.common.BuildFile.
Referenced by gyp.generator.msvs.GenerateOutput.
gyp.generator.msvs._InitNinjaFlavor(params, target_list, target_dicts)
Initialize targets for the ninja flavor. This sets up the necessary variables in the targets to generate msvs projects that use ninja as an external builder. The variables in the spec are only set if they have not been set. This allows individual specs to override the default values initialized here. Arguments: params: Params provided to the generator. target_list: List of target pairs: 'base/base.gyp:base'. target_dicts: Dict of target properties keyed on target pair.
References gyp.common.ParseQualifiedTarget, gyp.common.RelativePath.
Referenced by gyp.generator.msvs.GenerateOutput.
gyp.generator.msvs.CalculateVariables(default_variables, params)
Generated variables that require params to be known.
References gyp.common.GetFlavor.
gyp.generator.msvs.PerformBuild(data, configurations, params)
gyp.generator.msvs.CalculateGeneratorInputInfo(params)
gyp.generator.msvs.GenerateOutput(target_list, target_dicts, data, params)
Generate .sln and .vcproj files. This is the entry point for this generator. Arguments: target_list: List of target pairs: 'base/base.gyp:base'. target_dicts: Dict of target properties keyed on target pair. data: Dictionary containing per .gyp data.
References gyp.generator.msvs._ConfigFullName, gyp.generator.msvs._CreateProjectObjects, gyp.generator.msvs._GatherSolutionFolders, gyp.generator.msvs._GenerateProject, gyp.generator.msvs._InitNinjaFlavor, gyp.common.BuildFileTargets, gyp.common.DeepDependencyTargets.
gyp.generator.msvs._GenerateMSBuildFiltersFile(filters_path, source_files, rule_dependencies, extension_to_rule_name, platforms, toolset)
Generate the filters file. This file is used by Visual Studio to organize the presentation of source files into folders. Arguments: filters_path: The path of the file to be created. source_files: The hierarchical structure of all the sources. extension_to_rule_name: A dictionary mapping file extensions to rules.
References gyp.generator.msvs._AppendFiltersForMSBuild.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._AppendFiltersForMSBuild(parent_filter_name, sources, rule_dependencies, extension_to_rule_name, platforms, toolset, filter_group, source_group)
Creates the list of filters and sources to be added in the filter file. Args: parent_filter_name: The name of the filter under which the sources are found. sources: The hierarchy of filters and sources to process. extension_to_rule_name: A dictionary mapping file extensions to rules. filter_group: The list to which filter entries will be appended. source_group: The list to which source entries will be appended.
References gyp.generator.msvs._AppendFiltersForMSBuild, gyp.generator.msvs._MapFileToMsBuildSourceType.
Referenced by gyp.generator.msvs._AppendFiltersForMSBuild, gyp.generator.msvs._GenerateMSBuildFiltersFile.
gyp.generator.msvs._MapFileToMsBuildSourceType(source, rule_dependencies, extension_to_rule_name, platforms, toolset)
Returns the group and element type of the source file. Arguments: source: The source file name. extension_to_rule_name: A dictionary mapping file extensions to rules. Returns: A pair of (group this file should be part of, the label of element)
Referenced by gyp.generator.msvs._AddSources2, gyp.generator.msvs._AppendFiltersForMSBuild.
gyp.generator.msvs._GenerateRulesForMSBuild(output_dir, options, spec, sources, excluded_sources, props_files_of_rules, targets_files_of_rules, actions_to_add, rule_dependencies, extension_to_rule_name)
References gyp.generator.msvs._AdjustSourcesForRules, gyp.generator.msvs._GenerateExternalRules, gyp.generator.msvs._GenerateMSBuildRulePropsFile, gyp.generator.msvs._GenerateMSBuildRuleTargetsFile, gyp.generator.msvs._GenerateMSBuildRuleXmlFile.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GenerateMSBuildRulePropsFile(props_path, msbuild_rules)
Generate the .props file.
Referenced by gyp.generator.msvs._GenerateRulesForMSBuild.
gyp.generator.msvs._GenerateMSBuildRuleTargetsFile(targets_path, msbuild_rules)
Generate the .targets file.
Referenced by gyp.generator.msvs._GenerateRulesForMSBuild.
gyp.generator.msvs._GenerateMSBuildRuleXmlFile(xml_path, msbuild_rules)
Referenced by gyp.generator.msvs._GenerateRulesForMSBuild.
gyp.generator.msvs._GetConfigurationAndPlatform(name, settings, spec)
Referenced by gyp.generator.msvs._GetConfigurationCondition, gyp.generator.msvs._GetMSBuildProjectConfigurations.
gyp.generator.msvs._GetConfigurationCondition(name, settings, spec)
References gyp.generator.msvs._GetConfigurationAndPlatform.
Referenced by gyp.generator.msvs._AddSources2, gyp.generator.msvs._GetMSBuildConfigurationDetails, gyp.generator.msvs._GetMSBuildConfigurationGlobalProperties, gyp.generator.msvs._GetMSBuildPropertySheets, gyp.generator.msvs._GetMSBuildToolSettingsSections.
gyp.generator.msvs._GetMSBuildProjectConfigurations(configurations, spec)
References gyp.generator.msvs._GetConfigurationAndPlatform.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GetMSBuildGlobalProperties(spec, version, guid, gyp_file_name)
References gyp.generator.msvs._ConfigPlatform, gyp.generator.msvs._ConfigWindowsTargetPlatformVersion.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GetMSBuildConfigurationDetails(spec, build_file)
References gyp.generator.msvs._AddConditionalProperty, gyp.generator.msvs._ConfigTargetVersion, gyp.generator.msvs._GetConfigurationCondition, gyp.generator.msvs._GetMSBuildAttributes, gyp.generator.msvs._GetMSBuildPropertyGroup.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GetMSBuildLocalProperties(msbuild_toolset)
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GetMSBuildPropertySheets(configurations, spec)
References gyp.generator.msvs._FixPaths, gyp.generator.msvs._GetConfigurationCondition.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._ConvertMSVSBuildAttributes(spec, config, build_file)
References gyp.generator.msvs._ConvertMSVSCharacterSet, gyp.generator.msvs._ConvertMSVSConfigurationType, gyp.generator.msvs._GetMSVSAttributes, gyp.generator.msvs._GetMSVSConfigurationType.
Referenced by gyp.generator.msvs._GetMSBuildAttributes.
gyp.generator.msvs._ConvertMSVSCharacterSet(char_set)
Referenced by gyp.generator.msvs._ConvertMSVSBuildAttributes, gyp.generator.msvs._GetMSBuildAttributes.
gyp.generator.msvs._ConvertMSVSConfigurationType(config_type)
Referenced by gyp.generator.msvs._ConvertMSVSBuildAttributes, gyp.generator.msvs._GetMSBuildAttributes.
gyp.generator.msvs._GetMSBuildAttributes(spec, config, build_file)
References gyp.generator.msvs._ConvertMSVSBuildAttributes, gyp.generator.msvs._ConvertMSVSCharacterSet, gyp.generator.msvs._ConvertMSVSConfigurationType, gyp.generator.msvs._FixPath, gyp.generator.msvs._GetMSVSConfigurationType.
Referenced by gyp.generator.msvs._GetMSBuildConfigurationDetails, gyp.generator.msvs._GetMSBuildConfigurationGlobalProperties.
gyp.generator.msvs._GetMSBuildConfigurationGlobalProperties(spec, configurations, build_file)
References gyp.generator.msvs._AddConditionalProperty, gyp.generator.msvs._FixPath, gyp.generator.msvs._GetConfigurationCondition, gyp.generator.msvs._GetMSBuildAttributes, gyp.generator.msvs._GetMSBuildPropertyGroup, gyp.generator.msvs._GetValueFormattedForMSBuild.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._AddConditionalProperty(properties, condition, name, value)
Adds a property / conditional value pair to a dictionary. Arguments: properties: The dictionary to be modified. The key is the name of the property. The value is itself a dictionary; its key is the value and the value a list of condition for which this value is true. condition: The condition under which the named property has the value. name: The name of the property. value: The value of the property.
Referenced by gyp.generator.msvs._GetMSBuildConfigurationDetails, gyp.generator.msvs._GetMSBuildConfigurationGlobalProperties.
gyp.generator.msvs._GetMSBuildPropertyGroup(spec, label, properties)
Returns a PropertyGroup definition for the specified properties. Arguments: spec: The target project dict. label: An optional label for the PropertyGroup. properties: The dictionary to be converted. The key is the name of the property. The value is itself a dictionary; its key is the value and the value a list of condition for which this value is true.
References gyp.common.TopologicallySorted.
Referenced by gyp.generator.msvs._GetMSBuildConfigurationDetails, gyp.generator.msvs._GetMSBuildConfigurationGlobalProperties.
gyp.generator.msvs._GetMSBuildToolSettingsSections(spec, configurations)
References gyp.generator.msvs._GetConfigurationCondition, gyp.generator.msvs._GetValueFormattedForMSBuild.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._FinalizeMSBuildSettings(spec, configuration)
References gyp.generator.msvs._EscapeCppDefineForMSBuild, gyp.generator.msvs._GetDefines, gyp.generator.msvs._GetDisabledWarnings, gyp.generator.msvs._GetIncludeDirs, gyp.generator.msvs._GetLibraries, gyp.generator.msvs._GetLibraryDirs, gyp.generator.msvs._GetModuleDefinition, gyp.generator.msvs._GetOutputFilePathAndTool, gyp.generator.msvs._GetOutputTargetExt, gyp.generator.msvs._ToolAppend, gyp.generator.msvs._ToolSetOrAppend.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GetValueFormattedForMSBuild(tool_name, name, value)
Referenced by gyp.generator.msvs._GetMSBuildConfigurationGlobalProperties, gyp.generator.msvs._GetMSBuildToolSettingsSections.
gyp.generator.msvs._VerifySourcesExist(sources, root_dir)
Verifies that all source files exist on disk. Checks that all regular source files, i.e. not created at run time, exist on disk. Missing files cause needless recompilation but no otherwise visible errors. Arguments: sources: A recursive list of Filter/file names. root_dir: The root directory for the relative path names. Returns: A list of source files that cannot be found on disk.
References gyp.generator.msvs._VerifySourcesExist.
Referenced by gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject, gyp.generator.msvs._VerifySourcesExist.
gyp.generator.msvs._GetMSBuildSources(spec, sources, exclusions, rule_dependencies, extension_to_rule_name, actions_spec, sources_handled_by_action, list_excluded)
References gyp.generator.msvs._AddSources2.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._AddSources2(spec, sources, exclusions, grouped_sources, rule_dependencies, extension_to_rule_name, sources_handled_by_action, list_excluded)
References gyp.generator.msvs._AddSources2, gyp.generator.msvs._FixPath, gyp.generator.msvs._GetConfigurationCondition, gyp.generator.msvs._GetUniquePlatforms, gyp.generator.msvs._MapFileToMsBuildSourceType.
Referenced by gyp.generator.msvs._AddSources2, gyp.generator.msvs._GetMSBuildSources.
gyp.generator.msvs._GetMSBuildProjectReferences(project)
References gyp.common.RelativePath.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GenerateMSBuildProject(project, options, version, generator_flags, spec)
References gyp.generator.msvs._AddActions, gyp.generator.msvs._AddCopies, gyp.generator.msvs._AdjustSourcesAndConvertToFilterHierarchy, gyp.generator.msvs._AdjustSourcesForRules, gyp.generator.msvs._FilterActionsFromExcluded, gyp.generator.msvs._FinalizeMSBuildSettings, gyp.generator.msvs._GenerateActionsForMSBuild, gyp.generator.msvs._GenerateMSBuildFiltersFile, gyp.generator.msvs._GenerateRulesForMSBuild, gyp.generator.msvs._GetExcludedFilesFromBuild, gyp.generator.msvs._GetMSBuildConfigurationDetails, gyp.generator.msvs._GetMSBuildConfigurationGlobalProperties, gyp.generator.msvs._GetMSBuildExtensions, gyp.generator.msvs._GetMSBuildExtensionTargets, gyp.generator.msvs._GetMSBuildExternalBuilderTargets, gyp.generator.msvs._GetMSBuildGlobalProperties, gyp.generator.msvs._GetMSBuildLocalProperties, gyp.generator.msvs._GetMSBuildProjectConfigurations, gyp.generator.msvs._GetMSBuildProjectReferences, gyp.generator.msvs._GetMSBuildPropertySheets, gyp.generator.msvs._GetMSBuildSources, gyp.generator.msvs._GetMSBuildToolSettingsSections, gyp.generator.msvs._GetUniquePlatforms, gyp.generator.msvs._PrepareListOfSources, gyp.generator.msvs._VerifySourcesExist, gyp.common.EnsureDirExists.
Referenced by gyp.generator.msvs._GenerateProject.
gyp.generator.msvs._GetMSBuildExternalBuilderTargets(spec)
Return a list of MSBuild targets for external builders. The "Build" and "Clean" targets are always generated. If the spec contains 'msvs_external_builder_clcompile_cmd', then the "ClCompile" target will also be generated, to support building selected C/C++ files. Arguments: spec: The gyp target spec. Returns: List of MSBuild 'Target' specs.
References gyp.generator.msvs._BuildCommandLineForRuleRaw.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GetMSBuildExtensions(props_files_of_rules)
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GetMSBuildExtensionTargets(targets_files_of_rules)
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._GenerateActionsForMSBuild(spec, actions_to_add)
Add actions accumulated into an actions_to_add, merging as needed. Arguments: spec: the target project dict actions_to_add: dictionary keyed on input name, which maps to a list of dicts describing the actions attached to that input file. Returns: A pair of (action specification, the sources handled by this action).
References gyp.generator.msvs._AddMSBuildAction.
Referenced by gyp.generator.msvs._GenerateMSBuildProject.
gyp.generator.msvs._AddMSBuildAction(spec, primary_input, inputs, outputs, cmd, description, sources_handled_by_action, actions_spec)
References gyp.generator.msvs._FixPath, gyp.generator.msvs._FixPaths.
Referenced by gyp.generator.msvs._GenerateActionsForMSBuild.