pretty_sln
str pretty_sln.__author__
pretty_sln.BuildProject(project, built, projects, deps)
References BuildProject.
Referenced by BuildProject, PrintBuildOrder.
pretty_sln.ParseSolution(solution_file)
Referenced by main.
pretty_sln.PrintDependencies(projects, deps)
Referenced by main.
pretty_sln.PrintBuildOrder(projects, deps)
References BuildProject.
Referenced by main.
pretty_sln.PrintVCProj(projects)
Referenced by main.
pretty_sln.main()
References main, ParseSolution, PrintBuildOrder, PrintDependencies, PrintVCProj.
Referenced by main.