gyp::input
list gyp::input.linkable_types
list gyp::input.dependency_sections
list gyp::input.base_path_sections
gyp::input.path_sections
dict gyp::input.per_process_data
dict gyp::input.per_process_aux_data
list gyp::input.base_non_configuration_keys
list gyp::input.non_configuration_keys
list gyp::input.invalid_configuration_keys
bool gyp::input.multiple_toolsets
gyp::input.generator_filelist_paths
gyp::input.LBRACKETS
dict gyp::input.BRACKETS
gyp::input.early_variable_re
gyp::input.late_variable_re
gyp::input.latelate_variable_re
dict gyp::input.cached_command_results
int gyp::input.PHASE_EARLY
int gyp::input.PHASE_LATE
int gyp::input.PHASE_LATELATE
dict gyp::input.cached_conditions_asts
gyp::input.exception_re
gyp.input.IsPathSection(section)
Referenced by gyp.input.MergeDicts.
gyp.input.GetIncludedBuildFiles(build_file_path, aux_data, included=None)
Return a list of all build files included into build_file_path. The returned list will contain build_file_path as well as all other files that it included, either directly or indirectly. Note that the list may contain files that were included into a conditional section that evaluated to false and was not merged into build_file_path's dict. aux_data is a dict containing a key for each build file or included build file. Those keys provide access to dicts whose "included" keys contain lists of all other files included by the build file. included should be left at its default None value by external callers. It is used for recursion. The returned list will not contain any duplicate entries. Each build file in the list will be relative to the current directory.
References gyp.input.GetIncludedBuildFiles.
Referenced by gyp.input.GetIncludedBuildFiles, gyp.input.LoadTargetBuildFile.
gyp.input.CheckedEval(file_contents)
Return the eval of a gyp file. The gyp file is restricted to dictionaries and lists only, and repeated keys are not allowed. Note that this is slower than eval() is.
References gyp.input.CheckNode.
Referenced by gyp.input.LoadOneBuildFile.
gyp.input.CheckNode(node, keypath)
References gyp.input.CheckNode.
Referenced by gyp.input.CheckedEval, gyp.input.CheckNode.
gyp.input.LoadOneBuildFile(build_file_path, data, aux_data, includes, is_target, check)
References gyp.input.CheckedEval, gyp.common.ExceptionAppend, gyp.input.LoadBuildFileIncludesIntoDict.
Referenced by gyp.input.LoadBuildFileIncludesIntoDict, gyp.input.LoadTargetBuildFile.
gyp.input.LoadBuildFileIncludesIntoDict(subdict, subdict_path, data, aux_data, includes, check)
References gyp.DebugOutput, gyp.input.LoadBuildFileIncludesIntoDict, gyp.input.LoadBuildFileIncludesIntoList, gyp.input.LoadOneBuildFile, gyp.input.MergeDicts.
Referenced by gyp.input.LoadBuildFileIncludesIntoDict, gyp.input.LoadBuildFileIncludesIntoList, gyp.input.LoadOneBuildFile.
gyp.input.LoadBuildFileIncludesIntoList(sublist, sublist_path, data, aux_data, check)
References gyp.input.LoadBuildFileIncludesIntoDict, gyp.input.LoadBuildFileIncludesIntoList.
Referenced by gyp.input.LoadBuildFileIncludesIntoDict, gyp.input.LoadBuildFileIncludesIntoList.
gyp.input.ProcessToolsetsInDict(data)
References gyp.simple_copy.deepcopy, gyp.input.ProcessToolsetsInDict.
Referenced by gyp.input.LoadTargetBuildFile, gyp.input.ProcessToolsetsInDict.
gyp.input.LoadTargetBuildFile(build_file_path, data, aux_data, variables, includes, depth, check, load_dependencies)
References gyp.DebugOutput, gyp.simple_copy.deepcopy, gyp.common.ExceptionAppend, gyp.input.GetIncludedBuildFiles, gyp.input.LoadOneBuildFile, gyp.input.LoadTargetBuildFile, gyp.input.MergeDicts, gyp.input.ProcessToolsetsInDict, gyp.input.ProcessVariablesAndConditionsInDict, gyp.common.RelativePath, gyp.common.ResolveTarget.
Referenced by gyp.input.CallLoadTargetBuildFile, gyp.input.Load, gyp.input.LoadTargetBuildFile.
gyp.input.CallLoadTargetBuildFile(global_flags, build_file_path, variables, includes, depth, check, generator_input_info)
Wrapper around LoadTargetBuildFile for parallel processing. This wrapper is used when LoadTargetBuildFile is executed in a worker process.
References gyp.input.LoadTargetBuildFile, gyp.input.SetGeneratorGlobals.
gyp.input.LoadTargetBuildFilesParallel(build_files, data, variables, includes, depth, check, generator_input_info)
Referenced by gyp.input.Load.
gyp.input.FindEnclosingBracketGroup(input_str)
Referenced by gyp.input.ExpandVariables.
gyp.input.IsStrCanonicalInt(string)
Returns True if |string| is in its canonical integer form. The canonical form is such that str(int(string)) == string.
Referenced by gyp.input.ExpandVariables.
gyp.input.FixupPlatformCommand(cmd)
Referenced by gyp.input.ExpandVariables.
gyp.input.ExpandVariables(input, phase, variables, build_file)
References gyp.DebugOutput, gyp.simple_copy.deepcopy, gyp.common.EncodePOSIXShellList, gyp.common.EnsureDirExists, gyp.input.ExpandVariables, gyp.input.FindEnclosingBracketGroup, gyp.input.FixupPlatformCommand, gyp.input.IsStrCanonicalInt, gyp.input.ProcessListFiltersInDict, gyp.input.ProcessVariablesAndConditionsInList, gyp.common.RelativePath, gyp.common.WriteOnDiff.
Referenced by gyp.input.EvalSingleCondition, gyp.input.ExpandVariables, gyp.input.ProcessVariablesAndConditionsInDict, gyp.input.ProcessVariablesAndConditionsInList.
gyp.input.EvalCondition(condition, conditions_key, phase, variables, build_file)
Returns the dict that should be used or None if the result was that nothing should be used.
References gyp.input.EvalSingleCondition.
Referenced by gyp.input.ProcessConditionsInDict.
gyp.input.EvalSingleCondition(cond_expr, true_dict, false_dict, phase, variables, build_file)
Returns true_dict if cond_expr evaluates to true, and false_dict otherwise.
References gyp.common.ExceptionAppend, gyp.input.ExpandVariables.
Referenced by gyp.input.EvalCondition.
gyp.input.ProcessConditionsInDict(the_dict, phase, variables, build_file)
References gyp.input.EvalCondition, gyp.input.MergeDicts, gyp.input.ProcessVariablesAndConditionsInDict.
Referenced by gyp.input.ProcessVariablesAndConditionsInDict.
gyp.input.LoadAutomaticVariablesFromDict(variables, the_dict)
Referenced by gyp.input.ProcessVariablesAndConditionsInDict.
gyp.input.LoadVariablesFromVariablesDict(variables, the_dict, the_dict_key)
Referenced by gyp.input.ProcessVariablesAndConditionsInDict.
gyp.input.ProcessVariablesAndConditionsInDict(the_dict, phase, variables_in, build_file, the_dict_key=None)
Handle all variable and command expansion and conditional evaluation. This function is the public entry point for all variable expansions and conditional evaluations. The variables_in dictionary will not be modified by this function.
References gyp.input.ExpandVariables, gyp.input.LoadAutomaticVariablesFromDict, gyp.input.LoadVariablesFromVariablesDict, gyp.input.ProcessConditionsInDict, gyp.input.ProcessVariablesAndConditionsInDict, gyp.input.ProcessVariablesAndConditionsInList.
Referenced by gyp.input.Load, gyp.input.LoadTargetBuildFile, gyp.input.ProcessConditionsInDict, gyp.input.ProcessVariablesAndConditionsInDict, gyp.input.ProcessVariablesAndConditionsInList.
gyp.input.ProcessVariablesAndConditionsInList(the_list, phase, variables, build_file)
References gyp.input.ExpandVariables, gyp.input.ProcessVariablesAndConditionsInDict, gyp.input.ProcessVariablesAndConditionsInList.
Referenced by gyp.input.ExpandVariables, gyp.input.ProcessVariablesAndConditionsInDict, gyp.input.ProcessVariablesAndConditionsInList.
gyp.input.BuildTargetsDict(data)
Builds a dict mapping fully-qualified target names to their target dicts. |data| is a dict mapping loaded build files by pathname relative to the current directory. Values in |data| are build file contents. For each |data| value with a "targets" key, the value of the "targets" key is taken as a list containing target dicts. Each target's fully-qualified name is constructed from the pathname of the build file (|data| key) and its "target_name" property. These fully-qualified names are used as the keys in the returned dict. These keys provide access to the target dicts, the dicts in the "targets" lists.
References gyp.common.QualifiedTarget.
Referenced by gyp.input.Load.
gyp.input.QualifyDependencies(targets)
Make dependency links fully-qualified relative to the current directory. |targets| is a dict mapping fully-qualified target names to their target dicts. For each target in this dict, keys known to contain dependency links are examined, and any dependencies referenced will be rewritten so that they are fully-qualified and relative to the current directory. All rewritten dependencies are suitable for use as keys to |targets| or a similar dict.
References gyp.common.BuildFile, gyp.common.QualifiedTarget, gyp.common.ResolveTarget.
Referenced by gyp.input.Load.
gyp.input.ExpandWildcardDependencies(targets, data)
Expands dependencies specified as build_file:*. For each target in |targets|, examines sections containing links to other targets. If any such section contains a link of the form build_file:*, it is taken as a wildcard link, and is expanded to list each target in build_file. The |data| dict provides access to build file dicts. Any target that does not wish to be included by wildcard can provide an optional "suppress_wildcard" key in its target dict. When present and true, a wildcard dependency link will not include such targets. All dependency names, including the keys to |targets| and the values in each dependency list, must be qualified when this function is called.
References gyp.common.BuildFile, gyp.common.ParseQualifiedTarget, gyp.common.QualifiedTarget.
Referenced by gyp.input.Load.
gyp.input.Unify(items)
Removes duplicate elements from items, keeping the first element.
Referenced by gyp.input.RemoveDuplicateDependencies.
gyp.input.RemoveDuplicateDependencies(targets)
Makes sure every dependency appears only once in all targets's dependency lists.
References gyp.input.Unify.
Referenced by gyp.input.Load.
gyp.input.Filter(items, item)
Removes item from items.
Referenced by gyp.input.RemoveLinkDependenciesFromNoneTargets, gyp.input.RemoveSelfDependencies.
gyp.input.RemoveSelfDependencies(targets)
Remove self dependencies from targets that have the prune_self_dependency variable set.
References gyp.input.Filter.
Referenced by gyp.input.Load.
gyp.input.RemoveLinkDependenciesFromNoneTargets(targets)
Remove dependencies having the 'link_dependency' attribute from the 'none' targets.
References gyp.input.Filter.
Referenced by gyp.input.Load.
gyp.input.BuildDependencyList(targets)
Referenced by gyp.input.Load.
gyp.input.VerifyNoGYPFileCircularDependencies(targets)
References gyp.common.BuildFile, gyp.common.ExceptionAppend.
Referenced by gyp.input.Load.
gyp.input.DoDependentSettings(key, flat_list, targets, dependency_nodes)
References gyp.common.BuildFile, gyp.input.MergeDicts.
Referenced by gyp.input.Load.
gyp.input.AdjustStaticLibraryDependencies(flat_list, targets, dependency_nodes, sort_dependencies)
Referenced by gyp.input.Load.
gyp.input.MakePathRelative(to_file, fro_file, item)
References gyp.common.RelativePath.
Referenced by gyp.input.MergeDicts, gyp.input.MergeLists.
gyp.input.MergeLists(to, fro, to_file, fro_file, is_paths=False, append=True)
References gyp.input.MakePathRelative, gyp.input.MergeDicts, gyp.input.MergeLists.
Referenced by gyp.input.MergeDicts, gyp.input.MergeLists.
gyp.input.MergeDicts(to, fro, to_file, fro_file)
References gyp.input.IsPathSection, gyp.input.MakePathRelative, gyp.input.MergeDicts, gyp.input.MergeLists.
Referenced by gyp.input.DoDependentSettings, gyp.input.LoadBuildFileIncludesIntoDict, gyp.input.LoadTargetBuildFile, gyp.input.MergeConfigWithInheritance, gyp.input.MergeDicts, gyp.input.MergeLists, gyp.input.ProcessConditionsInDict.
gyp.input.MergeConfigWithInheritance(new_configuration_dict, build_file, target_dict, configuration, visited)
References gyp.input.MergeConfigWithInheritance, gyp.input.MergeDicts.
Referenced by gyp.input.MergeConfigWithInheritance, gyp.input.SetUpConfigurations.
gyp.input.SetUpConfigurations(target, target_dict)
References gyp.common.BuildFile, gyp.simple_copy.deepcopy, gyp.input.MergeConfigWithInheritance.
Referenced by gyp.input.Load.
gyp.input.ProcessListFiltersInDict(name, the_dict)
Process regular expression and exclusion-based filters on lists. An exclusion list is in a dict key named with a trailing "!", like "sources!". Every item in such a list is removed from the associated main list, which in this example, would be "sources". Removed items are placed into a "sources_excluded" list in the dict. Regular expression (regex) filters are contained in dict keys named with a trailing "/", such as "sources/" to operate on the "sources" list. Regex filters in a dict take the form: 'sources/': [ ['exclude', '_(linux|mac|win)\\.cc$'], ['include', '_mac\\.cc$'] ], The first filter says to exclude all files ending in _linux.cc, _mac.cc, and _win.cc. The second filter then includes all files ending in _mac.cc that are now or were once in the "sources" list. Items matching an "exclude" filter are subject to the same processing as would occur if they were listed by name in an exclusion list (ending in "!"). Items matching an "include" filter are brought back into the main list if previously excluded by an exclusion list or exclusion regex filter. Subsequent matching "exclude" patterns can still cause items to be excluded after matching an "include".
References gyp.input.ProcessListFiltersInDict, gyp.input.ProcessListFiltersInList.
Referenced by gyp.input.ExpandVariables, gyp.input.Load, gyp.input.ProcessListFiltersInDict, gyp.input.ProcessListFiltersInList.
gyp.input.ProcessListFiltersInList(name, the_list)
References gyp.input.ProcessListFiltersInDict, gyp.input.ProcessListFiltersInList.
Referenced by gyp.input.ProcessListFiltersInDict, gyp.input.ProcessListFiltersInList.
gyp.input.ValidateTargetType(target, target_dict)
Ensures the 'type' field on the target is one of the known types. Arguments: target: string, name of target. target_dict: dict, target spec. Raises an exception on error.
Referenced by gyp.input.Load.
gyp.input.ValidateRulesInTarget(target, target_dict, extra_sources_for_rules)
Ensures that the rules sections in target_dict are valid and consistent, and determines which sources they apply to. Arguments: target: string, name of target. target_dict: dict, target spec containing "rules" and "sources" lists. extra_sources_for_rules: a list of keys to scan for rule matches in addition to 'sources'.
Referenced by gyp.input.Load.
gyp.input.ValidateRunAsInTarget(target, target_dict, build_file)
Referenced by gyp.input.Load.
gyp.input.ValidateActionsInTarget(target, target_dict, build_file)
Validates the inputs to the actions in a target.
Referenced by gyp.input.Load.
gyp.input.TurnIntIntoStrInDict(the_dict)
Given dict the_dict, recursively converts all integers into strings.
References gyp.input.TurnIntIntoStrInDict, gyp.input.TurnIntIntoStrInList.
Referenced by gyp.input.Load, gyp.input.TurnIntIntoStrInDict, gyp.input.TurnIntIntoStrInList.
gyp.input.TurnIntIntoStrInList(the_list)
Given list the_list, recursively converts all integers into strings.
References gyp.input.TurnIntIntoStrInDict, gyp.input.TurnIntIntoStrInList.
Referenced by gyp.input.TurnIntIntoStrInDict, gyp.input.TurnIntIntoStrInList.
gyp.input.PruneUnwantedTargets(targets, flat_list, dependency_nodes, root_targets, data)
Return only the targets that are deep dependencies of |root_targets|.
References gyp.common.FindQualifiedTargets, gyp.common.QualifiedTarget.
Referenced by gyp.input.Load.
gyp.input.VerifyNoCollidingTargets(targets)
Verify that no two targets in the same directory share the same name. Arguments: targets: A list of targets in the form 'path/to/file.gyp:target_name'.
Referenced by gyp.input.Load.
gyp.input.SetGeneratorGlobals(generator_input_info)
Referenced by gyp.input.CallLoadTargetBuildFile, gyp.input.Load.
gyp.input.Load(build_files, variables, includes, depth, generator_input_info, check, circular_check, parallel, root_targets)
References gyp.input.AdjustStaticLibraryDependencies, gyp.input.BuildDependencyList, gyp.common.BuildFile, gyp.input.BuildTargetsDict, gyp.input.DoDependentSettings, gyp.common.ExceptionAppend, gyp.input.ExpandWildcardDependencies, gyp.input.LoadTargetBuildFile, gyp.input.LoadTargetBuildFilesParallel, gyp.input.ProcessListFiltersInDict, gyp.input.ProcessVariablesAndConditionsInDict, gyp.input.PruneUnwantedTargets, gyp.input.QualifyDependencies, gyp.input.RemoveDuplicateDependencies, gyp.input.RemoveLinkDependenciesFromNoneTargets, gyp.input.RemoveSelfDependencies, gyp.input.SetGeneratorGlobals, gyp.input.SetUpConfigurations, gyp.input.TurnIntIntoStrInDict, gyp.input.ValidateActionsInTarget, gyp.input.ValidateRulesInTarget, gyp.input.ValidateRunAsInTarget, gyp.input.ValidateTargetType, gyp.input.VerifyNoCollidingTargets, gyp.input.VerifyNoGYPFileCircularDependencies.
Referenced by gyp.Load.