gyp
dict gyp.debug
str gyp.DEBUG_GENERAL
str gyp.DEBUG_VARIABLES
str gyp.DEBUG_INCLUDES
gyp.DebugOutput(mode, message, *args)
Referenced by gyp.input.ExpandVariables, gyp_main, gyp.input.LoadBuildFileIncludesIntoDict, gyp.input.LoadTargetBuildFile.
gyp.FindBuildFiles()
Referenced by gyp_main.
gyp.Load(build_files, format, default_variables={}, includes=[], depth=".", params=None, check=False, circular_check=True)
Loads one or more specified build files. default_variables and includes will be copied before use. Returns the generator for the specified format and the data returned by loading the specified build files.
References gyp.input.Load.
Referenced by gyp_main.
gyp.NameValueListToDict(name_value_list)
Takes an array of strings of the form 'NAME=VALUE' and creates a dictionary of the pairs. If a string is simply NAME, then the value in the dictionary is set to True. If VALUE can be converted to an integer, it is.
Referenced by gyp_main.
gyp.ShlexEnv(env_name)
Referenced by gyp_main, RegenerateAppendFlag.
gyp.FormatOpt(opt, value)
Referenced by RegenerateAppendFlag, RegenerateFlags.
gyp.RegenerateAppendFlag(flag, values, predicate, env_name, options)
Regenerate a list of command line flags, for an option of action='append'. The |env_name|, if given, is checked in the environment and used to generate an initial list of options, then the options that were specified on the command line (given in |values|) are appended. This matches the handling of environment variables and command line flags where command line flags override the environment, while not requiring the environment to be set when the flags are used again.
References FormatOpt, ShlexEnv.
Referenced by RegenerateFlags.
gyp.RegenerateFlags(options)
Given a parsed options object, and taking the environment variables into account, returns a list of flags that should regenerate an equivalent options object (even in the absence of the environment variables.) Any path options will be normalized relative to depth. The format flag is not included, as it is assumed the calling generator will set that as appropriate.
References gyp.common.FixIfRelativePath, FormatOpt, RegenerateAppendFlag.
Referenced by gyp.generator.make.WriteAutoRegenerationRule.
gyp.gyp_main(args)
References DebugOutput, FindBuildFiles, Load, NameValueListToDict, ShlexEnv.
gyp.main(args)
Referenced by script_main.
gyp.script_main()
References main, script_main.
Referenced by script_main.