pretty_gyp
pretty_gyp.COMMENT_RE
str pretty_gyp.QUOTE_RE_STR
pretty_gyp.QUOTE_RE
pretty_gyp.comment_replace(matchobj)
pretty_gyp.mask_comments(input)
Mask the quoted strings so we skip braces inside quoted strings.
Referenced by split_double_braces.
pretty_gyp.quote_replace(matchobj)
pretty_gyp.mask_quotes(input)
Mask the quoted strings so we skip braces inside quoted strings.
Referenced by split_double_braces.
pretty_gyp.do_split(input, masked_input, search_re)
Referenced by split_double_braces.
pretty_gyp.split_double_braces(input)
Masks out the quotes and comments, and then splits appropriate lines (lines that matche the double_*_brace re's above) before indenting them below. These are used to split lines which have multiple braces on them, so that the indentation looks prettier when all laid out (e.g. closing braces make a nice diagonal line).
References do_split, mask_comments, mask_quotes.
Referenced by main.
pretty_gyp.count_braces(line)
keeps track of the number of braces on a given line and returns the result. It starts at zero and subtracts for closed braces, and adds for open braces.
Referenced by prettyprint_input.
pretty_gyp.prettyprint_input(lines)
Does the main work of indenting the input based on the brace counts.
References count_braces.
Referenced by main.
pretty_gyp.main()
References main, prettyprint_input, split_double_braces.
Referenced by main.