pretty_vcproj
str pretty_vcproj.__author__
pretty_vcproj.ARGUMENTS
pretty_vcproj.REPLACEMENTS
pretty_vcproj.cmp(x, y)
Referenced by pretty_vcproj.CmpNode.__call__, pretty_vcproj.CmpTuple.__call__.
pretty_vcproj.PrettyPrintNode(node, indent=0)
References PrettyPrintNode.
Referenced by main, PrettyPrintNode.
pretty_vcproj.FlattenFilter(node)
Returns a list of all the node and sub nodes.
References FlattenFilter.
Referenced by CleanupVcproj, FlattenFilter.
pretty_vcproj.FixFilenames(filenames, current_directory)
Referenced by AbsoluteNode, GetChildrenVsprops, main.
pretty_vcproj.AbsoluteNode(node)
Makes all the properties we know about in this node absolute.
References FixFilenames.
Referenced by CleanupVcproj.
pretty_vcproj.CleanupVcproj(node)
For each sub node, we call recursively this function.
References AbsoluteNode, CleanupVcproj, FlattenFilter.
Referenced by CleanupVcproj, main.
pretty_vcproj.GetConfiguationNodes(vcproj)
Referenced by main.
pretty_vcproj.GetChildrenVsprops(filename)
References FixFilenames.
Referenced by main.
pretty_vcproj.SeekToNode(node1, child2)
Referenced by MergeProperties.
pretty_vcproj.MergeAttributes(node1, node2)
Referenced by MergeProperties.
pretty_vcproj.MergeProperties(node1, node2)
References MergeAttributes, MergeProperties, SeekToNode.
Referenced by main, MergeProperties.
pretty_vcproj.main(argv)
Main function of this vcproj prettifier.
References CleanupVcproj, FixFilenames, GetChildrenVsprops, GetConfiguationNodes, main, MergeProperties, PrettyPrintNode.
Referenced by main.