gyp::generator::cmake
gyp::generator::cmake._maketrans
Referenced by gyp.generator.cmake.StringToCMakeTargetName.
dict gyp::generator::cmake.generator_default_variables
tuple gyp::generator::cmake.FULL_PATH_VARS
bool gyp::generator::cmake.generator_supports_multiple_toolsets
bool gyp::generator::cmake.generator_wants_static_library_dependencies_adjusted
dict gyp::generator::cmake.COMPILABLE_EXTENSIONS
dict gyp::generator::cmake.cmake_target_type_from_gyp_target_type
gyp::generator::cmake.cmake_inputs
gyp::generator::cmake.cmake_outputs
gyp::generator::cmake.gyp_inputs
gyp::generator::cmake.gyp_outputs
gyp::generator::cmake.ext
gyp::generator::cmake.inputs_name
gyp::generator::cmake.outputs_name
gyp::generator::cmake.command
gyp.generator.cmake.RemovePrefix(a, prefix)
Returns 'a' without 'prefix' if it starts with 'prefix'.
Referenced by gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.CalculateVariables(default_variables, params)
Calculate additional variables for use in the build (called by gyp).
References gyp.common.GetFlavor.
gyp.generator.cmake.Compilable(filename)
Return true if the file is compilable (should be in OBJS).
gyp.generator.cmake.Linkable(filename)
Return true if the file is linkable (should be on the link line).
Referenced by gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.NormjoinPathForceCMakeSource(base_path, rel_path)
Resolves rel_path against base_path and returns the result. If rel_path is an absolute path it is returned unchanged. Otherwise it is resolved against base_path and normalized. If the result is a relative path, it is forced to be relative to the CMakeLists.txt.
Referenced by gyp.generator.cmake.NormjoinRulePathForceCMakeSource, gyp.generator.cmake.WriteActions, gyp.generator.cmake.WriteRules, gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.NormjoinPath(base_path, rel_path)
Resolves rel_path against base_path and returns the result. TODO: what is this really used for? If rel_path begins with '$' it is returned unchanged. Otherwise it is resolved against base_path if relative, then normalized.
Referenced by gyp.generator.cmake.WriteRules, gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.CMakeStringEscape(a)
Escapes the string 'a' for use inside a CMake string. This means escaping '\' otherwise it may be seen as modifying the next character '"' otherwise it will end the string ';' otherwise the string becomes a list The following do not need to be escaped '#' when the lexer is in string state, this does not start a comment The following are yet unknown '$' generator variables (like ${obj}) must not be escaped, but text $ should be escaped what is wanted is to know which $ come from generator variables
Referenced by gyp.generator.cmake.SetFileProperty, gyp.generator.cmake.SetFilesProperty, gyp.generator.cmake.SetTargetProperty, gyp.generator.cmake.SetVariable, gyp.generator.cmake.SetVariableList.
gyp.generator.cmake.SetFileProperty(output, source_name, property_name, values, sep)
Given a set of source file, sets the given property on them.
References gyp.generator.cmake.CMakeStringEscape.
Referenced by gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.SetFilesProperty(output, variable, property_name, values, sep)
Given a set of source files, sets the given property on them.
References gyp.generator.cmake.CMakeStringEscape, gyp.generator.cmake.WriteVariable.
Referenced by gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.SetTargetProperty(output, target_name, property_name, values, sep="")
Given a target, sets the given property.
References gyp.generator.cmake.CMakeStringEscape.
Referenced by gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.SetVariable(output, variable_name, value)
Sets a CMake variable.
References gyp.generator.cmake.CMakeStringEscape.
Referenced by gyp.generator.cmake.GenerateOutputForConfig, gyp.generator.cmake.SetVariableList, gyp.generator.cmake.WriteRules, gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.SetVariableList(output, variable_name, values)
Sets a CMake variable to a list.
References gyp.generator.cmake.CMakeStringEscape, gyp.generator.cmake.SetVariable.
Referenced by gyp.generator.cmake.WriteActions, gyp.generator.cmake.WriteRules, gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.UnsetVariable(output, variable_name)
Unsets a CMake variable.
Referenced by gyp.generator.cmake.WriteRules, gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.WriteVariable(output, variable_name, prepend=None)
Referenced by gyp.generator.cmake.SetFilesProperty, gyp.generator.cmake.WriteActions, gyp.generator.cmake.WriteRules, gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.StringToCMakeTargetName(a)
Converts the given string 'a' to a valid CMake target name. All invalid characters are replaced by '_'. Invalid for cmake: ' ', '/', '(', ')', '"' Invalid for make: ':' Invalid for unknown reasons but cause failures: '.'
References gyp.generator.cmake._maketrans.
Referenced by gyp.generator.cmake.CreateCMakeTargetBaseName, gyp.generator.cmake.CreateCMakeTargetFullName, gyp.generator.cmake.WriteActions, gyp.generator.cmake.WriteRules.
gyp.generator.cmake.WriteActions(target_name, actions, extra_sources, extra_deps, path_to_gyp, output)
Write CMake for the 'actions' in the target. Args: target_name: the name of the CMake target being generated. actions: the Gyp 'actions' dict for this target. extra_sources: [(<cmake_src>, <src>)] to append with generated source files. extra_deps: [<cmake_taget>] to append with generated targets. path_to_gyp: relative path from CMakeLists.txt being generated to the Gyp file in which the target being generated is defined.
References gyp.common.EncodePOSIXShellList, gyp.generator.cmake.NormjoinPathForceCMakeSource, gyp.generator.cmake.SetVariableList, gyp.generator.cmake.StringToCMakeTargetName, gyp.generator.cmake.WriteVariable.
Referenced by gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.NormjoinRulePathForceCMakeSource(base_path, rel_path, rule_source)
References gyp.generator.cmake.NormjoinPathForceCMakeSource.
Referenced by gyp.generator.cmake.WriteRules.
gyp.generator.cmake.WriteRules(target_name, rules, extra_sources, extra_deps, path_to_gyp, output)
Write CMake for the 'rules' in the target. Args: target_name: the name of the CMake target being generated. actions: the Gyp 'actions' dict for this target. extra_sources: [(<cmake_src>, <src>)] to append with generated source files. extra_deps: [<cmake_taget>] to append with generated targets. path_to_gyp: relative path from CMakeLists.txt being generated to the Gyp file in which the target being generated is defined.
References gyp.common.EncodePOSIXShellList, gyp.generator.cmake.NormjoinPath, gyp.generator.cmake.NormjoinPathForceCMakeSource, gyp.generator.cmake.NormjoinRulePathForceCMakeSource, gyp.generator.cmake.SetVariable, gyp.generator.cmake.SetVariableList, gyp.generator.cmake.StringToCMakeTargetName, gyp.generator.cmake.UnsetVariable, gyp.generator.cmake.WriteVariable.
Referenced by gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.WriteCopies(target_name, copies, extra_deps, path_to_gyp, output)
Write CMake for the 'copies' in the target. Args: target_name: the name of the CMake target being generated. actions: the Gyp 'actions' dict for this target. extra_deps: [<cmake_taget>] to append with generated targets. path_to_gyp: relative path from CMakeLists.txt being generated to the Gyp file in which the target being generated is defined.
Referenced by gyp.generator.cmake.WriteTarget.
gyp.generator.cmake.CreateCMakeTargetBaseName(qualified_target)
This is the name we would like the target to have.
References gyp.common.ParseQualifiedTarget, gyp.generator.cmake.StringToCMakeTargetName.
Referenced by gyp.generator.cmake.CMakeNamer.CreateCMakeTargetName.
gyp.generator.cmake.CreateCMakeTargetFullName(qualified_target)
An unambiguous name for the target.
References gyp.common.ParseQualifiedTarget, gyp.generator.cmake.StringToCMakeTargetName.
Referenced by gyp.generator.cmake.CMakeNamer.CreateCMakeTargetName.
gyp.generator.cmake.WriteTarget(namer, qualified_target, target_dicts, build_dir, config_to_use, options, generator_flags, all_qualified_targets, flavor, output)
References gyp.common.InvertRelativePath, gyp.generator.cmake.Linkable, gyp.generator.cmake.NormjoinPath, gyp.generator.cmake.NormjoinPathForceCMakeSource, gyp.common.ParseQualifiedTarget, gyp.common.RelativePath, gyp.generator.cmake.RemovePrefix, gyp.generator.cmake.SetFileProperty, gyp.generator.cmake.SetFilesProperty, gyp.generator.cmake.SetTargetProperty, gyp.generator.cmake.SetVariable, gyp.generator.cmake.SetVariableList, gyp.common.uniquer, gyp.generator.cmake.UnsetVariable, gyp.generator.cmake.WriteActions, gyp.generator.cmake.WriteCopies, gyp.generator.cmake.WriteRules, gyp.generator.cmake.WriteVariable.
Referenced by gyp.generator.cmake.GenerateOutputForConfig.
gyp.generator.cmake.GenerateOutputForConfig(target_list, target_dicts, data, params, config_to_use)
References gyp.common.AllTargets, gyp.common.EnsureDirExists, gyp.common.GetEnvironFallback, gyp.common.GetFlavor, gyp.common.InvertRelativePath, gyp.xcode_emulation.MergeGlobalXcodeSettingsToSpec, gyp.common.ParseQualifiedTarget, gyp.generator.cmake.SetVariable, gyp.generator.cmake.WriteTarget.
Referenced by gyp.generator.cmake.CallGenerateOutputForConfig, gyp.generator.cmake.GenerateOutput.
gyp.generator.cmake.PerformBuild(data, configurations, params)
gyp.generator.cmake.CallGenerateOutputForConfig(arglist)
References gyp.generator.cmake.GenerateOutputForConfig.
gyp.generator.cmake.GenerateOutput(target_list, target_dicts, data, params)
References gyp.generator.cmake.GenerateOutputForConfig.