gyp::common
gyp::common._quote
gyp::common._escape
gyp::common.tmp_path
gyp::common.tmp_file
gyp.common.ExceptionAppend(e, msg)
Append a message to the given exception's message.
Referenced by gyp.xcodeproj_file.XCObject._XCKVPrint, gyp.input.EvalSingleCondition, gyp.generator.xcode.GenerateOutput, gyp.input.Load, gyp.input.LoadOneBuildFile, gyp.input.LoadTargetBuildFile, gyp.input.VerifyNoGYPFileCircularDependencies.
gyp.common.FindQualifiedTargets(target, qualified_list)
Given a list of qualified targets, return the qualified targets for the specified |target|.
References gyp.common.ParseQualifiedTarget.
Referenced by gyp.input.PruneUnwantedTargets.
gyp.common.ParseQualifiedTarget(target)
Referenced by gyp.generator.msvs._GatherSolutionFolders, gyp.generator.analyzer._GenerateTargets, gyp.generator.analyzer._GetUnqualifiedToTargetMapping, gyp.generator.msvs._InitNinjaFlavor, gyp.common.BuildFile, gyp.generator.cmake.CreateCMakeTargetBaseName, gyp.generator.cmake.CreateCMakeTargetFullName, gyp.input.ExpandWildcardDependencies, gyp.generator.analyzer.TargetCalculator.find_matching_compile_target_names, gyp.generator.analyzer.TargetCalculator.find_matching_test_target_names, gyp.common.FindQualifiedTargets, gyp.generator.android.GenerateOutput, gyp.generator.compile_commands_json.GenerateOutput, gyp.generator.gypd.GenerateOutput, gyp.generator.make.GenerateOutput, gyp.generator.xcode.GenerateOutput, gyp.generator.cmake.GenerateOutputForConfig, gyp.generator.ninja.GenerateOutputForConfig, gyp.generator.eclipse.GetCompilerPath, gyp.common.ResolveTarget, gyp.generator.cmake.WriteTarget.
gyp.common.ResolveTarget(build_file, target, toolset)
References gyp.common.ParseQualifiedTarget, gyp.common.RelativePath.
Referenced by gyp.input.LoadTargetBuildFile, gyp.input.QualifyDependencies.
gyp.common.BuildFile(fully_qualified_target)
References gyp.common.ParseQualifiedTarget.
Referenced by gyp.generator.msvs._CreateProjectObjects, gyp.generator.msvs._GetPathOfProject, gyp.common.BuildFileTargets, gyp.input.DoDependentSettings, gyp.input.ExpandWildcardDependencies, gyp.input.Load, gyp.input.QualifyDependencies, gyp.input.SetUpConfigurations, gyp.input.VerifyNoGYPFileCircularDependencies.
gyp.common.GetEnvironFallback(var_list, default)
Look up a key in the environment, with fallback to secondary keys and finally falling back to a default value.
Referenced by gyp.generator.cmake.GenerateOutputForConfig.
gyp.common.QualifiedTarget(build_file, target, toolset)
Referenced by gyp.input.BuildTargetsDict, gyp.input.ExpandWildcardDependencies, gyp.generator.xcode.XcodeProject.Finalize1, gyp.generator.xcode.XcodeProject.Finalize2, gyp.generator.android.GenerateOutput, gyp.generator.ninja.GenerateOutputForConfig, gyp.input.PruneUnwantedTargets, gyp.input.QualifyDependencies.
gyp.common.RelativePath(path, relative_to, follow_path_symlink=True)
Referenced by gyp.generator.msvs._GenerateMSVSProject, gyp.generator.msvs._GetMSBuildProjectReferences, gyp.generator.msvs._GetPathOfProject, gyp.generator.msvs._InitNinjaFlavor, gyp.xcodeproj_file.PBXProject.AddOrGetProjectReference, gyp.input.ExpandVariables, gyp.common.FixIfRelativePath, gyp.generator.android.GenerateOutput, gyp.generator.make.GenerateOutput, gyp.generator.ninja.GenerateOutputForConfig, gyp.common.InvertRelativePath, gyp.input.LoadTargetBuildFile, gyp.input.MakePathRelative, gyp.generator.android.AndroidMkWriter.NormalizeIncludePaths, gyp.common.ResolveTarget, gyp.MSVSNew.MSVSSolution.Write, gyp.generator.make.WriteAutoRegenerationRule, gyp.generator.cmake.WriteTarget.
gyp.common.InvertRelativePath(path, toplevel_dir=None)
Given a path like foo/bar that is relative to toplevel_dir, return the inverse relative path back to the toplevel_dir. E.g. os.path.normpath(os.path.join(path, InvertRelativePath(path))) should always produce the empty string, unless the path contains symlinks.
References gyp.common.RelativePath.
Referenced by gyp.generator.cmake.GenerateOutputForConfig, gyp.generator.ninja.GenerateOutputForConfig, gyp.generator.cmake.WriteTarget, gyp.generator.make.MakefileWriter.WriteTarget.
gyp.common.FixIfRelativePath(path, relative_to)
References gyp.common.RelativePath.
Referenced by gyp.RegenerateFlags, gyp.generator.make.WriteAutoRegenerationRule.
gyp.common.UnrelativePath(path, relative_to)
Referenced by gyp.generator.analyzer._WasBuildFileModified, gyp.generator.android.GenerateOutput, gyp.generator.make.GenerateOutput.
gyp.common.EncodePOSIXShellArgument(argument)
Encodes |argument| suitably for consumption by POSIX shells. argument may be quoted and escaped as necessary to ensure that POSIX shells treat the returned value as a literal representing the argument passed to this function. Parameter (variable) expansions beginning with $ are allowed to remain intact without escaping the $, to allow the argument to contain references to variables to be expanded by the shell.
Referenced by gyp.generator.compile_commands_json.AddCommandsForTarget, gyp.generator.ninja.NinjaWriter.ComputeExportEnvString, gyp.common.EncodePOSIXShellList, gyp.generator.xcode.GenerateOutput, gyp.generator.ninja.NinjaWriter.WriteLinkForArch.
gyp.common.EncodePOSIXShellList(list)
Encodes |list| suitably for consumption by POSIX shells. Returns EncodePOSIXShellArgument for each item in list, and joins them together using the space character as an argument separator.
References gyp.common.EncodePOSIXShellArgument.
Referenced by gyp.generator.compile_commands_json.AddCommandsForTarget, gyp.input.ExpandVariables, gyp.generator.xcode.XcodeProject.Finalize1, gyp.generator.xcode.GenerateOutput, gyp.generator.ninja.NinjaWriter.GetPostbuildCommand, gyp.xcode_emulation.GetSpecPostbuildCommands, gyp.generator.android.AndroidMkWriter.WriteActions, gyp.generator.cmake.WriteActions, gyp.generator.make.MakefileWriter.WriteActions, gyp.generator.make.WriteAutoRegenerationRule, gyp.generator.ninja.NinjaWriter.WriteLinkForArch, gyp.generator.ninja.NinjaWriter.WriteNewNinjaRule, gyp.generator.android.AndroidMkWriter.WriteRules, gyp.generator.cmake.WriteRules, gyp.generator.make.MakefileWriter.WriteRules, gyp.generator.make.MakefileWriter.WriteTarget.
gyp.common.DeepDependencyTargets(target_dicts, roots)
Returns the recursive list of target dependencies.
Referenced by gyp.common.AllTargets, gyp.generator.msvs.GenerateOutput.
gyp.common.BuildFileTargets(target_list, build_file)
From a target_list, returns the subset from the specified build_file.
References gyp.common.BuildFile.
Referenced by gyp.common.AllTargets, gyp.generator.msvs.GenerateOutput.
gyp.common.AllTargets(target_list, target_dicts, build_file)
Returns all targets (direct and dependencies) for the specified build_file.
References gyp.common.BuildFileTargets, gyp.common.DeepDependencyTargets.
Referenced by gyp.generator.android.GenerateOutput, gyp.generator.make.GenerateOutput, gyp.generator.cmake.GenerateOutputForConfig, gyp.generator.ninja.GenerateOutputForConfig.
gyp.common.WriteOnDiff(filename)
Write to a file only if the new contents differ. Arguments: filename: name of the file to potentially write to. Returns: A file like object which will write to temporary file and only overwrite the target if it differs (on close).
References gyp.common.IsCygwin.
Referenced by gyp.generator.msvs._GenerateExternalRules, gyp.msvs_emulation.MsvsSettings._GetLdManifestFlags, gyp.input.ExpandVariables.
gyp.common.EnsureDirExists(path)
Make sure the directory for |path| exists.
Referenced by gyp.generator.msvs._GenerateMSBuildProject, gyp.generator.msvs._GenerateMSVSProject, gyp.msvs_emulation.MsvsSettings._GetLdManifestFlags, gyp.input.ExpandVariables, gyp.generator.eclipse.GenerateCdtSettingsFile, gyp.generator.eclipse.GenerateClasspathFile, gyp.generator.android.GenerateOutput, gyp.generator.compile_commands_json.GenerateOutput, gyp.generator.make.GenerateOutput, gyp.generator.cmake.GenerateOutputForConfig, gyp.generator.ninja.OpenOutput, gyp.generator.android.AndroidMkWriter.Write, gyp.generator.make.MakefileWriter.Write, gyp.generator.make.MakefileWriter.WriteSubMake.
gyp.common.GetFlavor(params)
Returns |params.flavor| if it's set, the system's default flavor else.
Referenced by gyp.common_test.TestGetFlavor.assertFlavor, gyp.generator.analyzer.CalculateVariables, gyp.generator.cmake.CalculateVariables, gyp.generator.compile_commands_json.CalculateVariables, gyp.generator.dump_dependency_json.CalculateVariables, gyp.generator.eclipse.CalculateVariables, gyp.generator.make.CalculateVariables, gyp.generator.msvs.CalculateVariables, gyp.generator.ninja.CalculateVariables, gyp.generator.make.GenerateOutput, gyp.generator.ninja.GenerateOutput, gyp.generator.cmake.GenerateOutputForConfig, gyp.generator.ninja.GenerateOutputForConfig, gyp.generator.eclipse.GetAllDefines, gyp.generator.eclipse.GetAllIncludeDirectories, gyp.generator.compile_commands_json.IsMac.
gyp.common.CopyTool(flavor, out_path, generator_flags={})
Finds (flock|mac|win)_tool.gyp in the gyp directory and copies it to |out_path|.
Referenced by gyp.generator.make.GenerateOutput, gyp.generator.ninja.GenerateOutputForConfig.
gyp.common.uniquer(seq, idfun=lambda x:x)
Referenced by gyp.generator.android.AndroidMkWriter.ComputeDeps, gyp.generator.make.MakefileWriter.ComputeDeps, gyp.generator.ninja.NinjaWriter.WriteLinkForArch, gyp.generator.android.AndroidMkWriter.WriteSources, gyp.generator.cmake.WriteTarget, gyp.generator.make.MakefileWriter.WriteTarget, gyp.generator.android.AndroidMkWriter.WriteTargetFlags.
gyp.common.TopologicallySorted(graph, get_edges)
Topologically sort based on a user provided edge definition. Args: graph: A list of node names. get_edges: A function mapping from node name to a hashable collection of node names which this node has outgoing edges to. Returns: A list containing all of the node in graph in topological order. It is assumed that calling get_edges once for each node and caching is cheaper than repeatedly calling get_edges. Raises: CycleError in the event of a cycle. Example: graph = {'a': '$(b) $(c)', 'b': 'hi', 'c': '$(b)'} def GetEdges(node): return re.findall(r'\$\(([^))]\)', graph[node]) print TopologicallySorted(graph.keys(), GetEdges) ==> ['a', 'c', b']
Referenced by gyp.generator.msvs._GetMSBuildPropertyGroup, gyp.xcode_emulation._TopologicallySortedEnvVarKeys, gyp.common_test.TestTopologicallySorted.test_Valid.
gyp.common.CrossCompileRequested()
Referenced by gyp.xcode_emulation.XcodeSettings.GetCflags, gyp.xcode_emulation.XcodeSettings.GetLdflags.
gyp.common.IsCygwin()
Referenced by gyp.common.WriteOnDiff.