gyp::easy_xml
dict gyp::easy_xml._xml_escape_map
gyp::easy_xml._xml_escape_re
gyp.easy_xml.XmlToString(content, encoding="utf-8", pretty=False)
Writes the XML content to disk, touching the file only if it has changed. Visual Studio files have a lot of pre-defined structures. This function makes it easy to represent these structures as Python data structures, instead of having to create a lot of function calls. Each XML element of the content is represented as a list composed of: 1. The name of the element, a string, 2. The attributes of the element, a dictionary (optional), and 3+. The content of the element, if any. Strings are simple text nodes and lists are child elements. Example 1: <test/> becomes ['test'] Example 2: <myelement a='value1' b='value2'> <childtype>This is</childtype> <childtype>it!</childtype> </myelement> becomes ['myelement', {'a':'value1', 'b':'value2'}, ['childtype', 'This is'], ['childtype', 'it!'], ] Args: content: The structured content to be converted. encoding: The encoding to report on the first XML line. pretty: True if we want pretty printing with indents and new lines. Returns: The XML content as a string.
References gyp.easy_xml._ConstructContentList.
Referenced by gyp.easy_xml.WriteXmlIfChanged.
gyp.easy_xml._ConstructContentList(xml_parts, specification, pretty, level=0)
Appends the XML parts corresponding to the specification. Args: xml_parts: A list of XML parts to be appended to. specification: The specification of the element. See EasyXml docs. pretty: True if we want pretty printing with indents and new lines. level: Indentation level.
References gyp.easy_xml._ConstructContentList, gyp.easy_xml._XmlEscape.
Referenced by gyp.easy_xml._ConstructContentList, gyp.easy_xml.XmlToString.
gyp.easy_xml.WriteXmlIfChanged(content, path, encoding="utf-8", pretty=False, win32=(sys.platform=="win32"))
Writes the XML content to disk, touching the file only if it has changed. Args: content: The structured content to be written. path: Location of the file. encoding: The encoding to report on the first line of the XML file. pretty: True if we want pretty printing with indents and new lines.
References gyp.easy_xml.XmlToString.
gyp.easy_xml._XmlEscape(value, attr=False)
Escape a string for inclusion in XML.
Referenced by gyp.easy_xml._ConstructContentList.