gyp::generator::ninja
dict gyp::generator::ninja.generator_default_variables
list gyp::generator::ninja.generator_additional_non_configuration_keys
list gyp::generator::ninja.generator_additional_path_sections
list gyp::generator::ninja.generator_extra_sources_for_rules
gyp::generator::ninja.generator_filelist_paths
gyp::generator::ninja.generator_supports_multiple_toolsets
gyp.generator.ninja.StripPrefix(arg, prefix)
Referenced by gyp.generator.ninja.NinjaWriter.ComputeOutputFileName.
gyp.generator.ninja.QuoteShellArgument(arg, flavor)
Quote a string such that it will be interpreted as a single argument by the shell.
References gyp.msvs_emulation.QuoteForRspFile.
Referenced by gyp.generator.ninja.Define, gyp.generator.ninja.GenerateOutputForConfig, gyp.generator.ninja.NinjaWriter.GetPostbuildCommand, gyp.generator.ninja.NinjaWriter.WriteLinkForArch, gyp.generator.ninja.NinjaWriter.WriteMacInfoPlist, gyp.generator.ninja.NinjaWriter.WriteMacXCassets.
gyp.generator.ninja.Define(d, flavor)
Takes a preprocessor define and returns a -D parameter that's ninja- and shell-escaped.
References gyp.generator.ninja.QuoteShellArgument.
Referenced by gyp.generator.ninja.NinjaWriter.WriteMacInfoPlist, gyp.generator.ninja.NinjaWriter.WriteSourcesForArch.
gyp.generator.ninja.AddArch(output, arch)
Adds an arch string to an output path.
Referenced by gyp.generator.ninja.NinjaWriter.ComputeOutput.
gyp.generator.ninja.CalculateVariables(default_variables, params)
Calculate additional variables for use in the build (called by gyp).
References gyp.msvs_emulation.CalculateCommonVariables, gyp.common.GetFlavor.
Referenced by gyp.generator.ninja.NinjaWriter.ComputeOutputFileName.
gyp.generator.ninja.ComputeOutputDir(params)
Returns the path from the toplevel_dir to the build output directory.
Referenced by gyp.xcode_ninja._TargetFromSpec, gyp.generator.ninja.CalculateGeneratorInputInfo, gyp.generator.ninja.GenerateOutputForConfig.
gyp.generator.ninja.CalculateGeneratorInputInfo(params)
Called by __init__ to initialize generator values based on params.
References gyp.generator.ninja.ComputeOutputDir.
gyp.generator.ninja.OpenOutput(path, mode="w")
Open |path| for writing, creating directories if necessary.
References gyp.common.EnsureDirExists.
Referenced by gyp.generator.ninja.GenerateOutputForConfig.
gyp.generator.ninja.CommandWithWrapper(cmd, wrappers, prog)
Referenced by gyp.generator.ninja.GenerateOutputForConfig.
gyp.generator.ninja.GetDefaultConcurrentLinks()
Returns a best-guess for a number of concurrent links.
Referenced by gyp.generator.ninja.GenerateOutputForConfig.
gyp.generator.ninja._GetWinLinkRuleNameSuffix(embed_manifest)
Returns the suffix used to select an appropriate linking rule depending on whether the manifest embedding is enabled.
Referenced by gyp.generator.ninja._AddWinLinkRules, gyp.generator.ninja.NinjaWriter.WriteLinkForArch.
gyp.generator.ninja._AddWinLinkRules(master_ninja, embed_manifest)
Adds link rules for Windows platform to |master_ninja|.
References gyp.generator.ninja._GetWinLinkRuleNameSuffix.
Referenced by gyp.generator.ninja.GenerateOutputForConfig.
gyp.generator.ninja.GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
References gyp.generator.ninja._AddWinLinkRules, gyp.common.AllTargets, gyp.generator.ninja.CommandWithWrapper, gyp.generator.ninja.ComputeOutputDir, gyp.common.CopyTool, gyp.msvs_emulation.ExtractSharedMSVSSystemIncludes, gyp.msvs_emulation.GenerateEnvironmentFiles, gyp.generator.ninja.GetDefaultConcurrentLinks, gyp.common.GetFlavor, gyp.common.InvertRelativePath, gyp.xcode_emulation.MergeGlobalXcodeSettingsToSpec, gyp.generator.ninja.OpenOutput, gyp.common.ParseQualifiedTarget, gyp.common.QualifiedTarget, gyp.generator.ninja.QuoteShellArgument, gyp.common.RelativePath.
Referenced by gyp.generator.ninja.CallGenerateOutputForConfig, gyp.generator.ninja.GenerateOutput.
gyp.generator.ninja.PerformBuild(data, configurations, params)
gyp.generator.ninja.CallGenerateOutputForConfig(arglist)
References gyp.generator.ninja.GenerateOutputForConfig.
gyp.generator.ninja.GenerateOutput(target_list, target_dicts, data, params)
References gyp.xcode_emulation.CloneConfigurationForDeviceAndEmulator, gyp.generator.ninja.GenerateOutputForConfig, gyp.common.GetFlavor.