gyp::xcode_emulation
gyp::xcode_emulation.XCODE_VERSION_CACHE
gyp::xcode_emulation.XCODE_ARCHS_DEFAULT_CACHE
gyp.xcode_emulation.XcodeArchsVariableMapping(archs, archs_including_64_bit=None)
Constructs a dictionary with expansion for $(ARCHS_STANDARD) variable, and optionally for $(ARCHS_STANDARD_INCLUDING_64_BIT).
Referenced by gyp.xcode_emulation.GetXcodeArchsDefault.
gyp.xcode_emulation.GetXcodeArchsDefault()
Returns the |XcodeArchsDefault| object to use to expand ARCHS for the installed version of Xcode. The default values used by Xcode for ARCHS and the expansion of the variables depends on the version of Xcode used. For all version anterior to Xcode 5.0 or posterior to Xcode 5.1 included uses $(ARCHS_STANDARD) if ARCHS is unset, while Xcode 5.0 to 5.0.2 uses $(ARCHS_STANDARD_INCLUDING_64_BIT). This variable was added to Xcode 5.0 and deprecated with Xcode 5.1. For "macosx" SDKROOT, all version starting with Xcode 5.0 includes 64-bit architecture as part of $(ARCHS_STANDARD) and default to only building it. For "iphoneos" and "iphonesimulator" SDKROOT, 64-bit architectures are part of $(ARCHS_STANDARD_INCLUDING_64_BIT) from Xcode 5.0. From Xcode 5.1, they are also part of $(ARCHS_STANDARD). All these rules are coded in the construction of the |XcodeArchsDefault| object to use depending on the version of Xcode detected. The object is for performance reason.
References gyp.xcode_emulation.XcodeArchsVariableMapping, gyp.xcode_emulation.XcodeVersion.
Referenced by gyp.xcode_emulation.XcodeSettings.GetActiveArchs.
gyp.xcode_emulation.XcodeVersion()
Returns a tuple of version and build version of installed Xcode.
References gyp.xcode_emulation.CLTVersion, gyp.xcode_emulation.GetStdoutQuiet.
Referenced by gyp.xcode_emulation.XcodeSettings._DefaultSdkRoot, gyp.xcode_emulation._GetXcodeEnv, gyp.xcode_emulation.XcodeSettings.GetExtraPlistItems, gyp.xcode_emulation.XcodeSettings.GetLdflags, gyp.xcode_emulation.GetXcodeArchsDefault.
gyp.xcode_emulation.CLTVersion()
Returns the version of command-line tools from pkgutil.
References gyp.xcode_emulation.GetStdout.
Referenced by gyp.xcode_emulation.XcodeVersion.
gyp.xcode_emulation.GetStdoutQuiet(cmdlist)
Returns the content of standard output returned by invoking |cmdlist|. Ignores the stderr. Raises |GypError| if the command return with a non-zero return code.
Referenced by gyp.xcode_emulation.XcodeSettings._GetSdkVersionInfoItem, gyp.xcode_emulation.XcodeVersion.
gyp.xcode_emulation.GetStdout(cmdlist)
Returns the content of standard output returned by invoking |cmdlist|. Raises |GypError| if the command return with a non-zero return code.
Referenced by gyp.xcode_emulation.XcodeSettings._BuildMachineOSBuild, gyp.xcode_emulation.XcodeSettings._DefaultSdkRoot, gyp.xcode_emulation.CLTVersion.
gyp.xcode_emulation.MergeGlobalXcodeSettingsToSpec(global_dict, spec)
Merges the global xcode_settings dictionary into each configuration of the target represented by spec. For keys that are both in the global and the local xcode_settings dict, the local key gets precedence.
Referenced by gyp.generator.compile_commands_json.GenerateOutput, gyp.generator.make.GenerateOutput, gyp.generator.cmake.GenerateOutputForConfig, gyp.generator.ninja.GenerateOutputForConfig.
gyp.xcode_emulation.IsMacBundle(flavor, spec)
Returns if |spec| should be treated as a bundle. Bundles are directories with a certain subdirectory structure, instead of just a single file. Bundle rules do not produce a binary but also package resources into that directory.
gyp.xcode_emulation.GetMacBundleResources(product_dir, xcode_settings, resources)
Yields (output, resource) pairs for every resource in |resources|. Only call this for mac bundle targets. Args: product_dir: Path to the directory containing the output bundle, relative to the build directory. xcode_settings: The XcodeSettings of the current target. resources: A list of bundle resources, relative to the build directory.
Referenced by gyp.generator.make.MakefileWriter.WriteMacBundleResources, gyp.generator.ninja.NinjaWriter.WriteMacBundleResources.
gyp.xcode_emulation.GetMacInfoPlist(product_dir, xcode_settings, gyp_path_to_build_path)
Returns (info_plist, dest_plist, defines, extra_env), where: * |info_plist| is the source plist path, relative to the build directory, * |dest_plist| is the destination plist path, relative to the build directory, * |defines| is a list of preprocessor defines (empty if the plist shouldn't be preprocessed, * |extra_env| is a dict of env variables that should be exported when invoking |mac_tool copy-info-plist|. Only call this for mac bundle targets. Args: product_dir: Path to the directory containing the output bundle, relative to the build directory. xcode_settings: The XcodeSettings of the current target. gyp_to_build_path: A function that converts paths relative to the current gyp file to paths relative to the build directory.
Referenced by gyp.generator.make.MakefileWriter.WriteMacInfoPlist, gyp.generator.ninja.NinjaWriter.WriteMacInfoPlist.
gyp.xcode_emulation._GetXcodeEnv(xcode_settings, built_products_dir, srcroot, configuration, additional_settings=None)
Return the environment variables that Xcode would set. See http://developer.apple.com/library/mac/#documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW153 for a full list. Args: xcode_settings: An XcodeSettings object. If this is None, this function returns an empty dict. built_products_dir: Absolute path to the built products dir. srcroot: Absolute path to the source root. configuration: The build configuration name. additional_settings: An optional dict with more values to add to the result.
References gyp.xcode_emulation._NormalizeEnvVarReferences, gyp.xcode_emulation.XcodeVersion.
Referenced by gyp.xcode_emulation.GetSortedXcodeEnv.
gyp.xcode_emulation._NormalizeEnvVarReferences(str)
Takes a string containing variable references in the form ${FOO}, $(FOO), or $FOO, and returns a string with all variable references in the form ${FOO}.
Referenced by gyp.xcode_emulation.XcodeSettings._GetStripPostbuilds, gyp.xcode_emulation._GetXcodeEnv.
gyp.xcode_emulation.ExpandEnvVars(string, expansions)
Expands ${VARIABLES}, $(VARIABLES), and $VARIABLES in string per the expansions list. If the variable expands to something that references another variable, this variable is expanded as well if it's in env -- until no variables present in env are left.
Referenced by gyp.generator.ninja.NinjaWriter.GypPathToNinja, gyp.generator.make.MakefileWriter.WriteActions, gyp.generator.make.MakefileWriter.WriteCopies, gyp.generator.ninja.NinjaWriter.WriteNewNinjaRule, gyp.generator.make.MakefileWriter.WriteRules.
gyp.xcode_emulation._TopologicallySortedEnvVarKeys(env)
Takes a dict |env| whose values are strings that can refer to other keys, for example env['foo'] = '$(bar) and $(baz)'. Returns a list L of all keys of env such that key2 is after key1 in L if env[key2] refers to env[key1]. Throws an Exception in case of dependency cycles.
References gyp.common.TopologicallySorted.
Referenced by gyp.xcode_emulation.GetSortedXcodeEnv.
gyp.xcode_emulation.GetSortedXcodeEnv(xcode_settings, built_products_dir, srcroot, configuration, additional_settings=None)
References gyp.xcode_emulation._GetXcodeEnv, gyp.xcode_emulation._TopologicallySortedEnvVarKeys.
Referenced by gyp.generator.make.MakefileWriter.GetSortedXcodeEnv, gyp.generator.ninja.NinjaWriter.GetSortedXcodeEnv.
gyp.xcode_emulation.GetSpecPostbuildCommands(spec, quiet=False)
Returns the list of postbuilds explicitly defined on |spec|, in a form executable by a shell.
References gyp.common.EncodePOSIXShellList.
Referenced by gyp.generator.ninja.NinjaWriter.GetPostbuildCommand, gyp.generator.make.MakefileWriter.WriteTarget.
gyp.xcode_emulation._HasIOSTarget(targets)
Returns true if any target contains the iOS specific key IPHONEOS_DEPLOYMENT_TARGET.
Referenced by gyp.xcode_emulation.CloneConfigurationForDeviceAndEmulator.
gyp.xcode_emulation._AddIOSDeviceConfigurations(targets)
Clone all targets and append -iphoneos to the name. Configure these targets to build for iOS devices and use correct architectures for those builds.
Referenced by gyp.xcode_emulation.CloneConfigurationForDeviceAndEmulator.
gyp.xcode_emulation.CloneConfigurationForDeviceAndEmulator(target_dicts)
If |target_dicts| contains any iOS targets, automatically create -iphoneos targets for iOS device builds.
References gyp.xcode_emulation._AddIOSDeviceConfigurations, gyp.xcode_emulation._HasIOSTarget.
Referenced by gyp.generator.ninja.GenerateOutput.