gyp::generator::xcode
str gyp::generator::xcode._intermediate_var
str gyp::generator::xcode._shared_intermediate_var
str gyp::generator::xcode._library_search_paths_var
dict gyp::generator::xcode.generator_default_variables
list gyp::generator::xcode.generator_additional_path_sections
list gyp::generator::xcode.generator_additional_non_configuration_keys
list gyp::generator::xcode.generator_extra_sources_for_rules
gyp::generator::xcode.generator_filelist_paths
gyp::generator::xcode.xcode_standard_library_dirs
gyp::generator::xcode._xcode_variable_re
gyp::generator::xcode._xcode_define_re
gyp.generator.xcode.CreateXCConfigurationList(configuration_names)
Referenced by gyp.generator.xcode.XcodeProject.Finalize1, gyp.generator.xcode.GenerateOutput.
gyp.generator.xcode.AddSourceToTarget(source, type, pbxp, xct)
Referenced by gyp.generator.xcode.GenerateOutput.
gyp.generator.xcode.AddResourceToTarget(resource, pbxp, xct)
Referenced by gyp.generator.xcode.GenerateOutput.
gyp.generator.xcode.AddHeaderToTarget(header, pbxp, xct, is_public)
Referenced by gyp.generator.xcode.GenerateOutput.
gyp.generator.xcode.ExpandXcodeVariables(string, expansions)
Expands Xcode-style $(VARIABLES) in string per the expansions dict. In some rare cases, it is appropriate to expand Xcode variables when a project file is generated. For any substring $(VAR) in string, if VAR is a key in the expansions dict, $(VAR) will be replaced with expansions[VAR]. Any $(VAR) substring in string for which VAR is not a key in the expansions dict will remain in the returned string.
Referenced by gyp.generator.xcode.GenerateOutput.
gyp.generator.xcode.EscapeXcodeDefine(s)
We must escape the defines that we give to XCode so that it knows not to split on spaces and to respect backslash and quote literals. However, we must not quote the define, or Xcode will incorrectly interpret variables especially $(inherited).
Referenced by gyp.generator.xcode.GenerateOutput.
gyp.generator.xcode.PerformBuild(data, configurations, params)
gyp.generator.xcode.CalculateGeneratorInputInfo(params)
gyp.generator.xcode.GenerateOutput(target_list, target_dicts, data, params)
References gyp.generator.xcode.AddHeaderToTarget, gyp.generator.xcode.AddResourceToTarget, gyp.generator.xcode.AddSourceToTarget, gyp.xcodeproj_file.ConvertVariablesToShellSyntax, gyp.xcode_ninja.CreateWrapper, gyp.generator.xcode.CreateXCConfigurationList, gyp.common.EncodePOSIXShellArgument, gyp.common.EncodePOSIXShellList, gyp.generator.xcode.EscapeXcodeDefine, gyp.common.ExceptionAppend, gyp.generator.xcode.ExpandXcodeVariables, gyp.common.ParseQualifiedTarget.