gyp::xcodeproj_file
gyp::xcodeproj_file._unquoted
gyp::xcodeproj_file._quoted
gyp::xcodeproj_file._escaped
gyp::xcodeproj_file._path_leading_variable
gyp.xcodeproj_file.cmp(x, y)
Referenced by gyp.xcodeproj_file.XCHierarchicalElement.Compare, gyp.xcodeproj_file.PBXProject.SortRemoteProductReferences.
gyp.xcodeproj_file.SourceTreeAndPathFromPath(input_path)
Given input_path, returns a tuple with sourceTree and path values. Examples: input_path (source_tree, output_path) '$(VAR)/path' ('VAR', 'path') '$(VAR)' ('VAR', None) 'path' (None, 'path')
gyp.xcodeproj_file.ConvertVariablesToShellSyntax(input_string)
Referenced by gyp.generator.xcode.XcodeProject.Finalize1, gyp.generator.xcode.GenerateOutput.