gyp::generator::analyzer
bool gyp::generator::analyzer.debug
str gyp::generator::analyzer.found_dependency_string
str gyp::generator::analyzer.no_dependency_string
str gyp::generator::analyzer.all_changed_string
int gyp::generator::analyzer.MATCH_STATUS_MATCHES
int gyp::generator::analyzer.MATCH_STATUS_MATCHES_BY_DEPENDENCY
int gyp::generator::analyzer.MATCH_STATUS_DOESNT_MATCH
int gyp::generator::analyzer.MATCH_STATUS_TBD
gyp::generator::analyzer.generator_supports_multiple_toolsets
bool gyp::generator::analyzer.generator_wants_static_library_dependencies_adjusted
dict gyp::generator::analyzer.generator_default_variables
gyp.generator.analyzer._ToGypPath(path)
Converts a path to the format used by gyp.
Referenced by gyp.generator.analyzer._ExtractSources, gyp.generator.analyzer._GenerateTargets, gyp.generator.analyzer._WasBuildFileModified, gyp.generator.analyzer._WasGypIncludeFileModified, gyp.generator.analyzer.GenerateOutput.
gyp.generator.analyzer._ResolveParent(path, base_path_components)
Resolves |path|, which starts with at least one '../'. Returns an empty string if the path shouldn't be considered. See _AddSources() for a description of |base_path_components|.
Referenced by gyp.generator.analyzer._AddSources.
gyp.generator.analyzer._AddSources(sources, base_path, base_path_components, result)
Extracts valid sources from |sources| and adds them to |result|. Each source file is relative to |base_path|, but may contain '..'. To make resolving '..' easier |base_path_components| contains each of the directories in |base_path|. Additionally each source may contain variables. Such sources are ignored as it is assumed dependencies on them are expressed and tracked in some other means.
References gyp.generator.analyzer._ResolveParent.
Referenced by gyp.generator.analyzer._ExtractSources, gyp.generator.analyzer._ExtractSourcesFromAction.
gyp.generator.analyzer._ExtractSourcesFromAction(action, base_path, base_path_components, results)
References gyp.generator.analyzer._AddSources.
Referenced by gyp.generator.analyzer._ExtractSources.
gyp.generator.analyzer._ToLocalPath(toplevel_dir, path)
Converts |path| to a path relative to |toplevel_dir|.
Referenced by gyp.generator.analyzer._ExtractSources, gyp.generator.analyzer._WasBuildFileModified.
gyp.generator.analyzer._ExtractSources(target, target_dict, toplevel_dir)
References gyp.generator.analyzer._AddSources, gyp.generator.analyzer._ExtractSourcesFromAction, gyp.generator.analyzer._ToGypPath, gyp.generator.analyzer._ToLocalPath.
Referenced by gyp.generator.analyzer._GenerateTargets.
gyp.generator.analyzer._WasBuildFileModified(build_file, data, files, toplevel_dir)
Returns true if the build file |build_file| is either in |files| or one of the files included by |build_file| is in |files|. |toplevel_dir| is the root of the source tree.
References gyp.generator.analyzer._ToGypPath, gyp.generator.analyzer._ToLocalPath, gyp.common.UnrelativePath.
Referenced by gyp.generator.analyzer._GenerateTargets.
gyp.generator.analyzer._GetOrCreateTargetByName(targets, target_name)
Creates or returns the Target at targets[target_name]. If there is no Target for |target_name| one is created. Returns a tuple of whether a new Target was created and the Target.
Referenced by gyp.generator.analyzer._GenerateTargets.
gyp.generator.analyzer._DoesTargetTypeRequireBuild(target_dict)
Returns true if the target type is such that it needs to be built.
Referenced by gyp.generator.analyzer._GenerateTargets.
gyp.generator.analyzer._GenerateTargets(data, target_list, target_dicts, toplevel_dir, files, build_files)
Returns a tuple of the following: . A dictionary mapping from fully qualified name to Target. . A list of the targets that have a source file in |files|. . Targets that constitute the 'all' target. See description at top of file for details on the 'all' target. This sets the |match_status| of the targets that contain any of the source files in |files| to MATCH_STATUS_MATCHES. |toplevel_dir| is the root of the source tree.
References gyp.generator.analyzer._DoesTargetTypeRequireBuild, gyp.generator.analyzer._ExtractSources, gyp.generator.analyzer._GetOrCreateTargetByName, gyp.generator.analyzer._ToGypPath, gyp.generator.analyzer._WasBuildFileModified, gyp.common.ParseQualifiedTarget.
gyp.generator.analyzer._GetUnqualifiedToTargetMapping(all_targets, to_find)
Returns a tuple of the following: . mapping (dictionary) from unqualified name to Target for all the Targets in |to_find|. . any target names not found. If this is empty all targets were found.
References gyp.common.ParseQualifiedTarget.
gyp.generator.analyzer._DoesTargetDependOnMatchingTargets(target)
Returns true if |target| or any of its dependencies is one of the targets containing the files supplied as input to analyzer. This updates |matches| of the Targets as it recurses. target: the Target to look for.
References gyp.generator.analyzer._DoesTargetDependOnMatchingTargets.
Referenced by gyp.generator.analyzer._DoesTargetDependOnMatchingTargets, gyp.generator.analyzer._GetTargetsDependingOnMatchingTargets.
gyp.generator.analyzer._GetTargetsDependingOnMatchingTargets(possible_targets)
Returns the list of Targets in |possible_targets| that depend (either directly on indirectly) on at least one of the targets containing the files supplied as input to analyzer. possible_targets: targets to search from.
References gyp.generator.analyzer._DoesTargetDependOnMatchingTargets.
Referenced by gyp.generator.analyzer.TargetCalculator.find_matching_test_target_names.
gyp.generator.analyzer._AddCompileTargets(target, roots, add_if_no_ancestor, result)
Recurses through all targets that depend on |target|, adding all targets that need to be built (and are in |roots|) to |result|. roots: set of root targets. add_if_no_ancestor: If true and there are no ancestors of |target| then add |target| to |result|. |target| must still be in |roots|. result: targets that need to be built are added here.
References gyp.generator.analyzer._AddCompileTargets.
Referenced by gyp.generator.analyzer._AddCompileTargets, gyp.generator.analyzer._GetCompileTargets.
gyp.generator.analyzer._GetCompileTargets(matching_targets, supplied_targets)
Returns the set of Targets that require a build. matching_targets: targets that changed and need to be built. supplied_targets: set of targets supplied to analyzer to search from.
References gyp.generator.analyzer._AddCompileTargets.
Referenced by gyp.generator.analyzer.TargetCalculator.find_matching_compile_target_names.
gyp.generator.analyzer._WriteOutput(params, **values)
Writes the output, either to stdout or a file is specified.
Referenced by gyp.generator.analyzer.GenerateOutput.
gyp.generator.analyzer._WasGypIncludeFileModified(params, files)
Returns true if one of the files in |files| is in the set of included files.
References gyp.generator.analyzer._ToGypPath.
Referenced by gyp.generator.analyzer.GenerateOutput.
gyp.generator.analyzer._NamesNotIn(names, mapping)
Returns a list of the values in |names| that are not in |mapping|.
gyp.generator.analyzer._LookupTargets(names, mapping)
Returns a list of the mapping[name] for each value in |names| that is in |mapping|.
Referenced by gyp.generator.analyzer.TargetCalculator.find_matching_compile_target_names, gyp.generator.analyzer.TargetCalculator.find_matching_test_target_names.
gyp.generator.analyzer.CalculateVariables(default_variables, params)
Calculate additional variables for use in the build (called by gyp).
References gyp.msvs_emulation.CalculateCommonVariables, gyp.common.GetFlavor.
gyp.generator.analyzer.GenerateOutput(target_list, target_dicts, data, params)
Called by gyp as the final stage. Outputs results.
References gyp.generator.analyzer._ToGypPath, gyp.generator.analyzer._WasGypIncludeFileModified, gyp.generator.analyzer._WriteOutput.