Napi
using Napi::Int8Array = TypedArrayOf<int8_t>
Typed-array of signed 8-bit integers.
using Napi::Uint8Array = TypedArrayOf<uint8_t>
Typed-array of unsigned 8-bit integers.
using Napi::Int16Array = TypedArrayOf<int16_t>
Typed-array of signed 16-bit integers.
using Napi::Uint16Array = TypedArrayOf<uint16_t>
Typed-array of unsigned 16-bit integers.
using Napi::Int32Array = TypedArrayOf<int32_t>
Typed-array of signed 32-bit integers.
using Napi::Uint32Array = TypedArrayOf<uint32_t>
Typed-array of unsigned 32-bit integers.
using Napi::Float32Array = TypedArrayOf<float>
Typed-array of 32-bit floating-point values.
using Napi::Float64Array = TypedArrayOf<double>
Typed-array of 64-bit floating-point values.
using Napi::ModuleRegisterCallback = Object (*)(Env env, Object exports)
Defines the signature of a Node-API C++ module's registration callback (init) function.
using Napi::MaybeOrValue = T
napi_value Napi::RegisterModule(napi_env env, napi_value exports, ModuleRegisterCallback registerCallback)
References Napi::details::WrapCallback.
Maybe< T > Napi::Nothing()
Referenced by Napi::Symbol::For, Napi::Symbol::WellKnown.
Maybe< T > Napi::Just(const T &t)
Referenced by Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::FunctionReference::Call, Napi::Symbol::For, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::ObjectReference::Get, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::MakeCallback, Napi::FunctionReference::New, Napi::FunctionReference::New, Napi::FunctionReference::operator(), Napi::Symbol::WellKnown.
napi_status Napi::CreateFunction(napi_env env, const char *utf8name, napi_callback cb, CbData *data, napi_value *result)
Referenced by Napi::Function::New.
Reference< T > Napi::Weak(T value)
References Napi::Reference< T >::New.
ObjectReference Napi::Weak(Object value)
References Napi::Reference< T >::New.
FunctionReference Napi::Weak(Function value)
References Napi::Reference< T >::New.
Reference< T > Napi::Persistent(T value)
References Napi::Reference< T >::New.
Referenced by node_sqlite3::Database::Init.
ObjectReference Napi::Persistent(Object value)
References Napi::Reference< T >::New.
FunctionReference Napi::Persistent(Function value)
References Napi::Reference< T >::New.