graphviz
graphviz.ParseTarget(target)
Referenced by WriteGraph.
graphviz.LoadEdges(filename, targets)
Load the edges map from the dump file, and filter it to only show targets in |targets| and their depedendents.
Referenced by main.
graphviz.WriteGraph(edges)
Print a graphviz graph to stdout. |edges| is a map of target to a list of other targets it depends on.
References ParseTarget.
Referenced by main.
graphviz.main()
References LoadEdges, main, WriteGraph.
Referenced by main.