gyp::mac_tool
gyp.mac_tool.main(args)
Referenced by gyp.mac_tool.WriteHmap.
gyp.mac_tool.NextGreaterPowerOf2(x)
Referenced by gyp.mac_tool.WriteHmap.
gyp.mac_tool.WriteHmap(output_name, filelist)
Generates a header map based on |filelist|. Per Mark Mentovai: A header map is structured essentially as a hash table, keyed by names used in #includes, and providing pathnames to the actual files. The implementation below and the comment above comes from inspecting: http://www.opensource.apple.com/source/distcc/distcc-2503/distcc_dist/include_server/headermap.py?txt while also looking at the implementation in clang in: https://llvm.org/svn/llvm-project/cfe/trunk/lib/Lex/HeaderMap.cpp
References gyp.mac_tool.main, gyp.mac_tool.NextGreaterPowerOf2.
Referenced by gyp.mac_tool.MacTool.ExecCompileIosFrameworkHeaderMap.