.TH "Models/_redirects.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models/_redirects.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBredirect\fP ($url)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "redirect ( $url)"

.PP
Definition at line \fB3\fP of file \fB_redirects\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
