.TH "Async< Item, Parent >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Async< Item, Parent >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <async\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAsync\fP (Parent *parent_, Callback cb_)"
.br
.ti -1c
.RI "void \fBfinish\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (Item *item)"
.br
.ti -1c
.RI "void \fBsend\fP ()"
.br
.ti -1c
.RI "void \fBsend\fP (Item *item)"
.br
.ti -1c
.RI "\fB~Async\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBlistener\fP (uv_async_t *handle)"
.br
.ti -1c
.RI "static void \fBclose\fP (uv_handle_t *handle)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Parent * \fBparent\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uv_async_t \fBwatcher\fP"
.br
.ti -1c
.RI "\fBNODE_SQLITE3_MUTEX_t\fP std::vector< Item * > \fBdata\fP"
.br
.ti -1c
.RI "Callback \fBcallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Item, class Parent>
.br
class Async< Item, Parent >"
.PP
Definition at line \fB10\fP of file \fBasync\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Item , class Parent > \fBAsync\fP< Item, Parent >\fB::Async\fP (Parent * parent_, Callback cb_)\fR [inline]\fP"

.PP
Definition at line \fB22\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > \fBAsync\fP< Item, Parent >::~\fBAsync\fP ()\fR [inline]\fP"

.PP
Definition at line \fB71\fP of file \fBasync\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class Item , class Parent > void \fBAsync\fP< Item, Parent >::add (Item * item)\fR [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > static void \fBAsync\fP< Item, Parent >::close (uv_handle_t * handle)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB41\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > void \fBAsync\fP< Item, Parent >::finish ()\fR [inline]\fP"

.PP
Definition at line \fB48\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > static void \fBAsync\fP< Item, Parent >::listener (uv_async_t * handle)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > void \fBAsync\fP< Item, Parent >::send ()\fR [inline]\fP"

.PP
Definition at line \fB62\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > void \fBAsync\fP< Item, Parent >::send (Item * item)\fR [inline]\fP"

.PP
Definition at line \fB66\fP of file \fBasync\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class Item , class Parent > Callback \fBAsync\fP< Item, Parent >::callback\fR [protected]\fP"

.PP
Definition at line \fB17\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > \fBNODE_SQLITE3_MUTEX_t\fP std::vector<Item*> \fBAsync\fP< Item, Parent >::data\fR [protected]\fP"

.PP
Definition at line \fB16\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > Parent* \fBAsync\fP< Item, Parent >::parent"

.PP
Definition at line \fB19\fP of file \fBasync\&.h\fP\&.
.SS "template<class Item , class Parent > uv_async_t \fBAsync\fP< Item, Parent >::watcher\fR [protected]\fP"

.PP
Definition at line \fB14\fP of file \fBasync\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
