.TH "authenticate.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
authenticate.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$DATABASE_HOST\fP = 'localhost'"
.br
.ti -1c
.RI "\fB$DATABASE_USER\fP = 'root'"
.br
.ti -1c
.RI "\fB$DATABASE_PASS\fP = ''"
.br
.ti -1c
.RI "\fB$DATABASE_NAME\fP = 'academy'"
.br
.ti -1c
.RI "\fB$usernae\fP = $_POST['username']"
.br
.ti -1c
.RI "\fB$con\fP = mysqli_connect($DATABASE_HOST, $DATABASE_USER, $DATABASE_PASS, $DATABASE_NAME)"
.br
.ti -1c
.RI "if(mysqli_connect_errno()) if(!isset($_POST['username'], $_POST['password'])) \fB$query\fP = 'SELECT `username` FROM academy\&.$usernae'"
.br
.ti -1c
.RI "if($name=$con\->prepare($query)) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$con = mysqli_connect($DATABASE_HOST, $DATABASE_USER, $DATABASE_PASS, $DATABASE_NAME)"

.PP
Definition at line \fB12\fP of file \fBauthenticate\&.php\fP\&.
.SS "$DATABASE_HOST = 'localhost'"

.PP
Definition at line \fB4\fP of file \fBauthenticate\&.php\fP\&.
.SS "$DATABASE_NAME = 'academy'"

.PP
Definition at line \fB7\fP of file \fBauthenticate\&.php\fP\&.
.SS "$DATABASE_PASS = ''"

.PP
Definition at line \fB6\fP of file \fBauthenticate\&.php\fP\&.
.SS "$DATABASE_USER = 'root'"

.PP
Definition at line \fB5\fP of file \fBauthenticate\&.php\fP\&.
.SS "if(mysqli_connect_errno()) if (!isset( $_POST[ 'username'], $_POST[ 'password'])) $query = 'SELECT `username` FROM academy\&.$usernae'"

.PP
Definition at line \fB22\fP of file \fBauthenticate\&.php\fP\&.
.SS "$usernae = $_POST['username']"

.PP
Definition at line \fB8\fP of file \fBauthenticate\&.php\fP\&.
.SS "if ( $name=$con\->prepare( $query)) else"
\fBInitial value:\fP
.nf
{
            
            echo 'Incorrect username and/or password!'
.PP
.fi

.PP
Definition at line \fB34\fP of file \fBauthenticate\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
