.TH "backend/node_modules/sqlite3/src/backup.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/sqlite3/src/backup.h
.SH SYNOPSIS
.br
.PP
\fR#include 'database\&.h'\fP
.br
\fR#include <string>\fP
.br
\fR#include <queue>\fP
.br
\fR#include <set>\fP
.br
\fR#include <sqlite3\&.h>\fP
.br
\fR#include <napi\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnode_sqlite3::Backup\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Backup::Baton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Backup::InitializeBaton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Backup::StepBaton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Backup::Call\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode_sqlite3\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
