.TH "backend/node_modules/sqlite3/src/backup.cc" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/sqlite3/src/backup.cc
.SH SYNOPSIS
.br
.PP
\fR#include <cstring>\fP
.br
\fR#include <napi\&.h>\fP
.br
\fR#include 'macros\&.h'\fP
.br
\fR#include 'database\&.h'\fP
.br
\fR#include 'backup\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
