.TH "backend/node_modules/node-gyp/docs/binding.gyp-files-in-the-wild.md" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/docs/binding.gyp-files-in-the-wild.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
