.TH "Views Directory Reference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdashboard\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfooter\&.php\fP"
.br
.ti -1c
.RI "file \fBheader\&.php\fP"
.br
.ti -1c
.RI "file \fBlogin\&.php\fP"
.br
.ti -1c
.RI "file \fBlogout\&.php\fP"
.br
.ti -1c
.RI "file \fBregister\&.php\fP"
.br
.in -1c
