.TH "Controllers Directory Reference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controllers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatabase\&.php\fP"
.br
.ti -1c
.RI "file \fBdbController\&.php\fP"
.br
.ti -1c
.RI "file \fBloginController\&.php\fP"
.br
.ti -1c
.RI "file \fBsite\&.config\&.php\fP"
.br
.in -1c
