.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/generator/cmake.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/generator/cmake.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.generator\&.cmake\&.CMakeTargetType\fP"
.br
.ti -1c
.RI "class \fBgyp\&.generator\&.cmake\&.CMakeNamer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\&.cmake\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.RemovePrefix\fP (a, prefix)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.CalculateVariables\fP (default_variables, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.Compilable\fP (filename)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.Linkable\fP (filename)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.NormjoinPathForceCMakeSource\fP (base_path, rel_path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.NormjoinPath\fP (base_path, rel_path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.CMakeStringEscape\fP (a)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.SetFileProperty\fP (output, source_name, property_name, values, sep)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.SetFilesProperty\fP (output, variable, property_name, values, sep)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.SetTargetProperty\fP (output, target_name, property_name, values, sep='')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.SetVariable\fP (output, variable_name, value)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.SetVariableList\fP (output, variable_name, values)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.UnsetVariable\fP (output, variable_name)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.WriteVariable\fP (output, variable_name, prepend=None)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.StringToCMakeTargetName\fP (a)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.WriteActions\fP (target_name, actions, extra_sources, extra_deps, path_to_gyp, output)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.NormjoinRulePathForceCMakeSource\fP (base_path, rel_path, rule_source)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.WriteRules\fP (target_name, rules, extra_sources, extra_deps, path_to_gyp, output)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.WriteCopies\fP (target_name, copies, extra_deps, path_to_gyp, output)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.CreateCMakeTargetBaseName\fP (qualified_target)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.CreateCMakeTargetFullName\fP (qualified_target)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.WriteTarget\fP (namer, qualified_target, target_dicts, build_dir, config_to_use, options, generator_flags, all_qualified_targets, flavor, output)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.GenerateOutputForConfig\fP (target_list, target_dicts, data, params, config_to_use)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.PerformBuild\fP (data, configurations, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.CallGenerateOutputForConfig\fP (arglist)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.GenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&._maketrans\fP = str\&.maketrans"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.cmake\&.generator_default_variables\fP"
.br
.ti -1c
.RI "tuple \fBgyp\&.generator\&.cmake\&.FULL_PATH_VARS\fP = ('${CMAKE_CURRENT_LIST_DIR}', '${builddir}', '${obj}')"
.br
.ti -1c
.RI "bool \fBgyp\&.generator\&.cmake\&.generator_supports_multiple_toolsets\fP = True"
.br
.ti -1c
.RI "bool \fBgyp\&.generator\&.cmake\&.generator_wants_static_library_dependencies_adjusted\fP = True"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.cmake\&.COMPILABLE_EXTENSIONS\fP"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.cmake\&.cmake_target_type_from_gyp_target_type\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.cmake_inputs\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.cmake_outputs\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.gyp_inputs\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.gyp_outputs\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.ext\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.inputs_name\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.outputs_name\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.cmake\&.command\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
