.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/generator/compile_commands_json.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/generator/compile_commands_json.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\&.compile_commands_json\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.compile_commands_json\&.IsMac\fP (params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.compile_commands_json\&.CalculateVariables\fP (default_variables, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.compile_commands_json\&.AddCommandsForTarget\fP (cwd, target, params, per_config_commands)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.compile_commands_json\&.GenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.compile_commands_json\&.PerformBuild\fP (data, configurations, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBgyp\&.generator\&.compile_commands_json\&.generator_additional_non_configuration_keys\fP = []"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.compile_commands_json\&.generator_additional_path_sections\fP = []"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.compile_commands_json\&.generator_extra_sources_for_rules\fP = []"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.compile_commands_json\&.generator_filelist_paths\fP = None"
.br
.ti -1c
.RI "bool \fBgyp\&.generator\&.compile_commands_json\&.generator_supports_multiple_toolsets\fP = True"
.br
.ti -1c
.RI "bool \fBgyp\&.generator\&.compile_commands_json\&.generator_wants_sorted_dependencies\fP = False"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.compile_commands_json\&.generator_default_variables\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
