.TH "database/database.cpp" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database/database.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBUser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBUser\fP > \fBfetchUsers\fP ()"
.br
.ti -1c
.RI "void \fBcreateUser\fP (const \fBUser\fP &user)"
.br
.ti -1c
.RI "void \fBcreateDatabase\fP (const std::string &name)"
.br
.ti -1c
.RI "std::vector< \fBUser\fP > \fBfetch_users\fP ()"
.br
.ti -1c
.RI "void \fBcreate_user\fP (const \fBUser\fP &user)"
.br
.ti -1c
.RI "void \fBcreate_database\fP (const std::string &name)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void create_database (const std::string & name)"

.PP
Definition at line \fB41\fP of file \fBdatabase\&.cpp\fP\&.
.SS "void create_user (const \fBUser\fP & user)"

.PP
Definition at line \fB37\fP of file \fBdatabase\&.cpp\fP\&.
.SS "void createDatabase (const std::string & name)"

.PP
Definition at line \fB23\fP of file \fBdatabase\&.cpp\fP\&.
.SS "void createUser (const \fBUser\fP & user)"

.PP
Definition at line \fB18\fP of file \fBdatabase\&.cpp\fP\&.
.SS "std::vector< \fBUser\fP > fetch_users ()"

.PP
Definition at line \fB33\fP of file \fBdatabase\&.cpp\fP\&.
.SS "std::vector< \fBUser\fP > fetchUsers ()"

.PP
Definition at line \fB11\fP of file \fBdatabase\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
