.TH "database" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($file)"
.br
.ti -1c
.RI "\fBconnect\fP ($hostname, $username, $password, $\fBdatabase\fP)"
.br
.ti -1c
.RI "\fBquery\fP ($query)"
.br
.ti -1c
.RI "\fBclose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBdatabase\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "database::__construct ( $file)"

.PP
Definition at line \fB11\fP of file \fBdatabase\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "database::close ()"

.PP
Definition at line \fB32\fP of file \fBdatabase\&.php\fP\&.
.SS "database::connect ( $hostname,  $username,  $password,  $database)"

.PP
Definition at line \fB18\fP of file \fBdatabase\&.php\fP\&.
.SS "database::query ( $query)"

.PP
Definition at line \fB24\fP of file \fBdatabase\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
