.TH "db.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "catch(PDOException $e) \fBget_courses\fP ($pdo)"
.br
.ti -1c
.RI "\fBget_ucourses\fP ($pdo, $email)"
.br
.ti -1c
.RI "\fBget_course\fP ($pdo, $id)"
.br
.ti -1c
.RI "\fBget_item\fP ($pdo, $id)"
.br
.ti -1c
.RI "\fBget_allcourses\fP ($pdo)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$servername\fP ='localhost'"
.br
.ti -1c
.RI "\fB$username\fP ='root'"
.br
.ti -1c
.RI "\fB$password\fP =''"
.br
.ti -1c
.RI "\fB$dbname\fP = 'academy'"
.br
.ti -1c
.RI "\fB$conn\fP =mysqli_connect($servername,$username,$password, $dbname)"
.br
.ti -1c
.RI "if(! $conn) \fBtry\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "get_allcourses ( $pdo)"

.PP
Definition at line \fB72\fP of file \fBdb\&.php\fP\&.
.SS "get_course ( $pdo,  $id)"

.PP
Definition at line \fB45\fP of file \fBdb\&.php\fP\&.
.SS "catch(PDOException $e) get_courses ( $pdo)"

.PP
Definition at line \fB23\fP of file \fBdb\&.php\fP\&.
.SS "get_item ( $pdo,  $id)"

.PP
Definition at line \fB60\fP of file \fBdb\&.php\fP\&.
.SS "get_ucourses ( $pdo,  $email)"

.PP
Definition at line \fB33\fP of file \fBdb\&.php\fP\&.
.SH "Variable Documentation"
.PP 
.SS "$conn =mysqli_connect($servername,$username,$password, $dbname)"

.PP
Definition at line \fB7\fP of file \fBdb\&.php\fP\&.
.SS "$dbname = 'academy'"

.PP
Definition at line \fB6\fP of file \fBdb\&.php\fP\&.
.SS "$password =''"

.PP
Definition at line \fB5\fP of file \fBdb\&.php\fP\&.
.SS "$servername ='localhost'"

.PP
Definition at line \fB3\fP of file \fBdb\&.php\fP\&.
.SS "$username ='root'"

.PP
Definition at line \fB4\fP of file \fBdb\&.php\fP\&.
.SS "if (! $conn) try"
\fBInitial value:\fP
.nf
{
            $pdo = new PDO("mysql:host=" \&. $servername \&. ";dbname=" \&. $dbname, $username, $password)
.PP
.fi

.PP
Definition at line \fB12\fP of file \fBdb\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
