.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/generator/dump_dependency_json.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/generator/dump_dependency_json.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\&.dump_dependency_json\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.dump_dependency_json\&.CalculateVariables\fP (default_variables, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.dump_dependency_json\&.CalculateGeneratorInputInfo\fP (params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.dump_dependency_json\&.GenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBgyp\&.generator\&.dump_dependency_json\&.generator_supports_multiple_toolsets\fP = True"
.br
.ti -1c
.RI "bool \fBgyp\&.generator\&.dump_dependency_json\&.generator_wants_static_library_dependencies_adjusted\fP = False"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.dump_dependency_json\&.generator_filelist_paths\fP = {}"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.dump_dependency_json\&.generator_default_variables\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
