.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/easy_xml.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/easy_xml.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.easy_xml\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.easy_xml\&.XmlToString\fP (content, encoding='utf\-8', pretty=False)"
.br
.ti -1c
.RI "\fBgyp\&.easy_xml\&._ConstructContentList\fP (xml_parts, specification, pretty, level=0)"
.br
.ti -1c
.RI "\fBgyp\&.easy_xml\&.WriteXmlIfChanged\fP (content, path, encoding='utf\-8', pretty=False, win32=(sys\&.platform=='win32'))"
.br
.ti -1c
.RI "\fBgyp\&.easy_xml\&._XmlEscape\fP (value, attr=False)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBgyp\&.easy_xml\&._xml_escape_map\fP"
.br
.ti -1c
.RI "\fBgyp\&.easy_xml\&._xml_escape_re\fP = re\&.compile('(%s)' % '|'\&.join(map(re\&.escape, _xml_escape_map\&.keys())))"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
