.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/generator/eclipse.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/generator/eclipse.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\&.eclipse\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.CalculateVariables\fP (default_variables, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.CalculateGeneratorInputInfo\fP (params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GetAllIncludeDirectories\fP (target_list, target_dicts, shared_intermediate_dirs, config_name, params, compiler_path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GetCompilerPath\fP (target_list, data, options)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GetAllDefines\fP (target_list, target_dicts, data, config_name, params, compiler_path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.WriteIncludePaths\fP (out, eclipse_langs, include_dirs)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.WriteMacros\fP (out, eclipse_langs, defines)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GenerateOutputForConfig\fP (target_list, target_dicts, data, params, config_name)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GenerateCdtSettingsFile\fP (target_list, target_dicts, data, params, config_name, out_name, options, shared_intermediate_dirs)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GenerateClasspathFile\fP (target_list, target_dicts, toplevel_dir, toplevel_build, out_name)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GetJavaJars\fP (target_list, target_dicts, toplevel_dir)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GetJavaSourceDirs\fP (target_list, target_dicts, toplevel_dir)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.eclipse\&.GenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBgyp\&.generator\&.eclipse\&.generator_wants_static_library_dependencies_adjusted\fP = False"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.eclipse\&.generator_default_variables\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
