.TH "Views/dashboard/execute.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views/dashboard/execute.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$request_body\fP = file_get_contents('php://input')"
.br
.ti -1c
.RI "\fB$data\fP = json_decode($request_body)"
.br
.ti -1c
.RI "\fB$sql\fP = $data\->sql"
.br
.ti -1c
.RI "\fB$servername\fP = 'localhost'"
.br
.ti -1c
.RI "\fB$username\fP = 'root'"
.br
.ti -1c
.RI "\fB$password\fP = '123'"
.br
.ti -1c
.RI "\fB$dbname\fP = 'akuma'"
.br
.ti -1c
.RI "\fB$conn\fP = new mysqli($servername, $username, $password, $dbname)"
.br
.ti -1c
.RI "if($conn\->connect_error) \fB$result\fP = $conn\->query($sql)"
.br
.ti -1c
.RI "if(! $result) \fBelse\fP"
.br
.ti -1c
.RI "while($row=$result\->fetch_assoc()) \fB$response\fP = $rows"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$conn = new mysqli($servername, $username, $password, $dbname)"

.PP
Definition at line \fB16\fP of file \fBexecute\&.php\fP\&.
.SS "$data = json_decode($request_body)"

.PP
Definition at line \fB5\fP of file \fBexecute\&.php\fP\&.
.SS "$dbname = 'akuma'"

.PP
Definition at line \fB13\fP of file \fBexecute\&.php\fP\&.
.SS "$password = '123'"

.PP
Definition at line \fB12\fP of file \fBexecute\&.php\fP\&.
.SS "$request_body = file_get_contents('php://input')"

.PP
Definition at line \fB4\fP of file \fBexecute\&.php\fP\&.
.SS "while ( $row=$result\->fetch_assoc()) $response = $rows"

.PP
Definition at line \fB33\fP of file \fBexecute\&.php\fP\&.
.SS "if ( $conn\->connect_error) $result = $conn\->query($sql)"

.PP
Definition at line \fB24\fP of file \fBexecute\&.php\fP\&.
.SS "$servername = 'localhost'"

.PP
Definition at line \fB10\fP of file \fBexecute\&.php\fP\&.
.SS "$sql = $data\->sql"

.PP
Definition at line \fB7\fP of file \fBexecute\&.php\fP\&.
.SS "$username = 'root'"

.PP
Definition at line \fB11\fP of file \fBexecute\&.php\fP\&.
.SS "if (! $result) else"
\fBInitial value:\fP
.nf
{
    $rows = []
.PP
.fi

.PP
Definition at line \fB28\fP of file \fBexecute\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
