.TH "backend/node_modules/node-gyp/lib/Find-VisualStudio.cs" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/lib/Find-VisualStudio.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBVisualStudioConfiguration\&.IEnumSetupInstances\fP"
.br
.ti -1c
.RI "interface \fBVisualStudioConfiguration\&.ISetupConfiguration\fP"
.br
.ti -1c
.RI "interface \fBVisualStudioConfiguration\&.ISetupConfiguration2\fP"
.br
.ti -1c
.RI "interface \fBVisualStudioConfiguration\&.ISetupInstance\fP"
.br
.ti -1c
.RI "interface \fBVisualStudioConfiguration\&.ISetupInstance2\fP"
.br
.ti -1c
.RI "interface \fBVisualStudioConfiguration\&.ISetupPackageReference\fP"
.br
.ti -1c
.RI "interface \fBVisualStudioConfiguration\&.ISetupPropertyStore\fP"
.br
.ti -1c
.RI "interface \fBVisualStudioConfiguration\&.SetupConfiguration\fP"
.br
.ti -1c
.RI "class \fBVisualStudioConfiguration\&.SetupConfigurationClass\fP"
.br
.ti -1c
.RI "class \fBVisualStudioConfiguration\&.Main\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBVisualStudioConfiguration\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBVisualStudioConfiguration\&.InstanceState\fP : uint { \fBVisualStudioConfiguration\&.None\fP = 0, \fBVisualStudioConfiguration\&.Local\fP = 1, \fBVisualStudioConfiguration\&.Registered\fP = 2, \fBVisualStudioConfiguration\&.NoRebootRequired\fP = 4, \fBVisualStudioConfiguration\&.NoErrors\fP = 8, \fBVisualStudioConfiguration\&.Complete\fP = 4294967295 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
