.TH "graphviz" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphviz
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBParseTarget\fP (target)"
.br
.ti -1c
.RI "\fBLoadEdges\fP (filename, targets)"
.br
.ti -1c
.RI "\fBWriteGraph\fP (edges)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Using the JSON dumped by the dump-dependency-json generator,
generate input suitable for graphviz to render a dependency graph of
targets\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "graphviz\&.LoadEdges ( filename,  targets)"

.PP
.nf
Load the edges map from the dump file, and filter it to only
show targets in |targets| and their depedendents\&.
.fi
.PP
 
.PP
Definition at line \fB23\fP of file \fBgraphviz\&.py\fP\&.
.SS "graphviz\&.main ()"

.PP
Definition at line \fB88\fP of file \fBgraphviz\&.py\fP\&.
.SS "graphviz\&.ParseTarget ( target)"

.PP
Definition at line \fB17\fP of file \fBgraphviz\&.py\fP\&.
.SS "graphviz\&.WriteGraph ( edges)"

.PP
.nf
Print a graphviz graph to stdout\&.
|edges| is a map of target to a list of other targets it depends on\&.
.fi
.PP
 
.PP
Definition at line \fB44\fP of file \fBgraphviz\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
