.TH "gyp.MSVSUserFile.Writer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSUserFile.Writer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBuser_file_path\fP, \fBversion\fP, \fBname\fP)"
.br
.ti -1c
.RI "\fBAddConfig\fP (self, \fBname\fP)"
.br
.ti -1c
.RI "\fBAddDebugSettings\fP (self, config_name, command, environment={}, working_directory='')"
.br
.ti -1c
.RI "\fBWriteIfChanged\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuser_file_path\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBconfigurations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Visual Studio XML user user file writer\&.
.fi
.PP
 
.PP
Definition at line \fB56\fP of file \fBMSVSUserFile\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSUserFile\&.Writer\&.__init__ ( self,  user_file_path,  version,  name)"

.PP
.nf
Initializes the user file\&.

Args:
user_file_path: Path to the user file\&.
version: Version info\&.
name: Name of the user file\&.

.fi
.PP
 
.PP
Definition at line \fB59\fP of file \fBMSVSUserFile\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSUserFile\&.Writer\&.AddConfig ( self,  name)"

.PP
.nf
Adds a configuration to the project\&.

Args:
name: Configuration name\&.

.fi
.PP
 
.PP
Definition at line \fB72\fP of file \fBMSVSUserFile\&.py\fP\&.
.SS "gyp\&.MSVSUserFile\&.Writer\&.AddDebugSettings ( self,  config_name,  command,  environment = \fR{}\fP,  working_directory = \fR''\fP)"

.PP
.nf
Adds a DebugSettings node to the user file for a particular config\&.

Args:
command: command line to run\&.  First element in the list is the
executable\&.  All elements of the command will be quoted if
necessary\&.
working_directory: other files which may trigger the rule\&. (optional)

.fi
.PP
 
.PP
Definition at line \fB80\fP of file \fBMSVSUserFile\&.py\fP\&.
.SS "gyp\&.MSVSUserFile\&.Writer\&.WriteIfChanged ( self)"

.PP
.nf
Writes the user file\&.
.fi
.PP
 
.PP
Definition at line \fB140\fP of file \fBMSVSUserFile\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSUserFile\&.Writer\&.configurations"

.PP
Definition at line \fB70\fP of file \fBMSVSUserFile\&.py\fP\&.
.SS "gyp\&.MSVSUserFile\&.Writer\&.name"

.PP
Definition at line \fB69\fP of file \fBMSVSUserFile\&.py\fP\&.
.SS "gyp\&.MSVSUserFile\&.Writer\&.user_file_path"

.PP
Definition at line \fB67\fP of file \fBMSVSUserFile\&.py\fP\&.
.SS "gyp\&.MSVSUserFile\&.Writer\&.version"

.PP
Definition at line \fB68\fP of file \fBMSVSUserFile\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
