.TH "gyp.win_tool" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.win_tool
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWinTool\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (args)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBASE_DIR\fP = os\&.path\&.dirname(os\&.path\&.abspath(__file__))"
.br
.ti -1c
.RI "\fB_LINK_EXE_OUT_ARG\fP = re\&.compile('/OUT:(?P<out>\&.+)$', re\&.IGNORECASE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Utility functions for Windows builds\&.

These functions are executed via gyp-win-tool when using the ninja generator\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "gyp\&.win_tool\&.main ( args)"

.PP
Definition at line \fB28\fP of file \fBwin_tool\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "gyp\&.win_tool\&._LINK_EXE_OUT_ARG = re\&.compile('/OUT:(?P<out>\&.+)$', re\&.IGNORECASE)\fR [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBwin_tool\&.py\fP\&.
.SS "gyp\&.win_tool\&.BASE_DIR = os\&.path\&.dirname(os\&.path\&.abspath(__file__))"

.PP
Definition at line \fB21\fP of file \fBwin_tool\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
