.TH "gyp.xcodeproj_file.XCProjectFile" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.xcodeproj_file.XCProjectFile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComputeIDs\fP (self, recursive=True, overwrite=True, hash=None)"
.br
.ti -1c
.RI "\fBPrint\fP (self, file=sys\&.stdout)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, properties=None, \fBid\fP=None, \fBparent\fP=None)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBCopy\fP (self)"
.br
.ti -1c
.RI "\fBName\fP (self)"
.br
.ti -1c
.RI "\fBComment\fP (self)"
.br
.ti -1c
.RI "\fBHashables\fP (self)"
.br
.ti -1c
.RI "\fBHashablesForChild\fP (self)"
.br
.ti -1c
.RI "\fBEnsureNoIDCollisions\fP (self)"
.br
.ti -1c
.RI "\fBChildren\fP (self)"
.br
.ti -1c
.RI "\fBDescendants\fP (self)"
.br
.ti -1c
.RI "\fBPBXProjectAncestor\fP (self)"
.br
.ti -1c
.RI "\fBUpdateProperties\fP (self, properties, do_copy=False)"
.br
.ti -1c
.RI "\fBHasProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBGetProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBSetProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBDelProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBAppendProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBVerifyHasRequiredProperties\fP (self)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_PrintObjects\fP (self, file)"
.br
.in -1c

Protected Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_EncodeComment\fP (self, comment)"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP (self, match)"
.br
.ti -1c
.RI "\fB_EncodeString\fP (self, value)"
.br
.ti -1c
.RI "\fB_XCPrint\fP (self, file, tabs, line)"
.br
.ti -1c
.RI "\fB_XCPrintableValue\fP (self, tabs, value, flatten_list=False)"
.br
.ti -1c
.RI "\fB_XCKVPrint\fP (self, file, tabs, key, value)"
.br
.ti -1c
.RI "\fB_SetDefaultsFromSchema\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_should_print_single_line\fP"
.br
.in -1c

Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_properties\fP"
.br
.ti -1c
.RI "\fB_hashables\fP"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_schema\fP = XCObject\&._schema\&.copy()"
.br
.in -1c

Static Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "dict \fB_schema\fP = {}"
.br
.ti -1c
.RI "bool \fB_should_print_single_line\fP = False"
.br
.ti -1c
.RI "list \fB_encode_transforms\fP = []"
.br
.ti -1c
.RI "\fB_alternate_encode_transforms\fP = list(\fB_encode_transforms\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.in -1c

Static Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "int \fBi\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3130\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCProjectFile\&._PrintObjects ( self,  file)\fR [protected]\fP"

.PP
Definition at line \fB3170\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCProjectFile\&.ComputeIDs ( self,  recursive = \fRTrue\fP,  overwrite = \fRTrue\fP,  seed_hash = \fRNone\fP)"

.PP
.nf
Set 'id' properties deterministically\&.

An object's 'id' property is set based on a hash of its class type and
name, as well as the class type and name of all ancestor objects\&.  As
such, it is only advisable to call ComputeIDs once an entire project file
tree is built\&.

If recursive is True, recurse into all descendant objects and update their
hashes\&.

If overwrite is True, any existing value set in the 'id' property will be
replaced\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB3141\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCProjectFile\&.Print ( self,  file = \fRsys\&.stdout\fP)"

.PP
.nf
Prints a reprentation of this object to file, adhering to Xcode output
formatting\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB3148\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCProjectFile\&._schema = XCObject\&._schema\&.copy()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB3131\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCProjectFile\&._should_print_single_line\fR [protected]\fP"

.PP
Definition at line \fB3156\fP of file \fBxcodeproj_file\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
