.TH "gyp.MSVSSettings._StringList" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSSettings._StringList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.MSVSSettings\&._Type\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidateMSVS\fP (self, value)"
.br
.ti -1c
.RI "\fBValidateMSBuild\fP (self, value)"
.br
.ti -1c
.RI "\fBConvertToMSBuild\fP (self, value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A settings that's a list of strings\&.
.fi
.PP
 
.PP
Definition at line \fB121\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._StringList\&.ConvertToMSBuild ( self,  value)"

.PP
.nf
Returns the MSBuild equivalent of the MSVS value given\&.

Args:
value: the MSVS value to convert\&.

Returns:
the MSBuild equivalent\&.

Raises:
ValueError if value is not valid\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB132\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._StringList\&.ValidateMSBuild ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSBuild\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSBuild\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB128\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._StringList\&.ValidateMSVS ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSVS\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSVS\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB124\fP of file \fBMSVSSettings\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
