.TH "gyp.MSVSNew.MSVSSolutionEntry" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSNew.MSVSSolutionEntry
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgyp\&.MSVSNew\&.MSVSFolder\fP, and \fBgyp\&.MSVSNew\&.MSVSProject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__cmp__\fP (self, other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB69\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSSolutionEntry\&.__cmp__ ( self,  other)"

.PP
Definition at line \fB70\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSSolutionEntry\&.name"

.PP
Definition at line \fB72\fP of file \fBMSVSNew\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
