.TH "gyp.MSVSProject.Tool" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSProject.Tool
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, name, attrs=None)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_GetSpecification\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_attrs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Visual Studio tool\&.
.fi
.PP
 
.PP
Definition at line \fB12\fP of file \fBMSVSProject\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSProject\&.Tool\&.__init__ ( self,  name,  attrs = \fRNone\fP)"

.PP
.nf
Initializes the tool\&.

Args:
name: Tool name\&.
attrs: Dict of tool attributes; may be None\&.

.fi
.PP
 
.PP
Definition at line \fB15\fP of file \fBMSVSProject\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSProject\&.Tool\&._GetSpecification ( self)\fR [protected]\fP"

.PP
.nf
Creates an element for the tool\&.

Returns:
A new xml\&.dom\&.Element for the tool\&.

.fi
.PP
 
.PP
Definition at line \fB25\fP of file \fBMSVSProject\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSProject\&.Tool\&._attrs\fR [protected]\fP"

.PP
Definition at line \fB22\fP of file \fBMSVSProject\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
