.TH "gyp.common.GypError" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.common.GypError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBgyp\&.input\&.DependencyGraphNode\&.CircularException\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Error class representing an error, which is to be presented
to the user\&.  The main entry point will catch and display this\&.

.fi
.PP
 
.PP
Definition at line \fB32\fP of file \fBcommon\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
