.TH "gyp.MSVSUserFile" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSUserFile
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_FindCommandInPath\fP (command)"
.br
.ti -1c
.RI "\fB_QuoteWin32CommandLineArgs\fP (args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Visual Studio user preferences file writer\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "gyp\&.MSVSUserFile\&._FindCommandInPath ( command)\fR [protected]\fP"

.PP
.nf
If there are no slashes in the command given, this function
 searches the PATH env to find the given command, and converts it
 to an absolute path\&.  We have to do this because MSVS is looking
 for an actual file to launch a debugger on, not just a command
 line\&.  Note that this happens at GYP time, so anything needing to
 be built needs to have a full path\&.
.fi
.PP
 
.PP
Definition at line \fB17\fP of file \fBMSVSUserFile\&.py\fP\&.
.SS "gyp\&.MSVSUserFile\&._QuoteWin32CommandLineArgs ( args)\fR [protected]\fP"

.PP
Definition at line \fB39\fP of file \fBMSVSUserFile\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
