.TH "gyp.generator.android" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.android
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAndroidMkWriter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIsCPPExtension\fP (ext)"
.br
.ti -1c
.RI "\fBSourceify\fP (path)"
.br
.ti -1c
.RI "\fBPerformBuild\fP (data, configurations, params)"
.br
.ti -1c
.RI "\fBGenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBgenerator_default_variables\fP"
.br
.ti -1c
.RI "bool \fBgenerator_supports_multiple_toolsets\fP = True"
.br
.ti -1c
.RI "list \fBgenerator_additional_non_configuration_keys\fP"
.br
.ti -1c
.RI "list \fBgenerator_additional_path_sections\fP = []"
.br
.ti -1c
.RI "list \fBgenerator_extra_sources_for_rules\fP = []"
.br
.ti -1c
.RI "str \fBALL_MODULES_FOOTER\fP"
.br
.ti -1c
.RI "str \fBheader\fP"
.br
.ti -1c
.RI "dict \fBMODULE_CLASSES\fP"
.br
.ti -1c
.RI "dict \fBtarget_outputs\fP = {}"
.br
.ti -1c
.RI "dict \fBtarget_link_deps\fP = {}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "gyp\&.generator\&.android\&.GenerateOutput ( target_list,  target_dicts,  data,  params)"

.PP
Definition at line \fB1032\fP of file \fBandroid\&.py\fP\&.
.SS "gyp\&.generator\&.android\&.IsCPPExtension ( ext)"

.PP
Definition at line \fB80\fP of file \fBandroid\&.py\fP\&.
.SS "gyp\&.generator\&.android\&.PerformBuild ( data,  configurations,  params)"

.PP
Definition at line \fB1021\fP of file \fBandroid\&.py\fP\&.
.SS "gyp\&.generator\&.android\&.Sourceify ( path)"

.PP
.nf
Convert a path to its source directory form\&. The Android backend does not
support options\&.generator_output, so this function is a noop\&.
.fi
.PP
 
.PP
Definition at line \fB84\fP of file \fBandroid\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "str gyp\&.generator\&.android\&.ALL_MODULES_FOOTER"
\fBInitial value:\fP
.nf
1 =  """\\
2 # "gyp_all_modules" is a concatenation of the "gyp_all_modules" targets from
3 # all the included sub\-makefiles\&. This is just here to clarify\&.
4 gyp_all_modules:
5 """
.PP
.fi

.PP
Definition at line \fB61\fP of file \fBandroid\&.py\fP\&.
.SS "list gyp\&.generator\&.android\&.generator_additional_non_configuration_keys"
\fBInitial value:\fP
.nf
1 =  [
2     # Boolean to declare that this target does not want its name mangled\&.
3     "android_unmangled_name",
4     # Map of android build system variables to set\&.
5     "aosp_build_settings",
6 ]
.PP
.fi

.PP
Definition at line \fB51\fP of file \fBandroid\&.py\fP\&.
.SS "list gyp\&.generator\&.android\&.generator_additional_path_sections = []"

.PP
Definition at line \fB57\fP of file \fBandroid\&.py\fP\&.
.SS "dict gyp\&.generator\&.android\&.generator_default_variables"
\fBInitial value:\fP
.nf
1 =  {
2     "OS": "android",
3     "EXECUTABLE_PREFIX": "",
4     "EXECUTABLE_SUFFIX": "",
5     "STATIC_LIB_PREFIX": "lib",
6     "SHARED_LIB_PREFIX": "lib",
7     "STATIC_LIB_SUFFIX": "\&.a",
8     "SHARED_LIB_SUFFIX": "\&.so",
9     "INTERMEDIATE_DIR": "$(gyp_intermediate_dir)",
10     "SHARED_INTERMEDIATE_DIR": "$(gyp_shared_intermediate_dir)",
11     "PRODUCT_DIR": "$(gyp_shared_intermediate_dir)",
12     "SHARED_LIB_DIR": "$(builddir)/lib\&.$(TOOLSET)",
13     "LIB_DIR": "$(obj)\&.$(TOOLSET)",
14     "RULE_INPUT_ROOT": "%(INPUT_ROOT)s",  # This gets expanded by Python\&.
15     "RULE_INPUT_DIRNAME": "%(INPUT_DIRNAME)s",  # This gets expanded by Python\&.
16     "RULE_INPUT_PATH": "$(RULE_SOURCES)",
17     "RULE_INPUT_EXT": "$(suffix $<)",
18     "RULE_INPUT_NAME": "$(notdir $<)",
19     "CONFIGURATION_NAME": "$(GYP_CONFIGURATION)",
20 }
.PP
.fi

.PP
Definition at line \fB25\fP of file \fBandroid\&.py\fP\&.
.SS "list gyp\&.generator\&.android\&.generator_extra_sources_for_rules = []"

.PP
Definition at line \fB58\fP of file \fBandroid\&.py\fP\&.
.SS "bool gyp\&.generator\&.android\&.generator_supports_multiple_toolsets = True"

.PP
Definition at line \fB47\fP of file \fBandroid\&.py\fP\&.
.SS "str gyp\&.generator\&.android\&.header"
\fBInitial value:\fP
.nf
1 =  """\\
2 # This file is generated by gyp; do not edit\&.
3 
4 """
.PP
.fi

.PP
Definition at line \fB67\fP of file \fBandroid\&.py\fP\&.
.SS "dict gyp\&.generator\&.android\&.MODULE_CLASSES"
\fBInitial value:\fP
.nf
1 =  {
2     "static_library": "STATIC_LIBRARIES",
3     "shared_library": "SHARED_LIBRARIES",
4     "executable": "EXECUTABLES",
5 }
.PP
.fi

.PP
Definition at line \fB73\fP of file \fBandroid\&.py\fP\&.
.SS "dict gyp\&.generator\&.android\&.target_link_deps = {}"

.PP
Definition at line \fB99\fP of file \fBandroid\&.py\fP\&.
.SS "dict gyp\&.generator\&.android\&.target_outputs = {}"

.PP
Definition at line \fB94\fP of file \fBandroid\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
