.TH "gyp.generator.ninja_test.TestPrefixesAndSuffixes" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.ninja_test.TestPrefixesAndSuffixes
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_BinaryNamesWindows\fP (self)"
.br
.ti -1c
.RI "\fBtest_BinaryNamesLinux\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBninja_test\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.generator\&.ninja_test\&.TestPrefixesAndSuffixes\&.test_BinaryNamesLinux ( self)"

.PP
Definition at line \fB34\fP of file \fBninja_test\&.py\fP\&.
.SS "gyp\&.generator\&.ninja_test\&.TestPrefixesAndSuffixes\&.test_BinaryNamesWindows ( self)"

.PP
Definition at line \fB16\fP of file \fBninja_test\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
