.TH "gyp.MSVSVersion.VisualStudioVersion" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSVersion.VisualStudioVersion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBshort_name\fP, \fBdescription\fP, \fBsolution_version\fP, \fBproject_version\fP, \fBflat_sln\fP, \fBuses_vcxproj\fP, \fBpath\fP, \fBsdk_based\fP, \fBdefault_toolset\fP=None, \fBcompatible_sdks\fP=None)"
.br
.ti -1c
.RI "\fBShortName\fP (self)"
.br
.ti -1c
.RI "\fBDescription\fP (self)"
.br
.ti -1c
.RI "\fBSolutionVersion\fP (self)"
.br
.ti -1c
.RI "\fBProjectVersion\fP (self)"
.br
.ti -1c
.RI "\fBFlatSolution\fP (self)"
.br
.ti -1c
.RI "\fBUsesVcxproj\fP (self)"
.br
.ti -1c
.RI "\fBProjectExtension\fP (self)"
.br
.ti -1c
.RI "\fBPath\fP (self)"
.br
.ti -1c
.RI "\fBToolPath\fP (self, tool)"
.br
.ti -1c
.RI "\fBDefaultToolset\fP (self)"
.br
.ti -1c
.RI "\fBSetupScript\fP (self, target_arch)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBshort_name\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBsolution_version\fP"
.br
.ti -1c
.RI "\fBproject_version\fP"
.br
.ti -1c
.RI "\fBflat_sln\fP"
.br
.ti -1c
.RI "\fBuses_vcxproj\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBsdk_based\fP"
.br
.ti -1c
.RI "\fBdefault_toolset\fP"
.br
.ti -1c
.RI "\fBcompatible_sdks\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_SetupScriptInternal\fP (self, target_arch)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Information regarding a version of Visual Studio\&.
.fi
.PP
 
.PP
Definition at line \fB19\fP of file \fBMSVSVersion\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.__init__ ( self,  short_name,  description,  solution_version,  project_version,  flat_sln,  uses_vcxproj,  path,  sdk_based,  default_toolset = \fRNone\fP,  compatible_sdks = \fRNone\fP)"

.PP
Definition at line \fB22\fP of file \fBMSVSVersion\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&._SetupScriptInternal ( self,  target_arch)\fR [protected]\fP"

.PP
.nf
Returns a command (with arguments) to be used to set up the
environment\&.
.fi
.PP
 
.PP
Definition at line \fB87\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.DefaultToolset ( self)"

.PP
.nf
Returns the msbuild toolset version that will be used in the absence
of a user override\&.
.fi
.PP
 
.PP
Definition at line \fB82\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.Description ( self)"

.PP
.nf
Get the full description of the version\&.
.fi
.PP
 
.PP
Definition at line \fB51\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.FlatSolution ( self)"

.PP
Definition at line \fB63\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.Path ( self)"

.PP
.nf
Returns the path to Visual Studio installation\&.
.fi
.PP
 
.PP
Definition at line \fB74\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.ProjectExtension ( self)"

.PP
.nf
Returns the file extension for the project\&.
.fi
.PP
 
.PP
Definition at line \fB70\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.ProjectVersion ( self)"

.PP
.nf
Get the version number of the vcproj or vcxproj files\&.
.fi
.PP
 
.PP
Definition at line \fB59\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.SetupScript ( self,  target_arch)"

.PP
Definition at line \fB144\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.ShortName ( self)"

.PP
Definition at line \fB48\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.SolutionVersion ( self)"

.PP
.nf
Get the version number of the sln files\&.
.fi
.PP
 
.PP
Definition at line \fB55\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.ToolPath ( self,  tool)"

.PP
.nf
Returns the path to a given compiler tool\&. 
.fi
.PP
 
.PP
Definition at line \fB78\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.UsesVcxproj ( self)"

.PP
.nf
Returns true if this version uses a vcxproj file\&.
.fi
.PP
 
.PP
Definition at line \fB66\fP of file \fBMSVSVersion\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.compatible_sdks"

.PP
Definition at line \fB46\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.default_toolset"

.PP
Definition at line \fB43\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.description"

.PP
Definition at line \fB36\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.flat_sln"

.PP
Definition at line \fB39\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.path"

.PP
Definition at line \fB41\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.project_version"

.PP
Definition at line \fB38\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.sdk_based"

.PP
Definition at line \fB42\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.short_name"

.PP
Definition at line \fB35\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.solution_version"

.PP
Definition at line \fB37\fP of file \fBMSVSVersion\&.py\fP\&.
.SS "gyp\&.MSVSVersion\&.VisualStudioVersion\&.uses_vcxproj"

.PP
Definition at line \fB40\fP of file \fBMSVSVersion\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
