.TH "gyp.MSVSSettings_test" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSSettings_test
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestSequenceFunctions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Unit tests for the MSVSSettings\&.py file\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
