.TH "gyp.generator.analyzer.TargetCalculator" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.analyzer.TargetCalculator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, files, additional_compile_target_names, test_target_names, data, target_list, target_dicts, toplevel_dir, build_files)"
.br
.ti -1c
.RI "\fBis_build_impacted\fP (self)"
.br
.ti -1c
.RI "\fBfind_matching_test_target_names\fP (self)"
.br
.ti -1c
.RI "\fBfind_matching_compile_target_names\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBinvalid_targets\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_supplied_target_names\fP (self)"
.br
.ti -1c
.RI "\fB_supplied_target_names_no_all\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_additional_compile_target_names\fP"
.br
.ti -1c
.RI "\fB_test_target_names\fP"
.br
.ti -1c
.RI "\fB_name_to_target\fP"
.br
.ti -1c
.RI "\fB_changed_targets\fP"
.br
.ti -1c
.RI "\fB_root_targets\fP"
.br
.ti -1c
.RI "\fB_unqualified_mapping\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Calculates the matching test_targets and matching compile_targets\&.
.fi
.PP
 
.PP
Definition at line \fB629\fP of file \fBanalyzer\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&.__init__ ( self,  files,  additional_compile_target_names,  test_target_names,  data,  target_list,  target_dicts,  toplevel_dir,  build_files)"

.PP
Definition at line \fB632\fP of file \fBanalyzer\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&._supplied_target_names ( self)\fR [protected]\fP"

.PP
Definition at line \fB659\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&._supplied_target_names_no_all ( self)\fR [protected]\fP"

.PP
.nf
Returns the supplied test targets without 'all'\&.
.fi
.PP
 
.PP
Definition at line \fB662\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&.find_matching_compile_target_names ( self)"

.PP
.nf
Returns the set of output compile targets\&.
.fi
.PP
 
.PP
Definition at line \fB720\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&.find_matching_test_target_names ( self)"

.PP
.nf
Returns the set of output test targets\&.
.fi
.PP
 
.PP
Definition at line \fB672\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&.is_build_impacted ( self)"

.PP
.nf
Returns true if the supplied files impact the build at all\&.
.fi
.PP
 
.PP
Definition at line \fB668\fP of file \fBanalyzer\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&._additional_compile_target_names\fR [protected]\fP"

.PP
Definition at line \fB643\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&._changed_targets\fR [protected]\fP"

.PP
Definition at line \fB647\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&._name_to_target\fR [protected]\fP"

.PP
Definition at line \fB646\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&._root_targets\fR [protected]\fP"

.PP
Definition at line \fB648\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&._test_target_names\fR [protected]\fP"

.PP
Definition at line \fB644\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&._unqualified_mapping\fR [protected]\fP"

.PP
Definition at line \fB653\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.TargetCalculator\&.invalid_targets"

.PP
Definition at line \fB654\fP of file \fBanalyzer\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
