.TH "gyp.MSVSSettings._Integer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSSettings._Integer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.MSVSSettings\&._Type\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, msbuild_base=10)"
.br
.ti -1c
.RI "\fBValidateMSVS\fP (self, value)"
.br
.ti -1c
.RI "\fBValidateMSBuild\fP (self, value)"
.br
.ti -1c
.RI "\fBConvertToMSBuild\fP (self, value)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_msbuild_base\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Integer settings\&.
.fi
.PP
 
.PP
Definition at line \fB158\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Integer\&.__init__ ( self,  msbuild_base = \fR10\fP)"

.PP
Definition at line \fB161\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Integer\&.ConvertToMSBuild ( self,  value)"

.PP
.nf
Returns the MSBuild equivalent of the MSVS value given\&.

Args:
value: the MSVS value to convert\&.

Returns:
the MSBuild equivalent\&.

Raises:
ValueError if value is not valid\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB173\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._Integer\&.ValidateMSBuild ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSBuild\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSBuild\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB169\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._Integer\&.ValidateMSVS ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSVS\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSVS\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB165\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Integer\&._msbuild_base\fR [protected]\fP"

.PP
Definition at line \fB163\fP of file \fBMSVSSettings\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
