.TH "gyp.input.ParallelState" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.input.ParallelState
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBLoadTargetBuildFileCallback\fP (self, result)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpool\fP"
.br
.ti -1c
.RI "\fBcondition\fP"
.br
.ti -1c
.RI "\fBdata\fP"
.br
.ti -1c
.RI "\fBpending\fP"
.br
.ti -1c
.RI "\fBscheduled\fP"
.br
.ti -1c
.RI "\fBdependencies\fP"
.br
.ti -1c
.RI "\fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class to keep track of state when processing input files in parallel\&.

If build files are loaded in parallel, use this to keep track of
state during farming out and processing parallel jobs\&. It's stored
in a global so that the callback function can have access to it\&.

.fi
.PP
 
.PP
Definition at line \fB559\fP of file \fBinput\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.input\&.ParallelState\&.__init__ ( self)"

.PP
Definition at line \fB567\fP of file \fBinput\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.input\&.ParallelState\&.LoadTargetBuildFileCallback ( self,  result)"

.PP
.nf
Handle the results of running LoadTargetBuildFile in another process\&.

.fi
.PP
 
.PP
Definition at line \fB586\fP of file \fBinput\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.input\&.ParallelState\&.condition"

.PP
Definition at line \fB572\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.ParallelState\&.data"

.PP
Definition at line \fB574\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.ParallelState\&.dependencies"

.PP
Definition at line \fB582\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.ParallelState\&.error"

.PP
Definition at line \fB584\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.ParallelState\&.pending"

.PP
Definition at line \fB577\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.ParallelState\&.pool"

.PP
Definition at line \fB569\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.ParallelState\&.scheduled"

.PP
Definition at line \fB580\fP of file \fBinput\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
