.TH "gyp.flock_tool.FlockTool" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.flock_tool.FlockTool
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDispatch\fP (self, args)"
.br
.ti -1c
.RI "\fBExecFlock\fP (self, lockfile, *cmd_list)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_CommandifyName\fP (self, name_string)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class emulates the 'flock' command\&.
.fi
.PP
 
.PP
Definition at line \fB21\fP of file \fBflock_tool\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.flock_tool\&.FlockTool\&._CommandifyName ( self,  name_string)\fR [protected]\fP"

.PP
.nf
Transforms a tool name like copy-info-plist to CopyInfoPlist
.fi
.PP
 
.PP
Definition at line \fB32\fP of file \fBflock_tool\&.py\fP\&.
.SS "gyp\&.flock_tool\&.FlockTool\&.Dispatch ( self,  args)"

.PP
.nf
Dispatches a string command to a method\&.
.fi
.PP
 
.PP
Definition at line \fB24\fP of file \fBflock_tool\&.py\fP\&.
.SS "gyp\&.flock_tool\&.FlockTool\&.ExecFlock ( self,  lockfile, * cmd_list)"

.PP
.nf
Emulates the most basic behavior of Linux's flock(1)\&.
.fi
.PP
 
.PP
Definition at line \fB36\fP of file \fBflock_tool\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
