.TH "backend/node_modules/node-gyp/gyp/gyp_main.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/gyp_main.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp_main\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp_main\&.IsCygwin\fP ()"
.br
.ti -1c
.RI "\fBgyp_main\&.UnixifyPath\fP (\fBpath\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgyp_main\&.path\fP = \fBUnixifyPath\fP(sys\&.argv[0])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
