.TH "gyp_main" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp_main
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIsCygwin\fP ()"
.br
.ti -1c
.RI "\fBUnixifyPath\fP (\fBpath\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpath\fP = \fBUnixifyPath\fP(sys\&.argv[0])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "gyp_main\&.IsCygwin ()"

.PP
Definition at line \fB12\fP of file \fBgyp_main\&.py\fP\&.
.SS "gyp_main\&.UnixifyPath ( path)"

.PP
Definition at line \fB24\fP of file \fBgyp_main\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "gyp_main\&.path = \fBUnixifyPath\fP(sys\&.argv[0])"

.PP
Definition at line \fB40\fP of file \fBgyp_main\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
