.TH "gyp.generator.xcode.XcodeProject" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.xcode.XcodeProject
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBgyp_path\fP, \fBpath\fP, \fBbuild_file_dict\fP)"
.br
.ti -1c
.RI "\fBFinalize1\fP (self, xcode_targets, serialize_all_tests)"
.br
.ti -1c
.RI "\fBFinalize2\fP (self, xcode_targets, xcode_target_to_target_dict)"
.br
.ti -1c
.RI "\fBWrite\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgyp_path\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBproject\fP"
.br
.ti -1c
.RI "\fBproject_file\fP"
.br
.ti -1c
.RI "\fBbuild_file_dict\fP"
.br
.ti -1c
.RI "\fBcreated_dir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB112\fP of file \fBxcode\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.__init__ ( self,  gyp_path,  path,  build_file_dict)"

.PP
Definition at line \fB113\fP of file \fBxcode\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.Finalize1 ( self,  xcode_targets,  serialize_all_tests)"

.PP
Definition at line \fB138\fP of file \fBxcode\&.py\fP\&.
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.Finalize2 ( self,  xcode_targets,  xcode_target_to_target_dict)"

.PP
Definition at line \fB388\fP of file \fBxcode\&.py\fP\&.
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.Write ( self)"

.PP
Definition at line \fB456\fP of file \fBxcode\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.build_file_dict"

.PP
Definition at line \fB125\fP of file \fBxcode\&.py\fP\&.
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.created_dir"

.PP
Definition at line \fB130\fP of file \fBxcode\&.py\fP\&.
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.gyp_path"

.PP
Definition at line \fB114\fP of file \fBxcode\&.py\fP\&.
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.path"

.PP
Definition at line \fB115\fP of file \fBxcode\&.py\fP\&.
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.project"

.PP
Definition at line \fB116\fP of file \fBxcode\&.py\fP\&.
.SS "gyp\&.generator\&.xcode\&.XcodeProject\&.project_file"

.PP
Definition at line \fB122\fP of file \fBxcode\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
