.TH "gyp.xcodeproj_file.XCConfigurationList" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.xcodeproj_file.XCConfigurationList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBName\fP (self)"
.br
.ti -1c
.RI "\fBConfigurationNamed\fP (self, name)"
.br
.ti -1c
.RI "\fBDefaultConfiguration\fP (self)"
.br
.ti -1c
.RI "\fBHasBuildSetting\fP (self, key)"
.br
.ti -1c
.RI "\fBGetBuildSetting\fP (self, key)"
.br
.ti -1c
.RI "\fBSetBuildSetting\fP (self, key, value)"
.br
.ti -1c
.RI "\fBAppendBuildSetting\fP (self, key, value)"
.br
.ti -1c
.RI "\fBDelBuildSetting\fP (self, key)"
.br
.ti -1c
.RI "\fBSetBaseConfiguration\fP (self, value)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self, properties=None, \fBid\fP=None, \fBparent\fP=None)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBCopy\fP (self)"
.br
.ti -1c
.RI "\fBComment\fP (self)"
.br
.ti -1c
.RI "\fBHashables\fP (self)"
.br
.ti -1c
.RI "\fBHashablesForChild\fP (self)"
.br
.ti -1c
.RI "\fBComputeIDs\fP (self, recursive=True, overwrite=True, seed_hash=None)"
.br
.ti -1c
.RI "\fBEnsureNoIDCollisions\fP (self)"
.br
.ti -1c
.RI "\fBChildren\fP (self)"
.br
.ti -1c
.RI "\fBDescendants\fP (self)"
.br
.ti -1c
.RI "\fBPBXProjectAncestor\fP (self)"
.br
.ti -1c
.RI "\fBPrint\fP (self, file=sys\&.stdout)"
.br
.ti -1c
.RI "\fBUpdateProperties\fP (self, properties, do_copy=False)"
.br
.ti -1c
.RI "\fBHasProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBGetProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBSetProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBDelProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBAppendProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBVerifyHasRequiredProperties\fP (self)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "list \fB_configs\fP"
.br
.ti -1c
.RI "\fB_schema\fP = XCObject\&._schema\&.copy()"
.br
.in -1c

Static Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "dict \fB_schema\fP = {}"
.br
.ti -1c
.RI "bool \fB_should_print_single_line\fP = False"
.br
.ti -1c
.RI "list \fB_encode_transforms\fP = []"
.br
.ti -1c
.RI "\fB_alternate_encode_transforms\fP = list(\fB_encode_transforms\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.in -1c

Static Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "int \fBi\fP = 0"
.br
.in -1c

Protected Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_EncodeComment\fP (self, comment)"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP (self, match)"
.br
.ti -1c
.RI "\fB_EncodeString\fP (self, value)"
.br
.ti -1c
.RI "\fB_XCPrint\fP (self, file, tabs, line)"
.br
.ti -1c
.RI "\fB_XCPrintableValue\fP (self, tabs, value, flatten_list=False)"
.br
.ti -1c
.RI "\fB_XCKVPrint\fP (self, file, tabs, key, value)"
.br
.ti -1c
.RI "\fB_SetDefaultsFromSchema\fP (self)"
.br
.in -1c

Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_properties\fP"
.br
.ti -1c
.RI "\fB_hashables\fP"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1683\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.AppendBuildSetting ( self,  key,  value)"

.PP
.nf
Appends value to the build setting for key, which is treated as a list,
in all child XCBuildConfiguration objects\&.

.fi
.PP
 
.PP
Definition at line \fB1783\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.ConfigurationNamed ( self,  name)"

.PP
.nf
Convenience accessor to obtain an XCBuildConfiguration by name\&.
.fi
.PP
 
.PP
Definition at line \fB1708\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.DefaultConfiguration ( self)"

.PP
.nf
Convenience accessor to obtain the default XCBuildConfiguration\&.
.fi
.PP
 
.PP
Definition at line \fB1716\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.DelBuildSetting ( self,  key)"

.PP
.nf
Deletes the build setting key from all child XCBuildConfiguration
objects\&.

.fi
.PP
 
.PP
Definition at line \fB1791\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.GetBuildSetting ( self,  key)"

.PP
.nf
Gets the build setting for key\&.

All child XCConfiguration objects must have the same value set for the
setting, or a ValueError will be raised\&.

.fi
.PP
 
.PP
Definition at line \fB1754\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.HasBuildSetting ( self,  key)"

.PP
.nf
Determines the state of a build setting in all XCBuildConfiguration
child objects\&.

If all child objects have key in their build settings, and the value is the
same in all child objects, returns 1\&.

If no child objects have the key in their build settings, returns 0\&.

If some, but not all, child objects have the key in their build settings,
or if any children have different values for the key, returns -1\&.

.fi
.PP
 
.PP
Definition at line \fB1720\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.Name ( self)"

.PP
.nf
Return the name corresponding to an object\&.

Not all objects necessarily need to be nameable, and not all that do have
a 'name' property\&.  Override as needed\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB1699\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.SetBaseConfiguration ( self,  value)"

.PP
.nf
Sets the build configuration in all child XCBuildConfiguration objects\&.

.fi
.PP
 
.PP
Definition at line \fB1799\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&.SetBuildSetting ( self,  key,  value)"

.PP
.nf
Sets the build setting for key to value in all child
XCBuildConfiguration objects\&.

.fi
.PP
 
.PP
Definition at line \fB1775\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "list gyp\&.xcodeproj_file\&.XCConfigurationList\&._configs\fR [static]\fP, \fR [protected]\fP"
\fBInitial value:\fP
.nf
=  [
        XCBuildConfiguration({"name": "Debug"}),
        XCBuildConfiguration({"name": "Release"}),
    ]
.PP
.fi

.PP
Definition at line \fB1685\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCConfigurationList\&._schema = XCObject\&._schema\&.copy()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB1690\fP of file \fBxcodeproj_file\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
