.TH "gyp.MSVSNew.MSVSSolution" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSNew.MSVSSolution
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBpath\fP, \fBversion\fP, \fBentries\fP=None, \fBvariants\fP=None, \fBwebsiteProperties\fP=True)"
.br
.ti -1c
.RI "\fBWrite\fP (self, writer=\fBgyp\&.common\&.WriteOnDiff\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBwebsiteProperties\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBentries\fP"
.br
.ti -1c
.RI "\fBvariants\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Visual Studio solution\&.
.fi
.PP
 
.PP
Definition at line \fB190\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSSolution\&.__init__ ( self,  path,  version,  entries = \fRNone\fP,  variants = \fRNone\fP,  websiteProperties = \fRTrue\fP)"

.PP
.nf
Initializes the solution\&.

Args:
path: Path to solution file\&.
version: Format version to emit\&.
entries: List of entries in solution\&.  May contain Folder or Project
  objects\&.  May be None, if the folder is empty\&.
variants: List of build variant strings\&.  If none, a default list will
  be used\&.
websiteProperties: Flag to decide if the website properties section
  is generated\&.

.fi
.PP
 
.PP
Definition at line \fB193\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSSolution\&.Write ( self,  writer = \fR\fBgyp\&.common\&.WriteOnDiff\fP\fP)"

.PP
.nf
Writes the solution file to disk\&.

Raises:
IndexError: An entry appears multiple times\&.

.fi
.PP
 
.PP
Definition at line \fB230\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSSolution\&.entries"

.PP
Definition at line \fB213\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSSolution\&.path"

.PP
Definition at line \fB208\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSSolution\&.variants"

.PP
Definition at line \fB217\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSSolution\&.version"

.PP
Definition at line \fB210\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSSolution\&.websiteProperties"

.PP
Definition at line \fB209\fP of file \fBMSVSNew\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
