.TH "gyp.MSVSToolFile" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSToolFile
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Visual Studio project reader/writer\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
