.TH "gyp.generator.ninja.NinjaWriter" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.ninja.NinjaWriter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBhash_for_rules\fP, \fBtarget_outputs\fP, \fBbase_dir\fP, \fBbuild_dir\fP, output_file, \fBtoplevel_build\fP, \fBoutput_file_name\fP, \fBflavor\fP, toplevel_dir=None)"
.br
.ti -1c
.RI "\fBExpandSpecial\fP (self, path, product_dir=None)"
.br
.ti -1c
.RI "\fBExpandRuleVariables\fP (self, path, root, dirname, source, ext, \fBname\fP)"
.br
.ti -1c
.RI "\fBGypPathToNinja\fP (self, path, env=None)"
.br
.ti -1c
.RI "\fBGypPathToUniqueOutput\fP (self, path, qualified=True)"
.br
.ti -1c
.RI "\fBWriteCollapsedDependencies\fP (self, \fBname\fP, targets, order_only=None)"
.br
.ti -1c
.RI "\fBWriteSpec\fP (self, spec, \fBconfig_name\fP, generator_flags)"
.br
.ti -1c
.RI "\fBWriteWinIdlFiles\fP (self, spec, prebuild)"
.br
.ti -1c
.RI "\fBWriteActionsRulesCopies\fP (self, spec, extra_sources, prebuild, mac_bundle_depends)"
.br
.ti -1c
.RI "\fBGenerateDescription\fP (self, verb, message, fallback)"
.br
.ti -1c
.RI "\fBWriteActions\fP (self, actions, extra_sources, prebuild, extra_mac_bundle_resources)"
.br
.ti -1c
.RI "\fBWriteRules\fP (self, rules, extra_sources, prebuild, mac_bundle_resources, extra_mac_bundle_resources)"
.br
.ti -1c
.RI "\fBWriteCopies\fP (self, copies, prebuild, mac_bundle_depends)"
.br
.ti -1c
.RI "\fBWriteiOSFrameworkHeaders\fP (self, spec, outputs, prebuild)"
.br
.ti -1c
.RI "\fBWriteMacBundleResources\fP (self, resources, bundle_depends)"
.br
.ti -1c
.RI "\fBWriteMacXCassets\fP (self, xcassets, bundle_depends)"
.br
.ti -1c
.RI "\fBWriteMacInfoPlist\fP (self, partial_info_plist, bundle_depends)"
.br
.ti -1c
.RI "\fBWriteSources\fP (self, ninja_file, \fBconfig_name\fP, config, sources, predepends, precompiled_header, spec)"
.br
.ti -1c
.RI "\fBWriteSourcesForArch\fP (self, ninja_file, \fBconfig_name\fP, config, sources, predepends, precompiled_header, spec, arch=None)"
.br
.ti -1c
.RI "\fBWritePchTargets\fP (self, ninja_file, pch_commands)"
.br
.ti -1c
.RI "\fBWriteLink\fP (self, spec, \fBconfig_name\fP, config, link_deps, compile_deps)"
.br
.ti -1c
.RI "\fBWriteLinkForArch\fP (self, ninja_file, spec, \fBconfig_name\fP, config, link_deps, compile_deps, arch=None)"
.br
.ti -1c
.RI "\fBWriteTarget\fP (self, spec, \fBconfig_name\fP, config, link_deps, compile_deps)"
.br
.ti -1c
.RI "\fBWriteMacBundle\fP (self, spec, mac_bundle_depends, is_empty)"
.br
.ti -1c
.RI "\fBGetToolchainEnv\fP (self, additional_settings=None)"
.br
.ti -1c
.RI "\fBGetMsvsToolchainEnv\fP (self, additional_settings=None)"
.br
.ti -1c
.RI "\fBGetSortedXcodeEnv\fP (self, additional_settings=None)"
.br
.ti -1c
.RI "\fBGetSortedXcodePostbuildEnv\fP (self)"
.br
.ti -1c
.RI "\fBAppendPostbuildVariable\fP (self, variables, spec, output, binary, is_command_start=False)"
.br
.ti -1c
.RI "\fBGetPostbuildCommand\fP (self, spec, output, output_binary, is_command_start)"
.br
.ti -1c
.RI "\fBComputeExportEnvString\fP (self, env)"
.br
.ti -1c
.RI "\fBComputeMacBundleOutput\fP (self)"
.br
.ti -1c
.RI "\fBComputeOutputFileName\fP (self, spec, type=None)"
.br
.ti -1c
.RI "\fBComputeOutput\fP (self, spec, arch=None)"
.br
.ti -1c
.RI "\fBWriteVariableList\fP (self, ninja_file, var, values)"
.br
.ti -1c
.RI "\fBWriteNewNinjaRule\fP (self, \fBname\fP, args, description, win_shell_flags, env, pool, depfile=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhash_for_rules\fP"
.br
.ti -1c
.RI "\fBtarget_outputs\fP"
.br
.ti -1c
.RI "\fBbase_dir\fP"
.br
.ti -1c
.RI "\fBbuild_dir\fP"
.br
.ti -1c
.RI "\fBninja\fP"
.br
.ti -1c
.RI "\fBtoplevel_build\fP"
.br
.ti -1c
.RI "\fBoutput_file_name\fP"
.br
.ti -1c
.RI "\fBflavor\fP"
.br
.ti -1c
.RI "\fBabs_build_dir\fP"
.br
.ti -1c
.RI "\fBobj_ext\fP"
.br
.ti -1c
.RI "\fBwin_env\fP"
.br
.ti -1c
.RI "\fBbuild_to_base\fP"
.br
.ti -1c
.RI "\fBbase_to_build\fP"
.br
.ti -1c
.RI "\fBconfig_name\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBtoolset\fP"
.br
.ti -1c
.RI "\fBtarget\fP"
.br
.ti -1c
.RI "\fBis_standalone_static_library\fP"
.br
.ti -1c
.RI "\fBtarget_rpath\fP"
.br
.ti -1c
.RI "\fBis_mac_bundle\fP"
.br
.ti -1c
.RI "\fBxcode_settings\fP"
.br
.ti -1c
.RI "\fBmsvs_settings\fP"
.br
.ti -1c
.RI "\fBarchs\fP"
.br
.ti -1c
.RI "\fBarch_subninjas\fP"
.br
.ti -1c
.RI "\fBGypPathToNinja\fP"
.br
.ti -1c
.RI "\fBGypPathToUniqueOutput\fP"
.br
.ti -1c
.RI "\fBExpandSpecial\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_SubninjaNameForArch\fP (self, arch)"
.br
.ti -1c
.RI "\fB_WinIdlRule\fP (self, source, prebuild, outputs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB213\fP of file \fBninja\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.__init__ ( self,  hash_for_rules,  target_outputs,  base_dir,  build_dir,  output_file,  toplevel_build,  output_file_name,  flavor,  toplevel_dir = \fRNone\fP)"

.PP
.nf
base_dir: path from source root to directory containing this gyp file,
          by gyp semantics, all input paths are relative to this
build_dir: path from source root to build output
toplevel_dir: path to the toplevel directory

.fi
.PP
 
.PP
Definition at line \fB214\fP of file \fBninja\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&._SubninjaNameForArch ( self,  arch)\fR [protected]\fP"

.PP
Definition at line \fB374\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&._WinIdlRule ( self,  source,  prebuild,  outputs)\fR [protected]\fP"

.PP
.nf
Handle the implicit VS \&.idl rule for one source file\&. Fills |outputs|
with files that are generated\&.
.fi
.PP
 
.PP
Definition at line \fB552\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.AppendPostbuildVariable ( self,  variables,  spec,  output,  binary,  is_command_start = \fRFalse\fP)"

.PP
.nf
Adds a 'postbuild' variable if there is a postbuild for |output|\&.
.fi
.PP
 
.PP
Definition at line \fB1716\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.ComputeExportEnvString ( self,  env)"

.PP
.nf
Given an environment, returns a string looking like
    'export FOO=foo; export BAR='${FOO} bar;'
that exports |env| to the shell\&.
.fi
.PP
 
.PP
Definition at line \fB1771\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.ComputeMacBundleOutput ( self)"

.PP
.nf
Return the 'output' (full output path) to a bundle output directory\&.
.fi
.PP
 
.PP
Definition at line \fB1783\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.ComputeOutput ( self,  spec,  arch = \fRNone\fP)"

.PP
.nf
Compute the path for the final output of the spec\&.
.fi
.PP
 
.PP
Definition at line \fB1845\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.ComputeOutputFileName ( self,  spec,  type = \fRNone\fP)"

.PP
.nf
Compute the filename of the final output for the current target\&.
.fi
.PP
 
.PP
Definition at line \fB1791\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.ExpandRuleVariables ( self,  path,  root,  dirname,  source,  ext,  name)"

.PP
Definition at line \fB290\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.ExpandSpecial ( self,  path,  product_dir = \fRNone\fP)"

.PP
.nf
Expand specials like $!PRODUCT_DIR in |path|\&.

If |product_dir| is None, assumes the cwd is already the product
dir\&.  Otherwise, |product_dir| is the relative path to the product
dir\&.

.fi
.PP
 
.PP
Definition at line \fB259\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GenerateDescription ( self,  verb,  message,  fallback)"

.PP
.nf
Generate and return a description of a build step\&.

|verb| is the short summary, e\&.g\&. ACTION or RULE\&.
|message| is a hand-written description, or None if not available\&.
|fallback| is the gyp-level name of the step, usable as a fallback\&.

.fi
.PP
 
.PP
Definition at line \fB631\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GetMsvsToolchainEnv ( self,  additional_settings = \fRNone\fP)"

.PP
.nf
Returns the variables Visual Studio would set for build steps\&.
.fi
.PP
 
.PP
Definition at line \fB1686\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GetPostbuildCommand ( self,  spec,  output,  output_binary,  is_command_start)"

.PP
.nf
Returns a shell command that runs all the postbuilds, and removes
|output| if any of them fails\&. If |is_command_start| is False, then the
returned string will start with ' && '\&.
.fi
.PP
 
.PP
Definition at line \fB1724\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GetSortedXcodeEnv ( self,  additional_settings = \fRNone\fP)"

.PP
.nf
Returns the variables Xcode would set for build steps\&.
.fi
.PP
 
.PP
Definition at line \fB1692\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GetSortedXcodePostbuildEnv ( self)"

.PP
.nf
Returns the variables Xcode would set for postbuild steps\&.
.fi
.PP
 
.PP
Definition at line \fB1704\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GetToolchainEnv ( self,  additional_settings = \fRNone\fP)"

.PP
.nf
Returns the variables toolchain would set for build steps\&.
.fi
.PP
 
.PP
Definition at line \fB1679\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GypPathToNinja ( self,  path,  env = \fRNone\fP)"

.PP
.nf
Translate a gyp path to a ninja path, optionally expanding environment
variable references in |path| with |env|\&.

See the above discourse on path conversions\&.
.fi
.PP
 
.PP
Definition at line \fB300\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GypPathToUniqueOutput ( self,  path,  qualified = \fRTrue\fP)"

.PP
.nf
Translate a gyp path to a ninja path for writing output\&.

If qualified is True, qualify the resulting filename with the name
of the target\&.  This is necessary when e\&.g\&. compiling the same
path twice for two separate output targets\&.

See the above discourse on path conversions\&.
.fi
.PP
 
.PP
Definition at line \fB320\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteActions ( self,  actions,  extra_sources,  prebuild,  extra_mac_bundle_resources)"

.PP
Definition at line \fB645\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteActionsRulesCopies ( self,  spec,  extra_sources,  prebuild,  mac_bundle_depends)"

.PP
.nf
Write out the Actions, Rules, and Copies steps\&.  Return a path
representing the outputs of these steps\&.
.fi
.PP
 
.PP
Definition at line \fB587\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteCollapsedDependencies ( self,  name,  targets,  order_only = \fRNone\fP)"

.PP
.nf
Given a list of targets, return a path for a single file
representing the result of building all the targets or None\&.

Uses a stamp file if necessary\&.
.fi
.PP
 
.PP
Definition at line \fB358\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteCopies ( self,  copies,  prebuild,  mac_bundle_depends)"

.PP
Definition at line \fB831\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteiOSFrameworkHeaders ( self,  spec,  outputs,  prebuild)"

.PP
.nf
Prebuild steps to generate hmap files and copy headers to destination\&.
.fi
.PP
 
.PP
Definition at line \fB863\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteLink ( self,  spec,  config_name,  config,  link_deps,  compile_deps)"

.PP
.nf
Write out a link step\&. Fills out target\&.binary\&. 
.fi
.PP
 
.PP
Definition at line \fB1307\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteLinkForArch ( self,  ninja_file,  spec,  config_name,  config,  link_deps,  compile_deps,  arch = \fRNone\fP)"

.PP
.nf
Write out a link step\&. Fills out target\&.binary\&. 
.fi
.PP
 
.PP
Definition at line \fB1349\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteMacBundle ( self,  spec,  mac_bundle_depends,  is_empty)"

.PP
Definition at line \fB1647\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteMacBundleResources ( self,  resources,  bundle_depends)"

.PP
.nf
Writes ninja edges for 'mac_bundle_resources'\&.
.fi
.PP
 
.PP
Definition at line \fB887\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteMacInfoPlist ( self,  partial_info_plist,  bundle_depends)"

.PP
.nf
Write build rules for bundle Info\&.plist files\&.
.fi
.PP
 
.PP
Definition at line \fB969\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteMacXCassets ( self,  xcassets,  bundle_depends)"

.PP
.nf
Writes ninja edges for 'mac_bundle_resources' \&.xcassets files\&.

This add an invocation of 'actool' via the 'mac_tool\&.py' helper script\&.
It assumes that the assets catalogs define at least one imageset and
thus an Assets\&.car file will be generated in the application resources
directory\&. If this is not the case, then the build will probably be done
at each invocation of ninja\&.
.fi
.PP
 
.PP
Definition at line \fB918\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteNewNinjaRule ( self,  name,  args,  description,  win_shell_flags,  env,  pool,  depfile = \fRNone\fP)"

.PP
.nf
Write out a new ninja 'rule' statement for a given command\&.

Returns the name of the new rule, and a copy of |args| with variables
expanded\&.
.fi
.PP
 
.PP
Definition at line \fB1901\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WritePchTargets ( self,  ninja_file,  pch_commands)"

.PP
.nf
Writes ninja rules to compile prefix headers\&.
.fi
.PP
 
.PP
Definition at line \fB1285\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteRules ( self,  rules,  extra_sources,  prebuild,  mac_bundle_resources,  extra_mac_bundle_resources)"

.PP
Definition at line \fB686\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteSources ( self,  ninja_file,  config_name,  config,  sources,  predepends,  precompiled_header,  spec)"

.PP
.nf
Write build rules to compile all of |sources|\&.
.fi
.PP
 
.PP
Definition at line \fB1012\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteSourcesForArch ( self,  ninja_file,  config_name,  config,  sources,  predepends,  precompiled_header,  spec,  arch = \fRNone\fP)"

.PP
.nf
Write build rules to compile all of |sources|\&.
.fi
.PP
 
.PP
Definition at line \fB1057\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteSpec ( self,  spec,  config_name,  generator_flags)"

.PP
.nf
The main entry point for NinjaWriter: write the build rules for a spec\&.

Returns a Target object, which represents the output paths for this spec\&.
Returns None if there are no outputs (e\&.g\&. a settings-only 'none' type
target)\&.
.fi
.PP
 
.PP
Definition at line \fB378\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteTarget ( self,  spec,  config_name,  config,  link_deps,  compile_deps)"

.PP
Definition at line \fB1572\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteVariableList ( self,  ninja_file,  var,  values)"

.PP
Definition at line \fB1895\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.WriteWinIdlFiles ( self,  spec,  prebuild)"

.PP
.nf
Writes rules to match MSVS's implicit idl handling\&.
.fi
.PP
 
.PP
Definition at line \fB577\fP of file \fBninja\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.abs_build_dir"

.PP
Definition at line \fB242\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.arch_subninjas"

.PP
Definition at line \fB417\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.archs"

.PP
Definition at line \fB415\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.base_dir"

.PP
Definition at line \fB235\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.base_to_build"

.PP
Definition at line \fB257\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.build_dir"

.PP
Definition at line \fB236\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.build_to_base"

.PP
Definition at line \fB254\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.config_name"

.PP
Definition at line \fB385\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.ExpandSpecial"

.PP
Definition at line \fB1135\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.flavor"

.PP
Definition at line \fB241\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GypPathToNinja"

.PP
Definition at line \fB495\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.GypPathToUniqueOutput"

.PP
Definition at line \fB496\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.hash_for_rules"

.PP
Definition at line \fB233\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.is_mac_bundle"

.PP
Definition at line \fB396\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.is_standalone_static_library"

.PP
Definition at line \fB390\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.msvs_settings"

.PP
Definition at line \fB405\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.name"

.PP
Definition at line \fB386\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.ninja"

.PP
Definition at line \fB237\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.obj_ext"

.PP
Definition at line \fB245\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.output_file_name"

.PP
Definition at line \fB239\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.target"

.PP
Definition at line \fB389\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.target_outputs"

.PP
Definition at line \fB234\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.target_rpath"

.PP
Definition at line \fB394\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.toolset"

.PP
Definition at line \fB387\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.toplevel_build"

.PP
Definition at line \fB238\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.win_env"

.PP
Definition at line \fB248\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.NinjaWriter\&.xcode_settings"

.PP
Definition at line \fB397\fP of file \fBninja\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
