.TH "gyp.common.OrderedSet" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.common.OrderedSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits MutableSet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, iterable=None)"
.br
.ti -1c
.RI "\fB__len__\fP (self)"
.br
.ti -1c
.RI "\fB__contains__\fP (self, key)"
.br
.ti -1c
.RI "\fBadd\fP (self, key)"
.br
.ti -1c
.RI "\fBdiscard\fP (self, key)"
.br
.ti -1c
.RI "\fB__iter__\fP (self)"
.br
.ti -1c
.RI "\fB__reversed__\fP (self)"
.br
.ti -1c
.RI "\fBpop\fP (self, last=True)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fB__eq__\fP (self, other)"
.br
.ti -1c
.RI "\fBupdate\fP (self, iterable)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBend\fP"
.br
.ti -1c
.RI "\fBmap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB514\fP of file \fBcommon\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.common\&.OrderedSet\&.__init__ ( self,  iterable = \fRNone\fP)"

.PP
Definition at line \fB515\fP of file \fBcommon\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.common\&.OrderedSet\&.__contains__ ( self,  key)"

.PP
Definition at line \fB525\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.__eq__ ( self,  other)"

.PP
Definition at line \fB567\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.__iter__ ( self)"

.PP
Definition at line \fB540\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.__len__ ( self)"

.PP
Definition at line \fB522\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.__repr__ ( self)"

.PP
Definition at line \fB562\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.__reversed__ ( self)"

.PP
Definition at line \fB547\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.add ( self,  key)"

.PP
Definition at line \fB528\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.discard ( self,  key)"

.PP
Definition at line \fB534\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.pop ( self,  last = \fRTrue\fP)"

.PP
Definition at line \fB555\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.update ( self,  iterable)"

.PP
Definition at line \fB573\fP of file \fBcommon\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.common\&.OrderedSet\&.end"

.PP
Definition at line \fB516\fP of file \fBcommon\&.py\fP\&.
.SS "gyp\&.common\&.OrderedSet\&.map"

.PP
Definition at line \fB518\fP of file \fBcommon\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
