.TH "gyp.MSVSSettings._Type" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSSettings._Type
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgyp\&.MSVSSettings\&._Boolean\fP, \fBgyp\&.MSVSSettings\&._Enumeration\fP, \fBgyp\&.MSVSSettings\&._Integer\fP, \fBgyp\&.MSVSSettings\&._String\fP, and \fBgyp\&.MSVSSettings\&._StringList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidateMSVS\fP (self, value)"
.br
.ti -1c
.RI "\fBValidateMSBuild\fP (self, value)"
.br
.ti -1c
.RI "\fBConvertToMSBuild\fP (self, value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Type of settings (Base class)\&.
.fi
.PP
 
.PP
Definition at line \fB67\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Type\&.ConvertToMSBuild ( self,  value)"

.PP
.nf
Returns the MSBuild equivalent of the MSVS value given\&.

Args:
value: the MSVS value to convert\&.

Returns:
the MSBuild equivalent\&.

Raises:
ValueError if value is not valid\&.

.fi
.PP
 
.PP
Reimplemented in \fBgyp\&.MSVSSettings\&._Boolean\fP, \fBgyp\&.MSVSSettings\&._Enumeration\fP, \fBgyp\&.MSVSSettings\&._Integer\fP, \fBgyp\&.MSVSSettings\&._String\fP, and \fBgyp\&.MSVSSettings\&._StringList\fP\&.
.PP
Definition at line \fB90\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._Type\&.ValidateMSBuild ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSBuild\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSBuild\&.

.fi
.PP
 
.PP
Reimplemented in \fBgyp\&.MSVSSettings\&._Boolean\fP, \fBgyp\&.MSVSSettings\&._Enumeration\fP, \fBgyp\&.MSVSSettings\&._Integer\fP, \fBgyp\&.MSVSSettings\&._String\fP, and \fBgyp\&.MSVSSettings\&._StringList\fP\&.
.PP
Definition at line \fB80\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._Type\&.ValidateMSVS ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSVS\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSVS\&.

.fi
.PP
 
.PP
Reimplemented in \fBgyp\&.MSVSSettings\&._Boolean\fP, \fBgyp\&.MSVSSettings\&._Enumeration\fP, \fBgyp\&.MSVSSettings\&._Integer\fP, \fBgyp\&.MSVSSettings\&._String\fP, and \fBgyp\&.MSVSSettings\&._StringList\fP\&.
.PP
Definition at line \fB70\fP of file \fBMSVSSettings\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
