.TH "gyp.common_test.TestTopologicallySorted" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.common_test.TestTopologicallySorted
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_Valid\fP (self)"
.br
.ti -1c
.RI "\fBtest_Cycle\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBcommon_test\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.common_test\&.TestTopologicallySorted\&.test_Cycle ( self)"

.PP
.nf
Test that an exception is thrown on a cyclic graph\&.
.fi
.PP
 
.PP
Definition at line \fB31\fP of file \fBcommon_test\&.py\fP\&.
.SS "gyp\&.common_test\&.TestTopologicallySorted\&.test_Valid ( self)"

.PP
.nf
Test that sorting works on a valid graph with one possible order\&.
.fi
.PP
 
.PP
Definition at line \fB15\fP of file \fBcommon_test\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
