.TH "gyp.simple_copy.Error" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.simple_copy.Error
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBsimple_copy\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
