.TH "gyp.ninja_syntax" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.ninja_syntax
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWriter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBescape_path\fP (word)"
.br
.ti -1c
.RI "\fBescape\fP (string)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Python module for generating \&.ninja files\&.

Note that this is emphatically not a required piece of Ninja; it's
just a helpful utility for build-file-generation systems that already
use Python\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "gyp\&.ninja_syntax\&.escape ( string)"

.PP
.nf
Escape a string such that it can be embedded into a Ninja file without
further interpretation\&.
.fi
.PP
 
.PP
Definition at line \fB169\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.escape_path ( word)"

.PP
Definition at line \fB15\fP of file \fBninja_syntax\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
