.TH "gyp.common_test.TestGetFlavor" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.common_test.TestGetFlavor
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP (self)"
.br
.ti -1c
.RI "\fBtearDown\fP (self)"
.br
.ti -1c
.RI "\fBassertFlavor\fP (self, expected, argument, param)"
.br
.ti -1c
.RI "\fBtest_platform_default\fP (self)"
.br
.ti -1c
.RI "\fBtest_param\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBoriginal_platform\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Test that gyp\&.common\&.GetFlavor works as intended
.fi
.PP
 
.PP
Definition at line \fB48\fP of file \fBcommon_test\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.common_test\&.TestGetFlavor\&.assertFlavor ( self,  expected,  argument,  param)"

.PP
Definition at line \fB59\fP of file \fBcommon_test\&.py\fP\&.
.SS "gyp\&.common_test\&.TestGetFlavor\&.setUp ( self)"

.PP
Definition at line \fB53\fP of file \fBcommon_test\&.py\fP\&.
.SS "gyp\&.common_test\&.TestGetFlavor\&.tearDown ( self)"

.PP
Definition at line \fB56\fP of file \fBcommon_test\&.py\fP\&.
.SS "gyp\&.common_test\&.TestGetFlavor\&.test_param ( self)"

.PP
Definition at line \fB73\fP of file \fBcommon_test\&.py\fP\&.
.SS "gyp\&.common_test\&.TestGetFlavor\&.test_platform_default ( self)"

.PP
Definition at line \fB63\fP of file \fBcommon_test\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str gyp\&.common_test\&.TestGetFlavor\&.original_platform = ''\fR [static]\fP"

.PP
Definition at line \fB51\fP of file \fBcommon_test\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
