.TH "gyp.msvs_emulation.MsvsSettings._GetWrapper" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.msvs_emulation.MsvsSettings._GetWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBparent\fP, \fBfield\fP, \fBbase_path\fP, \fBappend\fP=None)"
.br
.ti -1c
.RI "\fB__call__\fP (self, name, map=None, prefix='', default=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparent\fP"
.br
.ti -1c
.RI "\fBfield\fP"
.br
.ti -1c
.RI "\fBbase_path\fP"
.br
.ti -1c
.RI "\fBappend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB311\fP of file \fBmsvs_emulation\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.msvs_emulation\&.MsvsSettings\&._GetWrapper\&.__init__ ( self,  parent,  field,  base_path,  append = \fRNone\fP)"

.PP
Definition at line \fB312\fP of file \fBmsvs_emulation\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.msvs_emulation\&.MsvsSettings\&._GetWrapper\&.__call__ ( self,  name,  map = \fRNone\fP,  prefix = \fR''\fP,  default = \fRNone\fP)"

.PP
Definition at line \fB318\fP of file \fBmsvs_emulation\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.msvs_emulation\&.MsvsSettings\&._GetWrapper\&.append"

.PP
Definition at line \fB316\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.MsvsSettings\&._GetWrapper\&.base_path"

.PP
Definition at line \fB315\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.MsvsSettings\&._GetWrapper\&.field"

.PP
Definition at line \fB314\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.MsvsSettings\&._GetWrapper\&.parent"

.PP
Definition at line \fB313\fP of file \fBmsvs_emulation\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
