.TH "gyp.msvs_emulation.PrecompiledHeader" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.msvs_emulation.PrecompiledHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBsettings\fP, \fBconfig\fP, gyp_to_build_path, gyp_to_unique_output, obj_ext)"
.br
.ti -1c
.RI "\fBGetObjDependencies\fP (self, sources, objs, arch)"
.br
.ti -1c
.RI "\fBGetPchBuildCommands\fP (self, arch)"
.br
.ti -1c
.RI "\fBGetFlagsModifications\fP (self, input, output, implicit, command, cflags_c, cflags_cc, expand_special)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsettings\fP"
.br
.ti -1c
.RI "\fBconfig\fP"
.br
.ti -1c
.RI "\fBpch_source\fP"
.br
.ti -1c
.RI "\fBoutput_obj\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_PchHeader\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Helper to generate dependencies and build rules to handle generation of
precompiled headers\&. Interface matches the GCH handler in xcode_emulation\&.py\&.

.fi
.PP
 
.PP
Definition at line \fB1027\fP of file \fBmsvs_emulation\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&.__init__ ( self,  settings,  config,  gyp_to_build_path,  gyp_to_unique_output,  obj_ext)"

.PP
Definition at line \fB1032\fP of file \fBmsvs_emulation\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&._PchHeader ( self)\fR [protected]\fP"

.PP
.nf
Get the header that will appear in an #include line for all source
files\&.
.fi
.PP
 
.PP
Definition at line \fB1042\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&.GetFlagsModifications ( self,  input,  output,  implicit,  command,  cflags_c,  cflags_cc,  expand_special)"

.PP
.nf
Get the modified cflags and implicit dependencies that should be used
for the pch compilation step\&.
.fi
.PP
 
.PP
Definition at line \fB1066\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&.GetObjDependencies ( self,  sources,  objs,  arch)"

.PP
.nf
Given a list of sources files and the corresponding object files,
returns a list of the pch files that should be depended upon\&. The
additional wrapping in the return value is for interface compatibility
with make\&.py on Mac, and xcode_emulation\&.py\&.
.fi
.PP
 
.PP
Definition at line \fB1047\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&.GetPchBuildCommands ( self,  arch)"

.PP
.nf
Not used on Windows as there are no additional build steps required
(instead, existing steps are modified in GetFlagsModifications below)\&.
.fi
.PP
 
.PP
Definition at line \fB1061\fP of file \fBmsvs_emulation\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&.config"

.PP
Definition at line \fB1036\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&.output_obj"

.PP
Definition at line \fB1040\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&.pch_source"

.PP
Definition at line \fB1038\fP of file \fBmsvs_emulation\&.py\fP\&.
.SS "gyp\&.msvs_emulation\&.PrecompiledHeader\&.settings"

.PP
Definition at line \fB1035\fP of file \fBmsvs_emulation\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
