.TH "gyp.MSVSNew.MSVSProject" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSNew.MSVSProject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.MSVSNew\&.MSVSSolutionEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBpath\fP, \fBname\fP=None, \fBdependencies\fP=None, \fBguid\fP=None, \fBspec\fP=None, \fBbuild_file\fP=None, \fBconfig_platform_overrides\fP=None, \fBfixpath_prefix\fP=None)"
.br
.ti -1c
.RI "\fBset_dependencies\fP (self, \fBdependencies\fP)"
.br
.ti -1c
.RI "\fBget_guid\fP (self)"
.br
.ti -1c
.RI "\fBset_msbuild_toolset\fP (self, \fBmsbuild_toolset\fP)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.MSVSNew\&.MSVSSolutionEntry\fP
.in +1c
.ti -1c
.RI "\fB__cmp__\fP (self, other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBguid\fP"
.br
.ti -1c
.RI "\fBspec\fP"
.br
.ti -1c
.RI "\fBbuild_file\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBdependencies\fP"
.br
.ti -1c
.RI "\fBentry_type_guid\fP"
.br
.ti -1c
.RI "\fBconfig_platform_overrides\fP"
.br
.ti -1c
.RI "\fBfixpath_prefix\fP"
.br
.ti -1c
.RI "\fBmsbuild_toolset\fP"
.br
.in -1c

Public Attributes inherited from \fBgyp\&.MSVSNew\&.MSVSSolutionEntry\fP
.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Visual Studio project\&.
.fi
.PP
 
.PP
Definition at line \fB115\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSProject\&.__init__ ( self,  path,  name = \fRNone\fP,  dependencies = \fRNone\fP,  guid = \fRNone\fP,  spec = \fRNone\fP,  build_file = \fRNone\fP,  config_platform_overrides = \fRNone\fP,  fixpath_prefix = \fRNone\fP)"

.PP
.nf
Initializes the project\&.

Args:
path: Absolute path to the project file\&.
name: Name of project\&.  If None, the name will be the same as the base
  name of the project file\&.
dependencies: List of other Project objects this project is dependent
  upon, if not None\&.
guid: GUID to use for project, if not None\&.
spec: Dictionary specifying how to build this project\&.
build_file: Filename of the \&.gyp file that the vcproj file comes from\&.
config_platform_overrides: optional dict of configuration platforms to
  used in place of the default for this target\&.
fixpath_prefix: the path used to adjust the behavior of _fixpath

.fi
.PP
 
.PP
Definition at line \fB118\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSProject\&.get_guid ( self)"

.PP
Definition at line \fB166\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.set_dependencies ( self,  dependencies)"

.PP
Definition at line \fB163\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.set_msbuild_toolset ( self,  msbuild_toolset)"

.PP
Definition at line \fB183\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSProject\&.build_file"

.PP
Definition at line \fB147\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.config_platform_overrides"

.PP
Definition at line \fB157\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.dependencies"

.PP
Definition at line \fB152\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.entry_type_guid"

.PP
Definition at line \fB154\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.fixpath_prefix"

.PP
Definition at line \fB160\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.guid"

.PP
Definition at line \fB145\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.msbuild_toolset"

.PP
Definition at line \fB161\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.name"

.PP
Definition at line \fB149\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.path"

.PP
Definition at line \fB144\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSProject\&.spec"

.PP
Definition at line \fB146\fP of file \fBMSVSNew\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
