.TH "gyp.generator.msvs.MSBuildRule" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.msvs.MSBuildRule
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, rule, spec)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdisplay_name\fP"
.br
.ti -1c
.RI "\fBrule_name\fP"
.br
.ti -1c
.RI "\fBtarget_name\fP"
.br
.ti -1c
.RI "\fBafter_targets\fP"
.br
.ti -1c
.RI "\fBbefore_targets\fP"
.br
.ti -1c
.RI "\fBdepends_on\fP"
.br
.ti -1c
.RI "\fBcompute_output\fP"
.br
.ti -1c
.RI "\fBdirs_to_make\fP"
.br
.ti -1c
.RI "\fBinputs\fP"
.br
.ti -1c
.RI "\fBtlog\fP"
.br
.ti -1c
.RI "\fBextension\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBadditional_dependencies\fP"
.br
.ti -1c
.RI "\fBoutputs\fP"
.br
.ti -1c
.RI "\fBcommand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Used to store information used to generate an MSBuild rule\&.

Attributes:
rule_name: The rule name, sanitized to use in XML\&.
target_name: The name of the target\&.
after_targets: The name of the AfterTargets element\&.
before_targets: The name of the BeforeTargets element\&.
depends_on: The name of the DependsOn element\&.
compute_output: The name of the ComputeOutput element\&.
dirs_to_make: The name of the DirsToMake element\&.
inputs: The name of the _inputs element\&.
tlog: The name of the _tlog element\&.
extension: The extension this rule applies to\&.
description: The message displayed when this rule is invoked\&.
additional_dependencies: A string listing additional dependencies\&.
outputs: The outputs of this rule\&.
command: The command used to run the rule\&.

.fi
.PP
 
.PP
Definition at line \fB2379\fP of file \fBmsvs\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.__init__ ( self,  rule,  spec)"

.PP
Definition at line \fB2399\fP of file \fBmsvs\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.additional_dependencies"

.PP
Definition at line \fB2422\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.after_targets"

.PP
Definition at line \fB2407\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.before_targets"

.PP
Definition at line \fB2408\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.command"

.PP
Definition at line \fB2435\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.compute_output"

.PP
Definition at line \fB2410\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.depends_on"

.PP
Definition at line \fB2409\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.description"

.PP
Definition at line \fB2418\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.dirs_to_make"

.PP
Definition at line \fB2411\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.display_name"

.PP
Definition at line \fB2400\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.extension"

.PP
Definition at line \fB2414\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.inputs"

.PP
Definition at line \fB2412\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.outputs"

.PP
Definition at line \fB2429\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.rule_name"

.PP
Definition at line \fB2402\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.target_name"

.PP
Definition at line \fB2406\fP of file \fBmsvs\&.py\fP\&.
.SS "gyp\&.generator\&.msvs\&.MSBuildRule\&.tlog"

.PP
Definition at line \fB2413\fP of file \fBmsvs\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
