.TH "gyp.MSVSSettings._Enumeration" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSSettings._Enumeration
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.MSVSSettings\&._Type\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, label_list, new=None)"
.br
.ti -1c
.RI "\fBValidateMSVS\fP (self, value)"
.br
.ti -1c
.RI "\fBValidateMSBuild\fP (self, value)"
.br
.ti -1c
.RI "\fBConvertToMSBuild\fP (self, value)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_label_list\fP"
.br
.ti -1c
.RI "\fB_msbuild_values\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Type of settings that is an enumeration\&.

In MSVS, the values are indexes like '0', '1', and '2'\&.
MSBuild uses text labels that are more representative, like 'Win32'\&.

Constructor args:
label_list: an array of MSBuild labels that correspond to the MSVS index\&.
    In the rare cases where MSVS has skipped an index value, None is
    used in the array to indicate the unused spot\&.
new: an array of labels that are new to MSBuild\&.

.fi
.PP
 
.PP
Definition at line \fB178\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Enumeration\&.__init__ ( self,  label_list,  new = \fRNone\fP)"

.PP
Definition at line \fB191\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Enumeration\&.ConvertToMSBuild ( self,  value)"

.PP
.nf
Returns the MSBuild equivalent of the MSVS value given\&.

Args:
value: the MSVS value to convert\&.

Returns:
the MSBuild equivalent\&.

Raises:
ValueError if value is not valid\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB206\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._Enumeration\&.ValidateMSBuild ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSBuild\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSBuild\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB202\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._Enumeration\&.ValidateMSVS ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSVS\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSVS\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB198\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Enumeration\&._label_list\fR [protected]\fP"

.PP
Definition at line \fB193\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._Enumeration\&._msbuild_values\fR [protected]\fP"

.PP
Definition at line \fB194\fP of file \fBMSVSSettings\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
