.TH "gyp.xcodeproj_file.PBXProject" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.xcodeproj_file.PBXProject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.xcodeproj_file\&.XCContainerPortal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, properties=None, \fBid\fP=None, \fBparent\fP=None, \fBpath\fP=None)"
.br
.ti -1c
.RI "\fBName\fP (self)"
.br
.ti -1c
.RI "\fBPath\fP (self)"
.br
.ti -1c
.RI "\fBComment\fP (self)"
.br
.ti -1c
.RI "\fBChildren\fP (self)"
.br
.ti -1c
.RI "\fBPBXProjectAncestor\fP (self)"
.br
.ti -1c
.RI "\fBSourceGroup\fP (self)"
.br
.ti -1c
.RI "\fBProductsGroup\fP (self)"
.br
.ti -1c
.RI "\fBIntermediatesGroup\fP (self)"
.br
.ti -1c
.RI "\fBFrameworksGroup\fP (self)"
.br
.ti -1c
.RI "\fBProjectsGroup\fP (self)"
.br
.ti -1c
.RI "\fBRootGroupForPath\fP (self, \fBpath\fP)"
.br
.ti -1c
.RI "\fBAddOrGetFileInRootGroup\fP (self, \fBpath\fP)"
.br
.ti -1c
.RI "\fBRootGroupsTakeOverOnlyChildren\fP (self, recurse=False)"
.br
.ti -1c
.RI "\fBSortGroups\fP (self)"
.br
.ti -1c
.RI "\fBAddOrGetProjectReference\fP (self, other_pbxproject)"
.br
.ti -1c
.RI "\fBSortRemoteProductReferences\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBCopy\fP (self)"
.br
.ti -1c
.RI "\fBHashables\fP (self)"
.br
.ti -1c
.RI "\fBHashablesForChild\fP (self)"
.br
.ti -1c
.RI "\fBComputeIDs\fP (self, recursive=True, overwrite=True, seed_hash=None)"
.br
.ti -1c
.RI "\fBEnsureNoIDCollisions\fP (self)"
.br
.ti -1c
.RI "\fBDescendants\fP (self)"
.br
.ti -1c
.RI "\fBPrint\fP (self, file=sys\&.stdout)"
.br
.ti -1c
.RI "\fBUpdateProperties\fP (self, properties, do_copy=False)"
.br
.ti -1c
.RI "\fBHasProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBGetProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBSetProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBDelProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBAppendProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBVerifyHasRequiredProperties\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBIntermediatesGroup\fP"
.br
.in -1c

Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_GroupByName\fP (self, name)"
.br
.ti -1c
.RI "\fB_AllSymrootsUnique\fP (self, target, inherit_unique_symroot)"
.br
.ti -1c
.RI "\fB_DefinedSymroots\fP (self, target)"
.br
.ti -1c
.RI "\fB_IsUniqueSymrootForTarget\fP (self, symroot)"
.br
.ti -1c
.RI "\fB_SetUpProductReferences\fP (self, other_pbxproject, product_group, project_ref)"
.br
.in -1c

Protected Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_EncodeComment\fP (self, comment)"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP (self, match)"
.br
.ti -1c
.RI "\fB_EncodeString\fP (self, value)"
.br
.ti -1c
.RI "\fB_XCPrint\fP (self, file, tabs, line)"
.br
.ti -1c
.RI "\fB_XCPrintableValue\fP (self, tabs, value, flatten_list=False)"
.br
.ti -1c
.RI "\fB_XCKVPrint\fP (self, file, tabs, key, value)"
.br
.ti -1c
.RI "\fB_SetDefaultsFromSchema\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_other_pbxprojects\fP"
.br
.ti -1c
.RI "\fB_properties\fP"
.br
.in -1c

Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_properties\fP"
.br
.ti -1c
.RI "\fB_hashables\fP"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_schema\fP = XCContainerPortal\&._schema\&.copy()"
.br
.in -1c

Static Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "dict \fB_schema\fP = {}"
.br
.ti -1c
.RI "bool \fB_should_print_single_line\fP = False"
.br
.ti -1c
.RI "list \fB_encode_transforms\fP = []"
.br
.ti -1c
.RI "\fB_alternate_encode_transforms\fP = list(\fB_encode_transforms\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "int \fBi\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Attributes:
path: 'sample\&.xcodeproj'\&.  TODO(mark) Document me!
_other_pbxprojects: A dictionary, keyed by other PBXProject objects\&.  Each
                    value is a reference to the dict in the
                    projectReferences list associated with the keyed
                    PBXProject\&.

.fi
.PP
 
.PP
Definition at line \fB2734\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.__init__ ( self,  properties = \fRNone\fP,  id = \fRNone\fP,  parent = \fRNone\fP,  path = \fRNone\fP)"

.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB2769\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.PBXProject\&._AllSymrootsUnique ( self,  target,  inherit_unique_symroot)\fR [protected]\fP"

.PP
Definition at line \fB3011\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&._DefinedSymroots ( self,  target)\fR [protected]\fP"

.PP
Definition at line \fB3027\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&._GroupByName ( self,  name)\fR [protected]\fP"

.PP
Definition at line \fB2804\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&._IsUniqueSymrootForTarget ( self,  symroot)\fR [protected]\fP"

.PP
Definition at line \fB3045\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&._SetUpProductReferences ( self,  other_pbxproject,  product_group,  project_ref)\fR [protected]\fP"

.PP
Definition at line \fB3054\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.AddOrGetFileInRootGroup ( self,  path)"

.PP
.nf
Returns a PBXFileReference corresponding to path in the correct group
according to RootGroupForPath's heuristics\&.

If an existing PBXFileReference for path exists, it will be returned\&.
Otherwise, one will be created and returned\&.

.fi
.PP
 
.PP
Definition at line \fB2875\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.AddOrGetProjectReference ( self,  other_pbxproject)"

.PP
.nf
Add a reference to another project file (via PBXProject object) to this
one\&.

Returns [ProductGroup, ProjectRef]\&.  ProductGroup is a PBXGroup object in
this project file that contains a PBXReferenceProxy object for each
product of each PBXNativeTarget in the other project file\&.  ProjectRef is
a PBXFileReference to the other project file\&.

If this project file already references the other project file, the
existing ProductGroup and ProjectRef are returned\&.  The ProductGroup will
still be updated if necessary\&.

.fi
.PP
 
.PP
Definition at line \fB2929\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.Children ( self)"

.PP
.nf
Returns a list of all of this object's owned (strong) children\&.
.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB2787\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.Comment ( self)"

.PP
.nf
Return a comment string for the object\&.

Most objects just use their name as the comment, but PBXProject uses
different values\&.

The returned comment is not escaped and does not have any comment marker
strings applied to it\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB2784\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.FrameworksGroup ( self)"

.PP
Definition at line \fB2832\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.IntermediatesGroup ( self)"

.PP
Definition at line \fB2827\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.Name ( self)"

.PP
.nf
Return the name corresponding to an object\&.

Not all objects necessarily need to be nameable, and not all that do have
a 'name' property\&.  Override as needed\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB2775\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.Path ( self)"

.PP
Definition at line \fB2781\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.PBXProjectAncestor ( self)"

.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB2801\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.ProductsGroup ( self)"

.PP
Definition at line \fB2821\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.ProjectsGroup ( self)"

.PP
Definition at line \fB2835\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.RootGroupForPath ( self,  path)"

.PP
.nf
Returns a PBXGroup child of this object to which path should be added\&.

This method is intended to choose between SourceGroup and
IntermediatesGroup on the basis of whether path is present in a source
directory or an intermediates directory\&.  For the purposes of this
determination, any path located within a derived file directory such as
PROJECT_DERIVED_FILE_DIR is treated as being in an intermediates
directory\&.

The returned value is a two-element tuple\&.  The first element is the
PBXGroup, and the second element specifies whether that group should be
organized hierarchically (True) or as a single flat list (False)\&.

.fi
.PP
 
.PP
Definition at line \fB2838\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.RootGroupsTakeOverOnlyChildren ( self,  recurse = \fRFalse\fP)"

.PP
.nf
Calls TakeOverOnlyChild for all groups in the main group\&.
.fi
.PP
 
.PP
Definition at line \fB2886\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.SortGroups ( self)"

.PP
Definition at line \fB2893\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.SortRemoteProductReferences ( self)"

.PP
Definition at line \fB3093\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.SourceGroup ( self)"

.PP
Definition at line \fB2818\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.PBXProject\&._other_pbxprojects\fR [protected]\fP"

.PP
Definition at line \fB2771\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&._properties\fR [protected]\fP"

.PP
Definition at line \fB2795\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&._schema = XCContainerPortal\&._schema\&.copy()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB2748\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.IntermediatesGroup"

.PP
Definition at line \fB2859\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXProject\&.path"

.PP
Definition at line \fB2770\fP of file \fBxcodeproj_file\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
