.TH "gyp.MSVSSettings._Tool" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSSettings._Tool
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBmsvs_name\fP, \fBmsbuild_name\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmsvs_name\fP"
.br
.ti -1c
.RI "\fBmsbuild_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Represents a tool used by MSVS or MSBuild\&.

Attributes:
  msvs_name: The name of the tool in MSVS\&.
  msbuild_name: The name of the tool in MSBuild\&.

.fi
.PP
 
.PP
Definition at line \fB35\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Tool\&.__init__ ( self,  msvs_name,  msbuild_name)"

.PP
Definition at line \fB43\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._Tool\&.msbuild_name"

.PP
Definition at line \fB45\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._Tool\&.msvs_name"

.PP
Definition at line \fB44\fP of file \fBMSVSSettings\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
