.TH "gyp.xcodeproj_file.XCHierarchicalElement" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.xcodeproj_file.XCHierarchicalElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Inherited by \fBgyp\&.xcodeproj_file\&.PBXGroup\fP, and \fBgyp\&.xcodeproj_file\&.XCFileLikeElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, properties=None, \fBid\fP=None, \fBparent\fP=None)"
.br
.ti -1c
.RI "\fBName\fP (self)"
.br
.ti -1c
.RI "\fBHashables\fP (self)"
.br
.ti -1c
.RI "\fBCompare\fP (self, other)"
.br
.ti -1c
.RI "\fBCompareRootGroup\fP (self, other)"
.br
.ti -1c
.RI "\fBPathFromSourceTreeAndPath\fP (self)"
.br
.ti -1c
.RI "\fBFullPath\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBCopy\fP (self)"
.br
.ti -1c
.RI "\fBComment\fP (self)"
.br
.ti -1c
.RI "\fBHashablesForChild\fP (self)"
.br
.ti -1c
.RI "\fBComputeIDs\fP (self, recursive=True, overwrite=True, seed_hash=None)"
.br
.ti -1c
.RI "\fBEnsureNoIDCollisions\fP (self)"
.br
.ti -1c
.RI "\fBChildren\fP (self)"
.br
.ti -1c
.RI "\fBDescendants\fP (self)"
.br
.ti -1c
.RI "\fBPBXProjectAncestor\fP (self)"
.br
.ti -1c
.RI "\fBPrint\fP (self, file=sys\&.stdout)"
.br
.ti -1c
.RI "\fBUpdateProperties\fP (self, properties, do_copy=False)"
.br
.ti -1c
.RI "\fBHasProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBGetProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBSetProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBDelProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBAppendProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBVerifyHasRequiredProperties\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_properties\fP"
.br
.ti -1c
.RI "\fB_hashables\fP"
.br
.in -1c

Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_properties\fP"
.br
.ti -1c
.RI "\fB_hashables\fP"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_schema\fP = XCObject\&._schema\&.copy()"
.br
.in -1c

Static Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "dict \fB_schema\fP = {}"
.br
.ti -1c
.RI "bool \fB_should_print_single_line\fP = False"
.br
.ti -1c
.RI "list \fB_encode_transforms\fP = []"
.br
.ti -1c
.RI "\fB_alternate_encode_transforms\fP = list(\fB_encode_transforms\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.in -1c

Static Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "int \fBi\fP = 0"
.br
.in -1c

Protected Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_EncodeComment\fP (self, comment)"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP (self, match)"
.br
.ti -1c
.RI "\fB_EncodeString\fP (self, value)"
.br
.ti -1c
.RI "\fB_XCPrint\fP (self, file, tabs, line)"
.br
.ti -1c
.RI "\fB_XCPrintableValue\fP (self, tabs, value, flatten_list=False)"
.br
.ti -1c
.RI "\fB_XCKVPrint\fP (self, file, tabs, key, value)"
.br
.ti -1c
.RI "\fB_SetDefaultsFromSchema\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Abstract base for PBXGroup and PBXFileReference\&.  Not represented in a
project file\&.
.fi
.PP
 
.PP
Definition at line \fB944\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&.__init__ ( self,  properties = \fRNone\fP,  id = \fRNone\fP,  parent = \fRNone\fP)"

.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Reimplemented in \fBgyp\&.xcodeproj_file\&.PBXFileReference\fP, and \fBgyp\&.xcodeproj_file\&.PBXGroup\fP\&.
.PP
Definition at line \fB968\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&.Compare ( self,  other)"

.PP
Definition at line \fB1064\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&.CompareRootGroup ( self,  other)"

.PP
Definition at line \fB1084\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&.FullPath ( self)"

.PP
Definition at line \fB1139\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&.Hashables ( self)"

.PP
.nf
Custom hashables for XCHierarchicalElements\&.

XCHierarchicalElements are special\&.  Generally, their hashes shouldn't
change if the paths don't change\&.  The normal XCObject implementation of
Hashables adds a hashable for each object, which means that if
the hierarchical structure changes (possibly due to changes caused when
TakeOverOnlyChild runs and encounters slight changes in the hierarchy),
the hashes will change\&.  For example, if a project file initially contains
a/b/f1 and a/b becomes collapsed into a/b, f1 will have a single parent
a/b\&.  If someone later adds a/f2 to the project file, a/b can no longer be
collapsed, and f1 winds up with parent b and grandparent a\&.  That would
be sufficient to change f1's hash\&.

To counteract this problem, hashables for all XCHierarchicalElements except
for the main group (which has neither a name nor a path) are taken to be
just the set of path components\&.  Because hashables are inherited from
parents, this provides assurance that a/b/f1 has the same set of hashables
whether its parent is b or a/b\&.

The main group is a special case\&.  As it is permitted to have no name or
path, it is permitted to use the standard XCObject hash mechanism\&.  This
is not considered a problem because there can be only one main group\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Reimplemented in \fBgyp\&.xcodeproj_file\&.PBXGroup\fP\&.
.PP
Definition at line \fB1009\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&.Name ( self)"

.PP
.nf
Return the name corresponding to an object\&.

Not all objects necessarily need to be nameable, and not all that do have
a 'name' property\&.  Override as needed\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB1000\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&.PathFromSourceTreeAndPath ( self)"

.PP
Definition at line \fB1123\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&._hashables\fR [protected]\fP"

.PP
Definition at line \fB1060\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&._properties\fR [protected]\fP"

.PP
Definition at line \fB971\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCHierarchicalElement\&._schema = XCObject\&._schema\&.copy()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB953\fP of file \fBxcodeproj_file\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
