.TH "gyp.input.DependencyGraphNode" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.input.DependencyGraphNode
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCircularException\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBref\fP)"
.br
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBFlattenToList\fP (self)"
.br
.ti -1c
.RI "\fBFindCycles\fP (self)"
.br
.ti -1c
.RI "\fBDirectDependencies\fP (self, \fBdependencies\fP=None)"
.br
.ti -1c
.RI "\fBDirectAndImportedDependencies\fP (self, targets, \fBdependencies\fP=None)"
.br
.ti -1c
.RI "\fBDeepDependencies\fP (self, \fBdependencies\fP=None)"
.br
.ti -1c
.RI "\fBDependenciesForLinkSettings\fP (self, targets)"
.br
.ti -1c
.RI "\fBDependenciesToLinkAgainst\fP (self, targets)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBref\fP"
.br
.ti -1c
.RI "\fBdependencies\fP"
.br
.ti -1c
.RI "\fBdependents\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_AddImportedDependencies\fP (self, targets, \fBdependencies\fP=None)"
.br
.ti -1c
.RI "\fB_LinkDependenciesInternal\fP (self, targets, include_shared_libraries, \fBdependencies\fP=None, initial=True)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Attributes:
ref: A reference to an object that this DependencyGraphNode represents\&.
dependencies: List of DependencyGraphNodes on which this one depends\&.
dependents: List of DependencyGraphNodes that depend on this one\&.

.fi
.PP
 
.PP
Definition at line \fB1666\fP of file \fBinput\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.input\&.DependencyGraphNode\&.__init__ ( self,  ref)"

.PP
Definition at line \fB1678\fP of file \fBinput\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.input\&.DependencyGraphNode\&.__repr__ ( self)"

.PP
Definition at line \fB1683\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&._AddImportedDependencies ( self,  targets,  dependencies = \fRNone\fP)\fR [protected]\fP"

.PP
.nf
Given a list of direct dependencies, adds indirect dependencies that
other dependencies have declared to export their settings\&.

This method does not operate on self\&.  Rather, it operates on the list
of dependencies in the |dependencies| argument\&.  For each dependency in
that list, if any declares that it exports the settings of one of its
own dependencies, those dependencies whose settings are 'passed through'
are added to the list\&.  As new items are added to the list, they too will
be processed, so it is possible to import settings through multiple levels
of dependencies\&.

This method is not terribly useful on its own, it depends on being
'primed' with a list of direct dependencies such as one provided by
DirectDependencies\&.  DirectAndImportedDependencies is intended to be the
public entry point\&.

.fi
.PP
 
.PP
Definition at line \fB1769\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&._LinkDependenciesInternal ( self,  targets,  include_shared_libraries,  dependencies = \fRNone\fP,  initial = \fRTrue\fP)\fR [protected]\fP"

.PP
.nf
Returns an OrderedSet of dependency targets that are linked
into this target\&.

This function has a split personality, depending on the setting of
|initial|\&.  Outside callers should always leave |initial| at its default
setting\&.

When adding a target to the list of dependencies, this function will
recurse into itself with |initial| set to False, to collect dependencies
that are linked into the linkable target for which the list is being built\&.

If |include_shared_libraries| is False, the resulting dependencies will not
include shared_library targets that are linked into this target\&.

.fi
.PP
 
.PP
Definition at line \fB1837\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.DeepDependencies ( self,  dependencies = \fRNone\fP)"

.PP
.nf
Returns an OrderedSet of all of a target's dependencies, recursively\&.
.fi
.PP
 
.PP
Definition at line \fB1820\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.DependenciesForLinkSettings ( self,  targets)"

.PP
.nf
Returns a list of dependency targets whose link_settings should be merged
into this target\&.

.fi
.PP
 
.PP
Definition at line \fB1933\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.DependenciesToLinkAgainst ( self,  targets)"

.PP
.nf
Returns a list of dependency targets that are linked into this target\&.

.fi
.PP
 
.PP
Definition at line \fB1948\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.DirectAndImportedDependencies ( self,  targets,  dependencies = \fRNone\fP)"

.PP
.nf
Returns a list of a target's direct dependencies and all indirect
dependencies that a dependency has advertised settings should be exported
through the dependency for\&.

.fi
.PP
 
.PP
Definition at line \fB1811\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.DirectDependencies ( self,  dependencies = \fRNone\fP)"

.PP
.nf
Returns a list of just direct dependencies\&.
.fi
.PP
 
.PP
Definition at line \fB1757\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.FindCycles ( self)"

.PP
.nf
Returns a list of cycles in the graph, where each cycle is its own list\&.

.fi
.PP
 
.PP
Definition at line \fB1737\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.FlattenToList ( self)"

.PP
Definition at line \fB1686\fP of file \fBinput\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.input\&.DependencyGraphNode\&.dependencies"

.PP
Definition at line \fB1680\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.dependents"

.PP
Definition at line \fB1681\fP of file \fBinput\&.py\fP\&.
.SS "gyp\&.input\&.DependencyGraphNode\&.ref"

.PP
Definition at line \fB1679\fP of file \fBinput\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
