.TH "gyp.easy_xml_test.TestSequenceFunctions" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.easy_xml_test.TestSequenceFunctions
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP (self)"
.br
.ti -1c
.RI "\fBtest_EasyXml_simple\fP (self)"
.br
.ti -1c
.RI "\fBtest_EasyXml_simple_with_attributes\fP (self)"
.br
.ti -1c
.RI "\fBtest_EasyXml_escaping\fP (self)"
.br
.ti -1c
.RI "\fBtest_EasyXml_pretty\fP (self)"
.br
.ti -1c
.RI "\fBtest_EasyXml_complex\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstderr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBeasy_xml_test\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.easy_xml_test\&.TestSequenceFunctions\&.setUp ( self)"

.PP
Definition at line \fB16\fP of file \fBeasy_xml_test\&.py\fP\&.
.SS "gyp\&.easy_xml_test\&.TestSequenceFunctions\&.test_EasyXml_complex ( self)"

.PP
Definition at line \fB63\fP of file \fBeasy_xml_test\&.py\fP\&.
.SS "gyp\&.easy_xml_test\&.TestSequenceFunctions\&.test_EasyXml_escaping ( self)"

.PP
Definition at line \fB36\fP of file \fBeasy_xml_test\&.py\fP\&.
.SS "gyp\&.easy_xml_test\&.TestSequenceFunctions\&.test_EasyXml_pretty ( self)"

.PP
Definition at line \fB46\fP of file \fBeasy_xml_test\&.py\fP\&.
.SS "gyp\&.easy_xml_test\&.TestSequenceFunctions\&.test_EasyXml_simple ( self)"

.PP
Definition at line \fB19\fP of file \fBeasy_xml_test\&.py\fP\&.
.SS "gyp\&.easy_xml_test\&.TestSequenceFunctions\&.test_EasyXml_simple_with_attributes ( self)"

.PP
Definition at line \fB30\fP of file \fBeasy_xml_test\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.easy_xml_test\&.TestSequenceFunctions\&.stderr"

.PP
Definition at line \fB17\fP of file \fBeasy_xml_test\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
