.TH "gyp.MSVSProject.Filter" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSProject.Filter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBname\fP, \fBcontents\fP=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBcontents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Visual Studio filter - that is, a virtual folder\&.
.fi
.PP
 
.PP
Definition at line \fB34\fP of file \fBMSVSProject\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSProject\&.Filter\&.__init__ ( self,  name,  contents = \fRNone\fP)"

.PP
.nf
Initializes the folder\&.

Args:
name: Filter (folder) name\&.
contents: List of filenames and/or Filter objects contained\&.

.fi
.PP
 
.PP
Definition at line \fB37\fP of file \fBMSVSProject\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSProject\&.Filter\&.contents"

.PP
Definition at line \fB45\fP of file \fBMSVSProject\&.py\fP\&.
.SS "gyp\&.MSVSProject\&.Filter\&.name"

.PP
Definition at line \fB44\fP of file \fBMSVSProject\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
