.TH "gyp.generator.analyzer.Config" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.analyzer.Config
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBInit\fP (self, params)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfiles\fP"
.br
.ti -1c
.RI "\fBtargets\fP"
.br
.ti -1c
.RI "\fBadditional_compile_target_names\fP"
.br
.ti -1c
.RI "\fBtest_target_names\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Details what we're looking for
files: set of files to search for
targets: see file description for details\&.
.fi
.PP
 
.PP
Definition at line \fB254\fP of file \fBanalyzer\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.generator\&.analyzer\&.Config\&.__init__ ( self)"

.PP
Definition at line \fB259\fP of file \fBanalyzer\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.generator\&.analyzer\&.Config\&.Init ( self,  params)"

.PP
.nf
Initializes Config\&. This is a separate method as it raises an exception
if there is a parse error\&.
.fi
.PP
 
.PP
Definition at line \fB265\fP of file \fBanalyzer\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.generator\&.analyzer\&.Config\&.additional_compile_target_names"

.PP
Definition at line \fB262\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Config\&.files"

.PP
Definition at line \fB260\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Config\&.targets"

.PP
Definition at line \fB261\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Config\&.test_target_names"

.PP
Definition at line \fB263\fP of file \fBanalyzer\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
