.TH "gyp.xml_fix.XmlFix" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.xml_fix.XmlFix
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBCleanup\fP (self)"
.br
.ti -1c
.RI "\fB__del__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwrite_data\fP"
.br
.ti -1c
.RI "\fBwritexml\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Object to manage temporary patching of xml\&.dom\&.minidom\&.
.fi
.PP
 
.PP
Definition at line \fB47\fP of file \fBxml_fix\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.xml_fix\&.XmlFix\&.__init__ ( self)"

.PP
Definition at line \fB50\fP of file \fBxml_fix\&.py\fP\&.
.SS "gyp\&.xml_fix\&.XmlFix\&.__del__ ( self)"

.PP
Definition at line \fB64\fP of file \fBxml_fix\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.xml_fix\&.XmlFix\&.Cleanup ( self)"

.PP
Definition at line \fB58\fP of file \fBxml_fix\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.xml_fix\&.XmlFix\&.write_data"

.PP
Definition at line \fB52\fP of file \fBxml_fix\&.py\fP\&.
.SS "gyp\&.xml_fix\&.XmlFix\&.writexml"

.PP
Definition at line \fB53\fP of file \fBxml_fix\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
