.TH "gyp.xml_fix" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.xml_fix
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXmlFix\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_Replacement_write_data\fP (writer, data, is_attrib=False)"
.br
.ti -1c
.RI "\fB_Replacement_writexml\fP (self, writer, indent='', addindent='', newl='')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtagName\fP"
.br
.ti -1c
.RI "\fBchildNodes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Applies a fix to CR LF TAB handling in xml\&.dom\&.

Fixes this: http://code\&.google\&.com/p/chromium/issues/detail?id=76293
Working around this: http://bugs\&.python\&.org/issue5752
TODO(bradnelson): Consider dropping this when we drop XP support\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "gyp\&.xml_fix\&._Replacement_write_data ( writer,  data,  is_attrib = \fRFalse\fP)\fR [protected]\fP"

.PP
.nf
Writes datachars to writer\&.
.fi
.PP
 
.PP
Definition at line \fB16\fP of file \fBxml_fix\&.py\fP\&.
.SS "gyp\&.xml_fix\&._Replacement_writexml ( self,  writer,  indent = \fR''\fP,  addindent = \fR''\fP,  newl = \fR''\fP)\fR [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBxml_fix\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "gyp\&.xml_fix\&.childNodes"

.PP
Definition at line \fB38\fP of file \fBxml_fix\&.py\fP\&.
.SS "gyp\&.xml_fix\&.tagName"

.PP
Definition at line \fB29\fP of file \fBxml_fix\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
