.TH "gyp.generator.msvs_test.TestSequenceFunctions" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.msvs_test.TestSequenceFunctions
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP (self)"
.br
.ti -1c
.RI "\fBtest_GetLibraries\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstderr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBmsvs_test\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.generator\&.msvs_test\&.TestSequenceFunctions\&.setUp ( self)"

.PP
Definition at line \fB15\fP of file \fBmsvs_test\&.py\fP\&.
.SS "gyp\&.generator\&.msvs_test\&.TestSequenceFunctions\&.test_GetLibraries ( self)"

.PP
Definition at line \fB18\fP of file \fBmsvs_test\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.generator\&.msvs_test\&.TestSequenceFunctions\&.stderr"

.PP
Definition at line \fB16\fP of file \fBmsvs_test\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
