.TH "gyp.xcodeproj_file.PBXGroup" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.xcodeproj_file.PBXGroup
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.xcodeproj_file\&.XCHierarchicalElement\fP\&.
.PP
Inherited by \fBgyp\&.xcodeproj_file\&.PBXVariantGroup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, properties=None, \fBid\fP=None, \fBparent\fP=None)"
.br
.ti -1c
.RI "\fBHashables\fP (self)"
.br
.ti -1c
.RI "\fBHashablesForChild\fP (self)"
.br
.ti -1c
.RI "\fBAppendChild\fP (self, child)"
.br
.ti -1c
.RI "\fBGetChildByName\fP (self, name)"
.br
.ti -1c
.RI "\fBGetChildByPath\fP (self, path)"
.br
.ti -1c
.RI "\fBGetChildByRemoteObject\fP (self, remote_object)"
.br
.ti -1c
.RI "\fBAddOrGetFileByPath\fP (self, path, hierarchical)"
.br
.ti -1c
.RI "\fBAddOrGetVariantGroupByNameAndPath\fP (self, name, path)"
.br
.ti -1c
.RI "\fBTakeOverOnlyChild\fP (self, recurse=False)"
.br
.ti -1c
.RI "\fBSortGroup\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCHierarchicalElement\fP
.in +1c
.ti -1c
.RI "\fBName\fP (self)"
.br
.ti -1c
.RI "\fBCompare\fP (self, other)"
.br
.ti -1c
.RI "\fBCompareRootGroup\fP (self, other)"
.br
.ti -1c
.RI "\fBPathFromSourceTreeAndPath\fP (self)"
.br
.ti -1c
.RI "\fBFullPath\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBCopy\fP (self)"
.br
.ti -1c
.RI "\fBComment\fP (self)"
.br
.ti -1c
.RI "\fBComputeIDs\fP (self, recursive=True, overwrite=True, seed_hash=None)"
.br
.ti -1c
.RI "\fBEnsureNoIDCollisions\fP (self)"
.br
.ti -1c
.RI "\fBChildren\fP (self)"
.br
.ti -1c
.RI "\fBDescendants\fP (self)"
.br
.ti -1c
.RI "\fBPBXProjectAncestor\fP (self)"
.br
.ti -1c
.RI "\fBPrint\fP (self, file=sys\&.stdout)"
.br
.ti -1c
.RI "\fBUpdateProperties\fP (self, properties, do_copy=False)"
.br
.ti -1c
.RI "\fBHasProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBGetProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBSetProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBDelProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBAppendProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBVerifyHasRequiredProperties\fP (self)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_AddChildToDicts\fP (self, child)"
.br
.in -1c

Protected Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_EncodeComment\fP (self, comment)"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP (self, match)"
.br
.ti -1c
.RI "\fB_EncodeString\fP (self, value)"
.br
.ti -1c
.RI "\fB_XCPrint\fP (self, file, tabs, line)"
.br
.ti -1c
.RI "\fB_XCPrintableValue\fP (self, tabs, value, flatten_list=False)"
.br
.ti -1c
.RI "\fB_XCKVPrint\fP (self, file, tabs, key, value)"
.br
.ti -1c
.RI "\fB_SetDefaultsFromSchema\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_children_by_path\fP"
.br
.ti -1c
.RI "\fB_variant_children_by_name_and_path\fP"
.br
.ti -1c
.RI "\fB_properties\fP"
.br
.in -1c

Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCHierarchicalElement\fP
.in +1c
.ti -1c
.RI "\fB_properties\fP"
.br
.ti -1c
.RI "\fB_hashables\fP"
.br
.in -1c

Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_properties\fP"
.br
.ti -1c
.RI "\fB_hashables\fP"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_schema\fP = XCHierarchicalElement\&._schema\&.copy()"
.br
.in -1c

Static Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCHierarchicalElement\fP
.in +1c
.ti -1c
.RI "\fB_schema\fP = XCObject\&._schema\&.copy()"
.br
.in -1c

Static Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "dict \fB_schema\fP = {}"
.br
.ti -1c
.RI "bool \fB_should_print_single_line\fP = False"
.br
.ti -1c
.RI "list \fB_encode_transforms\fP = []"
.br
.ti -1c
.RI "\fB_alternate_encode_transforms\fP = list(\fB_encode_transforms\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.in -1c

Static Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "int \fBi\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Attributes:
_children_by_path: Maps pathnames of children of this PBXGroup to the
  actual child XCHierarchicalElement objects\&.
_variant_children_by_name_and_path: Maps (name, path) tuples of
  PBXVariantGroup children to the actual child PBXVariantGroup objects\&.

.fi
.PP
 
.PP
Definition at line \fB1160\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.__init__ ( self,  properties = \fRNone\fP,  id = \fRNone\fP,  parent = \fRNone\fP)"

.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCHierarchicalElement\fP\&.
.PP
Definition at line \fB1178\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&._AddChildToDicts ( self,  child)\fR [protected]\fP"

.PP
Definition at line \fB1206\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.AddOrGetFileByPath ( self,  path,  hierarchical)"

.PP
.nf
Returns an existing or new file reference corresponding to path\&.

If hierarchical is True, this method will create or use the necessary
hierarchical group structure corresponding to path\&.  Otherwise, it will
look in and create an item in the current group only\&.

If an existing matching reference is found, it is returned, otherwise, a
new one will be created, added to the correct group, and returned\&.

If path identifies a directory by virtue of carrying a trailing slash,
this method returns a PBXFileReference of 'folder' type\&.  If path
identifies a variant, by virtue of it identifying a file inside a directory
with an '\&.lproj' extension, this method returns a PBXVariantGroup
containing the variant named by path, and possibly other variants\&.  For
all other paths, a 'normal' PBXFileReference will be returned\&.

.fi
.PP
 
.PP
Definition at line \fB1283\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.AddOrGetVariantGroupByNameAndPath ( self,  name,  path)"

.PP
.nf
Returns an existing or new PBXVariantGroup for name and path\&.

If a PBXVariantGroup identified by the name and path arguments is already
present as a child of this object, it is returned\&.  Otherwise, a new
PBXVariantGroup with the correct properties is created, added as a child,
and returned\&.

This method will generally be called by AddOrGetFileByPath, which knows
when to create a variant group based on the structure of the pathnames
passed to it\&.

.fi
.PP
 
.PP
Definition at line \fB1381\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.AppendChild ( self,  child)"

.PP
Definition at line \fB1227\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.GetChildByName ( self,  name)"

.PP
Definition at line \fB1234\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.GetChildByPath ( self,  path)"

.PP
Definition at line \fB1252\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.GetChildByRemoteObject ( self,  remote_object)"

.PP
Definition at line \fB1261\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.Hashables ( self)"

.PP
.nf
Custom hashables for XCHierarchicalElements\&.

XCHierarchicalElements are special\&.  Generally, their hashes shouldn't
change if the paths don't change\&.  The normal XCObject implementation of
Hashables adds a hashable for each object, which means that if
the hierarchical structure changes (possibly due to changes caused when
TakeOverOnlyChild runs and encounters slight changes in the hierarchy),
the hashes will change\&.  For example, if a project file initially contains
a/b/f1 and a/b becomes collapsed into a/b, f1 will have a single parent
a/b\&.  If someone later adds a/f2 to the project file, a/b can no longer be
collapsed, and f1 winds up with parent b and grandparent a\&.  That would
be sufficient to change f1's hash\&.

To counteract this problem, hashables for all XCHierarchicalElements except
for the main group (which has neither a name nor a path) are taken to be
just the set of path components\&.  Because hashables are inherited from
parents, this provides assurance that a/b/f1 has the same set of hashables
whether its parent is b or a/b\&.

The main group is a special case\&.  As it is permitted to have no name or
path, it is permitted to use the standard XCObject hash mechanism\&.  This
is not considered a problem because there can be only one main group\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCHierarchicalElement\fP\&.
.PP
Definition at line \fB1186\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.HashablesForChild ( self)"

.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB1201\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.SortGroup ( self)"

.PP
Definition at line \fB1488\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&.TakeOverOnlyChild ( self,  recurse = \fRFalse\fP)"

.PP
.nf
If this PBXGroup has only one child and it's also a PBXGroup, take
it over by making all of its children this object's children\&.

This function will continue to take over only children when those children
are groups\&.  If there are three PBXGroups representing a, b, and c, with
c inside b and b inside a, and a and b have no other children, this will
result in a taking over both b and c, forming a PBXGroup for a/b/c\&.

If recurse is True, this function will recurse into children and ask them
to collapse themselves by taking over only children as well\&.  Assuming
an example hierarchy with files at a/b/c/d1, a/b/c/d2, and a/b/c/d3/e/f
(d1, d2, and f are files, the rest are groups), recursion will result in
a group for a/b/c containing a group for d3/e\&.

.fi
.PP
 
.PP
Definition at line \fB1408\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&._children_by_path\fR [protected]\fP"

.PP
Definition at line \fB1181\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&._properties\fR [protected]\fP"

.PP
Definition at line \fB1243\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&._schema = XCHierarchicalElement\&._schema\&.copy()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB1169\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.PBXGroup\&._variant_children_by_name_and_path\fR [protected]\fP"

.PP
Definition at line \fB1182\fP of file \fBxcodeproj_file\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
