.TH "gyp.flock_tool" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.flock_tool
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFlockTool\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
These functions are executed via gyp-flock-tool when using the Makefile
generator\&.  Used on systems that don't have a built-in flock\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "gyp\&.flock_tool\&.main ( args)"

.PP
Definition at line \fB16\fP of file \fBflock_tool\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
