.TH "gyp.MSVSToolFile.Writer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSToolFile.Writer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBtool_file_path\fP, \fBname\fP)"
.br
.ti -1c
.RI "\fBAddCustomBuildRule\fP (self, \fBname\fP, cmd, description, additional_dependencies, outputs, extensions)"
.br
.ti -1c
.RI "\fBWriteIfChanged\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtool_file_path\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBrules_section\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Visual Studio XML tool file writer\&.
.fi
.PP
 
.PP
Definition at line \fB10\fP of file \fBMSVSToolFile\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSToolFile\&.Writer\&.__init__ ( self,  tool_file_path,  name)"

.PP
.nf
Initializes the tool file\&.

Args:
tool_file_path: Path to the tool file\&.
name: Name of the tool file\&.

.fi
.PP
 
.PP
Definition at line \fB13\fP of file \fBMSVSToolFile\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSToolFile\&.Writer\&.AddCustomBuildRule ( self,  name,  cmd,  description,  additional_dependencies,  outputs,  extensions)"

.PP
.nf
Adds a rule to the tool file\&.

Args:
name: Name of the rule\&.
description: Description of the rule\&.
cmd: Command line of the rule\&.
additional_dependencies: other files which may trigger the rule\&.
outputs: outputs of the rule\&.
extensions: extensions handled by the rule\&.

.fi
.PP
 
.PP
Definition at line \fB24\fP of file \fBMSVSToolFile\&.py\fP\&.
.SS "gyp\&.MSVSToolFile\&.Writer\&.WriteIfChanged ( self)"

.PP
.nf
Writes the tool file\&.
.fi
.PP
 
.PP
Definition at line \fB50\fP of file \fBMSVSToolFile\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSToolFile\&.Writer\&.name"

.PP
Definition at line \fB21\fP of file \fBMSVSToolFile\&.py\fP\&.
.SS "gyp\&.MSVSToolFile\&.Writer\&.rules_section"

.PP
Definition at line \fB22\fP of file \fBMSVSToolFile\&.py\fP\&.
.SS "gyp\&.MSVSToolFile\&.Writer\&.tool_file_path"

.PP
Definition at line \fB20\fP of file \fBMSVSToolFile\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
