.TH "gyp.generator.ninja.Target" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.ninja.Target
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBtype\fP)"
.br
.ti -1c
.RI "\fBLinkable\fP (self)"
.br
.ti -1c
.RI "\fBUsesToc\fP (self, flavor)"
.br
.ti -1c
.RI "\fBPreActionInput\fP (self, flavor)"
.br
.ti -1c
.RI "\fBPreCompileInput\fP (self)"
.br
.ti -1c
.RI "\fBFinalOutput\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBpreaction_stamp\fP"
.br
.ti -1c
.RI "\fBprecompile_stamp\fP"
.br
.ti -1c
.RI "\fBactions_stamp\fP"
.br
.ti -1c
.RI "\fBbinary\fP"
.br
.ti -1c
.RI "\fBbundle\fP"
.br
.ti -1c
.RI "\fBcomponent_objs\fP"
.br
.ti -1c
.RI "\fBcompile_deps\fP"
.br
.ti -1c
.RI "\fBimport_lib\fP"
.br
.ti -1c
.RI "\fBuses_cpp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Target represents the paths used within a single gyp target\&.

Conceptually, building a single target A is a series of steps:

1) actions/rules/copies  generates source/resources/etc\&.
2) compiles              generates \&.o files
3) link                  generates a binary (library/executable)
4) bundle                merges the above in a mac bundle

(Any of these steps can be optional\&.)

From a build ordering perspective, a dependent target B could just
depend on the last output of this series of steps\&.

But some dependent commands sometimes need to reach inside the box\&.
For example, when linking B it needs to get the path to the static
library generated by A\&.

This object stores those paths\&.  To keep things simple, member
variables only store concrete paths to single files, while methods
compute derived values like 'the last output of the target'\&.

.fi
.PP
 
.PP
Definition at line \fB101\fP of file \fBninja\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.generator\&.ninja\&.Target\&.__init__ ( self,  type)"

.PP
Definition at line \fB125\fP of file \fBninja\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.generator\&.ninja\&.Target\&.FinalOutput ( self)"

.PP
.nf
Return the last output of the target, which depends on all prior
steps\&.
.fi
.PP
 
.PP
Definition at line \fB182\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.Linkable ( self)"

.PP
.nf
Return true if this is a target that can be linked against\&.
.fi
.PP
 
.PP
Definition at line \fB156\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.PreActionInput ( self,  flavor)"

.PP
.nf
Return the path, if any, that should be used as a dependency of
any dependent action step\&.
.fi
.PP
 
.PP
Definition at line \fB170\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.PreCompileInput ( self)"

.PP
.nf
Return the path, if any, that should be used as a dependency of
any dependent compile step\&.
.fi
.PP
 
.PP
Definition at line \fB177\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.UsesToc ( self,  flavor)"

.PP
.nf
Return true if the target should produce a restat rule based on a TOC
file\&.
.fi
.PP
 
.PP
Definition at line \fB160\fP of file \fBninja\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.generator\&.ninja\&.Target\&.actions_stamp"

.PP
Definition at line \fB135\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.binary"

.PP
Definition at line \fB137\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.bundle"

.PP
Definition at line \fB140\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.compile_deps"

.PP
Definition at line \fB147\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.component_objs"

.PP
Definition at line \fB146\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.import_lib"

.PP
Definition at line \fB151\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.preaction_stamp"

.PP
Definition at line \fB130\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.precompile_stamp"

.PP
Definition at line \fB133\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.type"

.PP
Definition at line \fB127\fP of file \fBninja\&.py\fP\&.
.SS "gyp\&.generator\&.ninja\&.Target\&.uses_cpp"

.PP
Definition at line \fB154\fP of file \fBninja\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
