.TH "gyp.ninja_syntax.Writer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.ninja_syntax.Writer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBoutput\fP, \fBwidth\fP=78)"
.br
.ti -1c
.RI "\fBnewline\fP (self)"
.br
.ti -1c
.RI "\fBcomment\fP (self, text)"
.br
.ti -1c
.RI "\fBvariable\fP (self, key, value, indent=0)"
.br
.ti -1c
.RI "\fBpool\fP (self, name, depth)"
.br
.ti -1c
.RI "\fBrule\fP (self, name, command, description=None, depfile=None, generator=False, \fBpool\fP=None, restat=False, rspfile=None, rspfile_content=None, deps=None)"
.br
.ti -1c
.RI "\fBbuild\fP (self, outputs, \fBrule\fP, inputs=None, implicit=None, order_only=None, variables=None)"
.br
.ti -1c
.RI "\fBinclude\fP (self, path)"
.br
.ti -1c
.RI "\fBsubninja\fP (self, path)"
.br
.ti -1c
.RI "\fBdefault\fP (self, paths)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoutput\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_count_dollars_before_index\fP (self, s, i)"
.br
.ti -1c
.RI "\fB_line\fP (self, text, indent=0)"
.br
.ti -1c
.RI "\fB_as_list\fP (self, input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBninja_syntax\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.ninja_syntax\&.Writer\&.__init__ ( self,  output,  width = \fR78\fP)"

.PP
Definition at line \fB20\fP of file \fBninja_syntax\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.ninja_syntax\&.Writer\&._as_list ( self,  input)\fR [protected]\fP"

.PP
Definition at line \fB161\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&._count_dollars_before_index ( self,  s,  i)\fR [protected]\fP"

.PP
.nf
Returns the number of '$' characters right in front of s[i]\&.
.fi
.PP
 
.PP
Definition at line \fB115\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&._line ( self,  text,  indent = \fR0\fP)\fR [protected]\fP"

.PP
.nf
Write 'text' word-wrapped at self\&.width characters\&.
.fi
.PP
 
.PP
Definition at line \fB124\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.build ( self,  outputs,  rule,  inputs = \fRNone\fP,  implicit = \fRNone\fP,  order_only = \fRNone\fP,  variables = \fRNone\fP)"

.PP
Definition at line \fB74\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.comment ( self,  text)"

.PP
Definition at line \fB27\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.default ( self,  paths)"

.PP
Definition at line \fB112\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.include ( self,  path)"

.PP
Definition at line \fB106\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.newline ( self)"

.PP
Definition at line \fB24\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.pool ( self,  name,  depth)"

.PP
Definition at line \fB38\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.rule ( self,  name,  command,  description = \fRNone\fP,  depfile = \fRNone\fP,  generator = \fRFalse\fP,  pool = \fRNone\fP,  restat = \fRFalse\fP,  rspfile = \fRNone\fP,  rspfile_content = \fRNone\fP,  deps = \fRNone\fP)"

.PP
Definition at line \fB42\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.subninja ( self,  path)"

.PP
Definition at line \fB109\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.variable ( self,  key,  value,  indent = \fR0\fP)"

.PP
Definition at line \fB31\fP of file \fBninja_syntax\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.ninja_syntax\&.Writer\&.output"

.PP
Definition at line \fB21\fP of file \fBninja_syntax\&.py\fP\&.
.SS "gyp\&.ninja_syntax\&.Writer\&.width"

.PP
Definition at line \fB22\fP of file \fBninja_syntax\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
