.TH "gyp.generator.analyzer.Target" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.analyzer.Target
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBname\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdeps\fP"
.br
.ti -1c
.RI "\fBmatch_status\fP"
.br
.ti -1c
.RI "\fBback_deps\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBvisited\fP"
.br
.ti -1c
.RI "\fBrequires_build\fP"
.br
.ti -1c
.RI "\fBadded_to_compile_targets\fP"
.br
.ti -1c
.RI "\fBin_roots\fP"
.br
.ti -1c
.RI "\fBis_executable\fP"
.br
.ti -1c
.RI "\fBis_static_library\fP"
.br
.ti -1c
.RI "\fBis_or_has_linked_ancestor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Holds information about a particular target:
deps: set of Targets this Target depends upon\&. This is not recursive, only the
direct dependent Targets\&.
match_status: one of the MatchStatus values\&.
back_deps: set of Targets that have a dependency on this Target\&.
visited: used during iteration to indicate whether we've visited this target\&.
This is used for two iterations, once in building the set of Targets and
again in _GetBuildTargets()\&.
name: fully qualified name of the target\&.
requires_build: True if the target type is such that it needs to be built\&.
See _DoesTargetTypeRequireBuild for details\&.
added_to_compile_targets: used when determining if the target was added to the
set of targets that needs to be built\&.
in_roots: true if this target is a descendant of one of the root nodes\&.
is_executable: true if the type of target is executable\&.
is_static_library: true if the type of target is static_library\&.
is_or_has_linked_ancestor: true if the target does a link (eg executable), or
if there is a target in back_deps that does a link\&.
.fi
.PP
 
.PP
Definition at line \fB218\fP of file \fBanalyzer\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.generator\&.analyzer\&.Target\&.__init__ ( self,  name)"

.PP
Definition at line \fB238\fP of file \fBanalyzer\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.generator\&.analyzer\&.Target\&.added_to_compile_targets"

.PP
Definition at line \fB247\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.back_deps"

.PP
Definition at line \fB241\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.deps"

.PP
Definition at line \fB239\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.in_roots"

.PP
Definition at line \fB248\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.is_executable"

.PP
Definition at line \fB249\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.is_or_has_linked_ancestor"

.PP
Definition at line \fB251\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.is_static_library"

.PP
Definition at line \fB250\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.match_status"

.PP
Definition at line \fB240\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.name"

.PP
Definition at line \fB242\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.requires_build"

.PP
Definition at line \fB246\fP of file \fBanalyzer\&.py\fP\&.
.SS "gyp\&.generator\&.analyzer\&.Target\&.visited"

.PP
Definition at line \fB245\fP of file \fBanalyzer\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
