.TH "gyp.MSVSSettings._String" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSSettings._String
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.MSVSSettings\&._Type\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidateMSVS\fP (self, value)"
.br
.ti -1c
.RI "\fBValidateMSBuild\fP (self, value)"
.br
.ti -1c
.RI "\fBConvertToMSBuild\fP (self, value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A setting that's just a string\&.
.fi
.PP
 
.PP
Definition at line \fB105\fP of file \fBMSVSSettings\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSSettings\&._String\&.ConvertToMSBuild ( self,  value)"

.PP
.nf
Returns the MSBuild equivalent of the MSVS value given\&.

Args:
value: the MSVS value to convert\&.

Returns:
the MSBuild equivalent\&.

Raises:
ValueError if value is not valid\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB116\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._String\&.ValidateMSBuild ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSBuild\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSBuild\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB112\fP of file \fBMSVSSettings\&.py\fP\&.
.SS "gyp\&.MSVSSettings\&._String\&.ValidateMSVS ( self,  value)"

.PP
.nf
Verifies that the value is legal for MSVS\&.

Args:
value: the value to check for this type\&.

Raises:
ValueError if value is not valid for MSVS\&.

.fi
.PP
 
.PP
Reimplemented from \fBgyp\&.MSVSSettings\&._Type\fP\&.
.PP
Definition at line \fB108\fP of file \fBMSVSSettings\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
