.TH "gyp.xcodeproj_file.XCBuildPhase" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.xcodeproj_file.XCBuildPhase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Inherited by \fBgyp\&.xcodeproj_file\&.PBXCopyFilesBuildPhase\fP, \fBgyp\&.xcodeproj_file\&.PBXFrameworksBuildPhase\fP, \fBgyp\&.xcodeproj_file\&.PBXHeadersBuildPhase\fP, \fBgyp\&.xcodeproj_file\&.PBXResourcesBuildPhase\fP, \fBgyp\&.xcodeproj_file\&.PBXShellScriptBuildPhase\fP, and \fBgyp\&.xcodeproj_file\&.PBXSourcesBuildPhase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, properties=None, \fBid\fP=None, \fBparent\fP=None)"
.br
.ti -1c
.RI "\fBFileGroup\fP (self, path)"
.br
.ti -1c
.RI "\fBAppendBuildFile\fP (self, pbxbuildfile, path=None)"
.br
.ti -1c
.RI "\fBAddFile\fP (self, path, settings=None)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB__repr__\fP (self)"
.br
.ti -1c
.RI "\fBCopy\fP (self)"
.br
.ti -1c
.RI "\fBName\fP (self)"
.br
.ti -1c
.RI "\fBComment\fP (self)"
.br
.ti -1c
.RI "\fBHashables\fP (self)"
.br
.ti -1c
.RI "\fBHashablesForChild\fP (self)"
.br
.ti -1c
.RI "\fBComputeIDs\fP (self, recursive=True, overwrite=True, seed_hash=None)"
.br
.ti -1c
.RI "\fBEnsureNoIDCollisions\fP (self)"
.br
.ti -1c
.RI "\fBChildren\fP (self)"
.br
.ti -1c
.RI "\fBDescendants\fP (self)"
.br
.ti -1c
.RI "\fBPBXProjectAncestor\fP (self)"
.br
.ti -1c
.RI "\fBPrint\fP (self, file=sys\&.stdout)"
.br
.ti -1c
.RI "\fBUpdateProperties\fP (self, properties, do_copy=False)"
.br
.ti -1c
.RI "\fBHasProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBGetProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBSetProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBDelProperty\fP (self, key)"
.br
.ti -1c
.RI "\fBAppendProperty\fP (self, key, value)"
.br
.ti -1c
.RI "\fBVerifyHasRequiredProperties\fP (self)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_AddPathToDict\fP (self, pbxbuildfile, path)"
.br
.ti -1c
.RI "\fB_AddBuildFileToDicts\fP (self, pbxbuildfile, path=None)"
.br
.in -1c

Protected Member Functions inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_EncodeComment\fP (self, comment)"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP (self, match)"
.br
.ti -1c
.RI "\fB_EncodeString\fP (self, value)"
.br
.ti -1c
.RI "\fB_XCPrint\fP (self, file, tabs, line)"
.br
.ti -1c
.RI "\fB_XCPrintableValue\fP (self, tabs, value, flatten_list=False)"
.br
.ti -1c
.RI "\fB_XCKVPrint\fP (self, file, tabs, key, value)"
.br
.ti -1c
.RI "\fB_SetDefaultsFromSchema\fP (self)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_files_by_path\fP"
.br
.ti -1c
.RI "\fB_files_by_xcfilelikeelement\fP"
.br
.in -1c

Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fB_properties\fP"
.br
.ti -1c
.RI "\fB_hashables\fP"
.br
.ti -1c
.RI "\fB_EncodeTransform\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_schema\fP = XCObject\&._schema\&.copy()"
.br
.in -1c

Static Protected Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "dict \fB_schema\fP = {}"
.br
.ti -1c
.RI "bool \fB_should_print_single_line\fP = False"
.br
.ti -1c
.RI "list \fB_encode_transforms\fP = []"
.br
.ti -1c
.RI "\fB_alternate_encode_transforms\fP = list(\fB_encode_transforms\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.in -1c

Static Public Attributes inherited from \fBgyp\&.xcodeproj_file\&.XCObject\fP
.in +1c
.ti -1c
.RI "int \fBi\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Abstract base for build phase classes\&.  Not represented in a project
file\&.

Attributes:
_files_by_path: A dict mapping each path of a child in the files list by
  path (keys) to the corresponding PBXBuildFile children (values)\&.
_files_by_xcfilelikeelement: A dict mapping each XCFileLikeElement (keys)
  to the corresponding PBXBuildFile children (values)\&.

.fi
.PP
 
.PP
Definition at line \fB1839\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&.__init__ ( self,  properties = \fRNone\fP,  id = \fRNone\fP,  parent = \fRNone\fP)"

.PP
Reimplemented from \fBgyp\&.xcodeproj_file\&.XCObject\fP\&.
.PP
Definition at line \fB1867\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&._AddBuildFileToDicts ( self,  pbxbuildfile,  path = \fRNone\fP)\fR [protected]\fP"

.PP
.nf
Maintains the _files_by_path and _files_by_xcfilelikeelement dicts\&.

If path is specified, then it is the path that is being added to the
phase, and pbxbuildfile must contain either a PBXFileReference directly
referencing that path, or it must contain a PBXVariantGroup that itself
contains a PBXFileReference referencing the path\&.

If path is not specified, either the PBXFileReference's path or the paths
of all children of the PBXVariantGroup are taken as being added to the
phase\&.

If the path is already present in the phase, raises an exception\&.

If the PBXFileReference or PBXVariantGroup referenced by pbxbuildfile
are already present in the phase, referenced by a different PBXBuildFile
object, raises an exception\&.  This does not raise an exception when
a PBXFileReference or PBXVariantGroup reappear and are referenced by the
same PBXBuildFile that has already introduced them, because in the case
of PBXVariantGroup objects, they may correspond to multiple paths that are
not all added simultaneously\&.  When this situation occurs, the path needs
to be added to _files_by_path, but nothing needs to change in
_files_by_xcfilelikeelement, and the caller should have avoided adding
the PBXBuildFile if it is already present in the list of children\&.

.fi
.PP
 
.PP
Definition at line \fB1894\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&._AddPathToDict ( self,  pbxbuildfile,  path)\fR [protected]\fP"

.PP
.nf
Adds path to the dict tracking paths belonging to this build phase\&.

If the path is already a member of this build phase, raises an exception\&.

.fi
.PP
 
.PP
Definition at line \fB1884\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&.AddFile ( self,  path,  settings = \fRNone\fP)"

.PP
Definition at line \fB1962\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&.AppendBuildFile ( self,  pbxbuildfile,  path = \fRNone\fP)"

.PP
Definition at line \fB1953\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&.FileGroup ( self,  path)"

.PP
Reimplemented in \fBgyp\&.xcodeproj_file\&.PBXFrameworksBuildPhase\fP, \fBgyp\&.xcodeproj_file\&.PBXHeadersBuildPhase\fP, \fBgyp\&.xcodeproj_file\&.PBXResourcesBuildPhase\fP, and \fBgyp\&.xcodeproj_file\&.PBXSourcesBuildPhase\fP\&.
.PP
Definition at line \fB1876\fP of file \fBxcodeproj_file\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&._files_by_path\fR [protected]\fP"

.PP
Definition at line \fB1871\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&._files_by_xcfilelikeelement\fR [protected]\fP"

.PP
Definition at line \fB1872\fP of file \fBxcodeproj_file\&.py\fP\&.
.SS "gyp\&.xcodeproj_file\&.XCBuildPhase\&._schema = XCObject\&._schema\&.copy()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB1858\fP of file \fBxcodeproj_file\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
