.TH "gyp.generator.xcode_test.TestEscapeXcodeDefine" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.generator.xcode_test.TestEscapeXcodeDefine
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_InheritedRemainsUnescaped\fP (self)"
.br
.ti -1c
.RI "\fBtest_Escaping\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBxcode_test\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.generator\&.xcode_test\&.TestEscapeXcodeDefine\&.test_Escaping ( self)"

.PP
Definition at line \fB20\fP of file \fBxcode_test\&.py\fP\&.
.SS "gyp\&.generator\&.xcode_test\&.TestEscapeXcodeDefine\&.test_InheritedRemainsUnescaped ( self)"

.PP
Definition at line \fB17\fP of file \fBxcode_test\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
