.TH "gyp.MSVSNew.MSVSFolder" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gyp.MSVSNew.MSVSFolder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgyp\&.MSVSNew\&.MSVSSolutionEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBpath\fP, \fBname\fP=None, \fBentries\fP=None, \fBguid\fP=None, \fBitems\fP=None)"
.br
.ti -1c
.RI "\fBget_guid\fP (self)"
.br
.in -1c

Public Member Functions inherited from \fBgyp\&.MSVSNew\&.MSVSSolutionEntry\fP
.in +1c
.ti -1c
.RI "\fB__cmp__\fP (self, other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBguid\fP"
.br
.ti -1c
.RI "\fBentries\fP"
.br
.ti -1c
.RI "\fBitems\fP"
.br
.ti -1c
.RI "\fBentry_type_guid\fP"
.br
.in -1c

Public Attributes inherited from \fBgyp\&.MSVSNew\&.MSVSSolutionEntry\fP
.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Folder in a Visual Studio project or solution\&.
.fi
.PP
 
.PP
Definition at line \fB75\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSFolder\&.__init__ ( self,  path,  name = \fRNone\fP,  entries = \fRNone\fP,  guid = \fRNone\fP,  items = \fRNone\fP)"

.PP
.nf
Initializes the folder\&.

Args:
path: Full path to the folder\&.
name: Name of the folder\&.
entries: List of folder entries to nest inside this folder\&.  May contain
  Folder or Project objects\&.  May be None, if the folder is empty\&.
guid: GUID to use for folder, if not None\&.
items: List of solution items to include in the folder project\&.  May be
  None, if the folder does not directly contain items\&.

.fi
.PP
 
.PP
Definition at line \fB78\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSFolder\&.get_guid ( self)"

.PP
Definition at line \fB105\fP of file \fBMSVSNew\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "gyp\&.MSVSNew\&.MSVSFolder\&.entries"

.PP
Definition at line \fB100\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSFolder\&.entry_type_guid"

.PP
Definition at line \fB103\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSFolder\&.guid"

.PP
Definition at line \fB97\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSFolder\&.items"

.PP
Definition at line \fB101\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSFolder\&.name"

.PP
Definition at line \fB91\fP of file \fBMSVSNew\&.py\fP\&.
.SS "gyp\&.MSVSNew\&.MSVSFolder\&.path"

.PP
Definition at line \fB96\fP of file \fBMSVSNew\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
