.TH "Views/dashboard/index.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views/dashboard/index.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$username\fP = $_SESSION['name']"
.br
.ti -1c
.RI "\fB$name\fP = $_SESSION['fullname']"
.br
.ti -1c
.RI "\fB$email\fP = $_SESSION['email']"
.br
.ti -1c
.RI "if(! $username) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$email = $_SESSION['email']"

.PP
Definition at line \fB11\fP of file \fBindex\&.php\fP\&.
.SS "$name = $_SESSION['fullname']"

.PP
Definition at line \fB10\fP of file \fBindex\&.php\fP\&.
.SS "$username = $_SESSION['name']"
Author: Milton Vafana Email : miltonhyndrex@gmail.com Github: https://github.com/nia-cloud-official 
.PP
Definition at line \fB9\fP of file \fBindex\&.php\fP\&.
.SS "if (! $username) else"
\fBInitial value:\fP
.nf
{
    $username = $_SESSION['name']
.PP
.fi

.PP
Definition at line \fB15\fP of file \fBindex\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
