.TH "Views/logout.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views/logout.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$loginPageUrl\fP = '\&./login\&.php'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$loginPageUrl = '\&./login\&.php'"

.PP
Definition at line \fB3\fP of file \fBlogout\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
