.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/mac_tool.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/mac_tool.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.mac_tool\&.MacTool\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.mac_tool\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.mac_tool\&.main\fP (args)"
.br
.ti -1c
.RI "\fBgyp\&.mac_tool\&.NextGreaterPowerOf2\fP (x)"
.br
.ti -1c
.RI "\fBgyp\&.mac_tool\&.WriteHmap\fP (output_name, filelist)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
