.TH "major.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
major.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBaddData\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$servername\fP = 'localhost'"
.br
.ti -1c
.RI "\fB$username\fP = 'root'"
.br
.ti -1c
.RI "\fB$password\fP = ''"
.br
.ti -1c
.RI "\fB$dbname\fP = 'academy'"
.br
.ti -1c
.RI "\fB$conn\fP = new mysqli($servername, $username, $password, $dbname)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "addData ()"

.PP
Definition at line \fB11\fP of file \fBmajor\&.php\fP\&.
.SH "Variable Documentation"
.PP 
.SS "$conn = new mysqli($servername, $username, $password, $dbname)"

.PP
Definition at line \fB8\fP of file \fBmajor\&.php\fP\&.
.SS "$dbname = 'academy'"

.PP
Definition at line \fB6\fP of file \fBmajor\&.php\fP\&.
.SS "$password = ''"

.PP
Definition at line \fB5\fP of file \fBmajor\&.php\fP\&.
.SS "$servername = 'localhost'"

.PP
Definition at line \fB3\fP of file \fBmajor\&.php\fP\&.
.SS "$username = 'root'"

.PP
Definition at line \fB4\fP of file \fBmajor\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
