.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.generator\&.make\&.MakefileWriter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\&.make\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.CalculateVariables\fP (default_variables, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.CalculateGeneratorInputInfo\fP (params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.WriteRootHeaderSuffixRules\fP (writer)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.Compilable\fP (filename)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.Linkable\fP (filename)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.Target\fP (filename)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.EscapeShellArgument\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.EscapeMakeVariableExpansion\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.EscapeCppDefine\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.QuoteIfNecessary\fP (string)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.StringToMakefileVariable\fP (string)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.Sourceify\fP (path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.QuoteSpaces\fP (s, quote=r'\\ ')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.SourceifyAndQuoteSpaces\fP (path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.WriteAutoRegenerationRule\fP (params, root_makefile, makefile_name, build_files)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.PerformBuild\fP (data, configurations, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.GenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBgyp\&.generator\&.make\&.generator_default_variables\fP"
.br
.ti -1c
.RI "bool \fBgyp\&.generator\&.make\&.generator_supports_multiple_toolsets\fP = True"
.br
.ti -1c
.RI "bool \fBgyp\&.generator\&.make\&.generator_wants_sorted_dependencies\fP = False"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.make\&.generator_additional_non_configuration_keys\fP = []"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.make\&.generator_additional_path_sections\fP = []"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.make\&.generator_extra_sources_for_rules\fP = []"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.make\&.generator_filelist_paths\fP = None"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.SPACE_REPLACEMENT\fP = '?'"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.LINK_COMMANDS_LINUX\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.LINK_COMMANDS_MAC\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.LINK_COMMANDS_ANDROID\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.LINK_COMMANDS_AIX\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.LINK_COMMANDS_OS390\fP"
.br
.ti -1c
.RI "tuple \fBgyp\&.generator\&.make\&.SHARED_HEADER\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.SHARED_HEADER_MAC_COMMANDS\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.SHARED_HEADER_SUFFIX_RULES_COMMENT1\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.SHARED_HEADER_SUFFIX_RULES_COMMENT2\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.SHARED_FOOTER\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.header\fP"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.make\&.COMPILABLE_EXTENSIONS\fP"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.make\&.srcdir_prefix\fP = ''"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.make\&.target_outputs\fP = {}"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.make\&.target_link_deps\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
