.TH "md_backend_2node__modules_2es-define-property_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2es-define-property_2_r_e_a_d_m_e \- es-define-property \*{\fR\fP\*}  
.PP
 \fR\fP \fR\fP [][license-url] \fR\fP
.PP
\fR\fP.PP
\fRObject\&.defineProperty\fP, but not IE 8's broken one\&.
.SH "Example"
.PP
.PP
.nf
const assert = require('assert');

const $defineProperty = require('es\-define\-property');

if ($defineProperty) {
    assert\&.equal($defineProperty, Object\&.defineProperty);
} else if (Object\&.defineProperty) {
    assert\&.equal($defineProperty, false, 'this is IE 8');
} else {
    assert\&.equal($defineProperty, false, 'this is an ES3 engine');
}
.fi
.PP
.SH "Tests"
.PP
Simply clone the repo, \fRnpm install\fP, and run \fRnpm test\fP
.SH "Security"
.PP
Please email \fR@ljharb\fP or see https://tidelift.com/security if you have a potential security vulnerability to report\&. 
