.TH "md_backend_2node__modules_2humanize-ms_2_history" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2humanize-ms_2_history \- 1\&.2\&.1 / 2017-05-19 
.PP

.IP "\(bu" 2
fix: package\&.json to reduce vulnerabilities (#3)
.PP
.SH "1\&.2\&.0 / 2016-05-21"
.PP
.IP "\(bu" 2
feat: warn with stack
.PP
.SH "1\&.1\&.0 / 2016-04-04"
.PP
.IP "\(bu" 2
deps: upgrade ms to 0\&.7\&.0
.PP
.SH "1\&.0\&.1 / 2014-12-31"
.PP
.IP "\(bu" 2
feat(index\&.js): warn when result is undefined
.PP
.SH "1\&.0\&.0 / 2014-08-14"
.PP
.IP "\(bu" 2
init 
.PP

