.TH "md_backend_2node__modules_2nopt_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2nopt_2_c_h_a_n_g_e_l_o_g \- v4\&.0\&.1 (2016-12-14) 
.PP
 
.SS "WHOOPS"
.IP "\(bu" 2
\fR\fRfb9b1ce\fP\fP Merged so many patches at once that the code fencing (\fR@adius\fP) added got broken\&. Sorry, (\fR@adius\fP)! (\fR@othiym23\fP)
.PP
.SS "v4\&.0\&.0 (2016-12-13)"
.SS "BREAKING CHANGES"
.IP "\(bu" 2
\fR\fR651d447\fP\fP When parsing String-typed arguments, if the next value is \fR''\fP, don't simply swallow it\&. (\fR@samjonester\fP)
.PP
.SS "PERFORMANCE TWEAKS"
.IP "\(bu" 2
\fR\fR3370ce8\fP\fP Simplify initialization\&. (\fR@elidoran\fP)
.IP "\(bu" 2
\fR\fR356e58e\fP\fP Store \fRArray\&.isArray(types[arg])\fP for reuse\&. (\fR@elidoran\fP)
.IP "\(bu" 2
\fR\fR0d95e90\fP\fP Interpret single-item type arrays as a single type\&. (\fR@samjonester\fP)
.IP "\(bu" 2
\fR\fR07c69d3\fP\fP Simplify key-value extraction\&. (\fR@elidoran\fP)
.IP "\(bu" 2
\fR\fR39b6e5c\fP\fP Only call \fRDate\&.parse(val)\fP once\&. (\fR@elidoran\fP)
.IP "\(bu" 2
\fR\fR934943d\fP\fP Use \fRosenv\&.home()\fP to find a user's home directory instead of assuming it's always \fR$HOME\fP\&. (\fR@othiym23\fP)
.PP
.SS "TEST & CI IMPROVEMENTS"
.IP "\(bu" 2
\fR\fR326ffff\fP\fP Fix \fR/tmp\fP test to work on Windows\&. (\fR@elidoran\fP)
.IP "\(bu" 2
\fR\fRc89d31a\fP\fP Only run Windows tests on Windows, only run Unix tests on a Unix\&. (\fR@elidoran\fP)
.IP "\(bu" 2
\fR\fRaffd3d1\fP\fP Refresh Travis to run the tests against the currently-supported batch of npm versions\&. (\fR@helio\fP-frota)
.IP "\(bu" 2
\fR\fR55f9449\fP\fP \fRtap@8\&.0\&.1\fP (\fR@othiym23\fP)
.PP
.SS "DOC TWEAKS"
.IP "\(bu" 2
\fR\fR5271229\fP\fP Use JavaScript code block for syntax highlighting\&. (\fR@adius\fP)
.IP "\(bu" 2
\fR\fRc0d156f\fP\fP The code sample in the README had \fRmany2: [ oneThing ]\fP, and now it has \fRmany2: [ two, things ]\fP\&. (\fR@silkentrance\fP) 
.PP

