.TH "md_backend_2node__modules_2node-gyp_2mac_o_s___catalina" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2node-gyp_2mac_o_s___catalina \- Installation notes for macOS Catalina (v10\&.15) 
.PP
 \fIThis document specifically refers to upgrades from previous versions of macOS to Catalina (10\&.15)\&. It should be removed from the source repository when Catalina ceases to be the latest macOS version or when future Catalina versions no longer raise these issues\&.\fP
.PP
\fBBoth upgrading to macOS Catalina and running a Software Update in Catalina may cause normal \fRnode-gyp\fP installations to fail\&. This might manifest as the following error during \fRnpm install\fP:\fP
.PP
.PP
.nf
gyp: No Xcode or CLT version detected!
.fi
.PP
.SH "node-gyp v7"
.PP
The newest release of \fRnode-gyp\fP should solve this problem\&. If you are using \fRnode-gyp\fP directly then you should be able to install v7 and use it as-is\&.
.PP
If you need to use \fRnode-gyp\fP from within \fRnpm\fP (e\&.g\&. through \fRnpm install\fP), you will have to install \fRnode-gyp\fP (either globally with \fR-g\fP or to a predictable location) and tell \fRnpm\fP where the new version is\&. Either use:
.PP
.IP "\(bu" 2
\fRnpm config set node_gyp <path to node-gyp>\fP; or
.IP "\(bu" 2
run \fRnpm\fP with an environment variable prefix: \fRnpm_config_node_gyp=<path to node-gyp> npm install\fP
.PP
.PP
Where 'path to node-gyp' is to the \fRnode-gyp\fP executable which may be a symlink in your global bin directory (e\&.g\&. \fR/usr/local/bin/node-gyp\fP), or a path to the \fRnode-gyp\fP installation directory and the \fRbin/node-gyp\&.js\fP file within it (e\&.g\&. \fR/usr/local/lib/node_modules/node-gyp/bin/node-gyp\&.js\fP)\&.
.PP
\fBIf you use \fRnpm config set\fP to change your global \fRnode_gyp\fP you are responsible for keeping it up to date and can't rely on \fRnpm\fP to give you a newer version when available\&.\fP Use \fRnpm config delete node_gyp\fP to unset this configuration option\&.
.SH "Fixing Catalina for older versions of \fRnode-gyp\fP"
.PP
.SS "Is my Mac running macOS Catalina?"
Let's first make sure that your Mac is running Catalina: 
.PP
.nf
% sw_vers
    ProductName:    Mac OS X
    ProductVersion: 10\&.15
    BuildVersion:   19A602

.fi
.PP
 If \fRProductVersion\fP is less then \fR10\&.15\fP then this document is not for you\&. Normal install docs for \fRnode-gyp\fP on macOS can be found at https://github.com/nodejs/node-gyp#on-macos
.SS "The acid test"
To see if \fRXcode Command Line Tools\fP is installed in a way that will work with \fRnode-gyp\fP, run: 
.PP
.nf
curl \-sL https://github\&.com/nodejs/node\-gyp/raw/master/macOS_Catalina_acid_test\&.sh | bash

.fi
.PP
.PP
If test succeeded, \fIyou are done\fP! You should be ready to \fRinstall\fP \fRnode-gyp\fP\&.
.PP
If test failed, there is a problem with your Xcode Command Line Tools installation\&. \fBContinue to Solutions\fP\&.
.SS "Solutions"
There are three ways to install the Xcode libraries \fRnode-gyp\fP needs on macOS\&. People running Catalina have had success with some but not others in a way that has been unpredictable\&.
.PP
.IP "1." 4
With the full Xcode (~7\&.6 GB download) from the \fRApp Store\fP app\&.
.IP "2." 4
With the \fImuch\fP smaller Xcode Command Line Tools via \fRxcode-select --install\fP
.IP "3." 4
With the \fImuch\fP smaller Xcode Command Line Tools via manual download\&. \fBFor people running the latest version of Catalina (10\&.15\&.2 at the time of this writing), this has worked when the other two solutions haven't\&.\fP
.PP
.SS "Installing \fRnode-gyp\fP using the full Xcode"
.IP "1." 4
\fRxcodebuild -version\fP should show \fRXcode 11\&.1\fP or later\&.
.IP "  \(bu" 4
If not, then install/upgrade Xcode from the App Store app\&.
.PP

.IP "2." 4
Open the Xcode app and\&.\&.\&.
.IP "  \(bu" 4
Under \fBPreferences > Locations\fP select the tools if their location is empty\&.
.IP "  \(bu" 4
Allow Xcode app to do an essential install of the most recent compiler tools\&.
.PP

.IP "3." 4
Once all installations are \fIcomplete\fP, quit out of Xcode\&.
.IP "4." 4
\fRsudo xcodebuild -license accept\fP # If you agree with the licensing terms\&.
.IP "5." 4
\fRsoftwareupdate -l\fP # No listing is a good sign\&.
.IP "  \(bu" 4
If Xcode or Tools upgrades are listed, use 'Software Upgrade' to install them\&.
.PP

.IP "6." 4
\fRxcode-select -version\fP # Should return \fRxcode-select version 2370\fP or later\&.
.IP "7." 4
\fRxcode-select -print-path\fP # Should return \fR/Applications/Xcode\&.app/Contents/Developer\fP
.IP "8." 4
Try the \fB_acid test_ steps above\fP to see if your Mac is ready\&.
.IP "9." 4
If the \fIacid test\fP does \fInot\fP pass then\&.\&.\&.
.IP "10." 4
\fRsudo xcode-select --reset\fP # Enter root password\&. No output is normal\&.
.IP "11." 4
Repeat step 7 above\&. Is the path different this time? Repeat the \fIacid test\fP\&.
.PP
.SS "Installing \fRnode-gyp\fP using the Xcode Command Line Tools via \fRxcode-select --install\fP"
.IP "1." 4
If the \fIacid test\fP has not succeeded, then try \fRxcode-select --install\fP
.IP "2." 4
If the installation command returns \fRxcode-select: error: command line tools are already installed, use 'Software Update' to install updates\fP, continue to \fBremove and reinstall\fP
.IP "3." 4
Wait until the install process is \fIcomplete\fP\&.
.IP "4." 4
\fRsoftwareupdate -l\fP # No listing is a good sign\&.
.IP "  \(bu" 4
If Xcode or Tools upgrades are listed, use 'Software Update' to install them\&.
.PP

.IP "5." 4
\fRxcode-select -version\fP # Should return \fRxcode-select version 2370\fP or later\&.
.IP "6." 4
\fRxcode-select -print-path\fP # Should return \fR/Library/Developer/CommandLineTools\fP
.IP "7." 4
Try the \fB_acid test_ steps above\fP to see if your Mac is ready\&.
.IP "8." 4
If the \fIacid test\fP does \fInot\fP pass then\&.\&.\&.
.IP "9." 4
\fRsudo xcode-select --reset\fP # Enter root password\&. No output is normal\&.
.IP "10." 4
Repeat step 5 above\&. Is the path different this time? Repeat the \fIacid test\fP\&.
.PP
.SS "Installing \fRnode-gyp\fP using the Xcode Command Line Tools via manual download"
.IP "1." 4
Download the appropriate version of the 'Command Line Tools for Xcode' for your version of Catalina from https://developer.apple.com/download/more/\&. As of MacOS 10\&.15\&.5, that's \fRCommand_Line_Tools_for_Xcode_11\&.5\&.dmg\fP
.IP "2." 4
Install the package\&.
.IP "3." 4
Run the \fB_acid test_ steps above\fP\&.
.PP
.SS "I did all that and the acid test still does not pass :-("
.IP "1." 4
\fRsudo rm -rf $(xcode-select -print-path)\fP # Enter root password\&. No output is normal\&.
.IP "2." 4
\fRsudo rm -rf /Library/Developer/CommandLineTools\fP # Enter root password\&.
.IP "3." 4
\fRsudo xcode-select --reset\fP
.IP "4." 4
\fRxcode-select --install\fP
.IP "5." 4
If the \fB_acid test_ steps above\fP still does \fInot\fP pass then\&.\&.\&.
.IP "6." 4
\fRnpm explore npm -g -- npm install node-gyp@latest\fP
.IP "7." 4
\fRnpm explore npm -g -- npm explore npm-lifecycle -- npm install node-gyp@latest\fP
.IP "8." 4
If the \fIacid test\fP still does \fInot\fP pass then\&.\&.\&.
.IP "9." 4
Add a comment to https://github.com/nodejs/node-gyp/issues/1927 so we can improve\&.
.PP
.PP
Lessons learned from:
.IP "\(bu" 2
https://github.com/nodejs/node-gyp/issues/1779
.IP "\(bu" 2
https://github.com/nodejs/node-gyp/issues/1861
.IP "\(bu" 2
https://github.com/nodejs/node-gyp/issues/1927 and elsewhere
.IP "\(bu" 2
Thanks to @rrrix for discovering Solution 3 
.PP

