.TH "md_backend_2node__modules_2strip-json-comments_2readme" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2strip-json-comments_2readme \- strip-json-comments \fR\fP 
.PP
 
.PP
.RS 4
Strip comments from JSON\&. Lets you use comments in your JSON files! 
.RE
.PP
.PP
This is now possible:
.PP
.PP
.nf
{
    // rainbows
    "unicorn": /* ❤ */ "cake"
}
.fi
.PP
.PP
It will replace single-line comments \fR//\fP and multi-line comments \fR/**/\fP with whitespace\&. This allows JSON error positions to remain as close as possible to the original source\&.
.PP
Also available as a \fRgulp\fP/\fRgrunt\fP/\fRbroccoli\fP plugin\&.
.SH "Install"
.PP
.PP
.nf
$ npm install \-\-save strip\-json\-comments
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
const json = '{/*rainbows*/"unicorn":"cake"}';

JSON\&.parse(stripJsonComments(json));
//=> {unicorn: 'cake'}
.fi
.PP
.SH "API"
.PP
.SS "stripJsonComments(input, [options])"
.SS "input"
Type: \fRstring\fP
.PP
Accepts a string with JSON and returns a string without comments\&.
.SS "options"
.SS "whitespace"
Type: \fRboolean\fP 
.br
 Default: \fRtrue\fP
.PP
Replace comments with whitespace instead of stripping them entirely\&.
.SH "Related"
.PP
.IP "\(bu" 2
\fRstrip-json-comments-cli\fP - CLI for this module
.IP "\(bu" 2
\fRstrip-css-comments\fP - Strip comments from CSS
.PP
.SH "License"
.PP
MIT © \fRSindre Sorhus\fP 
