.TH "md_backend_2node__modules_2minimist_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2minimist_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.2\&.8\fP - 2023-02-09"
.PP
.SS "Merged"
.IP "\(bu" 2
[Fix] Fix long option followed by single dash \fR\fR#17\fP\fP
.IP "\(bu" 2
[Tests] Remove duplicate test \fR\fR#12\fP\fP
.IP "\(bu" 2
[Fix] opt\&.string works with multiple aliases \fR\fR#10\fP\fP
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] Fix long option followed by single dash (#17) \fR\fR#15\fP\fP
.IP "\(bu" 2
[Tests] Remove duplicate test (#12) \fR\fR#8\fP\fP
.IP "\(bu" 2
[Fix] Fix long option followed by single dash \fR\fR#15\fP\fP
.IP "\(bu" 2
[Fix] opt\&.string works with multiple aliases (#10) \fR\fR#9\fP\fP
.IP "\(bu" 2
[Fix] Fix handling of short option with non-trivial equals \fR\fR#5\fP\fP
.IP "\(bu" 2
[Tests] Remove duplicate test \fR\fR#8\fP\fP
.IP "\(bu" 2
[Fix] opt\&.string works with multiple aliases \fR\fR#9\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Merge tag 'v0\&.2\&.3' \fR\fRa026794\fP\fP
.IP "\(bu" 2
[eslint] fix indentation and whitespace \fR\fR5368ca4\fP\fP
.IP "\(bu" 2
[eslint] fix indentation and whitespace \fR\fRe5f5067\fP\fP
.IP "\(bu" 2
[eslint] more cleanup \fR\fR62fde7d\fP\fP
.IP "\(bu" 2
[eslint] more cleanup \fR\fR36ac5d0\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR73923d2\fP\fP
.IP "\(bu" 2
[actions] add reusable workflows \fR\fRd80727d\fP\fP
.IP "\(bu" 2
[eslint] add eslint; rules to enable later are warnings \fR\fR48bc06a\fP\fP
.IP "\(bu" 2
[eslint] fix indentation \fR\fR34b0f1c\fP\fP
.IP "\(bu" 2
[readme] rename and add badges \fR\fR5df0fe4\fP\fP
.IP "\(bu" 2
[Dev Deps] switch from \fRcovert\fP to \fRnyc\fP \fR\fRa48b128\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRcovert\fP, \fRtape\fP; remove unnecessary \fRtap\fP \fR\fRf0fb958\fP\fP
.IP "\(bu" 2
[meta] create FUNDING\&.yml; add \fRfunding\fP in package\&.json \fR\fR3639e0c\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fRbe2e038\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR282b570\fP\fP
.IP "\(bu" 2
isConstructorOrProto adapted from PR \fR\fRef9153f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP \fR\fR098873c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP \fR\fR3124ed3\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP \fR\fR4b927de\fP\fP
.IP "\(bu" 2
[Tests] add \fRaud\fP in \fRposttest\fP \fR\fRb32d9bd\fP\fP
.IP "\(bu" 2
[meta] update repo URLs \fR\fRf9fdfc0\fP\fP
.IP "\(bu" 2
[actions] Avoid 0\&.6 tests due to build failures \fR\fRba92fe6\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR950eaa7\fP\fP
.IP "\(bu" 2
[Dev Deps] add missing \fRnpmignore\fP dev dep \fR\fR3226afa\fP\fP
.IP "\(bu" 2
Merge tag 'v0\&.2\&.2' \fR\fR980d7ac\fP\fP
.PP
.SH "\fRv1\&.2\&.7\fP - 2022-10-10"
.PP
.SS "Commits"
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR0ebf4eb\fP\fP
.IP "\(bu" 2
[actions] add reusable workflows \fR\fRe115b63\fP\fP
.IP "\(bu" 2
[eslint] add eslint; rules to enable later are warnings \fR\fRf58745b\fP\fP
.IP "\(bu" 2
[Dev Deps] switch from \fRcovert\fP to \fRnyc\fP \fR\fRab03356\fP\fP
.IP "\(bu" 2
[readme] rename and add badges \fR\fR236f4a0\fP\fP
.IP "\(bu" 2
[meta] create FUNDING\&.yml; add \fRfunding\fP in package\&.json \fR\fR783a49b\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fRf81ece6\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR56cad44\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRcovert\fP, \fRtape\fP; remove unnecessary \fRtap\fP \fR\fR49c5f9f\fP\fP
.IP "\(bu" 2
[Tests] add \fRaud\fP in \fRposttest\fP \fR\fR228ae93\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP \fR\fR01fc23f\fP\fP
.IP "\(bu" 2
[meta] update repo URLs \fR\fR6b164c7\fP\fP
.PP
.SH "\fRv1\&.2\&.6\fP - 2022-03-21"
.PP
.SS "Commits"
.IP "\(bu" 2
test from prototype pollution PR \fR\fRbc8ecee\fP\fP
.IP "\(bu" 2
isConstructorOrProto adapted from PR \fR\fRc2b9819\fP\fP
.IP "\(bu" 2
security notice for additional prototype pollution issue \fR\fRef88b93\fP\fP
.PP
.SH "\fRv1\&.2\&.5\fP - 2020-03-12"
.PP
.SH "\fRv1\&.2\&.4\fP - 2020-03-11"
.PP
.SS "Commits"
.IP "\(bu" 2
security notice \fR\fR4cf1354\fP\fP
.IP "\(bu" 2
additional test for constructor prototype pollution \fR\fR1043d21\fP\fP
.PP
.SH "\fRv1\&.2\&.3\fP - 2020-03-10"
.PP
.SS "Commits"
.IP "\(bu" 2
more failing proto pollution tests \fR\fR13c01a5\fP\fP
.IP "\(bu" 2
even more aggressive checks for protocol pollution \fR\fR38a4d1c\fP\fP
.PP
.SH "\fRv1\&.2\&.2\fP - 2020-03-10"
.PP
.SS "Commits"
.IP "\(bu" 2
failing test for protocol pollution \fR\fR0efed03\fP\fP
.IP "\(bu" 2
cleanup \fR\fR67d3722\fP\fP
.IP "\(bu" 2
console\&.dir -> console\&.log \fR\fR47acf72\fP\fP
.IP "\(bu" 2
don't assign onto \fBproto\fP \fR\fR63e7ed0\fP\fP
.PP
.SH "\fRv1\&.2\&.1\fP - 2020-03-10"
.PP
.SS "Merged"
.IP "\(bu" 2
move the `opts['--']\fRexample back where it belongs [\fP#63`](https://github.com/minimistjs/minimist/pull/63)
.PP
.SS "Commits"
.IP "\(bu" 2
add test \fR\fR6be5dae\fP\fP
.IP "\(bu" 2
fix bad boolean regexp \fR\fRac3fc79\fP\fP
.PP
.SH "\fRv1\&.2\&.0\fP - 2015-08-24"
.PP
.SS "Commits"
.IP "\(bu" 2
failing -k=v short test \fR\fR63416b8\fP\fP
.IP "\(bu" 2
kv short fix \fR\fR6bbe145\fP\fP
.IP "\(bu" 2
failing kv short test \fR\fRf72ab7f\fP\fP
.IP "\(bu" 2
fixed kv test \fR\fRf5a48c3\fP\fP
.IP "\(bu" 2
enforce space between arg key and value \fR\fR86b321a\fP\fP
.PP
.SH "\fRv1\&.1\&.3\fP - 2015-08-06"
.PP
.SS "Commits"
.IP "\(bu" 2
add failing test - boolean alias array \fR\fR0fa3c5b\fP\fP
.IP "\(bu" 2
fix boolean values with multiple aliases \fR\fR9c0a6e7\fP\fP
.PP
.SH "\fRv1\&.1\&.2\fP - 2015-07-22"
.PP
.SS "Commits"
.IP "\(bu" 2
Convert boolean arguments to boolean values \fR\fR8f3dc27\fP\fP
.IP "\(bu" 2
use non-ancient npm, node 0\&.12 and iojs \fR\fR61ed1d0\fP\fP
.IP "\(bu" 2
an older npm for 0\&.8 \fR\fR25cf778\fP\fP
.PP
.SH "\fRv1\&.1\&.1\fP - 2015-03-10"
.PP
.SS "Commits"
.IP "\(bu" 2
check that they type of a value is a boolean, not just that it is currently set to a boolean \fR\fR6863198\fP\fP
.IP "\(bu" 2
upgrade tape, fix type issues from old tape version \fR\fR806712d\fP\fP
.IP "\(bu" 2
test for setting a boolean to a null default \fR\fR8c444fe\fP\fP
.IP "\(bu" 2
if the previous value was a boolean, without an default (or with an alias) don't make an array either \fR\fRe5f419a\fP\fP
.PP
.SH "\fRv1\&.1\&.0\fP - 2014-08-10"
.PP
.SS "Commits"
.IP "\(bu" 2
add support for handling 'unknown' options not registered with the parser\&. \fR\fR6f3cc5d\fP\fP
.IP "\(bu" 2
reformat package\&.json \fR\fR02ed371\fP\fP
.IP "\(bu" 2
coverage script \fR\fRe5531ba\fP\fP
.IP "\(bu" 2
extra fn to get 100% coverage again \fR\fRa6972da\fP\fP
.PP
.SH "\fRv1\&.0\&.0\fP - 2014-08-10"
.PP
.SS "Commits"
.IP "\(bu" 2
added stopEarly option \fR\fR471c7e4\fP\fP
.IP "\(bu" 2
fix list \fR\fRfef6ae7\fP\fP
.PP
.SH "\fRv0\&.2\&.3\fP - 2023-02-09"
.PP
.SS "Merged"
.IP "\(bu" 2
[Fix] Fix long option followed by single dash \fR\fR#17\fP\fP
.IP "\(bu" 2
[Tests] Remove duplicate test \fR\fR#12\fP\fP
.IP "\(bu" 2
[Fix] opt\&.string works with multiple aliases \fR\fR#10\fP\fP
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] Fix long option followed by single dash (#17) \fR\fR#15\fP\fP
.IP "\(bu" 2
[Tests] Remove duplicate test (#12) \fR\fR#8\fP\fP
.IP "\(bu" 2
[Fix] opt\&.string works with multiple aliases (#10) \fR\fR#9\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[eslint] fix indentation and whitespace \fR\fRe5f5067\fP\fP
.IP "\(bu" 2
[eslint] more cleanup \fR\fR36ac5d0\fP\fP
.IP "\(bu" 2
[eslint] fix indentation \fR\fR34b0f1c\fP\fP
.IP "\(bu" 2
isConstructorOrProto adapted from PR \fR\fRef9153f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP \fR\fR098873c\fP\fP
.IP "\(bu" 2
[Dev Deps] add missing \fRnpmignore\fP dev dep \fR\fR3226afa\fP\fP
.PP
.SH "\fRv0\&.2\&.2\fP - 2022-10-10"
.PP
.SS "Commits"
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR73923d2\fP\fP
.IP "\(bu" 2
[actions] add reusable workflows \fR\fRd80727d\fP\fP
.IP "\(bu" 2
[eslint] add eslint; rules to enable later are warnings \fR\fR48bc06a\fP\fP
.IP "\(bu" 2
[readme] rename and add badges \fR\fR5df0fe4\fP\fP
.IP "\(bu" 2
[Dev Deps] switch from \fRcovert\fP to \fRnyc\fP \fR\fRa48b128\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRcovert\fP, \fRtape\fP; remove unnecessary \fRtap\fP \fR\fRf0fb958\fP\fP
.IP "\(bu" 2
[meta] create FUNDING\&.yml; add \fRfunding\fP in package\&.json \fR\fR3639e0c\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fRbe2e038\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR282b570\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP \fR\fR4b927de\fP\fP
.IP "\(bu" 2
[Tests] add \fRaud\fP in \fRposttest\fP \fR\fRb32d9bd\fP\fP
.IP "\(bu" 2
[meta] update repo URLs \fR\fRf9fdfc0\fP\fP
.PP
.SH "\fRv0\&.2\&.1\fP - 2020-03-12"
.PP
.SH "\fRv0\&.2\&.0\fP - 2014-06-19"
.PP
.SS "Commits"
.IP "\(bu" 2
support all-boolean mode \fR\fR450a97f\fP\fP
.PP
.SH "\fRv0\&.1\&.0\fP - 2014-05-12"
.PP
.SS "Commits"
.IP "\(bu" 2
Provide a mechanism to segregate -- arguments \fR\fRce4a1e6\fP\fP
.IP "\(bu" 2
documented argv['--'] \fR\fR14db0e6\fP\fP
.IP "\(bu" 2
Adding a test-case for notFlags segregation \fR\fR715c1e3\fP\fP
.PP
.SH "\fRv0\&.0\&.10\fP - 2014-05-11"
.PP
.SS "Commits"
.IP "\(bu" 2
dedicated boolean test \fR\fR46e448f\fP\fP
.IP "\(bu" 2
dedicated num test \fR\fR9bf2d36\fP\fP
.IP "\(bu" 2
aliased values treated as strings \fR\fR1ab743b\fP\fP
.IP "\(bu" 2
cover the case of already numbers, at 100% coverage \fR\fRb2bb044\fP\fP
.IP "\(bu" 2
another test for higher coverage \fR\fR3662624\fP\fP
.PP
.SH "\fRv0\&.0\&.9\fP - 2014-05-08"
.PP
.SS "Commits"
.IP "\(bu" 2
Eliminate \fRlongest\fP fn\&. \fR\fR824f642\fP\fP
.PP
.SH "\fRv0\&.0\&.8\fP - 2014-02-20"
.PP
.SS "Commits"
.IP "\(bu" 2
return '' if flag is string and empty \fR\fRfa63ed4\fP\fP
.IP "\(bu" 2
handle joined single letters \fR\fR66c248f\fP\fP
.PP
.SH "\fRv0\&.0\&.7\fP - 2014-02-08"
.PP
.SS "Commits"
.IP "\(bu" 2
another swap of \&.test for \&.match \fR\fRd1da408\fP\fP
.PP
.SH "\fRv0\&.0\&.6\fP - 2014-02-08"
.PP
.SS "Commits"
.IP "\(bu" 2
use \&.test() instead of \&.match() to not crash on non-string values in the arguments array \fR\fR7e0d1ad\fP\fP
.PP
.SH "\fRv0\&.0\&.5\fP - 2013-09-18"
.PP
.SS "Commits"
.IP "\(bu" 2
Improve '--' handling\&. \fR\fRb11822c\fP\fP
.PP
.SH "\fRv0\&.0\&.4\fP - 2013-09-17"
.PP
.SH "\fRv0\&.0\&.3\fP - 2013-09-12"
.PP
.SS "Commits"
.IP "\(bu" 2
failing test for single dash preceeding a double dash \fR\fRb465514\fP\fP
.IP "\(bu" 2
fix for the dot test \fR\fR6a095f1\fP\fP
.PP
.SH "\fRv0\&.0\&.2\fP - 2013-08-28"
.PP
.SS "Commits"
.IP "\(bu" 2
allow dotted aliases & defaults \fR\fR321c33e\fP\fP
.IP "\(bu" 2
use a better version of ff \fR\fRe40f611\fP\fP
.PP
.SH "\fRv0\&.0\&.1\fP - 2013-06-25"
.PP
.SS "Commits"
.IP "\(bu" 2
remove trailing commas \fR\fR6ff0fa0\fP\fP
.PP
.SH "v0\&.0\&.0 - 2013-06-25"
.PP
.SS "Commits"
.IP "\(bu" 2
half of the parse test ported \fR\fR3079326\fP\fP
.IP "\(bu" 2
stripped down code and a passing test from optimist \fR\fR7cced88\fP\fP
.IP "\(bu" 2
ported parse tests completely over \fR\fR9448754\fP\fP
.IP "\(bu" 2
docs, package\&.json \fR\fRa5bf46a\fP\fP
.IP "\(bu" 2
move more short tests into short\&.js \fR\fR503edb5\fP\fP
.IP "\(bu" 2
default bool test was wrong, not the code \fR\fR1b9f5db\fP\fP
.IP "\(bu" 2
passing long tests ripped out of parse\&.js \fR\fR7972c4a\fP\fP
.IP "\(bu" 2
badges \fR\fR84c0370\fP\fP
.IP "\(bu" 2
all the tests now ported, some failures \fR\fR64239ed\fP\fP
.IP "\(bu" 2
failing short test \fR\fRf8a5341\fP\fP
.IP "\(bu" 2
fixed the numeric test \fR\fR6b034f3\fP\fP 
.PP

