.TH "md_backend_2node__modules_2get-intrinsic_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2get-intrinsic_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.2\&.4\fP - 2024-02-05"
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use all 7 <+ ES6 Errors from \fRes-errors\fP \fR\fRbcac811\fP\fP
.PP
.SH "\fRv1\&.2\&.3\fP - 2024-02-03"
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRes-errors\fP, so things that only need those do not need \fRget-intrinsic\fP \fR\fRf11db9c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRes-abstract\fP, \fRmock-property\fP, \fRnpmignore\fP \fR\fRb7ac7d1\fP\fP
.IP "\(bu" 2
[meta] simplify \fRexports\fP \fR\fRfaa0cc6\fP\fP
.IP "\(bu" 2
[meta] add missing \fRengines\&.node\fP \fR\fR774dd0b\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR5828e8e\fP\fP
.IP "\(bu" 2
[Robustness] use null objects for lookups \fR\fReb9a11f\fP\fP
.IP "\(bu" 2
[meta] add \fRsideEffects\fP flag \fR\fR89bcc7a\fP\fP
.PP
.SH "\fRv1\&.2\&.2\fP - 2023-10-20"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRcall-bind\fP, \fRes-abstract\fP, \fRmock-property\fP, \fRobject-inspect\fP, \fRtape\fP \fR\fRf51bcf2\fP\fP
.IP "\(bu" 2
[Refactor] use \fRhasown\fP instead of \fRhas\fP \fR\fR18d14b7\fP\fP
.IP "\(bu" 2
[Deps] update \fRfunction-bind\fP \fR\fR6e109c8\fP\fP
.PP
.SH "\fRv1\&.2\&.1\fP - 2023-05-13"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] avoid a crash in envs without \fR__proto__\fP \fR\fR7bad8d0\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRes-abstract\fP \fR\fRc60e6b7\fP\fP
.PP
.SH "\fRv1\&.2\&.0\fP - 2023-01-19"
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] update checkout action \fR\fRca6b12f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRes-abstract\fP, \fRobject-inspect\fP, \fRtape\fP \fR\fR41a3727\fP\fP
.IP "\(bu" 2
[Fix] ensure \fRError\&.prototype\fP is undeniable \fR\fRc511e97\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRes-abstract\fP, \fRtape\fP \fR\fR1bef8a8\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRes-abstract\fP \fR\fR0d41f16\fP\fP
.IP "\(bu" 2
[New] add \fRBigInt64Array\fP and \fRBigUint64Array\fP \fR\fRa6cca25\fP\fP
.IP "\(bu" 2
[Tests] use \fRgopd\fP \fR\fRecf7722\fP\fP
.PP
.SH "\fRv1\&.1\&.3\fP - 2022-09-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fRes-abstract\fP, \fRes-value-fixtures\fP, \fRtape\fP \fR\fR07ff291\fP\fP
.IP "\(bu" 2
[Fix] properly check for % signs \fR\fR50ac176\fP\fP
.PP
.SH "\fRv1\&.1\&.2\fP - 2022-06-08"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] properly validate against extra % signs \fR\fR#16\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] reuse common workflows \fR\fR0972547\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fR5ba0b51\fP\fP
.IP "\(bu" 2
[actions] use \fRnode/install\fP instead of \fRnode/run\fP; use \fRcodecov\fP action \fR\fRc364492\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRes-abstract\fP, \fRobject-inspect\fP, \fRtape\fP \fR\fRdc04dad\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRes-abstract\fP, \fRobject-inspect\fP, \fRsafe-publish-latest\fP, \fRtape\fP \fR\fR1c14059\fP\fP
.IP "\(bu" 2
[Tests] use \fRmock-property\fP \fR\fRb396ef0\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRobject-inspect\fP, \fRtape\fP \fR\fRc2c758d\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRes-abstract\fP, \fRes-value-fixtures\fP, \fRobject-inspect\fP, \fRtape\fP \fR\fR29e3c09\fP\fP
.IP "\(bu" 2
[actions] update codecov uploader \fR\fR8cbc141\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRes-abstract\fP, \fRes-value-fixtures\fP, \fRobject-inspect\fP, \fRtape\fP \fR\fR10b6f5c\fP\fP
.IP "\(bu" 2
[readme] add github actions/codecov badges \fR\fR4e25400\fP\fP
.IP "\(bu" 2
[Tests] use \fRfor-each\fP instead of \fRforeach\fP \fR\fRc05b957\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRes-abstract\fP \fR\fR29b05ae\fP\fP
.IP "\(bu" 2
[meta] use \fRprepublishOnly\fP script for npm 7+ \fR\fR95c285d\fP\fP
.IP "\(bu" 2
[Deps] update \fRhas-symbols\fP \fR\fR593cb4f\fP\fP
.IP "\(bu" 2
[readme] fix repo URLs \fR\fR1c8305b\fP\fP
.IP "\(bu" 2
[Deps] update \fRhas-symbols\fP \fR\fRc7138b6\fP\fP
.IP "\(bu" 2
[Dev Deps] remove unused \fRhas-bigints\fP \fR\fRbd63aff\fP\fP
.PP
.SH "\fRv1\&.1\&.1\fP - 2024-02-03"
.PP
.SS "Fixed"
.IP "\(bu" 2
[meta] export \fR\&./package\&.json\fP \fR\fR#9\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[readme] flesh out the readme; use \fRevalmd\fP \fR\fRd12f12c\fP\fP
.IP "\(bu" 2
[eslint] set up proper globals config \fR\fR5a8c098\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP \fR\fR7b9a5c0\fP\fP
.PP
.SH "\fRv1\&.1\&.0\fP - 2024-01-25"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Refactor] delay \fRFunction\fP eval until syntax-derived values are requested \fR\fR#3\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate tests to Github Actions \fR\fR2ab762b\fP\fP
.IP "\(bu" 2
[meta] do not publish github action workflow files \fR\fR5e7108e\fP\fP
.IP "\(bu" 2
[Tests] add some coverage \fR\fR01ac7a8\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRcall-bind\fP, \fRes-abstract\fP, \fRtape\fP; add \fRcall-bind\fP \fR\fR911b672\fP\fP
.IP "\(bu" 2
[Refactor] rearrange evalled constructors a bit \fR\fR7e7e4bf\fP\fP
.IP "\(bu" 2
[meta] add Automatic Rebase and Require Allow Edits workflows \fR\fR0199968\fP\fP
.PP
.SH "\fRv1\&.0\&.2\fP - 2020-12-17"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] Throw for non‑existent intrinsics \fR\fR68f873b\fP\fP
.IP "\(bu" 2
[Fix] Throw for non‑existent segments in the intrinsic path \fR\fR8325dee\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRhas-bigints\fP, \fRobject-inspect\fP \fR\fR0c227a7\fP\fP
.IP "\(bu" 2
[meta] do not lint coverage output \fR\fR70d2419\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2020-10-30"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] gather coverage data on every job \fR\fRd1d280d\fP\fP
.IP "\(bu" 2
[Fix] add missing dependencies \fR\fR5031771\fP\fP
.IP "\(bu" 2
[Tests] use \fRes-value-fixtures\fP \fR\fRaf48765\fP\fP
.PP
.SH "v1\&.0\&.0 - 2020-10-29"
.PP
.SS "Commits"
.IP "\(bu" 2
Implementation \fR\fRbbce57c\fP\fP
.IP "\(bu" 2
Tests \fR\fR17b4f0d\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR3153294\fP\fP
.IP "\(bu" 2
npm init \fR\fRfb326c4\fP\fP
.IP "\(bu" 2
[meta] add Automatic Rebase and Require Allow Edits workflows \fR\fR48862fb\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR5f28ad0\fP\fP
.IP "\(bu" 2
[meta] add 'funding'; create \fRFUNDING\&.yml\fP \fR\fRc2bbdde\fP\fP
.IP "\(bu" 2
[Tests] add \fRnpm run lint\fP \fR\fR0a84b98\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR9586c75\fP\fP 
.PP

