.TH "md_backend_2node__modules_2call-bind_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2call-bind_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.0\&.7\fP - 2024-02-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRes-define-property\fP \fR\fR09b76a0\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP, \fRset-function-length\fP \fR\fRad5136d\fP\fP
.PP
.SH "\fRv1\&.0\&.6\fP - 2024-02-05"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRnpmignore\fP, \fRtape\fP \fR\fRd564d5c\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP, \fRset-function-length\fP \fR\fRcfc2bdc\fP\fP
.IP "\(bu" 2
[Refactor] use \fRes-errors\fP, so things that only need those do not need \fRget-intrinsic\fP \fR\fR64cd289\fP\fP
.IP "\(bu" 2
[meta] add missing \fRengines\&.node\fP \fR\fR32a4038\fP\fP
.PP
.SH "\fRv1\&.0\&.5\fP - 2023-10-19"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] throw an error on non-functions as early as possible \fR\fRf262408\fP\fP
.IP "\(bu" 2
[Deps] update \fRset-function-length\fP \fR\fR3fff271\fP\fP
.PP
.SH "\fRv1\&.0\&.4\fP - 2023-10-19"
.PP
.SH "\fRv1\&.0\&.3\fP - 2023-10-19"
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] reuse common workflows \fR\fRa994df6\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fReef3ef2\fP\fP
.IP "\(bu" 2
[readme] flesh out content \fR\fR1845ccf\fP\fP
.IP "\(bu" 2
[actions] use \fRnode/install\fP instead of \fRnode/run\fP; use \fRcodecov\fP action \fR\fR5b47d53\fP\fP
.IP "\(bu" 2
[Refactor] use \fRset-function-length\fP \fR\fRa0e165c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR9c50103\fP\fP
.IP "\(bu" 2
[meta] simplify 'exports' \fR\fR019c6d0\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRsafe-publish-latest\fP, \fRtape\fP \fR\fR23bd718\fP\fP
.IP "\(bu" 2
[actions] update codecov uploader \fR\fR62552d7\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRtape\fP \fR\fRec81665\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRsafe-publish-latest\fP, \fRtape\fP \fR\fR35d67fc\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR0266d8d\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR43a5b28\fP\fP
.IP "\(bu" 2
[Deps] update \fRdefine-data-property\fP, \fRfunction-bind\fP, \fRget-intrinsic\fP \fR\fR780eb36\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRtape\fP \fR\fR90d50ad\fP\fP
.IP "\(bu" 2
[meta] use \fRprepublishOnly\fP script for npm 7+ \fR\fR44c5433\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR86bfbfc\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR5c53354\fP\fP
.IP "\(bu" 2
[actions] update checkout action \fR\fR4c393a8\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR4e70bde\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR55ae803\fP\fP
.PP
.SH "\fRv1\&.0\&.2\fP - 2021-01-11"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] properly include the receiver in the bound length \fR\fRdbae7bc\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2021-01-08"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate tests to Github Actions \fR\fRb6db284\fP\fP
.IP "\(bu" 2
[meta] do not publish github action workflow files \fR\fRec7fe46\fP\fP
.IP "\(bu" 2
[Fix] preserve original function’s length when possible \fR\fRadbceaa\fP\fP
.IP "\(bu" 2
[Tests] gather coverage data on every job \fR\fRd69e23c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR2fd3586\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fRf23e931\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR72d9f44\fP\fP
.IP "\(bu" 2
[meta] fix FUNDING\&.yml \fR\fRe723573\fP\fP
.IP "\(bu" 2
[eslint] ignore coverage output \fR\fR15e76d2\fP\fP
.IP "\(bu" 2
[meta] add Automatic Rebase and Require Allow Edits workflows \fR\fR8fa4dab\fP\fP
.PP
.SH "v1\&.0\&.0 - 2020-10-30"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial commit \fR\fR306cf98\fP\fP
.IP "\(bu" 2
Tests \fR\fRe10d0bb\fP\fP
.IP "\(bu" 2
Implementation \fR\fR43852ed\fP\fP
.IP "\(bu" 2
npm init \fR\fR408f860\fP\fP
.IP "\(bu" 2
[meta] add Automatic Rebase and Require Allow Edits workflows \fR\fRfb349b2\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fRc4001fc\fP\fP
.IP "\(bu" 2
[meta] add 'funding'; create \fRFUNDING\&.yml\fP \fR\fRd4d6d29\fP\fP
.IP "\(bu" 2
[Tests] add \fRnpm run lint\fP \fR\fRdedfb98\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR54ac776\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP \fR\fR9ea8e43\fP\fP 
.PP

