.TH "md_backend_2node__modules_2es-errors_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2es-errors_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.3\&.0\fP - 2024-02-05"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fREvalError\fP and \fRURIError\fP \fR\fR1927627\fP\fP
.PP
.SH "\fRv1\&.2\&.1\fP - 2024-02-04"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] add missing \fRexports\fP entry \fR\fR5bb5f28\fP\fP
.PP
.SH "\fRv1\&.2\&.0\fP - 2024-02-04"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRReferenceError\fP \fR\fR6d8cf5b\fP\fP
.PP
.SH "\fRv1\&.1\&.0\fP - 2024-02-04"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add base Error \fR\fR2983ab6\fP\fP
.PP
.SH "v1\&.0\&.0 - 2024-02-03"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme, type \fR\fR8f47631\fP\fP
.IP "\(bu" 2
Initial commit \fR\fRea5d099\fP\fP
.IP "\(bu" 2
npm init \fR\fR6f5ebf9\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRe1a0aeb\fP\fP
.IP "\(bu" 2
[meta] add \fRsideEffects\fP flag \fR\fRa9c7d46\fP\fP 
.PP

