.TH "md_backend_2node__modules_2side-channel_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2side-channel_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.0\&.6\fP - 2024-02-29"
.PP
.SS "Commits"
.IP "\(bu" 2
add types \fR\fR9beef66\fP\fP
.IP "\(bu" 2
[meta] simplify \fRexports\fP \fR\fR4334cf9\fP\fP
.IP "\(bu" 2
[Deps] update \fRcall-bind\fP \fR\fRd6043c4\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR6aca376\fP\fP
.PP
.SH "\fRv1\&.0\&.5\fP - 2024-02-06"
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] reuse common workflows \fR\fR3d2e1ff\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fR04296ea\fP\fP
.IP "\(bu" 2
[meta] add \fR\&.editorconfig\fP; add \fReclint\fP \fR\fR130f0a6\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRsafe-publish-latest\fP, \fRtape\fP \fR\fRd480c2f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRtape\fP \fR\fRecbe70e\fP\fP
.IP "\(bu" 2
[actions] update rebase action \fR\fR75240b9\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRnpmignore\fP, \fRtape\fP \fR\fRae8d281\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR7125b88\fP\fP
.IP "\(bu" 2
[Deps] update \fRcall-bind\fP, \fRget-intrinsic\fP, \fRobject-inspect\fP \fR\fR82577c9\fP\fP
.IP "\(bu" 2
[Deps] update \fRcall-bind\fP, \fRget-intrinsic\fP, \fRobject-inspect\fP \fR\fR550aadf\fP\fP
.IP "\(bu" 2
[Tests] increase coverage \fR\fR5130877\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP, \fRobject-inspect\fP \fR\fRba0194c\fP\fP
.IP "\(bu" 2
[meta] add missing \fRengines\&.node\fP \fR\fR985fd24\fP\fP
.IP "\(bu" 2
[Refactor] use \fRes-errors\fP, so things that only need those do not need \fRget-intrinsic\fP \fR\fR40227a8\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fRa989b40\fP\fP
.IP "\(bu" 2
[Deps] update \fRobject-inspect\fP \fR\fRaec42d2\fP\fP
.PP
.SH "\fRv1\&.0\&.4\fP - 2020-12-29"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate tests to Github Actions \fR\fR10909cb\fP\fP
.IP "\(bu" 2
[Refactor] Use a linked list rather than an array, and move accessed nodes to the beginning \fR\fR195613f\fP\fP
.IP "\(bu" 2
[meta] do not publish github action workflow files \fR\fR290ec29\fP\fP
.IP "\(bu" 2
[Tests] run \fRnyc\fP on all tests; use \fRtape\fP runner \fR\fRea6d030\fP\fP
.IP "\(bu" 2
[actions] add 'Allow Edits' workflow \fR\fRd464d8f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP \fR\fR02daca8\fP\fP
.IP "\(bu" 2
[Refactor] use \fRcall-bind\fP and \fRget-intrinsic\fP instead of \fRes-abstract\fP \fR\fRe09d481\fP\fP
.IP "\(bu" 2
[Deps] update \fRobject\&.assign\fP \fR\fRee83aa8\fP\fP
.IP "\(bu" 2
[actions] update rebase action to use checkout v2 \fR\fR7726b0b\fP\fP
.PP
.SH "\fRv1\&.0\&.3\fP - 2020-08-23"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRtape\fP \fR\fR1f10561\fP\fP
.IP "\(bu" 2
[Deps] update \fRes-abstract\fP, \fRobject-inspect\fP \fR\fRbc20159\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRtape\fP \fR\fRb9b2b22\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRtape\fP \fR\fR7055ab4\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRauto-changelog\fP; add \fRaud\fP \fR\fRd278c37\fP\fP
.IP "\(bu" 2
[actions] switch Automatic Rebase workflow to \fRpull_request_target\fP event \fR\fR3bcf982\fP\fP
.IP "\(bu" 2
[Tests] only audit prod deps \fR\fR18d01c4\fP\fP
.IP "\(bu" 2
[Deps] update \fRes-abstract\fP \fR\fR6ab096d\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR9dc174c\fP\fP
.IP "\(bu" 2
[Deps] update \fRes-abstract\fP \fR\fR431d0f0\fP\fP
.IP "\(bu" 2
[Deps] update \fRes-abstract\fP \fR\fR49869fd\fP\fP
.IP "\(bu" 2
[meta] Add package\&.json to package's exports \fR\fR77d9cdc\fP\fP
.PP
.SH "\fRv1\&.0\&.2\fP - 2019-12-20"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRtape\fP \fR\fR4a526df\fP\fP
.IP "\(bu" 2
[Deps] update \fRes-abstract\fP \fR\fRd4f6e62\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2019-12-01"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] add missing 'exports' \fR\fRd212907\fP\fP
.PP
.SH "v1\&.0\&.0 - 2019-12-01"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation \fR\fRdbebd3a\fP\fP
.IP "\(bu" 2
Initial tests \fR\fR73bdefe\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR43c03e1\fP\fP
.IP "\(bu" 2
npm init \fR\fR5c090a7\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fRa5c4e56\fP\fP
.IP "\(bu" 2
[actions] add automatic rebasing / merge commit blocking \fR\fRbab1683\fP\fP
.IP "\(bu" 2
[meta] add \fRfunding\fP field; create FUNDING\&.yml \fR\fR63d7aea\fP\fP
.IP "\(bu" 2
[Tests] add \fRnpm run lint\fP \fR\fR46a5a81\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR8b16b03\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP \fR\fR2f098ef\fP\fP 
.PP

