.TH "md_backend_2node__modules_2aproba_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2aproba_2_c_h_a_n_g_e_l_o_g \- CHANGELOG 
.PP
2\&.0\&.0
.IP "\(bu" 2
Drop support for 0\&.10 and 0\&.12\&. They haven't been in travis but still, since we \fIknow\fP we'll break with them now it's only polite to do a major bump\&. 
.PP

