.TH "md_backend_2node__modules_2expand-template_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2expand-template_2_r_e_a_d_m_e \- expand-template 
.PP
 
.PP
.RS 4
Expand placeholders in a template string\&. 
.RE
.PP
.PP
\fR\fP  \fR\fP \fR\fP
.SH "Install"
.PP
.PP
.nf
$ npm i expand\-template \-S
.fi
.PP
.SH "Usage"
.PP
Default functionality expands templates using \fR{}\fP as separators for string placeholders\&.
.PP
.PP
.nf
var expand = require('expand\-template')()
var template = '{foo}/{foo}/{bar}/{bar}'
console\&.log(expand(template, {
  foo: 'BAR',
  bar: 'FOO'
}))
// \-> BAR/BAR/FOO/FOO
.fi
.PP
.PP
Custom separators:
.PP
.PP
.nf
var expand = require('expand\-template')({ sep: '[]' })
var template = '[foo]/[foo]/[bar]/[bar]'
console\&.log(expand(template, {
  foo: 'BAR',
  bar: 'FOO'
}))
// \-> BAR/BAR/FOO/FOO
.fi
.PP
.SH "License"
.PP
All code, unless stated otherwise, is dual-licensed under \fR\fRWTFPL\fP\fP and \fR\fRMIT\fP\fP\&. 
