.TH "md_backend_2node__modules_2file-uri-to-path_2_history" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2file-uri-to-path_2_history \- 1\&.0\&.0 / 2017-07-06 
.PP

.IP "\(bu" 2
update 'mocha' to v3
.IP "\(bu" 2
fixed unicode URI decoding (#6)
.IP "\(bu" 2
add typings for Typescript
.IP "\(bu" 2
README: use SVG Travis-CI badge
.IP "\(bu" 2
add LICENSE file (MIT)
.IP "\(bu" 2
add \&.travis\&.yml file (testing Node\&.js 0\&.8 through 8 currently)
.IP "\(bu" 2
add README\&.md file
.PP
.SH "0\&.0\&.2 / 2014-01-27"
.PP
.IP "\(bu" 2
index: invert the path separators on Windows
.PP
.SH "0\&.0\&.1 / 2014-01-27"
.PP
.IP "\(bu" 2
initial commit 
.PP

