.TH "md_backend_2node__modules_2parseurl_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2parseurl_2_h_i_s_t_o_r_y \- 1\&.3\&.3 / 2019-04-15 
.PP

.IP "\(bu" 2
Fix Node\&.js 0\&.8 return value inconsistencies
.PP
.SH "1\&.3\&.2 / 2017-09-09"
.PP
.IP "\(bu" 2
perf: reduce overhead for full URLs
.IP "\(bu" 2
perf: unroll the 'fast-path' \fRRegExp\fP
.PP
.SH "1\&.3\&.1 / 2016-01-17"
.PP
.IP "\(bu" 2
perf: enable strict mode
.PP
.SH "1\&.3\&.0 / 2014-08-09"
.PP
.IP "\(bu" 2
Add \fRparseurl\&.original\fP for parsing \fRreq\&.originalUrl\fP with fallback
.IP "\(bu" 2
Return \fRundefined\fP if \fRreq\&.url\fP is \fRundefined\fP
.PP
.SH "1\&.2\&.0 / 2014-07-21"
.PP
.IP "\(bu" 2
Cache URLs based on original value
.IP "\(bu" 2
Remove no-longer-needed URL mis-parse work-around
.IP "\(bu" 2
Simplify the 'fast-path' \fRRegExp\fP
.PP
.SH "1\&.1\&.3 / 2014-07-08"
.PP
.IP "\(bu" 2
Fix typo
.PP
.SH "1\&.1\&.2 / 2014-07-08"
.PP
.IP "\(bu" 2
Seriously fix Node\&.js 0\&.8 compatibility
.PP
.SH "1\&.1\&.1 / 2014-07-08"
.PP
.IP "\(bu" 2
Fix Node\&.js 0\&.8 compatibility
.PP
.SH "1\&.1\&.0 / 2014-07-08"
.PP
.IP "\(bu" 2
Incorporate URL href-only parse fast-path
.PP
.SH "1\&.0\&.1 / 2014-03-08"
.PP
.IP "\(bu" 2
Add missing \fRrequire\fP
.PP
.SH "1\&.0\&.0 / 2014-03-08"
.PP
.IP "\(bu" 2
Genesis from \fRconnect\fP 
.PP

