.TH "md_backend_2node__modules_2decompress-response_2readme" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2decompress-response_2readme \- decompress-response \fR\fP 
.PP
 
.PP
.RS 4
Decompress a HTTP response if needed 
.RE
.PP
.PP
Decompresses the \fRresponse\fP from \fR\fRhttp\&.request\fP\fP if it's gzipped, deflated or compressed with Brotli, otherwise just passes it through\&.
.PP
Used by \fR\fRgot\fP\fP\&.
.SH "Install"
.PP
.PP
.nf
$ npm install decompress\-response
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
const http = require('http');
const decompressResponse = require('decompress\-response');

http\&.get('https://sindresorhus\&.com', response => {
    response = decompressResponse(response);
});
.fi
.PP
.SH "API"
.PP
.SS "decompressResponse(response)"
Returns the decompressed HTTP response stream\&.
.SS "response"
Type: \fR\fRhttp\&.IncomingMessage\fP\fP
.PP
The HTTP incoming stream with compressed data\&.
.PP
.PP
.PP
 \fB \fRGet professional support for this package with a Tidelift subscription\fP \fP 
.br
 \*< Tidelift helps make open source sustainable for maintainers while giving companies
.br
assurances about security, maintenance, and licensing for their dependencies\&. \*>   
