.TH "md_backend_2node__modules_2deep-extend_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2deep-extend_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP

.SH "v0\&.6\&.0"
.PP
.IP "\(bu" 2
Updated 'devDependencies' versions to fix vulnerability alerts
.IP "\(bu" 2
Dropped support of io\&.js and node\&.js v0\&.12\&.x and lower since new versions of 'devDependencies' couldn't work with those old node\&.js versions (minimal supported version of node\&.js now is v4\&.0\&.0)
.PP
.SH "v0\&.5\&.1"
.PP
.IP "\(bu" 2
Fix prototype pollution vulnerability (thanks to @mwakerman for the PR)
.IP "\(bu" 2
Avoid using deprecated Buffer API (thanks to @ChALkeR for the PR)
.PP
.SH "v0\&.5\&.0"
.PP
.IP "\(bu" 2
Auto-testing provided by Travis CI;
.IP "\(bu" 2
Support older Node\&.JS versions (\fRv0\&.11\&.x\fP and \fRv0\&.10\&.x\fP);
.IP "\(bu" 2
Removed tests files from npm package\&.
.PP
.SH "v0\&.4\&.2"
.PP
.IP "\(bu" 2
Fix for \fRnull\fP as an argument\&.
.PP
.SH "v0\&.4\&.1"
.PP
.IP "\(bu" 2
Removed test code from \fBnpm\fP package (\fRsee pull request #21\fP);
.IP "\(bu" 2
Increased minimal version of Node from \fR0\&.4\&.0\fP to \fR0\&.12\&.0\fP (because can't run tests on lesser version anyway)\&.
.PP
.SH "v0\&.4\&.0"
.PP
.IP "\(bu" 2
\fBWARNING!\fP Broken backward compatibility with \fRv0\&.3\&.x\fP;
.IP "\(bu" 2
Fixed bug with extending arrays instead of cloning;
.IP "\(bu" 2
Deep cloning for arrays;
.IP "\(bu" 2
Check for own property;
.IP "\(bu" 2
Fixed some documentation issues;
.IP "\(bu" 2
Strict JS mode\&. 
.PP

