.TH "md_backend_2node__modules_2prebuild-install_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2prebuild-install_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 
.SH "\fR7\&.1\&.2\fP - 2024-02-29"
.PP
.SS "Changed"
.IP "\(bu" 2
Support environments where MD5 is prohibited (\fR#191\fP) (\fR\fR9140468\fP\fP) (Tomasz Szuba)
.PP
.SH "\fR7\&.1\&.1\fP - 2022-06-07"
.PP
.SS "Changed"
.IP "\(bu" 2
Replace use of npmlog dependency with console\&.error (\fR#182\fP) (\fR\fR4e2284c\fP\fP) (Lovell Fuller)\&.
.IP "\(bu" 2
Ensure script output can be captured by tests (\fR#181\fP) (\fR\fRd1853cb\fP\fP) (Lovell Fuller)\&.
.PP
.SH "\fR7\&.1\&.0\fP - 2022-04-20"
.PP
.SS "Changed"
.IP "\(bu" 2
Allow setting libc to glibc on non-glibc platform (\fR#176\fP) (\fR\fRf729abb\fP\fP) (Joona Heinikoski)\&.
.PP
.SH "\fR7\&.0\&.1\fP - 2022-01-28"
.PP
.SS "Changed"
.IP "\(bu" 2
Upgrade to the latest version of \fRdetect-libc\fP (\fR#166\fP) (\fR\fRf71c6b9\fP\fP) (Lovell Fuller)\&.
.PP
.SH "\fR7\&.0\&.0\fP - 2024-11-12"
.PP
.SS "Changed"
.IP "\(bu" 2
\fBBreaking:\fP bump \fRnode-abi\fP so that Electron 14+ gets correct ABI (\fR#161\fP) (\fR\fR477f347\fP\fP) (csett86)\&. Drops support of Node\&.js < 10\&.
.IP "\(bu" 2
Bump \fRsimple-get\fP (\fR\fR7468c14\fP\fP) (Vincent Weevers)\&.
.PP
.SH "\fR6\&.1\&.4\fP - 2024-08-11"
.PP
.SS "Fixed"
.IP "\(bu" 2
Move auth token to header instead of query param (\fR#160\fP) (\fR\fRb3fad76\fP\fP) (nicolai-nordic)
.IP "\(bu" 2
Remove \fR_\fP prefix as it isn't allowed by npm config (\fR#153\fP) (\fR\fRa964e5b\fP\fP) (Tom Boothman)
.IP "\(bu" 2
Make \fRrc\&.path\fP absolute (\fR#158\fP) (\fR\fR57bcc06\fP\fP) (George Waters)\&.
.PP
.SH "\fR6\&.1\&.3\fP - 2024-06-03"
.PP
.SS "Changed"
.IP "\(bu" 2
Inline no longer maintained \fRnoop-logger\fP (\fR#155\fP) (\fR\fRe08d75a\fP\fP) (Alexandru Dima)
.IP "\(bu" 2
Point users towards \fRprebuildify\fP in README (\fR#150\fP) (\fR\fR5ee1a2f\fP\fP) (Vincent Weevers)
.PP
.SH "\fR6\&.1\&.2\fP - 2024-04-24"
.PP
.SS "Fixed"
.IP "\(bu" 2
Support URL-safe strings in scoped packages (\fR#148\fP) (\fR\fRdb36c7a\fP\fP) (Marco)
.PP
.SH "\fR6\&.1\&.1\fP - 2024-04-04"
.PP
.SS "Fixed"
.IP "\(bu" 2
Support \fRforce\fP & \fRbuildFromSource\fP options in yarn (\fR#140\fP) (\fR\fR8cb1ced\fP\fP) (João Moreno)
.IP "\(bu" 2
Bump \fRnode-abi\fP to prevent dedupe (closes \fR#135\fP) (\fR\fR2950fb2\fP\fP) (Vincent Weevers)
.PP
.SH "\fR6\&.1\&.0\fP - 2024-04-03"
.PP
.SS "Added"
.IP "\(bu" 2
Restore local prebuilds feature (\fR#137\fP) (\fR\fRdc4e5ea\fP\fP) (Wes Roberts)\&. Previously removed in \fR#81\fP / \fR\fRa069253\fP\fP\&.
.PP
.SH "\fR6\&.0\&.1\fP - 2024-02-14"
.PP
.SS "Fixed"
.IP "\(bu" 2
Fixes empty \fR--tag-prefix\fP (\fR#143\fP) (\fR\fB@mathiask88\fP\fP)
.PP
.SH "\fR6\&.0\&.0\fP - 2020-10-23"
.PP
.SS "Changed"
.IP "\(bu" 2
\fBBreaking:\fP don't skip downloads in standalone mode (\fR\fRb6f3b36\fP\fP) (\fR\fB@vweevers\fP\fP)
.PP
.SS "Added"
.IP "\(bu" 2
Document cross platform options (\fR\fRe5c9a5a\fP\fP) (\fR\fB@fishbone1\fP\fP)
.PP
.SS "Removed"
.IP "\(bu" 2
\fBBreaking:\fP remove \fR--compile\fP and \fR--prebuild\fP options (\fR\fR94f2492\fP\fP) (\fR\fB@vweevers\fP\fP)
.PP
.SS "Fixed"
.IP "\(bu" 2
Support npm 7 (\fR\fR8acccac\fP\fP, \fR\fR08eaf6d\fP\fP, \fR\fR22175b8\fP\fP) (\fR\fB@vweevers\fP\fP)
.PP
.SH "\fR5\&.3\&.6\fP - 2020-10-20"
.PP
.SS "Changed"
.IP "\(bu" 2
Replace \fRmkdirp\fP dependency with \fRmkdirp-classic\fP (\fR\fB@ralphtheninja\fP\fP) 
.PP

