.TH "md_backend_2node__modules_2node-gyp_2docs_2binding_8gyp-files-in-the-wild" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2node-gyp_2docs_2binding_8gyp-files-in-the-wild \- binding\&.gyp-files-in-the-wild 
.PP
This page contains links to some examples of existing \fRbinding\&.gyp\fP files that other node modules are using\&. Take a look at them for inspiration\&.
.PP
To add to this page, just add the link to the project's \fRbinding\&.gyp\fP file below:
.PP
.IP "\(bu" 2
\fRons\fP
.IP "\(bu" 2
\fRthmclrx\fP
.IP "\(bu" 2
\fRlibxmljs\fP
.IP "\(bu" 2
\fRnode-buffertools\fP
.IP "\(bu" 2
\fRnode-canvas\fP
.IP "\(bu" 2
\fRnode-ffi\fP + \fRlibffi\fP
.IP "\(bu" 2
\fRnode-time\fP
.IP "\(bu" 2
\fRnode-sass\fP + \fRlibsass\fP
.IP "\(bu" 2
\fRnode-serialport\fP
.IP "\(bu" 2
\fRnode-weak\fP
.IP "\(bu" 2
\fRpty\&.js\fP
.IP "\(bu" 2
\fRref\fP
.IP "\(bu" 2
\fRappjs\fP
.IP "\(bu" 2
\fRnwm\fP
.IP "\(bu" 2
\fRbcrypt\fP
.IP "\(bu" 2
\fRnk-mysql\fP
.IP "\(bu" 2
\fRnk-xrm-installer\fP + \fRincludable\&.gypi\fP + \fRunpack\&.py\fP + \fRdisburse\&.py\fP 
.br
 \*<\&.py files above provide complete reference for examples of fetching source via http, extracting, and moving files\&.\*> 
.IP "\(bu" 2
\fRnode-memwatch\fP
.IP "\(bu" 2
\fRnode-ip2location\fP
.IP "\(bu" 2
\fRnode-midi\fP
.IP "\(bu" 2
\fRnode-sqlite3\fP + \fRlibsqlite3\fP
.IP "\(bu" 2
\fRnode-zipfile\fP
.IP "\(bu" 2
\fRnode-mapnik\fP
.IP "\(bu" 2
\fRnode-inotify\fP
.IP "\(bu" 2
\fRv8-profiler\fP
.IP "\(bu" 2
\fRairtunes\fP
.IP "\(bu" 2
\fRnode-fann\fP
.IP "\(bu" 2
\fRnode-talib\fP
.IP "\(bu" 2
\fRnode-leveldown\fP + \fRleveldb\&.gyp\fP + \fRsnappy\&.gyp\fP
.IP "\(bu" 2
\fRnode-expat\fP + \fRlibexpat\fP
.IP "\(bu" 2
\fRnode-openvg-canvas\fP + \fRnode-openvg\fP
.IP "\(bu" 2
\fRnode-cryptopp\fP
.IP "\(bu" 2
\fRtopcube\fP
.IP "\(bu" 2
\fRnode-osmium\fP
.IP "\(bu" 2
\fRnode-osrm\fP
.IP "\(bu" 2
\fRnode-oracle\fP
.IP "\(bu" 2
\fRnode-process-list\fP
.IP "\(bu" 2
\fRnode-nanomsg\fP
.IP "\(bu" 2
\fRGhostscript4JS\fP
.IP "\(bu" 2
\fRnodecv\fP
.IP "\(bu" 2
\fRmagick-cli\fP
.IP "\(bu" 2
\fRsharp\fP
.IP "\(bu" 2
\fRkrb5\fP 
.PP

