.TH "md_backend_2node__modules_2body-parser_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2body-parser_2_h_i_s_t_o_r_y \- 1\&.20\&.2 / 2023-02-21 
.PP

.IP "\(bu" 2
Fix strict json error message on Node\&.js 19+
.IP "\(bu" 2
deps: content-type1\&.0\&.5
.IP "  \(bu" 4
perf: skip value escaping when unnecessary
.PP

.IP "\(bu" 2
deps: raw-body@2\&.5\&.2
.PP
.SH "1\&.20\&.1 / 2022-10-06"
.PP
.IP "\(bu" 2
deps: qs@6.11\&.0
.IP "\(bu" 2
perf: remove unnecessary object clone
.PP
.SH "1\&.20\&.0 / 2022-04-02"
.PP
.IP "\(bu" 2
Fix error message for json parse whitespace in \fRstrict\fP
.IP "\(bu" 2
Fix internal error when inflated body exceeds limit
.IP "\(bu" 2
Prevent loss of async hooks context
.IP "\(bu" 2
Prevent hanging when request already read
.IP "\(bu" 2
deps: depd@2\&.0\&.0
.IP "  \(bu" 4
Replace internal \fReval\fP usage with \fRFunction\fP constructor
.IP "  \(bu" 4
Use instance methods on \fRprocess\fP to check for listeners
.PP

.IP "\(bu" 2
deps: http-errors@2\&.0\&.0
.IP "  \(bu" 4
deps: depd@2\&.0\&.0
.IP "  \(bu" 4
deps: statuses@2\&.0\&.1
.PP

.IP "\(bu" 2
deps: on-finished@2\&.4\&.1
.IP "\(bu" 2
deps: qs@6.10\&.3
.IP "\(bu" 2
deps: raw-body@2\&.5\&.1
.IP "  \(bu" 4
deps: http-errors@2\&.0\&.0
.PP

.PP
.SH "1\&.19\&.2 / 2022-02-15"
.PP
.IP "\(bu" 2
deps: bytes@3\&.1\&.2
.IP "\(bu" 2
deps: qs@6\&.9\&.7
.IP "  \(bu" 4
Fix handling of \fR__proto__\fP keys
.PP

.IP "\(bu" 2
deps: raw-body@2\&.4\&.3
.IP "  \(bu" 4
deps: bytes@3\&.1\&.2
.PP

.PP
.SH "1\&.19\&.1 / 2021-12-10"
.PP
.IP "\(bu" 2
deps: bytes@3\&.1\&.1
.IP "\(bu" 2
deps: http-errors@1\&.8\&.1
.IP "  \(bu" 4
deps: inherits@2\&.0\&.4
.IP "  \(bu" 4
deps: toidentifier@1\&.0\&.1
.IP "  \(bu" 4
deps: setprototypeof@1\&.2\&.0
.PP

.IP "\(bu" 2
deps: qs@6\&.9\&.6
.IP "\(bu" 2
deps: raw-body@2\&.4\&.2
.IP "  \(bu" 4
deps: bytes@3\&.1\&.1
.IP "  \(bu" 4
deps: http-errors@1\&.8\&.1
.PP

.IP "\(bu" 2
deps: safe-buffer@5\&.2\&.1
.IP "\(bu" 2
deps: type-is1\&.6\&.18
.PP
.SH "1\&.19\&.0 / 2019-04-25"
.PP
.IP "\(bu" 2
deps: bytes@3\&.1\&.0
.IP "  \(bu" 4
Add petabyte (\fRpb\fP) support
.PP

.IP "\(bu" 2
deps: http-errors@1\&.7\&.2
.IP "  \(bu" 4
Set constructor name when possible
.IP "  \(bu" 4
deps: setprototypeof@1\&.1\&.1
.IP "  \(bu" 4
deps: statuses@'>= 1\&.5\&.0 < 2'
.PP

.IP "\(bu" 2
deps: iconv-lite@0.4.24
.IP "  \(bu" 4
Added encoding MIK
.PP

.IP "\(bu" 2
deps: qs@6\&.7\&.0
.IP "  \(bu" 4
Fix parsing array brackets after index
.PP

.IP "\(bu" 2
deps: raw-body@2\&.4\&.0
.IP "  \(bu" 4
deps: bytes@3\&.1\&.0
.IP "  \(bu" 4
deps: http-errors@1\&.7\&.2
.IP "  \(bu" 4
deps: iconv-lite@0.4.24
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.17
.IP "  \(bu" 4
deps: mime-types2\&.1\&.24
.IP "  \(bu" 4
perf: prevent internal \fRthrow\fP on invalid type
.PP

.PP
.SH "1\&.18\&.3 / 2018-05-14"
.PP
.IP "\(bu" 2
Fix stack trace for strict json parse error
.IP "\(bu" 2
deps: depd1\&.1\&.2
.IP "  \(bu" 4
perf: remove argument reassignment
.PP

.IP "\(bu" 2
deps: http-errors1\&.6\&.3
.IP "  \(bu" 4
deps: depd1\&.1\&.2
.IP "  \(bu" 4
deps: setprototypeof@1\&.1\&.0
.IP "  \(bu" 4
deps: statuses@'>= 1\&.3\&.1 < 2'
.PP

.IP "\(bu" 2
deps: iconv-lite@0.4.23
.IP "  \(bu" 4
Fix loading encoding with year appended
.IP "  \(bu" 4
Fix deprecation warnings on Node\&.js 10+
.PP

.IP "\(bu" 2
deps: qs@6\&.5\&.2
.IP "\(bu" 2
deps: raw-body@2\&.3\&.3
.IP "  \(bu" 4
deps: http-errors@1\&.6\&.3
.IP "  \(bu" 4
deps: iconv-lite@0.4.23
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.16
.IP "  \(bu" 4
deps: mime-types2\&.1\&.18
.PP

.PP
.SH "1\&.18\&.2 / 2017-09-22"
.PP
.IP "\(bu" 2
deps: debug@2\&.6\&.9
.IP "\(bu" 2
perf: remove argument reassignment
.PP
.SH "1\&.18\&.1 / 2017-09-12"
.PP
.IP "\(bu" 2
deps: content-type1\&.0\&.4
.IP "  \(bu" 4
perf: remove argument reassignment
.IP "  \(bu" 4
perf: skip parameter parsing when no parameters
.PP

.IP "\(bu" 2
deps: iconv-lite@0.4.19
.IP "  \(bu" 4
Fix ISO-8859-1 regression
.IP "  \(bu" 4
Update Windows-1255
.PP

.IP "\(bu" 2
deps: qs@6\&.5\&.1
.IP "  \(bu" 4
Fix parsing & compacting very deep objects
.PP

.IP "\(bu" 2
deps: raw-body@2\&.3\&.2
.IP "  \(bu" 4
deps: iconv-lite@0.4.19
.PP

.PP
.SH "1\&.18\&.0 / 2017-09-08"
.PP
.IP "\(bu" 2
Fix JSON strict violation error to match native parse error
.IP "\(bu" 2
Include the \fRbody\fP property on verify errors
.IP "\(bu" 2
Include the \fRtype\fP property on all generated errors
.IP "\(bu" 2
Use \fRhttp-errors\fP to set status code on errors
.IP "\(bu" 2
deps: bytes@3\&.0\&.0
.IP "\(bu" 2
deps: debug@2\&.6\&.8
.IP "\(bu" 2
deps: depd1\&.1\&.1
.IP "  \(bu" 4
Remove unnecessary \fRBuffer\fP loading
.PP

.IP "\(bu" 2
deps: http-errors1\&.6\&.2
.IP "  \(bu" 4
deps: depd@1\&.1\&.1
.PP

.IP "\(bu" 2
deps: iconv-lite@0.4.18
.IP "  \(bu" 4
Add support for React Native
.IP "  \(bu" 4
Add a warning if not loaded as utf-8
.IP "  \(bu" 4
Fix CESU-8 decoding in Node\&.js 8
.IP "  \(bu" 4
Improve speed of ISO-8859-1 encoding
.PP

.IP "\(bu" 2
deps: qs@6\&.5\&.0
.IP "\(bu" 2
deps: raw-body@2\&.3\&.1
.IP "  \(bu" 4
Use \fRhttp-errors\fP for standard emitted errors
.IP "  \(bu" 4
deps: bytes@3\&.0\&.0
.IP "  \(bu" 4
deps: iconv-lite@0.4.18
.IP "  \(bu" 4
perf: skip buffer decoding on overage chunk
.PP

.IP "\(bu" 2
perf: prevent internal \fRthrow\fP when missing charset
.PP
.SH "1\&.17\&.2 / 2017-05-17"
.PP
.IP "\(bu" 2
deps: debug@2\&.6\&.7
.IP "  \(bu" 4
Fix \fRDEBUG_MAX_ARRAY_LENGTH\fP
.IP "  \(bu" 4
deps: ms@2\&.0\&.0
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.15
.IP "  \(bu" 4
deps: mime-types2\&.1\&.15
.PP

.PP
.SH "1\&.17\&.1 / 2017-03-06"
.PP
.IP "\(bu" 2
deps: qs@6\&.4\&.0
.IP "  \(bu" 4
Fix regression parsing keys starting with \fR[\fP
.PP

.PP
.SH "1\&.17\&.0 / 2017-03-01"
.PP
.IP "\(bu" 2
deps: http-errors1\&.6\&.1
.IP "  \(bu" 4
Make \fRmessage\fP property enumerable for \fRHttpError\fPs
.IP "  \(bu" 4
deps: setprototypeof@1\&.0\&.3
.PP

.IP "\(bu" 2
deps: qs@6\&.3\&.1
.IP "  \(bu" 4
Fix compacting nested arrays
.PP

.PP
.SH "1\&.16\&.1 / 2017-02-10"
.PP
.IP "\(bu" 2
deps: debug@2\&.6\&.1
.IP "  \(bu" 4
Fix deprecation messages in WebStorm and other editors
.IP "  \(bu" 4
Undeprecate \fRDEBUG_FD\fP set to \fR1\fP or \fR2\fP
.PP

.PP
.SH "1\&.16\&.0 / 2017-01-17"
.PP
.IP "\(bu" 2
deps: debug@2\&.6\&.0
.IP "  \(bu" 4
Allow colors in workers
.IP "  \(bu" 4
Deprecated \fRDEBUG_FD\fP environment variable
.IP "  \(bu" 4
Fix error when running under React Native
.IP "  \(bu" 4
Use same color for same namespace
.IP "  \(bu" 4
deps: ms@0\&.7\&.2
.PP

.IP "\(bu" 2
deps: http-errors1\&.5\&.1
.IP "  \(bu" 4
deps: inherits@2\&.0\&.3
.IP "  \(bu" 4
deps: setprototypeof@1\&.0\&.2
.IP "  \(bu" 4
deps: statuses@'>= 1\&.3\&.1 < 2'
.PP

.IP "\(bu" 2
deps: iconv-lite@0.4.15
.IP "  \(bu" 4
Added encoding MS-31J
.IP "  \(bu" 4
Added encoding MS-932
.IP "  \(bu" 4
Added encoding MS-936
.IP "  \(bu" 4
Added encoding MS-949
.IP "  \(bu" 4
Added encoding MS-950
.IP "  \(bu" 4
Fix GBK/GB18030 handling of Euro character
.PP

.IP "\(bu" 2
deps: qs@6\&.2\&.1
.IP "  \(bu" 4
Fix array parsing from skipping empty values
.PP

.IP "\(bu" 2
deps: raw-body2\&.2\&.0
.IP "  \(bu" 4
deps: iconv-lite@0.4.15
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.14
.IP "  \(bu" 4
deps: mime-types2\&.1\&.13
.PP

.PP
.SH "1\&.15\&.2 / 2016-06-19"
.PP
.IP "\(bu" 2
deps: bytes@2\&.4\&.0
.IP "\(bu" 2
deps: content-type1\&.0\&.2
.IP "  \(bu" 4
perf: enable strict mode
.PP

.IP "\(bu" 2
deps: http-errors1\&.5\&.0
.IP "  \(bu" 4
Use \fRsetprototypeof\fP module to replace \fR__proto__\fP setting
.IP "  \(bu" 4
deps: statuses@'>= 1\&.3\&.0 < 2'
.IP "  \(bu" 4
perf: enable strict mode
.PP

.IP "\(bu" 2
deps: qs@6\&.2\&.0
.IP "\(bu" 2
deps: raw-body2\&.1\&.7
.IP "  \(bu" 4
deps: bytes@2\&.4\&.0
.IP "  \(bu" 4
perf: remove double-cleanup on happy path
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.13
.IP "  \(bu" 4
deps: mime-types2\&.1\&.11
.PP

.PP
.SH "1\&.15\&.1 / 2016-05-05"
.PP
.IP "\(bu" 2
deps: bytes@2\&.3\&.0
.IP "  \(bu" 4
Drop partial bytes on all parsed units
.IP "  \(bu" 4
Fix parsing byte string that looks like hex
.PP

.IP "\(bu" 2
deps: raw-body2\&.1\&.6
.IP "  \(bu" 4
deps: bytes@2\&.3\&.0
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.12
.IP "  \(bu" 4
deps: mime-types2\&.1\&.10
.PP

.PP
.SH "1\&.15\&.0 / 2016-02-10"
.PP
.IP "\(bu" 2
deps: http-errors1\&.4\&.0
.IP "  \(bu" 4
Add \fRHttpError\fP export, for \fRerr instanceof createError\&.HttpError\fP
.IP "  \(bu" 4
deps: inherits@2\&.0\&.1
.IP "  \(bu" 4
deps: statuses@'>= 1\&.2\&.1 < 2'
.PP

.IP "\(bu" 2
deps: qs@6\&.1\&.0
.IP "\(bu" 2
deps: type-is1\&.6\&.11
.IP "  \(bu" 4
deps: mime-types2\&.1\&.9
.PP

.PP
.SH "1\&.14\&.2 / 2015-12-16"
.PP
.IP "\(bu" 2
deps: bytes@2\&.2\&.0
.IP "\(bu" 2
deps: iconv-lite@0.4.13
.IP "\(bu" 2
deps: qs@5\&.2\&.0
.IP "\(bu" 2
deps: raw-body2\&.1\&.5
.IP "  \(bu" 4
deps: bytes@2\&.2\&.0
.IP "  \(bu" 4
deps: iconv-lite@0.4.13
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.10
.IP "  \(bu" 4
deps: mime-types2\&.1\&.8
.PP

.PP
.SH "1\&.14\&.1 / 2015-09-27"
.PP
.IP "\(bu" 2
Fix issue where invalid charset results in 400 when \fRverify\fP used
.IP "\(bu" 2
deps: iconv-lite@0.4.12
.IP "  \(bu" 4
Fix CESU-8 decoding in Node\&.js 4\&.x
.PP

.IP "\(bu" 2
deps: raw-body2\&.1\&.4
.IP "  \(bu" 4
Fix masking critical errors from \fRiconv-lite\fP
.IP "  \(bu" 4
deps: iconv-lite@0.4.12
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.9
.IP "  \(bu" 4
deps: mime-types2\&.1\&.7
.PP

.PP
.SH "1\&.14\&.0 / 2015-09-16"
.PP
.IP "\(bu" 2
Fix JSON strict parse error to match syntax errors
.IP "\(bu" 2
Provide static \fRrequire\fP analysis in \fRurlencoded\fP parser
.IP "\(bu" 2
deps: depd1\&.1\&.0
.IP "  \(bu" 4
Support web browser loading
.PP

.IP "\(bu" 2
deps: qs@5\&.1\&.0
.IP "\(bu" 2
deps: raw-body2\&.1\&.3
.IP "  \(bu" 4
Fix sync callback when attaching data listener causes sync read
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.8
.IP "  \(bu" 4
Fix type error when given invalid type to match against
.IP "  \(bu" 4
deps: mime-types2\&.1\&.6
.PP

.PP
.SH "1\&.13\&.3 / 2015-07-31"
.PP
.IP "\(bu" 2
deps: type-is1\&.6\&.6
.IP "  \(bu" 4
deps: mime-types2\&.1\&.4
.PP

.PP
.SH "1\&.13\&.2 / 2015-07-05"
.PP
.IP "\(bu" 2
deps: iconv-lite@0.4.11
.IP "\(bu" 2
deps: qs@4\&.0\&.0
.IP "  \(bu" 4
Fix dropping parameters like \fRhasOwnProperty\fP
.IP "  \(bu" 4
Fix user-visible incompatibilities from 3\&.1\&.0
.IP "  \(bu" 4
Fix various parsing edge cases
.PP

.IP "\(bu" 2
deps: raw-body2\&.1\&.2
.IP "  \(bu" 4
Fix error stack traces to skip \fRmakeError\fP
.IP "  \(bu" 4
deps: iconv-lite@0.4.11
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.4
.IP "  \(bu" 4
deps: mime-types2\&.1\&.2
.IP "  \(bu" 4
perf: enable strict mode
.IP "  \(bu" 4
perf: remove argument reassignment
.PP

.PP
.SH "1\&.13\&.1 / 2015-06-16"
.PP
.IP "\(bu" 2
deps: qs@2\&.4\&.2
.IP "  \(bu" 4
Downgraded from 3\&.1\&.0 because of user-visible incompatibilities
.PP

.PP
.SH "1\&.13\&.0 / 2015-06-14"
.PP
.IP "\(bu" 2
Add \fRstatusCode\fP property on \fRError\fPs, in addition to \fRstatus\fP
.IP "\(bu" 2
Change \fRtype\fP default to \fRapplication/json\fP for JSON parser
.IP "\(bu" 2
Change \fRtype\fP default to \fRapplication/x-www-form-urlencoded\fP for urlencoded parser
.IP "\(bu" 2
Provide static \fRrequire\fP analysis
.IP "\(bu" 2
Use the \fRhttp-errors\fP module to generate errors
.IP "\(bu" 2
deps: bytes@2\&.1\&.0
.IP "  \(bu" 4
Slight optimizations
.PP

.IP "\(bu" 2
deps: iconv-lite@0.4.10
.IP "  \(bu" 4
The encoding UTF-16 without BOM now defaults to UTF-16LE when detection fails
.IP "  \(bu" 4
Leading BOM is now removed when decoding
.PP

.IP "\(bu" 2
deps: on-finished2\&.3\&.0
.IP "  \(bu" 4
Add defined behavior for HTTP \fRCONNECT\fP requests
.IP "  \(bu" 4
Add defined behavior for HTTP \fRUpgrade\fP requests
.IP "  \(bu" 4
deps: ee-first@1\&.1\&.1
.PP

.IP "\(bu" 2
deps: qs@3\&.1\&.0
.IP "  \(bu" 4
Fix dropping parameters like \fRhasOwnProperty\fP
.IP "  \(bu" 4
Fix various parsing edge cases
.IP "  \(bu" 4
Parsed object now has \fRnull\fP prototype
.PP

.IP "\(bu" 2
deps: raw-body2\&.1\&.1
.IP "  \(bu" 4
Use \fRunpipe\fP module for unpiping requests
.IP "  \(bu" 4
deps: iconv-lite@0.4.10
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.3
.IP "  \(bu" 4
deps: mime-types2\&.1\&.1
.IP "  \(bu" 4
perf: reduce try block size
.IP "  \(bu" 4
perf: remove bitwise operations
.PP

.IP "\(bu" 2
perf: enable strict mode
.IP "\(bu" 2
perf: remove argument reassignment
.IP "\(bu" 2
perf: remove delete call
.PP
.SH "1\&.12\&.4 / 2015-05-10"
.PP
.IP "\(bu" 2
deps: debug2\&.2\&.0
.IP "\(bu" 2
deps: qs@2\&.4\&.2
.IP "  \(bu" 4
Fix allowing parameters like \fRconstructor\fP
.PP

.IP "\(bu" 2
deps: on-finished2\&.2\&.1
.IP "\(bu" 2
deps: raw-body2\&.0\&.1
.IP "  \(bu" 4
Fix a false-positive when unpiping in Node\&.js 0\&.8
.IP "  \(bu" 4
deps: bytes@2\&.0\&.1
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.2
.IP "  \(bu" 4
deps: mime-types2\&.0\&.11
.PP

.PP
.SH "1\&.12\&.3 / 2015-04-15"
.PP
.IP "\(bu" 2
Slight efficiency improvement when not debugging
.IP "\(bu" 2
deps: depd1\&.0\&.1
.IP "\(bu" 2
deps: iconv-lite@0\&.4\&.8
.IP "  \(bu" 4
Add encoding alias UNICODE-1-1-UTF-7
.PP

.IP "\(bu" 2
deps: raw-body@1\&.3\&.4
.IP "  \(bu" 4
Fix hanging callback if request aborts during read
.IP "  \(bu" 4
deps: iconv-lite@0\&.4\&.8
.PP

.PP
.SH "1\&.12\&.2 / 2015-03-16"
.PP
.IP "\(bu" 2
deps: qs@2\&.4\&.1
.IP "  \(bu" 4
Fix error when parameter \fRhasOwnProperty\fP is present
.PP

.PP
.SH "1\&.12\&.1 / 2015-03-15"
.PP
.IP "\(bu" 2
deps: debug2\&.1\&.3
.IP "  \(bu" 4
Fix high intensity foreground color for bold
.IP "  \(bu" 4
deps: ms@0\&.7\&.0
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.1
.IP "  \(bu" 4
deps: mime-types2\&.0\&.10
.PP

.PP
.SH "1\&.12\&.0 / 2015-02-13"
.PP
.IP "\(bu" 2
add \fRdebug\fP messages
.IP "\(bu" 2
accept a function for the \fRtype\fP option
.IP "\(bu" 2
use \fRcontent-type\fP to parse \fRContent-Type\fP headers
.IP "\(bu" 2
deps: iconv-lite@0\&.4\&.7
.IP "  \(bu" 4
Gracefully support enumerables on \fRObject\&.prototype\fP
.PP

.IP "\(bu" 2
deps: raw-body@1\&.3\&.3
.IP "  \(bu" 4
deps: iconv-lite@0\&.4\&.7
.PP

.IP "\(bu" 2
deps: type-is1\&.6\&.0
.IP "  \(bu" 4
fix argument reassignment
.IP "  \(bu" 4
fix false-positives in \fRhasBody\fP \fRTransfer-Encoding\fP check
.IP "  \(bu" 4
support wildcard for both type and subtype (\fR*/*\fP)
.IP "  \(bu" 4
deps: mime-types2\&.0\&.9
.PP

.PP
.SH "1\&.11\&.0 / 2015-01-30"
.PP
.IP "\(bu" 2
make internal \fRextended: true\fP depth limit infinity
.IP "\(bu" 2
deps: type-is1\&.5\&.6
.IP "  \(bu" 4
deps: mime-types2\&.0\&.8
.PP

.PP
.SH "1\&.10\&.2 / 2015-01-20"
.PP
.IP "\(bu" 2
deps: iconv-lite@0\&.4\&.6
.IP "  \(bu" 4
Fix rare aliases of single-byte encodings
.PP

.IP "\(bu" 2
deps: raw-body@1\&.3\&.2
.IP "  \(bu" 4
deps: iconv-lite@0\&.4\&.6
.PP

.PP
.SH "1\&.10\&.1 / 2015-01-01"
.PP
.IP "\(bu" 2
deps: on-finished2\&.2\&.0
.IP "\(bu" 2
deps: type-is1\&.5\&.5
.IP "  \(bu" 4
deps: mime-types2\&.0\&.7
.PP

.PP
.SH "1\&.10\&.0 / 2014-12-02"
.PP
.IP "\(bu" 2
make internal \fRextended: true\fP array limit dynamic
.PP
.SH "1\&.9\&.3 / 2014-11-21"
.PP
.IP "\(bu" 2
deps: iconv-lite@0\&.4\&.5
.IP "  \(bu" 4
Fix Windows-31J and X-SJIS encoding support
.PP

.IP "\(bu" 2
deps: qs@2\&.3\&.3
.IP "  \(bu" 4
Fix \fRarrayLimit\fP behavior
.PP

.IP "\(bu" 2
deps: raw-body@1\&.3\&.1
.IP "  \(bu" 4
deps: iconv-lite@0\&.4\&.5
.PP

.IP "\(bu" 2
deps: type-is1\&.5\&.3
.IP "  \(bu" 4
deps: mime-types2\&.0\&.3
.PP

.PP
.SH "1\&.9\&.2 / 2014-10-27"
.PP
.IP "\(bu" 2
deps: qs@2\&.3\&.2
.IP "  \(bu" 4
Fix parsing of mixed objects and values
.PP

.PP
.SH "1\&.9\&.1 / 2014-10-22"
.PP
.IP "\(bu" 2
deps: on-finished2\&.1\&.1
.IP "  \(bu" 4
Fix handling of pipelined requests
.PP

.IP "\(bu" 2
deps: qs@2\&.3\&.0
.IP "  \(bu" 4
Fix parsing of mixed implicit and explicit arrays
.PP

.IP "\(bu" 2
deps: type-is1\&.5\&.2
.IP "  \(bu" 4
deps: mime-types2\&.0\&.2
.PP

.PP
.SH "1\&.9\&.0 / 2014-09-24"
.PP
.IP "\(bu" 2
include the charset in 'unsupported charset' error message
.IP "\(bu" 2
include the encoding in 'unsupported content encoding' error message
.IP "\(bu" 2
deps: depd1\&.0\&.0
.PP
.SH "1\&.8\&.4 / 2014-09-23"
.PP
.IP "\(bu" 2
fix content encoding to be case-insensitive
.PP
.SH "1\&.8\&.3 / 2014-09-19"
.PP
.IP "\(bu" 2
deps: qs@2\&.2\&.4
.IP "  \(bu" 4
Fix issue with object keys starting with numbers truncated
.PP

.PP
.SH "1\&.8\&.2 / 2014-09-15"
.PP
.IP "\(bu" 2
deps: depd@0\&.4\&.5
.PP
.SH "1\&.8\&.1 / 2014-09-07"
.PP
.IP "\(bu" 2
deps: media-typer@0\&.3\&.0
.IP "\(bu" 2
deps: type-is1\&.5\&.1
.PP
.SH "1\&.8\&.0 / 2014-09-05"
.PP
.IP "\(bu" 2
make empty-body-handling consistent between chunked requests
.IP "  \(bu" 4
empty \fRjson\fP produces \fR{}\fP
.IP "  \(bu" 4
empty \fRraw\fP produces \fRnew Buffer(0)\fP
.IP "  \(bu" 4
empty \fRtext\fP produces `''\fR\fP
.IP "  \(bu" 4
\fRempty\fPurlencoded\fRproduces\fP{}\fR\fP
.PP

.IP "\(bu" 2
\fRdeps: qs@2\&.2\&.3
.IP "  \(bu" 4
Fix issue where first empty value in array is discarded
.PP
\fP
.IP "\(bu" 2
\fRdeps: type-is@~1\&.5\&.0
.IP "  \(bu" 4
fix
.PP
\fPhasbody\fRto be true for\fPcontent-length: 0`
.PP
.SH "1\&.7\&.0 / 2014-09-01"
.PP
.IP "\(bu" 2
add \fRparameterLimit\fP option to \fRurlencoded\fP parser
.IP "\(bu" 2
change \fRurlencoded\fP extended array limit to 100
.IP "\(bu" 2
respond with 413 when over \fRparameterLimit\fP in \fRurlencoded\fP
.PP
.SH "1\&.6\&.7 / 2014-08-29"
.PP
.IP "\(bu" 2
deps: qs@2\&.2\&.2
.IP "  \(bu" 4
Remove unnecessary cloning
.PP

.PP
.SH "1\&.6\&.6 / 2014-08-27"
.PP
.IP "\(bu" 2
deps: qs@2\&.2\&.0
.IP "  \(bu" 4
Array parsing fix
.IP "  \(bu" 4
Performance improvements
.PP

.PP
.SH "1\&.6\&.5 / 2014-08-16"
.PP
.IP "\(bu" 2
deps: on-finished@2\&.1\&.0
.PP
.SH "1\&.6\&.4 / 2014-08-14"
.PP
.IP "\(bu" 2
deps: qs@1\&.2\&.2
.PP
.SH "1\&.6\&.3 / 2014-08-10"
.PP
.IP "\(bu" 2
deps: qs@1\&.2\&.1
.PP
.SH "1\&.6\&.2 / 2014-08-07"
.PP
.IP "\(bu" 2
deps: qs@1\&.2\&.0
.IP "  \(bu" 4
Fix parsing array of objects
.PP

.PP
.SH "1\&.6\&.1 / 2014-08-06"
.PP
.IP "\(bu" 2
deps: qs@1\&.1\&.0
.IP "  \(bu" 4
Accept urlencoded square brackets
.IP "  \(bu" 4
Accept empty values in implicit array notation
.PP

.PP
.SH "1\&.6\&.0 / 2014-08-05"
.PP
.IP "\(bu" 2
deps: qs@1\&.0\&.2
.IP "  \(bu" 4
Complete rewrite
.IP "  \(bu" 4
Limits array length to 20
.IP "  \(bu" 4
Limits object depth to 5
.IP "  \(bu" 4
Limits parameters to 1,000
.PP

.PP
.SH "1\&.5\&.2 / 2014-07-27"
.PP
.IP "\(bu" 2
deps: depd@0\&.4\&.4
.IP "  \(bu" 4
Work-around v8 generating empty stack traces
.PP

.PP
.SH "1\&.5\&.1 / 2014-07-26"
.PP
.IP "\(bu" 2
deps: depd@0\&.4\&.3
.IP "  \(bu" 4
Fix exception when global \fRError\&.stackTraceLimit\fP is too low
.PP

.PP
.SH "1\&.5\&.0 / 2014-07-20"
.PP
.IP "\(bu" 2
deps: depd@0\&.4\&.2
.IP "  \(bu" 4
Add \fRTRACE_DEPRECATION\fP environment variable
.IP "  \(bu" 4
Remove non-standard grey color from color output
.IP "  \(bu" 4
Support \fR--no-deprecation\fP argument
.IP "  \(bu" 4
Support \fR--trace-deprecation\fP argument
.PP

.IP "\(bu" 2
deps: iconv-lite@0\&.4\&.4
.IP "  \(bu" 4
Added encoding UTF-7
.PP

.IP "\(bu" 2
deps: raw-body@1\&.3\&.0
.IP "  \(bu" 4
deps: iconv-lite@0\&.4\&.4
.IP "  \(bu" 4
Added encoding UTF-7
.IP "  \(bu" 4
Fix \fRCannot switch to old mode now\fP error on Node\&.js 0\&.10+
.PP

.IP "\(bu" 2
deps: type-is1\&.3\&.2
.PP
.SH "1\&.4\&.3 / 2014-06-19"
.PP
.IP "\(bu" 2
deps: type-is@1\&.3\&.1
.IP "  \(bu" 4
fix global variable leak
.PP

.PP
.SH "1\&.4\&.2 / 2014-06-19"
.PP
.IP "\(bu" 2
deps: type-is@1\&.3\&.0
.IP "  \(bu" 4
improve type parsing
.PP

.PP
.SH "1\&.4\&.1 / 2014-06-19"
.PP
.IP "\(bu" 2
fix urlencoded extended deprecation message
.PP
.SH "1\&.4\&.0 / 2014-06-19"
.PP
.IP "\(bu" 2
add \fRtext\fP parser
.IP "\(bu" 2
add \fRraw\fP parser
.IP "\(bu" 2
check accepted charset in content-type (accepts utf-8)
.IP "\(bu" 2
check accepted encoding in content-encoding (accepts identity)
.IP "\(bu" 2
deprecate \fRbodyParser()\fP middleware; use \fR\&.json()\fP and \fR\&.urlencoded()\fP as needed
.IP "\(bu" 2
deprecate \fRurlencoded()\fP without provided \fRextended\fP option
.IP "\(bu" 2
lazy-load urlencoded parsers
.IP "\(bu" 2
parsers split into files for reduced mem usage
.IP "\(bu" 2
support gzip and deflate bodies
.IP "  \(bu" 4
set \fRinflate: false\fP to turn off
.PP

.IP "\(bu" 2
deps: raw-body@1\&.2\&.2
.IP "  \(bu" 4
Support all encodings from \fRiconv-lite\fP
.PP

.PP
.SH "1\&.3\&.1 / 2014-06-11"
.PP
.IP "\(bu" 2
deps: type-is@1\&.2\&.1
.IP "  \(bu" 4
Switch dependency from mime to mime-types@1\&.0\&.0
.PP

.PP
.SH "1\&.3\&.0 / 2014-05-31"
.PP
.IP "\(bu" 2
add \fRextended\fP option to urlencoded parser
.PP
.SH "1\&.2\&.2 / 2014-05-27"
.PP
.IP "\(bu" 2
deps: raw-body@1\&.1\&.6
.IP "  \(bu" 4
assert stream encoding on node\&.js 0\&.8
.IP "  \(bu" 4
assert stream encoding on node\&.js < 0\&.10\&.6
.IP "  \(bu" 4
deps: bytes@1
.PP

.PP
.SH "1\&.2\&.1 / 2014-05-26"
.PP
.IP "\(bu" 2
invoke \fRnext(err)\fP after request fully read
.IP "  \(bu" 4
prevents hung responses and socket hang ups
.PP

.PP
.SH "1\&.2\&.0 / 2014-05-11"
.PP
.IP "\(bu" 2
add \fRverify\fP option
.IP "\(bu" 2
deps: type-is@1\&.2\&.0
.IP "  \(bu" 4
support suffix matching
.PP

.PP
.SH "1\&.1\&.2 / 2014-05-11"
.PP
.IP "\(bu" 2
improve json parser speed
.PP
.SH "1\&.1\&.1 / 2014-05-11"
.PP
.IP "\(bu" 2
fix repeated limit parsing with every request
.PP
.SH "1\&.1\&.0 / 2014-05-10"
.PP
.IP "\(bu" 2
add \fRtype\fP option
.IP "\(bu" 2
deps: pin for safety and consistency
.PP
.SH "1\&.0\&.2 / 2014-04-14"
.PP
.IP "\(bu" 2
use \fRtype-is\fP module
.PP
.SH "1\&.0\&.1 / 2014-03-20"
.PP
.IP "\(bu" 2
lower default limits to 100kb 
.PP

