.TH "md_backend_2node__modules_2path-is-absolute_2readme" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2path-is-absolute_2readme \- path-is-absolute \fR\fP 
.PP
 
.PP
.RS 4
Node\&.js 0\&.12 \fR\fRpath\&.isAbsolute()\fP\fP \fRponyfill\fP 
.RE
.PP
.SH "Install"
.PP
.PP
.nf
$ npm install \-\-save path\-is\-absolute
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
const pathIsAbsolute = require('path\-is\-absolute');

// Running on Linux
pathIsAbsolute('/home/foo');
//=> true
pathIsAbsolute('C:/Users/foo');
//=> false

// Running on Windows
pathIsAbsolute('C:/Users/foo');
//=> true
pathIsAbsolute('/home/foo');
//=> false

// Running on any OS
pathIsAbsolute\&.posix('/home/foo');
//=> true
pathIsAbsolute\&.posix('C:/Users/foo');
//=> false
pathIsAbsolute\&.win32('C:/Users/foo');
//=> true
pathIsAbsolute\&.win32('/home/foo');
//=> false
.fi
.PP
.SH "API"
.PP
See the \fR\fRpath\&.isAbsolute()\fP docs\fP\&.
.SS "pathIsAbsolute(path)"
.SS "pathIsAbsolute\&.posix(path)"
POSIX specific version\&.
.SS "pathIsAbsolute\&.win32(path)"
Windows specific version\&.
.SH "License"
.PP
MIT © \fRSindre Sorhus\fP 
