.TH "md_backend_2node__modules_2type-is_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2type-is_2_h_i_s_t_o_r_y \- 1\&.6\&.18 / 2019-04-26 
.PP

.IP "\(bu" 2
Fix regression passing request object to \fRtypeis\&.is\fP
.PP
.SH "1\&.6\&.17 / 2019-04-25"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.24
.IP "  \(bu" 4
Add Apple file extensions from IANA
.IP "  \(bu" 4
Add extension \fR\&.csl\fP to \fRapplication/vnd\&.citationstyles\&.style+xml\fP
.IP "  \(bu" 4
Add extension \fR\&.es\fP to \fRapplication/ecmascript\fP
.IP "  \(bu" 4
Add extension \fR\&.nq\fP to \fRapplication/n-quads\fP
.IP "  \(bu" 4
Add extension \fR\&.nt\fP to \fRapplication/n-triples\fP
.IP "  \(bu" 4
Add extension \fR\&.owl\fP to \fRapplication/rdf+xml\fP
.IP "  \(bu" 4
Add extensions \fR\&.siv\fP and \fR\&.sieve\fP to \fRapplication/sieve\fP
.IP "  \(bu" 4
Add extensions from IANA for \fRimage/*\fP types
.IP "  \(bu" 4
Add extensions from IANA for \fRmodel/*\fP types
.IP "  \(bu" 4
Add extensions to HEIC image types
.IP "  \(bu" 4
Add new mime types
.IP "  \(bu" 4
Add \fRtext/mdx\fP with extension \fR\&.mdx\fP
.PP

.IP "\(bu" 2
perf: prevent internal \fRthrow\fP on invalid type
.PP
.SH "1\&.6\&.16 / 2018-02-16"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.18
.IP "  \(bu" 4
Add \fRapplication/raml+yaml\fP with extension \fR\&.raml\fP
.IP "  \(bu" 4
Add \fRapplication/wasm\fP with extension \fR\&.wasm\fP
.IP "  \(bu" 4
Add \fRtext/shex\fP with extension \fR\&.shex\fP
.IP "  \(bu" 4
Add extensions for JPEG-2000 images
.IP "  \(bu" 4
Add extensions from IANA for \fRmessage/*\fP types
.IP "  \(bu" 4
Add extension \fR\&.mjs\fP to \fRapplication/javascript\fP
.IP "  \(bu" 4
Add extension \fR\&.wadl\fP to \fRapplication/vnd\&.sun\&.wadl+xml\fP
.IP "  \(bu" 4
Add extension \fR\&.gz\fP to \fRapplication/gzip\fP
.IP "  \(bu" 4
Add glTF types and extensions
.IP "  \(bu" 4
Add new mime types
.IP "  \(bu" 4
Update extensions \fR\&.md\fP and \fR\&.markdown\fP to be \fRtext/markdown\fP
.IP "  \(bu" 4
Update font MIME types
.IP "  \(bu" 4
Update \fRtext/hjson\fP to registered \fRapplication/hjson\fP
.PP

.PP
.SH "1\&.6\&.15 / 2017-03-31"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.15
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.14 / 2016-11-18"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.13
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.13 / 2016-05-18"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.11
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.12 / 2016-02-28"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.10
.IP "  \(bu" 4
Add new mime types
.IP "  \(bu" 4
Fix extension of \fRapplication/dash+xml\fP
.IP "  \(bu" 4
Update primary extension for \fRaudio/mp4\fP
.PP

.PP
.SH "1\&.6\&.11 / 2016-01-29"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.9
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.10 / 2015-12-01"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.8
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.9 / 2015-09-27"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.7
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.8 / 2015-09-04"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.6
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.7 / 2015-08-20"
.PP
.IP "\(bu" 2
Fix type error when given invalid type to match against
.IP "\(bu" 2
deps: mime-types2\&.1\&.5
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.6 / 2015-07-31"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.4
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.5 / 2015-07-16"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.3
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.4 / 2015-07-01"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.2
.IP "  \(bu" 4
Add new mime types
.PP

.IP "\(bu" 2
perf: enable strict mode
.IP "\(bu" 2
perf: remove argument reassignment
.PP
.SH "1\&.6\&.3 / 2015-06-08"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.1
.IP "  \(bu" 4
Add new mime types
.PP

.IP "\(bu" 2
perf: reduce try block size
.IP "\(bu" 2
perf: remove bitwise operations
.PP
.SH "1\&.6\&.2 / 2015-05-10"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.11
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.1 / 2015-03-13"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.10
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.6\&.0 / 2015-02-12"
.PP
.IP "\(bu" 2
fix false-positives in \fRhasBody\fP \fRTransfer-Encoding\fP check
.IP "\(bu" 2
support wildcard for both type and subtype (\fR*/*\fP)
.PP
.SH "1\&.5\&.7 / 2015-02-09"
.PP
.IP "\(bu" 2
fix argument reassignment
.IP "\(bu" 2
deps: mime-types2\&.0\&.9
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.5\&.6 / 2015-01-29"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.8
.IP "  \(bu" 4
Add new mime types
.PP

.PP
.SH "1\&.5\&.5 / 2014-12-30"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.7
.IP "  \(bu" 4
Add new mime types
.IP "  \(bu" 4
Fix missing extensions
.IP "  \(bu" 4
Fix various invalid MIME type entries
.IP "  \(bu" 4
Remove example template MIME types
.IP "  \(bu" 4
deps: mime-db1\&.5\&.0
.PP

.PP
.SH "1\&.5\&.4 / 2014-12-10"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.4
.IP "  \(bu" 4
Add new mime types
.IP "  \(bu" 4
deps: mime-db1\&.3\&.0
.PP

.PP
.SH "1\&.5\&.3 / 2014-11-09"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.3
.IP "  \(bu" 4
Add new mime types
.IP "  \(bu" 4
deps: mime-db1\&.2\&.0
.PP

.PP
.SH "1\&.5\&.2 / 2014-09-28"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.2
.IP "  \(bu" 4
Add new mime types
.IP "  \(bu" 4
deps: mime-db1\&.1\&.0
.PP

.PP
.SH "1\&.5\&.1 / 2014-09-07"
.PP
.IP "\(bu" 2
Support Node\&.js 0\&.6
.IP "\(bu" 2
deps: media-typer@0\&.3\&.0
.IP "\(bu" 2
deps: mime-types2\&.0\&.1
.IP "  \(bu" 4
Support Node\&.js 0\&.6
.PP

.PP
.SH "1\&.5\&.0 / 2014-09-05"
.PP
.IP "\(bu" 2
fix \fRhasbody\fP to be true for \fRcontent-length: 0\fP
.PP
.SH "1\&.4\&.0 / 2014-09-02"
.PP
.IP "\(bu" 2
update mime-types
.PP
.SH "1\&.3\&.2 / 2014-06-24"
.PP
.IP "\(bu" 2
use \fR~\fP range on mime-types
.PP
.SH "1\&.3\&.1 / 2014-06-19"
.PP
.IP "\(bu" 2
fix global variable leak
.PP
.SH "1\&.3\&.0 / 2014-06-19"
.PP
.IP "\(bu" 2
improve type parsing
.IP "  \(bu" 4
invalid media type never matches
.IP "  \(bu" 4
media type not case-sensitive
.IP "  \(bu" 4
extra LWS does not affect results
.PP

.PP
.SH "1\&.2\&.2 / 2014-06-19"
.PP
.IP "\(bu" 2
fix behavior on unknown type argument
.PP
.SH "1\&.2\&.1 / 2014-06-03"
.PP
.IP "\(bu" 2
switch dependency from \fRmime\fP to \fRmime-types@1\&.0\&.0\fP
.PP
.SH "1\&.2\&.0 / 2014-05-11"
.PP
.IP "\(bu" 2
support suffix matching:
.IP "  \(bu" 4
\fR+json\fP matches \fRapplication/vnd+json\fP
.IP "  \(bu" 4
\fR*/vnd+json\fP matches \fRapplication/vnd+json\fP
.IP "  \(bu" 4
\fRapplication/*+json\fP matches \fRapplication/vnd+json\fP
.PP

.PP
.SH "1\&.1\&.0 / 2014-04-12"
.PP
.IP "\(bu" 2
add non-array values support
.IP "\(bu" 2
expose internal utilities:
.IP "  \(bu" 4
\fR\&.is()\fP
.IP "  \(bu" 4
\fR\&.hasBody()\fP
.IP "  \(bu" 4
\fR\&.normalize()\fP
.IP "  \(bu" 4
\fR\&.match()\fP
.PP

.PP
.SH "1\&.0\&.1 / 2014-03-30"
.PP
.IP "\(bu" 2
add \fRmultipart\fP as a shorthand 
.PP

