.TH "md_backend_2node__modules_2methods_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2methods_2_r_e_a_d_m_e \- Methods 
.PP
 \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP
.PP
HTTP verbs that Node\&.js core's HTTP parser supports\&.
.PP
This module provides an export that is just like \fRhttp\&.METHODS\fP from Node\&.js core, with the following differences:
.PP
.IP "\(bu" 2
All method names are lower-cased\&.
.IP "\(bu" 2
Contains a fallback list of methods for Node\&.js versions that do not have a \fRhttp\&.METHODS\fP export (0\&.10 and lower)\&.
.IP "\(bu" 2
Provides the fallback list when using tools like \fRbrowserify\fP without pulling in the \fRhttp\fP shim module\&.
.PP
.SH "Install"
.PP
.PP
.nf
$ npm install methods
.fi
.PP
.SH "API"
.PP
.PP
.nf
var methods = require('methods')
.fi
.PP
.SS "methods"
This is an array of lower-cased method names that Node\&.js supports\&. If Node\&.js provides the \fRhttp\&.METHODS\fP export, then this is the same array lower-cased, otherwise it is a snapshot of the verbs from Node\&.js 0\&.10\&.
.SH "License"
.PP
[MIT](LICENSE) 
