.TH "md_backend_2node__modules_2debug_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2debug_2_r_e_a_d_m_e \- debug 
.PP
\fR\fP \fR\fP \fR\fP \fB![OpenCollective](https://opencollective\&.com/debug/backers/badge\&.svg)\fP \fB![OpenCollective](https://opencollective\&.com/debug/sponsors/badge\&.svg)\fP
.PP
A tiny node\&.js debugging utility modelled after node core's debugging technique\&.
.PP
\fBDiscussion around the V3 API is under way \fRhere\fP\fP
.SH "Installation"
.PP
.PP
.nf
$ npm install debug
.fi
.PP
.SH "Usage"
.PP
\fRdebug\fP exposes a function; simply pass this function the name of your module, and it will return a decorated version of \fRconsole\&.error\fP for you to pass debug statements to\&. This will allow you to toggle the debug output for different parts of your module as well as the module as a whole\&.
.PP
Example \fIapp\&.js\fP:
.PP
.PP
.nf
var debug = require('debug')('http')
  , http = require('http')
  , name = 'My App';

// fake app

debug('booting %s', name);

http\&.createServer(function(req, res){
  debug(req\&.method + ' ' + req\&.url);
  res\&.end('hello\\n');
})\&.listen(3000, function(){
  debug('listening');
});

// fake worker of some kind

require('\&./worker');
.fi
.PP
.PP
Example \fIworker\&.js\fP:
.PP
.PP
.nf
var debug = require('debug')('worker');

setInterval(function(){
  debug('doing some work');
}, 1000);
.fi
.PP
.PP
The \fBDEBUG\fP environment variable is then used to enable these based on space or comma-delimited names\&. Here are some examples:
.PP
.PP
.SS "Windows note"
On Windows the environment variable is set using the \fRset\fP command\&.
.PP
.PP
.nf
set DEBUG=*,\-not_this
.fi
.PP
.PP
Note that PowerShell uses different syntax to set environment variables\&.
.PP
.PP
.nf
$env:DEBUG = "*,\-not_this"
.fi
.PP
.PP
Then, run the program to be debugged as usual\&.
.SH "Millisecond diff"
.PP
When actively developing an application it can be useful to see when the time spent between one \fRdebug()\fP call and the next\&. Suppose for example you invoke \fRdebug()\fP before requesting a resource, and after as well, the '+NNNms' will show you how much time was spent between calls\&.
.PP
.PP
When stdout is not a TTY, \fRDate#toUTCString()\fP is used, making it more useful for logging the debug information as shown below:
.PP
.SH "Conventions"
.PP
If you're using this in one or more of your libraries, you \fIshould\fP use the name of your library so that developers may toggle debugging as desired without guessing names\&. If you have more than one debuggers you \fIshould\fP prefix them with your library name and use ':' to separate features\&. For example 'bodyParser' from Connect would then be 'connect:bodyParser'\&.
.SH "Wildcards"
.PP
The \fR*\fP character may be used as a wildcard\&. Suppose for example your library has debuggers named 'connect:bodyParser', 'connect:compress', 'connect:session', instead of listing all three with \fRDEBUG=connect:bodyParser,connect:compress,connect:session\fP, you may simply do \fRDEBUG=connect:*\fP, or to run everything using this module simply use \fRDEBUG=*\fP\&.
.PP
You can also exclude specific debuggers by prefixing them with a '-' character\&. For example, \fRDEBUG=*,-connect:*\fP would include all debuggers except those starting with 'connect:'\&.
.SH "Environment Variables"
.PP
When running through Node\&.js, you can set a few environment variables that will change the behavior of the debug logging:
.PP
Name   Purpose    \fRDEBUG\fP   Enables/disables specific debugging namespaces\&.    \fRDEBUG_COLORS\fP   Whether or not to use colors in the debug output\&.    \fRDEBUG_DEPTH\fP   Object inspection depth\&.    \fRDEBUG_SHOW_HIDDEN\fP   Shows hidden properties on inspected objects\&.   
.PP
\fBNote:\fP The environment variables beginning with \fRDEBUG_\fP end up being converted into an Options object that gets used with \fRo\fP/\fRO\fP formatters\&. See the Node\&.js documentation for \fR\fRutil\&.inspect()\fP\fP for the complete list\&.
.SH "Formatters"
.PP
Debug uses \fRprintf-style\fP formatting\&. Below are the officially supported formatters:
.PP
Formatter   Representation    \fRO\fP   Pretty-print an Object on multiple lines\&.    \fRo\fP   Pretty-print an Object all on a single line\&.    \fRs\fP   String\&.    \fRd\fP   Number (both integer and float)\&.    \fRj\fP   JSON\&. Replaced with the string '[Circular]' if the argument contains circular references\&.    \fR%%\fP   Single percent sign ('')\&. This does not consume an argument\&.   
.SS "Custom formatters"
You can add custom formatters by extending the \fRdebug\&.formatters\fP object\&. For example, if you wanted to add support for rendering a Buffer as hex with \fRh\fP, you could do something like:
.PP
.PP
.nf
const createDebug = require('debug')
createDebug\&.formatters\&.h = (v) => {
  return v\&.toString('hex')
}

// …elsewhere
const debug = createDebug('foo')
debug('this is hex: %h', new Buffer('hello world'))
//   foo this is hex: 68656c6c6f20776f726c6421 +0ms
.fi
.PP
.SH "Browser support"
.PP
You can build a browser-ready script using \fRbrowserify\fP, or just use the \fRbrowserify-as-a-service\fP \fRbuild\fP, if you don't want to build it yourself\&.
.PP
Debug's enable state is currently persisted by \fRlocalStorage\fP\&. Consider the situation shown below where you have \fRworker:a\fP and \fRworker:b\fP, and wish to debug both\&. You can enable this using \fRlocalStorage\&.debug\fP:
.PP
.PP
.nf
localStorage\&.debug = 'worker:*'
.fi
.PP
.PP
And then refresh the page\&.
.PP
.PP
.nf
a = debug('worker:a');
b = debug('worker:b');

setInterval(function(){
  a('doing some work');
}, 1000);

setInterval(function(){
  b('doing some work');
}, 1200);
.fi
.PP
.SS "Web Inspector Colors"
Colors are also enabled on 'Web Inspectors' that understand the \fRc\fP formatting option\&. These are WebKit web inspectors, Firefox (\fRsince version 31\fP) and the Firebug plugin for Firefox (any version)\&.
.PP
Colored output looks something like:
.PP
.SH "Output streams"
.PP
By default \fRdebug\fP will log to stderr, however this can be configured per-namespace by overriding the \fRlog\fP method:
.PP
Example \fIstdout\&.js\fP:
.PP
.PP
.nf
var debug = require('debug');
var error = debug('app:error');

// by default stderr is used
error('goes to stderr!');

var log = debug('app:log');
// set this namespace to log via console\&.log
log\&.log = console\&.log\&.bind(console); // don't forget to bind to console!
log('goes to stdout');
error('still goes to stderr!');

// set all output to go via console\&.info
// overrides all per\-namespace log settings
debug\&.log = console\&.info\&.bind(console);
error('now goes to stdout via console\&.info');
log('still goes to stdout, but via console\&.info now');
.fi
.PP
.SH "Authors"
.PP
.IP "\(bu" 2
TJ Holowaychuk
.IP "\(bu" 2
Nathan Rajlich
.IP "\(bu" 2
Andrew Rhyne
.PP
.SH "Backers"
.PP
Support us with a monthly donation and help us continue our activities\&. [\fRBecome a backer\fP]
.PP
\fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP
.SH "Sponsors"
.PP
Become a sponsor and get your logo on our README on Github with a link to your site\&. [\fRBecome a sponsor\fP]
.PP
\fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP
.SH "License"
.PP
(The MIT License)
.PP
Copyright (c) 2014-2016 TJ Holowaychuk <tj@vision-media.ca>
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
