.TH "md_backend_2node__modules_2gopd_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2gopd_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.0\&.1\fP - 2022-11-01"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] actually export gOPD instead of dP \fR\fR4b624bf\fP\fP
.PP
.SH "v1\&.0\&.0 - 2022-11-01"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme \fR\fR0911e01\fP\fP
.IP "\(bu" 2
Initial commit \fR\fRb84e33f\fP\fP
.IP "\(bu" 2
[actions] add reusable workflows \fR\fR12ae28a\fP\fP
.IP "\(bu" 2
npm init \fR\fR280118b\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fRbb78de5\fP\fP
.IP "\(bu" 2
[meta] create FUNDING\&.yml; add \fRfunding\fP in package\&.json \fR\fR11c22e6\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fR4f4537a\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRc567022\fP\fP 
.PP

