.TH "md_backend_2node__modules_2which_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2which_2_c_h_a_n_g_e_l_o_g \- Changes 
.PP

.SH "2\&.0\&.2"
.PP
.IP "\(bu" 2
Rename bin to \fRnode-which\fP
.PP
.SH "2\&.0\&.1"
.PP
.IP "\(bu" 2
generate changelog and publish on version bump
.IP "\(bu" 2
enforce 100% test coverage
.IP "\(bu" 2
Promise interface
.PP
.SH "2\&.0\&.0"
.PP
.IP "\(bu" 2
Parallel tests, modern JavaScript, and drop support for node < 8
.PP
.SH "1\&.3\&.1"
.PP
.IP "\(bu" 2
update deps
.IP "\(bu" 2
update travis
.PP
.SH "v1\&.3\&.0"
.PP
.IP "\(bu" 2
Add nothrow option to which\&.sync
.IP "\(bu" 2
update tap
.PP
.SH "v1\&.2\&.14"
.PP
.IP "\(bu" 2
appveyor: drop node 5 and 0\&.x
.IP "\(bu" 2
travis-ci: add node 6, drop 0\&.x
.PP
.SH "v1\&.2\&.13"
.PP
.IP "\(bu" 2
test: Pass missing option to pass on windows
.IP "\(bu" 2
update tap
.IP "\(bu" 2
update isexe to 2\&.0\&.0
.IP "\(bu" 2
neveragain\&.tech pledge request
.PP
.SH "v1\&.2\&.12"
.PP
.IP "\(bu" 2
Removed unused require
.PP
.SH "v1\&.2\&.11"
.PP
.IP "\(bu" 2
Prevent changelog script from being included in package
.PP
.SH "v1\&.2\&.10"
.PP
.IP "\(bu" 2
Use env\&.PATH only, not env\&.Path
.PP
.SH "v1\&.2\&.9"
.PP
.IP "\(bu" 2
fix for paths starting with \&.\&./
.IP "\(bu" 2
Remove unused \fRis-absolute\fP module
.PP
.SH "v1\&.2\&.8"
.PP
.IP "\(bu" 2
bullet items in changelog that contain (but don't start with) #
.PP
.SH "v1\&.2\&.7"
.PP
.IP "\(bu" 2
strip 'update changelog' changelog entries out of changelog
.PP
.SH "v1\&.2\&.6"
.PP
.IP "\(bu" 2
make the changelog bulleted
.PP
.SH "v1\&.2\&.5"
.PP
.IP "\(bu" 2
make a changelog, and keep it up to date
.IP "\(bu" 2
don't include tests in package
.IP "\(bu" 2
Properly handle relative-path executables
.IP "\(bu" 2
appveyor
.IP "\(bu" 2
Attach error code to Not Found error
.IP "\(bu" 2
Make tests pass on Windows
.PP
.SH "v1\&.2\&.4"
.PP
.IP "\(bu" 2
Fix typo
.PP
.SH "v1\&.2\&.3"
.PP
.IP "\(bu" 2
update isexe, fix regression in pathExt handling
.PP
.SH "v1\&.2\&.2"
.PP
.IP "\(bu" 2
update deps, use isexe module, test windows
.PP
.SH "v1\&.2\&.1"
.PP
.IP "\(bu" 2
Sometimes windows PATH entries are quoted
.IP "\(bu" 2
Fixed a bug in the check for group and user mode bits\&. This bug was introduced during refactoring for supporting strict mode\&.
.IP "\(bu" 2
doc cli
.PP
.SH "v1\&.2\&.0"
.PP
.IP "\(bu" 2
Add support for opt\&.all and -as cli flags
.IP "\(bu" 2
test the bin
.IP "\(bu" 2
update travis
.IP "\(bu" 2
Allow checking for multiple programs in bin/which
.IP "\(bu" 2
tap 2
.PP
.SH "v1\&.1\&.2"
.PP
.IP "\(bu" 2
travis
.IP "\(bu" 2
Refactored and fixed undefined error on Windows
.IP "\(bu" 2
Support strict mode
.PP
.SH "v1\&.1\&.1"
.PP
.IP "\(bu" 2
test +g exes against secondary groups, if available
.IP "\(bu" 2
Use windows exe semantics on cygwin & msys
.IP "\(bu" 2
cwd should be first in path on win32, not last
.IP "\(bu" 2
Handle lower-case 'env\&.Path' on Windows
.IP "\(bu" 2
Update docs
.IP "\(bu" 2
use single-quotes
.PP
.SH "v1\&.1\&.0"
.PP
.IP "\(bu" 2
Add tests, depend on is-absolute
.PP
.SH "v1\&.0\&.9"
.PP
.IP "\(bu" 2
which\&.js: root is allowed to execute files owned by anyone
.PP
.SH "v1\&.0\&.8"
.PP
.IP "\(bu" 2
don't use graceful-fs
.PP
.SH "v1\&.0\&.7"
.PP
.IP "\(bu" 2
add license to package\&.json
.PP
.SH "v1\&.0\&.6"
.PP
.IP "\(bu" 2
isc license
.PP
.SH "1\&.0\&.5"
.PP
.IP "\(bu" 2
Awful typo
.PP
.SH "1\&.0\&.4"
.PP
.IP "\(bu" 2
Test for path absoluteness properly
.IP "\(bu" 2
win: Allow '' as a pathext if cmd has a \&. in it
.PP
.SH "1\&.0\&.3"
.PP
.IP "\(bu" 2
Remove references to execPath
.IP "\(bu" 2
Make \fRwhich\&.sync()\fP work on Windows by honoring the PATHEXT variable\&.
.IP "\(bu" 2
Make \fRisExe()\fP always return true on Windows\&.
.IP "\(bu" 2
MIT
.PP
.SH "1\&.0\&.2"
.PP
.IP "\(bu" 2
Only files can be exes
.PP
.SH "1\&.0\&.1"
.PP
.IP "\(bu" 2
Respect the PATHEXT env for win32 support
.IP "\(bu" 2
should 0755 the bin
.IP "\(bu" 2
binary
.IP "\(bu" 2
guts
.IP "\(bu" 2
package
.IP "\(bu" 2
1st 
.PP

