.TH "md_backend_2node__modules_2file-uri-to-path_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2file-uri-to-path_2_r_e_a_d_m_e \- file-uri-to-path 
.PP

.SS "Convert a \fRfile:\fP URI to a file path"
\fR\fP.PP
Accepts a \fRfile:\fP URI and returns a regular file path suitable for use with the \fRfs\fP module functions\&.
.SH "Installation"
.PP
Install with \fRnpm\fP:
.PP
.PP
.nf
 bash
$ npm install file\-uri\-to\-path
.fi
.PP
.SH "Example"
.PP
.PP
.nf
 js
var uri2path = require('file\-uri\-to\-path');

uri2path('file://localhost/c|/WINDOWS/clock\&.avi');
// "c:\\\\WINDOWS\\\\clock\&.avi"

uri2path('file:///c|/WINDOWS/clock\&.avi');
// "c:\\\\WINDOWS\\\\clock\&.avi"

uri2path('file://localhost/c:/WINDOWS/clock\&.avi');
// "c:\\\\WINDOWS\\\\clock\&.avi"

uri2path('file://hostname/path/to/the%20file\&.txt');
// "\\\\\\\\hostname\\\\path\\\\to\\\\the file\&.txt"

uri2path('file:///c:/path/to/the%20file\&.txt');
// "c:\\\\path\\\\to\\\\the file\&.txt"
.fi
.PP
.SH "API"
.PP
.SS "fileUriToPath(String uri) → String"
.SH "License"
.PP
(The MIT License)
.PP
Copyright (c) 2014 Nathan Rajlich <nathan@tootallnate.net>
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
