.TH "md_backend_2node__modules_2send_2node__modules_2ms_2readme" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2send_2node__modules_2ms_2readme \- ms 
.PP
 
.PP
Use this package to easily convert various time formats to milliseconds\&.
.SH "Examples"
.PP
.PP
.nf
ms('2 days')  // 172800000
ms('1d')      // 86400000
ms('10h')     // 36000000
ms('2\&.5 hrs') // 9000000
ms('2h')      // 7200000
ms('1m')      // 60000
ms('5s')      // 5000
ms('1y')      // 31557600000
ms('100')     // 100
ms('\-3 days') // \-259200000
ms('\-1h')     // \-3600000
ms('\-200')    // \-200
.fi
.PP
.SS "Convert from Milliseconds"
.PP
.nf
ms(60000)             // "1m"
ms(2 * 60000)         // "2m"
ms(\-3 * 60000)        // "\-3m"
ms(ms('10 hours'))    // "10h"
.fi
.PP
.SS "Time Format Written-Out"
.PP
.nf
ms(60000, { long: true })             // "1 minute"
ms(2 * 60000, { long: true })         // "2 minutes"
ms(\-3 * 60000, { long: true })        // "\-3 minutes"
ms(ms('10 hours'), { long: true })    // "10 hours"
.fi
.PP
.SH "Features"
.PP
.IP "\(bu" 2
Works both in \fRNode\&.js\fP and in the browser
.IP "\(bu" 2
If a number is supplied to \fRms\fP, a string with a unit is returned
.IP "\(bu" 2
If a string that contains the number is supplied, it returns it as a number (e\&.g\&.: it returns \fR100\fP for `'100'`)
.IP "\(bu" 2
If you pass a string with a number and a valid unit, the number of equivalent milliseconds is returned
.PP
.SH "Related Packages"
.PP
.IP "\(bu" 2
\fRms\&.macro\fP - Run \fRms\fP as a macro at build-time\&.
.PP
.SH "Caught a Bug?"
.PP
.IP "1." 4
\fRFork\fP this repository to your own GitHub account and then \fRclone\fP it to your local device
.IP "2." 4
Link the package to the global module directory: \fRnpm link\fP
.IP "3." 4
Within the module you want to test your local development instance of ms, just link it to the dependencies: \fRnpm link ms\fP\&. Instead of the default one from npm, Node\&.js will now use your clone of ms!
.PP
.PP
As always, you can run the tests using: \fRnpm test\fP 
