.TH "md_backend_2node__modules_2buffer_2_a_u_t_h_o_r_s" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2buffer_2_a_u_t_h_o_r_s \- Authors 
.PP
 
.SS "Ordered by first contribution\&."
.IP "\(bu" 2
Romain Beauxis (toots@rastageeks.org)
.IP "\(bu" 2
Tobias Koppers (tobias.koppers@googlemail.com)
.IP "\(bu" 2
Janus (ysangkok@gmail.com)
.IP "\(bu" 2
Rainer Dreyer (rdrey1@gmail.com)
.IP "\(bu" 2
Tõnis Tiigi (tonistiigi@gmail.com)
.IP "\(bu" 2
James Halliday (mail@substack.net)
.IP "\(bu" 2
Michael Williamson (mike@zwobble.org)
.IP "\(bu" 2
elliottcable (github@elliottcable.name)
.IP "\(bu" 2
rafael (rvalle@livelens.net)
.IP "\(bu" 2
Andrew Kelley (superjoe30@gmail.com)
.IP "\(bu" 2
Andreas Madsen (amwebdk@gmail.com)
.IP "\(bu" 2
Mike Brevoort (mike.brevoort@pearson.com)
.IP "\(bu" 2
Brian White (mscdex@mscdex.net)
.IP "\(bu" 2
Feross Aboukhadijeh (feross@feross.org)
.IP "\(bu" 2
Ruben Verborgh (ruben@verborgh.org)
.IP "\(bu" 2
eliang (eliang.cs@gmail.com)
.IP "\(bu" 2
Jesse Tane (jesse.tane@gmail.com)
.IP "\(bu" 2
Alfonso Boza (alfonso@cloud.com)
.IP "\(bu" 2
Mathias Buus (mathiasbuus@gmail.com)
.IP "\(bu" 2
Devon Govett (devongovett@gmail.com)
.IP "\(bu" 2
Daniel Cousens (github@dcousens.com)
.IP "\(bu" 2
Joseph Dykstra (josephdykstra@gmail.com)
.IP "\(bu" 2
Parsha Pourkhomami (parshap+git@gmail.com)
.IP "\(bu" 2
Damjan Košir (damjan.kosir@gmail.com)
.IP "\(bu" 2
daverayment (dave.rayment@gmail.com)
.IP "\(bu" 2
kawanet (u-suke@kawa.net)
.IP "\(bu" 2
Linus Unnebäck (linus@folkdatorn.se)
.IP "\(bu" 2
Nolan Lawson (nolan.lawson@gmail.com)
.IP "\(bu" 2
Calvin Metcalf (calvin.metcalf@gmail.com)
.IP "\(bu" 2
Koki Takahashi (hakatasiloving@gmail.com)
.IP "\(bu" 2
Guy Bedford (guybedford@gmail.com)
.IP "\(bu" 2
Jan Schär (jscissr@gmail.com)
.IP "\(bu" 2
RaulTsc (tomescu.raul@gmail.com)
.IP "\(bu" 2
Matthieu Monsch (monsch@alum.mit.edu)
.IP "\(bu" 2
Dan Ehrenberg (littledan@chromium.org)
.IP "\(bu" 2
Kirill Fomichev (fanatid@ya.ru)
.IP "\(bu" 2
Yusuke Kawasaki (u-suke@kawa.net)
.IP "\(bu" 2
DC (dcposch@dcpos.ch)
.IP "\(bu" 2
John-David Dalton (john.david.dalton@gmail.com)
.IP "\(bu" 2
adventure-yunfei (adventure030@gmail.com)
.IP "\(bu" 2
Emil Bay (github@tixz.dk)
.IP "\(bu" 2
Sam Sudar (sudar.sam@gmail.com)
.IP "\(bu" 2
Volker Mische (volker.mische@gmail.com)
.IP "\(bu" 2
David Walton (support@geekstocks.com)
.IP "\(bu" 2
Сковорода Никита Андреевич (chalkerx@gmail.com)
.IP "\(bu" 2
greenkeeper[bot] (greenkeeper[bot]@users\&.noreply\&.github\&.com)
.IP "\(bu" 2
ukstv (sergey.ukustov@machinomy.com)
.IP "\(bu" 2
Renée Kooi (renee@kooi.me)
.IP "\(bu" 2
ranbochen (ranbochen@qq.com)
.IP "\(bu" 2
Vladimir Borovik (bobahbdb@gmail.com)
.IP "\(bu" 2
greenkeeper[bot] (23040076+greenkeeper[bot]@users\&.noreply\&.github\&.com)
.IP "\(bu" 2
kumavis (aaron@kumavis.me)
.IP "\(bu" 2
Sergey Ukustov (sergey.ukustov@machinomy.com)
.IP "\(bu" 2
Fei Liu (liu.feiwood@gmail.com)
.IP "\(bu" 2
Blaine Bublitz (blaine.bublitz@gmail.com)
.IP "\(bu" 2
clement (clement@seald.io)
.IP "\(bu" 2
Koushik Dutta (koushd@gmail.com)
.IP "\(bu" 2
Jordan Harband (ljharb@gmail.com)
.IP "\(bu" 2
Niklas Mischkulnig (mischnic@users.noreply.github.com)
.IP "\(bu" 2
Nikolai Vavilov (vvnicholas@gmail.com)
.IP "\(bu" 2
Fedor Nezhivoi (gyzerok@users.noreply.github.com)
.IP "\(bu" 2
Peter Newman (peternewman@users.noreply.github.com)
.IP "\(bu" 2
mathmakgakpak (44949126+mathmakgakpak@users.noreply.github.com)
.IP "\(bu" 2
jkkang (jkkang@smartauth.kr)
.PP
.SS "Generated by bin/update-authors\&.sh\&."

