.TH "md_backend_2node__modules_2forwarded_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2forwarded_2_h_i_s_t_o_r_y \- 0\&.2\&.0 / 2024-05-31 
.PP

.IP "\(bu" 2
Use \fRreq\&.socket\fP over deprecated \fRreq\&.connection\fP
.PP
.SH "0\&.1\&.2 / 2017-09-14"
.PP
.IP "\(bu" 2
perf: improve header parsing
.IP "\(bu" 2
perf: reduce overhead when no \fRX-Forwarded-For\fP header
.PP
.SH "0\&.1\&.1 / 2017-09-10"
.PP
.IP "\(bu" 2
Fix trimming leading / trailing OWS
.IP "\(bu" 2
perf: hoist regular expression
.PP
.SH "0\&.1\&.0 / 2014-09-21"
.PP
.IP "\(bu" 2
Initial release 
.PP

