.TH "md_backend_2node__modules_2negotiator_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2negotiator_2_h_i_s_t_o_r_y \- 0\&.6\&.3 / 2022-01-22 
.PP

.IP "\(bu" 2
Revert 'Lazy-load modules from main entry point'
.PP
.SH "0\&.6\&.2 / 2019-04-29"
.PP
.IP "\(bu" 2
Fix sorting charset, encoding, and language with extra parameters
.PP
.SH "0\&.6\&.1 / 2016-05-02"
.PP
.IP "\(bu" 2
perf: improve \fRAccept\fP parsing speed
.IP "\(bu" 2
perf: improve \fRAccept-Charset\fP parsing speed
.IP "\(bu" 2
perf: improve \fRAccept-Encoding\fP parsing speed
.IP "\(bu" 2
perf: improve \fRAccept-Language\fP parsing speed
.PP
.SH "0\&.6\&.0 / 2015-09-29"
.PP
.IP "\(bu" 2
Fix including type extensions in parameters in \fRAccept\fP parsing
.IP "\(bu" 2
Fix parsing \fRAccept\fP parameters with quoted equals
.IP "\(bu" 2
Fix parsing \fRAccept\fP parameters with quoted semicolons
.IP "\(bu" 2
Lazy-load modules from main entry point
.IP "\(bu" 2
perf: delay type concatenation until needed
.IP "\(bu" 2
perf: enable strict mode
.IP "\(bu" 2
perf: hoist regular expressions
.IP "\(bu" 2
perf: remove closures getting spec properties
.IP "\(bu" 2
perf: remove a closure from media type parsing
.IP "\(bu" 2
perf: remove property delete from media type parsing
.PP
.SH "0\&.5\&.3 / 2015-05-10"
.PP
.IP "\(bu" 2
Fix media type parameter matching to be case-insensitive
.PP
.SH "0\&.5\&.2 / 2015-05-06"
.PP
.IP "\(bu" 2
Fix comparing media types with quoted values
.IP "\(bu" 2
Fix splitting media types with quoted commas
.PP
.SH "0\&.5\&.1 / 2015-02-14"
.PP
.IP "\(bu" 2
Fix preference sorting to be stable for long acceptable lists
.PP
.SH "0\&.5\&.0 / 2014-12-18"
.PP
.IP "\(bu" 2
Fix list return order when large accepted list
.IP "\(bu" 2
Fix missing identity encoding when q=0 exists
.IP "\(bu" 2
Remove dynamic building of Negotiator class
.PP
.SH "0\&.4\&.9 / 2014-10-14"
.PP
.IP "\(bu" 2
Fix error when media type has invalid parameter
.PP
.SH "0\&.4\&.8 / 2014-09-28"
.PP
.IP "\(bu" 2
Fix all negotiations to be case-insensitive
.IP "\(bu" 2
Stable sort preferences of same quality according to client order
.IP "\(bu" 2
Support Node\&.js 0\&.6
.PP
.SH "0\&.4\&.7 / 2014-06-24"
.PP
.IP "\(bu" 2
Handle invalid provided languages
.IP "\(bu" 2
Handle invalid provided media types
.PP
.SH "0\&.4\&.6 / 2014-06-11"
.PP
.IP "\(bu" 2
Order by specificity when quality is the same
.PP
.SH "0\&.4\&.5 / 2014-05-29"
.PP
.IP "\(bu" 2
Fix regression in empty header handling
.PP
.SH "0\&.4\&.4 / 2014-05-29"
.PP
.IP "\(bu" 2
Fix behaviors when headers are not present
.PP
.SH "0\&.4\&.3 / 2014-04-16"
.PP
.IP "\(bu" 2
Handle slashes on media params correctly
.PP
.SH "0\&.4\&.2 / 2014-02-28"
.PP
.IP "\(bu" 2
Fix media type sorting
.IP "\(bu" 2
Handle media types params strictly
.PP
.SH "0\&.4\&.1 / 2014-01-16"
.PP
.IP "\(bu" 2
Use most specific matches
.PP
.SH "0\&.4\&.0 / 2014-01-09"
.PP
.IP "\(bu" 2
Remove preferred prefix from methods 
.PP

