.TH "md_backend_2node__modules_2array-flatten_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2array-flatten_2_r_e_a_d_m_e \- Array Flatten 
.PP
 \fR\fP \fR\fP \fR\fP \fR\fP
.PP
.RS 4
Flatten an array of nested arrays into a single flat array\&. Accepts an optional depth\&. 
.RE
.PP
.SH "Installation"
.PP
.PP
.nf
npm install array\-flatten \-\-save
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
var flatten = require('array\-flatten')

flatten([1, [2, [3, [4, [5], 6], 7], 8], 9])
//=> [1, 2, 3, 4, 5, 6, 7, 8, 9]

flatten([1, [2, [3, [4, [5], 6], 7], 8], 9], 2)
//=> [1, 2, 3, [4, [5], 6], 7, 8, 9]

(function () {
  flatten(arguments) //=> [1, 2, 3]
})(1, [2, 3])
.fi
.PP
.SH "License"
.PP
MIT 
