.TH "md_backend_2node__modules_2es-define-property_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2es-define-property_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "v1\&.0\&.0 - 2024-02-12"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme, types \fR\fR3e154e1\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR07d98de\fP\fP
.IP "\(bu" 2
npm init \fR\fRc4eb634\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR7af86ec\fP\fP 
.PP

