.TH "md_backend_2node__modules_2function-bind_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2function-bind_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.1\&.2\fP - 2023-10-12"
.PP
.SS "Merged"
.IP "\(bu" 2
Point to the correct file \fR\fR#16\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate tests to Github Actions \fR\fR4f8b57c\fP\fP
.IP "\(bu" 2
[Tests] remove \fRjscs\fP \fR\fR90eb2ed\fP\fP
.IP "\(bu" 2
[meta] update \fR\&.gitignore\fP \fR\fR53fcdc3\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv11\&.10\fP, \fRv10\&.15\fP, \fRv9\&.11\fP, \fRv8\&.15\fP, \fRv6\&.16\fP, \fRv4\&.9\fP; use \fRnvm install-latest-npm\fP; run audit script in tests \fR\fR1fe8f6e\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR1921fcb\fP\fP
.IP "\(bu" 2
[Robustness] remove runtime dependency on all builtins except \fR\&.apply\fP \fR\fRf743e61\fP\fP
.IP "\(bu" 2
Docs: enable badges; update wording \fR\fR503cb12\fP\fP
.IP "\(bu" 2
[readme] update badges \fR\fR290c5db\fP\fP
.IP "\(bu" 2
[Tests] switch to nyc for coverage \fR\fRea360ba\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRtape\fP \fR\fRcae5e9e\fP\fP
.IP "\(bu" 2
[meta] add \fRfunding\fP field; create FUNDING\&.yml \fR\fRc9f4274\fP\fP
.IP "\(bu" 2
[Tests] fix eslint errors from #15 \fR\fRf69aaa2\fP\fP
.IP "\(bu" 2
[actions] fix permissions \fR\fR99a0cd9\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fRf03b524\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint‑config\fP, \fReslint\fP, \fRtape\fP \fR\fR7af9300\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRcovert\fP, \fRtape\fP \fR\fR64a9127\fP\fP
.IP "\(bu" 2
[Tests] use \fRaud\fP instead of \fRnpm audit\fP \fR\fRe75069c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fRd03555c\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP \fR\fR9c8f809\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRtape\fP \fR\fRbaf6893\fP\fP
.IP "\(bu" 2
[meta] create SECURITY\&.md \fR\fR4db1779\fP\fP
.IP "\(bu" 2
[Tests] add \fRnpm run audit\fP \fR\fRc8b38ec\fP\fP
.IP "\(bu" 2
Revert 'Point to the correct file' \fR\fR05cdf0f\fP\fP
.PP
.SH "\fRv1\&.1\&.1\fP - 2017-08-28"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv8\fP; newer npm breaks on older node; fix scripts \fR\fR817f7d2\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fRjscs\fP, \fRtape\fP, \fR@ljharb/eslint-config\fP \fR\fR854288b\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP, \fRjscs\fP, \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fR83e639f\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR5ed97f5\fP\fP
.IP "\(bu" 2
Use a SPDX-compliant “license” field\&. \fR\fR5feefea\fP\fP
.PP
.SH "\fRv1\&.1\&.0\fP - 2016-02-14"
.PP
.SS "Commits"
.IP "\(bu" 2
Update \fReslint\fP, \fRtape\fP; use my personal shared \fReslint\fP config \fR\fR9c9062a\fP\fP
.IP "\(bu" 2
Add \fRnpm run eslint\fP \fR\fRdd96c56\fP\fP
.IP "\(bu" 2
[New] return the native \fRbind\fP when available\&. \fR\fR82186e0\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP, \fRjscs\fP, \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fRa3dd767\fP\fP
.IP "\(bu" 2
Update \fReslint\fP \fR\fR3dae2f7\fP\fP
.IP "\(bu" 2
Update \fRtape\fP, \fRcovert\fP, \fRjscs\fP \fR\fRa181eee\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv5\&.6\fP, \fRv4\&.3\fP \fR\fR964929a\fP\fP
.IP "\(bu" 2
Test up to \fRio\&.js\fP \fRv2\&.1\fP \fR\fR2be7310\fP\fP
.IP "\(bu" 2
Update \fRtape\fP, \fRjscs\fP, \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fR45f3d68\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP, \fRjscs\fP \fR\fR6e1340d\fP\fP
.IP "\(bu" 2
[Tests] up to \fRio\&.js\fP \fRv3\&.3\fP, \fRnode\fP \fRv4\&.1\fP \fR\fRd9bad2b\fP\fP
.IP "\(bu" 2
Update \fReslint\fP \fR\fR935590c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRjscs\fP, \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fR8c9a1ef\fP\fP
.IP "\(bu" 2
Test on \fRio\&.js\fP \fRv2\&.2\fP \fR\fR9a3a38c\fP\fP
.IP "\(bu" 2
Run \fRtravis-ci\fP tests on \fRiojs\fP and \fRnode\fP v0\&.12; speed up builds; allow 0\&.8 failures\&. \fR\fR69afc26\fP\fP
.IP "\(bu" 2
[Dev Deps] Update \fRtape\fP, \fReslint\fP \fR\fR36c1be0\fP\fP
.IP "\(bu" 2
Update \fRtape\fP, \fRjscs\fP \fR\fR98d8303\fP\fP
.IP "\(bu" 2
Update \fRjscs\fP \fR\fR9633a4e\fP\fP
.IP "\(bu" 2
Update \fRtape\fP, \fRjscs\fP \fR\fRc80ef0f\fP\fP
.IP "\(bu" 2
Test up to \fRio\&.js\fP \fRv3\&.0\fP \fR\fR7e2c853\fP\fP
.IP "\(bu" 2
Test on \fRio\&.js\fP \fRv2\&.4\fP \fR\fR5a199a2\fP\fP
.IP "\(bu" 2
Test on \fRio\&.js\fP \fRv2\&.3\fP \fR\fRa511b88\fP\fP
.IP "\(bu" 2
Fixing a typo from 822b4e1938db02dc9584aa434fd3a45cb20caf43 \fR\fR732d6b6\fP\fP
.IP "\(bu" 2
Update \fRjscs\fP \fR\fRda52a48\fP\fP
.IP "\(bu" 2
Lock covert to v1\&.0\&.0\&. \fR\fRd6150fd\fP\fP
.PP
.SH "\fRv1\&.0\&.2\fP - 2014-10-04"
.PP
.SH "\fRv1\&.0\&.1\fP - 2014-10-03"
.PP
.SS "Merged"
.IP "\(bu" 2
make CI build faster \fR\fR#3\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Using my standard jscs\&.json \fR\fRd8ee94c\fP\fP
.IP "\(bu" 2
Adding \fRnpm run lint\fP \fR\fR7571ab7\fP\fP
.IP "\(bu" 2
Using consistent indentation \fR\fRe91a1b1\fP\fP
.IP "\(bu" 2
Updating jscs \fR\fR7e17892\fP\fP
.IP "\(bu" 2
Using consistent quotes \fR\fRc50b57f\fP\fP
.IP "\(bu" 2
Adding keywords \fR\fRcb94631\fP\fP
.IP "\(bu" 2
Directly export a function expression instead of using a declaration, and relying on hoisting\&. \fR\fR5a33c5f\fP\fP
.IP "\(bu" 2
Naming npm URL and badge in README; use SVG \fR\fR2aef8fc\fP\fP
.IP "\(bu" 2
Naming deps URLs in README \fR\fR04228d7\fP\fP
.IP "\(bu" 2
Naming travis-ci URLs in README; using SVG \fR\fR62c810c\fP\fP
.IP "\(bu" 2
Make sure functions are invoked correctly (also passing coverage tests) \fR\fR2b289b4\fP\fP
.IP "\(bu" 2
Removing the strict mode pragmas; they make tests fail\&. \fR\fR1aa701d\fP\fP
.IP "\(bu" 2
Adding myself as a contributor \fR\fR85fd57b\fP\fP
.IP "\(bu" 2
Adding strict mode pragmas \fR\fR915b08e\fP\fP
.IP "\(bu" 2
Adding devDeps URLs to README \fR\fR4ccc731\fP\fP
.IP "\(bu" 2
Fixing the description\&. \fR\fRa7a472c\fP\fP
.IP "\(bu" 2
Using a function expression instead of a function declaration\&. \fR\fRb5d3e4e\fP\fP
.IP "\(bu" 2
Updating tape \fR\fRf086be6\fP\fP
.IP "\(bu" 2
Updating jscs \fR\fR5f9bdb3\fP\fP
.IP "\(bu" 2
Updating jscs \fR\fR9b409ba\fP\fP
.IP "\(bu" 2
Run coverage as part of tests\&. \fR\fR8e1b6d4\fP\fP
.IP "\(bu" 2
Run linter as part of tests \fR\fRc1ca83f\fP\fP
.IP "\(bu" 2
Updating covert \fR\fR701e837\fP\fP
.PP
.SH "\fRv1\&.0\&.0\fP - 2014-08-09"
.PP
.SS "Commits"
.IP "\(bu" 2
Make sure old and unstable nodes don't fail Travis \fR\fR27adca3\fP\fP
.IP "\(bu" 2
Fixing an issue when the bound function is called as a constructor in ES3\&. \fR\fRe20122d\fP\fP
.IP "\(bu" 2
Adding \fRnpm run coverage\fP \fR\fRa2e29c4\fP\fP
.IP "\(bu" 2
Updating tape \fR\fRb741168\fP\fP
.IP "\(bu" 2
Upgrading tape \fR\fR63631a0\fP\fP
.IP "\(bu" 2
Updating tape \fR\fR363cb46\fP\fP
.PP
.SH "v0\&.2\&.0 - 2014-03-23"
.PP
.SS "Commits"
.IP "\(bu" 2
Updating test coverage to match es5-shim\&. \fR\fRaa94d44\fP\fP
.IP "\(bu" 2
initial \fR\fR942ee07\fP\fP
.IP "\(bu" 2
Setting the bound function's length properly\&. \fR\fR079f46a\fP\fP
.IP "\(bu" 2
Ensuring that some older browsers will throw when given a regex\&. \fR\fR36ac55b\fP\fP
.IP "\(bu" 2
Removing npm scripts that don't have dependencies \fR\fR9d2be60\fP\fP
.IP "\(bu" 2
Updating tape \fR\fR297a4ac\fP\fP
.IP "\(bu" 2
Skipping length tests for now\&. \fR\fRd9891ea\fP\fP
.IP "\(bu" 2
don't take my tea \fR\fRdccd930\fP\fP 
.PP

