.TH "md_backend_2node__modules_2has-property-descriptors_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2has-property-descriptors_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.0\&.2\fP - 2024-02-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRes-define-property\fP \fR\fRf93a8c8\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRnpmignore\fP, \fRtape\fP \fR\fR42b0c9d\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR35e9b46\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2023-10-20"
.PP
.SS "Commits"
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fR5bbf4da\fP\fP
.IP "\(bu" 2
[actions] update rebase action to use reusable workflow \fR\fR3a5585b\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fRe5c1212\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRtape\fP \fR\fRe942917\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fRf4a44ec\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fReeb275b\fP\fP
.PP
.SH "v1\&.0\&.0 - 2022-04-14"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests \fR\fR303559f\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR3a7ca2d\fP\fP
.IP "\(bu" 2
read me \fR\fRdd73dce\fP\fP
.IP "\(bu" 2
npm init \fR\fRc1e6557\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRe72f7c6\fP\fP 
.PP

