.TH "md_backend_2node__modules_2is-lambda_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2is-lambda_2_r_e_a_d_m_e \- is-lambda 
.PP
 Returns \fRtrue\fP if the current environment is an \fRAWS Lambda\fP server\&.
.PP
\fR\fP \fR\fP
.SH "Installation"
.PP
.PP
.nf
npm install is\-lambda
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
var isLambda = require('is\-lambda')

if (isLambda) {
  console\&.log('The code is running on a AWS Lambda')
}
.fi
.PP
.SH "License"
.PP
MIT 
