.TH "md_backend_2node__modules_2mime-db_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2mime-db_2_h_i_s_t_o_r_y \- 1\&.52\&.0 / 2022-02-21 
.PP

.IP "\(bu" 2
Add extensions from IANA for more \fRimage/*\fP types
.IP "\(bu" 2
Add extension \fR\&.asc\fP to \fRapplication/pgp-keys\fP
.IP "\(bu" 2
Add extensions to various XML types
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.51\&.0 / 2021-11-08"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Mark \fRimage/vnd\&.microsoft\&.icon\fP as compressible
.IP "\(bu" 2
Mark \fRimage/vnd\&.ms-dds\fP as compressible
.PP
.SH "1\&.50\&.0 / 2021-09-15"
.PP
.IP "\(bu" 2
Add deprecated iWorks mime types and extensions
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.49\&.0 / 2021-07-26"
.PP
.IP "\(bu" 2
Add extension \fR\&.trig\fP to \fRapplication/trig\fP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.48\&.0 / 2021-05-30"
.PP
.IP "\(bu" 2
Add extension \fR\&.mvt\fP to \fRapplication/vnd\&.mapbox-vector-tile\fP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Mark \fRtext/yaml\fP as compressible
.PP
.SH "1\&.47\&.0 / 2021-04-01"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Remove ambigious extensions from IANA for \fRapplication/*+xml\fP types
.IP "\(bu" 2
Update primary extension to \fR\&.es\fP for \fRapplication/ecmascript\fP
.PP
.SH "1\&.46\&.0 / 2021-02-13"
.PP
.IP "\(bu" 2
Add extension \fR\&.amr\fP to \fRaudio/amr\fP
.IP "\(bu" 2
Add extension \fR\&.m4s\fP to \fRvideo/iso\&.segment\fP
.IP "\(bu" 2
Add extension \fR\&.opus\fP to \fRaudio/ogg\fP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.45\&.0 / 2020-09-22"
.PP
.IP "\(bu" 2
Add \fRapplication/ubjson\fP with extension \fR\&.ubj\fP
.IP "\(bu" 2
Add \fRimage/avif\fP with extension \fR\&.avif\fP
.IP "\(bu" 2
Add \fRimage/ktx2\fP with extension \fR\&.ktx2\fP
.IP "\(bu" 2
Add extension \fR\&.dbf\fP to \fRapplication/vnd\&.dbf\fP
.IP "\(bu" 2
Add extension \fR\&.rar\fP to \fRapplication/vnd\&.rar\fP
.IP "\(bu" 2
Add extension \fR\&.td\fP to \fRapplication/urc-targetdesc+xml\fP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Fix extension of \fRapplication/vnd\&.apple\&.keynote\fP to be \fR\&.key\fP
.PP
.SH "1\&.44\&.0 / 2020-04-22"
.PP
.IP "\(bu" 2
Add charsets from IANA
.IP "\(bu" 2
Add extension \fR\&.cjs\fP to \fRapplication/node\fP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.43\&.0 / 2020-01-05"
.PP
.IP "\(bu" 2
Add \fRapplication/x-keepass2\fP with extension \fR\&.kdbx\fP
.IP "\(bu" 2
Add extension \fR\&.mxmf\fP to \fRaudio/mobile-xmf\fP
.IP "\(bu" 2
Add extensions from IANA for \fRapplication/*+xml\fP types
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.42\&.0 / 2019-09-25"
.PP
.IP "\(bu" 2
Add \fRimage/vnd\&.ms-dds\fP with extension \fR\&.dds\fP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Remove compressible from \fRmultipart/mixed\fP
.PP
.SH "1\&.41\&.0 / 2019-08-30"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add \fRapplication/toml\fP with extension \fR\&.toml\fP
.IP "\(bu" 2
Mark \fRfont/ttf\fP as compressible
.PP
.SH "1\&.40\&.0 / 2019-04-20"
.PP
.IP "\(bu" 2
Add extensions from IANA for \fRmodel/*\fP types
.IP "\(bu" 2
Add \fRtext/mdx\fP with extension \fR\&.mdx\fP
.PP
.SH "1\&.39\&.0 / 2019-04-04"
.PP
.IP "\(bu" 2
Add extensions \fR\&.siv\fP and \fR\&.sieve\fP to \fRapplication/sieve\fP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.38\&.0 / 2019-02-04"
.PP
.IP "\(bu" 2
Add extension \fR\&.nq\fP to \fRapplication/n-quads\fP
.IP "\(bu" 2
Add extension \fR\&.nt\fP to \fRapplication/n-triples\fP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Mark \fRtext/less\fP as compressible
.PP
.SH "1\&.37\&.0 / 2018-10-19"
.PP
.IP "\(bu" 2
Add extensions to HEIC image types
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.36\&.0 / 2018-08-20"
.PP
.IP "\(bu" 2
Add Apple file extensions from IANA
.IP "\(bu" 2
Add extensions from IANA for \fRimage/*\fP types
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.35\&.0 / 2018-07-15"
.PP
.IP "\(bu" 2
Add extension \fR\&.owl\fP to \fRapplication/rdf+xml\fP
.IP "\(bu" 2
Add new upstream MIME types
.IP "  \(bu" 4
Removes extension \fR\&.woff\fP from \fRapplication/font-woff\fP
.PP

.PP
.SH "1\&.34\&.0 / 2018-06-03"
.PP
.IP "\(bu" 2
Add extension \fR\&.csl\fP to \fRapplication/vnd\&.citationstyles\&.style+xml\fP
.IP "\(bu" 2
Add extension \fR\&.es\fP to \fRapplication/ecmascript\fP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add \fRUTF-8\fP as default charset for \fRtext/turtle\fP
.IP "\(bu" 2
Mark all XML-derived types as compressible
.PP
.SH "1\&.33\&.0 / 2018-02-15"
.PP
.IP "\(bu" 2
Add extensions from IANA for \fRmessage/*\fP types
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Fix some incorrect OOXML types
.IP "\(bu" 2
Remove \fRapplication/font-woff2\fP
.PP
.SH "1\&.32\&.0 / 2017-11-29"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Update \fRtext/hjson\fP to registered \fRapplication/hjson\fP
.IP "\(bu" 2
Add \fRtext/shex\fP with extension \fR\&.shex\fP
.PP
.SH "1\&.31\&.0 / 2017-10-25"
.PP
.IP "\(bu" 2
Add \fRapplication/raml+yaml\fP with extension \fR\&.raml\fP
.IP "\(bu" 2
Add \fRapplication/wasm\fP with extension \fR\&.wasm\fP
.IP "\(bu" 2
Add new \fRfont\fP type from IANA
.IP "\(bu" 2
Add new upstream font extensions
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add extensions for JPEG-2000 images
.PP
.SH "1\&.30\&.0 / 2017-08-27"
.PP
.IP "\(bu" 2
Add \fRapplication/vnd\&.ms-outlook\fP
.IP "\(bu" 2
Add \fRapplication/x-arj\fP
.IP "\(bu" 2
Add extension \fR\&.mjs\fP to \fRapplication/javascript\fP
.IP "\(bu" 2
Add glTF types and extensions
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add \fRtext/x-org\fP
.IP "\(bu" 2
Add VirtualBox MIME types
.IP "\(bu" 2
Fix \fRsource\fP records for \fRvideo/*\fP types that are IANA
.IP "\(bu" 2
Update \fRfont/opentype\fP to registered \fRfont/otf\fP
.PP
.SH "1\&.29\&.0 / 2017-07-10"
.PP
.IP "\(bu" 2
Add \fRapplication/fido\&.trusted-apps+json\fP
.IP "\(bu" 2
Add extension \fR\&.wadl\fP to \fRapplication/vnd\&.sun\&.wadl+xml\fP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add \fRUTF-8\fP as default charset for \fRtext/css\fP
.PP
.SH "1\&.28\&.0 / 2017-05-14"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add extension \fR\&.gz\fP to \fRapplication/gzip\fP
.IP "\(bu" 2
Update extensions \fR\&.md\fP and \fR\&.markdown\fP to be \fRtext/markdown\fP
.PP
.SH "1\&.27\&.0 / 2017-03-16"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add \fRimage/apng\fP with extension \fR\&.apng\fP
.PP
.SH "1\&.26\&.0 / 2017-01-14"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add extension \fR\&.geojson\fP to \fRapplication/geo+json\fP
.PP
.SH "1\&.25\&.0 / 2016-11-11"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.24\&.0 / 2016-09-18"
.PP
.IP "\(bu" 2
Add \fRaudio/mp3\fP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.23\&.0 / 2016-05-01"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Add extension \fR\&.3gpp\fP to \fRaudio/3gpp\fP
.PP
.SH "1\&.22\&.0 / 2016-02-15"
.PP
.IP "\(bu" 2
Add \fRtext/slim\fP
.IP "\(bu" 2
Add extension \fR\&.rng\fP to \fRapplication/xml\fP
.IP "\(bu" 2
Add new upstream MIME types
.IP "\(bu" 2
Fix extension of \fRapplication/dash+xml\fP to be \fR\&.mpd\fP
.IP "\(bu" 2
Update primary extension to \fR\&.m4a\fP for \fRaudio/mp4\fP
.PP
.SH "1\&.21\&.0 / 2016-01-06"
.PP
.IP "\(bu" 2
Add Google document types
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.20\&.0 / 2015-11-10"
.PP
.IP "\(bu" 2
Add \fRtext/x-suse-ymp\fP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.19\&.0 / 2015-09-17"
.PP
.IP "\(bu" 2
Add \fRapplication/vnd\&.apple\&.pkpass\fP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.18\&.0 / 2015-09-03"
.PP
.IP "\(bu" 2
Add new upstream MIME types
.PP
.SH "1\&.17\&.0 / 2015-08-13"
.PP
.IP "\(bu" 2
Add \fRapplication/x-msdos-program\fP
.IP "\(bu" 2
Add \fRaudio/g711-0\fP
.IP "\(bu" 2
Add \fRimage/vnd\&.mozilla\&.apng\fP
.IP "\(bu" 2
Add extension \fR\&.exe\fP to \fRapplication/x-msdos-program\fP
.PP
.SH "1\&.16\&.0 / 2015-07-29"
.PP
.IP "\(bu" 2
Add \fRapplication/vnd\&.uri-map\fP
.PP
.SH "1\&.15\&.0 / 2015-07-13"
.PP
.IP "\(bu" 2
Add \fRapplication/x-httpd-php\fP
.PP
.SH "1\&.14\&.0 / 2015-06-25"
.PP
.IP "\(bu" 2
Add \fRapplication/scim+json\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.3gpp\&.ussd+xml\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.biopax\&.rdf+xml\fP
.IP "\(bu" 2
Add \fRtext/x-processing\fP
.PP
.SH "1\&.13\&.0 / 2015-06-07"
.PP
.IP "\(bu" 2
Add nginx as a source
.IP "\(bu" 2
Add \fRapplication/x-cocoa\fP
.IP "\(bu" 2
Add \fRapplication/x-java-archive-diff\fP
.IP "\(bu" 2
Add \fRapplication/x-makeself\fP
.IP "\(bu" 2
Add \fRapplication/x-perl\fP
.IP "\(bu" 2
Add \fRapplication/x-pilot\fP
.IP "\(bu" 2
Add \fRapplication/x-redhat-package-manager\fP
.IP "\(bu" 2
Add \fRapplication/x-sea\fP
.IP "\(bu" 2
Add \fRaudio/x-m4a\fP
.IP "\(bu" 2
Add \fRaudio/x-realaudio\fP
.IP "\(bu" 2
Add \fRimage/x-jng\fP
.IP "\(bu" 2
Add \fRtext/mathml\fP
.PP
.SH "1\&.12\&.0 / 2015-06-05"
.PP
.IP "\(bu" 2
Add \fRapplication/bdoc\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.hyperdrive+json\fP
.IP "\(bu" 2
Add \fRapplication/x-bdoc\fP
.IP "\(bu" 2
Add extension \fR\&.rtf\fP to \fRtext/rtf\fP
.PP
.SH "1\&.11\&.0 / 2015-05-31"
.PP
.IP "\(bu" 2
Add \fRaudio/wav\fP
.IP "\(bu" 2
Add \fRaudio/wave\fP
.IP "\(bu" 2
Add extension \fR\&.litcoffee\fP to \fRtext/coffeescript\fP
.IP "\(bu" 2
Add extension \fR\&.sfd-hdstx\fP to \fRapplication/vnd\&.hydrostatix\&.sof-data\fP
.IP "\(bu" 2
Add extension \fR\&.n-gage\fP to \fRapplication/vnd\&.nokia\&.n-gage\&.symbian\&.install\fP
.PP
.SH "1\&.10\&.0 / 2015-05-19"
.PP
.IP "\(bu" 2
Add \fRapplication/vnd\&.balsamiq\&.bmpr\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.microsoft\&.portable-executable\fP
.IP "\(bu" 2
Add \fRapplication/x-ns-proxy-autoconfig\fP
.PP
.SH "1\&.9\&.1 / 2015-04-19"
.PP
.IP "\(bu" 2
Remove \fR\&.json\fP extension from \fRapplication/manifest+json\fP
.IP "  \(bu" 4
This is causing bugs downstream
.PP

.PP
.SH "1\&.9\&.0 / 2015-04-19"
.PP
.IP "\(bu" 2
Add \fRapplication/manifest+json\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.micro+json\fP
.IP "\(bu" 2
Add \fRimage/vnd\&.zbrush\&.pcx\fP
.IP "\(bu" 2
Add \fRimage/x-ms-bmp\fP
.PP
.SH "1\&.8\&.0 / 2015-03-13"
.PP
.IP "\(bu" 2
Add \fRapplication/vnd\&.citationstyles\&.style+xml\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.fastcopy-disk-image\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.gov\&.sk\&.xmldatacontainer+xml\fP
.IP "\(bu" 2
Add extension \fR\&.jsonld\fP to \fRapplication/ld+json\fP
.PP
.SH "1\&.7\&.0 / 2015-02-08"
.PP
.IP "\(bu" 2
Add \fRapplication/vnd\&.gerber\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.msa-disk-image\fP
.PP
.SH "1\&.6\&.1 / 2015-02-05"
.PP
.IP "\(bu" 2
Community extensions ownership transferred from \fRnode-mime\fP
.PP
.SH "1\&.6\&.0 / 2015-01-29"
.PP
.IP "\(bu" 2
Add \fRapplication/jose\fP
.IP "\(bu" 2
Add \fRapplication/jose+json\fP
.IP "\(bu" 2
Add \fRapplication/json-seq\fP
.IP "\(bu" 2
Add \fRapplication/jwk+json\fP
.IP "\(bu" 2
Add \fRapplication/jwk-set+json\fP
.IP "\(bu" 2
Add \fRapplication/jwt\fP
.IP "\(bu" 2
Add \fRapplication/rdap+json\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.gov\&.sk\&.e-form+xml\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.ims\&.imsccv1p3\fP
.PP
.SH "1\&.5\&.0 / 2014-12-30"
.PP
.IP "\(bu" 2
Add \fRapplication/vnd\&.oracle\&.resource+json\fP
.IP "\(bu" 2
Fix various invalid MIME type entries
.IP "  \(bu" 4
\fRapplication/mbox+xml\fP
.IP "  \(bu" 4
\fRapplication/oscp-response\fP
.IP "  \(bu" 4
\fRapplication/vwg-multiplexed\fP
.IP "  \(bu" 4
\fRaudio/g721\fP
.PP

.PP
.SH "1\&.4\&.0 / 2014-12-21"
.PP
.IP "\(bu" 2
Add \fRapplication/vnd\&.ims\&.imsccv1p2\fP
.IP "\(bu" 2
Fix various invalid MIME type entries
.IP "  \(bu" 4
\fRapplication/vnd-acucobol\fP
.IP "  \(bu" 4
\fRapplication/vnd-curl\fP
.IP "  \(bu" 4
\fRapplication/vnd-dart\fP
.IP "  \(bu" 4
\fRapplication/vnd-dxr\fP
.IP "  \(bu" 4
\fRapplication/vnd-fdf\fP
.IP "  \(bu" 4
\fRapplication/vnd-mif\fP
.IP "  \(bu" 4
\fRapplication/vnd-sema\fP
.IP "  \(bu" 4
\fRapplication/vnd-wap-wmlc\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.adobe\&.flash-movie\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.dece-zip\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.dvb_service\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.micrografx-igx\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.sealed-doc\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.sealed-eml\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.sealed-mht\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.sealed-ppt\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.sealed-tiff\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.sealed-xls\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.sealedmedia\&.softseal-html\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.sealedmedia\&.softseal-pdf\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.wap-slc\fP
.IP "  \(bu" 4
\fRapplication/vnd\&.wap-wbxml\fP
.IP "  \(bu" 4
\fRaudio/vnd\&.sealedmedia\&.softseal-mpeg\fP
.IP "  \(bu" 4
\fRimage/vnd-djvu\fP
.IP "  \(bu" 4
\fRimage/vnd-svf\fP
.IP "  \(bu" 4
\fRimage/vnd-wap-wbmp\fP
.IP "  \(bu" 4
\fRimage/vnd\&.sealed-png\fP
.IP "  \(bu" 4
\fRimage/vnd\&.sealedmedia\&.softseal-gif\fP
.IP "  \(bu" 4
\fRimage/vnd\&.sealedmedia\&.softseal-jpg\fP
.IP "  \(bu" 4
\fRmodel/vnd-dwf\fP
.IP "  \(bu" 4
\fRmodel/vnd\&.parasolid\&.transmit-binary\fP
.IP "  \(bu" 4
\fRmodel/vnd\&.parasolid\&.transmit-text\fP
.IP "  \(bu" 4
\fRtext/vnd-a\fP
.IP "  \(bu" 4
\fRtext/vnd-curl\fP
.IP "  \(bu" 4
\fRtext/vnd\&.wap-wml\fP
.PP

.IP "\(bu" 2
Remove example template MIME types
.IP "  \(bu" 4
\fRapplication/example\fP
.IP "  \(bu" 4
\fRaudio/example\fP
.IP "  \(bu" 4
\fRimage/example\fP
.IP "  \(bu" 4
\fRmessage/example\fP
.IP "  \(bu" 4
\fRmodel/example\fP
.IP "  \(bu" 4
\fRmultipart/example\fP
.IP "  \(bu" 4
\fRtext/example\fP
.IP "  \(bu" 4
\fRvideo/example\fP
.PP

.PP
.SH "1\&.3\&.1 / 2014-12-16"
.PP
.IP "\(bu" 2
Fix missing extensions
.IP "  \(bu" 4
\fRapplication/json5\fP
.IP "  \(bu" 4
\fRtext/hjson\fP
.PP

.PP
.SH "1\&.3\&.0 / 2014-12-07"
.PP
.IP "\(bu" 2
Add \fRapplication/a2l\fP
.IP "\(bu" 2
Add \fRapplication/aml\fP
.IP "\(bu" 2
Add \fRapplication/atfx\fP
.IP "\(bu" 2
Add \fRapplication/atxml\fP
.IP "\(bu" 2
Add \fRapplication/cdfx+xml\fP
.IP "\(bu" 2
Add \fRapplication/dii\fP
.IP "\(bu" 2
Add \fRapplication/json5\fP
.IP "\(bu" 2
Add \fRapplication/lxf\fP
.IP "\(bu" 2
Add \fRapplication/mf4\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.apache\&.thrift\&.compact\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.apache\&.thrift\&.json\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.coffeescript\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.enphase\&.envoy\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.ims\&.imsccv1p1\fP
.IP "\(bu" 2
Add \fRtext/csv-schema\fP
.IP "\(bu" 2
Add \fRtext/hjson\fP
.IP "\(bu" 2
Add \fRtext/markdown\fP
.IP "\(bu" 2
Add \fRtext/yaml\fP
.PP
.SH "1\&.2\&.0 / 2014-11-09"
.PP
.IP "\(bu" 2
Add \fRapplication/cea\fP
.IP "\(bu" 2
Add \fRapplication/dit\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.gov\&.sk\&.e-form+zip\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.tmd\&.mediaflex\&.api+xml\fP
.IP "\(bu" 2
Type \fRapplication/epub+zip\fP is now IANA-registered
.PP
.SH "1\&.1\&.2 / 2014-10-23"
.PP
.IP "\(bu" 2
Rebuild database for \fRapplication/x-www-form-urlencoded\fP change
.PP
.SH "1\&.1\&.1 / 2014-10-20"
.PP
.IP "\(bu" 2
Mark \fRapplication/x-www-form-urlencoded\fP as compressible\&.
.PP
.SH "1\&.1\&.0 / 2014-09-28"
.PP
.IP "\(bu" 2
Add \fRapplication/font-woff2\fP
.PP
.SH "1\&.0\&.3 / 2014-09-25"
.PP
.IP "\(bu" 2
Fix engine requirement in package
.PP
.SH "1\&.0\&.2 / 2014-09-25"
.PP
.IP "\(bu" 2
Add \fRapplication/coap-group+json\fP
.IP "\(bu" 2
Add \fRapplication/dcd\fP
.IP "\(bu" 2
Add \fRapplication/vnd\&.apache\&.thrift\&.binary\fP
.IP "\(bu" 2
Add \fRimage/vnd\&.tencent\&.tap\fP
.IP "\(bu" 2
Mark all JSON-derived types as compressible
.IP "\(bu" 2
Update \fRtext/vtt\fP data
.PP
.SH "1\&.0\&.1 / 2014-08-30"
.PP
.IP "\(bu" 2
Fix extension ordering
.PP
.SH "1\&.0\&.0 / 2014-08-30"
.PP
.IP "\(bu" 2
Add \fRapplication/atf\fP
.IP "\(bu" 2
Add \fRapplication/merge-patch+json\fP
.IP "\(bu" 2
Add \fRmultipart/x-mixed-replace\fP
.IP "\(bu" 2
Add `source: 'apache'\fRmetadata\fP
.IP "\(bu" 2
\fRAdd\fPsource: 'iana'` metadata
.IP "\(bu" 2
Remove badly-assumed charset data 
.PP

