.TH "md_backend_2node__modules_2http-proxy-agent_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2http-proxy-agent_2_r_e_a_d_m_e \- http-proxy-agent 
.PP

.SS "An HTTP(s) proxy \fRhttp\&.Agent\fP implementation for HTTP"
\fR\fP.PP
This module provides an \fRhttp\&.Agent\fP implementation that connects to a specified HTTP or HTTPS proxy server, and can be used with the built-in \fRhttp\fP module\&.
.PP
\fBNote:\fP For HTTP proxy usage with the \fRhttps\fP module, check out \fR\fRnode-https-proxy-agent\fP\fP\&.
.SH "Installation"
.PP
Install with \fRnpm\fP:
.PP
.PP
.nf
 bash
$ npm install http\-proxy\-agent
.fi
.PP
.SH "Example"
.PP
.PP
.nf
 js
var url = require('url');
var http = require('http');
var HttpProxyAgent = require('http\-proxy\-agent');

// HTTP/HTTPS proxy to connect to
var proxy = process\&.env\&.http_proxy || 'http://168\&.63\&.76\&.32:3128';
console\&.log('using proxy server %j', proxy);

// HTTP endpoint for the proxy to connect to
var endpoint = process\&.argv[2] || 'http://nodejs\&.org/api/';
console\&.log('attempting to GET %j', endpoint);
var opts = url\&.parse(endpoint);

// create an instance of the `HttpProxyAgent` class with the proxy server information
var agent = new HttpProxyAgent(proxy);
opts\&.agent = agent;

http\&.get(opts, function (res) {
  console\&.log('"response" event!', res\&.headers);
  res\&.pipe(process\&.stdout);
});
.fi
.PP
.SH "License"
.PP
(The MIT License)
.PP
Copyright (c) 2013 Nathan Rajlich <nathan@tootallnate.net>
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
