.TH "md_backend_2node__modules_2on-finished_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2on-finished_2_h_i_s_t_o_r_y \- 2\&.4\&.1 / 2022-02-22 
.PP

.IP "\(bu" 2
Fix error on early async hooks implementations
.PP
.SH "2\&.4\&.0 / 2022-02-21"
.PP
.IP "\(bu" 2
Prevent loss of async hooks context
.PP
.SH "2\&.3\&.0 / 2015-05-26"
.PP
.IP "\(bu" 2
Add defined behavior for HTTP \fRCONNECT\fP requests
.IP "\(bu" 2
Add defined behavior for HTTP \fRUpgrade\fP requests
.IP "\(bu" 2
deps: ee-first@1\&.1\&.1
.PP
.SH "2\&.2\&.1 / 2015-04-22"
.PP
.IP "\(bu" 2
Fix \fRisFinished(req)\fP when data buffered
.PP
.SH "2\&.2\&.0 / 2014-12-22"
.PP
.IP "\(bu" 2
Add message object to callback arguments
.PP
.SH "2\&.1\&.1 / 2014-10-22"
.PP
.IP "\(bu" 2
Fix handling of pipelined requests
.PP
.SH "2\&.1\&.0 / 2014-08-16"
.PP
.IP "\(bu" 2
Check if \fRsocket\fP is detached
.IP "\(bu" 2
Return \fRundefined\fP for \fRisFinished\fP if state unknown
.PP
.SH "2\&.0\&.0 / 2014-08-16"
.PP
.IP "\(bu" 2
Add \fRisFinished\fP function
.IP "\(bu" 2
Move to \fRjshttp\fP organization
.IP "\(bu" 2
Remove support for plain socket argument
.IP "\(bu" 2
Rename to \fRon-finished\fP
.IP "\(bu" 2
Support both \fRreq\fP and \fRres\fP as arguments
.IP "\(bu" 2
deps: ee-first@1\&.0\&.5
.PP
.SH "1\&.2\&.2 / 2014-06-10"
.PP
.IP "\(bu" 2
Reduce listeners added to emitters
.IP "  \(bu" 4
avoids 'event emitter leak' warnings when used multiple times on same request
.PP

.PP
.SH "1\&.2\&.1 / 2014-06-08"
.PP
.IP "\(bu" 2
Fix returned value when already finished
.PP
.SH "1\&.2\&.0 / 2014-06-05"
.PP
.IP "\(bu" 2
Call callback when called on already-finished socket
.PP
.SH "1\&.1\&.4 / 2014-05-27"
.PP
.IP "\(bu" 2
Support node\&.js 0\&.8
.PP
.SH "1\&.1\&.3 / 2014-04-30"
.PP
.IP "\(bu" 2
Make sure errors passed as instanceof \fRError\fP
.PP
.SH "1\&.1\&.2 / 2014-04-18"
.PP
.IP "\(bu" 2
Default the \fRsocket\fP to passed-in object
.PP
.SH "1\&.1\&.1 / 2014-01-16"
.PP
.IP "\(bu" 2
Rename module to \fRfinished\fP
.PP
.SH "1\&.1\&.0 / 2013-12-25"
.PP
.IP "\(bu" 2
Call callback when called on already-errored socket
.PP
.SH "1\&.0\&.1 / 2013-12-20"
.PP
.IP "\(bu" 2
Actually pass the error to the callback
.PP
.SH "1\&.0\&.0 / 2013-12-20"
.PP
.IP "\(bu" 2
Initial release 
.PP

