.TH "md_backend_2node__modules_2range-parser_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2range-parser_2_h_i_s_t_o_r_y \- 1\&.2\&.1 / 2019-05-10 
.PP

.IP "\(bu" 2
Improve error when \fRstr\fP is not a string
.PP
.SH "1\&.2\&.0 / 2016-06-01"
.PP
.IP "\(bu" 2
Add \fRcombine\fP option to combine overlapping ranges
.PP
.SH "1\&.1\&.0 / 2016-05-13"
.PP
.IP "\(bu" 2
Fix incorrectly returning -1 when there is at least one valid range
.IP "\(bu" 2
perf: remove internal function
.PP
.SH "1\&.0\&.3 / 2015-10-29"
.PP
.IP "\(bu" 2
perf: enable strict mode
.PP
.SH "1\&.0\&.2 / 2014-09-08"
.PP
.IP "\(bu" 2
Support Node\&.js 0\&.6
.PP
.SH "1\&.0\&.1 / 2014-09-07"
.PP
.IP "\(bu" 2
Move repository to jshttp
.PP
.SH "1\&.0\&.0 / 2013-12-11"
.PP
.IP "\(bu" 2
Add repository to package\&.json
.IP "\(bu" 2
Add MIT license
.PP
.SH "0\&.0\&.4 / 2012-06-17"
.PP
.IP "\(bu" 2
Change ret -1 for unsatisfiable and -2 when invalid
.PP
.SH "0\&.0\&.3 / 2012-06-17"
.PP
.IP "\(bu" 2
Fix last-byte-pos default to len - 1
.PP
.SH "0\&.0\&.2 / 2012-06-14"
.PP
.IP "\(bu" 2
Add \fR\&.type\fP
.PP
.SH "0\&.0\&.1 / 2012-06-11"
.PP
.IP "\(bu" 2
Initial release 
.PP

