.TH "md_backend_2node__modules_2hasown_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2hasown_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv2\&.0\&.2\fP - 2024-03-10"
.PP
.SS "Commits"
.IP "\(bu" 2
[types] use shared config \fR\fR68e9d4d\fP\fP
.IP "\(bu" 2
[actions] remove redundant finisher; use reusable workflow \fR\fR241a68e\fP\fP
.IP "\(bu" 2
[Tests] increase coverage \fR\fR4125c0d\fP\fP
.IP "\(bu" 2
[Tests] skip \fRnpm ls\fP in old node due to TS \fR\fR01b9282\fP\fP
.IP "\(bu" 2
[types] improve predicate type \fR\fRd340f85\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR70089fc\fP\fP
.IP "\(bu" 2
[Tests] use \fR@arethetypeswrong/cli\fP \fR\fR50b272c\fP\fP
.PP
.SH "\fRv2\&.0\&.1\fP - 2024-02-10"
.PP
.SS "Commits"
.IP "\(bu" 2
[types] use a handwritten d\&.ts file; fix exported type \fR\fR012b989\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/function-bind\fP, \fR@types/mock-property\fP, \fR@types/tape\fP, \fRaud\fP, \fRmock-property\fP, \fRnpmignore\fP, \fRtape\fP, \fRtypescript\fP \fR\fR977a56f\fP\fP
.IP "\(bu" 2
[meta] add \fRsideEffects\fP flag \fR\fR3a60b7b\fP\fP
.PP
.SH "\fRv2\&.0\&.0\fP - 2023-10-19"
.PP
.SS "Commits"
.IP "\(bu" 2
revamped implementation, tests, readme \fR\fR72bf8b3\fP\fP
.IP "\(bu" 2
[meta] revamp package\&.json \fR\fR079775f\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR6640e23\fP\fP
.PP
.SH "v1\&.0\&.1 - 2023-10-10"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial commit \fR\fR8dbfde6\fP\fP 
.PP

