.TH "md_backend_2node__modules_2bytes_2_history" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2bytes_2_history \- 3\&.1\&.2 / 2022-01-27 
.PP

.IP "\(bu" 2
Fix return value for un-parsable strings
.PP
.SH "3\&.1\&.1 / 2024-11-15"
.PP
.IP "\(bu" 2
Fix 'thousandsSeparator' incorrecting formatting fractional part
.PP
.SH "3\&.1\&.0 / 2019-01-22"
.PP
.IP "\(bu" 2
Add petabyte (\fRpb\fP) support
.PP
.SH "3\&.0\&.0 / 2017-08-31"
.PP
.IP "\(bu" 2
Change 'kB' to 'KB' in format output
.IP "\(bu" 2
Remove support for Node\&.js 0\&.6
.IP "\(bu" 2
Remove support for ComponentJS
.PP
.SH "2\&.5\&.0 / 2017-03-24"
.PP
.IP "\(bu" 2
Add option 'unit'
.PP
.SH "2\&.4\&.0 / 2016-06-01"
.PP
.IP "\(bu" 2
Add option 'unitSeparator'
.PP
.SH "2\&.3\&.0 / 2016-02-15"
.PP
.IP "\(bu" 2
Drop partial bytes on all parsed units
.IP "\(bu" 2
Fix non-finite numbers to \fR\&.format\fP to return \fRnull\fP
.IP "\(bu" 2
Fix parsing byte string that looks like hex
.IP "\(bu" 2
perf: hoist regular expressions
.PP
.SH "2\&.2\&.0 / 2015-11-13"
.PP
.IP "\(bu" 2
add option 'decimalPlaces'
.IP "\(bu" 2
add option 'fixedDecimals'
.PP
.SH "2\&.1\&.0 / 2015-05-21"
.PP
.IP "\(bu" 2
add \fR\&.format\fP export
.IP "\(bu" 2
add \fR\&.parse\fP export
.PP
.SH "2\&.0\&.2 / 2015-05-20"
.PP
.IP "\(bu" 2
remove map recreation
.IP "\(bu" 2
remove unnecessary object construction
.PP
.SH "2\&.0\&.1 / 2015-05-07"
.PP
.IP "\(bu" 2
fix browserify require
.IP "\(bu" 2
remove node\&.extend dependency
.PP
.SH "2\&.0\&.0 / 2015-04-12"
.PP
.IP "\(bu" 2
add option 'case'
.IP "\(bu" 2
add option 'thousandsSeparator'
.IP "\(bu" 2
return 'null' on invalid parse input
.IP "\(bu" 2
support proper round-trip: bytes(bytes(num)) === num
.IP "\(bu" 2
units no longer case sensitive when parsing
.PP
.SH "1\&.0\&.0 / 2014-05-05"
.PP
.IP "\(bu" 2
add negative support\&. fixes #6
.PP
.SH "0\&.3\&.0 / 2014-03-19"
.PP
.IP "\(bu" 2
added terabyte support
.PP
.SH "0\&.2\&.1 / 2013-04-01"
.PP
.IP "\(bu" 2
add \&.component
.PP
.SH "0\&.2\&.0 / 2012-10-28"
.PP
.IP "\(bu" 2
bytes(200)\&.should\&.eql('200b')
.PP
.SH "0\&.1\&.0 / 2012-07-04"
.PP
.IP "\(bu" 2
add bytes to string conversion [yields] 
.PP

