.TH "md_backend_2node__modules_2strip-ansi_2readme" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2strip-ansi_2readme \- strip-ansi \fR\fP 
.PP
 
.PP
.RS 4
Strip \fRANSI escape codes\fP from a string 
.RE
.PP
.SH "Install"
.PP
.PP
.nf
$ npm install strip\-ansi
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
const stripAnsi = require('strip\-ansi');

stripAnsi('\\u001B[4mUnicorn\\u001B[0m');
//=> 'Unicorn'

stripAnsi('\\u001B]8;;https://github\&.com\\u0007Click\\u001B]8;;\\u0007');
//=> 'Click'
.fi
.PP
.SH "strip-ansi for enterprise"
.PP
Available as part of the Tidelift Subscription\&.
.PP
The maintainers of strip-ansi and thousands of other packages are working with Tidelift to deliver commercial support and maintenance for the open source dependencies you use to build your applications\&. Save time, reduce risk, and improve code health, while paying the maintainers of the exact dependencies you use\&. \fRLearn more\&.\fP
.SH "Related"
.PP
.IP "\(bu" 2
\fRstrip-ansi-cli\fP - CLI for this module
.IP "\(bu" 2
\fRstrip-ansi-stream\fP - Streaming version of this module
.IP "\(bu" 2
\fRhas-ansi\fP - Check if a string has ANSI escape codes
.IP "\(bu" 2
\fRansi-regex\fP - Regular expression for matching ANSI escape codes
.IP "\(bu" 2
\fRchalk\fP - Terminal string styling done right
.PP
.SH "Maintainers"
.PP
.IP "\(bu" 2
\fRSindre Sorhus\fP
.IP "\(bu" 2
\fRJosh Junon\fP 
.PP

