.TH "md_backend_2node__modules_2gopd_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2gopd_2_r_e_a_d_m_e \- gopd \*{\fR\fP\*}  
.PP
 \fR\fP \fR\fP [][license-url] \fR\fP
.PP
\fR\fP.PP
\fRObject\&.getOwnPropertyDescriptor\fP, but accounts for IE's broken implementation\&.
.SH "Usage"
.PP
.PP
.nf
var gOPD = require('gopd');
var assert = require('assert');

if (gOPD) {
    assert\&.equal(typeof gOPD, 'function', 'descriptors supported');
    // use gOPD like Object\&.getOwnPropertyDescriptor here
} else {
    assert\&.ok(!gOPD, 'descriptors not supported');
}
.fi
.PP
 
