.TH "md_backend_2node__modules_2accepts_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2accepts_2_h_i_s_t_o_r_y \- 1\&.3\&.8 / 2022-02-02 
.PP

.IP "\(bu" 2
deps: mime-types2\&.1\&.34
.IP "  \(bu" 4
deps: mime-db1\&.51\&.0
.PP

.IP "\(bu" 2
deps: negotiator@0\&.6\&.3
.PP
.SH "1\&.3\&.7 / 2019-04-29"
.PP
.IP "\(bu" 2
deps: negotiator@0\&.6\&.2
.IP "  \(bu" 4
Fix sorting charset, encoding, and language with extra parameters
.PP

.PP
.SH "1\&.3\&.6 / 2019-04-28"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.24
.IP "  \(bu" 4
deps: mime-db1\&.40\&.0
.PP

.PP
.SH "1\&.3\&.5 / 2018-02-28"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.18
.IP "  \(bu" 4
deps: mime-db1\&.33\&.0
.PP

.PP
.SH "1\&.3\&.4 / 2017-08-22"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.16
.IP "  \(bu" 4
deps: mime-db1\&.29\&.0
.PP

.PP
.SH "1\&.3\&.3 / 2016-05-02"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.11
.IP "  \(bu" 4
deps: mime-db1\&.23\&.0
.PP

.IP "\(bu" 2
deps: negotiator@0\&.6\&.1
.IP "  \(bu" 4
perf: improve \fRAccept\fP parsing speed
.IP "  \(bu" 4
perf: improve \fRAccept-Charset\fP parsing speed
.IP "  \(bu" 4
perf: improve \fRAccept-Encoding\fP parsing speed
.IP "  \(bu" 4
perf: improve \fRAccept-Language\fP parsing speed
.PP

.PP
.SH "1\&.3\&.2 / 2016-03-08"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.10
.IP "  \(bu" 4
Fix extension of \fRapplication/dash+xml\fP
.IP "  \(bu" 4
Update primary extension for \fRaudio/mp4\fP
.IP "  \(bu" 4
deps: mime-db1\&.22\&.0
.PP

.PP
.SH "1\&.3\&.1 / 2016-01-19"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.9
.IP "  \(bu" 4
deps: mime-db1\&.21\&.0
.PP

.PP
.SH "1\&.3\&.0 / 2015-09-29"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.7
.IP "  \(bu" 4
deps: mime-db1\&.19\&.0
.PP

.IP "\(bu" 2
deps: negotiator@0\&.6\&.0
.IP "  \(bu" 4
Fix including type extensions in parameters in \fRAccept\fP parsing
.IP "  \(bu" 4
Fix parsing \fRAccept\fP parameters with quoted equals
.IP "  \(bu" 4
Fix parsing \fRAccept\fP parameters with quoted semicolons
.IP "  \(bu" 4
Lazy-load modules from main entry point
.IP "  \(bu" 4
perf: delay type concatenation until needed
.IP "  \(bu" 4
perf: enable strict mode
.IP "  \(bu" 4
perf: hoist regular expressions
.IP "  \(bu" 4
perf: remove closures getting spec properties
.IP "  \(bu" 4
perf: remove a closure from media type parsing
.IP "  \(bu" 4
perf: remove property delete from media type parsing
.PP

.PP
.SH "1\&.2\&.13 / 2015-09-06"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.6
.IP "  \(bu" 4
deps: mime-db1\&.18\&.0
.PP

.PP
.SH "1\&.2\&.12 / 2015-07-30"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.4
.IP "  \(bu" 4
deps: mime-db1\&.16\&.0
.PP

.PP
.SH "1\&.2\&.11 / 2015-07-16"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.3
.IP "  \(bu" 4
deps: mime-db1\&.15\&.0
.PP

.PP
.SH "1\&.2\&.10 / 2015-07-01"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.2
.IP "  \(bu" 4
deps: mime-db1\&.14\&.0
.PP

.PP
.SH "1\&.2\&.9 / 2015-06-08"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.1
.IP "  \(bu" 4
perf: fix deopt during mapping
.PP

.PP
.SH "1\&.2\&.8 / 2015-06-07"
.PP
.IP "\(bu" 2
deps: mime-types2\&.1\&.0
.IP "  \(bu" 4
deps: mime-db1\&.13\&.0
.PP

.IP "\(bu" 2
perf: avoid argument reassignment & argument slice
.IP "\(bu" 2
perf: avoid negotiator recursive construction
.IP "\(bu" 2
perf: enable strict mode
.IP "\(bu" 2
perf: remove unnecessary bitwise operator
.PP
.SH "1\&.2\&.7 / 2015-05-10"
.PP
.IP "\(bu" 2
deps: negotiator@0\&.5\&.3
.IP "  \(bu" 4
Fix media type parameter matching to be case-insensitive
.PP

.PP
.SH "1\&.2\&.6 / 2015-05-07"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.11
.IP "  \(bu" 4
deps: mime-db1\&.9\&.1
.PP

.IP "\(bu" 2
deps: negotiator@0\&.5\&.2
.IP "  \(bu" 4
Fix comparing media types with quoted values
.IP "  \(bu" 4
Fix splitting media types with quoted commas
.PP

.PP
.SH "1\&.2\&.5 / 2015-03-13"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.10
.IP "  \(bu" 4
deps: mime-db1\&.8\&.0
.PP

.PP
.SH "1\&.2\&.4 / 2015-02-14"
.PP
.IP "\(bu" 2
Support Node\&.js 0\&.6
.IP "\(bu" 2
deps: mime-types2\&.0\&.9
.IP "  \(bu" 4
deps: mime-db1\&.7\&.0
.PP

.IP "\(bu" 2
deps: negotiator@0\&.5\&.1
.IP "  \(bu" 4
Fix preference sorting to be stable for long acceptable lists
.PP

.PP
.SH "1\&.2\&.3 / 2015-01-31"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.8
.IP "  \(bu" 4
deps: mime-db1\&.6\&.0
.PP

.PP
.SH "1\&.2\&.2 / 2014-12-30"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.7
.IP "  \(bu" 4
deps: mime-db1\&.5\&.0
.PP

.PP
.SH "1\&.2\&.1 / 2014-12-30"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.5
.IP "  \(bu" 4
deps: mime-db1\&.3\&.1
.PP

.PP
.SH "1\&.2\&.0 / 2014-12-19"
.PP
.IP "\(bu" 2
deps: negotiator@0\&.5\&.0
.IP "  \(bu" 4
Fix list return order when large accepted list
.IP "  \(bu" 4
Fix missing identity encoding when q=0 exists
.IP "  \(bu" 4
Remove dynamic building of Negotiator class
.PP

.PP
.SH "1\&.1\&.4 / 2014-12-10"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.4
.IP "  \(bu" 4
deps: mime-db1\&.3\&.0
.PP

.PP
.SH "1\&.1\&.3 / 2014-11-09"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.3
.IP "  \(bu" 4
deps: mime-db1\&.2\&.0
.PP

.PP
.SH "1\&.1\&.2 / 2014-10-14"
.PP
.IP "\(bu" 2
deps: negotiator@0\&.4\&.9
.IP "  \(bu" 4
Fix error when media type has invalid parameter
.PP

.PP
.SH "1\&.1\&.1 / 2014-09-28"
.PP
.IP "\(bu" 2
deps: mime-types2\&.0\&.2
.IP "  \(bu" 4
deps: mime-db1\&.1\&.0
.PP

.IP "\(bu" 2
deps: negotiator@0\&.4\&.8
.IP "  \(bu" 4
Fix all negotiations to be case-insensitive
.IP "  \(bu" 4
Stable sort preferences of same quality according to client order
.PP

.PP
.SH "1\&.1\&.0 / 2014-09-02"
.PP
.IP "\(bu" 2
update \fRmime-types\fP
.PP
.SH "1\&.0\&.7 / 2014-07-04"
.PP
.IP "\(bu" 2
Fix wrong type returned from \fRtype\fP when match after unknown extension
.PP
.SH "1\&.0\&.6 / 2014-06-24"
.PP
.IP "\(bu" 2
deps: negotiator@0\&.4\&.7
.PP
.SH "1\&.0\&.5 / 2014-06-20"
.PP
.IP "\(bu" 2
fix crash when unknown extension given
.PP
.SH "1\&.0\&.4 / 2014-06-19"
.PP
.IP "\(bu" 2
use \fRmime-types\fP
.PP
.SH "1\&.0\&.3 / 2014-06-11"
.PP
.IP "\(bu" 2
deps: negotiator@0\&.4\&.6
.IP "  \(bu" 4
Order by specificity when quality is the same
.PP

.PP
.SH "1\&.0\&.2 / 2014-05-29"
.PP
.IP "\(bu" 2
Fix interpretation when header not in request
.IP "\(bu" 2
deps: pin negotiator@0\&.4\&.5
.PP
.SH "1\&.0\&.1 / 2014-01-18"
.PP
.IP "\(bu" 2
Identity encoding isn't always acceptable
.IP "\(bu" 2
deps: negotiator0\&.4\&.0
.PP
.SH "1\&.0\&.0 / 2013-12-27"
.PP
.IP "\(bu" 2
Genesis 
.PP

