.TH "md_backend_2node__modules_2safer-buffer_2_porting-_buffer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2safer-buffer_2_porting-_buffer \- Porting to the Buffer\&.from/Buffer\&.alloc API 
.PP
  
.SH "Overview"
.PP
.IP "\(bu" 2
\fBVariant 1: Drop support for Node\&.js ≤ 4\&.4\&.x and 5\&.0\&.0 — 5\&.9\&.x\&.\fP (\fIrecommended\fP)
.IP "\(bu" 2
\fBVariant 2: Use a polyfill\fP
.IP "\(bu" 2
\fBVariant 3: manual detection, with safeguards\fP
.PP
.SS "Finding problematic bits of code using grep"
Just run `grep -nrE '[^a-zA-Z](Slow)?Buffer\\s*(' --exclude-dir node_modules`\&.
.PP
It will find all the potentially unsafe places in your own code (with some considerably unlikely exceptions)\&.
.SS "Finding problematic bits of code using Node\&.js 8"
If you’re using Node\&.js ≥ 8\&.0\&.0 (which is recommended), Node\&.js exposes multiple options that help with finding the relevant pieces of code:
.PP
.IP "\(bu" 2
\fR--trace-warnings\fP will make Node\&.js show a stack trace for this warning and other warnings that are printed by Node\&.js\&.
.IP "\(bu" 2
\fR--trace-deprecation\fP does the same thing, but only for deprecation warnings\&.
.IP "\(bu" 2
\fR--pending-deprecation\fP will show more types of deprecation warnings\&. In particular, it will show the \fRBuffer()\fP deprecation warning, even on Node\&.js 8\&.
.PP
.PP
You can set these flags using an environment variable:
.PP
.PP
.nf
$ export NODE_OPTIONS='\-\-trace\-warnings \-\-pending\-deprecation'
$ cat example\&.js
'use strict';
const foo = new Buffer('foo');
$ node example\&.js
(node:7147) [DEP0005] DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns\&. Please use the new Buffer\&.alloc(), Buffer\&.allocUnsafe(), or Buffer\&.from() construction methods instead\&.
    at showFlaggedDeprecation (buffer\&.js:127:13)
    at new Buffer (buffer\&.js:148:3)
    at Object\&.<anonymous> (/path/to/example\&.js:2:13)
    [\&.\&.\&. more stack trace lines \&.\&.\&.]
.fi
.PP
.SS "Finding problematic bits of code using linters"
Eslint rules \fRno-buffer-constructor\fP or \fRnode/no-deprecated-api\fP also find calls to deprecated \fRBuffer()\fP API\&. Those rules are included in some pre-sets\&.
.PP
There is a drawback, though, that it doesn't always \fRwork correctly\fP when \fRBuffer\fP is overriden e\&.g\&. with a polyfill, so recommended is a combination of this and some other method described above\&.
.PP
 
.SH "Variant 1: Drop support for Node\&.js ≤ 4\&.4\&.x and 5\&.0\&.0 — 5\&.9\&.x\&."
.PP
This is the recommended solution nowadays that would imply only minimal overhead\&.
.PP
The Node\&.js 5\&.x release line has been unsupported since July 2016, and the Node\&.js 4\&.x release line reaches its End of Life in April 2018 (→ \fRSchedule\fP)\&. This means that these versions of Node\&.js will \fInot\fP receive any updates, even in case of security issues, so using these release lines should be avoided, if at all possible\&.
.PP
What you would do in this case is to convert all \fRnew Buffer()\fP or \fRBuffer()\fP calls to use \fRBuffer\&.alloc()\fP or \fRBuffer\&.from()\fP, in the following way:
.PP
.IP "\(bu" 2
For \fRnew Buffer(number)\fP, replace it with \fRBuffer\&.alloc(number)\fP\&.
.IP "\(bu" 2
For \fRnew Buffer(string)\fP (or \fRnew Buffer(string, encoding)\fP), replace it with \fRBuffer\&.from(string)\fP (or \fRBuffer\&.from(string, encoding)\fP)\&.
.IP "\(bu" 2
For all other combinations of arguments (these are much rarer), also replace \fRnew Buffer(\&.\&.\&.arguments)\fP with \fRBuffer\&.from(\&.\&.\&.arguments)\fP\&.
.PP
.PP
Note that \fRBuffer\&.alloc()\fP is also \fIfaster\fP on the current Node\&.js versions than \fRnew Buffer(size)\&.fill(0)\fP, which is what you would otherwise need to ensure zero-filling\&.
.PP
Enabling eslint rule \fRno-buffer-constructor\fP or \fRnode/no-deprecated-api\fP is recommended to avoid accidential unsafe Buffer API usage\&.
.PP
There is also a \fRJSCodeshift codemod\fP for automatically migrating Buffer constructors to \fRBuffer\&.alloc()\fP or \fRBuffer\&.from()\fP\&. Note that it currently only works with cases where the arguments are literals or where the constructor is invoked with two arguments\&.
.PP
\fIIf you currently support those older Node\&.js versions and dropping them would be a semver-major change for you, or if you support older branches of your packages, consider using \fBVariant 2\fP or \fBVariant 3\fP on older branches, so people using those older branches will also receive the fix\&. That way, you will eradicate potential issues caused by unguarded Buffer API usage and your users will not observe a runtime deprecation warning when running your code on Node\&.js 10\&.\fP
.PP
 
.SH "Variant 2: Use a polyfill"
.PP
Utilize \fRsafer-buffer\fP as a polyfill to support older Node\&.js versions\&.
.PP
You would take exacly the same steps as in \fBVariant 1\fP, but with a polyfill `const Buffer = require('safer-buffer')\&.Buffer\fRin all files where you use the new\fPBuffer` api\&.
.PP
Make sure that you do not use old \fRnew Buffer\fP API — in any files where the line above is added, using old \fRnew Buffer()\fP API will \fIthrow\fP\&. It will be easy to notice that in CI, though\&.
.PP
Alternatively, you could use \fRbuffer-from\fP and/or \fRbuffer-alloc\fP \fRponyfills\fP — those are great, the only downsides being 4 deps in the tree and slightly more code changes to migrate off them (as you would be using e\&.g\&. \fRBuffer\&.from\fP under a different name)\&. If you need only \fRBuffer\&.from\fP polyfilled — \fRbuffer-from\fP alone which comes with no extra dependencies\&.
.PP
\fIAlternatively, you could use \fRsafe-buffer\fP — it also provides a polyfill, but takes a different approach which has \fRit's drawbacks\fP\&. It will allow you to also use the older \fRnew Buffer()\fP API in your code, though — but that's arguably a benefit, as it is problematic, can cause issues in your code, and will start emitting runtime deprecation warnings starting with Node\&.js 10\&.\fP
.PP
Note that in either case, it is important that you also remove all calls to the old Buffer API manually — just throwing in \fRsafe-buffer\fP doesn't fix the problem by itself, it just provides a polyfill for the new API\&. I have seen people doing that mistake\&.
.PP
Enabling eslint rule \fRno-buffer-constructor\fP or \fRnode/no-deprecated-api\fP is recommended\&.
.PP
\fIDon't forget to drop the polyfill usage once you drop support for Node\&.js < 4\&.5\&.0\&.\fP
.PP
 
.SH "Variant 3 — manual detection, with safeguards"
.PP
This is useful if you create Buffer instances in only a few places (e\&.g\&. one), or you have your own wrapper around them\&.
.SS "Buffer(0)"
This special case for creating empty buffers can be safely replaced with \fRBuffer\&.concat([])\fP, which returns the same result all the way down to Node\&.js 0\&.8\&.x\&.
.SS "Buffer(notNumber)"
Before:
.PP
.PP
.nf
var buf = new Buffer(notNumber, encoding);
.fi
.PP
.PP
After:
.PP
.PP
.nf
var buf;
if (Buffer\&.from && Buffer\&.from !== Uint8Array\&.from) {
  buf = Buffer\&.from(notNumber, encoding);
} else {
  if (typeof notNumber === 'number')
    throw new Error('The "size" argument must be of type number\&.');
  buf = new Buffer(notNumber, encoding);
}
.fi
.PP
.PP
\fRencoding\fP is optional\&.
.PP
Note that the \fRtypeof notNumber\fP before \fRnew Buffer\fP is required (for cases when \fRnotNumber\fP argument is not hard-coded) and \fIis not caused by the deprecation of Buffer constructor\fP — it's exactly \fIwhy\fP the Buffer constructor is deprecated\&. Ecosystem packages lacking this type-check caused numereous security issues — situations when unsanitized user input could end up in the \fRBuffer(arg)\fP create problems ranging from DoS to leaking sensitive information to the attacker from the process memory\&.
.PP
When \fRnotNumber\fP argument is hardcoded (e\&.g\&. literal \fR'abc'\fP or \fR[0,1,2]\fP), the \fRtypeof\fP check can be omitted\&.
.PP
Also note that using TypeScript does not fix this problem for you — when libs written in \fRTypeScript\fP are used from JS, or when user input ends up there — it behaves exactly as pure JS, as all type checks are translation-time only and are not present in the actual JS code which TS compiles to\&.
.SS "Buffer(number)"
For Node\&.js 0\&.10\&.x (and below) support:
.PP
.PP
.nf
var buf;
if (Buffer\&.alloc) {
  buf = Buffer\&.alloc(number);
} else {
  buf = new Buffer(number);
  buf\&.fill(0);
}
.fi
.PP
.PP
Otherwise (Node\&.js ≥ 0\&.12\&.x):
.PP
.PP
.nf
const buf = Buffer\&.alloc ? Buffer\&.alloc(number) : new Buffer(number)\&.fill(0);
.fi
.PP
.SH "Regarding Buffer\&.allocUnsafe"
.PP
Be extra cautious when using \fRBuffer\&.allocUnsafe\fP:
.IP "\(bu" 2
Don't use it if you don't have a good reason to
.IP "  \(bu" 4
e\&.g\&. you probably won't ever see a performance difference for small buffers, in fact, those might be even faster with \fRBuffer\&.alloc()\fP,
.IP "  \(bu" 4
if your code is not in the hot code path — you also probably won't notice a difference,
.IP "  \(bu" 4
keep in mind that zero-filling minimizes the potential risks\&.
.PP

.IP "\(bu" 2
If you use it, make sure that you never return the buffer in a partially-filled state,
.IP "  \(bu" 4
if you are writing to it sequentially — always truncate it to the actuall written length
.PP

.PP
.PP
Errors in handling buffers allocated with \fRBuffer\&.allocUnsafe\fP could result in various issues, ranged from undefined behaviour of your code to sensitive data (user input, passwords, certs) leaking to the remote attacker\&.
.PP
\fINote that the same applies to \fRnew Buffer\fP usage without zero-filling, depending on the Node\&.js version (and lacking type checks also adds DoS to the list of potential problems)\&.\fP
.PP
 
.SH "FAQ"
.PP
 
.SS "What is wrong with the \fRBuffer\fP constructor?"
The \fRBuffer\fP constructor could be used to create a buffer in many different ways:
.PP
.IP "\(bu" 2
\fRnew Buffer(42)\fP creates a \fRBuffer\fP of 42 bytes\&. Before Node\&.js 8, this buffer contained \fIarbitrary memory\fP for performance reasons, which could include anything ranging from program source code to passwords and encryption keys\&.
.IP "\(bu" 2
`new Buffer('abc')\fRcreates a\fPBuffer\fRthat contains the UTF-8-encoded version of the string\fP'abc'\fR\&. A second argument could specify another encoding: For example, \fPnew Buffer(string, 'base64')` could be used to convert a Base64 string into the original sequence of bytes that it represents\&.
.IP "\(bu" 2
There are several other combinations of arguments\&.
.PP
.PP
This meant that, in code like \fRvar buffer = new Buffer(foo);\fP, \fIit is not possible to tell what exactly the contents of the generated buffer are\fP without knowing the type of \fRfoo\fP\&.
.PP
Sometimes, the value of \fRfoo\fP comes from an external source\&. For example, this function could be exposed as a service on a web server, converting a UTF-8 string into its Base64 form:
.PP
.PP
.nf
function stringToBase64(req, res) {
  // The request body should have the format of `{ string: 'foobar' }`
  const rawBytes = new Buffer(req\&.body\&.string)
  const encoded = rawBytes\&.toString('base64')
  res\&.end({ encoded: encoded })
}
.fi
.PP
.PP
Note that this code does \fInot\fP validate the type of \fRreq\&.body\&.string\fP:
.PP
.IP "\(bu" 2
\fRreq\&.body\&.string\fP is expected to be a string\&. If this is the case, all goes well\&.
.IP "\(bu" 2
\fRreq\&.body\&.string\fP is controlled by the client that sends the request\&.
.IP "\(bu" 2
If \fRreq\&.body\&.string\fP is the \fInumber\fP \fR50\fP, the \fRrawBytes\fP would be 50 bytes:
.IP "  \(bu" 4
Before Node\&.js 8, the content would be uninitialized
.IP "  \(bu" 4
After Node\&.js 8, the content would be \fR50\fP bytes with the value \fR0\fP
.PP

.PP
.PP
Because of the missing type check, an attacker could intentionally send a number as part of the request\&. Using this, they can either:
.PP
.IP "\(bu" 2
Read uninitialized memory\&. This \fBwill\fP leak passwords, encryption keys and other kinds of sensitive information\&. (Information leak)
.IP "\(bu" 2
Force the program to allocate a large amount of memory\&. For example, when specifying \fR500000000\fP as the input value, each request will allocate 500MB of memory\&. This can be used to either exhaust the memory available of a program completely and make it crash, or slow it down significantly\&. (Denial of Service)
.PP
.PP
Both of these scenarios are considered serious security issues in a real-world web server context\&.
.PP
when using \fRBuffer\&.from(req\&.body\&.string)\fP instead, passing a number will always throw an exception instead, giving a controlled behaviour that can always be handled by the program\&.
.PP
 
.SS "The \fRBuffer()\fP constructor has been deprecated for a while\&. Is this really an issue?"
Surveys of code in the \fRnpm\fP ecosystem have shown that the \fRBuffer()\fP constructor is still widely used\&. This includes new code, and overall usage of such code has actually been \fIincreasing\fP\&. 
