.TH "md_backend_2node__modules_2finalhandler_2_s_e_c_u_r_i_t_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2finalhandler_2_s_e_c_u_r_i_t_y \- Security Policies and Procedures 
.PP
 
.SH "Reporting a Bug"
.PP
The \fRfinalhandler\fP team and community take all security bugs seriously\&. Thank you for improving the security of Express\&. We appreciate your efforts and responsible disclosure and will make every effort to acknowledge your contributions\&.
.PP
Report security bugs by emailing the current owner(s) of \fRfinalhandler\fP\&. This information can be found in the npm registry using the command \fRnpm owner ls finalhandler\fP\&. If unsure or unable to get the information from the above, open an issue in the \fRproject issue tracker\fP asking for the current contact information\&.
.PP
To ensure the timely response to your report, please ensure that the entirety of the report is contained within the email body and not solely behind a web link or an attachment\&.
.PP
At least one owner will acknowledge your email within 48 hours, and will send a more detailed response within 48 hours indicating the next steps in handling your report\&. After the initial reply to your report, the owners will endeavor to keep you informed of the progress towards a fix and full announcement, and may ask for additional information or guidance\&. 
