.TH "md_backend_2node__modules_2deep-extend_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2deep-extend_2_r_e_a_d_m_e \- Deep Extend 
.PP
Recursive object extending\&.
.PP
\fR\fP.PP
\fR\fP.SH "Install"
.PP
.PP
.nf
$ npm install deep\-extend
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
var deepExtend = require('deep\-extend');
var obj1 = {
  a: 1,
  b: 2,
  d: {
    a: 1,
    b: [],
    c: { test1: 123, test2: 321 }
  },
  f: 5,
  g: 123,
  i: 321,
  j: [1, 2]
};
var obj2 = {
  b: 3,
  c: 5,
  d: {
    b: { first: 'one', second: 'two' },
    c: { test2: 222 }
  },
  e: { one: 1, two: 2 },
  f: [],
  g: (void 0),
  h: /abc/g,
  i: null,
  j: [3, 4]
};

deepExtend(obj1, obj2);

console\&.log(obj1);
/*
{ a: 1,
  b: 3,
  d:
   { a: 1,
     b: { first: 'one', second: 'two' },
     c: { test1: 123, test2: 222 } },
  f: [],
  g: undefined,
  c: 5,
  e: { one: 1, two: 2 },
  h: /abc/g,
  i: null,
  j: [3, 4] }
*/
.fi
.PP
.SH "Unit testing"
.PP
.PP
.nf
$ npm test
.fi
.PP
.SH "Changelog"
.PP
\fBCHANGELOG\&.md\fP
.SH "Any issues?"
.PP
Please, report about issues \fRhere\fP\&.
.SH "License"
.PP
\fRMIT\fP 
