.TH "md_backend_2node__modules_2object-inspect_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2object-inspect_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.13\&.1\fP - 2023-10-19"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] in IE 8, global can !== window despite them being prototypes of each other \fR\fR30d0859\fP\fP
.PP
.SH "\fRv1\&.13\&.0\fP - 2023-10-14"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add special handling for the global object \fR\fR431bab2\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fRfd4f619\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRmock-property\fP, \fRtape\fP \fR\fRb453f6c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRerror-cause\fP \fR\fRe8ffc57\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR054b8b9\fP\fP
.IP "\(bu" 2
[Dev Deps] temporarily remove \fRaud\fP due to breaking change in transitive deps \fR\fR2476845\fP\fP
.IP "\(bu" 2
[Dev Deps] pin \fRglob\fP, since v10\&.3\&.8+ requires a broken \fRjackspeak\fP \fR\fR383fa5e\fP\fP
.IP "\(bu" 2
[Dev Deps] pin \fRjackspeak\fP since 2\&.1\&.2+ depends on npm aliases, which kill the install process in npm < 6 \fR\fR68c244c\fP\fP
.PP
.SH "\fRv1\&.12\&.3\fP - 2023-01-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] in eg FF 24, collections lack forEach \fR\fR75fc226\fP\fP
.IP "\(bu" 2
[actions] update rebase action to use reusable workflow \fR\fR250a277\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRes-value-fixtures\fP, \fRtape\fP \fR\fR66a19b3\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRerror-cause\fP \fR\fRc43d332\fP\fP
.IP "\(bu" 2
[Tests] add \fR@pkgjs/support\fP to \fRpostlint\fP \fR\fRe2618d2\fP\fP
.PP
.SH "\fRv1\&.12\&.2\fP - 2022-05-26"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] use \fRutil\&.inspect\fP for a custom inspection symbol method \fR\fRe243bf2\fP\fP
.IP "\(bu" 2
[meta] add support info \fR\fRca20ba3\fP\fP
.IP "\(bu" 2
[Fix] ignore \fRcause\fP in node v16\&.9 and v16\&.10 where it has a bug \fR\fR86aa553\fP\fP
.PP
.SH "\fRv1\&.12\&.1\fP - 2022-05-21"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] use \fRmock-property\fP \fR\fR4ec8893\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fR07f868c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRtape\fP \fR\fRb05244b\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRerror-cause\fP, \fRes-value-fixtures\fP, \fRfunctions-have-names\fP, \fRtape\fP \fR\fRd037398\fP\fP
.IP "\(bu" 2
[Fix] properly handle callable regexes in older engines \fR\fR848fe48\fP\fP
.PP
.SH "\fRv1\&.12\&.0\fP - 2021-12-18"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRnumericSeparator\fP boolean option \fR\fR2d2d537\fP\fP
.IP "\(bu" 2
[Robustness] cache more prototype methods \fR\fR191533d\fP\fP
.IP "\(bu" 2
[New] ensure an Error’s \fRcause\fP is displayed \fR\fR53bc2ce\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fRbc164b6\fP\fP
.IP "\(bu" 2
[Robustness] cache \fRRegExp\&.prototype\&.test\fP \fR\fRa314ab8\fP\fP
.IP "\(bu" 2
[meta] fix auto-changelog settings \fR\fR5ed0983\fP\fP
.PP
.SH "\fRv1\&.11\&.1\fP - 2021-12-05"
.PP
.SS "Commits"
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR7dbdd22\fP\fP
.IP "\(bu" 2
[actions] reuse common workflows \fR\fRc8823bc\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRsafe-publish-latest\fP, \fRtape\fP \fR\fR7532b12\fP\fP
.IP "\(bu" 2
[Refactor] use \fRhas-tostringtag\fP to behave correctly in the presence of symbol shams \fR\fR94abb5d\fP\fP
.IP "\(bu" 2
[actions] update codecov uploader \fR\fR5ed5102\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fRtape\fP \fR\fR37b2ad2\fP\fP
.IP "\(bu" 2
[meta] add \fRsideEffects\fP flag \fR\fRd341f90\fP\fP
.PP
.SH "\fRv1\&.11\&.0\fP - 2021-07-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] \fRcustomInspect\fP: add \fRsymbol\fP option, to mimic modern util\&.inspect behavior \fR\fRe973a6e\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP \fR\fR05f1cb3\fP\fP
.PP
.SH "\fRv1\&.10\&.3\fP - 2021-05-07"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] handle core-js Symbol shams \fR\fR4acfc2c\fP\fP
.IP "\(bu" 2
[readme] update badges \fR\fR95c323a\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP \fR\fRcb38f48\fP\fP
.PP
.SH "\fRv1\&.10\&.2\fP - 2021-04-17"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] use a robust check for a boxed Symbol \fR\fR87f12d6\fP\fP
.PP
.SH "\fRv1\&.10\&.1\fP - 2021-04-17"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] use a robust check for a boxed bigint \fR\fRd5ca829\fP\fP
.PP
.SH "\fRv1\&.10\&.0\fP - 2021-04-17"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] increase coverage \fR\fRd8abb8a\fP\fP
.IP "\(bu" 2
[actions] use \fRnode/install\fP instead of \fRnode/run\fP; use \fRcodecov\fP action \fR\fR4bfec2e\fP\fP
.IP "\(bu" 2
[New] respect \fRSymbol\&.toStringTag\fP on objects \fR\fR799b58f\fP\fP
.IP "\(bu" 2
[Fix] do not allow Symbol\&.toStringTag to masquerade as builtins \fR\fRd6c5b37\fP\fP
.IP "\(bu" 2
[New] add \fRWeakRef\fP support \fR\fRb6d898e\fP\fP
.IP "\(bu" 2
[meta] do not publish github action workflow files \fR\fR918cdfc\fP\fP
.IP "\(bu" 2
[meta] create \fRFUNDING\&.yml\fP \fR\fR0bb5fc5\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR22c8dc0\fP\fP
.IP "\(bu" 2
[meta] use \fRprepublishOnly\fP script for npm 7+ \fR\fRe52ee09\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP \fR\fR7c4e6fd\fP\fP
.PP
.SH "\fRv1\&.9\&.0\fP - 2020-11-30"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate tests to Github Actions \fR\fRd262251\fP\fP
.IP "\(bu" 2
[New] add enumerable own Symbols to plain object output \fR\fRee60c03\fP\fP
.IP "\(bu" 2
[Tests] add passing tests \fR\fR01ac3e4\fP\fP
.IP "\(bu" 2
[actions] add 'Require Allow Edits' action \fR\fRc2d7746\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRcore-js\fP \fR\fR70058de\fP\fP
.IP "\(bu" 2
[Fix] hex characters in strings should be uppercased, to match node \fRassert\fP \fR\fR6ab8faa\fP\fP
.IP "\(bu" 2
[Tests] run \fRnyc\fP on all tests \fR\fR4c47372\fP\fP
.IP "\(bu" 2
[Tests] node 0\&.8 has an unpredictable property order; fix \fRgroups\fP test by removing property \fR\fRf192069\fP\fP
.IP "\(bu" 2
[New] add enumerable properties to Function inspect result, per node’s \fRassert\fP \fR\fRfd38e1b\fP\fP
.IP "\(bu" 2
[Tests] fix tests for node < 10, due to regex match \fRgroups\fP \fR\fR2ac6462\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fR44b59e2\fP\fP
.IP "\(bu" 2
[Robustness] cache \fRSymbol\&.prototype\&.toString\fP \fR\fRf3c2074\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP \fR\fR9411294\fP\fP
.IP "\(bu" 2
[meta] \fRrequire-allow-edits\fP no longer requires an explicit github token \fR\fR36c0220\fP\fP
.IP "\(bu" 2
[actions] update rebase checkout action to v2 \fR\fR55a39a6\fP\fP
.IP "\(bu" 2
[actions] switch Automatic Rebase workflow to \fRpull_request_target\fP event \fR\fRf59fd3c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP \fR\fRa492bec\fP\fP
.PP
.SH "\fRv1\&.8\&.0\fP - 2020-06-18"
.PP
.SS "Fixed"
.IP "\(bu" 2
[New] add \fRindent\fP option \fR\fR#27\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] add codecov \fR\fR4324cbb\fP\fP
.IP "\(bu" 2
[New] add \fRmaxStringLength\fP option \fR\fRb3995cb\fP\fP
.IP "\(bu" 2
[New] add \fRcustomInspect\fP option, to disable custom inspect methods \fR\fR28b9179\fP\fP
.IP "\(bu" 2
[Tests] add Date and RegExp tests \fR\fR3b28eca\fP\fP
.IP "\(bu" 2
[actions] add automatic rebasing / merge commit blocking \fR\fR0d9c6c0\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRcore-js\fP, \fRtape\fP; add \fRaud\fP \fR\fR7c204f2\fP\fP
.IP "\(bu" 2
[readme] fix repo URLs, remove testling \fR\fR34ca9a0\fP\fP
.IP "\(bu" 2
[Fix] when truncating a deep array, note it as \fR[Array]\fP instead of just \fR[Object]\fP \fR\fRf74c82d\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRtape\fP \fR\fR1a8a5ea\fP\fP
.IP "\(bu" 2
[Fix] do not be fooled by a function’s own \fRtoString\fP method \fR\fR7cb5c65\fP\fP
.IP "\(bu" 2
[patch] indicate explicitly that anon functions are anonymous, to match node \fR\fR81ebdd4\fP\fP
.IP "\(bu" 2
[Dev Deps] loosen the \fRcore-js\fP dep \fR\fRe7472e8\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR699827e\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP \fR\fRc5d2868\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP \fR\fR9199501\fP\fP
.PP
.SH "\fRv1\&.7\&.0\fP - 2019-11-10"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] use shared travis-ci configs \fR\fR19899ed\fP\fP
.IP "\(bu" 2
[Tests] add linting \fR\fRa00f057\fP\fP
.IP "\(bu" 2
[Tests] lint last file \fR\fR2698047\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv12\&.7\fP, \fRv11\&.15\fP, \fRv10\&.16\fP, \fRv8\&.16\fP, \fRv6\&.17\fP \fR\fR589e87a\fP\fP
.IP "\(bu" 2
[New] add support for \fRWeakMap\fP and \fRWeakSet\fP \fR\fR3ddb3e4\fP\fP
.IP "\(bu" 2
[meta] clean up license so github can detect it properly \fR\fR27527bb\fP\fP
.IP "\(bu" 2
[Tests] cover \fRutil\&.inspect\&.custom\fP \fR\fR36d47b9\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRcore-js\fP, \fRtape\fP \fR\fRb614eaa\fP\fP
.IP "\(bu" 2
[Tests] fix coverage thresholds \fR\fR7b7b176\fP\fP
.IP "\(bu" 2
[Tests] bigint tests now can run on unflagged node \fR\fR063af31\fP\fP
.IP "\(bu" 2
[Refactor] add early bailout to \fRisMap\fP and \fRisSet\fP checks \fR\fRfc51047\fP\fP
.IP "\(bu" 2
[meta] add \fRfunding\fP field \fR\fR7f9953a\fP\fP
.IP "\(bu" 2
[Tests] Fix invalid strict-mode syntax with hexadecimal \fR\fRa8b5425\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP \fR\fR98df157\fP\fP
.IP "\(bu" 2
add copyright to LICENSE \fR\fRbb69fd0\fP\fP
.IP "\(bu" 2
[Tests] use \fRnpx aud\fP in \fRposttest\fP \fR\fR4838353\fP\fP
.IP "\(bu" 2
[Tests] move \fR0\&.6\fP to allowed failures, because it won‘t build on travis \fR\fR1bff32a\fP\fP
.PP
.SH "\fRv1\&.6\&.0\fP - 2018-05-02"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add support for boxed BigInt primitives \fR\fR356c66a\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv10\&.0\fP, \fRv9\&.11\fP, \fRv8\&.11\fP, \fRv6\&.14\fP, \fRv4\&.9\fP \fR\fRc77b65b\fP\fP
.IP "\(bu" 2
[New] Add support for upcoming \fRBigInt\fP \fR\fR1ac548e\fP\fP
.IP "\(bu" 2
[Tests] run bigint tests in CI with --harmony-bigint flag \fR\fRd31b738\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRcore-js\fP, \fRtape\fP \fR\fRff9eff6\fP\fP
.IP "\(bu" 2
[Docs] fix example to use \fRsafer-buffer\fP \fR\fR48cae12\fP\fP
.PP
.SH "\fRv1\&.5\&.0\fP - 2017-12-25"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRquoteStyle\fP option \fR\fRf5a72d2\fP\fP
.IP "\(bu" 2
[Tests] add more test coverage \fR\fR30ebe4e\fP\fP
.IP "\(bu" 2
[Tests] require 0\&.6 to pass \fR\fR99a008c\fP\fP
.PP
.SH "\fRv1\&.4\&.1\fP - 2017-12-19"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv9\&.3\fP, \fRv8\&.9\fP, \fRv6\&.12\fP \fR\fR6674476\fP\fP
.IP "\(bu" 2
[Fix] \fRinspect(Object(-0))\fP should be “Object(-0)”, not “Object(0)” \fR\fRd0a031f\fP\fP
.PP
.SH "\fRv1\&.4\&.0\fP - 2017-10-24"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] add \fRnpm run coverage\fP \fR\fR3b48fb2\fP\fP
.IP "\(bu" 2
[Tests] remove commented-out osx builds \fR\fR71e24db\fP\fP
.IP "\(bu" 2
[New] add support for \fRutil\&.inspect\&.custom\fP, in node only\&. \fR\fR20cca77\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv8\&.6\fP; use \fRnvm install-latest-npm\fP to ensure new npm doesn’t break old node \fR\fR252952d\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv8\&.8\fP \fR\fR4aa868d\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRcore-js\fP, \fRtape\fP \fR\fR59483d1\fP\fP
.PP
.SH "\fRv1\&.3\&.0\fP - 2017-07-31"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] Map/Set: work around core-js bug < v2\&.5\&.0 \fR\fR#9\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add support for arrays with additional object keys \fR\fR0d19937\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv8\&.2\fP, \fRv7\&.10\fP, \fRv6\&.11\fP; fix new npm breaking on older nodes \fR\fRe24784a\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRc6faebc\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR7345a0a\fP\fP
.PP
.SH "\fRv1\&.2\&.2\fP - 2017-03-24"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv7\&.7\fP, \fRv6\&.10\fP, \fRv4\&.8\fP; improve test matrix \fR\fRa2ddc15\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv7\&.0\fP, \fRv6\&.9\fP, \fRv5\&.12\fP, \fRv4\&.6\fP, \fRio\&.js\fP \fRv3\&.3\fP; improve test matrix \fR\fRa48949f\fP\fP
.IP "\(bu" 2
[Performance] check for primitive types as early as possible\&. \fR\fR3b8092a\fP\fP
.IP "\(bu" 2
[Refactor] remove unneeded \fRelse\fPs\&. \fR\fR7255034\fP\fP
.IP "\(bu" 2
[Refactor] avoid recreating \fRlowbyte\fP function every time\&. \fR\fR81edd34\fP\fP
.IP "\(bu" 2
[Fix] differentiate -0 from 0 \fR\fR521d345\fP\fP
.IP "\(bu" 2
[Refactor] move object key gathering into separate function \fR\fRaca6265\fP\fP
.IP "\(bu" 2
[Refactor] consolidate wrapping logic for boxed primitives into a function\&. \fR\fR4e440cd\fP\fP
.IP "\(bu" 2
[Robustness] use \fRtypeof\fP instead of comparing to literal \fRundefined\fP \fR\fR5ca6f60\fP\fP
.IP "\(bu" 2
[Refactor] consolidate Map/Set notations\&. \fR\fR4e576e5\fP\fP
.IP "\(bu" 2
[Tests] ensure that this function remains anonymous, despite ES6 name inference\&. \fR\fR7540ae5\fP\fP
.IP "\(bu" 2
[Refactor] explicitly coerce Error objects to strings\&. \fR\fR7f4ca84\fP\fP
.IP "\(bu" 2
[Refactor] split up \fRvar\fP declarations for debuggability \fR\fR6f2c11e\fP\fP
.IP "\(bu" 2
[Robustness] cache \fRObject\&.prototype\&.toString\fP \fR\fRdf44a20\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR3ec714e\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fRbeb72d9\fP\fP
.PP
.SH "\fRv1\&.2\&.1\fP - 2016-04-09"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] fix Boolean \fRfalse\fP object inspection\&. \fR\fR#7\fP\fP
.PP
.SH "\fRv1\&.2\&.0\fP - 2016-04-09"
.PP
.SS "Fixed"
.IP "\(bu" 2
[New] add support for inspecting String/Number/Boolean objects\&. \fR\fR#6\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR742caa2\fP\fP
.PP
.SH "\fRv1\&.1\&.0\fP - 2015-12-14"
.PP
.SS "Merged"
.IP "\(bu" 2
[New] add ES6 Map/Set support\&. \fR\fR#4\fP\fP
.PP
.SS "Fixed"
.IP "\(bu" 2
[New] add ES6 Map/Set support\&. \fR\fR#3\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
Update \fRtravis\&.yml\fP to test on bunches of \fRiojs\fP and \fRnode\fP versions\&. \fR\fR4c1fd65\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP \fR\fR88a907e\fP\fP
.PP
.SH "\fR1\&.0\&.2\fP - 2015-08-07"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] Cache \fRObject\&.prototype\&.hasOwnProperty\fP in case it's deleted later\&. \fR\fR1d0075d\fP\fP
.IP "\(bu" 2
[Dev Deps] Update \fRtape\fP \fR\fRca8d5d7\fP\fP
.IP "\(bu" 2
gitignore node_modules since this is a reusable modules\&. \fR\fRed41407\fP\fP
.PP
.SH "\fR1\&.0\&.1\fP - 2015-07-19"
.PP
.SS "Commits"
.IP "\(bu" 2
Make \fRinspect\fP work with symbol primitives and objects, including in node 0\&.11 and 0\&.12\&. \fR\fRddf1b94\fP\fP
.IP "\(bu" 2
bump tape \fR\fR103d674\fP\fP
.IP "\(bu" 2
use newer travis config \fR\fRd497276\fP\fP
.PP
.SH "\fR1\&.0\&.0\fP - 2014-08-05"
.PP
.SS "Commits"
.IP "\(bu" 2
error inspect works properly \fR\fR260a22d\fP\fP
.IP "\(bu" 2
seen coverage \fR\fR57269e8\fP\fP
.IP "\(bu" 2
htmlelement instance coverage \fR\fR397ffe1\fP\fP
.IP "\(bu" 2
more element coverage \fR\fR6905cc2\fP\fP
.IP "\(bu" 2
failing test for type errors \fR\fR385b615\fP\fP
.IP "\(bu" 2
fn name coverage \fR\fRedc906d\fP\fP
.IP "\(bu" 2
server-side element test \fR\fR362d1d3\fP\fP
.IP "\(bu" 2
custom inspect fn \fR\fRe89b0f6\fP\fP
.IP "\(bu" 2
fixed browser test \fR\fRb530882\fP\fP
.IP "\(bu" 2
depth test, matches node \fR\fR1cfd9e0\fP\fP
.IP "\(bu" 2
exercise hasOwnProperty path \fR\fR8d753fb\fP\fP
.IP "\(bu" 2
more cases covered for errors \fR\fRc5c46a5\fP\fP
.IP "\(bu" 2
\\W obj key test case \fR\fRb0eceee\fP\fP
.IP "\(bu" 2
coverage for explicit depth param \fR\fRe12b91c\fP\fP
.PP
.SH "\fR0\&.4\&.0\fP - 2014-03-21"
.PP
.SS "Commits"
.IP "\(bu" 2
passing lowbyte interpolation test \fR\fRb847511\fP\fP
.IP "\(bu" 2
lowbyte test \fR\fR4a2b0e1\fP\fP
.PP
.SH "\fR0\&.3\&.1\fP - 2014-03-04"
.PP
.SS "Commits"
.IP "\(bu" 2
sort keys \fR\fRa07b19c\fP\fP
.PP
.SH "\fR0\&.3\&.0\fP - 2014-03-04"
.PP
.SS "Commits"
.IP "\(bu" 2
[] and {} instead of [ ] and { } \fR\fR654c44b\fP\fP
.PP
.SH "\fR0\&.2\&.0\fP - 2014-03-04"
.PP
.SS "Commits"
.IP "\(bu" 2
failing holes test \fR\fR99cdfad\fP\fP
.IP "\(bu" 2
regex already work \fR\fRe324033\fP\fP
.IP "\(bu" 2
failing undef/null test \fR\fR1f88a00\fP\fP
.IP "\(bu" 2
holes in the all example \fR\fR7d345f3\fP\fP
.IP "\(bu" 2
check for \&.inspect(), fixes Buffer use-case \fR\fRc3f7546\fP\fP
.IP "\(bu" 2
fixes for holes \fR\fRce25f73\fP\fP
.IP "\(bu" 2
weird null behavior \fR\fR405c1ea\fP\fP
.IP "\(bu" 2
tape is actually a devDependency, upgrade \fR\fR703b0ce\fP\fP
.IP "\(bu" 2
put date in the example \fR\fRa342219\fP\fP
.IP "\(bu" 2
passing the null test \fR\fR4ab737e\fP\fP
.PP
.SH "\fR0\&.1\&.3\fP - 2013-07-26"
.PP
.SS "Commits"
.IP "\(bu" 2
special isElement() check \fR\fR882768a\fP\fP
.IP "\(bu" 2
oh right old IEs don't have indexOf either \fR\fR36d1275\fP\fP
.PP
.SH "\fR0\&.1\&.1\fP - 2013-07-26"
.PP
.SS "Commits"
.IP "\(bu" 2
tests! \fR\fR4422fd9\fP\fP
.IP "\(bu" 2
fix for ie<9, doesn't have hasOwnProperty \fR\fR6b7d611\fP\fP
.IP "\(bu" 2
fix for all IEs: no f\&.name \fR\fR4e0c2f6\fP\fP
.IP "\(bu" 2
badges \fR\fR5ed0d88\fP\fP
.PP
.SH "\fR0\&.1\&.0\fP - 2013-07-26"
.PP
.SS "Commits"
.IP "\(bu" 2
[Function] for functions \fR\fRad5c485\fP\fP
.PP
.SH "0\&.0\&.0 - 2013-07-26"
.PP
.SS "Commits"
.IP "\(bu" 2
working browser example \fR\fR34be6b6\fP\fP
.IP "\(bu" 2
package\&.json etc \fR\fRcad51f2\fP\fP
.IP "\(bu" 2
docs complete \fR\fRb80cce2\fP\fP
.IP "\(bu" 2
circular example \fR\fR4b4a7b9\fP\fP
.IP "\(bu" 2
string rep \fR\fR7afb479\fP\fP 
.PP

