.TH "md_backend_2node__modules_2encoding_2node__modules_2iconv-lite_2_changelog" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2encoding_2node__modules_2iconv-lite_2_changelog \- 0\&.6\&.3 / 2024-05-23 
.PP

.IP "\(bu" 2
Fix HKSCS encoding to prefer Big5 codes if both Big5 and HKSCS codes are possible (#264)
.PP
.SH "0\&.6\&.2 / 2020-07-08"
.PP
.IP "\(bu" 2
Support Uint8Array-s decoding without conversion to Buffers, plus fix an edge case\&.
.PP
.SH "0\&.6\&.1 / 2020-06-28"
.PP
.IP "\(bu" 2
Support Uint8Array-s directly when decoding (#246, by @gyzerok)
.IP "\(bu" 2
Unify package\&.json version ranges to be strictly semver-compatible (#241)
.IP "\(bu" 2
Fix minor issue in UTF-32 decoder's endianness detection code\&.
.PP
.SH "0\&.6\&.0 / 2020-06-08"
.PP
.IP "\(bu" 2
Updated 'gb18030' encoding to :2005 edition (see https://github.com/whatwg/encoding/issues/22)\&.
.IP "\(bu" 2
Removed \fRiconv\&.extendNodeEncodings()\fP mechanism\&. It was deprecated 5 years ago and didn't work in recent Node versions\&.
.IP "\(bu" 2
Reworked Streaming API behavior in browser environments to fix #204\&. Streaming API will be excluded by default in browser packs, saving ~100Kb bundle size, unless enabled explicitly using `iconv\&.enableStreamingAPI(require('stream'))`\&.
.IP "\(bu" 2
Updates to development environment & tests:
.IP "  \(bu" 4
Added \&./test/webpack private package to test complex new use cases that need custom environment\&. It's tested as a separate job in Travis CI\&.
.IP "  \(bu" 4
Updated generation code for the new EUC-KR index file format from Encoding Standard\&.
.IP "  \(bu" 4
Removed Buffer() constructor in tests (#197 by @gabrielschulhof)\&.
.PP

.PP
.SH "0\&.5\&.2 / 2020-06-08"
.PP
.IP "\(bu" 2
Added \fRiconv\&.getEncoder()\fP and \fRiconv\&.getDecoder()\fP methods to typescript definitions (#229)\&.
.IP "\(bu" 2
Fixed semver version to 6\&.1\&.2 to support Node 8\&.x (by @tanandara)\&.
.IP "\(bu" 2
Capped iconv version to 2\&.x as 3\&.x has dropped support for older Node versions\&.
.IP "\(bu" 2
Switched from instanbul to c8 for code coverage\&.
.PP
.SH "0\&.5\&.1 / 2020-01-18"
.PP
.IP "\(bu" 2
Added cp720 encoding (#221, by @kr-deps)
.IP "\(bu" 2
(minor) Changed Changelog\&.md formatting to use h2\&.
.PP
.SH "0\&.5\&.0 / 2019-06-26"
.PP
.IP "\(bu" 2
Added UTF-32 encoding, both little-endian and big-endian variants (UTF-32LE, UTF32-BE)\&. If endianness is not provided for decoding, it's deduced automatically from the stream using a heuristic similar to what we use in UTF-16\&. (great work in #216 by @kshetline)
.IP "\(bu" 2
Several minor updates to README (#217 by @oldj, plus some more)
.IP "\(bu" 2
Added Node versions 10 and 12 to Travis test harness\&.
.PP
.SH "0\&.4\&.24 / 2018-08-22"
.PP
.IP "\(bu" 2
Added MIK encoding (#196, by @Ivan-Kalatchev)
.PP
.SH "0\&.4\&.23 / 2018-05-07"
.PP
.IP "\(bu" 2
Fix deprecation warning in Node v10 due to the last usage of \fRnew Buffer\fP (#185, by @felixbuenemann)
.IP "\(bu" 2
Switched from NodeBuffer to Buffer in typings (#155 by @felixfbecker, #186 by @larssn)
.PP
.SH "0\&.4\&.22 / 2018-05-05"
.PP
.IP "\(bu" 2
Use older semver style for dependencies to be compatible with Node version 0\&.10 (#182, by @dougwilson)
.IP "\(bu" 2
Fix tests to accomodate fixes in Node v10 (#182, by @dougwilson)
.PP
.SH "0\&.4\&.21 / 2018-04-06"
.PP
.IP "\(bu" 2
Fix encoding canonicalization (#156)
.IP "\(bu" 2
Fix the paths in the 'browser' field in package\&.json (#174 by @LMLB)
.IP "\(bu" 2
Removed 'contributors' section in package\&.json - see Git history instead\&.
.PP
.SH "0\&.4\&.20 / 2018-04-06"
.PP
.IP "\(bu" 2
Updated \fRnew Buffer()\fP usages with recommended replacements as it's being deprecated in Node v10 (#176, #178 by @ChALkeR)
.PP
.SH "0\&.4\&.19 / 2017-09-09"
.PP
.IP "\(bu" 2
Fixed iso8859-1 codec regression in handling untranslatable characters (#162, caused by #147)
.IP "\(bu" 2
Re-generated windows1255 codec, because it was updated in iconv project
.IP "\(bu" 2
Fixed grammar in error message when iconv-lite is loaded with encoding other than utf8
.PP
.SH "0\&.4\&.18 / 2017-06-13"
.PP
.IP "\(bu" 2
Fixed CESU-8 regression in Node v8\&.
.PP
.SH "0\&.4\&.17 / 2017-04-22"
.PP
.IP "\(bu" 2
Updated typescript definition file to support Angular 2 AoT mode (#153 by @larssn)
.PP
.SH "0\&.4\&.16 / 2017-04-22"
.PP
.IP "\(bu" 2
Added support for React Native (#150)
.IP "\(bu" 2
Changed iso8859-1 encoding to usine internal 'binary' encoding, as it's the same thing (#147 by @mscdex)
.IP "\(bu" 2
Fixed typo in Readme (#138 by @jiangzhuo)
.IP "\(bu" 2
Fixed build for Node v6\&.10+ by making correct version comparison
.IP "\(bu" 2
Added a warning if iconv-lite is loaded not as utf-8 (see #142)
.PP
.SH "0\&.4\&.15 / 2016-11-21"
.PP
.IP "\(bu" 2
Fixed typescript type definition (#137)
.PP
.SH "0\&.4\&.14 / 2016-11-20"
.PP
.IP "\(bu" 2
Preparation for v1\&.0
.IP "\(bu" 2
Added Node v6 and latest Node versions to Travis CI test rig
.IP "\(bu" 2
Deprecated Node v0\&.8 support
.IP "\(bu" 2
Typescript typings (@larssn)
.IP "\(bu" 2
Fix encoding of Euro character in GB 18030 (inspired by @lygstate)
.IP "\(bu" 2
Add ms prefix to dbcs windows encodings (@rokoroku)
.PP
.SH "0\&.4\&.13 / 2015-10-01"
.PP
.IP "\(bu" 2
Fix silly mistake in deprecation notice\&.
.PP
.SH "0\&.4\&.12 / 2015-09-26"
.PP
.IP "\(bu" 2
Node v4 support:
.IP "  \(bu" 4
Added CESU-8 decoding (#106)
.IP "  \(bu" 4
Added deprecation notice for \fRextendNodeEncodings\fP
.IP "  \(bu" 4
Added Travis tests for Node v4 and io\&.js latest (#105 by @Mithgol)
.PP

.PP
.SH "0\&.4\&.11 / 2015-07-03"
.PP
.IP "\(bu" 2
Added CESU-8 encoding\&.
.PP
.SH "0\&.4\&.10 / 2015-05-26"
.PP
.IP "\(bu" 2
Changed UTF-16 endianness heuristic to take into account any ASCII chars, not just spaces\&. This should minimize the importance of 'default' endianness\&.
.PP
.SH "0\&.4\&.9 / 2015-05-24"
.PP
.IP "\(bu" 2
Streamlined BOM handling: strip BOM by default, add BOM when encoding if addBOM: true\&. Added docs to Readme\&.
.IP "\(bu" 2
UTF16 now uses UTF16-LE by default\&.
.IP "\(bu" 2
Fixed minor issue with big5 encoding\&.
.IP "\(bu" 2
Added io\&.js testing on Travis; updated node-iconv version to test against\&. Now we just skip testing SBCS encodings that node-iconv doesn't support\&.
.IP "\(bu" 2
(internal refactoring) Updated codec interface to use classes\&.
.IP "\(bu" 2
Use strict mode in all files\&.
.PP
.SH "0\&.4\&.8 / 2015-04-14"
.PP
.IP "\(bu" 2
added alias UNICODE-1-1-UTF-7 for UTF-7 encoding (#94)
.PP
.SH "0\&.4\&.7 / 2015-02-05"
.PP
.IP "\(bu" 2
stop official support of Node\&.js v0\&.8\&. Should still work, but no guarantees\&. reason: Packages needed for testing are hard to get on Travis CI\&.
.IP "\(bu" 2
work in environment where Object\&.prototype is monkey patched with enumerable props (#89)\&.
.PP
.SH "0\&.4\&.6 / 2015-01-12"
.PP
.IP "\(bu" 2
fix rare aliases of single-byte encodings (thanks @mscdex)
.IP "\(bu" 2
double the timeout for dbcs tests to make them less flaky on travis
.PP
.SH "0\&.4\&.5 / 2014-11-20"
.PP
.IP "\(bu" 2
fix windows-31j and x-sjis encoding support (@nleush)
.IP "\(bu" 2
minor fix: undefined variable reference when internal error happens
.PP
.SH "0\&.4\&.4 / 2014-07-16"
.PP
.IP "\(bu" 2
added encodings UTF-7 (RFC2152) and UTF-7-IMAP (RFC3501 Section 5\&.1\&.3)
.IP "\(bu" 2
fixed streaming base64 encoding
.PP
.SH "0\&.4\&.3 / 2014-06-14"
.PP
.IP "\(bu" 2
added encodings UTF-16BE and UTF-16 with BOM
.PP
.SH "0\&.4\&.2 / 2014-06-12"
.PP
.IP "\(bu" 2
don't throw exception if \fRextendNodeEncodings()\fP is called more than once
.PP
.SH "0\&.4\&.1 / 2014-06-11"
.PP
.IP "\(bu" 2
codepage 808 added
.PP
.SH "0\&.4\&.0 / 2014-06-10"
.PP
.IP "\(bu" 2
code is rewritten from scratch
.IP "\(bu" 2
all widespread encodings are supported
.IP "\(bu" 2
streaming interface added
.IP "\(bu" 2
browserify compatibility added
.IP "\(bu" 2
(optional) extend core primitive encodings to make usage even simpler
.IP "\(bu" 2
moved from vows to mocha as the testing framework 
.PP

