.TH "md_backend_2node__modules_2github-from-package_2readme" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2github-from-package_2readme \- github-from-package 
.PP
 return the github url from a package\&.json file
.PP
\fR\fP.SH "example"
.PP
For the \fR\&./package\&.json\fP file:
.PP
.PP
.nf
 json
{
  "name": "beep\-boop",
  "version": "1\&.2\&.3",
  "repository" : {
    "type" : "git",
    "url": "git@github\&.com:substack/beep\-boop\&.git"
  }
}
.fi
.PP
.PP
.PP
.nf
 js
var github = require('github\-from\-package');
var url = github(require('\&./package\&.json'));
console\&.log(url);
.fi
.PP
.PP
.PP
.nf
https://github\&.com/substack/beep\-boop
.fi
.PP
.SH "methods"
.PP
.PP
.nf
 js
var github = require('github\-from\-package')
.fi
.PP
.SS "var url = github(pkg)"
Return the most likely github url from the package\&.json contents \fRpkg\fP\&. If no github url can be determined, return \fRundefined\fP\&.
.SH "install"
.PP
With \fRnpm\fP do:
.PP
.PP
.nf
npm install github\-from\-package
.fi
.PP
.SH "license"
.PP
MIT 
