.TH "md_backend_2node__modules_2indent-string_2readme" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2indent-string_2readme \- indent-string \fR\fP 
.PP
 
.PP
.RS 4
Indent each line in a string 
.RE
.PP
.SH "Install"
.PP
.PP
.nf
$ npm install indent\-string
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
const indentString = require('indent\-string');

indentString('Unicorns\\nRainbows', 4);
//=> '    Unicorns\\n    Rainbows'

indentString('Unicorns\\nRainbows', 4, {indent: '♥'});
//=> '♥♥♥♥Unicorns\\n♥♥♥♥Rainbows'
.fi
.PP
.SH "API"
.PP
.SS "indentString(string, [count], [options])"
.SS "string"
Type: \fRstring\fP
.PP
The string to indent\&.
.SS "count"
Type: \fRnumber\fP
.br
 Default: \fR1\fP
.PP
How many times you want \fRoptions\&.indent\fP repeated\&.
.SS "options"
Type: \fRobject\fP
.SS "indent"
Type: \fRstring\fP
.br
 Default: `' '`
.PP
The string to use for the indent\&.
.SS "includeEmptyLines"
Type: \fRboolean\fP
.br
 Default: \fRfalse\fP
.PP
Also indent empty lines\&.
.SH "Related"
.PP
.IP "\(bu" 2
\fRindent-string-cli\fP - CLI for this module
.IP "\(bu" 2
\fRstrip-indent\fP - Strip leading whitespace from every line in a string
.PP
.SH "License"
.PP
MIT © \fRSindre Sorhus\fP 
