.TH "md_backend_2node__modules_2agentkeepalive_2_history" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2agentkeepalive_2_history \- 4\&.5\&.0 / 2023-08-06 
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR1e5e312\fP\fP] - deps: remove debug and depd (#114) (fengmk2 <fengmk2@gmail.com>)
.PP
.SH "4\&.4\&.0 / 2023-08-05"
.PP
\fBfeatures\fP
.IP "\(bu" 2
[\fR\fRc7c1e93\fP\fP] - feat: return socket from createConnection (#113) (Nabeel Bukhari <nabeel.bukhari@hotmail.com>)
.PP
.SH "4\&.3\&.0 / 2023-03-06"
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR6f9852b\fP\fP] - deps: depd@2\&.0\&.0 (#109) (Brian DeHamer <bdehamer@github.com>)
.IP "\(bu" 2
[\fR\fRfd4bd9b\fP\fP] - test: use npm install (#110) (fengmk2 <fengmk2@gmail.com>)
.IP "\(bu" 2
[\fR\fRd52822c\fP\fP] - chore: update contributors (fengmk2 <fengmk2@gmail.com>)
.PP
.SH "4\&.2\&.1 / 2022-02-21"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fR8b13b5c\fP\fP] - fix: explicitly set \fR| undefined\fP in type definitions (#99) (Benoit Lemoine <lemoine.benoit@gmail.com>)
.PP
.SH "4\&.2\&.0 / 2021-12-31"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fRf418c67\fP\fP] - fix: change \fRfreeSocketTimeout\fP default value to 4000 (#102) (fengmk2 <fengmk2@gmail.com>)
.PP
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fRbc2a1ce\fP\fP] - doc(readme): making \fRtimeout\fP's default clear (#100) (Aaron <aaronarinder@gmail.com>)
.PP
.SH "4\&.1\&.4 / 2021-02-05"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fR4d04794\fP\fP] - fix(types): correct \fRHttps\fP constructor argument (#89) (Simen Bekkhus <sbekkhus91@gmail.com>)
.PP
.SH "4\&.1\&.3 / 2020-06-15"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fR4ba9f9c\fP\fP] - fix: compatible with node v12\&.16\&.3 (#91) (killa <killa123@126.com>)
.PP
.SH "4\&.1\&.2 / 2020-04-25"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fRde66b02\fP\fP] - fix: detect http request timeout handler (#88) (fengmk2 <fengmk2@gmail.com>)
.PP
.SH "4\&.1\&.1 / 2020-04-25"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fRbbd20c0\fP\fP] - fix: definition error (#87) (吖猩 <whxaxes@qq.com>)
.PP
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR3b01699\fP\fP] - test: run test on node 12 (#84) (Igor Savin <iselwin@gmail.com>)
.PP
.SH "4\&.1\&.0 / 2019-10-12"
.PP
\fBfeatures\fP
.IP "\(bu" 2
[\fR\fRfe33b80\fP\fP] - feat: Add \fRreusedSocket\fP property on client request (#82) (Weijia Wang <starkwang@126.com>)
.PP
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR77ba744\fP\fP] - docs: fix grammar in readme (#81) (Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>)
.PP
.SH "4\&.0\&.2 / 2019-02-19"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fR56d4a9b\fP\fP] - fix: HttpAgent export = internal (#74) (Andrew Leedham <AndrewLeedham@outlook.com>)
.PP
.SH "4\&.0\&.1 / 2019-02-19"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fRbad1ac0\fP\fP] - fix: HttpsAgent Type Definition (#71) (#72) (Andrew Leedham <AndrewLeedham@outlook.com>)
.IP "\(bu" 2
[\fR\fRf48a4a7\fP\fP] - fix: export interface (#70) (Vinay <vinaybedre@gmail.com>)
.PP
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR9124343\fP\fP] - chore: add agent\&.options\&.keepAlive instead agent\&.keepAlive (fengmk2 <fengmk2@gmail.com>)
.IP "\(bu" 2
[\fR\fRd177d40\fP\fP] - test: add request timeout bigger than agent timeout cases (fengmk2 <fengmk2@gmail.com>)
.PP
.SH "4\&.0\&.0 / 2018-10-23"
.PP
\fBfeatures\fP
.IP "\(bu" 2
[\fR\fR5c9f3bb\fP\fP] - feat: impl the new Agent extend http\&.Agent (fengmk2 <fengmk2@gmail.com>)
.PP
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR498c8f1\fP\fP] - chore: move LICENSE from readme to file (fengmk2 <fengmk2@gmail.com>)
.IP "\(bu" 2
[\fR\fR4f39894\fP\fP] - bugfix: support agent\&.options\&.timeout on https agent (fengmk2 <fengmk2@gmail.com>)
.PP
.SH "3\&.5\&.2 / 2018-10-19"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fR5751fc1\fP\fP] - fix: sockLen being miscalculated when removing sockets (#60) (Ehden Sinai <cixel@users.noreply.github.com>)
.PP
.SH "3\&.5\&.1 / 2018-07-31"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fR495f1ab\fP\fP] - fix: add the lost npm files (#66) (Henry Zhuang <zhuanghengfei@gmail.com>)
.PP
.SH "3\&.5\&.0 / 2018-07-31"
.PP
\fBfeatures\fP
.IP "\(bu" 2
[\fR\fR16f5aea\fP\fP] - feat: add typing define\&. (#65) (Henry Zhuang <zhuanghengfei@gmail.com>)
.PP
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR28fa062\fP\fP] - docs: add 'per host' to description of maxFreeSockets (tony-gutierrez <tony.gutierrez@bluefletch.com>)
.IP "\(bu" 2
[\fR\fR7df2577\fP\fP] - test: run test on node 10 (#63) (fengmk2 <fengmk2@gmail.com>)
.PP
.SH "3\&.4\&.1 / 2018-03-08"
.PP
\fBfixes\fP
.IP "\(bu" 2
[\fR\fR4d3a3b1\fP\fP] - fix: Handle ipv6 addresses in host-header correctly with TLS (#53) (Mattias Holmlund <u376@m1.holmlund.se>)
.PP
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR55a7a5c\fP\fP] - test: stop timer after test end (fengmk2 <fengmk2@gmail.com>)
.PP
.SH "3\&.4\&.0 / 2018-02-27"
.PP
\fBfeatures\fP
.IP "\(bu" 2
[\fR\fRbc7cadb\fP\fP] - feat: use socket custom freeSocketKeepAliveTimeout first (#59) (fengmk2 <fengmk2@gmail.com>)
.PP
.PP
\fBothers\fP
.IP "\(bu" 2
[\fR\fR138eda8\fP\fP] - doc: fix \fRkeepAliveMsecs\fP params description (#55) (Hongcai Deng <admin@dhchouse.com>)
.PP
.SH "3\&.3\&.0 / 2017-06-20"
.PP
.IP "\(bu" 2
feat: add statusChanged getter (#51)
.IP "\(bu" 2
chore: format License
.PP
.SH "3\&.2\&.0 / 2017-06-10"
.PP
.IP "\(bu" 2
feat: add expiring active sockets
.IP "\(bu" 2
test: add node 8 (#49)
.PP
.SH "3\&.1\&.0 / 2017-02-20"
.PP
.IP "\(bu" 2
feat: timeout support humanize ms (#48)
.PP
.SH "3\&.0\&.0 / 2016-12-20"
.PP
.IP "\(bu" 2
fix: emit agent socket close event
.IP "\(bu" 2
test: add remove excess calls to removeSocket
.IP "\(bu" 2
test: use egg-ci
.IP "\(bu" 2
test: refactor test with eslint rules
.IP "\(bu" 2
feat: merge _http_agent\&.js from 7\&.2\&.1
.PP
.SH "2\&.2\&.0 / 2016-06-26"
.PP
.IP "\(bu" 2
feat: Add browser shim (noop) for isomorphic use\&. (#39)
.IP "\(bu" 2
chore: add security check badge
.PP
.SH "2\&.1\&.1 / 2016-04-06"
.PP
.IP "\(bu" 2
https: fix ssl socket leak when keepalive is used
.IP "\(bu" 2
chore: remove circle ci image
.PP
.SH "2\&.1\&.0 / 2016-04-02"
.PP
.IP "\(bu" 2
fix: opened sockets number overflow maxSockets
.PP
.SH "2\&.0\&.5 / 2016-03-16"
.PP
.IP "\(bu" 2
fix: pick _evictSession to httpsAgent
.PP
.SH "2\&.0\&.4 / 2016-03-13"
.PP
.IP "\(bu" 2
test: add Circle ci
.IP "\(bu" 2
test: add appveyor ci build
.IP "\(bu" 2
refactor: make sure only one error listener
.IP "\(bu" 2
chore: use codecov
.IP "\(bu" 2
fix: handle idle socket error
.IP "\(bu" 2
test: run on more node versions
.PP
.SH "2\&.0\&.3 / 2015-08-03"
.PP
.IP "\(bu" 2
fix: add default error handler to avoid Unhandled error event throw
.PP
.SH "2\&.0\&.2 / 2015-04-25"
.PP
.IP "\(bu" 2
fix: remove socket from freeSockets on 'timeout' (@pmalouin)
.PP
.SH "2\&.0\&.1 / 2015-04-19"
.PP
.IP "\(bu" 2
fix: add timeoutSocketCount to getCurrentStatus()
.IP "\(bu" 2
feat(getCurrentStatus): add getCurrentStatus
.PP
.SH "2\&.0\&.0 / 2015-04-01"
.PP
.IP "\(bu" 2
fix: socket\&.destroyed always be undefined on 0\&.10\&.x
.IP "\(bu" 2
Make it compatible with node v0\&.10\&.x (@lattmann)
.PP
.SH "1\&.2\&.1 / 2015-03-23"
.PP
.IP "\(bu" 2
patch from iojs: don't overwrite servername option
.IP "\(bu" 2
patch commits from joyent/node
.IP "\(bu" 2
add max sockets test case
.IP "\(bu" 2
add nagle algorithm delayed link
.PP
.SH "1\&.2\&.0 / 2014-09-02"
.PP
.IP "\(bu" 2
allow set keepAliveTimeout = 0
.IP "\(bu" 2
support timeout on working socket\&. fixed #6
.PP
.SH "1\&.1\&.0 / 2014-08-28"
.PP
.IP "\(bu" 2
add some socket counter for deep monitor
.PP
.SH "1\&.0\&.0 / 2014-08-13"
.PP
.IP "\(bu" 2
update _http_agent, only support 0\&.11+, only support node 0\&.11\&.0+
.PP
.SH "0\&.2\&.2 / 2013-11-19"
.PP
.IP "\(bu" 2
support node 0\&.8 and node 0\&.10
.PP
.SH "0\&.2\&.1 / 2013-11-08"
.PP
.IP "\(bu" 2
fix socket does not timeout bug, it will hang on life, must use 0\&.2\&.x on node 0\&.11
.PP
.SH "0\&.2\&.0 / 2013-11-06"
.PP
.IP "\(bu" 2
use keepalive agent on node 0\&.11+ impl
.PP
.SH "0\&.1\&.5 / 2013-06-24"
.PP
.IP "\(bu" 2
support coveralls
.IP "\(bu" 2
add node 0\&.10 test
.IP "\(bu" 2
add 0\&.8\&.22 original https\&.js
.IP "\(bu" 2
add original http\&.js module to diff
.IP "\(bu" 2
update jscover
.IP "\(bu" 2
mv pem to fixtures
.IP "\(bu" 2
add https agent usage 
.PP

