.TH "md_backend_2node__modules_2ieee754_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2ieee754_2_r_e_a_d_m_e \- ieee754 \fR\fP \fR\fP \fR\fP \fR\fP 
.PP

.PP
\fR\fP.SS "Read/write IEEE754 floating point numbers from/to a Buffer or array-like object\&."
.SH "install"
.PP
.PP
.nf
npm install ieee754
.fi
.PP
.SH "methods"
.PP
`var ieee754 = require('ieee754')`
.PP
The \fRieee754\fP object has the following functions:
.PP
.PP
.nf
ieee754\&.read = function (buffer, offset, isLE, mLen, nBytes)
ieee754\&.write = function (buffer, value, offset, isLE, mLen, nBytes)
.fi
.PP
.PP
The arguments mean the following:
.PP
.IP "\(bu" 2
buffer = the buffer
.IP "\(bu" 2
offset = offset into the buffer
.IP "\(bu" 2
value = value to set (only for \fRwrite\fP)
.IP "\(bu" 2
isLe = is little endian?
.IP "\(bu" 2
mLen = mantissa length
.IP "\(bu" 2
nBytes = number of bytes
.PP
.SH "what is ieee754?"
.PP
The IEEE Standard for Floating-Point Arithmetic (IEEE 754) is a technical standard for floating-point computation\&. \fRRead more\fP\&.
.SH "license"
.PP
BSD 3 Clause\&. Copyright (c) 2008, Fair Oaks Labs, Inc\&. 
