.TH "md_backend_2node__modules_2define-data-property_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2define-data-property_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.1\&.4\fP - 2024-02-13"
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRes-define-property\fP \fR\fR90f2f4c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/object\&.getownpropertydescriptors\fP \fR\fRcd929d9\fP\fP
.PP
.SH "\fRv1\&.1\&.3\fP - 2024-02-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[types] hand-write d\&.ts instead of emitting it \fR\fR0cbc988\fP\fP
.IP "\(bu" 2
[meta] simplify \fRexports\fP \fR\fR690781e\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRhasown\fP; clean up DT packages \fR\fR6cdfd1c\fP\fP
.IP "\(bu" 2
[actions] cleanup \fR\fR3142bc6\fP\fP
.IP "\(bu" 2
[meta] add \fRfunding\fP \fR\fR8474423\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP \fR\fR3e9be00\fP\fP
.PP
.SH "\fRv1\&.1\&.2\fP - 2024-02-05"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update @types packages, \fRobject-inspect\fP, \fRtape\fP, \fRtypescript\fP \fR\fRdf41bf8\fP\fP
.IP "\(bu" 2
[Dev Deps] update DT packages, \fRaud\fP, \fRnpmignore\fP, \fRtape\fP, typescript\fR[\fPfab0e4e\fR](https://github.com/ljharb/define-data-property/commit/fab0e4ec709ee02b79f42d6db3ee5f26e0a34b8a)\fP
.IP "\(bu" 2
\fR[Dev Deps] use\fPhasown\fRinstead of\fPhas\fR[\fPaa51ef9\fR](https://github.com/ljharb/define-data-property/commit/aa51ef93f6403d49d9bb72a807bcdb6e418978c0)\fP
.IP "\(bu" 2
\fR[Refactor] use\fPes-errors\fR, so things that only need those do not need\fPget-intrinsic\fR[\fPd89be50\fR](https://github.com/ljharb/define-data-property/commit/d89be50571175888d391238605122679f7e65ffc)\fP
.IP "\(bu" 2
\fR[Deps] update\fPhas-property-descriptors\fR[\fP7af887c\fR](https://github.com/ljharb/define-data-property/commit/7af887c9083b59b195b0079e04815cfed9fcee2b)\fP
.IP "\(bu" 2
\fR[Deps] update\fPget-intrinsic\fR[\fPbb8728e`](https://github.com/ljharb/define-data-property/commit/bb8728ec42cd998505a7157ae24853a560c20646)
.PP
.SH "\fRv1\&.1\&.1\fP - 2023-10-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] fix tests in ES3 engines \fR\fR5c6920e\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/es-value-fixtures\fP, \fR@types/for-each\fP, \fR@types/gopd\fP, \fR@types/has-property-descriptors\fP, \fRtape\fP, \fRtypescript\fP \fR\fR7d82dfc\fP\fP
.IP "\(bu" 2
[Fix] IE 8 has a broken \fRObject\&.defineProperty\fP \fR\fR0672e1a\fP\fP
.IP "\(bu" 2
[meta] emit types on prepack \fR\fR73acb1f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRtape\fP, \fRtypescript\fP \fR\fR9489a77\fP\fP
.PP
.SH "\fRv1\&.1\&.0\fP - 2023-09-13"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRloose\fP arg \fR\fR155235a\fP\fP
.IP "\(bu" 2
[New] allow \fRnull\fP to be passed for the non* args \fR\fR7d2fa5f\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2023-09-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[meta] add TS types \fR\fR43d763c\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@types/tape\fP, \fRtypescript\fP \fR\fRf444985\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP, \fR\fR172bb10\fP\fP
.PP
.SH "v1\&.0\&.0 - 2023-09-12"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme \fR\fR5b43d6b\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR35e577a\fP\fP
.IP "\(bu" 2
npm init \fR\fR82a0a04\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR96df244\fP\fP
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fRa87ff18\fP\fP 
.PP

