.TH "md_backend_2node__modules_2http-errors_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2http-errors_2_h_i_s_t_o_r_y \- 2\&.0\&.0 / 2021-12-17 
.PP

.IP "\(bu" 2
Drop support for Node\&.js 0\&.6
.IP "\(bu" 2
Remove \fRI'mateapot\fP export; use \fRImATeapot\fP instead
.IP "\(bu" 2
Remove support for status being non-first argument
.IP "\(bu" 2
Rename \fRUnorderedCollection\fP constructor to \fRTooEarly\fP
.IP "\(bu" 2
deps: depd@2\&.0\&.0
.IP "  \(bu" 4
Replace internal \fReval\fP usage with \fRFunction\fP constructor
.IP "  \(bu" 4
Use instance methods on \fRprocess\fP to check for listeners
.PP

.IP "\(bu" 2
deps: statuses@2\&.0\&.1
.IP "  \(bu" 4
Fix messaging casing of \fR418 I'm a Teapot\fP
.IP "  \(bu" 4
Remove code 306
.IP "  \(bu" 4
Rename \fR425 Unordered Collection\fP to standard \fR425 Too Early\fP
.PP

.PP
.SH "2021-11-14 / 1\&.8\&.1"
.PP
.IP "\(bu" 2
deps: toidentifier@1\&.0\&.1
.PP
.SH "2020-06-29 / 1\&.8\&.0"
.PP
.IP "\(bu" 2
Add \fRisHttpError\fP export to determine if value is an HTTP error
.IP "\(bu" 2
deps: setprototypeof@1\&.2\&.0
.PP
.SH "2019-06-24 / 1\&.7\&.3"
.PP
.IP "\(bu" 2
deps: inherits@2\&.0\&.4
.PP
.SH "2019-02-18 / 1\&.7\&.2"
.PP
.IP "\(bu" 2
deps: setprototypeof@1\&.1\&.1
.PP
.SH "2018-09-08 / 1\&.7\&.1"
.PP
.IP "\(bu" 2
Fix error creating objects in some environments
.PP
.SH "2018-07-30 / 1\&.7\&.0"
.PP
.IP "\(bu" 2
Set constructor name when possible
.IP "\(bu" 2
Use \fRtoidentifier\fP module to make class names
.IP "\(bu" 2
deps: statuses@'>= 1\&.5\&.0 < 2'
.PP
.SH "2018-03-29 / 1\&.6\&.3"
.PP
.IP "\(bu" 2
deps: depd1\&.1\&.2
.IP "  \(bu" 4
perf: remove argument reassignment
.PP

.IP "\(bu" 2
deps: setprototypeof@1\&.1\&.0
.IP "\(bu" 2
deps: statuses@'>= 1\&.4\&.0 < 2'
.PP
.SH "2017-08-04 / 1\&.6\&.2"
.PP
.IP "\(bu" 2
deps: depd@1\&.1\&.1
.IP "  \(bu" 4
Remove unnecessary \fRBuffer\fP loading
.PP

.PP
.SH "2017-02-20 / 1\&.6\&.1"
.PP
.IP "\(bu" 2
deps: setprototypeof@1\&.0\&.3
.IP "  \(bu" 4
Fix shim for old browsers
.PP

.PP
.SH "2017-02-14 / 1\&.6\&.0"
.PP
.IP "\(bu" 2
Accept custom 4xx and 5xx status codes in factory
.IP "\(bu" 2
Add deprecation message to \fR'I'mateapot'\fP export
.IP "\(bu" 2
Deprecate passing status code as anything except first argument in factory
.IP "\(bu" 2
Deprecate using non-error status codes
.IP "\(bu" 2
Make \fRmessage\fP property enumerable for \fRHttpError\fPs
.PP
.SH "2016-11-16 / 1\&.5\&.1"
.PP
.IP "\(bu" 2
deps: inherits@2\&.0\&.3
.IP "  \(bu" 4
Fix issue loading in browser
.PP

.IP "\(bu" 2
deps: setprototypeof@1\&.0\&.2
.IP "\(bu" 2
deps: statuses@'>= 1\&.3\&.1 < 2'
.PP
.SH "2016-05-18 / 1\&.5\&.0"
.PP
.IP "\(bu" 2
Support new code \fR421 Misdirected Request\fP
.IP "\(bu" 2
Use \fRsetprototypeof\fP module to replace \fR__proto__\fP setting
.IP "\(bu" 2
deps: statuses@'>= 1\&.3\&.0 < 2'
.IP "  \(bu" 4
Add \fR421 Misdirected Request\fP
.IP "  \(bu" 4
perf: enable strict mode
.PP

.IP "\(bu" 2
perf: enable strict mode
.PP
.SH "2016-01-28 / 1\&.4\&.0"
.PP
.IP "\(bu" 2
Add \fRHttpError\fP export, for \fRerr instanceof createError\&.HttpError\fP
.IP "\(bu" 2
deps: inherits@2\&.0\&.1
.IP "\(bu" 2
deps: statuses@'>= 1\&.2\&.1 < 2'
.IP "  \(bu" 4
Fix message for status 451
.IP "  \(bu" 4
Remove incorrect nginx status code
.PP

.PP
.SH "2015-02-02 / 1\&.3\&.1"
.PP
.IP "\(bu" 2
Fix regression where status can be overwritten in \fRcreateError\fP \fRprops\fP
.PP
.SH "2015-02-01 / 1\&.3\&.0"
.PP
.IP "\(bu" 2
Construct errors using defined constructors from \fRcreateError\fP
.IP "\(bu" 2
Fix error names that are not identifiers
.IP "  \(bu" 4
\fRcreateError['I'mateapot']\fP is now \fRcreateError\&.ImATeapot\fP
.PP

.IP "\(bu" 2
Set a meaningful \fRname\fP property on constructed errors
.PP
.SH "2014-12-09 / 1\&.2\&.8"
.PP
.IP "\(bu" 2
Fix stack trace from exported function
.IP "\(bu" 2
Remove \fRarguments\&.callee\fP usage
.PP
.SH "2014-10-14 / 1\&.2\&.7"
.PP
.IP "\(bu" 2
Remove duplicate line
.PP
.SH "2014-10-02 / 1\&.2\&.6"
.PP
.IP "\(bu" 2
Fix \fRexpose\fP to be \fRtrue\fP for \fRClientError\fP constructor
.PP
.SH "2014-09-28 / 1\&.2\&.5"
.PP
.IP "\(bu" 2
deps: statuses@1
.PP
.SH "2014-09-21 / 1\&.2\&.4"
.PP
.IP "\(bu" 2
Fix dependency version to work with old \fRnpm\fPs
.PP
.SH "2014-09-21 / 1\&.2\&.3"
.PP
.IP "\(bu" 2
deps: statuses1\&.1\&.0
.PP
.SH "2014-09-21 / 1\&.2\&.2"
.PP
.IP "\(bu" 2
Fix publish error
.PP
.SH "2014-09-21 / 1\&.2\&.1"
.PP
.IP "\(bu" 2
Support Node\&.js 0\&.6
.IP "\(bu" 2
Use \fRinherits\fP instead of \fRutil\fP
.PP
.SH "2014-09-09 / 1\&.2\&.0"
.PP
.IP "\(bu" 2
Fix the way inheriting functions
.IP "\(bu" 2
Support \fRexpose\fP being provided in properties argument
.PP
.SH "2014-09-08 / 1\&.1\&.0"
.PP
.IP "\(bu" 2
Default status to 500
.IP "\(bu" 2
Support provided \fRerror\fP to extend
.PP
.SH "2014-09-08 / 1\&.0\&.1"
.PP
.IP "\(bu" 2
Fix accepting string message
.PP
.SH "2014-09-08 / 1\&.0\&.0"
.PP
.IP "\(bu" 2
Initial release 
.PP

