.TH "md_backend_2node__modules_2node-gyp_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2node-gyp_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 
.SS "\fR8\&.4\&.1\fP (2024-11-19)"
.SS "Bug Fixes"
.IP "\(bu" 2
windows command missing space (\fR#2553\fP) (\fRcc37b88\fP)
.PP
.SS "Doc"
.IP "\(bu" 2
fix typo in powershell node-gyp update (\fR787cf7f\fP)
.PP
.SS "Core"
.IP "\(bu" 2
npmlog@6\&.0\&.0 (\fR8083f6b\fP)
.PP
.SH "\fR8\&.4\&.0\fP (2024-11-05)"
.PP
.SS "Features"
.IP "\(bu" 2
build with config\&.gypi from node headers (\fRa27dc08\fP)
.IP "\(bu" 2
support vs2022 (\fR#2533\fP) (\fR5a00387\fP)
.PP
.SH "\fR8\&.3\&.0\fP (2024-10-11)"
.PP
.SS "Features"
.IP "\(bu" 2
\fBgyp:\fP update gyp to v0\&.10\&.0 (\fR#2521\fP) (\fR5585792\fP)
.PP
.SS "Tests"
.IP "\(bu" 2
Python 3\&.10 was release on Oct\&. 4th (\fR#2504\fP) (\fR0a67dcd\fP)
.PP
.SS "Miscellaneous"
.IP "\(bu" 2
\fBdeps:\fP bump make-fetch-happen from 8\&.0\&.14 to 9\&.1\&.0 (\fRb05b4fe\fP)
.IP "\(bu" 2
refactor the creation of config\&.gypi file (\fRf2ad87f\fP)
.PP
.SH "\fR8\&.2\&.0\fP (2024-08-23)"
.PP
.SS "Features"
.IP "\(bu" 2
\fBgyp:\fP update gyp to v0\&.9\&.6 (\fR#2481\fP) (\fRed9a9ed\fP)
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
add error arg back into catch block for older Node\&.js users (\fR5cde818\fP)
.IP "\(bu" 2
change default gyp update message (\fR#2420\fP) (\fRcfd12ff\fP)
.IP "\(bu" 2
doc how to update node-gyp independently from npm (\fRc8c0af7\fP)
.IP "\(bu" 2
missing spaces (\fRf0882b1\fP)
.PP
.SS "Core"
.IP "\(bu" 2
deep-copy process\&.config during configure (\fR#2368\fP) (\fR5f1a06c\fP)
.PP
.SS "Miscellaneous"
.IP "\(bu" 2
\fBdeps:\fP bump tar from 6\&.1\&.0 to 6\&.1\&.2 (\fR#2474\fP) (\fRec15a3e\fP)
.IP "\(bu" 2
fix typos discovered by codespell (\fR#2442\fP) (\fR2d0ce55\fP)
.IP "\(bu" 2
GitHub Actions Test on node: [12\&.x, 14\&.x, 16\&.x] (\fR#2439\fP) (\fRb7bccdb\fP)
.PP
.SS "Doc"
.IP "\(bu" 2
correct link to 'binding\&.gyp files out in the wild' (\fR#2483\fP) (\fR660dd7b\fP)
.IP "\(bu" 2
\fBwiki:\fP Add a link to the node-midi binding\&.gyp file\&. (\fRb354711\fP)
.IP "\(bu" 2
\fBwiki:\fP add bcrypt (\fRe199cfa\fP)
.IP "\(bu" 2
\fBwiki:\fP Add helpful information (\fR4eda827\fP)
.IP "\(bu" 2
\fBwiki:\fP Add node-canvas (\fR13a9553\fP)
.IP "\(bu" 2
\fBwiki:\fP Add node-openvg-canvas and node-openvg\&. (\fR61f709e\fP)
.IP "\(bu" 2
\fBwiki:\fP add one more example (\fR77f3632\fP)
.IP "\(bu" 2
\fBwiki:\fP add topcube, node-osmium, and node-osrm (\fR1a75d2b\fP)
.IP "\(bu" 2
\fBwiki:\fP Added details for properly fixing (\fR3d4d9d5\fP)
.IP "\(bu" 2
\fBwiki:\fP Added Ghostscript4JS (\fRbf4bed1\fP)
.IP "\(bu" 2
\fBwiki:\fP added levelup (\fR1575bce\fP)
.IP "\(bu" 2
\fBwiki:\fP Added nk-mysql (nodamysql) (\fR5b4f2d0\fP)
.IP "\(bu" 2
\fBwiki:\fP Added nk-xrm-installer \&.gyp references, including \&.py scripts for providing complete reference to examples of fetching source via http, extracting, and moving files (as opposed to copying) (\fRceb3088\fP)
.IP "\(bu" 2
\fBwiki:\fP Added tip about resolving frustrating LNK1181 error (\fRe64798d\fP)
.IP "\(bu" 2
\fBwiki:\fP ADDED: Node\&.js binding to OpenCV (\fRe2dc777\fP)
.IP "\(bu" 2
\fBwiki:\fP Adding link to node-cryptopp's gyp file (\fR875adbe\fP)
.IP "\(bu" 2
\fBwiki:\fP Adding the sharp library to the list (\fR9dce0e4\fP)
.IP "\(bu" 2
\fBwiki:\fP Adds node-fann (\fR23e3d48\fP)
.IP "\(bu" 2
\fBwiki:\fP Adds node-inotify and v8-profiler (\fRb6e542f\fP)
.IP "\(bu" 2
\fBwiki:\fP Bumping Python version from 2\&.3 to 2\&.7 as per the node-gyp readme (\fR55ebd6e\fP)
.IP "\(bu" 2
\fBwiki:\fP C++ build tools version upgraded (\fR5b899b7\fP)
.IP "\(bu" 2
\fBwiki:\fP change bcrypt url to binding\&.gyp file (\fRe11bdd8\fP)
.IP "\(bu" 2
\fBwiki:\fP Clarification + direct link to VS2010 (\fR531c724\fP)
.IP "\(bu" 2
\fBwiki:\fP Correcting the link to node-osmium (\fRfae7516\fP)
.IP "\(bu" 2
\fBwiki:\fP Created 'binding\&.gyp' files out in the wild (markdown) (\fRd4fd143\fP)
.IP "\(bu" 2
\fBwiki:\fP Created Common issues (markdown) (\fRa38299e\fP)
.IP "\(bu" 2
\fBwiki:\fP Created Error: 'pre' versions of node cannot be installed (markdown) (\fR98bc80d\fP)
.IP "\(bu" 2
\fBwiki:\fP Created Linking to OpenSSL (markdown) (\fRc46d00d\fP)
.IP "\(bu" 2
\fBwiki:\fP Created Updating npm's bundled node gyp (markdown) (\fRe0ac8d1\fP)
.IP "\(bu" 2
\fBwiki:\fP Created use of undeclared identifier 'TypedArray' (markdown) (\fR65ba711\fP)
.IP "\(bu" 2
\fBwiki:\fP Created Visual Studio 2010 Setup (markdown) (\fR5b80e83\fP)
.IP "\(bu" 2
\fBwiki:\fP Created Visual studio 2012 setup (markdown) (\fRbecef31\fP)
.IP "\(bu" 2
\fBwiki:\fP Destroyed Visual Studio 2010 Setup (markdown) (\fR93423b4\fP)
.IP "\(bu" 2
\fBwiki:\fP Destroyed Visual studio 2012 setup (markdown) (\fR3601508\fP)
.IP "\(bu" 2
\fBwiki:\fP Different commands for Windows npm v6 vs\&. v7 (\fR0fce46b\fP)
.IP "\(bu" 2
\fBwiki:\fP Drop in favor of (\fR9285ff6\fP)
.IP "\(bu" 2
\fBwiki:\fP Explicit link to Visual C++ 2010 Express (\fR378c363\fP)
.IP "\(bu" 2
\fBwiki:\fP fix link to gyp file used to build libsqlite3 (\fR54db8d7\fP)
.IP "\(bu" 2
\fBwiki:\fP Fix link to node-zipfile (\fR92e49a8\fP)
.IP "\(bu" 2
\fBwiki:\fP fixed node-serialport link (\fR954ee53\fP)
.IP "\(bu" 2
\fBwiki:\fP I highly missing it in common issue as every windows biggner face that issue (\fRd617fae\fP)
.IP "\(bu" 2
\fBwiki:\fP if ouns that the -h did not help\&. I founs on github that there was support for visual studio 2015, while i couldn't install node-red beacuse it kept telling me the key 2015 was missing\&. looking in he gyp python code i found the local file was bot up t dat with the github repo\&. updating took several efforts before i tried to drop the -g option\&. (\fR408b72f\fP)
.IP "\(bu" 2
\fBwiki:\fP If permissions error, please try and then the command\&. (\fRee8e1c1\fP)
.IP "\(bu" 2
\fBwiki:\fP Improve Unix instructions (\fRc3e5487\fP)
.IP "\(bu" 2
\fBwiki:\fP link to docs/ from README (\fRb52e487\fP)
.IP "\(bu" 2
\fBwiki:\fP Lower case L (\fR3aa2c6b\fP)
.IP "\(bu" 2
\fBwiki:\fP Make changes discussed in https://github.com/nodejs/node-gyp/issues/2416 (\fR1dcad87\fP)
.IP "\(bu" 2
\fBwiki:\fP move wiki docs into doc/ (\fRf0a4835\fP)
.IP "\(bu" 2
\fBwiki:\fP node-sass in the wild (\fRd310a73\fP)
.IP "\(bu" 2
\fBwiki:\fP node-srs was a 404 (\fRbbca21a\fP)
.IP "\(bu" 2
\fBwiki:\fP Note: VS2010 seems to be no longer available! VS2013 or nothing! (\fR7b5dcaf\fP)
.IP "\(bu" 2
\fBwiki:\fP safer doc names, remove unnecessary TypedArray doc (\fR161c235\fP)
.IP "\(bu" 2
\fBwiki:\fP sorry, forgot to mention a specific windows version\&. (\fRd69dffc\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR7444b47\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fRd766b74\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fRd319b0e\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR3c6692d\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR93392d5\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR8841158\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR81bfa1f\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fRd1cd237\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR3de9e17\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fRa9b7096\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR3236069\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR1462755\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR7ab1337\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR640895d\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fRced8c96\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR27b883a\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fRd29fb13\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fR2765891\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated 'binding\&.gyp' files out in the wild (markdown) (\fRdc97766\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Error: 'pre' versions of node cannot be installed (markdown) (\fRe9f8b33\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Home (markdown) (\fR3407109\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Home (markdown) (\fR6e392bc\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Home (markdown) (\fR65efe32\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Home (markdown) (\fRea28f09\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Home (markdown) (\fR0e37ff4\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Home (markdown) (\fRb398ef4\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Linking to OpenSSL (markdown) (\fR8919028\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Linking to OpenSSL (markdown) (\fRc00eb77\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated node-levelup to node-leveldown (broken links) (\fR59668bb\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Updating npm's bundled node gyp (markdown) (\fRd314854\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Updating npm's bundled node gyp (markdown) (\fR11858b0\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Updating npm's bundled node gyp (markdown) (\fR33561e9\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Updating npm's bundled node gyp (markdown) (\fR4a7f2d0\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Updating npm's bundled node gyp (markdown) (\fR979a706\fP)
.IP "\(bu" 2
\fBwiki:\fP Updated Updating npm's bundled node gyp (markdown) (\fRe50e04d\fP)
.PP
.SH "\fR8\&.1\&.0\fP (2024-05-28)"
.PP
.SS "Features"
.IP "\(bu" 2
\fBgyp:\fP update gyp to v0\&.9\&.1 (\fR#2402\fP) (\fR814b1b0\fP)
.PP
.SS "Miscellaneous"
.IP "\(bu" 2
add \fRrelease-please-action\fP for automated releases (\fR#2395\fP) (\fR07e9d7c\fP)
.PP
.SS "Core"
.IP "\(bu" 2
fail gracefully if we can't find the username (\fR#2375\fP) (\fRfca4795\fP)
.IP "\(bu" 2
log as yes/no whether build dir was created (\fR#2370\fP) (\fR245dee5\fP)
.PP
.SS "Doc"
.IP "\(bu" 2
fix v8\&.0\&.0 release date (\fR4b83c3d\fP)
.IP "\(bu" 2
remove redundant version info (\fR#2403\fP) (\fR1423670\fP)
.IP "\(bu" 2
Update README\&.md Visual Studio Community page polski to auto (\fR#2371\fP) (\fR1b4697a\fP)
.PP
.SH "v8\&.0\&.0 2024-04-03"
.PP
.IP "\(bu" 2
[\fR\fR0d8a6f1b19\fP\fP] - \fBci\fP: update actions/setup-node to v2 (#2302) (Sora Morimoto) \fR#2302\fP
.IP "\(bu" 2
[\fR\fR15a5c7d45b\fP\fP] - \fBci\fP: migrate deprecated grammar (#2285) (Jiawen Geng) \fR#2285\fP
.IP "\(bu" 2
[\fR\fR06ddde27f9\fP\fP] - \fBdeps\fP: sync mutual dependencies with npm (DeeDeeG) \fR#2348\fP
.IP "\(bu" 2
[\fR\fRa5fd1f41e3\fP\fP] - \fBdoc\fP: add downloads badge (#2352) (Jiawen Geng) \fR#2352\fP
.IP "\(bu" 2
[\fR\fRcc1cbce056\fP\fP] - \fBdoc\fP: update \fBmacOS_Catalina\&.md\fP (#2293) (iMrLopez) \fR#2293\fP
.IP "\(bu" 2
[\fR\fR6287118fc4\fP\fP] - \fBdoc\fP: updated README\&.md to copy easily (#2281) (மனோஜ்குமார் பழனிச்சாமி) \fR#2281\fP
.IP "\(bu" 2
[\fR\fR66c0f04467\fP\fP] - \fBdoc\fP: add missing \fRsudo\fP to Catalina doc (Karl Horky) \fR#2244\fP
.IP "\(bu" 2
[\fR\fR0da2e0140d\fP\fP] - \fBgyp\fP: update gyp to v0\&.8\&.1 (#2355) (DeeDeeG) \fR#2355\fP
.IP "\(bu" 2
[\fR\fR0093ec8646\fP\fP] - \fBgyp\fP: Improve our flake8 linting tests (Christian Clauss) \fR#2356\fP
.IP "\(bu" 2
[\fR\fRa78b584236\fP\fP] - **(SEMVER-MAJOR)** \fBgyp\fP: remove support for Python 2 (#2300) (Christian Clauss) \fR#2300\fP
.IP "\(bu" 2
[\fR\fRc3c510d89e\fP\fP] - \fBgyp\fP: update gyp to v0\&.8\&.0 (#2318) (Christian Clauss) \fR#2318\fP
.IP "\(bu" 2
[\fR\fR9e1397c52e\fP\fP] - **(SEMVER-MAJOR)** \fBgyp\fP: update gyp to v0\&.7\&.0 (#2284) (Jiawen Geng) \fR#2284\fP
.IP "\(bu" 2
[\fR\fR1bd18f3e77\fP\fP] - **(SEMVER-MAJOR)** \fBlib\fP: drop Python 2 support in find-python\&.js (#2333) (DeeDeeG) \fR#2333\fP
.IP "\(bu" 2
[\fR\fRe81602ef55\fP\fP] - **(SEMVER-MAJOR)** \fBlib\fP: migrate requests to fetch (#2220) (Matias Lopez) \fR#2220\fP
.IP "\(bu" 2
[\fR\fR392b7760b4\fP\fP] - \fBlib\fP: avoid changing process\&.config (#2322) (Michaël Zasso) \fR#2322\fP
.PP
.SH "v7\&.1\&.2 2020-10-17"
.PP
.IP "\(bu" 2
[\fR\fR096e3aded5\fP\fP] - \fBgyp\fP: update gyp to 0\&.6\&.2 (Myles Borins) \fR#2241\fP
.IP "\(bu" 2
[\fR\fR54f97cd243\fP\fP] - \fBdoc\fP: add cmd to reset \fRxcode-select\fP to initial state (Valera Rozuvan) \fR#2235\fP
.PP
.SH "v7\&.1\&.1 2020-10-15"
.PP
This release restores the location of shared library builds to the pre-v7 location\&. In v7\&.0\&.0 until this release, shared library outputs were placed in a lib\&.target subdirectory inside the build/{Release,Debug} directory for builds using \fRmake\fP (Linux, etc\&.)\&. This is inconsistent with macOS (Xcode) behavior and previous node-gyp behavior so has been reverted\&. We consider this a bug-fix rather than semver-major change\&.
.PP
.IP "\(bu" 2
[\fR\fR18bf2d1d38\fP\fP] - \fBdeps\fP: update deps to match npm@7 (Rod Vagg) \fR#2240\fP
.IP "\(bu" 2
[\fR\fRee6a837cb7\fP\fP] - \fBgyp\fP: update gyp to 0\&.6\&.1 (Rod Vagg) \fR#2238\fP
.IP "\(bu" 2
[\fR\fR3e7f8ccafc\fP\fP] - \fBlib\fP: better log message when ps fails (Martin Midtgaard) \fR#2229\fP
.IP "\(bu" 2
[\fR\fR7fb314339f\fP\fP] - \fBtest\fP: GitHub Actions: Test on Python 3\&.9 (Christian Clauss) \fR#2230\fP
.IP "\(bu" 2
[\fR\fR754996b9ec\fP\fP] - \fBdoc\fP: replace status badges with new Actions badge (Rod Vagg) \fR#2218\fP
.IP "\(bu" 2
[\fR\fR2317dc400c\fP\fP] - \fBci\fP: switch to GitHub Actions (Shelley Vohr) \fR#2210\fP
.IP "\(bu" 2
[\fR\fR2cca9b74f7\fP\fP] - \fBdoc\fP: drop the --production flag for installing windows-build-tools (DeeDeeG) \fR#2206\fP
.PP
.SH "v7\&.1\&.0 2020-08-12"
.PP
.IP "\(bu" 2
[\fR\fRaaf33c3029\fP\fP] - \fBbuild\fP: add update-gyp script (Samuel Attard) \fR#2167\fP
.IP "\(bu" 2
* [\fR\fR3baa4e4172\fP\fP] - **(SEMVER-MINOR)** \fBgyp\fP: update gyp to 0\&.4\&.0 (Samuel Attard) \fR#2165\fP
.IP "\(bu" 2
* [\fR\fRf461d56c53\fP\fP] - **(SEMVER-MINOR)** \fBbuild\fP: support apple silicon (arm64 darwin) builds (Samuel Attard) \fR#2165\fP
.IP "\(bu" 2
* [\fR\fRee6fa7d3bc\fP\fP] - \fBdocs\fP: note that node-gyp@7 should solve Catalina CLT issues (Rod Vagg) \fR#2156\fP
.IP "\(bu" 2
* [\fR\fR4fc8ff179d\fP\fP] - \fBdoc\fP: silence curl for macOS Catalina acid test (Chia Wei Ong) \fR#2150\fP
.IP "\(bu" 2
* [\fR\fR7857cb2eb1\fP\fP] - \fBdeps\fP: increase 'engines' to 'node' : '\\>= 10\&.12\&.0' (DeeDeeG) \fR#2153\fP
.PP
.SH "v7\&.0\&.0 2020-06-03"
.PP
.IP "\(bu" 2
[\fR\fRe18a61afc1\fP\fP] - \fBbuild\fP: shrink bloated addon binaries on windows (Shelley Vohr) \fR#2060\fP
.IP "\(bu" 2
[\fR\fR4937722cf5\fP\fP] - **(SEMVER-MAJOR)** \fBdeps\fP: replace mkdirp with {recursive} mkdir (Rod Vagg) \fR#2123\fP
.IP "\(bu" 2
[\fR\fRd45438a047\fP\fP] - **(SEMVER-MAJOR)** \fBdeps\fP: update deps, match to npm@7 (Rod Vagg) \fR#2126\fP
.IP "\(bu" 2
[\fR\fRba4f34b7d6\fP\fP] - \fBdoc\fP: update catalina xcode clt download link (Dario Vladovic) \fR#2133\fP
.IP "\(bu" 2
[\fR\fRf7bfce96ed\fP\fP] - \fBdoc\fP: update acid test and introduce curl|bash test script (Dario Vladovic) \fR#2105\fP
.IP "\(bu" 2
[\fR\fRe529f3309d\fP\fP] - \fBdoc\fP: update README to reflect upgrade to gyp-next (Ujjwal Sharma) \fR#2092\fP
.IP "\(bu" 2
[\fR\fR9aed6286a3\fP\fP] - \fBdoc\fP: give more attention to Catalina issues doc (Matheus Marchini) \fR#2134\fP
.IP "\(bu" 2
[\fR\fR963f2a7b48\fP\fP] - \fBdoc\fP: improve Catalina discoverability for search engines (Matheus Marchini) \fR#2135\fP
.IP "\(bu" 2
[\fR\fR7b75af349b\fP\fP] - \fBdoc\fP: add macOS Catalina software update info (Karl Horky) \fR#2078\fP
.IP "\(bu" 2
[\fR\fR4f23c7bee2\fP\fP] - \fBdoc\fP: update link to the code of conduct (#2073) (Michaël Zasso) \fR#2073\fP
.IP "\(bu" 2
[\fR\fR473cfa283f\fP\fP] - \fBdoc\fP: note in README that Python 3\&.8 is supported (#2072) (Michaël Zasso) \fR#2072\fP
.IP "\(bu" 2
[\fR\fRe7402b4a7c\fP\fP] - \fBdoc\fP: update catalina xcode cli tools download link (#2044) (Dario Vladović) \fR#2044\fP
.IP "\(bu" 2
[\fR\fR35de45984f\fP\fP] - \fBdoc\fP: update catalina xcode cli tools download link; formatting (Jonathan Hult) \fR#2034\fP
.IP "\(bu" 2
[\fR\fR48642191f5\fP\fP] - \fBdoc\fP: add download link for Command Line Tools for Xcode (Przemysław Bitkowski) \fR#2029\fP
.IP "\(bu" 2
[\fR\fRae5b150051\fP\fP] - \fBdoc\fP: Catalina suggestion: remove /Library/Developer/CommandLineTools (Christian Clauss) \fR#2022\fP
.IP "\(bu" 2
[\fR\fRd1dea13fe4\fP\fP] - \fBdoc\fP: fix changelog 6\&.1\&.0 release year to be 2020 (Quentin Vernot) \fR#2024\fP
.IP "\(bu" 2
[\fR\fR6356117b08\fP\fP] - \fBdoc, bin\fP: stop suggesting opening node-gyp issues (Bartosz Sosnowski) \fR#2096\fP
.IP "\(bu" 2
[\fR\fRa6b76a8b48\fP\fP] - \fBgyp\fP: update gyp to 0\&.2\&.1 (Ujjwal Sharma) \fR#2092\fP
.IP "\(bu" 2
[\fR\fRebc34ec823\fP\fP] - \fBgyp\fP: update gyp to 0\&.2\&.0 (Ujjwal Sharma) \fR#2092\fP
.IP "\(bu" 2
[\fR\fR972780bde7\fP\fP] - **(SEMVER-MAJOR)** \fBgyp\fP: sync code base with nodejs repo (#1975) (Michaël Zasso) \fR#1975\fP
.IP "\(bu" 2
[\fR\fRc255ffbf6a\fP\fP] - \fBlib\fP: drop '-2' flag for 'py\&.exe' launcher (DeeDeeG) \fR#2131\fP
.IP "\(bu" 2
[\fR\fR1f7e1e93b5\fP\fP] - \fBlib\fP: ignore VS instances that cause COMExceptions (Andrew Casey) \fR#2018\fP
.IP "\(bu" 2
[\fR\fR741ab096d5\fP\fP] - \fBtest\fP: remove support for EOL versions of Node\&.js (Shelley Vohr)
.IP "\(bu" 2
[\fR\fRca86ef2539\fP\fP] - \fBtest\fP: bump actions/checkout from v1 to v2 (BSKY) \fR#2063\fP
.PP
.SH "v6\&.1\&.0 2020-01-08"
.PP
.IP "\(bu" 2
[\fR\fR9a7dd16b76\fP\fP] - \fBdoc\fP: remove backticks from Python version list (Rod Vagg) \fR#2011\fP
.IP "\(bu" 2
[\fR\fR26cd6eaea6\fP\fP] - \fBdoc\fP: add GitHub Actions badge (#1994) (Rod Vagg) \fR#1994\fP
.IP "\(bu" 2
[\fR\fR312c12ef4f\fP\fP] - \fBdoc\fP: update \fBmacOS_Catalina\&.md\fP (#1992) (James Home) \fR#1992\fP
.IP "\(bu" 2
[\fR\fRf7b6b6b77b\fP\fP] - \fBdoc\fP: fix typo in README\&.md (#1985) (Suraneti Rodsuwan) \fR#1985\fP
.IP "\(bu" 2
[\fR\fR6b8f2652dd\fP\fP] - \fBdoc\fP: add travis badge (Rod Vagg) \fR#1971\fP
.IP "\(bu" 2
[\fR\fR20aa0b44f7\fP\fP] - \fBdoc\fP: macOS Catalina add two commands (Christian Clauss) \fR#1962\fP
.IP "\(bu" 2
[\fR\fR14f2a07a39\fP\fP] - \fBgyp\fP: list(dict) so we can del dict(key) while iterating (Christian Clauss) \fR#2009\fP
.IP "\(bu" 2
[\fR\fRf242ce4d2c\fP\fP] - \fBlib\fP: compatibility with semver ≥ 7 (\fRnew\fP for semver\&.Range) (Xavier Guimard) \fR#2006\fP
.IP "\(bu" 2
[\fR\fR3bcba2a01a\fP\fP] - **(SEMVER-MINOR)** \fBlib\fP: noproxy support, match proxy detection to \fRrequest\fP (Matias Lopez) \fR#1978\fP
.IP "\(bu" 2
[\fR\fR470cc2178e\fP\fP] - \fBtest\fP: remove old docker test harness (#1993) (Rod Vagg) \fR#1993\fP
.IP "\(bu" 2
[\fR\fR31ecc8421d\fP\fP] - \fBtest\fP: add Windows to GitHub Actions testing (#1996) (Christian Clauss) \fR#1996\fP
.IP "\(bu" 2
[\fR\fR5a729e86ee\fP\fP] - \fBtest\fP: fix typo in header download test (#2001) (Richard Lau) \fR#2001\fP
.IP "\(bu" 2
[\fR\fR345c70e56d\fP\fP] - \fBtest\fP: direct python invocation & simpler pyenv (Matias Lopez) \fR#1979\fP
.IP "\(bu" 2
[\fR\fRd6a7e0e1fb\fP\fP] - \fBtest\fP: fix macOS Travis on Python 2\&.7 & 3\&.7 (Christian Clauss) \fR#1979\fP
.IP "\(bu" 2
[\fR\fR5a64e9bd32\fP\fP] - \fBtest\fP: initial Github Actions with Ubuntu & macOS (Christian Clauss) \fR#1985\fP
.IP "\(bu" 2
[\fR\fR04da736d38\fP\fP] - \fBtest\fP: fix Python unittests (cclauss) \fR#1961\fP
.IP "\(bu" 2
[\fR\fR0670e5189d\fP\fP] - \fBtest\fP: add header download test (Rod Vagg) \fR#1796\fP
.IP "\(bu" 2
[\fR\fRc506a6a150\fP\fP] - \fBtest\fP: configure proper devDir for invoking configure() (Rod Vagg) \fR#1796\fP
.PP
.SH "v6\&.0\&.1 2019-11-01"
.PP
.IP "\(bu" 2
[\fR\fR8ec2e681d5\fP\fP] - \fBdoc\fP: add \fBmacOS_Catalina\&.md\fP document (cclauss) \fR#1940\fP
.IP "\(bu" 2
[\fR\fR1b11be63cc\fP\fP] - \fBgyp\fP: python3 fixes: utf8 decode, use of 'None' in eval (Wilfried Goesgens) \fR#1925\fP
.IP "\(bu" 2
[\fR\fRc0282daa48\fP\fP] - \fBgyp\fP: iteritems() -> items() in \fBcompile_commands_json\&.py\fP (cclauss) \fR#1947\fP
.IP "\(bu" 2
[\fR\fRd8e09a1b6a\fP\fP] - \fBgyp\fP: make cmake python3 compatible (gengjiawen) \fR#1944\fP
.IP "\(bu" 2
[\fR\fR9c0f3404f0\fP\fP] - \fBgyp\fP: fix TypeError in XcodeVersion() (Christian Clauss) \fR#1939\fP
.IP "\(bu" 2
[\fR\fRbb2eb72a3f\fP\fP] - \fBgyp\fP: finish decode stdout on Python 3 (Christian Clauss) \fR#1937\fP
.IP "\(bu" 2
[\fR\fRf0693413d9\fP\fP] - \fBsrc,win\fP: allow 403 errors for arm64 node\&.lib (Richard Lau) \fR#1934\fP
.IP "\(bu" 2
[\fR\fRc60c22de58\fP\fP] - \fBdeps\fP: update deps to roughly match current npm@6 (Rod Vagg) \fR#1920\fP
.IP "\(bu" 2
[\fR\fRb91718eefc\fP\fP] - \fBtest\fP: upgrade Linux Travis CI to Python 3\&.8 (Christian Clauss) \fR#1923\fP
.IP "\(bu" 2
[\fR\fR3538a317b6\fP\fP] - \fBdoc\fP: adjustments to the README\&.md for new users (Dan Pike) \fR#1919\fP
.IP "\(bu" 2
[\fR\fR4fff8458c0\fP\fP] - \fBtravis\fP: ignore failed \fRbrew upgrade npm\fP, update xcode (Christian Clauss) \fR#1932\fP
.IP "\(bu" 2
[\fR\fR60e4488f08\fP\fP] - \fBbuild\fP: avoid bare exceptions in \fBxcode_emulation\&.py\fP (Christian Clauss) \fR#1932\fP
.IP "\(bu" 2
[\fR\fR032db2a2d0\fP\fP] - \fBlib,install\fP: always download SHA sums on Windows (Sam Hughes) \fR#1926\fP
.IP "\(bu" 2
[\fR\fR5a83630c33\fP\fP] - \fBtravis\fP: add Windows + Python 3\&.8 to the mix (Rod Vagg) \fR#1921\fP
.PP
.SH "v6\&.0\&.0 2019-10-04"
.PP
.IP "\(bu" 2
[\fR\fRdd0e97ef0b\fP\fP] - **(SEMVER-MAJOR)** \fBlib\fP: try to find \fRpython\fP after \fRpython3\fP (Sam Roberts) \fR#1907\fP
.IP "\(bu" 2
[\fR\fRf60ed47d14\fP\fP] - \fBtravis\fP: add Python 3\&.5 and 3\&.6 tests on Linux (Christian Clauss) \fR#1903\fP
.IP "\(bu" 2
[\fR\fRc763ca1838\fP\fP] - **(SEMVER-MAJOR)** \fBdoc\fP: Declare that node-gyp is Python 3 compatible (cclauss) \fR#1811\fP
.IP "\(bu" 2
[\fR\fR3d1c60ab81\fP\fP] - **(SEMVER-MAJOR)** \fBlib\fP: accept Python 3 by default (João Reis) \fR#1844\fP
.IP "\(bu" 2
[\fR\fRc6e3b65a23\fP\fP] - **(SEMVER-MAJOR)** \fBlib\fP: raise the minimum Python version from 2\&.6 to 2\&.7 (cclauss) \fR#1818\fP
.PP
.SH "v5\&.1\&.1 2020-05-25"
.PP
.IP "\(bu" 2
[\fR\fRbdd3a79abe\fP\fP] - \fBbuild\fP: shrink bloated addon binaries on windows (Shelley Vohr) \fR#2060\fP
.IP "\(bu" 2
[\fR\fR1f2ba75bc0\fP\fP] - \fBdoc\fP: add macOS Catalina software update info (Karl Horky) \fR#2078\fP
.IP "\(bu" 2
[\fR\fRc106d915f5\fP\fP] - \fBdoc\fP: update catalina xcode cli tools download link (#2044) (Dario Vladović) \fR#2044\fP
.IP "\(bu" 2
[\fR\fR9a6fea92e2\fP\fP] - \fBdoc\fP: update catalina xcode cli tools download link; formatting (Jonathan Hult) \fR#2034\fP
.IP "\(bu" 2
[\fR\fR59b0b1add8\fP\fP] - \fBdoc\fP: add download link for Command Line Tools for Xcode (Przemysław Bitkowski) \fR#2029\fP
.IP "\(bu" 2
[\fR\fRbb8d0e7b10\fP\fP] - \fBdoc\fP: Catalina suggestion: remove /Library/Developer/CommandLineTools (Christian Clauss) \fR#2022\fP
.IP "\(bu" 2
[\fR\fRfb2e80d4e3\fP\fP] - \fBdoc\fP: update link to the code of conduct (#2073) (Michaël Zasso) \fR#2073\fP
.IP "\(bu" 2
[\fR\fR251d9c885c\fP\fP] - \fBdoc\fP: note in README that Python 3\&.8 is supported (#2072) (Michaël Zasso) \fR#2072\fP
.IP "\(bu" 2
[\fR\fR2b6fc3c8d6\fP\fP] - \fBdoc, bin\fP: stop suggesting opening node-gyp issues (Bartosz Sosnowski) \fR#2096\fP
.IP "\(bu" 2
[\fR\fRa876ae58ad\fP\fP] - \fBtest\fP: bump actions/checkout from v1 to v2 (BSKY) \fR#2063\fP
.PP
.SH "v5\&.1\&.0 2020-02-05"
.PP
.IP "\(bu" 2
[\fR\fRf37a8b40d0\fP\fP] - \fBdoc\fP: add GitHub Actions badge (#1994) (Rod Vagg) \fR#1994\fP
.IP "\(bu" 2
[\fR\fRcb3f6aae5e\fP\fP] - \fBdoc\fP: update \fBmacOS_Catalina\&.md\fP (#1992) (James Home) \fR#1992\fP
.IP "\(bu" 2
[\fR\fR0607596a4c\fP\fP] - \fBdoc\fP: fix typo in README\&.md (#1985) (Suraneti Rodsuwan) \fR#1985\fP
.IP "\(bu" 2
[\fR\fR0d5a415a14\fP\fP] - \fBdoc\fP: add travis badge (Rod Vagg) \fR#1971\fP
.IP "\(bu" 2
[\fR\fR103740cd95\fP\fP] - \fBgyp\fP: list(dict) so we can del dict(key) while iterating (Christian Clauss) \fR#2009\fP
.IP "\(bu" 2
[\fR\fR278dcddbdd\fP\fP] - \fBlib\fP: ignore VS instances that cause COMExceptions (Andrew Casey) \fR#2018\fP
.IP "\(bu" 2
[\fR\fR1694907bbf\fP\fP] - \fBlib\fP: compatibility with semver ≥ 7 (\fRnew\fP for semver\&.Range) (Xavier Guimard) \fR#2006\fP
.IP "\(bu" 2
[\fR\fRa3f1143514\fP\fP] - **(SEMVER-MINOR)** \fBlib\fP: noproxy support, match proxy detection to \fRrequest\fP (Matias Lopez) \fR#1978\fP
.IP "\(bu" 2
[\fR\fR52365819c7\fP\fP] - \fBtest\fP: remove old docker test harness (#1993) (Rod Vagg) \fR#1993\fP
.IP "\(bu" 2
[\fR\fRbc509c511d\fP\fP] - \fBtest\fP: add Windows to GitHub Actions testing (#1996) (Christian Clauss) \fR#1996\fP
.IP "\(bu" 2
[\fR\fR91ee26dd48\fP\fP] - \fBtest\fP: fix typo in header download test (#2001) (Richard Lau) \fR#2001\fP
.IP "\(bu" 2
[\fR\fR0923f344c9\fP\fP] - \fBtest\fP: direct python invocation & simpler pyenv (Matias Lopez) \fR#1979\fP
.IP "\(bu" 2
[\fR\fR32c8744b34\fP\fP] - \fBtest\fP: fix macOS Travis on Python 2\&.7 & 3\&.7 (Christian Clauss) \fR#1979\fP
.IP "\(bu" 2
[\fR\fRfd4b1351e4\fP\fP] - \fBtest\fP: initial Github Actions with Ubuntu & macOS (Christian Clauss) \fR#1985\fP
.PP
.SH "v5\&.0\&.7 2019-12-16"
.PP
Republish of v5\&.0\&.6 with unnecessary tarball removed from pack file\&.
.SH "v5\&.0\&.6 2019-12-16"
.PP
.IP "\(bu" 2
[\fR\fRcdec00286f\fP\fP] - \fBdoc\fP: adjustments to the README\&.md for new users (Dan Pike) \fR#1919\fP
.IP "\(bu" 2
[\fR\fRb7c8233ef2\fP\fP] - \fBtest\fP: fix Python unittests (cclauss) \fR#1961\fP
.IP "\(bu" 2
[\fR\fRe12b00ab0a\fP\fP] - \fBdoc\fP: macOS Catalina add two commands (Christian Clauss) \fR#1962\fP
.IP "\(bu" 2
[\fR\fR70b9890c0d\fP\fP] - \fBtest\fP: add header download test (Rod Vagg) \fR#1796\fP
.IP "\(bu" 2
[\fR\fR4029fa8629\fP\fP] - \fBtest\fP: configure proper devDir for invoking configure() (Rod Vagg) \fR#1796\fP
.IP "\(bu" 2
[\fR\fRfe8b02cc8b\fP\fP] - \fBdoc\fP: add \fBmacOS_Catalina\&.md\fP document (cclauss) \fR#1940\fP
.IP "\(bu" 2
[\fR\fR8ea47ce365\fP\fP] - \fBgyp\fP: python3 fixes: utf8 decode, use of 'None' in eval (Wilfried Goesgens) \fR#1925\fP
.IP "\(bu" 2
[\fR\fRc7229716ba\fP\fP] - \fBgyp\fP: iteritems() -> items() in \fBcompile_commands_json\&.py\fP (cclauss) \fR#1947\fP
.IP "\(bu" 2
[\fR\fR2a18b2a0f8\fP\fP] - \fBgyp\fP: make cmake python3 compatible (gengjiawen) \fR#1944\fP
.IP "\(bu" 2
[\fR\fR70f391e844\fP\fP] - \fBgyp\fP: fix TypeError in XcodeVersion() (Christian Clauss) \fR#1939\fP
.IP "\(bu" 2
[\fR\fR9f4f0fa34e\fP\fP] - \fBgyp\fP: finish decode stdout on Python 3 (Christian Clauss) \fR#1937\fP
.IP "\(bu" 2
[\fR\fR7cf507906d\fP\fP] - \fBsrc,win\fP: allow 403 errors for arm64 node\&.lib (Richard Lau) \fR#1934\fP
.IP "\(bu" 2
[\fR\fRad0d182c01\fP\fP] - \fBdeps\fP: update deps to roughly match current npm@6 (Rod Vagg) \fR#1920\fP
.IP "\(bu" 2
[\fR\fR1553081ed6\fP\fP] - \fBtest\fP: upgrade Linux Travis CI to Python 3\&.8 (Christian Clauss) \fR#1923\fP
.IP "\(bu" 2
[\fR\fR0705cae9aa\fP\fP] - \fBtravis\fP: ignore failed \fRbrew upgrade npm\fP, update xcode (Christian Clauss) \fR#1932\fP
.IP "\(bu" 2
[\fR\fR7bfdb6f5bf\fP\fP] - \fBbuild\fP: avoid bare exceptions in \fBxcode_emulation\&.py\fP (Christian Clauss) \fR#1932\fP
.IP "\(bu" 2
[\fR\fR7edf7658fa\fP\fP] - \fBlib,install\fP: always download SHA sums on Windows (Sam Hughes) \fR#1926\fP
.IP "\(bu" 2
[\fR\fR69056d04fe\fP\fP] - \fBtravis\fP: add Windows + Python 3\&.8 to the mix (Rod Vagg) \fR#1921\fP
.PP
.SH "v5\&.0\&.5 2019-10-04"
.PP
.IP "\(bu" 2
[\fR\fR3891391746\fP\fP] - \fBdoc\fP: reconcile README with Python 3 compat changes (Rod Vagg) \fR#1911\fP
.IP "\(bu" 2
[\fR\fR07f81f1920\fP\fP] - \fBlib\fP: accept Python 3 after Python 2 (Sam Roberts) \fR#1910\fP
.IP "\(bu" 2
[\fR\fR04ce59f4a2\fP\fP] - \fBdoc\fP: clarify Python configuration, etc (Sam Roberts) \fR#1908\fP
.IP "\(bu" 2
[\fR\fR01c46ee3df\fP\fP] - \fBgyp\fP: add __lt__ to MSVSSolutionEntry (João Reis) \fR#1904\fP
.IP "\(bu" 2
[\fR\fR735d961b99\fP\fP] - \fBwin\fP: support VS 2017 Desktop Express (João Reis) \fR#1902\fP
.IP "\(bu" 2
[\fR\fR3834156a92\fP\fP] - \fBtest\fP: add Python 3\&.5 and 3\&.6 tests on Linux (cclauss) \fR#1909\fP
.IP "\(bu" 2
[\fR\fR1196e990d8\fP\fP] - \fBsrc\fP: update to standard@14 (Rod Vagg) \fR#1899\fP
.IP "\(bu" 2
[\fR\fR53ee7dfe89\fP\fP] - \fBgyp\fP: fix undefined name: cflags --> ldflags (Christian Clauss) \fR#1901\fP
.IP "\(bu" 2
[\fR\fR5871dcf6c9\fP\fP] - \fBsrc,win\fP: add support for fetching arm64 node\&.lib (Richard Townsend) \fR#1875\fP
.PP
.SH "v5\&.0\&.4 2019-09-27"
.PP
.IP "\(bu" 2
[\fR\fR1236869ffc\fP\fP] - \fBgyp\fP: modify XcodeVersion() to convert '4\&.2' to '0420' and '10\&.0' to '1000' (Christian Clauss) \fR#1895\fP
.IP "\(bu" 2
[\fR\fR36638afe48\fP\fP] - \fBgyp\fP: more decode stdout on Python 3 (cclauss) \fR#1894\fP
.IP "\(bu" 2
[\fR\fRf753c167c5\fP\fP] - \fBgyp\fP: decode stdout on Python 3 (cclauss) \fR#1890\fP
.IP "\(bu" 2
[\fR\fR60a4083523\fP\fP] - \fBdoc\fP: update xcode install instructions to match Node's BUILDING (Nhan Khong) \fR#1884\fP
.IP "\(bu" 2
[\fR\fR19dbc9ac32\fP\fP] - \fBdeps\fP: update tar to 4\&.4\&.12 (Matheus Marchini) \fR#1889\fP
.IP "\(bu" 2
[\fR\fR5f3ed92181\fP\fP] - \fBbin\fP: fix the usage instructions (Halit Ogunc) \fR#1888\fP
.IP "\(bu" 2
[\fR\fRaab118edf1\fP\fP] - \fBlib\fP: adding keep-alive header to download requests (Milad Farazmand) \fR#1863\fP
.IP "\(bu" 2
[\fR\fR1186e89326\fP\fP] - \fBlib\fP: ignore non-critical os\&.userInfo() failures (Rod Vagg) \fR#1835\fP
.IP "\(bu" 2
[\fR\fR785e527c3d\fP\fP] - \fBdoc\fP: fix missing argument for setting python path (lagorsse) \fR#1802\fP
.IP "\(bu" 2
[\fR\fRa97615196c\fP\fP] - \fBgyp\fP: rm semicolons (Python != JavaScript) (MattIPv4) \fR#1858\fP
.IP "\(bu" 2
[\fR\fR06019bac24\fP\fP] - \fBgyp\fP: assorted typo fixes (XhmikosR) \fR#1853\fP
.IP "\(bu" 2
[\fR\fR3f4972c1ca\fP\fP] - \fBgyp\fP: use 'is' when comparing to None (Vladyslav Burzakovskyy) \fR#1860\fP
.IP "\(bu" 2
[\fR\fR1cb4708073\fP\fP] - \fBsrc,win\fP: improve unmanaged handling (Peter Sabath) \fR#1852\fP
.IP "\(bu" 2
[\fR\fR5553cd910e\fP\fP] - \fBgyp\fP: improve Windows+Cygwin compatibility (Jose Quijada) \fR#1817\fP
.IP "\(bu" 2
[\fR\fR8bcb1fbb43\fP\fP] - \fBgyp\fP: Python 3 Windows fixes (João Reis) \fR#1843\fP
.IP "\(bu" 2
[\fR\fR2e24d0a326\fP\fP] - \fBtest\fP: accept Python 3 in test-find-python\&.js (João Reis) \fR#1843\fP
.IP "\(bu" 2
[\fR\fR1267b4dc1c\fP\fP] - \fBbuild\fP: add test run Python 3\&.7 on macOS (Christian Clauss) \fR#1843\fP
.IP "\(bu" 2
[\fR\fRda1b031aa3\fP\fP] - \fBbuild\fP: import StringIO on Python 2 and Python 3 (Christian Clauss) \fR#1836\fP
.IP "\(bu" 2
[\fR\fRfa0ed4aa42\fP\fP] - \fBbuild\fP: more Python 3 compat, replace compile with ast (cclauss) \fR#1820\fP
.IP "\(bu" 2
[\fR\fR18d5c7c9d0\fP\fP] - \fBwin,src\fP: update \fBwin_delay_load_hook\&.cc\fP to work with /clr (Ivan Petrovic) \fR#1819\fP
.PP
.SH "v5\&.0\&.3 2019-07-17"
.PP
.IP "\(bu" 2
[\fR\fR66ad305775\fP\fP] - \fBpython\fP: accept Python 3 conditionally (João Reis) \fR#1815\fP
.IP "\(bu" 2
[\fR\fR7e7fce3fed\fP\fP] - \fBpython\fP: move Python detection to its own file (João Reis) \fR#1815\fP
.IP "\(bu" 2
[\fR\fRe40c99e283\fP\fP] - \fBsrc\fP: implement standard\&.js linting (Rod Vagg) \fR#1794\fP
.IP "\(bu" 2
[\fR\fRbb92c761a9\fP\fP] - \fBtest\fP: add Node\&.js 6 on Windows to Travis CI (João Reis) \fR#1812\fP
.IP "\(bu" 2
[\fR\fR7fd924079f\fP\fP] - \fBtest\fP: increase tap timeout (João Reis) \fR#1812\fP
.IP "\(bu" 2
[\fR\fR7e8127068f\fP\fP] - \fBtest\fP: cover supported node versions with travis (Rod Vagg) \fR#1809\fP
.IP "\(bu" 2
[\fR\fR24109148df\fP\fP] - \fBtest\fP: downgrade to tap@^12 for continued Node 6 support (Rod Vagg) \fR#1808\fP
.IP "\(bu" 2
[\fR\fR656117cc4a\fP\fP] - \fBwin\fP: make VS path match case-insensitive (João Reis) \fR#1806\fP
.PP
.SH "v5\&.0\&.2 2019-06-27"
.PP
.IP "\(bu" 2
[\fR\fR2761afbf73\fP\fP] - \fBbuild,test\fP: add duplicate symbol test (Gabriel Schulhof) \fR#1689\fP
.IP "\(bu" 2
[\fR\fR82f129d6de\fP\fP] - \fBgyp\fP: replace optparse to argparse (KiYugadgeter) \fR#1591\fP
.IP "\(bu" 2
[\fR\fRafaaa29c61\fP\fP] - \fBgyp\fP: remove from __future__ import with_statement (cclauss) \fR#1799\fP
.IP "\(bu" 2
[\fR\fRa991f633d6\fP\fP] - \fBgyp\fP: fix the remaining Python 3 issues (cclauss) \fR#1793\fP
.IP "\(bu" 2
[\fR\fRf952b08f84\fP\fP] - \fBgyp\fP: move from __future__ import to the top of the file (cclauss) \fR#1789\fP
.IP "\(bu" 2
[\fR\fR4f4a677dfa\fP\fP] - \fBgyp\fP: use different default compiler for z/OS (Shuowang (Wayne) Zhang) \fR#1768\fP
.IP "\(bu" 2
[\fR\fR03683f09d6\fP\fP] - \fBlib\fP: code de-duplication (Pavel Medvedev) \fR#965\fP
.IP "\(bu" 2
[\fR\fR611bc3c89f\fP\fP] - \fBlib\fP: add \&.json suffix for explicit require (Rod Vagg) \fR#1787\fP
.IP "\(bu" 2
[\fR\fRd3478d7b0b\fP\fP] - \fBmeta\fP: add to \&.gitignore (Refael Ackermann) \fR#1573\fP
.IP "\(bu" 2
[\fR\fR7a9a038e9e\fP\fP] - \fBtest\fP: add parallel test runs on macOS and Windows (cclauss) \fR#1800\fP
.IP "\(bu" 2
[\fR\fR7dd7f2b2a2\fP\fP] - \fBtest\fP: fix Python syntax error in test-adding\&.js (cclauss) \fR#1793\fP
.IP "\(bu" 2
[\fR\fR395f843de0\fP\fP] - \fBtest\fP: replace self-signed cert with 'localhost' (Rod Vagg) \fR#1795\fP
.IP "\(bu" 2
[\fR\fRa52c6eb9e8\fP\fP] - \fBtest\fP: migrate from tape to tap (Rod Vagg) \fR#1795\fP
.IP "\(bu" 2
[\fR\fRec2eb44a30\fP\fP] - \fBtest\fP: use Nan in duplicate_symbols (Gabriel Schulhof) \fR#1689\fP
.IP "\(bu" 2
[\fR\fR1597c84aad\fP\fP] - \fBtest\fP: use Travis CI to run tests on every pull request (cclauss) \fR#1752\fP
.IP "\(bu" 2
[\fR\fRdd9bf929ac\fP\fP] - \fBzos\fP: update compiler options (Shuowang (Wayne) Zhang) \fR#1768\fP
.PP
.SH "v5\&.0\&.1 2019-06-20"
.PP
.IP "\(bu" 2
[\fR\fRe3861722ed\fP\fP] - \fBdoc\fP: document --jobs max (David Sanders) \fR#1770\fP
.IP "\(bu" 2
[\fR\fR1cfdb28886\fP\fP] - \fBlib\fP: reintroduce support for iojs file naming for releases >= 1 && < 4 (Samuel Attard) \fR#1777\fP
.PP
.SH "v5\&.0\&.0 2019-06-13"
.PP
.IP "\(bu" 2
[\fR\fR8a83972743\fP\fP] - **(SEMVER-MAJOR)** \fBbin\fP: follow XDG OS conventions for storing data (Selwyn) \fR#1570\fP
.IP "\(bu" 2
[\fR\fR9e46872ea3\fP\fP] - \fBbin,lib\fP: remove extra comments/lines/spaces (Jon Moss) \fR#1508\fP
.IP "\(bu" 2
[\fR\fR8098ebdeb4\fP\fP] - \fBdeps\fP: replace \fRosenv\fP dependency with native \fRos\fP (Selwyn)
.IP "\(bu" 2
[\fR\fRf83b457e03\fP\fP] - \fBdeps\fP: bump request to 2\&.8\&.7, fixes heok/hawk issues (Rohit Hazra) \fR#1492\fP
.IP "\(bu" 2
[\fR\fR323cee7323\fP\fP] - \fBdeps\fP: pin \fRrequest\fP version range (Refael Ackermann) \fR#1300\fP
.IP "\(bu" 2
[\fR\fRc515912d08\fP\fP] - \fBdoc\fP: improve issue template (Bartosz Sosnowski) \fR#1618\fP
.IP "\(bu" 2
[\fR\fRcca2d66727\fP\fP] - \fBdoc\fP: python info needs own header (Taylor D\&. Lee) \fR#1245\fP
.IP "\(bu" 2
[\fR\fR3e64c780f5\fP\fP] - \fBdoc\fP: lint README\&.md (Jon Moss) \fR#1498\fP
.IP "\(bu" 2
[\fR\fRa20faedc91\fP\fP] - **(SEMVER-MAJOR)** \fBgyp\fP: enable MARMASM items only on new VS versions (João Reis) \fR#1762\fP
.IP "\(bu" 2
[\fR\fR721eb691cf\fP\fP] - \fBgyp\fP: teach MSVS generator about MARMASM Items (Jon Kunkee) \fR#1679\fP
.IP "\(bu" 2
[\fR\fR91744bfecc\fP\fP] - \fBgyp\fP: add support for Windows on Arm (Richard Townsend) \fR#1739\fP
.IP "\(bu" 2
[\fR\fRa6e0a6c7ed\fP\fP] - \fBgyp\fP: move compile_commands_json (Paul Maréchal) \fR#1661\fP
.IP "\(bu" 2
[\fR\fR92e8b52cee\fP\fP] - \fBgyp\fP: fix target --> self\&.target (cclauss)
.IP "\(bu" 2
[\fR\fRfebdfa2137\fP\fP] - \fBgyp\fP: fix sntex error (cclauss) \fR#1333\fP
.IP "\(bu" 2
[\fR\fR588d333c14\fP\fP] - \fBgyp\fP: _winreg module was renamed to winreg in Python 3\&. (Craig Rodrigues)
.IP "\(bu" 2
[\fR\fR98226d198c\fP\fP] - \fBgyp\fP: replace basestring with str, but only on Python 3\&. (Craig Rodrigues)
.IP "\(bu" 2
[\fR\fR7535e4478e\fP\fP] - \fBgyp\fP: replace deprecated functions (Craig Rodrigues)
.IP "\(bu" 2
[\fR\fR2040cd21cc\fP\fP] - \fBgyp\fP: use print as a function, as specified in PEP 3105\&. (Craig Rodrigues)
.IP "\(bu" 2
[\fR\fRabef93ded5\fP\fP] - \fBgyp\fP: get ready for python 3 (cclauss)
.IP "\(bu" 2
[\fR\fR43031fadcb\fP\fP] - \fBpython\fP: clean-up detection (João Reis) \fR#1582\fP
.IP "\(bu" 2
[\fR\fR49ab79d221\fP\fP] - \fBpython\fP: more informative error (Refael Ackermann) \fR#1269\fP
.IP "\(bu" 2
[\fR\fR997bc3c748\fP\fP] - \fBreadme\fP: add ARM64 info to MSVC setup instructions (Jon Kunkee) \fR#1655\fP
.IP "\(bu" 2
[\fR\fR788e767179\fP\fP] - \fBtest\fP: remove unused variable (João Reis)
.IP "\(bu" 2
[\fR\fR6f5a408934\fP\fP] - \fBtools\fP: fix usage of inherited -fPIC and -fPIE (Jens) \fR#1340\fP
.IP "\(bu" 2
[\fR\fR0efb8fb34b\fP\fP] - **(SEMVER-MAJOR)** \fBwin\fP: support running in VS Command Prompt (João Reis) \fR#1762\fP
.IP "\(bu" 2
[\fR\fR360ddbdf3a\fP\fP] - **(SEMVER-MAJOR)** \fBwin\fP: add support for Visual Studio 2019 (João Reis) \fR#1762\fP
.IP "\(bu" 2
[\fR\fR8f43f68275\fP\fP] - **(SEMVER-MAJOR)** \fBwin\fP: detect all VS versions in node-gyp (João Reis) \fR#1762\fP
.IP "\(bu" 2
[\fR\fR7fe4095974\fP\fP] - **(SEMVER-MAJOR)** \fBwin\fP: generic Visual Studio 2017 detection (João Reis) \fR#1762\fP
.IP "\(bu" 2
[\fR\fR7a71d68bce\fP\fP] - \fBwin\fP: use msbuild from the configure stage (Bartosz Sosnowski) \fR#1654\fP
.IP "\(bu" 2
[\fR\fRd3b21220a0\fP\fP] - \fBwin\fP: fix delay-load hook for electron 4 (Andy Dill)
.IP "\(bu" 2
[\fR\fR81f3a92338\fP\fP] - Update list of Node\&.js versions to test against\&. (Ben Noordhuis) \fR#1670\fP
.IP "\(bu" 2
[\fR\fR4748f6ab75\fP\fP] - Remove deprecated compatibility code\&. (Ben Noordhuis) \fR#1670\fP
.IP "\(bu" 2
[\fR\fR45e3221fd4\fP\fP] - Remove an outdated workaround for Python 2\&.4 (cclauss) \fR#1650\fP
.IP "\(bu" 2
[\fR\fR721dc7d314\fP\fP] - Add ARM64 to MSBuild /Platform logic (Jon Kunkee) \fR#1655\fP
.IP "\(bu" 2
[\fR\fRa5b7410497\fP\fP] - Add ESLint no-unused-vars rule (Jon Moss) \fR#1497\fP
.PP
.SH "v4\&.0\&.0 2019-04-24"
.PP
.IP "\(bu" 2
[\fR\fRceed5cbe10\fP\fP] - \fBdeps\fP: updated tar package version to 4\&.4\&.8 (Pobegaylo Maksim) \fR#1713\fP
.IP "\(bu" 2
[\fR\fR374519e066\fP\fP] - **(SEMVER-MAJOR)** Upgrade to tar v3 (isaacs) \fR#1212\fP
.IP "\(bu" 2
[\fR\fRe6699d13cd\fP\fP] - \fBtest\fP: fix addon test for Node\&.js 12 and V8 7\&.4 (Richard Lau) \fR#1705\fP
.IP "\(bu" 2
[\fR\fR0c6bf530a0\fP\fP] - \fBlib\fP: use print() for python version detection (GreenAddress) \fR#1534\fP
.PP
.SH "v3\&.8\&.0 2018-08-09"
.PP
.IP "\(bu" 2
[\fR\fRc5929cb4fe\fP\fP] - \fBdoc\fP: update Xcode preferences tab name\&. (Ivan Daniluk) \fR#1330\fP
.IP "\(bu" 2
[\fR\fR8b488da8b9\fP\fP] - \fBdoc\fP: update link to commit guidelines (Jonas Hermsmeier) \fR#1456\fP
.IP "\(bu" 2
[\fR\fRb4fe8c16f9\fP\fP] - \fBdoc\fP: fix visual studio links (Bartosz Sosnowski) \fR#1490\fP
.IP "\(bu" 2
[\fR\fR536759c7e9\fP\fP] - \fBconfigure\fP: use sys\&.version_info to get python version (Yang Guo) \fR#1504\fP
.IP "\(bu" 2
[\fR\fR94c39c604e\fP\fP] - \fBgyp\fP: fix ninja build failure (GYP patch) (Daniel Bevenius) \fRnodejs/node#12484\fP
.IP "\(bu" 2
[\fR\fRe8ea74e0fa\fP\fP] - \fBtools\fP: patch gyp to avoid xcrun errors (Ujjwal Sharma) \fRnodejs/node#21520\fP
.IP "\(bu" 2
[\fR\fRea9aff44f2\fP\fP] - \fBtools\fP: fix 'the the' typos in comments (Masashi Hirano) \fRnodejs/node#20716\fP
.IP "\(bu" 2
[\fR\fR207e5aa4fd\fP\fP] - \fBgyp\fP: implement LD/LDXX for ninja and FIPS (Sam Roberts)
.IP "\(bu" 2
[\fR\fRb416c5f4b7\fP\fP] - \fBgyp\fP: enable cctest to use objects (gyp part) (Daniel Bevenius) \fRnodejs/node#12450\fP
.IP "\(bu" 2
[\fR\fR40692d016b\fP\fP] - \fBgyp\fP: add compile_commands\&.json gyp generator (Ben Noordhuis) \fRnodejs/node#12450\fP
.IP "\(bu" 2
[\fR\fRfc3c4e2b10\fP\fP] - \fBgyp\fP: float gyp patch for long filenames (Anna Henningsen) \fRnodejs/node#7963\fP
.IP "\(bu" 2
[\fR\fR8aedbfdef6\fP\fP] - \fBgyp\fP: backport GYP fix to fix AIX shared suffix (Stewart Addison)
.IP "\(bu" 2
[\fR\fR6cd84b84fc\fP\fP] - \fBtest\fP: formatting and minor fixes for execFileSync replacement (Rod Vagg) \fR#1521\fP
.IP "\(bu" 2
[\fR\fR60e421363f\fP\fP] - \fBtest\fP: added test/processExecSync\&.js for when execFileSync is not available\&. (Rohit Hazra) \fR#1492\fP
.IP "\(bu" 2
[\fR\fR969447c5bd\fP\fP] - \fBdeps\fP: bump request to 2\&.8\&.7, fixes heok/hawk issues (Rohit Hazra) \fR#1492\fP
.IP "\(bu" 2
[\fR\fR340403ccfe\fP\fP] - \fBwin\fP: improve parsing of SDK version (Alessandro Vergani) \fR#1516\fP
.PP
.SH "v3\&.7\&.0 2018-06-08"
.PP
.IP "\(bu" 2
[\fR\fR84cea7b30d\fP\fP] - Remove unused gyp test scripts\&. (Ben Noordhuis) \fR#1458\fP
.IP "\(bu" 2
[\fR\fR0540e4ec63\fP\fP] - \fBgyp\fP: escape spaces in filenames in make generator (Jeff Senn) \fR#1436\fP
.IP "\(bu" 2
[\fR\fR88fc6fa0ec\fP\fP] - Drop dependency on minimatch\&. (Brian Woodward) \fR#1158\fP
.IP "\(bu" 2
[\fR\fR1e203c5148\fP\fP] - Fix include path when pointing to Node\&.js source (Richard Lau) \fR#1055\fP
.IP "\(bu" 2
[\fR\fR53d8cb967c\fP\fP] - Prefix build targets with /t: on Windows (Natalie Wolfe) \fR#1164\fP
.IP "\(bu" 2
[\fR\fR53a5f8ff38\fP\fP] - \fBgyp\fP: add support for \&.mm files to msvs generator (Julien Racle) \fR#1167\fP
.IP "\(bu" 2
[\fR\fRdd8561e528\fP\fP] - \fBzos\fP: don't use universal-new-lines mode (John Barboza) \fR#1451\fP
.IP "\(bu" 2
[\fR\fRe5a69010ed\fP\fP] - \fBzos\fP: add search locations for libnode\&.x (John Barboza) \fR#1451\fP
.IP "\(bu" 2
[\fR\fR79febace53\fP\fP] - \fBdoc\fP: update macOS information in README (Josh Parnham) \fR#1323\fP
.IP "\(bu" 2
[\fR\fR9425448945\fP\fP] - \fBgyp\fP: don't print xcodebuild not found errors (Gibson Fahnestock) \fR#1370\fP
.IP "\(bu" 2
[\fR\fR6f1286f5b2\fP\fP] - Fix infinite install loop\&. (Ben Noordhuis) \fR#1384\fP
.IP "\(bu" 2
[\fR\fR2580b9139e\fP\fP] - Update \fR--nodedir\fP description in README\&. (Ben Noordhuis) \fR#1372\fP
.IP "\(bu" 2
[\fR\fRa61360391a\fP\fP] - Update README with another way to install on windows (JeffAtDeere) \fR#1352\fP
.IP "\(bu" 2
[\fR\fR47496bf6dc\fP\fP] - Fix IndexError when parsing GYP files\&. (Ben Noordhuis) \fR#1267\fP
.IP "\(bu" 2
[\fR\fRb2024dee7b\fP\fP] - \fBzos\fP: support platform (John Barboza) \fR#1276\fP
.IP "\(bu" 2
[\fR\fR90d86512f4\fP\fP] - \fBwin\fP: run PS with \fR-NoProfile\fP (Refael Ackermann) \fR#1292\fP
.IP "\(bu" 2
[\fR\fR2da5f86ef7\fP\fP] - \fBdoc\fP: add github PR and Issue templates (Gibson Fahnestock) \fR#1228\fP
.IP "\(bu" 2
[\fR\fRa46a770d68\fP\fP] - \fBdoc\fP: update proposed DCO and CoC (Mikeal Rogers) \fR#1229\fP
.IP "\(bu" 2
[\fR\fR7e803d58e0\fP\fP] - \fBdoc\fP: headerify the Install instructions (Nick Schonning) \fR#1225\fP
.IP "\(bu" 2
[\fR\fRf27599193a\fP\fP] - \fBgyp\fP: update xml string encoding conversion (Liu Chao) \fR#1203\fP
.IP "\(bu" 2
[\fR\fR0a07e481f7\fP\fP] - \fBconfigure\fP: don't set ensure if tarball is set (Gibson Fahnestock) \fR#1220\fP
.PP
.SH "v3\&.6\&.3 2018-06-08"
.PP
.IP "\(bu" 2
[\fR\fR90cd2e8da9\fP\fP] - \fBgyp\fP: fix regex to match multi-digit versions (Jonas Hermsmeier) \fR#1455\fP
.IP "\(bu" 2
[\fR\fR7900122337\fP\fP] - deps: pin \fRrequest\fP version range (Refael Ackerman) \fR#1300\fP
.PP
.SH "v3\&.6\&.2 2017-06-01"
.PP
.IP "\(bu" 2
[\fR\fR72afdd62cd\fP\fP] - \fBbuild\fP: rename copyNodeLib() to doBuild() (Liu Chao) \fR#1206\fP
.IP "\(bu" 2
[\fR\fRbad903ac70\fP\fP] - \fBwin\fP: more robust parsing of SDK version (Refael Ackermann) \fR#1198\fP
.IP "\(bu" 2
[\fR\fR241752f381\fP\fP] - Log dist-url\&. (Ben Noordhuis) \fR#1170\fP
.IP "\(bu" 2
[\fR\fR386746c7d1\fP\fP] - \fBconfigure\fP: use full path in node_lib_file GYP var (Pavel Medvedev) \fR#964\fP
.IP "\(bu" 2
[\fR\fR0913b2dd99\fP\fP] - \fBbuild, win\fP: use target_arch to link with node\&.lib (Pavel Medvedev) \fR#964\fP
.IP "\(bu" 2
[\fR\fRc307b302f7\fP\fP] - \fBdoc\fP: blorb about setting \fRnpm_config_OPTION_NAME\fP (Refael Ackermann) \fR#1185\fP
.PP
.SH "v3\&.6\&.1 2017-04-30"
.PP
.IP "\(bu" 2
[\fR\fR49801716c2\fP\fP] - \fBtest\fP: fix test-find-python on v0\&.10\&.x buildbot\&. (Ben Noordhuis) \fR#1172\fP
.IP "\(bu" 2
[\fR\fRa83a3801fc\fP\fP] - \fBtest\fP: fix test/test-configure-python on AIX (Richard Lau) \fR#1131\fP
.IP "\(bu" 2
[\fR\fR8a767145c9\fP\fP] - \fBgyp\fP: Revert quote_cmd workaround (Kunal Pathak) \fR#1153\fP
.IP "\(bu" 2
[\fR\fRc09cf7671e\fP\fP] - \fBdoc\fP: add a note for using \fRconfigure\fP on Windows (Vse Mozhet Byt) \fR#1152\fP
.IP "\(bu" 2
[\fR\fRda9cb5f411\fP\fP] - Delete superfluous \&.patch files\&. (Ben Noordhuis) \fR#1122\fP
.PP
.SH "v3\&.6\&.0 2017-03-16"
.PP
.IP "\(bu" 2
[\fR\fRae141e1906\fP\fP] - \fBwin\fP: find and setup for VS2017 (Refael Ackermann) \fR#1130\fP
.IP "\(bu" 2
[\fR\fRec5fc36a80\fP\fP] - Add support to build node\&.js with chakracore for ARM\&. (Kunal Pathak) \fR#873\fP
.IP "\(bu" 2
[\fR\fRa04ea3051a\fP\fP] - Add support to build node\&.js with chakracore\&. (Kunal Pathak) \fR#873\fP
.IP "\(bu" 2
[\fR\fR93d7fa83c8\fP\fP] - Upgrade semver dependency\&. (Ben Noordhuis) \fR#1107\fP
.IP "\(bu" 2
[\fR\fRff9a6fadfd\fP\fP] - Update link of gyp as Google code is shutting down (Peter Dave Hello) \fR#1061\fP
.PP
.SH "v3\&.5\&.0 2017-01-10"
.PP
.IP "\(bu" 2
[\fR\fR762d19a39e\fP\fP] - [doc] merge History\&.md and CHANGELOG\&.md (Rod Vagg)
.IP "\(bu" 2
[\fR\fR80fc5c3d31\fP\fP] - Fix deprecated dependency warning (Simone Primarosa) \fR#1069\fP
.IP "\(bu" 2
[\fR\fR05c44944fd\fP\fP] - Open the build file with universal-newlines mode (Guy Margalit) \fR#1053\fP
.IP "\(bu" 2
[\fR\fR37ae7be114\fP\fP] - Try python launcher when stock python is python 3\&. (Ben Noordhuis) \fR#992\fP
.IP "\(bu" 2
[\fR\fRe3778d9907\fP\fP] - Add lots of findPython() tests\&. (Ben Noordhuis) \fR#992\fP
.IP "\(bu" 2
[\fR\fRafc766adf6\fP\fP] - Unset executable bit for \&.bat files (Pavel Medvedev) \fR#969\fP
.IP "\(bu" 2
[\fR\fRddac348991\fP\fP] - Use push on PYTHONPATH and add tests (Michael Hart) \fR#990\fP
.IP "\(bu" 2
[\fR\fRb182a19042\fP\fP] - \fI\fBRevert\fP\fP 'add 'path-array' dep' (Michael Hart) \fR#990\fP
.IP "\(bu" 2
[\fR\fR7c08b85c5a\fP\fP] - \fI\fBRevert\fP\fP '**configure**: use 'path-array' for PYTHONPATH' (Michael Hart) \fR#990\fP
.IP "\(bu" 2
[\fR\fR9c8d275526\fP\fP] - Add --devdir flag\&. (Ben Noordhuis) \fR#916\fP
.IP "\(bu" 2
[\fR\fRf6eab1f9e4\fP\fP] - \fBdoc\fP: add windows-build-tools to readme (Felix Rieseberg) \fR#970\fP
.PP
.SH "v3\&.4\&.0 2016-06-28"
.PP
.IP "\(bu" 2
[\fR\fRce5fd04e94\fP\fP] - \fBdeps\fP: update minimatch version (delphiactual) \fR#961\fP
.IP "\(bu" 2
[\fR\fR77383ddd85\fP\fP] - Replace fs\&.accessSync call to fs\&.statSync (Richard Lau) \fR#955\fP
.IP "\(bu" 2
[\fR\fR0dba4bda57\fP\fP] - \fBtest\fP: add simple addon test (Richard Lau) \fR#955\fP
.IP "\(bu" 2
[\fR\fRc4344b3889\fP\fP] - \fBdoc\fP: add --target option to README (Gibson Fahnestock) \fR#958\fP
.IP "\(bu" 2
[\fR\fRcc778e9215\fP\fP] - Override BUILDING_UV_SHARED, BUILDING_V8_SHARED\&. (Ben Noordhuis) \fR#915\fP
.IP "\(bu" 2
[\fR\fRaf35b2ad32\fP\fP] - Move VC++ Build Tools to Build Tools landing page\&. (Andrew Pardoe) \fR#953\fP
.IP "\(bu" 2
[\fR\fRf31482e226\fP\fP] - \fBwin\fP: work around __pfnDliNotifyHook2 type change (Alexis Campailla) \fR#952\fP
.IP "\(bu" 2
[\fR\fR3df8222fa5\fP\fP] - Allow for npmlog@3\&.x (Rebecca Turner) \fR#950\fP
.IP "\(bu" 2
[\fR\fRa4fa07b390\fP\fP] - More verbose error on locating msbuild\&.exe failure\&. (Mateusz Jaworski) \fR#930\fP
.IP "\(bu" 2
[\fR\fR4ee31329e0\fP\fP] - \fBdoc\fP: add command options to README\&.md (Gibson Fahnestock) \fR#937\fP
.IP "\(bu" 2
[\fR\fRc8c7ca86b9\fP\fP] - Add --silent option for zero output\&. (Gibson Fahnestock) \fR#937\fP
.IP "\(bu" 2
[\fR\fRac29d23a7c\fP\fP] - Upgrade to glob@7\&.0\&.3\&. (Ben Noordhuis) \fR#943\fP
.IP "\(bu" 2
[\fR\fR15fd56be3d\fP\fP] - Enable V8 deprecation warnings for native modules (Matt Loring) \fR#920\fP
.IP "\(bu" 2
[\fR\fR7f1c1b960c\fP\fP] - \fBgyp\fP: improvements for android generator (Robert Chiras) \fR#935\fP
.IP "\(bu" 2
[\fR\fR088082766c\fP\fP] - Update Windows install instructions (Sara Itani) \fR#867\fP
.IP "\(bu" 2
[\fR\fR625c1515f9\fP\fP] - \fBgyp\fP: inherit CC/CXX for CC/CXX\&.host (Johan Bergström) \fR#908\fP
.IP "\(bu" 2
[\fR\fR3bcb1720e4\fP\fP] - Add support for the Python launcher on Windows (Patrick Westerhoff) [#894](https://github.com/nodejs/node-gyp/pull/894
.PP
.SH "v3\&.3\&.1 2016-03-04"
.PP
.IP "\(bu" 2
[\fR\fRa981ef847a\fP\fP] - \fBgyp\fP: fix android generator (Robert Chiras) \fR#889\fP
.PP
.SH "v3\&.3\&.0 2016-02-16"
.PP
.IP "\(bu" 2
[\fR\fR818d854a4d\fP\fP] - Introduce NODEJS_ORG_MIRROR and IOJS_ORG_MIRROR (Rod Vagg) \fR#878\fP
.IP "\(bu" 2
[\fR\fRd1e4cc4b62\fP\fP] - **(SEMVER-MINOR)** Download headers tarball for ~0\&.12\&.10 || ~0\&.10\&.42 (Rod Vagg) \fR#877\fP
.IP "\(bu" 2
[\fR\fR6e28ad1bea\fP\fP] - Allow for npmlog@2\&.x (Rebecca Turner) \fR#861\fP
.IP "\(bu" 2
[\fR\fR07371e5812\fP\fP] - Use -fPIC for NetBSD\&. (Marcin Cieślak) \fR#856\fP
.IP "\(bu" 2
[\fR\fR8c4b0ffa50\fP\fP] - **(SEMVER-MINOR)** Add --cafile command line option\&. (Ben Noordhuis) \fR#837\fP
.IP "\(bu" 2
[\fR\fRb3ad43498e\fP\fP] - **(SEMVER-MINOR)** Make download() function testable\&. (Ben Noordhuis) \fR#837\fP
.PP
.SH "v3\&.2\&.1 2015-12-03"
.PP
.IP "\(bu" 2
[\fR\fRab89b477c4\fP\fP] - Upgrade gyp to b3cef02\&. (Ben Noordhuis) \fR#831\fP
.IP "\(bu" 2
[\fR\fR90078ecb17\fP\fP] - Define WIN32_LEAN_AND_MEAN conditionally\&. (Ben Noordhuis) \fR#824\fP
.PP
.SH "v3\&.2\&.0 2015-11-25"
.PP
.IP "\(bu" 2
[\fR\fR268f1ca4c7\fP\fP] - Use result of \fRwhich\fP when searching for python\&. (Refael Ackermann) \fR#668\fP
.IP "\(bu" 2
[\fR\fR817ed9bd78\fP\fP] - Add test for python executable search logic\&. (Ben Noordhuis) \fR#756\fP
.IP "\(bu" 2
[\fR\fR0e2dfda1f3\fP\fP] - Fix test/test-options when run through \fRnpm test\fP\&. (Ben Noordhuis) \fR#755\fP
.IP "\(bu" 2
[\fR\fR9bfa0876b4\fP\fP] - Add support for AIX (Michael Dawson) \fR#753\fP
.IP "\(bu" 2
[\fR\fRa8d441a0a2\fP\fP] - Update README for Windows 10 support\&. (Jason Williams) \fR#766\fP
.IP "\(bu" 2
[\fR\fRd1d6015276\fP\fP] - Update broken links and switch to HTTPS\&. (andrew morton)
.PP
.SH "v3\&.1\&.0 2015-11-14"
.PP
.IP "\(bu" 2
[\fR\fR9049241f91\fP\fP] - \fBgyp\fP: don't use links at all, just copy the files instead (Nathan Zadoks)
.IP "\(bu" 2
[\fR\fR8ef90348d1\fP\fP] - \fBgyp\fP: apply https://codereview.chromium.org/11361103/ (Nathan Rajlich)
.IP "\(bu" 2
[\fR\fRa2ed0df84e\fP\fP] - \fBgyp\fP: always install into $PRODUCT_DIR (Nathan Rajlich)
.IP "\(bu" 2
[\fR\fRcc8b2fa83e\fP\fP] - Update gyp to b3cef02\&. (Imran Iqbal) \fR#781\fP
.IP "\(bu" 2
[\fR\fRf5d86eb84e\fP\fP] - Update to tar@2\&.0\&.0\&. (Edgar Muentes) \fR#797\fP
.IP "\(bu" 2
[\fR\fR2ac7de02c4\fP\fP] - Fix infinite loop with zero-length options\&. (Ben Noordhuis) \fR#745\fP
.IP "\(bu" 2
[\fR\fR101bed639b\fP\fP] - This platform value came from debian package, and now the value (Jérémy Lal) \fR#738\fP
.PP
.SH "v3\&.0\&.3 2015-09-14"
.PP
.IP "\(bu" 2
[\fR\fRad827cda30\fP\fP] - tarballUrl global and && when checking for iojs (Lars-Magnus Skog) \fR#729\fP
.PP
.SH "v3\&.0\&.2 2015-09-12"
.PP
.IP "\(bu" 2
[\fR\fR6e8c3bf3c6\fP\fP] - add back support for passing additional cmdline args (Rod Vagg) \fR#723\fP
.IP "\(bu" 2
[\fR\fRff82f2f3b9\fP\fP] - fixed broken link in docs to Visual Studio 2013 download (simon-p-r) \fR#722\fP
.PP
.SH "v3\&.0\&.1 2015-09-08"
.PP
.IP "\(bu" 2
[\fR\fR846337e36b\fP\fP] - normalise versions for target == this comparison (Rod Vagg) \fR#716\fP
.PP
.SH "v3\&.0\&.0 2015-09-08"
.PP
.IP "\(bu" 2
[\fR\fR9720d0373c\fP\fP] - remove node_modules from tree (Rod Vagg) \fR#711\fP
.IP "\(bu" 2
[\fR\fR6dcf220db7\fP\fP] - test version major directly, don't use semver\&.satisfies() (Rod Vagg) \fR#711\fP
.IP "\(bu" 2
[\fR\fR938dd18d1c\fP\fP] - refactor for clarity, fix dist-url, add env var dist-url functionality (Rod Vagg) \fR#711\fP
.IP "\(bu" 2
[\fR\fR9e9df66a06\fP\fP] - use process\&.release, make aware of io\&.js & node v4 differences (Rod Vagg) \fR#711\fP
.IP "\(bu" 2
[\fR\fR1ea7ed01f4\fP\fP] - \fBdeps\fP: update graceful-fs dependency to the latest (Sakthipriyan Vairamani) \fR#714\fP
.IP "\(bu" 2
[\fR\fR0fbc387b35\fP\fP] - Update repository URLs\&. (Ben Noordhuis) \fR#715\fP
.IP "\(bu" 2
[\fR\fRbbedb8868b\fP\fP] - **(SEMVER-MAJOR)** \fBwin\fP: enable delay-load hook by default (Jeremiah Senkpiel) \fR#708\fP
.IP "\(bu" 2
[\fR\fR85ed107565\fP\fP] - Merge pull request #664 from othiym23/othiym23/allow-semver-5 (Nathan Rajlich)
.IP "\(bu" 2
[\fR\fR0c720d234c\fP\fP] - allow semver@5 (Forrest L Norvell)
.PP
.SH "2\&.0\&.2 / 2015-07-14"
.PP
.IP "\(bu" 2
Use HTTPS for dist url (#656, @SonicHedgehog)
.IP "\(bu" 2
Merge pull request #648 from nevosegal/master
.IP "\(bu" 2
Merge pull request #650 from magic890/patch-1
.IP "\(bu" 2
Updated Installation section on README
.IP "\(bu" 2
Updated link to gyp user documentation
.IP "\(bu" 2
Fix download error message spelling (#643, @tomxtobin)
.IP "\(bu" 2
Merge pull request #637 from lygstate/master
.IP "\(bu" 2
Set NODE_GYP_DIR for addon\&.gypi to setting absolute path for src/win_delay_load_hook\&.c, and fixes of the long relative path issue on Win32\&. Fixes #636 (#637, @lygstate)\&.
.PP
.SH "2\&.0\&.1 / 2015-05-28"
.PP
.IP "\(bu" 2
configure: try/catch the semver range\&.test() call
.IP "\(bu" 2
README: update for visual studio 2013 (#510, @samccone)
.PP
.SH "2\&.0\&.0 / 2015-05-24"
.PP
.IP "\(bu" 2
configure: check for python2 executable by default, fallback to python
.IP "\(bu" 2
configure: don't clobber existing $PYTHONPATH
.IP "\(bu" 2
configure: use 'path-array' for PYTHONPATH
.IP "\(bu" 2
gyp: fix for non-acsii userprofile name on Windows
.IP "\(bu" 2
gyp: always install into $PRODUCT_DIR
.IP "\(bu" 2
gyp: apply https://codereview.chromium.org/11361103/
.IP "\(bu" 2
gyp: don't use links at all, just copy the files instead
.IP "\(bu" 2
gyp: update gyp to e1c8fcf7
.IP "\(bu" 2
Updated README\&.md with updated Windows build info
.IP "\(bu" 2
Show URL when a download fails
.IP "\(bu" 2
package: add a 'license' field
.IP "\(bu" 2
move HMODULE m declaration to top
.IP "\(bu" 2
Only add '-undefined dynamic_lookup' to loadable_module targets
.IP "\(bu" 2
win: optionally allow node\&.exe/iojs\&.exe to be renamed
.IP "\(bu" 2
Avoid downloading shasums if using tarPath
.IP "\(bu" 2
Add target name preprocessor define: \fRNODE_GYP_MODULE_NAME\fP
.IP "\(bu" 2
Show better error message in case of bad network settings 
.PP

