.TH "md_backend_2node__modules_2fresh_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2fresh_2_h_i_s_t_o_r_y \- 0\&.5\&.2 / 2017-09-13 
.PP

.IP "\(bu" 2
Fix regression matching multiple ETags in \fRIf-None-Match\fP
.IP "\(bu" 2
perf: improve \fRIf-None-Match\fP token parsing
.PP
.SH "0\&.5\&.1 / 2017-09-11"
.PP
.IP "\(bu" 2
Fix handling of modified headers with invalid dates
.IP "\(bu" 2
perf: improve ETag match loop
.PP
.SH "0\&.5\&.0 / 2017-02-21"
.PP
.IP "\(bu" 2
Fix incorrect result when \fRIf-None-Match\fP has both \fR*\fP and ETags
.IP "\(bu" 2
Fix weak \fRETag\fP matching to match spec
.IP "\(bu" 2
perf: delay reading header values until needed
.IP "\(bu" 2
perf: skip checking modified time if ETag check failed
.IP "\(bu" 2
perf: skip parsing \fRIf-None-Match\fP when no \fRETag\fP header
.IP "\(bu" 2
perf: use \fRDate\&.parse\fP instead of \fRnew Date\fP
.PP
.SH "0\&.4\&.0 / 2017-02-05"
.PP
.IP "\(bu" 2
Fix false detection of \fRno-cache\fP request directive
.IP "\(bu" 2
perf: enable strict mode
.IP "\(bu" 2
perf: hoist regular expressions
.IP "\(bu" 2
perf: remove duplicate conditional
.IP "\(bu" 2
perf: remove unnecessary boolean coercions
.PP
.SH "0\&.3\&.0 / 2015-05-12"
.PP
.IP "\(bu" 2
Add weak \fRETag\fP matching support
.PP
.SH "0\&.2\&.4 / 2014-09-07"
.PP
.IP "\(bu" 2
Support Node\&.js 0\&.6
.PP
.SH "0\&.2\&.3 / 2014-09-07"
.PP
.IP "\(bu" 2
Move repository to jshttp
.PP
.SH "0\&.2\&.2 / 2014-02-19"
.PP
.IP "\(bu" 2
Revert 'Fix for blank page on Safari reload'
.PP
.SH "0\&.2\&.1 / 2014-01-29"
.PP
.IP "\(bu" 2
Fix for blank page on Safari reload
.PP
.SH "0\&.2\&.0 / 2013-08-11"
.PP
.IP "\(bu" 2
Return stale for \fRCache-Control: no-cache\fP
.PP
.SH "0\&.1\&.0 / 2012-06-15"
.PP
.IP "\(bu" 2
Add \fRIf-None-Match: *\fP support
.PP
.SH "0\&.0\&.1 / 2012-06-10"
.PP
.IP "\(bu" 2
Initial release 
.PP

