.TH "md_backend_2node__modules_2has-symbols_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2has-symbols_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.0\&.3\fP - 2022-03-01"
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] use \fRnode/install\fP instead of \fRnode/run\fP; use \fRcodecov\fP action \fR\fR518b28f\fP\fP
.IP "\(bu" 2
[meta] add \fRbugs\fP and \fRhomepage\fP fields; reorder package\&.json \fR\fRc480b13\fP\fP
.IP "\(bu" 2
[actions] reuse common workflows \fR\fR01d0ee0\fP\fP
.IP "\(bu" 2
[actions] update codecov uploader \fR\fR6424ebe\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRtape\fP \fR\fRdfa7e7f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRsafe-publish-latest\fP, \fRtape\fP \fR\fR0c8d436\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR9026554\fP\fP
.IP "\(bu" 2
[readme] add actions and codecov badges \fR\fReaa9682\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fRtape\fP \fR\fRbc7a3ba\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fRauto-changelog\fP \fR\fR0ace00a\fP\fP
.IP "\(bu" 2
[meta] use \fRprepublishOnly\fP script for npm 7+ \fR\fR093f72b\fP\fP
.IP "\(bu" 2
[Tests] test on all 16 minors \fR\fR9b80d3d\fP\fP
.PP
.SH "\fRv1\&.0\&.2\fP - 2024-02-27"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] use a universal way to get the original Symbol \fR\fR#11\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate tests to Github Actions \fR\fR90ae798\fP\fP
.IP "\(bu" 2
[meta] do not publish github action workflow files \fR\fR29e60a1\fP\fP
.IP "\(bu" 2
[Tests] run \fRnyc\fP on all tests \fR\fR8476b91\fP\fP
.IP "\(bu" 2
[readme] fix repo URLs, remove defunct badges \fR\fR126288e\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRcore-js\fP, \fRget-own-property-symbols\fP \fR\fRd84bdfa\fP\fP
.IP "\(bu" 2
[Tests] fix linting errors \fR\fR0df3070\fP\fP
.IP "\(bu" 2
[actions] add 'Allow Edits' workflow \fR\fR1e6bc29\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRtape\fP \fR\fR36cea2a\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR1278338\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR1493254\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRcore-js\fP \fR\fRb090bf2\fP\fP
.IP "\(bu" 2
[actions] switch Automatic Rebase workflow to \fRpull_request_target\fP event \fR\fR4addb7a\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRauto-changelog\fP, \fRtape\fP \fR\fR81d0baf\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRauto-changelog\fP; add \fRaud\fP \fR\fR1a4e561\fP\fP
.IP "\(bu" 2
[readme] remove unused testling URLs \fR\fR3000941\fP\fP
.IP "\(bu" 2
[Tests] only audit prod deps \fR\fR692e974\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP \fR\fR51c946c\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2019-11-16"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] use shared travis-ci configs \fR\fRce396c9\fP\fP
.IP "\(bu" 2
[Tests] up to \fRnode\fP \fRv12\&.4\fP, \fRv11\&.15\fP, \fRv10\&.15\fP, \fRv9\&.11\fP, \fRv8\&.15\fP, \fRv7\&.10\fP, \fRv6\&.17\fP, \fRv4\&.9\fP; use \fRnvm install-latest-npm\fP \fR\fR0690732\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR2163d0b\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRcore-js\fP, \fRsafe-publish-latest\fP, \fRtape\fP \fR\fR8e0951f\fP\fP
.IP "\(bu" 2
[actions] add automatic rebasing / merge commit blocking \fR\fRb09cdb7\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRsafe-publish-latest\fP, \fRcore-js\fP, \fRget-own-property-symbols\fP, \fRtape\fP \fR\fR1dd42cd\fP\fP
.IP "\(bu" 2
[meta] create FUNDING\&.yml \fR\fRaa57a17\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRa2d8bea\fP\fP
.IP "\(bu" 2
[Tests] use \fRnpx aud\fP instead of \fRnsp\fP or \fRnpm audit\fP with hoops \fR\fR9e96cb7\fP\fP
.IP "\(bu" 2
[meta] add \fRfunding\fP field \fR\fRa0b32cf\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRsafe-publish-latest\fP \fR\fRcb9f0a5\fP\fP
.PP
.SH "v1\&.0\&.0 - 2016-09-19"
.PP
.SS "Commits"
.IP "\(bu" 2
Tests\&. \fR\fRecb6eb9\fP\fP
.IP "\(bu" 2
package\&.json \fR\fR88a337c\fP\fP
.IP "\(bu" 2
Initial commit \fR\fR42e1e55\fP\fP
.IP "\(bu" 2
Initial implementation\&. \fR\fR33f5cc6\fP\fP
.IP "\(bu" 2
read me \fR\fR01f1170\fP\fP 
.PP

