.TH "md_backend_2node__modules_2mime_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2mime_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 
.SH "v1\&.6\&.0 (24/11/2017)"
.PP
\fINo changelog for this release\&.\fP
.PP
.PP
.SH "v2\&.0\&.4 (24/11/2017)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] Switch to mime-score module for resolving extension contention issues\&. \fR#182\fP
.IP "\(bu" 2
[\fBclosed\fP] Update mime-db to 1\&.31\&.0 in v1\&.x branch \fR#181\fP
.PP
.PP
.PP
.SH "v1\&.5\&.0 (22/11/2017)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] need ES5 version ready in npm package \fR#179\fP
.IP "\(bu" 2
[\fBclosed\fP] mime-db no trace of iWork - pages / numbers / etc\&. \fR#178\fP
.IP "\(bu" 2
[\fBclosed\fP] How it works in brownser ? \fR#176\fP
.IP "\(bu" 2
[\fBclosed\fP] Missing \fR\&./Mime\fP \fR#175\fP
.IP "\(bu" 2
[\fBclosed\fP] Vulnerable Regular Expression \fR#167\fP
.PP
.PP
.PP
.SH "v2\&.0\&.3 (25/09/2017)"
.PP
\fINo changelog for this release\&.\fP
.PP
.PP
.SH "v1\&.4\&.1 (25/09/2017)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] Issue when bundling with webpack \fR#172\fP
.PP
.PP
.PP
.SH "v2\&.0\&.2 (15/09/2017)"
.PP
.IP "\(bu" 2
[\fBV2\fP] fs\&.readFileSync is not a function \fR#165\fP
.IP "\(bu" 2
[\fBclosed\fP] The extension for video/quicktime should map to \&.mov, not \&.qt \fR#164\fP
.IP "\(bu" 2
[\fBV2\fP] [v2 Feedback request] Mime class API \fR#163\fP
.IP "\(bu" 2
[\fBV2\fP] [v2 Feedback request] Resolving conflicts over extensions \fR#162\fP
.IP "\(bu" 2
[\fBV2\fP] Allow callers to load module with official, full, or no defined types\&. \fR#161\fP
.IP "\(bu" 2
[\fBV2\fP] Use 'facets' to resolve extension conflicts \fR#160\fP
.IP "\(bu" 2
[\fBV2\fP] Remove fs and path dependencies \fR#152\fP
.IP "\(bu" 2
[\fBV2\fP] Default content-type should not be application/octet-stream \fR#139\fP
.IP "\(bu" 2
[\fBV2\fP] reset mime-types \fR#124\fP
.IP "\(bu" 2
[\fBV2\fP] Extensionless paths should return null or false \fR#113\fP
.PP
.PP
.PP
.SH "v2\&.0\&.1 (14/09/2017)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] Changelog for v2\&.0 does not mention breaking changes \fR#171\fP
.IP "\(bu" 2
[\fBclosed\fP] MIME breaking with 'class' declaration as it is without 'use strict mode' \fR#170\fP
.PP
.PP
.PP
.SH "v2\&.0\&.0 (12/09/2017)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] woff and woff2 \fR#168\fP
.PP
.PP
.PP
.SH "v1\&.4\&.0 (28/08/2017)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] support for ac3 voc files \fR#159\fP
.IP "\(bu" 2
[\fBclosed\fP] Help understanding change from application/xml to text/xml \fR#158\fP
.IP "\(bu" 2
[\fBclosed\fP] no longer able to override mimetype \fR#157\fP
.IP "\(bu" 2
[\fBclosed\fP] application/vnd\&.adobe\&.photoshop \fR#147\fP
.IP "\(bu" 2
[\fBclosed\fP] Directories should appear as something other than application/octet-stream \fR#135\fP
.IP "\(bu" 2
[\fBclosed\fP] requested features \fR#131\fP
.IP "\(bu" 2
[\fBclosed\fP] Make types\&.json loading optional? \fR#129\fP
.IP "\(bu" 2
[\fBclosed\fP] Cannot find module '\&./types\&.json' \fR#120\fP
.IP "\(bu" 2
[\fBV2\fP] \&.wav files show up as 'audio/x-wav' instead of 'audio/x-wave' \fR#118\fP
.IP "\(bu" 2
[\fBclosed\fP] Don't be a pain in the ass for node community \fR#108\fP
.IP "\(bu" 2
[\fBclosed\fP] don't make default_type global \fR#78\fP
.IP "\(bu" 2
[\fBclosed\fP] mime\&.extension() fails if the content-type is parameterized \fR#74\fP
.PP
.PP
.PP
.SH "v1\&.3\&.6 (11/05/2017)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] \&.md should be text/markdown as of March 2016 \fR#154\fP
.IP "\(bu" 2
[\fBclosed\fP] Error while installing mime \fR#153\fP
.IP "\(bu" 2
[\fBclosed\fP] application/manifest+json \fR#149\fP
.IP "\(bu" 2
[\fBclosed\fP] Dynamic adaptive streaming over HTTP (DASH) file extension typo \fR#141\fP
.IP "\(bu" 2
[\fBclosed\fP] charsets image/png undefined \fR#140\fP
.IP "\(bu" 2
[\fBclosed\fP] Mime-db dependency out of date \fR#130\fP
.IP "\(bu" 2
[\fBclosed\fP] how to support plist？ \fR#126\fP
.IP "\(bu" 2
[\fBclosed\fP] how does \&.types file format look like? \fR#123\fP
.IP "\(bu" 2
[\fBclosed\fP] Feature: support for expanding MIME patterns \fR#121\fP
.IP "\(bu" 2
[\fBclosed\fP] DEBUG_MIME doesn't work \fR#117\fP
.PP
.PP
.PP
.SH "v1\&.3\&.4 (06/02/2015)"
.PP
\fINo changelog for this release\&.\fP
.PP
.PP
.SH "v1\&.3\&.3 (06/02/2015)"
.PP
\fINo changelog for this release\&.\fP
.PP
.PP
.SH "v1\&.3\&.1 (05/02/2015)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] Consider adding support for Handlebars \&.hbs file ending \fR#111\fP
.IP "\(bu" 2
[\fBclosed\fP] Consider adding support for hjson\&. \fR#110\fP
.IP "\(bu" 2
[\fBclosed\fP] Add mime type for Opus audio files \fR#94\fP
.IP "\(bu" 2
[\fBclosed\fP] Consider making the \fRRequesting New Types\fP information more visible \fR#77\fP
.PP
.PP
.PP
.SH "v1\&.3\&.0 (05/02/2015)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] Add common name? \fR#114\fP
.IP "\(bu" 2
[\fBclosed\fP] application/x-yaml \fR#104\fP
.IP "\(bu" 2
[\fBclosed\fP] Add mime type for WOFF file format 2\&.0 \fR#102\fP
.IP "\(bu" 2
[\fBclosed\fP] application/x-msi for \&.msi \fR#99\fP
.IP "\(bu" 2
[\fBclosed\fP] Add mimetype for gettext translation files \fR#98\fP
.IP "\(bu" 2
[\fBclosed\fP] collaborators \fR#88\fP
.IP "\(bu" 2
[\fBclosed\fP] getting errot in installation of mime module\&.\&.\&.any1 can help? \fR#87\fP
.IP "\(bu" 2
[\fBclosed\fP] should application/json's charset be utf8? \fR#86\fP
.IP "\(bu" 2
[\fBclosed\fP] Add 'license' and 'licenses' to package\&.json \fR#81\fP
.IP "\(bu" 2
[\fBclosed\fP] lookup with extension-less file on Windows returns wrong type \fR#68\fP
.PP
.PP
.PP
.SH "v1\&.2\&.11 (15/08/2013)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] Update mime\&.types \fR#65\fP
.IP "\(bu" 2
[\fBclosed\fP] Publish a new version \fR#63\fP
.IP "\(bu" 2
[\fBclosed\fP] README should state upfront that 'application/octet-stream' is default for unknown extension \fR#55\fP
.IP "\(bu" 2
[\fBclosed\fP] Suggested improvement to the charset API \fR#52\fP
.PP
.PP
.PP
.SH "v1\&.2\&.10 (25/07/2013)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] Mime type for woff files should be application/font-woff and not application/x-font-woff \fR#62\fP
.IP "\(bu" 2
[\fBclosed\fP] node\&.types in conflict with mime\&.types \fR#51\fP
.PP
.PP
.PP
.SH "v1\&.2\&.9 (17/01/2013)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] Please update 'mime' NPM \fR#49\fP
.IP "\(bu" 2
[\fBclosed\fP] Please add semicolon \fR#46\fP
.IP "\(bu" 2
[\fBclosed\fP] parse full mime types \fR#43\fP
.PP
.PP
.PP
.SH "v1\&.2\&.8 (10/01/2013)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] /js directory mime is application/javascript\&. Is it correct? \fR#47\fP
.IP "\(bu" 2
[\fBclosed\fP] Add mime types for lua code\&. \fR#45\fP
.PP
.PP
.PP
.SH "v1\&.2\&.7 (19/10/2012)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] cannot install 1\&.2\&.7 via npm \fR#41\fP
.IP "\(bu" 2
[\fBclosed\fP] Transfer ownership to @broofa \fR#36\fP
.IP "\(bu" 2
[\fBclosed\fP] it's wrong to set charset to UTF-8 for text \fR#30\fP
.IP "\(bu" 2
[\fBclosed\fP] Allow multiple instances of MIME types container \fR#27\fP
.PP
.PP
.PP
.SH "v1\&.2\&.5 (16/02/2012)"
.PP
.IP "\(bu" 2
[\fBclosed\fP] When looking up a types, check hasOwnProperty \fR#23\fP
.IP "\(bu" 2
[\fBclosed\fP] Bump version to 1\&.2\&.2 \fR#18\fP
.IP "\(bu" 2
[\fBclosed\fP] No license \fR#16\fP
.IP "\(bu" 2
[\fBclosed\fP] Some types missing that are used by html5/css3 \fR#13\fP
.IP "\(bu" 2
[\fBclosed\fP] npm install fails for 1\&.2\&.1 \fR#12\fP
.IP "\(bu" 2
[\fBclosed\fP] image/pjpeg + image/x-png \fR#10\fP
.IP "\(bu" 2
[\fBclosed\fP] symlink \fR#8\fP
.IP "\(bu" 2
[\fBclosed\fP] gzip \fR#2\fP
.IP "\(bu" 2
[\fBclosed\fP] ALL CAPS filenames return incorrect mime type \fR#1\fP 
.PP

