.TH "md_backend_2node__modules_2prebuild-install_2_c_o_n_t_r_i_b_u_t_i_n_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2prebuild-install_2_c_o_n_t_r_i_b_u_t_i_n_g \- Contributing to prebuild 
.PP

.IP "\(bu" 2
no commits direct to master
.IP "\(bu" 2
all commits as pull requests (one or several per PR)
.IP "\(bu" 2
each commit solves one identifiable problem
.IP "\(bu" 2
never merge one's own PRs, another contributor does this 
.PP

