.TH "md_backend_2node__modules_2content-type_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2content-type_2_h_i_s_t_o_r_y \- 1\&.0\&.5 / 2023-01-29 
.PP

.IP "\(bu" 2
perf: skip value escaping when unnecessary
.PP
.SH "1\&.0\&.4 / 2017-09-11"
.PP
.IP "\(bu" 2
perf: skip parameter parsing when no parameters
.PP
.SH "1\&.0\&.3 / 2017-09-10"
.PP
.IP "\(bu" 2
perf: remove argument reassignment
.PP
.SH "1\&.0\&.2 / 2016-05-09"
.PP
.IP "\(bu" 2
perf: enable strict mode
.PP
.SH "1\&.0\&.1 / 2015-02-13"
.PP
.IP "\(bu" 2
Improve missing \fRContent-Type\fP header error message
.PP
.SH "1\&.0\&.0 / 2015-02-01"
.PP
.IP "\(bu" 2
Initial implementation, derived from \fRmedia-typer@0\&.3\&.0\fP 
.PP

