.TH "md_backend_2node__modules_2node-gyp_2gyp_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2node-gyp_2gyp_2_r_e_a_d_m_e \- GYP can Generate Your Projects\&. 
.PP
Documents are available at \fRgyp\&.gsrc\&.io\fP, or you can check out \fRmd-pages\fP branch to read those documents offline\&.
.PP
\fBgyp-next\fP is \fRreleased\fP to the \fR\fBPython Packaging Index\fP\fP (PyPI) and can be installed with the command:
.IP "\(bu" 2
\fRpython3 -m pip install gyp-next\fP 
.PP

