.TH "md_backend_2node__modules_2vary_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2vary_2_h_i_s_t_o_r_y \- 1\&.1\&.2 / 2017-09-23 
.PP

.IP "\(bu" 2
perf: improve header token parsing speed
.PP
.SH "1\&.1\&.1 / 2017-03-20"
.PP
.IP "\(bu" 2
perf: hoist regular expression
.PP
.SH "1\&.1\&.0 / 2015-09-29"
.PP
.IP "\(bu" 2
Only accept valid field names in the \fRfield\fP argument
.IP "  \(bu" 4
Ensures the resulting string is a valid HTTP header value
.PP

.PP
.SH "1\&.0\&.1 / 2015-07-08"
.PP
.IP "\(bu" 2
Fix setting empty header from empty \fRfield\fP
.IP "\(bu" 2
perf: enable strict mode
.IP "\(bu" 2
perf: remove argument reassignments
.PP
.SH "1\&.0\&.0 / 2014-08-10"
.PP
.IP "\(bu" 2
Accept valid \fRVary\fP header string as \fRfield\fP
.IP "\(bu" 2
Add \fRvary\&.append\fP for low-level string manipulation
.IP "\(bu" 2
Move to \fRjshttp\fP orgainzation
.PP
.SH "0\&.1\&.0 / 2014-06-05"
.PP
.IP "\(bu" 2
Support array of fields to set
.PP
.SH "0\&.0\&.0 / 2014-06-04"
.PP
.IP "\(bu" 2
Initial release 
.PP

