.TH "md_backend_2node__modules_2node-gyp_2gyp_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2node-gyp_2gyp_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 
.SH "\fR0\&.10\&.0\fP (2021-08-26)"
.PP
.SS "Features"
.IP "\(bu" 2
\fBmsvs:\fP add support for Visual Studio 2022 (\fR#124\fP) (\fR4bd9215\fP)
.PP
.SS "\fR0\&.9\&.6\fP (2021-08-23)"
.SS "Bug Fixes"
.IP "\(bu" 2
align flake8 test (\fR#122\fP) (\fRf1faa8d\fP)
.IP "\(bu" 2
\fBmsvs:\fP fix paths again in action command arguments (\fR#121\fP) (\fR7159dfb\fP)
.PP
.SS "\fR0\&.9\&.5\fP (2021-08-18)"
.SS "Bug Fixes"
.IP "\(bu" 2
add python 3\&.6 to node-gyp integration test (\fR3462d4c\fP)
.IP "\(bu" 2
revert for windows compatibility (\fRd078e7d\fP)
.IP "\(bu" 2
support msvs_quote_cmd in ninja generator (\fR#117\fP) (\fR46486ac\fP)
.PP
.SS "\fR0\&.9\&.4\fP (2021-08-09)"
.SS "Bug Fixes"
.IP "\(bu" 2
\&.S is an extension for asm file on Windows (\fR#115\fP) (\fRd2fad44\fP)
.PP
.SS "\fR0\&.9\&.3\fP (2021-07-07)"
.SS "Bug Fixes"
.IP "\(bu" 2
build failure with ninja and Python 3 on Windows (\fR#113\fP) (\fRc172d10\fP)
.PP
.SS "\fR0\&.9\&.2\fP (2021-05-21)"
.SS "Bug Fixes"
.IP "\(bu" 2
add support of utf8 encoding (\fR#105\fP) (\fR4d0f93c\fP)
.PP
.SS "\fR0\&.9\&.1\fP (2021-05-14)"
.SS "Bug Fixes"
.IP "\(bu" 2
py lint (\fR3b6a8ee\fP)
.PP
.SH "\fR0\&.9\&.0\fP (2021-05-13)"
.PP
.SS "Features"
.IP "\(bu" 2
use LDFLAGS_host for host toolset (\fR#98\fP) (\fRbea5c7b\fP)
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
\fBmsvs\&.py\fP: remove overindentation (\fR#102\fP) (\fR3f83e99\fP)
.IP "\(bu" 2
update gyp\&.el to change case to cl-case (\fR#93\fP) (\fR13d5b66\fP)
.PP
.SS "\fR0\&.8\&.1\fP (2021-02-18)"
.SS "Bug Fixes"
.IP "\(bu" 2
update shebang lines from python to python3 (\fR#94\fP) (\fRa1b0d41\fP)
.PP
.SH "\fR0\&.8\&.0\fP (2021-01-15)"
.PP
.SS "⚠ BREAKING CHANGES"
.IP "\(bu" 2
remove support for Python 2
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
revert posix build job (\fR#86\fP) (\fR39dc34f\fP)
.PP
.SS "gyp"
.IP "\(bu" 2
Remove support for Python 2 (\fR#88\fP) (\fR22e4654\fP)
.PP
.SH "\fR0\&.7\&.0\fP (2020-12-17)"
.PP
.SS "⚠ BREAKING CHANGES"
.IP "\(bu" 2
\fBmsvs:\fP On Windows, arguments passed to the 'action' commands are no longer transformed to replace slashes with backslashes\&.
.PP
.SS "Features"
.IP "\(bu" 2
\fBxcode:\fP --cross-compiling overrides arch-specific settings (\fR973bae0\fP)
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
\fBmsvs:\fP do not fix paths in action command arguments (\fRfc22f83\fP)
.IP "\(bu" 2
cmake on python 3 (\fRfd61f5f\fP)
.IP "\(bu" 2
ValueError: invalid mode: 'rU' while trying to load binding\&.gyp (\fRd0504e6\fP)
.IP "\(bu" 2
xcode cmake parsing (\fReefe8d1\fP)
.PP
.SS "\fR0\&.6\&.2\fP (2020-10-16)"
.SS "Bug Fixes"
.IP "\(bu" 2
do not rewrite absolute paths to avoid long paths (\fR#74\fP) (\fRc2ccc1a\fP)
.IP "\(bu" 2
only include MARMASM when toolset is target (\fR5a2794a\fP)
.PP
.SS "\fR0\&.6\&.1\fP (2020-10-14)"
.SS "Bug Fixes"
.IP "\(bu" 2
Correctly rename object files for absolute paths in MSVS generator\&.
.PP
.SH "\fR0\&.6\&.0\fP (2020-10-13)"
.PP
.SS "Features"
.IP "\(bu" 2
The Makefile generator will now output shared libraries directly to the product directory on all platforms (previously only macOS)\&.
.PP
.SH "\fR0\&.5\&.0\fP (2020-09-30)"
.PP
.SS "Features"
.IP "\(bu" 2
Extended compile_commands_json generator to consider more file extensions than just \fRc\fP and \fRcc\fP\&. \fRcpp\fP and \fRcxx\fP are now supported\&.
.IP "\(bu" 2
Source files with duplicate basenames are now supported\&.
.PP
.SS "Removed"
.IP "\(bu" 2
The \fR--no-duplicate-basename-check\fP option was removed\&.
.IP "\(bu" 2
The \fRmsvs_enable_marmasm\fP configuration option was removed in favor of auto-inclusion of the 'marmasm' sections for Windows on ARM\&.
.PP
.SH "\fR0\&.4\&.0\fP (2020-07-14)"
.PP
.SS "Features"
.IP "\(bu" 2
Added support for passing arbitrary architectures to Xcode builds, enables \fRarm64\fP builds\&.
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Fixed a bug on Solaris where copying archives failed\&.
.PP
.SH "\fR0\&.3\&.0\fP (2020-06-06)"
.PP
.SS "Features"
.IP "\(bu" 2
Added support for MSVC cross-compilation\&. This allows compilation on x64 for a Windows ARM target\&.
.PP
.SS "Bug Fixes"
.IP "\(bu" 2
Fixed XCode CLT version detection on macOS Catalina\&.
.PP
.SS "\fR0\&.2\&.1\fP (2020-05-05)"
.SS "Bug Fixes"
.IP "\(bu" 2
Relicensed to Node\&.js contributors\&.
.IP "\(bu" 2
Fixed Windows bug introduced in v0\&.2\&.0\&.
.PP
.SH "\fR0\&.2\&.0\fP (2020-04-06)"
.PP
This is the first release of this project, based on https://chromium.googlesource.com/external/gyp with changes made over the years in Node\&.js and node-gyp\&. 
