.TH "md_backend_2node__modules_2has-symbols_2_r_e_a_d_m_e" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2has-symbols_2_r_e_a_d_m_e \- has-symbols \*{\fR\fP\*}  
.PP
 \fR\fP \fR\fP \fR\fP \fR\fP [][license-url] \fR\fP
.PP
\fR\fP.PP
Determine if the JS environment has Symbol support\&. Supports spec, or shams\&.
.SH "Example"
.PP
.PP
.nf
var hasSymbols = require('has\-symbols');

hasSymbols() === true; // if the environment has native Symbol support\&. Not polyfillable, not forgeable\&.

var hasSymbolsKinda = require('has\-symbols/shams');
hasSymbolsKinda() === true; // if the environment has a Symbol sham that mostly follows the spec\&.
.fi
.PP
.SH "Supported Symbol shams"
.PP
.IP "\(bu" 2
get-own-property-symbols \fRnpm\fP | \fRgithub\fP
.IP "\(bu" 2
core-js \fRnpm\fP | \fRgithub\fP
.PP
.SH "Tests"
.PP
Simply clone the repo, \fRnpm install\fP, and run \fRnpm test\fP 
