.TH "md_backend_2node__modules_2methods_2_h_i_s_t_o_r_y" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2methods_2_h_i_s_t_o_r_y \- 1\&.1\&.2 / 2016-01-17 
.PP

.IP "\(bu" 2
perf: enable strict mode
.PP
.SH "1\&.1\&.1 / 2014-12-30"
.PP
.IP "\(bu" 2
Improve \fRbrowserify\fP support
.PP
.SH "1\&.1\&.0 / 2014-07-05"
.PP
.IP "\(bu" 2
Add \fRCONNECT\fP method
.PP
.SH "1\&.0\&.1 / 2014-06-02"
.PP
.IP "\(bu" 2
Fix module to work with harmony transform
.PP
.SH "1\&.0\&.0 / 2014-05-08"
.PP
.IP "\(bu" 2
Add \fRPURGE\fP method
.PP
.SH "0\&.1\&.0 / 2013-10-28"
.PP
.IP "\(bu" 2
Add \fRhttp\&.METHODS\fP support 
.PP

