.TH "md_backend_2node__modules_2set-blocking_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2set-blocking_2_c_h_a_n_g_e_l_o_g \- Change Log 
.PP
 All notable changes to this project will be documented in this file\&. See \fRstandard-version\fP for commit guidelines\&.
.PP
 
.SH "\fR2\&.0\&.0\fP (2016-05-17)"
.PP
.SS "Features"
.IP "\(bu" 2
add an isTTY check (\fR#3\fP) (\fR66ce277\fP)
.PP
.SS "BREAKING CHANGES"
.IP "\(bu" 2
stdio/stderr will not be set to blocking if isTTY === false
.PP
.PP
 
.SH "1\&.0\&.0 (2016-05-14)"
.PP
.SS "Features"
.IP "\(bu" 2
implemented shim for stream\&._handle\&.setBlocking (\fR6bde0c0\fP) 
.PP

