.TH "md_backend_2node__modules_2set-function-length_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2set-function-length_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP
 All notable changes to this project will be documented in this file\&.
.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv1\&.2\&.2\fP - 2024-03-09"
.PP
.SS "Commits"
.IP "\(bu" 2
[types] use shared config \fR\fR027032f\fP\fP
.IP "\(bu" 2
[actions] remove redundant finisher; use reusable workflow \fR\fR1fd4fb1\fP\fP
.IP "\(bu" 2
[types] use a handwritten d\&.ts file instead of emit \fR\fR01b9761\fP\fP
.IP "\(bu" 2
[Deps] update \fRdefine-data-property\fP, \fRget-intrinsic\fP, \fRhas-property-descriptors\fP \fR\fRbee8eaf\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRcall-bind\fP, \fRtape\fP \fR\fR5dae579\fP\fP
.IP "\(bu" 2
[Tests] use \fR@arethetypeswrong/cli\fP \fR\fR7e22425\fP\fP
.PP
.SH "\fRv1\&.2\&.1\fP - 2024-02-06"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fRcall-bind\fP, \fRtape\fP, \fRtypescript\fP \fR\fRd9a4601\fP\fP
.IP "\(bu" 2
[Deps] update \fRdefine-data-property\fP, \fRget-intrinsic\fP \fR\fR38d39ae\fP\fP
.IP "\(bu" 2
[Refactor] use \fRes-errors\fP, so things that only need those do not need \fRget-intrinsic\fP \fR\fRb4bfe5a\fP\fP
.PP
.SH "\fRv1\&.2\&.0\fP - 2024-01-14"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add types \fR\fRf6d9088\fP\fP
.IP "\(bu" 2
[Fix] ensure \fRenv\fP properties are always booleans \fR\fR0c42f84\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRcall-bind\fP, \fRnpmignore\fP, \fRtape\fP \fR\fR2b75f75\fP\fP
.IP "\(bu" 2
[Deps] update \fRget-intrinsic\fP, \fRhas-property-descriptors\fP \fR\fR19bf0fc\fP\fP
.IP "\(bu" 2
[meta] add \fRsideEffects\fP flag \fR\fR8bb9b78\fP\fP
.PP
.SH "\fRv1\&.1\&.1\fP - 2023-10-19"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] move \fRdefine-data-property\fP to runtime deps \fR\fR#2\fP\fP
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fRobject-inspect\fP; add missing \fRcall-bind\fP \fR\fR5aecf79\fP\fP
.PP
.SH "\fRv1\&.1\&.0\fP - 2023-10-13"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRenv\fP entry point \fR\fR475c87a\fP\fP
.IP "\(bu" 2
[Tests] add coverage with \fRnyc\fP \fR\fR14f0bf8\fP\fP
.IP "\(bu" 2
[eslint] fix linting failure \fR\fRfb516f9\fP\fP
.IP "\(bu" 2
[Deps] update \fRdefine-data-property\fP \fR\fRd727e7c\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2023-10-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRget-intrinsic\fP, since it‘s in the dep graph anyways \fR\fR278a954\fP\fP
.IP "\(bu" 2
[meta] add \fRexports\fP \fR\fR72acfe5\fP\fP
.PP
.SH "v1\&.0\&.0 - 2023-10-12"
.PP
.SS "Commits"
.IP "\(bu" 2
Initial implementation, tests, readme \fR\fRfce14e1\fP\fP
.IP "\(bu" 2
Initial commit \fR\fRca7ba85\fP\fP
.IP "\(bu" 2
npm init \fR\fR6a7e493\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRd2bf6c4\fP\fP 
.PP

