.TH "md_backend_2node__modules_2is-fullwidth-code-point_2readme" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2is-fullwidth-code-point_2readme \- is-fullwidth-code-point \fR\fP 
.PP
 
.PP
.RS 4
Check if the character represented by a given \fRUnicode code point\fP is \fRfullwidth\fP 
.RE
.PP
.SH "Install"
.PP
.PP
.nf
$ npm install is\-fullwidth\-code\-point
.fi
.PP
.SH "Usage"
.PP
.PP
.nf
const isFullwidthCodePoint = require('is\-fullwidth\-code\-point');

isFullwidthCodePoint('谢'\&.codePointAt(0));
//=> true

isFullwidthCodePoint('a'\&.codePointAt(0));
//=> false
.fi
.PP
.SH "API"
.PP
.SS "isFullwidthCodePoint(codePoint)"
.SS "codePoint"
Type: \fRnumber\fP
.PP
The \fRcode point\fP of a character\&.
.SH "License"
.PP
MIT © \fRSindre Sorhus\fP 
