.TH "md_backend_2node__modules_2debug_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2debug_2_c_h_a_n_g_e_l_o_g \- 2\&.6\&.9 / 2017-09-22 
.PP

.IP "\(bu" 2
remove ReDoS regexp in o formatter (#504)
.PP
.SH "2\&.6\&.8 / 2017-05-18"
.PP
.IP "\(bu" 2
Fix: Check for undefined on browser globals (#462, @marbemac)
.PP
.SH "2\&.6\&.7 / 2017-05-16"
.PP
.IP "\(bu" 2
Fix: Update ms to 2\&.0\&.0 to fix regular expression denial of service vulnerability (#458, @hubdotcom)
.IP "\(bu" 2
Fix: Inline extend function in node implementation (#452, @dougwilson)
.IP "\(bu" 2
Docs: Fix typo (#455, @msasad)
.PP
.SH "2\&.6\&.5 / 2017-04-27"
.PP
.IP "\(bu" 2
Fix: null reference check on window\&.documentElement\&.style\&.WebkitAppearance (#447, @thebigredgeek)
.IP "\(bu" 2
Misc: clean up browser reference checks (#447, @thebigredgeek)
.IP "\(bu" 2
Misc: add npm-debug\&.log to \&.gitignore (@thebigredgeek)
.PP
.SH "2\&.6\&.4 / 2017-04-20"
.PP
.IP "\(bu" 2
Fix: bug that would occure if process\&.env\&.DEBUG is a non-string value\&. (#444, @LucianBuzzo)
.IP "\(bu" 2
Chore: ignore bower\&.json in npm installations\&. (#437, @joaovieira)
.IP "\(bu" 2
Misc: update 'ms' to v0\&.7\&.3 (@tootallnate)
.PP
.SH "2\&.6\&.3 / 2017-03-13"
.PP
.IP "\(bu" 2
Fix: Electron reference to \fRprocess\&.env\&.DEBUG\fP (#431, @paulcbetts)
.IP "\(bu" 2
Docs: Changelog fix (@thebigredgeek)
.PP
.SH "2\&.6\&.2 / 2017-03-10"
.PP
.IP "\(bu" 2
Fix: DEBUG_MAX_ARRAY_LENGTH (#420, @slavaGanzin)
.IP "\(bu" 2
Docs: Add backers and sponsors from Open Collective (#422, @piamancini)
.IP "\(bu" 2
Docs: Add Slackin invite badge (@tootallnate)
.PP
.SH "2\&.6\&.1 / 2017-02-10"
.PP
.IP "\(bu" 2
Fix: Module's \fRexport default\fP syntax fix for IE8 \fRExpected identifier\fP error
.IP "\(bu" 2
Fix: Whitelist DEBUG_FD for values 1 and 2 only (#415, @pi0)
.IP "\(bu" 2
Fix: IE8 'Expected identifier' error (#414, @vgoma)
.IP "\(bu" 2
Fix: Namespaces would not disable once enabled (#409, @musikov)
.PP
.SH "2\&.6\&.0 / 2016-12-28"
.PP
.IP "\(bu" 2
Fix: added better null pointer checks for browser useColors (@thebigredgeek)
.IP "\(bu" 2
Improvement: removed explicit \fRwindow\&.debug\fP export (#404, @tootallnate)
.IP "\(bu" 2
Improvement: deprecated \fRDEBUG_FD\fP environment variable (#405, @tootallnate)
.PP
.SH "2\&.5\&.2 / 2016-12-25"
.PP
.IP "\(bu" 2
Fix: reference error on window within webworkers (#393, @KlausTrainer)
.IP "\(bu" 2
Docs: fixed README typo (#391, @lurch)
.IP "\(bu" 2
Docs: added notice about v3 api discussion (@thebigredgeek)
.PP
.SH "2\&.5\&.1 / 2016-12-20"
.PP
.IP "\(bu" 2
Fix: babel-core compatibility
.PP
.SH "2\&.5\&.0 / 2016-12-20"
.PP
.IP "\(bu" 2
Fix: wrong reference in bower file (@thebigredgeek)
.IP "\(bu" 2
Fix: webworker compatibility (@thebigredgeek)
.IP "\(bu" 2
Fix: output formatting issue (#388, @kribblo)
.IP "\(bu" 2
Fix: babel-loader compatibility (#383, @escwald)
.IP "\(bu" 2
Misc: removed built asset from repo and publications (@thebigredgeek)
.IP "\(bu" 2
Misc: moved source files to /src (#378, @yamikuronue)
.IP "\(bu" 2
Test: added karma integration and replaced babel with browserify for browser tests (#378, @yamikuronue)
.IP "\(bu" 2
Test: coveralls integration (#378, @yamikuronue)
.IP "\(bu" 2
Docs: simplified language in the opening paragraph (#373, @yamikuronue)
.PP
.SH "2\&.4\&.5 / 2016-12-17"
.PP
.IP "\(bu" 2
Fix: \fRnavigator\fP undefined in Rhino (#376, @jochenberger)
.IP "\(bu" 2
Fix: custom log function (#379, @hsiliev)
.IP "\(bu" 2
Improvement: bit of cleanup + linting fixes (@thebigredgeek)
.IP "\(bu" 2
Improvement: rm non-maintainted \fRdist/\fP dir (#375, @freewil)
.IP "\(bu" 2
Docs: simplified language in the opening paragraph\&. (#373, @yamikuronue)
.PP
.SH "2\&.4\&.4 / 2016-12-14"
.PP
.IP "\(bu" 2
Fix: work around debug being loaded in preload scripts for electron (#368, @paulcbetts)
.PP
.SH "2\&.4\&.3 / 2016-12-14"
.PP
.IP "\(bu" 2
Fix: navigation\&.userAgent error for react native (#364, @escwald)
.PP
.SH "2\&.4\&.2 / 2016-12-14"
.PP
.IP "\(bu" 2
Fix: browser colors (#367, @tootallnate)
.IP "\(bu" 2
Misc: travis ci integration (@thebigredgeek)
.IP "\(bu" 2
Misc: added linting and testing boilerplate with sanity check (@thebigredgeek)
.PP
.SH "2\&.4\&.1 / 2016-12-13"
.PP
.IP "\(bu" 2
Fix: typo that broke the package (#356)
.PP
.SH "2\&.4\&.0 / 2016-12-13"
.PP
.IP "\(bu" 2
Fix: bower\&.json references unbuilt src entry point (#342, @justmatt)
.IP "\(bu" 2
Fix: revert 'handle regex special characters' (@tootallnate)
.IP "\(bu" 2
Feature: configurable util\&.inspect()\fRoptions for NodeJS (#327, @tootallnate)\fP
.IP "\(bu" 2
\fRFeature: O\fP(big O) pretty-prints objects (#322, @tootallnate)
.IP "\(bu" 2
Improvement: allow colors in workers (#335, @botverse)
.IP "\(bu" 2
Improvement: use same color for same namespace\&. (#338, @lchenay)
.PP
.SH "2\&.3\&.3 / 2016-11-09"
.PP
.IP "\(bu" 2
Fix: Catch \fRJSON\&.stringify()\fP errors (#195, Jovan Alleyne)
.IP "\(bu" 2
Fix: Returning \fRlocalStorage\fP saved values (#331, Levi Thomason)
.IP "\(bu" 2
Improvement: Don't create an empty object when no \fRprocess\fP (Nathan Rajlich)
.PP
.SH "2\&.3\&.2 / 2016-11-09"
.PP
.IP "\(bu" 2
Fix: be super-safe in index\&.js as well (@TooTallNate)
.IP "\(bu" 2
Fix: should check whether process exists (Tom Newby)
.PP
.SH "2\&.3\&.1 / 2016-11-09"
.PP
.IP "\(bu" 2
Fix: Added electron compatibility (#324, @paulcbetts)
.IP "\(bu" 2
Improvement: Added performance optimizations (@tootallnate)
.IP "\(bu" 2
Readme: Corrected PowerShell environment variable example (#252, @gimre)
.IP "\(bu" 2
Misc: Removed yarn lock file from source control (#321, @fengmk2)
.PP
.SH "2\&.3\&.0 / 2016-11-07"
.PP
.IP "\(bu" 2
Fix: Consistent placement of ms diff at end of output (#215, @gorangajic)
.IP "\(bu" 2
Fix: Escaping of regex special characters in namespace strings (#250, @zacronos)
.IP "\(bu" 2
Fix: Fixed bug causing crash on react-native (#282, @vkarpov15)
.IP "\(bu" 2
Feature: Enabled ES6+ compatible import via default export (#212 @bucaran)
.IP "\(bu" 2
Feature: Added O formatter to reflect Chrome's console\&.log capability (#279, @oncletom)
.IP "\(bu" 2
Package: Update 'ms' to 0\&.7\&.2 (#315, @DevSide)
.IP "\(bu" 2
Package: removed superfluous version property from bower\&.json (#207 @kkirsche)
.IP "\(bu" 2
Readme: fix USE_COLORS to DEBUG_COLORS
.IP "\(bu" 2
Readme: Doc fixes for format string sugar (#269, @mlucool)
.IP "\(bu" 2
Readme: Updated docs for DEBUG_FD and DEBUG_COLORS environment variables (#232, @mattlyons0)
.IP "\(bu" 2
Readme: doc fixes for PowerShell (#271 #243, @exoticknight @unreadable)
.IP "\(bu" 2
Readme: better docs for browser support (#224, @matthewmueller)
.IP "\(bu" 2
Tooling: Added yarn integration for development (#317, @thebigredgeek)
.IP "\(bu" 2
Misc: Renamed History\&.md to CHANGELOG\&.md (@thebigredgeek)
.IP "\(bu" 2
Misc: Added license file (#226 #274, @CantemoInternal @sdaitzman)
.IP "\(bu" 2
Misc: Updated contributors (@thebigredgeek)
.PP
.SH "2\&.2\&.0 / 2015-05-09"
.PP
.IP "\(bu" 2
package: update 'ms' to v0\&.7\&.1 (#202, @dougwilson)
.IP "\(bu" 2
README: add logging to file example (#193, @DanielOchoa)
.IP "\(bu" 2
README: fixed a typo (#191, @amir-s)
.IP "\(bu" 2
browser: expose \fRstorage\fP (#190, @stephenmathieson)
.IP "\(bu" 2
Makefile: add a \fRdistclean\fP target (#189, @stephenmathieson)
.PP
.SH "2\&.1\&.3 / 2015-03-13"
.PP
.IP "\(bu" 2
Updated stdout/stderr example (#186)
.IP "\(bu" 2
Updated example/stdout\&.js to match debug current behaviour
.IP "\(bu" 2
Renamed example/stderr\&.js to stdout\&.js
.IP "\(bu" 2
Update Readme\&.md (#184)
.IP "\(bu" 2
replace high intensity foreground color for bold (#182, #183)
.PP
.SH "2\&.1\&.2 / 2015-03-01"
.PP
.IP "\(bu" 2
dist: recompile
.IP "\(bu" 2
update 'ms' to v0\&.7\&.0
.IP "\(bu" 2
package: update 'browserify' to v9\&.0\&.3
.IP "\(bu" 2
component: fix 'ms\&.js' repo location
.IP "\(bu" 2
changed bower package name
.IP "\(bu" 2
updated documentation about using debug in a browser
.IP "\(bu" 2
fix: security error on safari (#167, #168, @yields)
.PP
.SH "2\&.1\&.1 / 2014-12-29"
.PP
.IP "\(bu" 2
browser: use \fRtypeof\fP to check for \fRconsole\fP existence
.IP "\(bu" 2
browser: check for \fRconsole\&.log\fP truthiness (fix IE 8/9)
.IP "\(bu" 2
browser: add support for Chrome apps
.IP "\(bu" 2
Readme: added Windows usage remarks
.IP "\(bu" 2
Add \fRbower\&.json\fP to properly support bower install
.PP
.SH "2\&.1\&.0 / 2014-10-15"
.PP
.IP "\(bu" 2
node: implement \fRDEBUG_FD\fP env variable support
.IP "\(bu" 2
package: update 'browserify' to v6\&.1\&.0
.IP "\(bu" 2
package: add 'license' field to package\&.json (#135, @panuhorsmalahti)
.PP
.SH "2\&.0\&.0 / 2014-09-01"
.PP
.IP "\(bu" 2
package: update 'browserify' to v5\&.11\&.0
.IP "\(bu" 2
node: use stderr rather than stdout for logging (#29, @stephenmathieson)
.PP
.SH "1\&.0\&.4 / 2014-07-15"
.PP
.IP "\(bu" 2
dist: recompile
.IP "\(bu" 2
example: remove \fRconsole\&.info()\fP log usage
.IP "\(bu" 2
example: add 'Content-Type' UTF-8 header to browser example
.IP "\(bu" 2
browser: place c marker after the space character
.IP "\(bu" 2
browser: reset the 'content' color via \fRcolor: inherit\fP
.IP "\(bu" 2
browser: add colors support for Firefox >= v31
.IP "\(bu" 2
debug: prefer an instance \fRlog()\fP function over the global one (#119)
.IP "\(bu" 2
Readme: update documentation about styled console logs for FF v31 (#116, @wryk)
.PP
.SH "1\&.0\&.3 / 2014-07-09"
.PP
.IP "\(bu" 2
Add support for multiple wildcards in namespaces (#122, @seegno)
.IP "\(bu" 2
browser: fix lint
.PP
.SH "1\&.0\&.2 / 2014-06-10"
.PP
.IP "\(bu" 2
browser: update color palette (#113, @gscottolson)
.IP "\(bu" 2
common: make console logging function configurable (#108, @timoxley)
.IP "\(bu" 2
node: fix o colors on old node <= 0\&.8\&.x
.IP "\(bu" 2
Makefile: find node path using shell/which (#109, @timoxley)
.PP
.SH "1\&.0\&.1 / 2014-06-06"
.PP
.IP "\(bu" 2
browser: use \fRremoveItem()\fP to clear localStorage
.IP "\(bu" 2
browser, node: don't set DEBUG if namespaces is undefined (#107, @leedm777)
.IP "\(bu" 2
package: add 'contributors' section
.IP "\(bu" 2
node: fix comment typo
.IP "\(bu" 2
README: list authors
.PP
.SH "1\&.0\&.0 / 2014-06-04"
.PP
.IP "\(bu" 2
make ms diff be global, not be scope
.IP "\(bu" 2
debug: ignore empty strings in enable()
.IP "\(bu" 2
node: make DEBUG_COLORS able to disable coloring
.IP "\(bu" 2
*: export the \fRcolors\fP array
.IP "\(bu" 2
npmignore: don't publish the \fRdist\fP dir
.IP "\(bu" 2
Makefile: refactor to use browserify
.IP "\(bu" 2
package: add 'browserify' as a dev dependency
.IP "\(bu" 2
Readme: add Web Inspector Colors section
.IP "\(bu" 2
node: reset terminal color for the debug content
.IP "\(bu" 2
node: map '%o' to \fRutil\&.inspect()\fP
.IP "\(bu" 2
browser: map '%j' to \fRJSON\&.stringify()\fP
.IP "\(bu" 2
debug: add custom 'formatters'
.IP "\(bu" 2
debug: use 'ms' module for humanizing the diff
.IP "\(bu" 2
Readme: add 'bash' syntax highlighting
.IP "\(bu" 2
browser: add Firebug color support
.IP "\(bu" 2
browser: add colors for WebKit browsers
.IP "\(bu" 2
node: apply log to \fRconsole\fP
.IP "\(bu" 2
rewrite: abstract common logic for Node & browsers
.IP "\(bu" 2
add \&.jshintrc file
.PP
.SH "0\&.8\&.1 / 2014-04-14"
.PP
.IP "\(bu" 2
package: re-add the 'component' section
.PP
.SH "0\&.8\&.0 / 2014-03-30"
.PP
.IP "\(bu" 2
add \fRenable()\fP method for nodejs\&. Closes #27
.IP "\(bu" 2
change from stderr to stdout
.IP "\(bu" 2
remove unnecessary index\&.js file
.PP
.SH "0\&.7\&.4 / 2013-11-13"
.PP
.IP "\(bu" 2
remove 'browserify' key from package\&.json (fixes something in browserify)
.PP
.SH "0\&.7\&.3 / 2013-10-30"
.PP
.IP "\(bu" 2
fix: catch localStorage security error when cookies are blocked (Chrome)
.IP "\(bu" 2
add debug(err) support\&. Closes #46
.IP "\(bu" 2
add \&.browser prop to package\&.json\&. Closes #42
.PP
.SH "0\&.7\&.2 / 2013-02-06"
.PP
.IP "\(bu" 2
fix package\&.json
.IP "\(bu" 2
fix: Mobile Safari (private mode) is broken with debug
.IP "\(bu" 2
fix: Use unicode to send escape character to shell instead of octal to work with strict mode javascript
.PP
.SH "0\&.7\&.1 / 2013-02-05"
.PP
.IP "\(bu" 2
add repository URL to package\&.json
.IP "\(bu" 2
add DEBUG_COLORED to force colored output
.IP "\(bu" 2
add browserify support
.IP "\(bu" 2
fix component\&. Closes #24
.PP
.SH "0\&.7\&.0 / 2012-05-04"
.PP
.IP "\(bu" 2
Added \&.component to package\&.json
.IP "\(bu" 2
Added debug\&.component\&.js build
.PP
.SH "0\&.6\&.0 / 2012-03-16"
.PP
.IP "\(bu" 2
Added support for '-' prefix in DEBUG [Vinay Pulim]
.IP "\(bu" 2
Added \fR\&.enabled\fP flag to the node version [TooTallNate]
.PP
.SH "0\&.5\&.0 / 2012-02-02"
.PP
.IP "\(bu" 2
Added: humanize diffs\&. Closes #8
.IP "\(bu" 2
Added \fRdebug\&.disable()\fP to the CS variant
.IP "\(bu" 2
Removed padding\&. Closes #10
.IP "\(bu" 2
Fixed: persist client-side variant again\&. Closes #9
.PP
.SH "0\&.4\&.0 / 2012-02-01"
.PP
.IP "\(bu" 2
Added browser variant support for older browsers [TooTallNate]
.IP "\(bu" 2
Added `debug\&.enable('project:*')` to browser variant [TooTallNate]
.IP "\(bu" 2
Added padding to diff (moved it to the right)
.PP
.SH "0\&.3\&.0 / 2012-01-26"
.PP
.IP "\(bu" 2
Added millisecond diff when isatty, otherwise UTC string
.PP
.SH "0\&.2\&.0 / 2012-01-22"
.PP
.IP "\(bu" 2
Added wildcard support
.PP
.SH "0\&.1\&.0 / 2011-12-02"
.PP
.IP "\(bu" 2
Added: remove colors unless stderr isatty [TooTallNate]
.PP
.SH "0\&.0\&.1 / 2010-01-03"
.PP
.IP "\(bu" 2
Initial release 
.PP

