.TH "md_backend_2node__modules_2rimraf_2_c_h_a_n_g_e_l_o_g" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2rimraf_2_c_h_a_n_g_e_l_o_g \- v3\&.0 
.PP

.IP "\(bu" 2
Add \fR--preserve-root\fP option to executable (default true)
.IP "\(bu" 2
Drop support for Node\&.js below version 6
.PP
.SH "v2\&.7"
.PP
.IP "\(bu" 2
Make \fRglob\fP an optional dependency
.PP
.SH "2\&.6"
.PP
.IP "\(bu" 2
Retry on EBUSY on non-windows platforms as well
.IP "\(bu" 2
Make \fRrimraf\&.sync\fP 10000% more reliable on Windows
.PP
.SH "2\&.5"
.PP
.IP "\(bu" 2
Handle Windows EPERM when lstat-ing read-only dirs
.IP "\(bu" 2
Add glob option to pass options to glob
.PP
.SH "2\&.4"
.PP
.IP "\(bu" 2
Add EPERM to delay/retry loop
.IP "\(bu" 2
Add \fRdisableGlob\fP option
.PP
.SH "2\&.3"
.PP
.IP "\(bu" 2
Make maxBusyTries and emfileWait configurable
.IP "\(bu" 2
Handle weird SunOS unlink-dir issue
.IP "\(bu" 2
Glob the CLI arg for better Windows support
.PP
.SH "2\&.2"
.PP
.IP "\(bu" 2
Handle ENOENT properly on Windows
.IP "\(bu" 2
Allow overriding fs methods
.IP "\(bu" 2
Treat EPERM as indicative of non-empty dir
.IP "\(bu" 2
Remove optional graceful-fs dep
.IP "\(bu" 2
Consistently return null error instead of undefined on success
.IP "\(bu" 2
win32: Treat ENOTEMPTY the same as EBUSY
.IP "\(bu" 2
Add \fRrimraf\fP binary
.PP
.SH "2\&.1"
.PP
.IP "\(bu" 2
Fix SunOS error code for a non-empty directory
.IP "\(bu" 2
Try rmdir before readdir
.IP "\(bu" 2
Treat EISDIR like EPERM
.IP "\(bu" 2
Remove chmod
.IP "\(bu" 2
Remove lstat polyfill, node 0\&.7 is not supported
.PP
.SH "2\&.0"
.PP
.IP "\(bu" 2
Fix myGid call to check process\&.getgid
.IP "\(bu" 2
Simplify the EBUSY backoff logic\&.
.IP "\(bu" 2
Use fs\&.lstat in node >= 0\&.7\&.9
.IP "\(bu" 2
Remove gently option
.IP "\(bu" 2
remove fiber implementation
.IP "\(bu" 2
Delete files that are marked read-only
.PP
.SH "1\&.0"
.PP
.IP "\(bu" 2
Allow ENOENT in sync method
.IP "\(bu" 2
Throw when no callback is provided
.IP "\(bu" 2
Make opts\&.gently an absolute path
.IP "\(bu" 2
use 'stat' if 'lstat' is not available
.IP "\(bu" 2
Consistent error naming, and rethrow non-ENOENT stat errors
.IP "\(bu" 2
add fiber implementation 
.PP

