.TH "md_backend_2node__modules_2node-gyp_2docs_2_common-issues" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_backend_2node__modules_2node-gyp_2docs_2_common-issues \- Python Issues OSX 
.PP
 Make sure you are using the native Python version in OSX\&. If you use a MacPorts of HomeBrew version, you may run into problems\&.
.PP
If you have issues with \fRexecvp\fP, be sure to check your \fR$PYTHON\fP environment variable\&. If it is not set to the native version, unset it and try again\&.
.PP
Notes: https://gist.github.com/erichocean/5177582
.SH "npm ERR! \fRnode-gyp rebuild\fP(Windows)"
.PP
.IP "\(bu" 2
just install the build tools from \fRhere\fP Please note the version as is required in below command e\&.g \fB2017\fP
.IP "\(bu" 2
Launch cmd, run \fRnpm config set msvs_version 2017\fP
.IP "\(bu" 2
close and open new CMD/terminal and all is well :100: 
.PP

