.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.generator\&.msvs\&.MSBuildRule\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\&.msvs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetDomainAndUserName\fP ()"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._NormalizedSource\fP (source)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._FixPath\fP (path, separator='\\\\')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._IsWindowsAbsPath\fP (path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._FixPaths\fP (paths, separator='\\\\')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConvertSourcesToFilterHierarchy\fP (sources, prefix=None, excluded=None, list_excluded=True, msvs_version=None)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ToolAppend\fP (tools, tool_name, setting, value, only_if_unset=False)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ToolSetOrAppend\fP (tools, tool_name, setting, value, only_if_unset=False)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConfigTargetVersion\fP (config_data)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConfigPlatform\fP (config_data)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConfigBaseName\fP (config_name, platform_name)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConfigFullName\fP (config_name, config_data)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConfigWindowsTargetPlatformVersion\fP (config_data, version)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._BuildCommandLineForRuleRaw\fP (spec, cmd, cygwin_shell, has_input_path, quote_cmd, do_setup_env)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._BuildCommandLineForRule\fP (spec, rule, has_input_path, do_setup_env)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddActionStep\fP (actions_dict, inputs, outputs, description, command)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddCustomBuildToolForMSVS\fP (p, spec, primary_input, inputs, outputs, description, cmd)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddAccumulatedActionsToMSVS\fP (p, spec, actions_dict)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._RuleExpandPath\fP (path, input_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._FindRuleTriggerFiles\fP (rule, sources)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._RuleInputsAndOutputs\fP (rule, trigger_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateNativeRulesForMSVS\fP (p, rules, output_dir, spec, options)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._Cygwinify\fP (path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateExternalRules\fP (rules, output_dir, spec, sources, options, actions_to_add)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._EscapeEnvironmentVariableExpansion\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._EscapeCommandLineArgumentForMSVS\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._EscapeVCProjCommandLineArgListItem\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._EscapeCppDefineForMSVS\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._EscapeCommandLineArgumentForMSBuild\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._EscapeMSBuildSpecialCharacters\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._EscapeCppDefineForMSBuild\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateRulesForMSVS\fP (p, output_dir, options, spec, sources, excluded_sources, actions_to_add)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AdjustSourcesForRules\fP (rules, sources, excluded_sources, is_msbuild)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._FilterActionsFromExcluded\fP (excluded_sources, actions_to_add)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetDefaultConfiguration\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetGuidOfProject\fP (proj_path, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMsbuildToolsetOfProject\fP (proj_path, spec, version)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateProject\fP (project, options, version, generator_flags, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateMSVSProject\fP (project, options, version, generator_flags)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetUniquePlatforms\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._CreateMSVSUserFile\fP (proj_path, version, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSVSConfigurationType\fP (spec, build_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddConfigurationToMSVSProject\fP (p, spec, config_type, config_name, config)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetIncludeDirs\fP (config)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetLibraryDirs\fP (config)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetLibraries\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetOutputFilePathAndTool\fP (spec, msbuild)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetOutputTargetExt\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetDefines\fP (config)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetDisabledWarnings\fP (config)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetModuleDefinition\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConvertToolsToExpectedForm\fP (tools)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddConfigurationToMSVS\fP (p, spec, tools, config, config_type, config_name)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSVSAttributes\fP (spec, config, config_type)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddNormalizedSources\fP (sources_set, sources_array)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._PrepareListOfSources\fP (spec, generator_flags, gyp_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AdjustSourcesAndConvertToFilterHierarchy\fP (spec, options, gyp_dir, sources, excluded_sources, list_excluded, version)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._IdlFilesHandledNonNatively\fP (spec, sources)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetPrecompileRelatedFiles\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ExcludeFilesFromBeingBuilt\fP (p, spec, excluded_sources, excluded_idl, list_excluded)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetExcludedFilesFromBuild\fP (spec, excluded_sources, excluded_idl)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddToolFilesToMSVS\fP (p, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._HandlePreCompiledHeaders\fP (p, sources, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddActions\fP (actions_to_add, spec, relative_path_of_gyp_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._WriteMSVSUserFile\fP (project_path, version, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddCopies\fP (actions_to_add, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetCopies\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetPathDict\fP (root, path)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._DictsToFolders\fP (base_path, bucket, flat)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._CollapseSingles\fP (parent, node)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GatherSolutionFolders\fP (sln_projects, project_objects, flat)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetPathOfProject\fP (qualified_target, spec, options, msvs_version)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetPlatformOverridesOfProject\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._CreateProjectObjects\fP (target_list, target_dicts, options, msvs_version)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._InitNinjaFlavor\fP (params, target_list, target_dicts)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.CalculateVariables\fP (default_variables, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.PerformBuild\fP (data, configurations, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.CalculateGeneratorInputInfo\fP (params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.GenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateMSBuildFiltersFile\fP (filters_path, source_files, rule_dependencies, extension_to_rule_name, platforms, toolset)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AppendFiltersForMSBuild\fP (parent_filter_name, sources, rule_dependencies, extension_to_rule_name, platforms, toolset, filter_group, source_group)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._MapFileToMsBuildSourceType\fP (source, rule_dependencies, extension_to_rule_name, platforms, toolset)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateRulesForMSBuild\fP (output_dir, options, spec, sources, excluded_sources, props_files_of_rules, targets_files_of_rules, actions_to_add, rule_dependencies, extension_to_rule_name)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateMSBuildRulePropsFile\fP (props_path, msbuild_rules)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateMSBuildRuleTargetsFile\fP (targets_path, msbuild_rules)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateMSBuildRuleXmlFile\fP (xml_path, msbuild_rules)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetConfigurationAndPlatform\fP (name, settings, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetConfigurationCondition\fP (name, settings, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildProjectConfigurations\fP (configurations, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildGlobalProperties\fP (spec, version, guid, gyp_file_name)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildConfigurationDetails\fP (spec, build_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildLocalProperties\fP (msbuild_toolset)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildPropertySheets\fP (configurations, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConvertMSVSBuildAttributes\fP (spec, config, build_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConvertMSVSCharacterSet\fP (char_set)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._ConvertMSVSConfigurationType\fP (config_type)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildAttributes\fP (spec, config, build_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildConfigurationGlobalProperties\fP (spec, configurations, build_file)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddConditionalProperty\fP (properties, condition, name, value)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildPropertyGroup\fP (spec, label, properties)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildToolSettingsSections\fP (spec, configurations)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._FinalizeMSBuildSettings\fP (spec, configuration)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetValueFormattedForMSBuild\fP (tool_name, name, value)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._VerifySourcesExist\fP (sources, root_dir)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildSources\fP (spec, sources, exclusions, rule_dependencies, extension_to_rule_name, actions_spec, sources_handled_by_action, list_excluded)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddSources2\fP (spec, sources, exclusions, grouped_sources, rule_dependencies, extension_to_rule_name, sources_handled_by_action, list_excluded)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildProjectReferences\fP (project)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateMSBuildProject\fP (project, options, version, generator_flags, spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildExternalBuilderTargets\fP (spec)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildExtensions\fP (props_files_of_rules)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GetMSBuildExtensionTargets\fP (targets_files_of_rules)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._GenerateActionsForMSBuild\fP (spec, actions_to_add)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&._AddMSBuildAction\fP (spec, primary_input, inputs, outputs, cmd, description, sources_handled_by_action, actions_spec)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.VALID_MSVS_GUID_CHARS\fP = re\&.compile(r'^[A\-F0\-9\\\-]+$')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.generator_supports_multiple_toolsets\fP = \fBgyp\&.common\&.CrossCompileRequested\fP()"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.msvs\&.generator_default_variables\fP"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.msvs\&.generator_additional_path_sections\fP"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.msvs\&.generator_additional_non_configuration_keys\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.generator_filelist_paths\fP = None"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.msvs\&.precomp_keys\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.cached_username\fP = None"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.cached_domain\fP = None"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.fixpath_prefix\fP = None"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.quote_replacer_regex\fP = re\&.compile(r'(\\\\*)'')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.delimiters_replacer_regex\fP = re\&.compile(r'(\\\\*)([,;]+)')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.quote_replacer_regex2\fP = re\&.compile(r'(\\\\+)'')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.msvs\&.MSVS_VARIABLE_REFERENCE\fP = re\&.compile(r'\\$\\(([a\-zA\-Z_][a\-zA\-Z0\-9_]*)\\)')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
