.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/MSVSUtil.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/MSVSUtil.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.MSVSUtil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.MSVSUtil\&._GetLargePdbShimCcPath\fP ()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSUtil\&._DeepCopySomeKeys\fP (in_dict, keys)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSUtil\&._SuffixName\fP (name, suffix)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSUtil\&._ShardName\fP (name, number)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSUtil\&.ShardTargets\fP (target_list, target_dicts)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSUtil\&._GetPdbPath\fP (target_dict, config_name, vars)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSUtil\&.InsertLargePdbShims\fP (target_list, target_dicts, vars)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBgyp\&.MSVSUtil\&.TARGET_TYPE_EXT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
