.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/MSVSNew.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/MSVSNew.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.MSVSNew\&.MSVSSolutionEntry\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSNew\&.MSVSFolder\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSNew\&.MSVSProject\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSNew\&.MSVSSolution\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.MSVSNew\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.MSVSNew\&.cmp\fP (x, y)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSNew\&.MakeGuid\fP (name, seed='msvs_new')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBgyp\&.MSVSNew\&.ENTRY_TYPE_GUIDS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
