.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/msvs_emulation.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/msvs_emulation.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.msvs_emulation\&.MsvsSettings\fP"
.br
.ti -1c
.RI "class \fBgyp\&.msvs_emulation\&.MsvsSettings\&._GetWrapper\fP"
.br
.ti -1c
.RI "class \fBgyp\&.msvs_emulation\&.PrecompiledHeader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.msvs_emulation\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.QuoteForRspFile\fP (arg, quote_cmd=True)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.EncodeRspFileList\fP (args, quote_cmd)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._GenericRetrieve\fP (root, default, path)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._AddPrefix\fP (element, prefix)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._DoRemapping\fP (element, map)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._AppendOrReturn\fP (append, element)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._FindDirectXInstallation\fP ()"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.GetGlobalVSMacroEnv\fP (\fBvs_version\fP)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.ExtractSharedMSVSSystemIncludes\fP (configs, generator_flags)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._LanguageMatchesForPch\fP (source_ext, pch_source_ext)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.GetVSVersion\fP (generator_flags)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._GetVsvarsSetupArgs\fP (generator_flags, arch)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.ExpandMacros\fP (string, expansions)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._ExtractImportantEnvironment\fP (output_of_set)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._FormatAsEnvironmentBlock\fP (envvar_dict)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&._ExtractCLPath\fP (output_of_where)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.GenerateEnvironmentFiles\fP (toplevel_build_dir, generator_flags, system_includes, open_out)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.VerifyMissingSources\fP (sources, build_dir, generator_flags, gyp_to_ninja)"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.CalculateCommonVariables\fP (default_variables, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.windows_quoter_regex\fP = re\&.compile(r'(\\\\*)'')"
.br
.ti -1c
.RI "\fBgyp\&.msvs_emulation\&.vs_version\fP = None"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
