.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.MSVSSettings\&._Tool\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSSettings\&._Type\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSSettings\&._String\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSSettings\&._StringList\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSSettings\&._Boolean\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSSettings\&._Integer\fP"
.br
.ti -1c
.RI "class \fBgyp\&.MSVSSettings\&._Enumeration\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.MSVSSettings\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._AddTool\fP (tool)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._GetMSBuildToolSettings\fP (msbuild_settings, tool)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._Same\fP (tool, name, setting_type)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._Renamed\fP (tool, msvs_name, msbuild_name, setting_type)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._Moved\fP (tool, settings_name, msbuild_tool_name, setting_type)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._MovedAndRenamed\fP (tool, msvs_settings_name, msbuild_tool_name, msbuild_settings_name, setting_type)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._MSVSOnly\fP (tool, name, setting_type)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._MSBuildOnly\fP (tool, name, setting_type)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._ConvertedToAdditionalOption\fP (tool, msvs_name, flag)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._CustomGeneratePreprocessedFile\fP (tool, msvs_name)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._ValidateExclusionSetting\fP (setting, settings, error_msg, stderr=sys\&.stderr)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&.FixVCMacroSlashes\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&.ConvertVCMacrosToMSBuild\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&.ConvertToMSBuildSettings\fP (msvs_settings, stderr=sys\&.stderr)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&.ValidateMSVSSettings\fP (settings, stderr=sys\&.stderr)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&.ValidateMSBuildSettings\fP (settings, stderr=sys\&.stderr)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._ValidateSettings\fP (validators, settings, stderr)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBgyp\&.MSVSSettings\&._msvs_validators\fP = {}"
.br
.ti -1c
.RI "dict \fBgyp\&.MSVSSettings\&._msbuild_validators\fP = {}"
.br
.ti -1c
.RI "dict \fBgyp\&.MSVSSettings\&._msvs_to_msbuild_converters\fP = {}"
.br
.ti -1c
.RI "dict \fBgyp\&.MSVSSettings\&._msbuild_name_of_tool\fP = {}"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._boolean\fP = \fB_Boolean\fP()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._integer\fP = \fB_Integer\fP()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._string\fP = \fB_String\fP()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._file_name\fP = \fB_String\fP()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._folder_name\fP = \fB_String\fP()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._file_list\fP = \fB_StringList\fP()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._folder_list\fP = \fB_StringList\fP()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._string_list\fP = \fB_StringList\fP()"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._newly_boolean\fP = \fB_Enumeration\fP(['', 'false', 'true'])"
.br
.ti -1c
.RI "tuple \fBgyp\&.MSVSSettings\&.fix_vc_macro_slashes_regex_list\fP = ('IntDir', 'OutDir')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&.fix_vc_macro_slashes_regex\fP"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._EXCLUDED_SUFFIX_RE\fP = re\&.compile('^(\&.*)_excluded$')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._compile\fP = \fB_Tool\fP('VCCLCompilerTool', 'ClCompile')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._link\fP = \fB_Tool\fP('VCLinkerTool', 'Link')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._midl\fP = \fB_Tool\fP('VCMIDLTool', 'Midl')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._rc\fP = \fB_Tool\fP('VCResourceCompilerTool', 'ResourceCompile')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._lib\fP = \fB_Tool\fP('VCLibrarianTool', 'Lib')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._manifest\fP = \fB_Tool\fP('VCManifestTool', 'Manifest')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._masm\fP = \fB_Tool\fP('MASM', 'MASM')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._armasm\fP = \fB_Tool\fP('ARMASM', 'ARMASM')"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._subsystem_enumeration\fP"
.br
.ti -1c
.RI "\fBgyp\&.MSVSSettings\&._target_machine_enumeration\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
