.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/MSVSVersion.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/MSVSVersion.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.MSVSVersion\&.VisualStudioVersion\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.MSVSVersion\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&.JoinPath\fP (*args)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&._RegistryQueryBase\fP (sysdir, key, value)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&._RegistryQuery\fP (key, value=None)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&._RegistryGetValueUsingWinReg\fP (key, value)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&._RegistryGetValue\fP (key, value)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&._CreateVersion\fP (name, path, sdk_based=False)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&._ConvertToCygpath\fP (path)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&._DetectVisualStudioVersions\fP (versions_to_check, force_express)"
.br
.ti -1c
.RI "\fBgyp\&.MSVSVersion\&.SelectVisualStudioVersion\fP (version='auto', allow_fallback=True)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
