.TH "Napi::Object::PropertyLValue< Key >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::Object::PropertyLValue< Key >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator Value\fP () const"
.br
.RI "Converts an L-value to a value\&. "
.ti -1c
.RI "template<typename ValueType > \fBPropertyLValue\fP & \fBoperator=\fP (ValueType value)"
.br
.ti -1c
.RI "template<typename ValueType > \fBObject::PropertyLValue\fP< Key > & \fBoperator=\fP (ValueType value)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBNapi::Object\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Key>
.br
class Napi::Object::PropertyLValue< Key >"Enables property and element assignments using indexing syntax\&.
.PP
This is a convenient helper to get and set object properties\&. As getting and setting object properties may throw with JavaScript exceptions, it is notable that these operations may fail\&. When NODE_ADDON_API_ENABLE_MAYBE is defined, the process will abort on JavaScript exceptions\&.
.PP
Example: 
.PP
.nf
Napi::Value propertyValue = object1['A'];
object2['A'] = propertyValue;
Napi::Value elementValue = array[0];
array[1] = elementValue; 

.fi
.PP
 
.PP
Definition at line \fB767\fP of file \fBnapi\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Key > \fBNapi::Object::PropertyLValue\fP< Key >::operator \fBValue\fP () const\fR [inline]\fP"

.PP
Converts an L-value to a value\&. 
.PP
Definition at line \fB1366\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Key > template<typename ValueType > \fBObject::PropertyLValue\fP< Key > & \fBNapi::Object::PropertyLValue\fP< Key >::operator= (ValueType value)\fR [inline]\fP"

.PP
Definition at line \fB1377\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Key > template<typename ValueType > \fBPropertyLValue\fP & \fBNapi::Object::PropertyLValue\fP< Key >::operator= (ValueType value)"
Assigns a value to the property\&. The type of value can be anything supported by \fR\fBObject::Set\fP\fP\&. 
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<typename Key > friend class \fBNapi::Object\fP\fR [friend]\fP"

.PP
Definition at line \fB784\fP of file \fBnapi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
