.TH "Napi::AccessorCallbackData< T, TGetterCallback, TSetterCallback >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::AccessorCallbackData< T, TGetterCallback, TSetterCallback >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TGetterCallback \fBgetterCallback\fP"
.br
.ti -1c
.RI "TSetterCallback \fBsetterCallback\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename TGetterCallback, typename TSetterCallback>
.br
struct Napi::AccessorCallbackData< T, TGetterCallback, TSetterCallback >"
.PP
Definition at line \fB2142\fP of file \fBnapi\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T , typename TGetterCallback , typename TSetterCallback > void* \fBNapi::AccessorCallbackData\fP< T, TGetterCallback, TSetterCallback >::data"

.PP
Definition at line \fB2145\fP of file \fBnapi\&.h\fP\&.
.SS "template<typename T , typename TGetterCallback , typename TSetterCallback > TGetterCallback \fBNapi::AccessorCallbackData\fP< T, TGetterCallback, TSetterCallback >::getterCallback"

.PP
Definition at line \fB2143\fP of file \fBnapi\&.h\fP\&.
.SS "template<typename T , typename TGetterCallback , typename TSetterCallback > TSetterCallback \fBNapi::AccessorCallbackData\fP< T, TGetterCallback, TSetterCallback >::setterCallback"

.PP
Definition at line \fB2144\fP of file \fBnapi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
