.TH "Napi::CallbackInfo" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::CallbackInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallbackInfo\fP (napi_env env, napi_callback_info info)"
.br
.ti -1c
.RI "\fB~CallbackInfo\fP ()"
.br
.ti -1c
.RI "\fBNapi::Env\fP \fBEnv\fP () const"
.br
.ti -1c
.RI "\fBValue\fP \fBNewTarget\fP () const"
.br
.ti -1c
.RI "bool \fBIsConstructCall\fP () const"
.br
.ti -1c
.RI "size_t \fBLength\fP () const"
.br
.ti -1c
.RI "const \fBValue\fP \fBoperator[]\fP (size_t index) const"
.br
.ti -1c
.RI "\fBValue\fP \fBThis\fP () const"
.br
.ti -1c
.RI "void * \fBData\fP () const"
.br
.ti -1c
.RI "void \fBSetData\fP (void *data)"
.br
.ti -1c
.RI "\fBoperator napi_callback_info\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1866\fP of file \fBnapi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Napi::CallbackInfo::CallbackInfo (napi_env env, napi_callback_info info)\fR [inline]\fP"

.PP
Definition at line \fB3746\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::CallbackInfo::~CallbackInfo ()\fR [inline]\fP"

.PP
Definition at line \fB3769\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void * Napi::CallbackInfo::Data () const\fR [inline]\fP"

.PP
Definition at line \fB3809\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBNapi::Env\fP Napi::CallbackInfo::Env () const\fR [inline]\fP"

.PP
Definition at line \fB3790\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "bool Napi::CallbackInfo::IsConstructCall () const\fR [inline]\fP"

.PP
Definition at line \fB3786\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "size_t Napi::CallbackInfo::Length () const\fR [inline]\fP"

.PP
Definition at line \fB3794\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBValue\fP Napi::CallbackInfo::NewTarget () const\fR [inline]\fP"

.PP
Definition at line \fB3779\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::CallbackInfo::operator napi_callback_info () const\fR [inline]\fP, \fR [explicit]\fP"

.PP
Definition at line \fB3775\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "const \fBValue\fP Napi::CallbackInfo::operator[] (size_t index) const\fR [inline]\fP"

.PP
Definition at line \fB3798\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "void Napi::CallbackInfo::SetData (void * data)\fR [inline]\fP"

.PP
Definition at line \fB3813\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBValue\fP Napi::CallbackInfo::This () const\fR [inline]\fP"

.PP
Definition at line \fB3802\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
