.TH "Napi::EscapableHandleScope" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::EscapableHandleScope
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEscapableHandleScope\fP (napi_env env, napi_escapable_handle_scope scope)"
.br
.ti -1c
.RI "\fBEscapableHandleScope\fP (\fBNapi::Env\fP env)"
.br
.ti -1c
.RI "\fB~EscapableHandleScope\fP ()"
.br
.ti -1c
.RI "\fBoperator napi_escapable_handle_scope\fP () const"
.br
.ti -1c
.RI "\fBNapi::Env\fP \fBEnv\fP () const"
.br
.ti -1c
.RI "\fBValue\fP \fBEscape\fP (napi_value escapee)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2463\fP of file \fBnapi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Napi::EscapableHandleScope::EscapableHandleScope (napi_env env, napi_escapable_handle_scope scope)\fR [inline]\fP"

.PP
Definition at line \fB4929\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::EscapableHandleScope::EscapableHandleScope (\fBNapi::Env\fP env)\fR [inline]\fP, \fR [explicit]\fP"

.PP
Definition at line \fB4933\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::EscapableHandleScope::~EscapableHandleScope ()\fR [inline]\fP"

.PP
Definition at line \fB4938\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBNapi::Env\fP Napi::EscapableHandleScope::Env () const\fR [inline]\fP"

.PP
Definition at line \fB4949\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBValue\fP Napi::EscapableHandleScope::Escape (napi_value escapee)\fR [inline]\fP"

.PP
Definition at line \fB4953\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::EscapableHandleScope::operator napi_escapable_handle_scope () const\fR [inline]\fP"

.PP
Definition at line \fB4945\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
