.TH "Napi::InstanceWrap< T >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::InstanceWrap< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.PP
Inherited by \fBNapi::ObjectWrap< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBInstanceVoidMethodCallback\fP = void (T::*)(const \fBCallbackInfo\fP& info)"
.br
.ti -1c
.RI "using \fBInstanceMethodCallback\fP = \fBNapi::Value\fP (T::*)(const \fBCallbackInfo\fP& info)"
.br
.ti -1c
.RI "using \fBInstanceGetterCallback\fP = \fBNapi::Value\fP (T::*)(const \fBCallbackInfo\fP& info)"
.br
.ti -1c
.RI "using \fBInstanceSetterCallback\fP"
.br
.ti -1c
.RI "using \fBPropertyDescriptor\fP = \fBClassPropertyDescriptor\fP<T>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBInstanceWrap\fP< T >\fB::InstanceVoidMethodCallback\fP method> \fBClassPropertyDescriptor\fP< T > \fBInstanceMethod\fP (const char *utf8name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "template<typename \fBInstanceWrap\fP< T >\fB::InstanceVoidMethodCallback\fP method> \fBClassPropertyDescriptor\fP< T > \fBInstanceMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "template<typename \fBInstanceWrap\fP< T >\fB::InstanceGetterCallback\fP getter, typename \fBInstanceWrap\fP< T >\fB::InstanceSetterCallback\fP setter> \fBClassPropertyDescriptor\fP< T > \fBInstanceAccessor\fP (const char *utf8name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "template<typename \fBInstanceWrap\fP< T >\fB::InstanceGetterCallback\fP getter, typename \fBInstanceWrap\fP< T >\fB::InstanceSetterCallback\fP setter> \fBClassPropertyDescriptor\fP< T > \fBInstanceAccessor\fP (\fBSymbol\fP name, napi_property_attributes attributes, void *data)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (const char *utf8name, \fBInstanceVoidMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (const char *utf8name, \fBInstanceMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (\fBSymbol\fP name, \fBInstanceVoidMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (\fBSymbol\fP name, \fBInstanceMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBInstanceVoidMethodCallback\fP method> static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBInstanceMethodCallback\fP method> static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBInstanceVoidMethodCallback\fP method> static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBInstanceMethodCallback\fP method> static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceAccessor\fP (const char *utf8name, \fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceAccessor\fP (\fBSymbol\fP name, \fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter = nullptr> static \fBPropertyDescriptor\fP \fBInstanceAccessor\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter = nullptr> static \fBPropertyDescriptor\fP \fBInstanceAccessor\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceValue\fP (const char *utf8name, \fBNapi::Value\fP value, napi_property_attributes attributes=napi_default)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceValue\fP (\fBSymbol\fP name, \fBNapi::Value\fP value, napi_property_attributes attributes=napi_default)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAttachPropData\fP (napi_env env, napi_value value, const napi_property_descriptor *prop)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Napi::InstanceWrap< T >"
.PP
Definition at line \fB2149\fP of file \fBnapi\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > using \fBNapi::InstanceWrap\fP< T >::InstanceGetterCallback = \fBNapi::Value\fP (T::*)(const \fBCallbackInfo\fP& info)"

.PP
Definition at line \fB2153\fP of file \fBnapi\&.h\fP\&.
.SS "template<typename T > using \fBNapi::InstanceWrap\fP< T >::InstanceMethodCallback = \fBNapi::Value\fP (T::*)(const \fBCallbackInfo\fP& info)"

.PP
Definition at line \fB2152\fP of file \fBnapi\&.h\fP\&.
.SS "template<typename T > using \fBNapi::InstanceWrap\fP< T >::InstanceSetterCallback"
\fBInitial value:\fP
.nf
 void (T::*)(const CallbackInfo& info,
                                             const Napi::Value& value)
.PP
.fi

.PP
Definition at line \fB2154\fP of file \fBnapi\&.h\fP\&.
.SS "template<typename T > using \fBNapi::InstanceWrap\fP< T >::InstanceVoidMethodCallback = void (T::*)(const \fBCallbackInfo\fP& info)"

.PP
Definition at line \fB2151\fP of file \fBnapi\&.h\fP\&.
.SS "template<typename T > using \fBNapi::InstanceWrap\fP< T >::PropertyDescriptor = \fBClassPropertyDescriptor\fP<T>"

.PP
Definition at line \fB2157\fP of file \fBnapi\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBNapi::InstanceWrap\fP< T >::AttachPropData (napi_env env, napi_value value, const napi_property_descriptor * prop)\fR [inline]\fP, \fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB4125\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceAccessor (const char * utf8name, \fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4263\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > template<typename \fBInstanceWrap\fP< T >\fB::InstanceGetterCallback\fP getter, typename \fBInstanceWrap\fP< T >\fB::InstanceSetterCallback\fP setter> \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceAccessor (const char * utf8name, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB4303\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > template<\fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter = nullptr> static \fBPropertyDescriptor\fP \fBNapi::InstanceWrap\fP< T >::InstanceAccessor (const char * utf8name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename T > \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceAccessor (\fBSymbol\fP name, \fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4282\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > template<typename \fBInstanceWrap\fP< T >\fB::InstanceGetterCallback\fP getter, typename \fBInstanceWrap\fP< T >\fB::InstanceSetterCallback\fP setter> \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceAccessor (\fBSymbol\fP name, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB4317\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > template<\fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter = nullptr> static \fBPropertyDescriptor\fP \fBNapi::InstanceWrap\fP< T >::InstanceAccessor (\fBSymbol\fP name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename T > \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceMethod (const char * utf8name, \fBInstanceMethodCallback\fP method, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4164\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceMethod (const char * utf8name, \fBInstanceVoidMethodCallback\fP method, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4147\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > template<typename \fBInstanceWrap\fP< T >\fB::InstanceMethodCallback\fP method> \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceMethod (const char * utf8name, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB4216\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > template<\fBInstanceVoidMethodCallback\fP method> static \fBPropertyDescriptor\fP \fBNapi::InstanceWrap\fP< T >::InstanceMethod (const char * utf8name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename T > template<\fBInstanceMethodCallback\fP method> static \fBPropertyDescriptor\fP \fBNapi::InstanceWrap\fP< T >::InstanceMethod (const char * utf8name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename T > \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceMethod (\fBSymbol\fP name, \fBInstanceMethodCallback\fP method, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4198\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceMethod (\fBSymbol\fP name, \fBInstanceVoidMethodCallback\fP method, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4181\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > template<typename \fBInstanceWrap\fP< T >\fB::InstanceMethodCallback\fP method> \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceMethod (\fBSymbol\fP name, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB4240\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > template<\fBInstanceVoidMethodCallback\fP method> static \fBPropertyDescriptor\fP \fBNapi::InstanceWrap\fP< T >::InstanceMethod (\fBSymbol\fP name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename T > template<\fBInstanceMethodCallback\fP method> static \fBPropertyDescriptor\fP \fBNapi::InstanceWrap\fP< T >::InstanceMethod (\fBSymbol\fP name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename T > \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceValue (const char * utf8name, \fBNapi::Value\fP value, napi_property_attributes attributes = \fRnapi_default\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4329\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T > \fBClassPropertyDescriptor\fP< T > \fBNapi::InstanceWrap\fP< T >::InstanceValue (\fBSymbol\fP name, \fBNapi::Value\fP value, napi_property_attributes attributes = \fRnapi_default\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4341\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
