.TH "Napi::details::CallbackData< Callable, Return >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::details::CallbackData< Callable, Return >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\-inl\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static napi_value \fBWrapper\fP (napi_env env, napi_callback_info info)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Callable \fBcallback\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Callable, typename Return>
.br
struct Napi::details::CallbackData< Callable, Return >"
.PP
Definition at line \fB110\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Callable , typename Return > static napi_value \fBNapi::details::CallbackData\fP< Callable, Return >::Wrapper (napi_env env, napi_callback_info info)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB111\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename Callable , typename Return > Callable \fBNapi::details::CallbackData\fP< Callable, Return >::callback"

.PP
Definition at line \fB121\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Callable , typename Return > void* \fBNapi::details::CallbackData\fP< Callable, Return >::data"

.PP
Definition at line \fB122\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
