.TH "Napi::ClassPropertyDescriptor< T >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::ClassPropertyDescriptor< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassPropertyDescriptor\fP (napi_property_descriptor desc)"
.br
.ti -1c
.RI "\fBoperator napi_property_descriptor &\fP ()"
.br
.ti -1c
.RI "\fBoperator const napi_property_descriptor &\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Napi::ClassPropertyDescriptor< T >"Property descriptor for use with \fR\fBObjectWrap::DefineClass()\fP\fP\&.
.PP
This is different from the standalone \fR\fBPropertyDescriptor\fP\fP because it is specific to each \fR\fBObjectWrap\fP<T>\fP subclass\&. This prevents using descriptors from a different class when defining a new class (preventing the callbacks from having incorrect \fRthis\fP pointers)\&. 
.PP
Definition at line \fB2124\fP of file \fBnapi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBNapi::ClassPropertyDescriptor\fP< T >::ClassPropertyDescriptor (napi_property_descriptor desc)\fR [inline]\fP"

.PP
Definition at line \fB2126\fP of file \fBnapi\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBNapi::ClassPropertyDescriptor\fP< T >::operator const napi_property_descriptor & () const\fR [inline]\fP"

.PP
Definition at line \fB2129\fP of file \fBnapi\&.h\fP\&.
.SS "template<typename T > \fBNapi::ClassPropertyDescriptor\fP< T >::operator napi_property_descriptor & ()\fR [inline]\fP"

.PP
Definition at line \fB2128\fP of file \fBnapi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
