.TH "Napi::details::disjunction<... >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::details::disjunction<... >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\-inl\&.h>\fP
.PP
Inherits std::false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&.>
.br
struct Napi::details::disjunction<\&.\&.\&. >"
.PP
Definition at line \fB1290\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
