.TH "Napi::MemoryManagement" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::MemoryManagement
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int64_t \fBAdjustExternalMemory\fP (\fBEnv\fP env, int64_t change_in_bytes)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3161\fP of file \fBnapi\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int64_t Napi::MemoryManagement::AdjustExternalMemory (\fBEnv\fP env, int64_t change_in_bytes)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB6483\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
