.TH "Napi::PropertyDescriptor" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::PropertyDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBGetterCallback\fP = \fBNapi::Value\fP (*)(const \fBNapi::CallbackInfo\fP& info)"
.br
.ti -1c
.RI "using \fBSetterCallback\fP = void (*)(const \fBNapi::CallbackInfo\fP& info)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertyDescriptor\fP (napi_property_descriptor desc)"
.br
.ti -1c
.RI "\fBoperator napi_property_descriptor &\fP ()"
.br
.ti -1c
.RI "\fBoperator const napi_property_descriptor &\fP () const"
.br
.ti -1c
.RI "template<typename Getter > \fBPropertyDescriptor\fP \fBAccessor\fP (const char *utf8name, Getter getter, napi_property_attributes attributes, void *)"
.br
.ti -1c
.RI "template<typename Getter > \fBPropertyDescriptor\fP \fBAccessor\fP (const std::string &utf8name, Getter getter, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "template<typename Getter > \fBPropertyDescriptor\fP \fBAccessor\fP (napi_value name, Getter getter, napi_property_attributes attributes, void *)"
.br
.ti -1c
.RI "template<typename Getter > \fBPropertyDescriptor\fP \fBAccessor\fP (\fBName\fP name, Getter getter, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP \fBAccessor\fP (const char *utf8name, Getter getter, Setter setter, napi_property_attributes attributes, void *)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP \fBAccessor\fP (const std::string &utf8name, Getter getter, Setter setter, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP \fBAccessor\fP (napi_value name, Getter getter, Setter setter, napi_property_attributes attributes, void *)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP \fBAccessor\fP (\fBName\fP name, Getter getter, Setter setter, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "template<typename Callable > \fBPropertyDescriptor\fP \fBFunction\fP (const char *utf8name, Callable cb, napi_property_attributes attributes, void *)"
.br
.ti -1c
.RI "template<typename Callable > \fBPropertyDescriptor\fP \fBFunction\fP (const std::string &utf8name, Callable cb, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "template<typename Callable > \fBPropertyDescriptor\fP \fBFunction\fP (napi_value name, Callable cb, napi_property_attributes attributes, void *)"
.br
.ti -1c
.RI "template<typename Callable > \fBPropertyDescriptor\fP \fBFunction\fP (\fBName\fP name, Callable cb, napi_property_attributes attributes, void *data)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Getter > static \fBPropertyDescriptor\fP \fBAccessor\fP (const char *utf8name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter > static \fBPropertyDescriptor\fP \fBAccessor\fP (const std::string &utf8name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter > static \fBPropertyDescriptor\fP \fBAccessor\fP (napi_value name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter > static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBName\fP name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP \fBAccessor\fP (const char *utf8name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP \fBAccessor\fP (const std::string &utf8name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP \fBAccessor\fP (napi_value name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBName\fP name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Callable > static \fBPropertyDescriptor\fP \fBFunction\fP (const char *utf8name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Callable > static \fBPropertyDescriptor\fP \fBFunction\fP (const std::string &utf8name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Callable > static \fBPropertyDescriptor\fP \fBFunction\fP (napi_value name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Callable > static \fBPropertyDescriptor\fP \fBFunction\fP (\fBName\fP name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBGetterCallback\fP Getter> static \fBPropertyDescriptor\fP \fBAccessor\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBGetterCallback\fP Getter> static \fBPropertyDescriptor\fP \fBAccessor\fP (const std::string &utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBGetterCallback\fP Getter> static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBName\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBGetterCallback\fP Getter, \fBSetterCallback\fP Setter> static \fBPropertyDescriptor\fP \fBAccessor\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBGetterCallback\fP Getter, \fBSetterCallback\fP Setter> static \fBPropertyDescriptor\fP \fBAccessor\fP (const std::string &utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<\fBGetterCallback\fP Getter, \fBSetterCallback\fP Setter> static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBName\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter > static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const char *utf8name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter > static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const std::string &utf8name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter > static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, \fBName\fP name, Getter getter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const char *utf8name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const std::string &utf8name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP \fBAccessor\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, \fBName\fP name, Getter getter, Setter setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Callable > static \fBPropertyDescriptor\fP \fBFunction\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const char *utf8name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Callable > static \fBPropertyDescriptor\fP \fBFunction\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const std::string &utf8name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "template<typename Callable > static \fBPropertyDescriptor\fP \fBFunction\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP object, \fBName\fP name, Callable cb, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBValue\fP (const char *utf8name, napi_value value, napi_property_attributes attributes=napi_default)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBValue\fP (const std::string &utf8name, napi_value value, napi_property_attributes attributes=napi_default)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBValue\fP (napi_value name, napi_value value, napi_property_attributes attributes=napi_default)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBValue\fP (\fBName\fP name, \fBNapi::Value\fP value, napi_property_attributes attributes=napi_default)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1896\fP of file \fBnapi\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBNapi::PropertyDescriptor::GetterCallback\fP = \fBNapi::Value\fP (*)(const \fBNapi::CallbackInfo\fP& info)"

.PP
Definition at line \fB1898\fP of file \fBnapi\&.h\fP\&.
.SS "using \fBNapi::PropertyDescriptor::SetterCallback\fP = void (*)(const \fBNapi::CallbackInfo\fP& info)"

.PP
Definition at line \fB1899\fP of file \fBnapi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Napi::PropertyDescriptor::PropertyDescriptor (napi_property_descriptor desc)\fR [inline]\fP"

.PP
Definition at line \fB4109\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Getter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const char * utf8name, Getter getter, napi_property_attributes attributes, void * )\fR [inline]\fP"

.PP
Definition at line \fB9\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Getter > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const char * utf8name, Getter getter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const char * utf8name, Getter getter, Setter setter, napi_property_attributes attributes, void * )\fR [inline]\fP"

.PP
Definition at line \fB65\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const char * utf8name, Getter getter, Setter setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename \fBPropertyDescriptor::GetterCallback\fP Getter> \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const char * utf8name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.PP
Definition at line \fB3822\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename \fBPropertyDescriptor::GetterCallback\fP Getter, typename \fBPropertyDescriptor::SetterCallback\fP Setter> \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const char * utf8name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.PP
Definition at line \fB3857\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const std::string & utf8name, Getter getter, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB29\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Getter > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const std::string & utf8name, Getter getter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const std::string & utf8name, Getter getter, Setter setter, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB86\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const std::string & utf8name, Getter getter, Setter setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename \fBPropertyDescriptor::GetterCallback\fP Getter> \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const std::string & utf8name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.PP
Definition at line \fB3835\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename \fBPropertyDescriptor::GetterCallback\fP Getter, typename \fBPropertyDescriptor::SetterCallback\fP Setter> \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (const std::string & utf8name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.PP
Definition at line \fB3872\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBName\fP name, Getter getter, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Getter > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBName\fP name, Getter getter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBName\fP name, Getter getter, Setter setter, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB117\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBName\fP name, Getter getter, Setter setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename \fBPropertyDescriptor::GetterCallback\fP Getter> \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBName\fP name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.PP
Definition at line \fB3843\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename \fBPropertyDescriptor::GetterCallback\fP Getter, typename \fBPropertyDescriptor::SetterCallback\fP Setter> \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBName\fP name, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.PP
Definition at line \fB3881\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const char * utf8name, Getter getter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB3895\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const char * utf8name, Getter getter, Setter setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB3960\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const std::string & utf8name, Getter getter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB3922\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const std::string & utf8name, Getter getter, Setter setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB3988\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBNapi::Env\fP env, \fBNapi::Object\fP object, \fBName\fP name, Getter getter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB3933\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (\fBNapi::Env\fP env, \fBNapi::Object\fP object, \fBName\fP name, Getter getter, Setter setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4001\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Getter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (napi_value name, Getter getter, napi_property_attributes attributes, void * )\fR [inline]\fP"

.PP
Definition at line \fB38\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Getter > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (napi_value name, Getter getter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename Getter , typename Setter > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (napi_value name, Getter getter, Setter setter, napi_property_attributes attributes, void * )\fR [inline]\fP"

.PP
Definition at line \fB96\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Getter , typename Setter > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Accessor (napi_value name, Getter getter, Setter setter, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename Callable > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (const char * utf8name, Callable cb, napi_property_attributes attributes, void * )\fR [inline]\fP"

.PP
Definition at line \fB129\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Callable > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (const char * utf8name, Callable cb, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename Callable > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (const std::string & utf8name, Callable cb, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB150\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Callable > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (const std::string & utf8name, Callable cb, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename Callable > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (\fBName\fP name, Callable cb, napi_property_attributes attributes, void * data)\fR [inline]\fP"

.PP
Definition at line \fB180\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Callable > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (\fBName\fP name, Callable cb, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "template<typename Callable > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const char * utf8name, Callable cb, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4029\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Callable > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (\fBNapi::Env\fP env, \fBNapi::Object\fP object, const std::string & utf8name, Callable cb, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4047\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Callable > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (\fBNapi::Env\fP env, \fBNapi::Object\fP object, \fBName\fP name, Callable cb, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4058\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename Callable > \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (napi_value name, Callable cb, napi_property_attributes attributes, void * )\fR [inline]\fP"

.PP
Definition at line \fB159\fP of file \fBnapi\-inl\&.deprecated\&.h\fP\&.
.SS "template<typename Callable > static \fBPropertyDescriptor\fP Napi::PropertyDescriptor::Function (napi_value name, Callable cb, napi_property_attributes attributes = \fRnapi_default\fP, void * data = \fRnullptr\fP)\fR [static]\fP"

.SS "Napi::PropertyDescriptor::operator const napi_property_descriptor & () const\fR [inline]\fP"

.PP
Definition at line \fB4116\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::PropertyDescriptor::operator napi_property_descriptor & ()\fR [inline]\fP"

.PP
Definition at line \fB4112\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBPropertyDescriptor\fP Napi::PropertyDescriptor::Value (const char * utf8name, napi_value value, napi_property_attributes attributes = \fRnapi_default\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4075\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBPropertyDescriptor\fP Napi::PropertyDescriptor::Value (const std::string & utf8name, napi_value value, napi_property_attributes attributes = \fRnapi_default\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4089\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBPropertyDescriptor\fP Napi::PropertyDescriptor::Value (\fBName\fP name, \fBNapi::Value\fP value, napi_property_attributes attributes = \fRnapi_default\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4102\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBPropertyDescriptor\fP Napi::PropertyDescriptor::Value (napi_value name, napi_value value, napi_property_attributes attributes = \fRnapi_default\fP)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB4096\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
