.TH "Napi::details::vf_number< bool >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::details::vf_number< bool >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\-inl\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBBoolean\fP \fBFrom\fP (napi_env env, bool value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1255\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBBoolean\fP \fBNapi::details::vf_number\fP< bool >::From (napi_env env, bool value)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB1256\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
