.TH "Napi::details::vf_fallback< T >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::details::vf_fallback< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\-inl\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBValue\fP \fBFrom\fP (napi_env env, const T &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct Napi::details::vf_fallback< T >"
.PP
Definition at line \fB1285\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static \fBValue\fP \fBNapi::details::vf_fallback\fP< T >::From (napi_env env, const T & value)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB1286\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
