.TH "Napi::Env" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::Env
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnv\fP (napi_env env)"
.br
.ti -1c
.RI "\fBoperator napi_env\fP () const"
.br
.ti -1c
.RI "\fBObject\fP \fBGlobal\fP () const"
.br
.ti -1c
.RI "\fBValue\fP \fBUndefined\fP () const"
.br
.ti -1c
.RI "\fBValue\fP \fBNull\fP () const"
.br
.ti -1c
.RI "bool \fBIsExceptionPending\fP () const"
.br
.ti -1c
.RI "\fBError\fP \fBGetAndClearPendingException\fP () const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< \fBValue\fP > \fBRunScript\fP (const char *utf8script) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< \fBValue\fP > \fBRunScript\fP (const std::string &utf8script) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< \fBValue\fP > \fBRunScript\fP (\fBString\fP script) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Environment for Node-API values and operations\&.
.PP
All Node-API values and operations must be associated with an environment\&. An environment instance is always provided to callback functions; that environment must then be used for any creation of Node-API values or other Node-API operations within the callback\&. (Many methods infer the environment from the \fRthis\fP instance that the method is called on\&.)
.PP
In the future, multiple environments per process may be supported, although current implementations only support one environment per process\&.
.PP
In the V8 JavaScript engine, a Node-API environment approximately corresponds to an Isolate\&. 
.PP
Definition at line \fB295\fP of file \fBnapi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Napi::Env::Env (napi_env env)\fR [inline]\fP"

.PP
Definition at line \fB452\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBError\fP Napi::Env::GetAndClearPendingException () const\fR [inline]\fP"

.PP
Definition at line \fB487\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBObject\fP Napi::Env::Global () const\fR [inline]\fP"

.PP
Definition at line \fB458\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "bool Napi::Env::IsExceptionPending () const\fR [inline]\fP"

.PP
Definition at line \fB479\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBValue\fP Napi::Env::Null () const\fR [inline]\fP"

.PP
Definition at line \fB472\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::Env::operator napi_env () const\fR [inline]\fP"

.PP
Definition at line \fB454\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< \fBValue\fP > Napi::Env::RunScript (const char * utf8script) const\fR [inline]\fP"

.PP
Definition at line \fB497\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< \fBValue\fP > Napi::Env::RunScript (const std::string & utf8script) const\fR [inline]\fP"

.PP
Definition at line \fB502\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< \fBValue\fP > Napi::Env::RunScript (\fBString\fP script) const\fR [inline]\fP"

.PP
Definition at line \fB506\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBValue\fP Napi::Env::Undefined () const\fR [inline]\fP"

.PP
Definition at line \fB465\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
