.TH "Napi::VersionManagement" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::VersionManagement
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBGetNapiVersion\fP (\fBEnv\fP env)"
.br
.ti -1c
.RI "static const napi_node_version * \fBGetNodeVersion\fP (\fBEnv\fP env)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3167\fP of file \fBnapi\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t Napi::VersionManagement::GetNapiVersion (\fBEnv\fP env)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB6496\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "const napi_node_version * Napi::VersionManagement::GetNodeVersion (\fBEnv\fP env)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB6503\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
