.TH "Napi::details::disjunction< B >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::details::disjunction< B >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\-inl\&.h>\fP
.PP
Inherits B\&.
.SH "Detailed Description"
.PP 

.SS "template<typename B>
.br
struct Napi::details::disjunction< B >"
.PP
Definition at line \fB1292\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
