.TH "Napi::Promise::Deferred" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::Promise::Deferred
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeferred\fP (napi_env env)"
.br
.ti -1c
.RI "\fBNapi::Promise\fP \fBPromise\fP () const"
.br
.ti -1c
.RI "\fBNapi::Env\fP \fBEnv\fP () const"
.br
.ti -1c
.RI "void \fBResolve\fP (napi_value value) const"
.br
.ti -1c
.RI "void \fBReject\fP (napi_value value) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDeferred\fP \fBNew\fP (napi_env env)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1469\fP of file \fBnapi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Napi::Promise::Deferred::Deferred (napi_env env)\fR [inline]\fP"

.PP
Definition at line \fB2587\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBNapi::Env\fP Napi::Promise::Deferred::Env () const\fR [inline]\fP"

.PP
Definition at line \fB2596\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBPromise::Deferred\fP Napi::Promise::Deferred::New (napi_env env)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB2583\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBPromise\fP Napi::Promise::Deferred::Promise () const\fR [inline]\fP"

.PP
Definition at line \fB2592\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "void Napi::Promise::Deferred::Reject (napi_value value) const\fR [inline]\fP"

.PP
Definition at line \fB2605\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "void Napi::Promise::Deferred::Resolve (napi_value value) const\fR [inline]\fP"

.PP
Definition at line \fB2600\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
