.TH "Napi::MethodCallbackData< T, TCallback >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::MethodCallbackData< T, TCallback >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TCallback \fBcallback\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename TCallback>
.br
struct Napi::MethodCallbackData< T, TCallback >"
.PP
Definition at line \fB2136\fP of file \fBnapi\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T , typename TCallback > TCallback \fBNapi::MethodCallbackData\fP< T, TCallback >::callback"

.PP
Definition at line \fB2137\fP of file \fBnapi\&.h\fP\&.
.SS "template<typename T , typename TCallback > void* \fBNapi::MethodCallbackData\fP< T, TCallback >::data"

.PP
Definition at line \fB2138\fP of file \fBnapi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
