.TH "Napi::AsyncContext" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::AsyncContext
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAsyncContext\fP (napi_env env, const char *resource_name)"
.br
.ti -1c
.RI "\fBAsyncContext\fP (napi_env env, const char *resource_name, const \fBObject\fP &resource)"
.br
.ti -1c
.RI "virtual \fB~AsyncContext\fP ()"
.br
.ti -1c
.RI "\fBAsyncContext\fP (\fBAsyncContext\fP &&other)"
.br
.ti -1c
.RI "\fBAsyncContext\fP & \fBoperator=\fP (\fBAsyncContext\fP &&other)"
.br
.ti -1c
.RI "\fBoperator napi_async_context\fP () const"
.br
.ti -1c
.RI "\fBNapi::Env\fP \fBEnv\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2502\fP of file \fBnapi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Napi::AsyncContext::AsyncContext (napi_env env, const char * resource_name)\fR [inline]\fP, \fR [explicit]\fP"

.PP
Definition at line \fB4994\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::AsyncContext::AsyncContext (napi_env env, const char * resource_name, const \fBObject\fP & resource)\fR [inline]\fP, \fR [explicit]\fP"

.PP
Definition at line \fB4997\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::AsyncContext::~AsyncContext ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Definition at line \fB5010\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::AsyncContext::AsyncContext (\fBAsyncContext\fP && other)\fR [inline]\fP"

.PP
Definition at line \fB5017\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBNapi::Env\fP Napi::AsyncContext::Env () const\fR [inline]\fP"

.PP
Definition at line \fB5036\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::AsyncContext::operator napi_async_context () const\fR [inline]\fP"

.PP
Definition at line \fB5032\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBAsyncContext\fP & Napi::AsyncContext::operator= (\fBAsyncContext\fP && other)\fR [inline]\fP"

.PP
Definition at line \fB5024\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
