.TH "Napi::details::can_make_string< T >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::details::can_make_string< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\-inl\&.h>\fP
.PP
Inherits \fBNapi::details::disjunction< std::is_convertible< T, const char * >::type, std::is_convertible< T, const char16_t * >::type, std::is_convertible< T, std::string >::type, std::is_convertible< T, std::u16string >::type >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct Napi::details::can_make_string< T >"
.PP
Definition at line \fB1298\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
