.TH "Napi::details::FinalizeData< T, Finalizer, Hint >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::details::FinalizeData< T, Finalizer, Hint >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\-inl\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBWrapper\fP (napi_env env, void *data, void *finalizeHint) \fBNAPI_NOEXCEPT\fP"
.br
.ti -1c
.RI "static void \fBWrapperWithHint\fP (napi_env env, void *data, void *finalizeHint) \fBNAPI_NOEXCEPT\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Finalizer \fBcallback\fP"
.br
.ti -1c
.RI "Hint * \fBhint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename Finalizer, typename Hint = void>
.br
struct Napi::details::FinalizeData< T, Finalizer, Hint >"
.PP
Definition at line \fB184\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename Finalizer , typename Hint  = void> static void \fBNapi::details::FinalizeData\fP< T, Finalizer, Hint >::Wrapper (napi_env env, void * data, void * finalizeHint)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB185\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T , typename Finalizer , typename Hint  = void> static void \fBNapi::details::FinalizeData\fP< T, Finalizer, Hint >::WrapperWithHint (napi_env env, void * data, void * finalizeHint)\fR [inline]\fP, \fR [static]\fP"

.PP
Definition at line \fB195\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T , typename Finalizer , typename Hint  = void> Finalizer \fBNapi::details::FinalizeData\fP< T, Finalizer, Hint >::callback"

.PP
Definition at line \fB206\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "template<typename T , typename Finalizer , typename Hint  = void> Hint* \fBNapi::details::FinalizeData\fP< T, Finalizer, Hint >::hint"

.PP
Definition at line \fB207\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
