.TH "Napi::details::disjunction< B, Bs... >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::details::disjunction< B, Bs... >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\-inl\&.h>\fP
.PP
Inherits std::conditional::type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename B, typename\&.\&.\&. Bs>
.br
struct Napi::details::disjunction< B, Bs\&.\&.\&. >"
.PP
Definition at line \fB1294\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
