.TH "Napi::ObjectReference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napi::ObjectReference
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <napi\&.h>\fP
.PP
Inherits \fBNapi::Reference< Object >\fP\&.
.PP
Inherited by \fBNapi::Error\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectReference\fP ()"
.br
.ti -1c
.RI "\fBObjectReference\fP (napi_env env, napi_ref ref)"
.br
.ti -1c
.RI "\fBObjectReference\fP (\fBReference\fP< \fBObject\fP > &&other)"
.br
.ti -1c
.RI "\fBObjectReference\fP & \fBoperator=\fP (\fBReference\fP< \fBObject\fP > &&other)"
.br
.ti -1c
.RI "\fBObjectReference\fP (\fBObjectReference\fP &&other)"
.br
.ti -1c
.RI "\fBObjectReference\fP & \fBoperator=\fP (\fBObjectReference\fP &&other)"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< \fBNapi::Value\fP > \fBGet\fP (const char *utf8name) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< \fBNapi::Value\fP > \fBGet\fP (const std::string &utf8name) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const char *utf8name, napi_value value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const char *utf8name, \fBNapi::Value\fP value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const char *utf8name, const char *utf8value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const char *utf8name, bool boolValue) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const char *utf8name, double numberValue) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const std::string &utf8name, napi_value value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const std::string &utf8name, \fBNapi::Value\fP value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const std::string &utf8name, std::string &utf8value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const std::string &utf8name, bool boolValue) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (const std::string &utf8name, double numberValue) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< \fBNapi::Value\fP > \fBGet\fP (uint32_t index) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (uint32_t index, const napi_value value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (uint32_t index, const \fBNapi::Value\fP value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (uint32_t index, const char *utf8value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (uint32_t index, const std::string &utf8value) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (uint32_t index, bool boolValue) const"
.br
.ti -1c
.RI "\fBMaybeOrValue\fP< bool > \fBSet\fP (uint32_t index, double numberValue) const"
.br
.in -1c

Public Member Functions inherited from \fBNapi::Reference< Object >\fP
.in +1c
.ti -1c
.RI "\fBReference\fP ()"
.br
.ti -1c
.RI "\fBReference\fP (napi_env env, napi_ref ref)"
.br
.ti -1c
.RI "\fBReference\fP (\fBReference\fP< \fBObject\fP > &&other)"
.br
.ti -1c
.RI "\fB~Reference\fP ()"
.br
.ti -1c
.RI "\fBReference\fP< \fBObject\fP > & \fBoperator=\fP (\fBReference\fP< \fBObject\fP > &&other)"
.br
.ti -1c
.RI "\fBoperator napi_ref\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBReference\fP< \fBObject\fP > &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBReference\fP< \fBObject\fP > &other) const"
.br
.ti -1c
.RI "\fBNapi::Env\fP \fBEnv\fP () const"
.br
.ti -1c
.RI "bool \fBIsEmpty\fP () const"
.br
.ti -1c
.RI "\fBObject\fP \fBValue\fP () const"
.br
.ti -1c
.RI "uint32_t \fBRef\fP () const"
.br
.ti -1c
.RI "uint32_t \fBUnref\fP () const"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP (const \fBObject\fP &value, uint32_t refcount=0)"
.br
.ti -1c
.RI "void \fBSuppressDestruct\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectReference\fP (const \fBObjectReference\fP &)"
.br
.in -1c

Protected Member Functions inherited from \fBNapi::Reference< Object >\fP
.in +1c
.ti -1c
.RI "\fBReference\fP (const \fBReference\fP< \fBObject\fP > &)"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBNapi::Reference< Object >\fP
.in +1c
.ti -1c
.RI "static \fBReference\fP< \fBObject\fP > \fBNew\fP (const \fBObject\fP &value, uint32_t initialRefcount=0)"
.br
.in -1c

Protected Attributes inherited from \fBNapi::Reference< Object >\fP
.in +1c
.ti -1c
.RI "napi_env \fB_env\fP"
.br
.RI "!cond INTERNAL "
.ti -1c
.RI "napi_ref \fB_ref\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1596\fP of file \fBnapi\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Napi::ObjectReference::ObjectReference ()\fR [inline]\fP"

.PP
Definition at line \fB3349\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::ObjectReference::ObjectReference (napi_env env, napi_ref ref)\fR [inline]\fP"

.PP
Definition at line \fB3351\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::ObjectReference::ObjectReference (\fBReference\fP< \fBObject\fP > && other)\fR [inline]\fP"

.PP
Definition at line \fB3354\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::ObjectReference::ObjectReference (\fBObjectReference\fP && other)\fR [inline]\fP"

.PP
Definition at line \fB3362\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "Napi::ObjectReference::ObjectReference (const \fBObjectReference\fP & other)\fR [inline]\fP, \fR [protected]\fP"

.PP
Definition at line \fB3370\fP of file \fBnapi\-inl\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMaybeOrValue\fP< \fBNapi::Value\fP > Napi::ObjectReference::Get (const char * utf8name) const\fR [inline]\fP"

.PP
Definition at line \fB3373\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< \fBNapi::Value\fP > Napi::ObjectReference::Get (const std::string & utf8name) const\fR [inline]\fP"

.PP
Definition at line \fB3390\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< \fBNapi::Value\fP > Napi::ObjectReference::Get (uint32_t index) const\fR [inline]\fP"

.PP
Definition at line \fB3467\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBObjectReference\fP & Napi::ObjectReference::operator= (\fBObjectReference\fP && other)\fR [inline]\fP"

.PP
Definition at line \fB3365\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBObjectReference\fP & Napi::ObjectReference::operator= (\fBReference\fP< \fBObject\fP > && other)\fR [inline]\fP"

.PP
Definition at line \fB3357\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const char * utf8name, bool boolValue) const\fR [inline]\fP"

.PP
Definition at line \fB3425\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const char * utf8name, const char * utf8value) const\fR [inline]\fP"

.PP
Definition at line \fB3419\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const char * utf8name, double numberValue) const\fR [inline]\fP"

.PP
Definition at line \fB3431\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const char * utf8name, \fBNapi::Value\fP value) const\fR [inline]\fP"

.PP
Definition at line \fB3413\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const char * utf8name, napi_value value) const\fR [inline]\fP"

.PP
Definition at line \fB3407\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const std::string & utf8name, bool boolValue) const\fR [inline]\fP"

.PP
Definition at line \fB3455\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const std::string & utf8name, double numberValue) const\fR [inline]\fP"

.PP
Definition at line \fB3461\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const std::string & utf8name, \fBNapi::Value\fP value) const\fR [inline]\fP"

.PP
Definition at line \fB3443\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const std::string & utf8name, napi_value value) const\fR [inline]\fP"

.PP
Definition at line \fB3437\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (const std::string & utf8name, std::string & utf8value) const\fR [inline]\fP"

.PP
Definition at line \fB3449\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (uint32_t index, bool boolValue) const\fR [inline]\fP"

.PP
Definition at line \fB3507\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (uint32_t index, const char * utf8value) const\fR [inline]\fP"

.PP
Definition at line \fB3495\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (uint32_t index, const \fBNapi::Value\fP value) const\fR [inline]\fP"

.PP
Definition at line \fB3489\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (uint32_t index, const napi_value value) const\fR [inline]\fP"

.PP
Definition at line \fB3483\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (uint32_t index, const std::string & utf8value) const\fR [inline]\fP"

.PP
Definition at line \fB3501\fP of file \fBnapi\-inl\&.h\fP\&.
.SS "\fBMaybeOrValue\fP< bool > Napi::ObjectReference::Set (uint32_t index, double numberValue) const\fR [inline]\fP"

.PP
Definition at line \fB3513\fP of file \fBnapi\-inl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
