.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.generator\&.ninja\&.Target\fP"
.br
.ti -1c
.RI "class \fBgyp\&.generator\&.ninja\&.NinjaWriter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\&.ninja\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.StripPrefix\fP (arg, prefix)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.QuoteShellArgument\fP (arg, flavor)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.Define\fP (d, flavor)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.AddArch\fP (output, arch)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.CalculateVariables\fP (default_variables, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.ComputeOutputDir\fP (params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.CalculateGeneratorInputInfo\fP (params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.OpenOutput\fP (path, mode='w')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.CommandWithWrapper\fP (cmd, wrappers, prog)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.GetDefaultConcurrentLinks\fP ()"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&._GetWinLinkRuleNameSuffix\fP (embed_manifest)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&._AddWinLinkRules\fP (master_ninja, embed_manifest)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.GenerateOutputForConfig\fP (target_list, target_dicts, data, params, config_name)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.PerformBuild\fP (data, configurations, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.CallGenerateOutputForConfig\fP (arglist)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.GenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBgyp\&.generator\&.ninja\&.generator_default_variables\fP"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.ninja\&.generator_additional_non_configuration_keys\fP = []"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.ninja\&.generator_additional_path_sections\fP = []"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.ninja\&.generator_extra_sources_for_rules\fP = []"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.generator_filelist_paths\fP = None"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.ninja\&.generator_supports_multiple_toolsets\fP = \fBgyp\&.common\&.CrossCompileRequested\fP()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
