.TH "node_sqlite3::Statement::Baton" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Statement::Baton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <statement\&.h>\fP
.PP
Inherited by \fBnode_sqlite3::Statement::EachBaton\fP, \fBnode_sqlite3::Statement::RowBaton\fP, \fBnode_sqlite3::Statement::RowsBaton\fP, and \fBnode_sqlite3::Statement::RunBaton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaton\fP (\fBStatement\fP *stmt_, \fBNapi::Function\fP cb_)"
.br
.ti -1c
.RI "virtual \fB~Baton\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "napi_async_work \fBrequest\fP = NULL"
.br
.ti -1c
.RI "\fBStatement\fP * \fBstmt\fP"
.br
.ti -1c
.RI "\fBNapi::FunctionReference\fP \fBcallback\fP"
.br
.ti -1c
.RI "\fBParameters\fP \fBparameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB83\fP of file \fBstatement\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Statement::Baton::Baton (\fBStatement\fP * stmt_, \fBNapi::Function\fP cb_)\fR [inline]\fP"

.PP
Definition at line \fB89\fP of file \fBstatement\&.h\fP\&.
.SS "virtual node_sqlite3::Statement::Baton::~Baton ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Definition at line \fB93\fP of file \fBstatement\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBNapi::FunctionReference\fP node_sqlite3::Statement::Baton::callback"

.PP
Definition at line \fB86\fP of file \fBstatement\&.h\fP\&.
.SS "\fBParameters\fP node_sqlite3::Statement::Baton::parameters"

.PP
Definition at line \fB87\fP of file \fBstatement\&.h\fP\&.
.SS "napi_async_work node_sqlite3::Statement::Baton::request = NULL"

.PP
Definition at line \fB84\fP of file \fBstatement\&.h\fP\&.
.SS "\fBStatement\fP* node_sqlite3::Statement::Baton::stmt"

.PP
Definition at line \fB85\fP of file \fBstatement\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
