.TH "node_sqlite3::Values::Field" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Values::Field
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <statement\&.h>\fP
.PP
Inherited by \fBnode_sqlite3::Values::Blob\fP, \fBnode_sqlite3::Values::Float\fP, \fBnode_sqlite3::Values::Integer\fP, and \fBnode_sqlite3::Values::Text\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBField\fP (unsigned short _index, unsigned short _type=SQLITE_NULL)"
.br
.ti -1c
.RI "\fBField\fP (const char *_name, unsigned short _type=SQLITE_NULL)"
.br
.ti -1c
.RI "virtual \fB~Field\fP ()=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBtype\fP"
.br
.ti -1c
.RI "unsigned short \fBindex\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBstatement\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Values::Field::Field (unsigned short _index, unsigned short _type = \fRSQLITE_NULL\fP)\fR [inline]\fP"

.PP
Definition at line \fB22\fP of file \fBstatement\&.h\fP\&.
.SS "node_sqlite3::Values::Field::Field (const char * _name, unsigned short _type = \fRSQLITE_NULL\fP)\fR [inline]\fP"

.PP
Definition at line \fB24\fP of file \fBstatement\&.h\fP\&.
.SS "virtual node_sqlite3::Values::Field::~Field ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned short node_sqlite3::Values::Field::index"

.PP
Definition at line \fB28\fP of file \fBstatement\&.h\fP\&.
.SS "std::string node_sqlite3::Values::Field::name"

.PP
Definition at line \fB29\fP of file \fBstatement\&.h\fP\&.
.SS "unsigned short node_sqlite3::Values::Field::type"

.PP
Definition at line \fB27\fP of file \fBstatement\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
