.TH "node_sqlite3::Backup::Baton" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Backup::Baton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <backup\&.h>\fP
.PP
Inherited by \fBnode_sqlite3::Backup::StepBaton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaton\fP (\fBBackup\fP *backup_, \fBNapi::Function\fP cb_)"
.br
.ti -1c
.RI "virtual \fB~Baton\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "napi_async_work \fBrequest\fP = NULL"
.br
.ti -1c
.RI "\fBBackup\fP * \fBbackup\fP"
.br
.ti -1c
.RI "\fBNapi::FunctionReference\fP \fBcallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB98\fP of file \fBbackup\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Backup::Baton::Baton (\fBBackup\fP * backup_, \fBNapi::Function\fP cb_)\fR [inline]\fP"

.PP
Definition at line \fB103\fP of file \fBbackup\&.h\fP\&.
.SS "virtual node_sqlite3::Backup::Baton::~Baton ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Definition at line \fB107\fP of file \fBbackup\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBackup\fP* node_sqlite3::Backup::Baton::backup"

.PP
Definition at line \fB100\fP of file \fBbackup\&.h\fP\&.
.SS "\fBNapi::FunctionReference\fP node_sqlite3::Backup::Baton::callback"

.PP
Definition at line \fB101\fP of file \fBbackup\&.h\fP\&.
.SS "napi_async_work node_sqlite3::Backup::Baton::request = NULL"

.PP
Definition at line \fB99\fP of file \fBbackup\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
