.TH "node_sqlite3::Statement::RowBaton" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Statement::RowBaton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <statement\&.h>\fP
.PP
Inherits \fBnode_sqlite3::Statement::Baton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRowBaton\fP (\fBStatement\fP *stmt_, \fBNapi::Function\fP cb_)"
.br
.ti -1c
.RI "virtual \fB~RowBaton\fP () override=default"
.br
.in -1c

Public Member Functions inherited from \fBnode_sqlite3::Statement::Baton\fP
.in +1c
.ti -1c
.RI "\fBBaton\fP (\fBStatement\fP *stmt_, \fBNapi::Function\fP cb_)"
.br
.ti -1c
.RI "virtual \fB~Baton\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRow\fP \fBrow\fP"
.br
.in -1c

Public Attributes inherited from \fBnode_sqlite3::Statement::Baton\fP
.in +1c
.ti -1c
.RI "napi_async_work \fBrequest\fP = NULL"
.br
.ti -1c
.RI "\fBStatement\fP * \fBstmt\fP"
.br
.ti -1c
.RI "\fBNapi::FunctionReference\fP \fBcallback\fP"
.br
.ti -1c
.RI "\fBParameters\fP \fBparameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB101\fP of file \fBstatement\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Statement::RowBaton::RowBaton (\fBStatement\fP * stmt_, \fBNapi::Function\fP cb_)\fR [inline]\fP"

.PP
Definition at line \fB102\fP of file \fBstatement\&.h\fP\&.
.SS "virtual node_sqlite3::Statement::RowBaton::~RowBaton ()\fR [override]\fP, \fR [virtual]\fP, \fR [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBRow\fP node_sqlite3::Statement::RowBaton::row"

.PP
Definition at line \fB104\fP of file \fBstatement\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
