.TH "backend/node_modules/sqlite3/src/node_sqlite3.cc" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/sqlite3/src/node_sqlite3.cc
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <string>\fP
.br
\fR#include <sqlite3\&.h>\fP
.br
\fR#include 'macros\&.h'\fP
.br
\fR#include 'database\&.h'\fP
.br
\fR#include 'statement\&.h'\fP
.br
\fR#include 'backup\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBsqlite_code_string\fP (int code)"
.br
.ti -1c
.RI "const char * \fBsqlite_authorizer_string\fP (int type)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char * sqlite_authorizer_string (int type)"

.PP
Definition at line \fB119\fP of file \fBnode_sqlite3\&.cc\fP\&.
.SS "const char * sqlite_code_string (int code)"

.PP
Definition at line \fB84\fP of file \fBnode_sqlite3\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
