.TH "node_sqlite3::Backup::StepBaton" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Backup::StepBaton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <backup\&.h>\fP
.PP
Inherits \fBnode_sqlite3::Backup::Baton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStepBaton\fP (\fBBackup\fP *backup_, \fBNapi::Function\fP cb_, int pages_)"
.br
.ti -1c
.RI "virtual \fB~StepBaton\fP () override=default"
.br
.in -1c

Public Member Functions inherited from \fBnode_sqlite3::Backup::Baton\fP
.in +1c
.ti -1c
.RI "\fBBaton\fP (\fBBackup\fP *backup_, \fBNapi::Function\fP cb_)"
.br
.ti -1c
.RI "virtual \fB~Baton\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpages\fP"
.br
.ti -1c
.RI "std::set< int > \fBretryErrorsSet\fP"
.br
.in -1c

Public Attributes inherited from \fBnode_sqlite3::Backup::Baton\fP
.in +1c
.ti -1c
.RI "napi_async_work \fBrequest\fP = NULL"
.br
.ti -1c
.RI "\fBBackup\fP * \fBbackup\fP"
.br
.ti -1c
.RI "\fBNapi::FunctionReference\fP \fBcallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB133\fP of file \fBbackup\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Backup::StepBaton::StepBaton (\fBBackup\fP * backup_, \fBNapi::Function\fP cb_, int pages_)\fR [inline]\fP"

.PP
Definition at line \fB136\fP of file \fBbackup\&.h\fP\&.
.SS "virtual node_sqlite3::Backup::StepBaton::~StepBaton ()\fR [override]\fP, \fR [virtual]\fP, \fR [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int node_sqlite3::Backup::StepBaton::pages"

.PP
Definition at line \fB134\fP of file \fBbackup\&.h\fP\&.
.SS "std::set<int> node_sqlite3::Backup::StepBaton::retryErrorsSet"

.PP
Definition at line \fB135\fP of file \fBbackup\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
