.TH "node_sqlite3::Values::Blob" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Values::Blob
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <statement\&.h>\fP
.PP
Inherits \fBnode_sqlite3::Values::Field\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T > \fBBlob\fP (T _name, size_t len, const void *val)"
.br
.ti -1c
.RI "virtual \fB~Blob\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBnode_sqlite3::Values::Field\fP
.in +1c
.ti -1c
.RI "\fBField\fP (unsigned short _index, unsigned short _type=SQLITE_NULL)"
.br
.ti -1c
.RI "\fBField\fP (const char *_name, unsigned short _type=SQLITE_NULL)"
.br
.ti -1c
.RI "virtual \fB~Field\fP ()=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.in -1c

Public Attributes inherited from \fBnode_sqlite3::Values::Field\fP
.in +1c
.ti -1c
.RI "unsigned short \fBtype\fP"
.br
.ti -1c
.RI "unsigned short \fBindex\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB55\fP of file \fBstatement\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > node_sqlite3::Values::Blob::Blob (T _name, size_t len, const void * val)\fR [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBstatement\&.h\fP\&.
.SS "virtual node_sqlite3::Values::Blob::~Blob ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Definition at line \fB62\fP of file \fBstatement\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int node_sqlite3::Values::Blob::length"

.PP
Definition at line \fB65\fP of file \fBstatement\&.h\fP\&.
.SS "char* node_sqlite3::Values::Blob::value"

.PP
Definition at line \fB66\fP of file \fBstatement\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
