.TH "node_sqlite3::Database::UpdateInfo" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Database::UpdateInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <database\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBdatabase\fP"
.br
.ti -1c
.RI "std::string \fBtable\fP"
.br
.ti -1c
.RI "sqlite3_int64 \fBrowid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB109\fP of file \fBdatabase\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string node_sqlite3::Database::UpdateInfo::database"

.PP
Definition at line \fB111\fP of file \fBdatabase\&.h\fP\&.
.SS "sqlite3_int64 node_sqlite3::Database::UpdateInfo::rowid"

.PP
Definition at line \fB113\fP of file \fBdatabase\&.h\fP\&.
.SS "std::string node_sqlite3::Database::UpdateInfo::table"

.PP
Definition at line \fB112\fP of file \fBdatabase\&.h\fP\&.
.SS "int node_sqlite3::Database::UpdateInfo::type"

.PP
Definition at line \fB110\fP of file \fBdatabase\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
