.TH "node_sqlite3::Statement::Async" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Statement::Async
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <statement\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAsync\fP (\fBStatement\fP *st, uv_async_cb async_cb)"
.br
.ti -1c
.RI "\fB~Async\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uv_async_t \fBwatcher\fP"
.br
.ti -1c
.RI "\fBStatement\fP * \fBstmt\fP"
.br
.ti -1c
.RI "\fBRows\fP \fBdata\fP"
.br
.ti -1c
.RI "\fBNODE_SQLITE3_MUTEX_t\fP"
.br
.ti -1c
.RI "bool \fBcompleted\fP"
.br
.ti -1c
.RI "int \fBretrieved\fP"
.br
.ti -1c
.RI "\fBNapi::FunctionReference\fP \fBitem_cb\fP"
.br
.ti -1c
.RI "\fBNapi::FunctionReference\fP \fBcompleted_cb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB161\fP of file \fBstatement\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Statement::Async::Async (\fBStatement\fP * st, uv_async_cb async_cb)\fR [inline]\fP"

.PP
Definition at line \fB174\fP of file \fBstatement\&.h\fP\&.
.SS "node_sqlite3::Statement::Async::~Async ()\fR [inline]\fP"

.PP
Definition at line \fB184\fP of file \fBstatement\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool node_sqlite3::Statement::Async::completed"

.PP
Definition at line \fB166\fP of file \fBstatement\&.h\fP\&.
.SS "\fBNapi::FunctionReference\fP node_sqlite3::Statement::Async::completed_cb"

.PP
Definition at line \fB172\fP of file \fBstatement\&.h\fP\&.
.SS "\fBRows\fP node_sqlite3::Statement::Async::data"

.PP
Definition at line \fB164\fP of file \fBstatement\&.h\fP\&.
.SS "\fBNapi::FunctionReference\fP node_sqlite3::Statement::Async::item_cb"

.PP
Definition at line \fB171\fP of file \fBstatement\&.h\fP\&.
.SS "node_sqlite3::Statement::Async::NODE_SQLITE3_MUTEX_t"

.PP
Definition at line \fB165\fP of file \fBstatement\&.h\fP\&.
.SS "int node_sqlite3::Statement::Async::retrieved"

.PP
Definition at line \fB167\fP of file \fBstatement\&.h\fP\&.
.SS "\fBStatement\fP* node_sqlite3::Statement::Async::stmt"

.PP
Definition at line \fB163\fP of file \fBstatement\&.h\fP\&.
.SS "uv_async_t node_sqlite3::Statement::Async::watcher"

.PP
Definition at line \fB162\fP of file \fBstatement\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
