.TH "node_sqlite3::Backup::Call" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Backup::Call
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <backup\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCall\fP (\fBWork_Callback\fP cb_, \fBBaton\fP *baton_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWork_Callback\fP \fBcallback\fP"
.br
.ti -1c
.RI "\fBBaton\fP * \fBbaton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB143\fP of file \fBbackup\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Backup::Call::Call (\fBWork_Callback\fP cb_, \fBBaton\fP * baton_)\fR [inline]\fP"

.PP
Definition at line \fB144\fP of file \fBbackup\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBaton\fP* node_sqlite3::Backup::Call::baton"

.PP
Definition at line \fB146\fP of file \fBbackup\&.h\fP\&.
.SS "\fBWork_Callback\fP node_sqlite3::Backup::Call::callback"

.PP
Definition at line \fB145\fP of file \fBbackup\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
