.TH "node_sqlite3::Database::LimitBaton" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Database::LimitBaton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <database\&.h>\fP
.PP
Inherits \fBnode_sqlite3::Database::Baton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLimitBaton\fP (\fBDatabase\fP *db_, \fBNapi::Function\fP cb_, int id_, int value_)"
.br
.ti -1c
.RI "virtual \fB~LimitBaton\fP () override=default"
.br
.in -1c

Public Member Functions inherited from \fBnode_sqlite3::Database::Baton\fP
.in +1c
.ti -1c
.RI "\fBBaton\fP (\fBDatabase\fP *db_, \fBNapi::Function\fP cb_)"
.br
.ti -1c
.RI "virtual \fB~Baton\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c

Public Attributes inherited from \fBnode_sqlite3::Database::Baton\fP
.in +1c
.ti -1c
.RI "napi_async_work \fBrequest\fP = NULL"
.br
.ti -1c
.RI "\fBDatabase\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBNapi::FunctionReference\fP \fBcallback\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB86\fP of file \fBdatabase\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Database::LimitBaton::LimitBaton (\fBDatabase\fP * db_, \fBNapi::Function\fP cb_, int id_, int value_)\fR [inline]\fP"

.PP
Definition at line \fB89\fP of file \fBdatabase\&.h\fP\&.
.SS "virtual node_sqlite3::Database::LimitBaton::~LimitBaton ()\fR [override]\fP, \fR [virtual]\fP, \fR [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int node_sqlite3::Database::LimitBaton::id"

.PP
Definition at line \fB87\fP of file \fBdatabase\&.h\fP\&.
.SS "int node_sqlite3::Database::LimitBaton::value"

.PP
Definition at line \fB88\fP of file \fBdatabase\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
