.TH "node_sqlite3::Database::Call" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Database::Call
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <database\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCall\fP (\fBWork_Callback\fP cb_, \fBBaton\fP *baton_, bool exclusive_=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWork_Callback\fP \fBcallback\fP"
.br
.ti -1c
.RI "bool \fBexclusive\fP"
.br
.ti -1c
.RI "\fBBaton\fP * \fBbaton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB96\fP of file \fBdatabase\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Database::Call::Call (\fBWork_Callback\fP cb_, \fBBaton\fP * baton_, bool exclusive_ = \fRfalse\fP)\fR [inline]\fP"

.PP
Definition at line \fB97\fP of file \fBdatabase\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBaton\fP* node_sqlite3::Database::Call::baton"

.PP
Definition at line \fB101\fP of file \fBdatabase\&.h\fP\&.
.SS "\fBWork_Callback\fP node_sqlite3::Database::Call::callback"

.PP
Definition at line \fB99\fP of file \fBdatabase\&.h\fP\&.
.SS "bool node_sqlite3::Database::Call::exclusive"

.PP
Definition at line \fB100\fP of file \fBdatabase\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
