.TH "node_sqlite3::Statement::PrepareBaton" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Statement::PrepareBaton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <statement\&.h>\fP
.PP
Inherits \fBnode_sqlite3::Database::Baton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrepareBaton\fP (\fBDatabase\fP *db_, \fBNapi::Function\fP cb_, \fBStatement\fP *stmt_)"
.br
.ti -1c
.RI "virtual \fB~PrepareBaton\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBnode_sqlite3::Database::Baton\fP
.in +1c
.ti -1c
.RI "\fBBaton\fP (\fBDatabase\fP *db_, \fBNapi::Function\fP cb_)"
.br
.ti -1c
.RI "virtual \fB~Baton\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStatement\fP * \fBstmt\fP"
.br
.ti -1c
.RI "std::string \fBsql\fP"
.br
.in -1c

Public Attributes inherited from \fBnode_sqlite3::Database::Baton\fP
.in +1c
.ti -1c
.RI "napi_async_work \fBrequest\fP = NULL"
.br
.ti -1c
.RI "\fBDatabase\fP * \fBdb\fP"
.br
.ti -1c
.RI "\fBNapi::FunctionReference\fP \fBcallback\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB136\fP of file \fBstatement\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node_sqlite3::Statement::PrepareBaton::PrepareBaton (\fBDatabase\fP * db_, \fBNapi::Function\fP cb_, \fBStatement\fP * stmt_)\fR [inline]\fP"

.PP
Definition at line \fB139\fP of file \fBstatement\&.h\fP\&.
.SS "virtual node_sqlite3::Statement::PrepareBaton::~PrepareBaton ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Definition at line \fB143\fP of file \fBstatement\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string node_sqlite3::Statement::PrepareBaton::sql"

.PP
Definition at line \fB138\fP of file \fBstatement\&.h\fP\&.
.SS "\fBStatement\fP* node_sqlite3::Statement::PrepareBaton::stmt"

.PP
Definition at line \fB137\fP of file \fBstatement\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
