.TH "node_sqlite3::Database::ProfileInfo" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Database::ProfileInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <database\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBsql\fP"
.br
.ti -1c
.RI "sqlite3_int64 \fBnsecs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB104\fP of file \fBdatabase\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "sqlite3_int64 node_sqlite3::Database::ProfileInfo::nsecs"

.PP
Definition at line \fB106\fP of file \fBdatabase\&.h\fP\&.
.SS "std::string node_sqlite3::Database::ProfileInfo::sql"

.PP
Definition at line \fB105\fP of file \fBdatabase\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
