.TH "node_sqlite3::Statement" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Statement
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <statement\&.h>\fP
.PP
Inherits \fBNapi::ObjectWrap< Statement >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAsync\fP"
.br
.ti -1c
.RI "struct \fBBaton\fP"
.br
.ti -1c
.RI "struct \fBCall\fP"
.br
.ti -1c
.RI "struct \fBEachBaton\fP"
.br
.ti -1c
.RI "struct \fBPrepareBaton\fP"
.br
.ti -1c
.RI "struct \fBRowBaton\fP"
.br
.ti -1c
.RI "struct \fBRowsBaton\fP"
.br
.ti -1c
.RI "struct \fBRunBaton\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void(* \fBWork_Callback\fP) (\fBBaton\fP *baton)"
.br
.in -1c

Public Types inherited from \fBNapi::ObjectWrap< Statement >\fP
.in +1c
.ti -1c
.RI "using \fBStaticVoidMethodCallback\fP"
.br
.ti -1c
.RI "using \fBStaticMethodCallback\fP"
.br
.ti -1c
.RI "using \fBStaticGetterCallback\fP"
.br
.ti -1c
.RI "using \fBStaticSetterCallback\fP"
.br
.ti -1c
.RI "using \fBPropertyDescriptor\fP"
.br
.in -1c

Public Types inherited from \fBNapi::InstanceWrap< Statement >\fP
.in +1c
.ti -1c
.RI "using \fBInstanceVoidMethodCallback\fP"
.br
.ti -1c
.RI "using \fBInstanceMethodCallback\fP"
.br
.ti -1c
.RI "using \fBInstanceGetterCallback\fP"
.br
.ti -1c
.RI "using \fBInstanceSetterCallback\fP"
.br
.ti -1c
.RI "using \fBPropertyDescriptor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatement\fP (const \fBNapi::CallbackInfo\fP &info)"
.br
.ti -1c
.RI "\fB~Statement\fP ()"
.br
.ti -1c
.RI "\fBNapi::Value\fP \fBFinalize_\fP (const \fBNapi::CallbackInfo\fP &info)"
.br
.in -1c

Public Member Functions inherited from \fBNapi::ObjectWrap< Statement >\fP
.in +1c
.ti -1c
.RI "\fBObjectWrap\fP (const \fBCallbackInfo\fP &callbackInfo)"
.br
.ti -1c
.RI "virtual \fB~ObjectWrap\fP ()"
.br
.ti -1c
.RI "\fBClassPropertyDescriptor\fP< Statement > \fBStaticMethod\fP (const char *utf8name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "\fBClassPropertyDescriptor\fP< Statement > \fBStaticMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "\fBClassPropertyDescriptor\fP< Statement > \fBStaticAccessor\fP (const char *utf8name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "\fBClassPropertyDescriptor\fP< Statement > \fBStaticAccessor\fP (\fBSymbol\fP name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "virtual void \fBFinalize\fP (\fBNapi::Env\fP env)"
.br
.in -1c

Public Member Functions inherited from \fBNapi::InstanceWrap< Statement >\fP
.in +1c
.ti -1c
.RI "\fBClassPropertyDescriptor\fP< Statement > \fBInstanceMethod\fP (const char *utf8name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "\fBClassPropertyDescriptor\fP< Statement > \fBInstanceMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "\fBClassPropertyDescriptor\fP< Statement > \fBInstanceAccessor\fP (const char *utf8name, napi_property_attributes attributes, void *data)"
.br
.ti -1c
.RI "\fBClassPropertyDescriptor\fP< Statement > \fBInstanceAccessor\fP (\fBSymbol\fP name, napi_property_attributes attributes, void *data)"
.br
.in -1c

Public Member Functions inherited from \fBNapi::Reference< Object >\fP
.in +1c
.ti -1c
.RI "\fBReference\fP ()"
.br
.ti -1c
.RI "\fBReference\fP (napi_env env, napi_ref ref)"
.br
.ti -1c
.RI "\fBReference\fP (\fBReference\fP< \fBObject\fP > &&other)"
.br
.ti -1c
.RI "\fB~Reference\fP ()"
.br
.ti -1c
.RI "\fBReference\fP< \fBObject\fP > & \fBoperator=\fP (\fBReference\fP< \fBObject\fP > &&other)"
.br
.ti -1c
.RI "\fBoperator napi_ref\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBReference\fP< \fBObject\fP > &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBReference\fP< \fBObject\fP > &other) const"
.br
.ti -1c
.RI "\fBNapi::Env\fP \fBEnv\fP () const"
.br
.ti -1c
.RI "bool \fBIsEmpty\fP () const"
.br
.ti -1c
.RI "\fBObject\fP \fBValue\fP () const"
.br
.ti -1c
.RI "uint32_t \fBRef\fP () const"
.br
.ti -1c
.RI "uint32_t \fBUnref\fP () const"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP (const \fBObject\fP &value, uint32_t refcount=0)"
.br
.ti -1c
.RI "void \fBSuppressDestruct\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNapi::Object\fP \fBInit\fP (\fBNapi::Env\fP env, \fBNapi::Object\fP exports)"
.br
.ti -1c
.RI "static \fBNapi::Value\fP \fBNew\fP (const \fBNapi::CallbackInfo\fP &info)"
.br
.in -1c

Static Public Member Functions inherited from \fBNapi::ObjectWrap< Statement >\fP
.in +1c
.ti -1c
.RI "static Statement * \fBUnwrap\fP (\fBObject\fP wrapper)"
.br
.ti -1c
.RI "static \fBFunction\fP \fBDefineClass\fP (\fBNapi::Env\fP env, const char *utf8name, const std::initializer_list< \fBPropertyDescriptor\fP > &properties, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBFunction\fP \fBDefineClass\fP (\fBNapi::Env\fP env, const char *utf8name, const std::vector< \fBPropertyDescriptor\fP > &properties, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticMethod\fP (const char *utf8name, \fBStaticVoidMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticMethod\fP (const char *utf8name, \fBStaticMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticMethod\fP (\fBSymbol\fP name, \fBStaticVoidMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticMethod\fP (\fBSymbol\fP name, \fBStaticMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticMethod\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticMethod\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticAccessor\fP (const char *utf8name, \fBStaticGetterCallback\fP getter, \fBStaticSetterCallback\fP setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticAccessor\fP (\fBSymbol\fP name, \fBStaticGetterCallback\fP getter, \fBStaticSetterCallback\fP setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticAccessor\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticAccessor\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticValue\fP (const char *utf8name, \fBNapi::Value\fP value, napi_property_attributes attributes=napi_default)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBStaticValue\fP (\fBSymbol\fP name, \fBNapi::Value\fP value, napi_property_attributes attributes=napi_default)"
.br
.ti -1c
.RI "static \fBNapi::Value\fP \fBOnCalledAsFunction\fP (const \fBNapi::CallbackInfo\fP &callbackInfo)"
.br
.in -1c

Static Public Member Functions inherited from \fBNapi::InstanceWrap< Statement >\fP
.in +1c
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (const char *utf8name, \fBInstanceVoidMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (const char *utf8name, \fBInstanceMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (\fBSymbol\fP name, \fBInstanceVoidMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (\fBSymbol\fP name, \fBInstanceMethodCallback\fP method, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceMethod\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceAccessor\fP (const char *utf8name, \fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceAccessor\fP (\fBSymbol\fP name, \fBInstanceGetterCallback\fP getter, \fBInstanceSetterCallback\fP setter, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceAccessor\fP (const char *utf8name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceAccessor\fP (\fBSymbol\fP name, napi_property_attributes attributes=napi_default, void *data=nullptr)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceValue\fP (const char *utf8name, \fBNapi::Value\fP value, napi_property_attributes attributes=napi_default)"
.br
.ti -1c
.RI "static \fBPropertyDescriptor\fP \fBInstanceValue\fP (\fBSymbol\fP name, \fBNapi::Value\fP value, napi_property_attributes attributes=napi_default)"
.br
.in -1c

Static Public Member Functions inherited from \fBNapi::Reference< Object >\fP
.in +1c
.ti -1c
.RI "static \fBReference\fP< \fBObject\fP > \fBNew\fP (const \fBObject\fP &value, uint32_t initialRefcount=0)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBFinalize_\fP ()"
.br
.ti -1c
.RI "template<class T > std::unique_ptr< \fBValues::Field\fP > \fBBindParameter\fP (const \fBNapi::Value\fP source, T pos)"
.br
.ti -1c
.RI "template<class T > T * \fBBind\fP (const \fBNapi::CallbackInfo\fP &info, int start=0, int end=\-1)"
.br
.ti -1c
.RI "bool \fBBind\fP (const \fBParameters\fP &parameters)"
.br
.ti -1c
.RI "void \fBSchedule\fP (\fBWork_Callback\fP callback, \fBBaton\fP *baton)"
.br
.ti -1c
.RI "void \fBProcess\fP ()"
.br
.ti -1c
.RI "void \fBCleanQueue\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBNapi::Reference< Object >\fP
.in +1c
.ti -1c
.RI "\fBReference\fP (const \fBReference\fP< \fBObject\fP > &)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBWork_BeginPrepare\fP (\fBDatabase::Baton\fP *baton)"
.br
.ti -1c
.RI "static void \fBWork_Prepare\fP (napi_env env, void *data)"
.br
.ti -1c
.RI "static void \fBWork_AfterPrepare\fP (napi_env env, napi_status \fBstatus\fP, void *data)"
.br
.ti -1c
.RI "static void \fBAsyncEach\fP (uv_async_t *handle)"
.br
.ti -1c
.RI "static void \fBCloseCallback\fP (uv_handle_t *handle)"
.br
.ti -1c
.RI "static void \fBFinalize_\fP (\fBBaton\fP *baton)"
.br
.ti -1c
.RI "static void \fBGetRow\fP (\fBRow\fP *row, sqlite3_stmt *stmt)"
.br
.ti -1c
.RI "static \fBNapi::Value\fP \fBRowToJS\fP (\fBNapi::Env\fP env, \fBRow\fP *row)"
.br
.ti -1c
.RI "template<class T > static void \fBError\fP (T *baton)"
.br
.in -1c

Static Protected Member Functions inherited from \fBNapi::InstanceWrap< Statement >\fP
.in +1c
.ti -1c
.RI "static void \fBAttachPropData\fP (napi_env env, napi_value value, const napi_property_descriptor *prop)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBDatabase\fP * \fBdb\fP"
.br
.ti -1c
.RI "sqlite3_stmt * \fB_handle\fP = NULL"
.br
.ti -1c
.RI "int \fBstatus\fP = SQLITE_OK"
.br
.ti -1c
.RI "bool \fBprepared\fP = false"
.br
.ti -1c
.RI "bool \fBlocked\fP = true"
.br
.ti -1c
.RI "bool \fBfinalized\fP = false"
.br
.ti -1c
.RI "std::queue< \fBCall\fP * > \fBqueue\fP"
.br
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.in -1c

Protected Attributes inherited from \fBNapi::Reference< Object >\fP
.in +1c
.ti -1c
.RI "napi_env \fB_env\fP"
.br
.RI "!cond INTERNAL "
.ti -1c
.RI "napi_ref \fB_ref\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB78\fP of file \fBstatement\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef void(* node_sqlite3::Statement::Work_Callback) (\fBBaton\fP *baton)"

.PP
Definition at line \fB153\fP of file \fBstatement\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Statement::Statement (const \fBNapi::CallbackInfo\fP & info)"

.PP
Definition at line \fB91\fP of file \fBstatement\&.cc\fP\&.
.SS "node_sqlite3::Statement::~Statement ()\fR [inline]\fP"

.PP
Definition at line \fB194\fP of file \fBstatement\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Statement::AsyncEach (uv_async_t * handle)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB692\fP of file \fBstatement\&.cc\fP\&.
.SS "template<class T > T * Statement::Bind (const \fBNapi::CallbackInfo\fP & info, int start = \fR0\fP, int end = \fR\-1\fP)\fR [protected]\fP"

.PP
Definition at line \fB223\fP of file \fBstatement\&.cc\fP\&.
.SS "bool Statement::Bind (const \fBParameters\fP & parameters)\fR [protected]\fP"

.PP
Definition at line \fB279\fP of file \fBstatement\&.cc\fP\&.
.SS "template<class T > std::unique_ptr< \fBValues::Field\fP > Statement::BindParameter (const \fBNapi::Value\fP source, T pos)\fR [inline]\fP, \fR [protected]\fP"

.PP
Definition at line \fB179\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::CleanQueue ()\fR [protected]\fP"

.PP
Definition at line \fB897\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::CloseCallback (uv_handle_t * handle)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB685\fP of file \fBstatement\&.cc\fP\&.
.SS "template<class T > void Statement::Error (T * baton)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB68\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::Finalize_ ()\fR [protected]\fP"

.PP
Definition at line \fB886\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::Finalize_ (\fBBaton\fP * baton)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB872\fP of file \fBstatement\&.cc\fP\&.
.SS "\fBNapi::Value\fP Statement::Finalize_ (const \fBNapi::CallbackInfo\fP & info)"

.PP
Definition at line \fB861\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::GetRow (\fBRow\fP * row, sqlite3_stmt * stmt)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB825\fP of file \fBstatement\&.cc\fP\&.
.SS "\fBNapi::Object\fP Statement::Init (\fBNapi::Env\fP env, \fBNapi::Object\fP exports)\fR [static]\fP"

.PP
Definition at line \fB11\fP of file \fBstatement\&.cc\fP\&.
.SS "static \fBNapi::Value\fP node_sqlite3::Statement::New (const \fBNapi::CallbackInfo\fP & info)\fR [static]\fP"

.SS "void Statement::Process ()\fR [protected]\fP"

.PP
Definition at line \fB42\fP of file \fBstatement\&.cc\fP\&.
.SS "\fBNapi::Value\fP Statement::RowToJS (\fBNapi::Env\fP env, \fBRow\fP * row)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB790\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::Schedule (\fBWork_Callback\fP callback, \fBBaton\fP * baton)\fR [protected]\fP"

.PP
Definition at line \fB55\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::Work_AfterPrepare (napi_env env, napi_status status, void * data)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB155\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::Work_BeginPrepare (\fBDatabase::Baton\fP * baton)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB123\fP of file \fBstatement\&.cc\fP\&.
.SS "void Statement::Work_Prepare (napi_env env, void * data)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB131\fP of file \fBstatement\&.cc\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "sqlite3_stmt* node_sqlite3::Statement::_handle = NULL\fR [protected]\fP"

.PP
Definition at line \fB232\fP of file \fBstatement\&.h\fP\&.
.SS "\fBDatabase\fP* node_sqlite3::Statement::db\fR [protected]\fP"

.PP
Definition at line \fB230\fP of file \fBstatement\&.h\fP\&.
.SS "bool node_sqlite3::Statement::finalized = false\fR [protected]\fP"

.PP
Definition at line \fB236\fP of file \fBstatement\&.h\fP\&.
.SS "bool node_sqlite3::Statement::locked = true\fR [protected]\fP"

.PP
Definition at line \fB235\fP of file \fBstatement\&.h\fP\&.
.SS "std::string node_sqlite3::Statement::message\fR [protected]\fP"

.PP
Definition at line \fB239\fP of file \fBstatement\&.h\fP\&.
.SS "bool node_sqlite3::Statement::prepared = false\fR [protected]\fP"

.PP
Definition at line \fB234\fP of file \fBstatement\&.h\fP\&.
.SS "std::queue<\fBCall\fP*> node_sqlite3::Statement::queue\fR [protected]\fP"

.PP
Definition at line \fB238\fP of file \fBstatement\&.h\fP\&.
.SS "int node_sqlite3::Statement::status = SQLITE_OK\fR [protected]\fP"

.PP
Definition at line \fB233\fP of file \fBstatement\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
