.TH "node_sqlite3" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBValues\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBackup\fP"
.br
.ti -1c
.RI "class \fBDatabase\fP"
.br
.ti -1c
.RI "class \fBStatement\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< std::unique_ptr< \fBValues::Field\fP > > \fBRow\fP"
.br
.ti -1c
.RI "typedef std::vector< std::unique_ptr< \fBRow\fP > > \fBRows\fP"
.br
.ti -1c
.RI "typedef \fBRow\fP \fBParameters\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBRow\fP \fBnode_sqlite3::Parameters\fP"

.PP
Definition at line \fB74\fP of file \fBstatement\&.h\fP\&.
.SS "typedef std::vector<std::unique_ptr<\fBValues::Field\fP> > \fBnode_sqlite3::Row\fP"

.PP
Definition at line \fB72\fP of file \fBstatement\&.h\fP\&.
.SS "typedef std::vector<std::unique_ptr<\fBRow\fP> > \fBnode_sqlite3::Rows\fP"

.PP
Definition at line \fB73\fP of file \fBstatement\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
