.TH "node_sqlite3::Values::Integer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_sqlite3::Values::Integer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <statement\&.h>\fP
.PP
Inherits \fBnode_sqlite3::Values::Field\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T > \fBInteger\fP (T _name, int64_t val)"
.br
.ti -1c
.RI "virtual \fB~Integer\fP () override=default"
.br
.in -1c

Public Member Functions inherited from \fBnode_sqlite3::Values::Field\fP
.in +1c
.ti -1c
.RI "\fBField\fP (unsigned short _index, unsigned short _type=SQLITE_NULL)"
.br
.ti -1c
.RI "\fBField\fP (const char *_name, unsigned short _type=SQLITE_NULL)"
.br
.ti -1c
.RI "virtual \fB~Field\fP ()=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBvalue\fP"
.br
.in -1c

Public Attributes inherited from \fBnode_sqlite3::Values::Field\fP
.in +1c
.ti -1c
.RI "unsigned short \fBtype\fP"
.br
.ti -1c
.RI "unsigned short \fBindex\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBstatement\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > node_sqlite3::Values::Integer::Integer (T _name, int64_t val)\fR [inline]\fP"

.PP
Definition at line \fB35\fP of file \fBstatement\&.h\fP\&.
.SS "virtual node_sqlite3::Values::Integer::~Integer ()\fR [override]\fP, \fR [virtual]\fP, \fR [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int64_t node_sqlite3::Values::Integer::value"

.PP
Definition at line \fB37\fP of file \fBstatement\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
