.TH "backend/node_modules/node-gyp/gyp/tools/pretty_vcproj.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/tools/pretty_vcproj.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpretty_vcproj\&.CmpTuple\fP"
.br
.ti -1c
.RI "class \fBpretty_vcproj\&.CmpNode\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpretty_vcproj\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpretty_vcproj\&.cmp\fP (x, y)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.PrettyPrintNode\fP (node, indent=0)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.FlattenFilter\fP (node)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.FixFilenames\fP (filenames, current_directory)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.AbsoluteNode\fP (node)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.CleanupVcproj\fP (node)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.GetConfiguationNodes\fP (vcproj)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.GetChildrenVsprops\fP (filename)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.SeekToNode\fP (node1, child2)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.MergeAttributes\fP (node1, node2)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.MergeProperties\fP (node1, node2)"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.main\fP (argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpretty_vcproj\&.ARGUMENTS\fP = None"
.br
.ti -1c
.RI "\fBpretty_vcproj\&.REPLACEMENTS\fP = dict()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
