.TH "backend/node_modules/node-gyp/gyp/tools/pretty_gyp.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/tools/pretty_gyp.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpretty_gyp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpretty_gyp\&.comment_replace\fP (matchobj)"
.br
.ti -1c
.RI "\fBpretty_gyp\&.mask_comments\fP (input)"
.br
.ti -1c
.RI "\fBpretty_gyp\&.quote_replace\fP (matchobj)"
.br
.ti -1c
.RI "\fBpretty_gyp\&.mask_quotes\fP (input)"
.br
.ti -1c
.RI "\fBpretty_gyp\&.do_split\fP (input, masked_input, search_re)"
.br
.ti -1c
.RI "\fBpretty_gyp\&.split_double_braces\fP (input)"
.br
.ti -1c
.RI "\fBpretty_gyp\&.count_braces\fP (line)"
.br
.ti -1c
.RI "\fBpretty_gyp\&.prettyprint_input\fP (lines)"
.br
.ti -1c
.RI "\fBpretty_gyp\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpretty_gyp\&.COMMENT_RE\fP = re\&.compile(r'\\s*#\&.*')"
.br
.ti -1c
.RI "str \fBpretty_gyp\&.QUOTE_RE_STR\fP = r'(?P<q>[\\''])(\&.*?)(?<![^\\\\][\\\\])(?P=q)'"
.br
.ti -1c
.RI "\fBpretty_gyp\&.QUOTE_RE\fP = re\&.compile(\fBQUOTE_RE_STR\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
