.TH "backend/node_modules/node-gyp/gyp/tools/pretty_sln.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/tools/pretty_sln.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpretty_sln\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpretty_sln\&.BuildProject\fP (project, built, projects, deps)"
.br
.ti -1c
.RI "\fBpretty_sln\&.ParseSolution\fP (solution_file)"
.br
.ti -1c
.RI "\fBpretty_sln\&.PrintDependencies\fP (projects, deps)"
.br
.ti -1c
.RI "\fBpretty_sln\&.PrintBuildOrder\fP (projects, deps)"
.br
.ti -1c
.RI "\fBpretty_sln\&.PrintVCProj\fP (projects)"
.br
.ti -1c
.RI "\fBpretty_sln\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
