.TH "pretty_sln" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pretty_sln
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBuildProject\fP (project, built, projects, deps)"
.br
.ti -1c
.RI "\fBParseSolution\fP (solution_file)"
.br
.ti -1c
.RI "\fBPrintDependencies\fP (projects, deps)"
.br
.ti -1c
.RI "\fBPrintBuildOrder\fP (projects, deps)"
.br
.ti -1c
.RI "\fBPrintVCProj\fP (projects)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Prints the information in a sln file in a diffable way\&.

   It first outputs each projects in alphabetical order with their
   dependencies\&.

   Then it outputs a possible build order\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "pretty_sln\&.BuildProject ( project,  built,  projects,  deps)"

.PP
Definition at line \fB24\fP of file \fBpretty_sln\&.py\fP\&.
.SS "pretty_sln\&.main ()"

.PP
Definition at line \fB165\fP of file \fBpretty_sln\&.py\fP\&.
.SS "pretty_sln\&.ParseSolution ( solution_file)"

.PP
Definition at line \fB35\fP of file \fBpretty_sln\&.py\fP\&.
.SS "pretty_sln\&.PrintBuildOrder ( projects,  deps)"

.PP
Definition at line \fB126\fP of file \fBpretty_sln\&.py\fP\&.
.SS "pretty_sln\&.PrintDependencies ( projects,  deps)"

.PP
Definition at line \fB109\fP of file \fBpretty_sln\&.py\fP\&.
.SS "pretty_sln\&.PrintVCProj ( projects)"

.PP
Definition at line \fB140\fP of file \fBpretty_sln\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
