.TH "pretty_vcproj.CmpTuple" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pretty_vcproj.CmpTuple
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__call__\fP (self, x, y)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Compare function between 2 tuple\&.
.fi
.PP
 
.PP
Definition at line \fB31\fP of file \fBpretty_vcproj\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "pretty_vcproj\&.CmpTuple\&.__call__ ( self,  x,  y)"

.PP
Definition at line \fB34\fP of file \fBpretty_vcproj\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
