.TH "QueryParser" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueryParser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmatches\fP ($document, $query)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2\fP of file \fBQueryParser\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "QueryParser::matches ( $document,  $query)"

.PP
Definition at line \fB4\fP of file \fBQueryParser\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
