.TH "redirect.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
redirect.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$message\fP = 'This is a \fBredirect\fP page\&. You will be redirected to the \fBlogin\fP page in a few minutes\&.'"
.br
.ti -1c
.RI "\fB$url\fP = '\&./login\&.php'"
.br
.ti -1c
.RI "\fB$delay\fP = 180"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$delay = 180"

.PP
Definition at line \fB9\fP of file \fBredirect\&.php\fP\&.
.SS "$message = 'This is a \fBredirect\fP page\&. You will be redirected to the \fBlogin\fP page in a few minutes\&.'"

.PP
Definition at line \fB3\fP of file \fBredirect\&.php\fP\&.
.SS "$url = '\&./login\&.php'"

.PP
Definition at line \fB6\fP of file \fBredirect\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
