.TH "setup" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBhere\fP = path\&.abspath(path\&.dirname(__file__))"
.br
.ti -1c
.RI "\fBlong_description\fP = in_file\&.read()"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBlong_description_content_type\fP"
.br
.ti -1c
.RI "\fBauthor\fP"
.br
.ti -1c
.RI "\fBauthor_email\fP"
.br
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBpackage_dir\fP"
.br
.ti -1c
.RI "\fBpackages\fP"
.br
.ti -1c
.RI "\fBentry_points\fP"
.br
.ti -1c
.RI "\fBpython_requires\fP"
.br
.ti -1c
.RI "\fBclassifiers\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "setup\&.author"

.PP
Definition at line \fB22\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.author_email"

.PP
Definition at line \fB23\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.classifiers"

.PP
Definition at line \fB29\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.description"

.PP
Definition at line \fB19\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.entry_points"

.PP
Definition at line \fB27\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.here = path\&.abspath(path\&.dirname(__file__))"

.PP
Definition at line \fB11\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.long_description = in_file\&.read()"

.PP
Definition at line \fB14\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.long_description_content_type"

.PP
Definition at line \fB21\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.name"

.PP
Definition at line \fB17\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.package_dir"

.PP
Definition at line \fB25\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.packages"

.PP
Definition at line \fB26\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.python_requires"

.PP
Definition at line \fB28\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.url"

.PP
Definition at line \fB24\fP of file \fBsetup\&.py\fP\&.
.SS "setup\&.version"

.PP
Definition at line \fB18\fP of file \fBsetup\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
