.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/simple_copy.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/simple_copy.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.simple_copy\&.Error\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.simple_copy\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.simple_copy\&.deepcopy\fP (x)"
.br
.ti -1c
.RI "\fBgyp\&.simple_copy\&._deepcopy_atomic\fP (x)"
.br
.ti -1c
.RI "\fBgyp\&.simple_copy\&._deepcopy_list\fP (x)"
.br
.ti -1c
.RI "\fBgyp\&.simple_copy\&._deepcopy_dict\fP (x)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBgyp\&.simple_copy\&._deepcopy_dispatch\fP = {}"
.br
.ti -1c
.RI "\fBgyp\&.simple_copy\&.types\fP = bool, float, int, str, type, type(None)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
