.TH "Controllers/site.config.php" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controllers/site.config.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBSITENAME\fP 'Akuma'"
.br
.ti -1c
.RI "const \fBSITE_DESCRIPTION\fP 'A fully featured data tool for data visualization , editing and more!'"
.br
.ti -1c
.RI "const \fBCompany\fP 'Odyssey'"
.br
.ti -1c
.RI "const \fBURL\fP 'http://localhost/akuma/'"
.br
.ti -1c
.RI "const \fBEmail\fP 'milton@odyssey\&.co\&.zw'"
.br
.ti -1c
.RI "const \fBGithub\fP 'https://www\&.github\&.com/nia\-cloud\-official'"
.br
.ti -1c
.RI "const \fBTel\fP '+263715212928'"
.br
.ti -1c
.RI "const \fBDeveloper\fP 'Milton Vafana'"
.br
.ti -1c
.RI "const \fBSERVER\fP 'localhost'"
.br
.ti -1c
.RI "const \fBUSER\fP 'root'"
.br
.ti -1c
.RI "const \fBPASS\fP '123'"
.br
.ti -1c
.RI "const \fBDBNAME\fP 'akuma'"
.br
.ti -1c
.RI "\fBtry\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const Company 'Odyssey'"

.PP
Definition at line \fB11\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const DBNAME 'akuma'"

.PP
Definition at line \fB20\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const Developer 'Milton Vafana'"

.PP
Definition at line \fB16\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const Email 'milton@odyssey\&.co\&.zw'"

.PP
Definition at line \fB13\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const Github 'https://www\&.github\&.com/nia\-cloud\-official'"

.PP
Definition at line \fB14\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const PASS '123'"

.PP
Definition at line \fB19\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const SERVER 'localhost'"

.PP
Definition at line \fB17\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const SITE_DESCRIPTION 'A fully featured data tool for data visualization , editing and more!'"

.PP
Definition at line \fB10\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const SITENAME 'Akuma'"
Author: Milton Vafana Email : miltonhyndrex@gmail.com Github: https://github.com/nia-cloud-official 
.PP
Definition at line \fB9\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const Tel '+263715212928'"

.PP
Definition at line \fB15\fP of file \fBsite\&.config\&.php\fP\&.
.SS "try"
\fBInitial value:\fP
.nf
{
    $pdo = new PDO("mysql:host=" \&. SERVER \&. ";dbname=" \&. DBNAME, USER, PASS)
.PP
.fi

.PP
Definition at line \fB22\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const URL 'http://localhost/akuma/'"

.PP
Definition at line \fB12\fP of file \fBsite\&.config\&.php\fP\&.
.SS "const USER 'root'"

.PP
Definition at line \fB18\fP of file \fBsite\&.config\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
