.TH "backend/node_modules/sqlite3/src/statement.cc" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/sqlite3/src/statement.cc
.SH SYNOPSIS
.br
.PP
\fR#include <cstring>\fP
.br
\fR#include <napi\&.h>\fP
.br
\fR#include <uv\&.h>\fP
.br
\fR#include 'macros\&.h'\fP
.br
\fR#include 'database\&.h'\fP
.br
\fR#include 'statement\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBOtherInstanceOf\fP (\fBNapi::Object\fP source, const char *object_type)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool OtherInstanceOf (\fBNapi::Object\fP source, const char * object_type)"

.PP
Definition at line \fB32\fP of file \fBstatement\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
