.TH "backend/node_modules/sqlite3/src/statement.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/sqlite3/src/statement.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdlib>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <string>\fP
.br
\fR#include <queue>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <sqlite3\&.h>\fP
.br
\fR#include <napi\&.h>\fP
.br
\fR#include <uv\&.h>\fP
.br
\fR#include 'database\&.h'\fP
.br
\fR#include 'threading\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBnode_sqlite3::Values::Field\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Values::Integer\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Values::Float\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Values::Text\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Values::Blob\fP"
.br
.ti -1c
.RI "class \fBnode_sqlite3::Statement\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Statement::Baton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Statement::RowBaton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Statement::RunBaton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Statement::RowsBaton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Statement::EachBaton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Statement::PrepareBaton\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Statement::Call\fP"
.br
.ti -1c
.RI "struct \fBnode_sqlite3::Statement::Async\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnode_sqlite3\fP"
.br
.ti -1c
.RI "namespace \fBnode_sqlite3::Values\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBField\fP \fBnode_sqlite3::Values::Null\fP"
.br
.ti -1c
.RI "typedef std::vector< std::unique_ptr< \fBValues::Field\fP > > \fBnode_sqlite3::Row\fP"
.br
.ti -1c
.RI "typedef std::vector< std::unique_ptr< \fBRow\fP > > \fBnode_sqlite3::Rows\fP"
.br
.ti -1c
.RI "typedef \fBRow\fP \fBnode_sqlite3::Parameters\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
