.TH "test-charmap" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test-charmap
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "test\-charmap\&.main ()"

.PP
Definition at line \fB10\fP of file \fBtest\-charmap\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
