.TH "test_gyp.Runner" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_gyp.Runner
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, \fBformats\fP, \fBtests\fP, \fBgyp_options\fP, \fBverbose\fP)"
.br
.ti -1c
.RI "\fBrun\fP (self)"
.br
.ti -1c
.RI "\fBrun_test\fP (self, test, fmt, i)"
.br
.ti -1c
.RI "\fBprint_\fP (self, msg)"
.br
.ti -1c
.RI "\fBerase_current_line\fP (self)"
.br
.ti -1c
.RI "\fBprint_results\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBformats\fP"
.br
.ti -1c
.RI "\fBtests\fP"
.br
.ti -1c
.RI "\fBverbose\fP"
.br
.ti -1c
.RI "\fBgyp_options\fP"
.br
.ti -1c
.RI "\fBfailures\fP"
.br
.ti -1c
.RI "\fBnum_tests\fP"
.br
.ti -1c
.RI "\fBfmt_str\fP"
.br
.ti -1c
.RI "\fBisatty\fP"
.br
.ti -1c
.RI "\fBenv\fP"
.br
.ti -1c
.RI "\fBhpos\fP"
.br
.ti -1c
.RI "\fBtook\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB167\fP of file \fBtest_gyp\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test_gyp\&.Runner\&.__init__ ( self,  formats,  tests,  gyp_options,  verbose)"

.PP
Definition at line \fB168\fP of file \fBtest_gyp\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "test_gyp\&.Runner\&.erase_current_line ( self)"

.PP
Definition at line \fB237\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.print_ ( self,  msg)"

.PP
Definition at line \fB228\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.print_results ( self)"

.PP
Definition at line \fB242\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.run ( self)"

.PP
Definition at line \fB181\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.run_test ( self,  test,  fmt,  i)"

.PP
Definition at line \fB195\fP of file \fBtest_gyp\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "test_gyp\&.Runner\&.env"

.PP
Definition at line \fB178\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.failures"

.PP
Definition at line \fB173\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.fmt_str"

.PP
Definition at line \fB176\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.formats"

.PP
Definition at line \fB169\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.gyp_options"

.PP
Definition at line \fB172\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.hpos"

.PP
Definition at line \fB179\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.isatty"

.PP
Definition at line \fB177\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.num_tests"

.PP
Definition at line \fB174\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.tests"

.PP
Definition at line \fB170\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.took"

.PP
Definition at line \fB193\fP of file \fBtest_gyp\&.py\fP\&.
.SS "test_gyp\&.Runner\&.verbose"

.PP
Definition at line \fB171\fP of file \fBtest_gyp\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
