.TH "backend/node_modules/sqlite3/src/threading.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/sqlite3/src/threading.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNODE_SQLITE3_MUTEX_t\fP   uv_mutex_t mutex;"
.br
.ti -1c
.RI "#define \fBNODE_SQLITE3_MUTEX_INIT\fP   uv_mutex_init(&mutex);"
.br
.ti -1c
.RI "#define \fBNODE_SQLITE3_MUTEX_LOCK\fP(m)   uv_mutex_lock(m);"
.br
.ti -1c
.RI "#define \fBNODE_SQLITE3_MUTEX_UNLOCK\fP(m)   uv_mutex_unlock(m);"
.br
.ti -1c
.RI "#define \fBNODE_SQLITE3_MUTEX_DESTROY\fP   uv_mutex_destroy(&mutex);"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NODE_SQLITE3_MUTEX_DESTROY   uv_mutex_destroy(&mutex);"

.PP
Definition at line \fB8\fP of file \fBthreading\&.h\fP\&.
.SS "#define NODE_SQLITE3_MUTEX_INIT   uv_mutex_init(&mutex);"

.PP
Definition at line \fB5\fP of file \fBthreading\&.h\fP\&.
.SS "#define NODE_SQLITE3_MUTEX_LOCK( m)   uv_mutex_lock(m);"

.PP
Definition at line \fB6\fP of file \fBthreading\&.h\fP\&.
.SS "#define NODE_SQLITE3_MUTEX_t   uv_mutex_t mutex;"

.PP
Definition at line \fB4\fP of file \fBthreading\&.h\fP\&.
.SS "#define NODE_SQLITE3_MUTEX_UNLOCK( m)   uv_mutex_unlock(m);"

.PP
Definition at line \fB7\fP of file \fBthreading\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
