.TH "backend/node_modules/node-gyp/update-gyp.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/update-gyp.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBupdate\-gyp\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBupdate\-gyp\&.BASE_URL\fP = 'https://github\&.com/nodejs/gyp\-next/archive/'"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.CHECKOUT_PATH\fP = os\&.path\&.dirname(os\&.path\&.realpath(__file__))"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.CHECKOUT_GYP_PATH\fP = os\&.path\&.join(\fBCHECKOUT_PATH\fP, 'gyp')"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.parser\fP = argparse\&.ArgumentParser()"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.help\fP"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.args\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "str \fBupdate\-gyp\&.tar_url\fP = \fBBASE_URL\fP + args\&.tag + '\&.tar\&.gz'"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.changed_files\fP = subprocess\&.check_output(['git', 'diff', '\-\-name\-only'])\&.strip()"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.tar_file\fP = os\&.path\&.join(tmp_dir, 'gyp\&.tar\&.gz')"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.unzip_target\fP = os\&.path\&.join(tmp_dir, 'gyp')"
.br
.ti -1c
.RI "\fBupdate\-gyp\&.cwd\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
