.TH "update-gyp" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
update-gyp
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBBASE_URL\fP = 'https://github\&.com/nodejs/gyp\-next/archive/'"
.br
.ti -1c
.RI "\fBCHECKOUT_PATH\fP = os\&.path\&.dirname(os\&.path\&.realpath(__file__))"
.br
.ti -1c
.RI "\fBCHECKOUT_GYP_PATH\fP = os\&.path\&.join(\fBCHECKOUT_PATH\fP, 'gyp')"
.br
.ti -1c
.RI "\fBparser\fP = argparse\&.ArgumentParser()"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.ti -1c
.RI "\fBargs\fP = parser\&.parse_args()"
.br
.ti -1c
.RI "str \fBtar_url\fP = \fBBASE_URL\fP + args\&.tag + '\&.tar\&.gz'"
.br
.ti -1c
.RI "\fBchanged_files\fP = subprocess\&.check_output(['git', 'diff', '\-\-name\-only'])\&.strip()"
.br
.ti -1c
.RI "\fBtar_file\fP = os\&.path\&.join(tmp_dir, 'gyp\&.tar\&.gz')"
.br
.ti -1c
.RI "\fBunzip_target\fP = os\&.path\&.join(tmp_dir, 'gyp')"
.br
.ti -1c
.RI "\fBcwd\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "update\-gyp\&.args = parser\&.parse_args()"

.PP
Definition at line \fB17\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "str update\-gyp\&.BASE_URL = 'https://github\&.com/nodejs/gyp\-next/archive/'"

.PP
Definition at line \fB11\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "update\-gyp\&.changed_files = subprocess\&.check_output(['git', 'diff', '\-\-name\-only'])\&.strip()"

.PP
Definition at line \fB21\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "update\-gyp\&.CHECKOUT_GYP_PATH = os\&.path\&.join(\fBCHECKOUT_PATH\fP, 'gyp')"

.PP
Definition at line \fB13\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "update\-gyp\&.CHECKOUT_PATH = os\&.path\&.dirname(os\&.path\&.realpath(__file__))"

.PP
Definition at line \fB12\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "update\-gyp\&.cwd"

.PP
Definition at line \fB45\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "update\-gyp\&.help"

.PP
Definition at line \fB16\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "update\-gyp\&.parser = argparse\&.ArgumentParser()"

.PP
Definition at line \fB15\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "update\-gyp\&.tar_file = os\&.path\&.join(tmp_dir, 'gyp\&.tar\&.gz')"

.PP
Definition at line \fB26\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "str update\-gyp\&.tar_url = \fBBASE_URL\fP + args\&.tag + '\&.tar\&.gz'"

.PP
Definition at line \fB19\fP of file \fBupdate\-gyp\&.py\fP\&.
.SS "update\-gyp\&.unzip_target = os\&.path\&.join(tmp_dir, 'gyp')"

.PP
Definition at line \fB27\fP of file \fBupdate\-gyp\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
