.TH "User" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "int \fBage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBdatabase\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int User::age"

.PP
Definition at line \fB8\fP of file \fBdatabase\&.cpp\fP\&.
.SS "std::string User::name"

.PP
Definition at line \fB7\fP of file \fBdatabase\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
