.TH "VisualStudioConfiguration.SetupConfigurationClass" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.SetupConfigurationClass
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line \fB184\fP of file \fBFind\-VisualStudio\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
