.TH "VisualStudioConfiguration.SetupConfiguration" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.SetupConfiguration
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisualStudioConfiguration\&.ISetupConfiguration2\fP, and \fBVisualStudioConfiguration\&.ISetupConfiguration\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBVisualStudioConfiguration\&.ISetupConfiguration2\fP
.in +1c
.ti -1c
.RI "\fBIEnumSetupInstances\fP \fBEnumInstances\fP ()"
.br
.ti -1c
.RI "\fBISetupInstance\fP \fBGetInstanceForCurrentProcess\fP ()"
.br
.ti -1c
.RI "\fBISetupInstance\fP \fBGetInstanceForPath\fP ([MarshalAs(UnmanagedType\&.LPWStr), In] string path)"
.br
.ti -1c
.RI "\fBIEnumSetupInstances\fP \fBEnumAllInstances\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB177\fP of file \fBFind\-VisualStudio\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
