.TH "VisualStudioConfiguration.IEnumSetupInstances" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.IEnumSetupInstances
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNext\fP ([MarshalAs(UnmanagedType\&.U4), In] int celt, [MarshalAs(UnmanagedType\&.LPArray, ArraySubType=UnmanagedType\&.Interface), Out] \fBISetupInstance\fP[] rgelt, [MarshalAs(UnmanagedType\&.U4)] out int pceltFetched)"
.br
.ti -1c
.RI "void \fBSkip\fP ([MarshalAs(UnmanagedType\&.U4), In] int celt)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "\fBIEnumSetupInstances\fP \fBClone\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBFind\-VisualStudio\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIEnumSetupInstances\fP VisualStudioConfiguration\&.IEnumSetupInstances\&.Clone ()"

.SS "void VisualStudioConfiguration\&.IEnumSetupInstances\&.Next ([MarshalAs(UnmanagedType\&.U4), In] int celt, [MarshalAs(UnmanagedType\&.LPArray, ArraySubType=UnmanagedType\&.Interface), Out] \fBISetupInstance\fP[] rgelt, [MarshalAs(UnmanagedType\&.U4)] out int pceltFetched)"

.SS "void VisualStudioConfiguration\&.IEnumSetupInstances\&.Reset ()"

.SS "void VisualStudioConfiguration\&.IEnumSetupInstances\&.Skip ([MarshalAs(UnmanagedType\&.U4), In] int celt)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
