.TH "VisualStudioConfiguration.ISetupConfiguration2" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.ISetupConfiguration2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisualStudioConfiguration\&.ISetupConfiguration\fP\&.
.PP
Inherited by \fBVisualStudioConfiguration\&.SetupConfiguration\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIEnumSetupInstances\fP \fBEnumInstances\fP ()"
.br
.ti -1c
.RI "\fBISetupInstance\fP \fBGetInstanceForCurrentProcess\fP ()"
.br
.ti -1c
.RI "\fBISetupInstance\fP \fBGetInstanceForPath\fP ([MarshalAs(UnmanagedType\&.LPWStr), In] string path)"
.br
.ti -1c
.RI "\fBIEnumSetupInstances\fP \fBEnumAllInstances\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB55\fP of file \fBFind\-VisualStudio\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIEnumSetupInstances\fP VisualStudioConfiguration\&.ISetupConfiguration2\&.EnumAllInstances ()"

.SS "\fBIEnumSetupInstances\fP VisualStudioConfiguration\&.ISetupConfiguration2\&.EnumInstances ()"

.SS "\fBISetupInstance\fP VisualStudioConfiguration\&.ISetupConfiguration2\&.GetInstanceForCurrentProcess ()"

.SS "\fBISetupInstance\fP VisualStudioConfiguration\&.ISetupConfiguration2\&.GetInstanceForPath ([MarshalAs(UnmanagedType\&.LPWStr), In] string path)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
