.TH "VisualStudioConfiguration.ISetupInstance2" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.ISetupInstance2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisualStudioConfiguration\&.ISetupInstance\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetInstanceId\fP ()"
.br
.ti -1c
.RI "System\&.Runtime\&.InteropServices\&.ComTypes\&.FILETIME \fBGetInstallDate\fP ()"
.br
.ti -1c
.RI "string \fBGetInstallationName\fP ()"
.br
.ti -1c
.RI "string \fBGetInstallationPath\fP ()"
.br
.ti -1c
.RI "string \fBGetInstallationVersion\fP ()"
.br
.ti -1c
.RI "string \fBGetDisplayName\fP ([MarshalAs(UnmanagedType\&.U4), In] int lcid)"
.br
.ti -1c
.RI "string \fBGetDescription\fP ([MarshalAs(UnmanagedType\&.U4), In] int lcid)"
.br
.ti -1c
.RI "string \fBResolvePath\fP ([MarshalAs(UnmanagedType\&.LPWStr), In] string pwszRelativePath)"
.br
.ti -1c
.RI "\fBInstanceState\fP \fBGetState\fP ()"
.br
.ti -1c
.RI "\fBISetupPackageReference\fP[] \fBGetPackages\fP ()"
.br
.ti -1c
.RI "\fBISetupPackageReference\fP \fBGetProduct\fP ()"
.br
.ti -1c
.RI "string \fBGetProductPath\fP ()"
.br
.ti -1c
.RI "bool \fBIsLaunchable\fP ()"
.br
.ti -1c
.RI "bool \fBIsComplete\fP ()"
.br
.ti -1c
.RI "\fBISetupPropertyStore\fP \fBGetProperties\fP ()"
.br
.ti -1c
.RI "string \fBGetEnginePath\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBFind\-VisualStudio\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.GetDescription ([MarshalAs(UnmanagedType\&.U4), In] int lcid)"

.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.GetDisplayName ([MarshalAs(UnmanagedType\&.U4), In] int lcid)"

.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.GetEnginePath ()"

.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.GetInstallationName ()"

.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.GetInstallationPath ()"

.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.GetInstallationVersion ()"

.SS "System\&.Runtime\&.InteropServices\&.ComTypes\&.FILETIME VisualStudioConfiguration\&.ISetupInstance2\&.GetInstallDate ()"

.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.GetInstanceId ()"

.SS "\fBISetupPackageReference\fP[] VisualStudioConfiguration\&.ISetupInstance2\&.GetPackages ()"

.SS "\fBISetupPackageReference\fP VisualStudioConfiguration\&.ISetupInstance2\&.GetProduct ()"

.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.GetProductPath ()"

.SS "\fBISetupPropertyStore\fP VisualStudioConfiguration\&.ISetupInstance2\&.GetProperties ()"

.SS "\fBInstanceState\fP VisualStudioConfiguration\&.ISetupInstance2\&.GetState ()"

.SS "bool VisualStudioConfiguration\&.ISetupInstance2\&.IsComplete ()"

.SS "bool VisualStudioConfiguration\&.ISetupInstance2\&.IsLaunchable ()"

.SS "string VisualStudioConfiguration\&.ISetupInstance2\&.ResolvePath ([MarshalAs(UnmanagedType\&.LPWStr), In] string pwszRelativePath)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
