.TH "VisualStudioConfiguration.ISetupPackageReference" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.ISetupPackageReference
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetId\fP ()"
.br
.ti -1c
.RI "string \fBGetVersion\fP ()"
.br
.ti -1c
.RI "string \fBGetChip\fP ()"
.br
.ti -1c
.RI "string \fBGetLanguage\fP ()"
.br
.ti -1c
.RI "string \fBGetBranch\fP ()"
.br
.ti -1c
.RI "string \fBGetType\fP ()"
.br
.ti -1c
.RI "string \fBGetUniqueId\fP ()"
.br
.ti -1c
.RI "bool \fBGetIsExtension\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB134\fP of file \fBFind\-VisualStudio\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string VisualStudioConfiguration\&.ISetupPackageReference\&.GetBranch ()"

.SS "string VisualStudioConfiguration\&.ISetupPackageReference\&.GetChip ()"

.SS "string VisualStudioConfiguration\&.ISetupPackageReference\&.GetId ()"

.SS "bool VisualStudioConfiguration\&.ISetupPackageReference\&.GetIsExtension ()"

.SS "string VisualStudioConfiguration\&.ISetupPackageReference\&.GetLanguage ()"

.SS "string VisualStudioConfiguration\&.ISetupPackageReference\&.GetType ()"

.SS "string VisualStudioConfiguration\&.ISetupPackageReference\&.GetUniqueId ()"

.SS "string VisualStudioConfiguration\&.ISetupPackageReference\&.GetVersion ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
