.TH "VisualStudioConfiguration.ISetupInstance" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.ISetupInstance
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBVisualStudioConfiguration\&.ISetupInstance2\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB74\fP of file \fBFind\-VisualStudio\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
