.TH "VisualStudioConfiguration" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIEnumSetupInstances\fP"
.br
.ti -1c
.RI "interface \fBISetupConfiguration\fP"
.br
.ti -1c
.RI "interface \fBISetupConfiguration2\fP"
.br
.ti -1c
.RI "interface \fBISetupInstance\fP"
.br
.ti -1c
.RI "interface \fBISetupInstance2\fP"
.br
.ti -1c
.RI "interface \fBISetupPackageReference\fP"
.br
.ti -1c
.RI "interface \fBISetupPropertyStore\fP"
.br
.ti -1c
.RI "class \fBMain\fP"
.br
.ti -1c
.RI "interface \fBSetupConfiguration\fP"
.br
.ti -1c
.RI "class \fBSetupConfigurationClass\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBInstanceState\fP : uint { \fBNone\fP = 0, \fBLocal\fP = 1, \fBRegistered\fP = 2, \fBNoRebootRequired\fP = 4, \fBNoErrors\fP = 8, \fBComplete\fP = 4294967295 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBVisualStudioConfiguration\&.InstanceState\fP : uint"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fILocal \fP\fP
.TP
\fB\fIRegistered \fP\fP
.TP
\fB\fINoRebootRequired \fP\fP
.TP
\fB\fINoErrors \fP\fP
.TP
\fB\fIComplete \fP\fP
.PP
Definition at line \fB17\fP of file \fBFind\-VisualStudio\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
