.TH "VisualStudioConfiguration.ISetupPropertyStore" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.ISetupPropertyStore
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string[] \fBGetNames\fP ()"
.br
.ti -1c
.RI "object \fBGetValue\fP ([MarshalAs(UnmanagedType\&.LPWStr), In] string pwszName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB165\fP of file \fBFind\-VisualStudio\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string[] VisualStudioConfiguration\&.ISetupPropertyStore\&.GetNames ()"

.SS "object VisualStudioConfiguration\&.ISetupPropertyStore\&.GetValue ([MarshalAs(UnmanagedType\&.LPWStr), In] string pwszName)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
