.TH "VisualStudioConfiguration.ISetupConfiguration" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VisualStudioConfiguration.ISetupConfiguration
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBVisualStudioConfiguration\&.ISetupConfiguration2\fP, and \fBVisualStudioConfiguration\&.SetupConfiguration\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBFind\-VisualStudio\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
