.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/win_tool.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/win_tool.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.win_tool\&.WinTool\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.win_tool\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.win_tool\&.main\fP (args)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgyp\&.win_tool\&.BASE_DIR\fP = os\&.path\&.dirname(os\&.path\&.abspath(__file__))"
.br
.ti -1c
.RI "\fBgyp\&.win_tool\&._LINK_EXE_OUT_ARG\fP = re\&.compile('/OUT:(?P<out>\&.+)$', re\&.IGNORECASE)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
