.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/xcode_ninja.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/xcode_ninja.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.xcode_ninja\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.xcode_ninja\&._WriteWorkspace\fP (main_gyp, sources_gyp, params)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_ninja\&._TargetFromSpec\fP (old_spec, params)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_ninja\&.IsValidTargetForWrapper\fP (target_extras, executable_target_pattern, spec)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_ninja\&.CreateWrapper\fP (target_list, target_dicts, data, params)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
