.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCObject\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCHierarchicalElement\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXGroup\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCFileLikeElement\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCContainerPortal\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCRemoteObject\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXFileReference\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXVariantGroup\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCBuildConfiguration\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCConfigurationList\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXBuildFile\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCBuildPhase\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXHeadersBuildPhase\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXResourcesBuildPhase\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXSourcesBuildPhase\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXFrameworksBuildPhase\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXShellScriptBuildPhase\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXCopyFilesBuildPhase\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXBuildRule\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXContainerItemProxy\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXTargetDependency\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXReferenceProxy\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCTarget\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXNativeTarget\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXAggregateTarget\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.PBXProject\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcodeproj_file\&.XCProjectFile\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.xcodeproj_file\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.xcodeproj_file\&.cmp\fP (x, y)"
.br
.ti -1c
.RI "\fBgyp\&.xcodeproj_file\&.SourceTreeAndPathFromPath\fP (input_path)"
.br
.ti -1c
.RI "\fBgyp\&.xcodeproj_file\&.ConvertVariablesToShellSyntax\fP (input_string)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgyp\&.xcodeproj_file\&._unquoted\fP = re\&.compile('^[A\-Za\-z0\-9$\&./_]+$')"
.br
.ti -1c
.RI "\fBgyp\&.xcodeproj_file\&._quoted\fP = re\&.compile('___')"
.br
.ti -1c
.RI "\fBgyp\&.xcodeproj_file\&._escaped\fP = re\&.compile('[\\\\\\\\']|[\\x00\-\\x1f]')"
.br
.ti -1c
.RI "\fBgyp\&.xcodeproj_file\&._path_leading_variable\fP = re\&.compile(r'^\\$\\((\&.*?)\\)(/(\&.*))?$')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
