.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.xcode_emulation\&.XcodeArchsDefault\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcode_emulation\&.XcodeSettings\fP"
.br
.ti -1c
.RI "class \fBgyp\&.xcode_emulation\&.MacPrefixHeader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.xcode_emulation\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.XcodeArchsVariableMapping\fP (archs, archs_including_64_bit=None)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.GetXcodeArchsDefault\fP ()"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.XcodeVersion\fP ()"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.CLTVersion\fP ()"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.GetStdoutQuiet\fP (cmdlist)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.GetStdout\fP (cmdlist)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.MergeGlobalXcodeSettingsToSpec\fP (global_dict, spec)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.IsMacBundle\fP (flavor, spec)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.GetMacBundleResources\fP (product_dir, xcode_settings, resources)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.GetMacInfoPlist\fP (product_dir, xcode_settings, gyp_path_to_build_path)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&._GetXcodeEnv\fP (xcode_settings, built_products_dir, srcroot, configuration, additional_settings=None)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&._NormalizeEnvVarReferences\fP (str)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.ExpandEnvVars\fP (string, expansions)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&._TopologicallySortedEnvVarKeys\fP (env)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.GetSortedXcodeEnv\fP (xcode_settings, built_products_dir, srcroot, configuration, additional_settings=None)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.GetSpecPostbuildCommands\fP (spec, quiet=False)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&._HasIOSTarget\fP (targets)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&._AddIOSDeviceConfigurations\fP (targets)"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.CloneConfigurationForDeviceAndEmulator\fP (target_dicts)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.XCODE_VERSION_CACHE\fP = None"
.br
.ti -1c
.RI "\fBgyp\&.xcode_emulation\&.XCODE_ARCHS_DEFAULT_CACHE\fP = None"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
