.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.generator\&.xcode\&.XcodeProject\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.generator\&.xcode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.CreateXCConfigurationList\fP (configuration_names)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.AddSourceToTarget\fP (source, type, pbxp, xct)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.AddResourceToTarget\fP (resource, pbxp, xct)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.AddHeaderToTarget\fP (header, pbxp, xct, is_public)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.ExpandXcodeVariables\fP (string, expansions)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.EscapeXcodeDefine\fP (s)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.PerformBuild\fP (data, configurations, params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.CalculateGeneratorInputInfo\fP (params)"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.GenerateOutput\fP (target_list, target_dicts, data, params)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBgyp\&.generator\&.xcode\&._intermediate_var\fP = 'INTERMEDIATE_DIR'"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.xcode\&._shared_intermediate_var\fP = 'SHARED_INTERMEDIATE_DIR'"
.br
.ti -1c
.RI "str \fBgyp\&.generator\&.xcode\&._library_search_paths_var\fP = 'LIBRARY_SEARCH_PATHS'"
.br
.ti -1c
.RI "dict \fBgyp\&.generator\&.xcode\&.generator_default_variables\fP"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.xcode\&.generator_additional_path_sections\fP"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.xcode\&.generator_additional_non_configuration_keys\fP"
.br
.ti -1c
.RI "list \fBgyp\&.generator\&.xcode\&.generator_extra_sources_for_rules\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.generator_filelist_paths\fP = None"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&.xcode_standard_library_dirs\fP"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&._xcode_variable_re\fP = re\&.compile(r'(\\$\\((\&.*?)\\))')"
.br
.ti -1c
.RI "\fBgyp\&.generator\&.xcode\&._xcode_define_re\fP = re\&.compile(r'([\\\\\\'\\' ])')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
