.TH "backend/node_modules/node-gyp/gyp/pylib/gyp/xml_fix.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backend/node_modules/node-gyp/gyp/pylib/gyp/xml_fix.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgyp\&.xml_fix\&.XmlFix\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgyp\fP"
.br
.ti -1c
.RI "namespace \fBgyp\&.xml_fix\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgyp\&.xml_fix\&._Replacement_write_data\fP (writer, data, is_attrib=False)"
.br
.ti -1c
.RI "\fBgyp\&.xml_fix\&._Replacement_writexml\fP (self, writer, indent='', addindent='', newl='')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgyp\&.xml_fix\&.tagName\fP"
.br
.ti -1c
.RI "\fBgyp\&.xml_fix\&.childNodes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
