var searchData=
[
  ['keep_20log_20of_20all_20errors_0',['keep log of all errors',['../md_backend_2node__modules_2finalhandler_2_r_e_a_d_m_e.html#autotoc_md1282',1,'']]],
  ['key_20data_20opts_20promise_20tt_1',['&lt;a name=&quot;put-data&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; cacache.put(cache, key, data, [opts]) -\&gt; Promise&lt;/tt&gt;',['../md_backend_2node__modules_2cacache_2_r_e_a_d_m_e.html#autotoc_md446',1,'']]],
  ['key_20integrity_20opts_20promise_20tt_2',['&lt;a name=&quot;index-insert&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; cacache.index.insert(cache, key, integrity, opts) -\&gt; Promise&lt;/tt&gt;',['../md_backend_2node__modules_2cacache_2_r_e_a_d_m_e.html#autotoc_md464',1,'']]],
  ['key_20matchfn_20opts_20promise_20tt_3',['&lt;a name=&quot;index-compact&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; cacache.index.compact(cache, key, matchFn, [opts]) -\&gt; Promise&lt;/tt&gt;',['../md_backend_2node__modules_2cacache_2_r_e_a_d_m_e.html#autotoc_md463',1,'']]],
  ['key_20opts_20promise_20data_20metadata_20integrity_20tt_4',['&lt;a name=&quot;get-data&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; cacache.get(cache, key, [opts]) -\&gt; Promise({data, metadata, integrity})&lt;/tt&gt;',['../md_backend_2node__modules_2cacache_2_r_e_a_d_m_e.html#autotoc_md432',1,'']]],
  ['key_20opts_20promise_20tt_5',['&lt;a name=&quot;rm-entry&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; cacache.rm.entry(cache, key, [opts]) -\&gt; Promise&lt;/tt&gt;',['../md_backend_2node__modules_2cacache_2_r_e_a_d_m_e.html#autotoc_md459',1,'']]],
  ['key_20opts_20readable_20tt_6',['&lt;a name=&quot;get-stream&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; cacache.get.stream(cache, key, [opts]) -\&gt; Readable&lt;/tt&gt;',['../md_backend_2node__modules_2cacache_2_r_e_a_d_m_e.html#autotoc_md435',1,'']]],
  ['key_20opts_20strictssl_20tt_7',['&lt;a name=&quot;https-opts&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; opts.ca, opts.cert, opts.key, opts.strictSSL&lt;/tt&gt;',['../md_backend_2node__modules_2make-fetch-happen_2_r_e_a_d_m_e.html#autotoc_md1829',1,'']]],
  ['key_20opts_20writable_20tt_8',['&lt;a name=&quot;put-stream&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; cacache.put.stream(cache, key, [opts]) -\&gt; Writable&lt;/tt&gt;',['../md_backend_2node__modules_2cacache_2_r_e_a_d_m_e.html#autotoc_md448',1,'']]],
  ['key_20promise_20tt_9',['&lt;a name=&quot;get-info&quot;&gt;&lt;/a&gt; &lt;tt&gt;\&gt; cacache.get.info(cache, key) -\&gt; Promise&lt;/tt&gt;',['../md_backend_2node__modules_2cacache_2_r_e_a_d_m_e.html#autotoc_md437',1,'']]],
  ['keys_20options_10',['pathToRegexp(path, keys, options)',['../md_backend_2node__modules_2path-to-regexp_2_readme.html#autotoc_md2686',1,'']]],
  ['known_20issues_11',['Known Issues',['../md_backend_2node__modules_2fresh_2_r_e_a_d_m_e.html#autotoc_md1310',1,'']]],
  ['koa_20example_12',['Simple Koa example',['../md_backend_2node__modules_2raw-body_2_r_e_a_d_m_e.html#autotoc_md2947',1,'']]],
  ['kornelski_20http_20cache_20semantics_20img_20src_20https_3a_20travis_20ci_20org_20kornelski_20http_20cache_20semantics_20svg_20branch_20master_20alt_20build_20status_20a_13',['Can I cache this? &lt;a href=&quot;https://travis-ci.org/kornelski/http-cache-semantics&quot; &gt;&lt;img src=&quot;https://travis-ci.org/kornelski/http-cache-semantics.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../md_backend_2node__modules_2http-cache-semantics_2_r_e_a_d_m_e.html',1,'']]],
  ['kornelski_20http_20cache_20semantics_20svg_20branch_20master_20alt_20build_20status_20a_14',['Can I cache this? &lt;a href=&quot;https://travis-ci.org/kornelski/http-cache-semantics&quot; &gt;&lt;img src=&quot;https://travis-ci.org/kornelski/http-cache-semantics.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../md_backend_2node__modules_2http-cache-semantics_2_r_e_a_d_m_e.html',1,'']]]
];
