var dir_bf5813a6dea64b55d2dc1ed2e2021732 =
[
    [ "generator", "dir_fb78602211b7473098c8b6607dcf7044.html", "dir_fb78602211b7473098c8b6607dcf7044" ],
    [ "__init__.py", "____init_____8py.html", "____init_____8py" ],
    [ "common.py", "common_8py.html", "common_8py" ],
    [ "common_test.py", "common__test_8py.html", "common__test_8py" ],
    [ "easy_xml.py", "easy__xml_8py.html", "easy__xml_8py" ],
    [ "easy_xml_test.py", "easy__xml__test_8py.html", "easy__xml__test_8py" ],
    [ "flock_tool.py", "flock__tool_8py.html", "flock__tool_8py" ],
    [ "input.py", "input_8py.html", "input_8py" ],
    [ "input_test.py", "input__test_8py.html", "input__test_8py" ],
    [ "mac_tool.py", "mac__tool_8py.html", "mac__tool_8py" ],
    [ "msvs_emulation.py", "msvs__emulation_8py.html", "msvs__emulation_8py" ],
    [ "MSVSNew.py", "_m_s_v_s_new_8py.html", "_m_s_v_s_new_8py" ],
    [ "MSVSProject.py", "_m_s_v_s_project_8py.html", "_m_s_v_s_project_8py" ],
    [ "MSVSSettings.py", "_m_s_v_s_settings_8py.html", "_m_s_v_s_settings_8py" ],
    [ "MSVSSettings_test.py", "_m_s_v_s_settings__test_8py.html", "_m_s_v_s_settings__test_8py" ],
    [ "MSVSToolFile.py", "_m_s_v_s_tool_file_8py.html", "_m_s_v_s_tool_file_8py" ],
    [ "MSVSUserFile.py", "_m_s_v_s_user_file_8py.html", "_m_s_v_s_user_file_8py" ],
    [ "MSVSUtil.py", "_m_s_v_s_util_8py.html", "_m_s_v_s_util_8py" ],
    [ "MSVSVersion.py", "_m_s_v_s_version_8py.html", "_m_s_v_s_version_8py" ],
    [ "ninja_syntax.py", "ninja__syntax_8py.html", "ninja__syntax_8py" ],
    [ "simple_copy.py", "simple__copy_8py.html", "simple__copy_8py" ],
    [ "win_tool.py", "win__tool_8py.html", "win__tool_8py" ],
    [ "xcode_emulation.py", "xcode__emulation_8py.html", "xcode__emulation_8py" ],
    [ "xcode_ninja.py", "xcode__ninja_8py.html", "xcode__ninja_8py" ],
    [ "xcodeproj_file.py", "xcodeproj__file_8py.html", "xcodeproj__file_8py" ],
    [ "xml_fix.py", "xml__fix_8py.html", "xml__fix_8py" ]
];