var namespacegyp_1_1xcodeproj__file =
[
    [ "PBXAggregateTarget", "classgyp_1_1xcodeproj__file_1_1_p_b_x_aggregate_target.html", null ],
    [ "PBXBuildFile", "classgyp_1_1xcodeproj__file_1_1_p_b_x_build_file.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_build_file" ],
    [ "PBXBuildRule", "classgyp_1_1xcodeproj__file_1_1_p_b_x_build_rule.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_build_rule" ],
    [ "PBXContainerItemProxy", "classgyp_1_1xcodeproj__file_1_1_p_b_x_container_item_proxy.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_container_item_proxy" ],
    [ "PBXCopyFilesBuildPhase", "classgyp_1_1xcodeproj__file_1_1_p_b_x_copy_files_build_phase.html", null ],
    [ "PBXFileReference", "classgyp_1_1xcodeproj__file_1_1_p_b_x_file_reference.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_file_reference" ],
    [ "PBXFrameworksBuildPhase", "classgyp_1_1xcodeproj__file_1_1_p_b_x_frameworks_build_phase.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_frameworks_build_phase" ],
    [ "PBXGroup", "classgyp_1_1xcodeproj__file_1_1_p_b_x_group.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_group" ],
    [ "PBXHeadersBuildPhase", "classgyp_1_1xcodeproj__file_1_1_p_b_x_headers_build_phase.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_headers_build_phase" ],
    [ "PBXNativeTarget", "classgyp_1_1xcodeproj__file_1_1_p_b_x_native_target.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_native_target" ],
    [ "PBXProject", "classgyp_1_1xcodeproj__file_1_1_p_b_x_project.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_project" ],
    [ "PBXReferenceProxy", "classgyp_1_1xcodeproj__file_1_1_p_b_x_reference_proxy.html", null ],
    [ "PBXResourcesBuildPhase", "classgyp_1_1xcodeproj__file_1_1_p_b_x_resources_build_phase.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_resources_build_phase" ],
    [ "PBXShellScriptBuildPhase", "classgyp_1_1xcodeproj__file_1_1_p_b_x_shell_script_build_phase.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_shell_script_build_phase" ],
    [ "PBXSourcesBuildPhase", "classgyp_1_1xcodeproj__file_1_1_p_b_x_sources_build_phase.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_sources_build_phase" ],
    [ "PBXTargetDependency", "classgyp_1_1xcodeproj__file_1_1_p_b_x_target_dependency.html", "classgyp_1_1xcodeproj__file_1_1_p_b_x_target_dependency" ],
    [ "PBXVariantGroup", "classgyp_1_1xcodeproj__file_1_1_p_b_x_variant_group.html", null ],
    [ "XCBuildConfiguration", "classgyp_1_1xcodeproj__file_1_1_x_c_build_configuration.html", "classgyp_1_1xcodeproj__file_1_1_x_c_build_configuration" ],
    [ "XCBuildPhase", "classgyp_1_1xcodeproj__file_1_1_x_c_build_phase.html", "classgyp_1_1xcodeproj__file_1_1_x_c_build_phase" ],
    [ "XCConfigurationList", "classgyp_1_1xcodeproj__file_1_1_x_c_configuration_list.html", "classgyp_1_1xcodeproj__file_1_1_x_c_configuration_list" ],
    [ "XCContainerPortal", "classgyp_1_1xcodeproj__file_1_1_x_c_container_portal.html", null ],
    [ "XCFileLikeElement", "classgyp_1_1xcodeproj__file_1_1_x_c_file_like_element.html", "classgyp_1_1xcodeproj__file_1_1_x_c_file_like_element" ],
    [ "XCHierarchicalElement", "classgyp_1_1xcodeproj__file_1_1_x_c_hierarchical_element.html", "classgyp_1_1xcodeproj__file_1_1_x_c_hierarchical_element" ],
    [ "XCObject", "classgyp_1_1xcodeproj__file_1_1_x_c_object.html", "classgyp_1_1xcodeproj__file_1_1_x_c_object" ],
    [ "XCProjectFile", "classgyp_1_1xcodeproj__file_1_1_x_c_project_file.html", "classgyp_1_1xcodeproj__file_1_1_x_c_project_file" ],
    [ "XCRemoteObject", "classgyp_1_1xcodeproj__file_1_1_x_c_remote_object.html", null ],
    [ "XCTarget", "classgyp_1_1xcodeproj__file_1_1_x_c_target.html", "classgyp_1_1xcodeproj__file_1_1_x_c_target" ],
    [ "cmp", "namespacegyp_1_1xcodeproj__file.html#a9ec6d6e81c4bf8025f5ba0ec688e1767", null ],
    [ "ConvertVariablesToShellSyntax", "namespacegyp_1_1xcodeproj__file.html#a3948b5389e8d7f62e6812b6af839de4f", null ],
    [ "SourceTreeAndPathFromPath", "namespacegyp_1_1xcodeproj__file.html#ae15a785ea8a9cba9ad1ad479029e508b", null ],
    [ "_escaped", "namespacegyp_1_1xcodeproj__file.html#a4d8a14634b0cbda539003cf4c56eb965", null ],
    [ "_path_leading_variable", "namespacegyp_1_1xcodeproj__file.html#ac0afa7a210531d7eaabfa4538173967e", null ],
    [ "_quoted", "namespacegyp_1_1xcodeproj__file.html#af4c8ddfcc3498b61603cd810a6146e8a", null ],
    [ "_unquoted", "namespacegyp_1_1xcodeproj__file.html#af9c77bb03944824e89bca2059b28df4e", null ]
];